import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.1",
  passingScore: 75,
  questions: [
    {
      id: "1.1.1",
      question: {
        en: "When does the Article 23 reporting clock start?",
        de: "Wann startet die Meldekette nach Artikel 23?",
        fr: "Quand le délai de notification de l'article 23 commence-t-il à courir ?",
        it: "Quando inizia a decorrere il termine di notifica dell'articolo 23?",
        es: "¿Cuándo empieza a contar el plazo de notificación del artículo 23?",
        pl: "Kiedy zaczyna biec termin zgłoszenia z artykułu 23?",
        cs: "Kdy začíná běžet lhůta pro ohlášení podle článku 23?",
        pt: "Quando começa a correr o prazo de notificação do artigo 23?",
        ro: "Când începe să curgă termenul de notificare prevăzut la articolul 23?",
      },
      options: [
        { en: "When the SIEM raises an alert", de: "Wenn das SIEM einen Alarm auslöst", fr: "Lorsque le SIEM déclenche une alerte", it: "Quando il SIEM genera un allarme", es: "Cuando el SIEM genera una alerta", pl: "Gdy SIEM generuje alert", cs: "Když SIEM vyvolá výstrahu", pt: "Quando o SIEM gera um alerta", ro: "Când SIEM generează o alertă" },
        { en: "When a responsible person becomes aware enough to assess the incident as significant", de: "Wenn eine verantwortliche Person Kenntnis erlangt und den Vorfall als erheblich einstufen kann", fr: "Lorsqu'une personne responsable a connaissance de l'incident au point de pouvoir l'évaluer comme important", it: "Quando una persona responsabile ne viene a conoscenza al punto da poter valutare l'incidente come significativo", es: "Cuando una persona responsable tiene conocimiento suficiente para evaluar el incidente como significativo", pl: "Gdy osoba odpowiedzialna uzyska wiedzę wystarczającą, aby ocenić incydent jako istotny", cs: "Když odpovědná osoba získá dostatek informací, aby mohla incident posoudit jako významný", pt: "Quando uma pessoa responsável toma conhecimento o suficiente para avaliar o incidente como significativo", ro: "Când o persoană responsabilă ia cunoștință în măsura suficientă pentru a evalua incidentul ca fiind semnificativ" },
        { en: "When the IT manager begins forensic triage", de: "Wenn die IT-Verantwortliche die forensische Erstanalyse beginnt", fr: "Lorsque le responsable informatique entame le triage forensique", it: "Quando il responsabile IT avvia il triage forense", es: "Cuando el responsable de TI inicia el triaje forense", pl: "Gdy menedżer IT rozpoczyna wstępną analizę kryminalistyczną", cs: "Když vedoucí IT zahájí forenzní třídění", pt: "Quando o responsável de TI inicia a triagem forense", ro: "Când managerul IT începe trierea criminalistică" },
        { en: "When the CSIRT acknowledges the early warning", de: "Wenn das CSIRT die Frühwarnung bestätigt", fr: "Lorsque le CSIRT accuse réception de l'alerte précoce", it: "Quando il CSIRT conferma il preallarme", es: "Cuando el CSIRT confirma la alerta temprana", pl: "Gdy CSIRT potwierdzi wczesne ostrzeżenie", cs: "Když CSIRT potvrdí přijetí včasného varování", pt: "Quando o CSIRT confirma a receção do alerta antecipado", ro: "Când CSIRT confirmă primirea avertizării timpurii" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 23(4)(a) NIS 2 uses 'becoming aware,' not detection. Awareness is the moment a responsible person knows enough to assess significance.",
        de: "Artikel 23(4)(a) NIS 2 spricht von Kenntniserlangung, nicht von Detektion. Kenntniserlangung ist der Moment, in dem eine verantwortliche Person genug weiß, um die Erheblichkeit zu beurteilen.",
        fr: "L'article 23(4)(a) NIS 2 emploie « avoir connaissance », et non la détection. La connaissance est le moment où une personne responsable en sait assez pour évaluer le caractère important.",
        it: "L'articolo 23(4)(a) NIS 2 parla di « venire a conoscenza », non di rilevamento. La conoscenza è il momento in cui una persona responsabile sa abbastanza da valutare la significatività.",
        es: "El artículo 23(4)(a) NIS 2 emplea « tener conocimiento », no la detección. El conocimiento es el momento en que una persona responsable sabe lo suficiente para evaluar la significatividad.",
        pl: "Artykuł 23(4)(a) NIS 2 mówi o « powzięciu wiedzy », a nie o wykryciu. Powzięcie wiedzy to moment, w którym osoba odpowiedzialna wie wystarczająco dużo, aby ocenić istotność.",
        cs: "Článek 23(4)(a) NIS 2 hovoří o « získání informací », nikoli o detekci. Získání informací je okamžik, kdy odpovědná osoba ví dost na to, aby posoudila významnost.",
        pt: "O artigo 23(4)(a) NIS 2 fala de « tomada de conhecimento », não de deteção. A tomada de conhecimento é o momento em que uma pessoa responsável sabe o suficiente para avaliar a significância.",
        ro: "Articolul 23(4)(a) NIS 2 se referă la « luarea la cunoștință », nu la detectare. Luarea la cunoștință este momentul în care o persoană responsabilă știe suficient pentru a evalua caracterul semnificativ.",
      },
    },
    {
      id: "1.1.2",
      question: {
        en: "Within how many hours of becoming aware must the early warning reach the CSIRT?",
        de: "Innerhalb welcher Frist nach Kenntniserlangung muss die Frühwarnung beim CSIRT eingehen?",
        fr: "Dans combien d'heures après en avoir eu connaissance l'alerte précoce doit-elle parvenir au CSIRT ?",
        it: "Entro quante ore dal momento in cui se ne è venuti a conoscenza il preallarme deve pervenire al CSIRT?",
        es: "¿Dentro de cuántas horas desde que se tiene conocimiento debe llegar la alerta temprana al CSIRT?",
        pl: "W ciągu ilu godzin od powzięcia wiedzy wczesne ostrzeżenie musi dotrzeć do CSIRT?",
        cs: "Do kolika hodin od získání informací musí včasné varování dorazit k CSIRT?",
        pt: "Dentro de quantas horas após tomar conhecimento deve o alerta antecipado chegar ao CSIRT?",
        ro: "În câte ore de la luarea la cunoștință trebuie să ajungă avertizarea timpurie la CSIRT?",
      },
      options: [
        { en: "6 hours", de: "6 Stunden", fr: "6 heures", it: "6 ore", es: "6 horas", pl: "6 godzin", cs: "6 hodin", pt: "6 horas", ro: "6 ore" },
        { en: "12 hours", de: "12 Stunden", fr: "12 heures", it: "12 ore", es: "12 horas", pl: "12 godzin", cs: "12 hodin", pt: "12 horas", ro: "12 ore" },
        { en: "24 hours", de: "24 Stunden", fr: "24 heures", it: "24 ore", es: "24 horas", pl: "24 godziny", cs: "24 hodin", pt: "24 horas", ro: "24 de ore" },
        { en: "72 hours", de: "72 Stunden", fr: "72 heures", it: "72 ore", es: "72 horas", pl: "72 godziny", cs: "72 hodin", pt: "72 horas", ro: "72 de ore" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Article 23(4)(a) NIS 2 requires the early warning within 24 hours of becoming aware.",
        de: "Artikel 23(4)(a) NIS 2 verlangt die Frühwarnung innerhalb von 24 Stunden nach Kenntniserlangung.",
        fr: "L'article 23(4)(a) NIS 2 exige l'alerte précoce dans les 24 heures suivant la prise de connaissance.",
        it: "L'articolo 23(4)(a) NIS 2 richiede il preallarme entro 24 ore dal momento in cui se ne è venuti a conoscenza.",
        es: "El artículo 23(4)(a) NIS 2 exige la alerta temprana dentro de las 24 horas siguientes a tener conocimiento.",
        pl: "Artykuł 23(4)(a) NIS 2 wymaga wczesnego ostrzeżenia w ciągu 24 godzin od powzięcia wiedzy.",
        cs: "Článek 23(4)(a) NIS 2 vyžaduje včasné varování do 24 hodin od získání informací.",
        pt: "O artigo 23(4)(a) NIS 2 exige o alerta antecipado dentro de 24 horas após a tomada de conhecimento.",
        ro: "Articolul 23(4)(a) NIS 2 impune avertizarea timpurie în termen de 24 de ore de la luarea la cunoștință.",
      },
    },
    {
      id: "1.1.3",
      question: {
        en: "What is the deadline for the formal incident notification under Article 23(4)(b)?",
        de: "Wie lautet die Frist für die formelle Vorfallsmeldung nach Artikel 23(4)(b)?",
        fr: "Quel est le délai de la notification formelle d'incident au titre de l'article 23(4)(b) ?",
        it: "Qual è il termine per la notifica formale dell'incidente ai sensi dell'articolo 23(4)(b)?",
        es: "¿Cuál es el plazo para la notificación formal del incidente conforme al artículo 23(4)(b)?",
        pl: "Jaki jest termin formalnego zgłoszenia incydentu zgodnie z artykułem 23(4)(b)?",
        cs: "Jaká je lhůta pro formální oznámení incidentu podle článku 23(4)(b)?",
        pt: "Qual é o prazo para a notificação formal do incidente nos termos do artigo 23(4)(b)?",
        ro: "Care este termenul pentru notificarea formală a incidentului în temeiul articolului 23(4)(b)?",
      },
      options: [
        { en: "24 hours", de: "24 Stunden", fr: "24 heures", it: "24 ore", es: "24 horas", pl: "24 godziny", cs: "24 hodin", pt: "24 horas", ro: "24 de ore" },
        { en: "72 hours", de: "72 Stunden", fr: "72 heures", it: "72 ore", es: "72 horas", pl: "72 godziny", cs: "72 hodin", pt: "72 horas", ro: "72 de ore" },
        { en: "One week", de: "Eine Woche", fr: "Une semaine", it: "Una settimana", es: "Una semana", pl: "Jeden tydzień", cs: "Jeden týden", pt: "Uma semana", ro: "O săptămână" },
        { en: "One month", de: "Ein Monat", fr: "Un mois", it: "Un mese", es: "Un mes", pl: "Jeden miesiąc", cs: "Jeden měsíc", pt: "Um mês", ro: "O lună" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 23(4)(b) NIS 2 sets the incident notification deadline at 72 hours of becoming aware.",
        de: "Artikel 23(4)(b) NIS 2 legt die Frist für die Vorfallsmeldung auf 72 Stunden ab Kenntniserlangung fest.",
        fr: "L'article 23(4)(b) NIS 2 fixe le délai de notification d'incident à 72 heures à compter de la prise de connaissance.",
        it: "L'articolo 23(4)(b) NIS 2 fissa il termine per la notifica dell'incidente a 72 ore dal momento in cui se ne è venuti a conoscenza.",
        es: "El artículo 23(4)(b) NIS 2 fija el plazo de notificación del incidente en 72 horas desde que se tiene conocimiento.",
        pl: "Artykuł 23(4)(b) NIS 2 ustala termin zgłoszenia incydentu na 72 godziny od powzięcia wiedzy.",
        cs: "Článek 23(4)(b) NIS 2 stanoví lhůtu pro oznámení incidentu na 72 hodin od získání informací.",
        pt: "O artigo 23(4)(b) NIS 2 fixa o prazo de notificação do incidente em 72 horas após a tomada de conhecimento.",
        ro: "Articolul 23(4)(b) NIS 2 stabilește termenul de notificare a incidentului la 72 de ore de la luarea la cunoștință.",
      },
    },
    {
      id: "1.1.4",
      question: {
        en: "By when is the final report due?",
        de: "Bis wann ist der Abschlussbericht fällig?",
        fr: "Pour quand le rapport final est-il dû ?",
        it: "Entro quando è dovuta la relazione finale?",
        es: "¿Para cuándo debe presentarse el informe final?",
        pl: "Do kiedy należy złożyć raport końcowy?",
        cs: "Do kdy je třeba předložit závěrečnou zprávu?",
        pt: "Até quando deve ser apresentado o relatório final?",
        ro: "Până când trebuie depus raportul final?",
      },
      options: [
        { en: "72 hours after the early warning", de: "72 Stunden nach der Frühwarnung", fr: "72 heures après l'alerte précoce", it: "72 ore dopo il preallarme", es: "72 horas después de la alerta temprana", pl: "72 godziny po wczesnym ostrzeżeniu", cs: "72 hodin po včasném varování", pt: "72 horas após o alerta antecipado", ro: "72 de ore după avertizarea timpurie" },
        { en: "One week after the incident notification", de: "Eine Woche nach der Vorfallsmeldung", fr: "Une semaine après la notification d'incident", it: "Una settimana dopo la notifica dell'incidente", es: "Una semana después de la notificación del incidente", pl: "Jeden tydzień po zgłoszeniu incydentu", cs: "Jeden týden po oznámení incidentu", pt: "Uma semana após a notificação do incidente", ro: "O săptămână după notificarea incidentului" },
        { en: "One month after the incident notification", de: "Ein Monat nach der Vorfallsmeldung", fr: "Un mois après la notification d'incident", it: "Un mese dopo la notifica dell'incidente", es: "Un mes después de la notificación del incidente", pl: "Jeden miesiąc po zgłoszeniu incydentu", cs: "Jeden měsíc po oznámení incidentu", pt: "Um mês após a notificação do incidente", ro: "O lună după notificarea incidentului" },
        { en: "Three months after the incident notification", de: "Drei Monate nach der Vorfallsmeldung", fr: "Trois mois après la notification d'incident", it: "Tre mesi dopo la notifica dell'incidente", es: "Tres meses después de la notificación del incidente", pl: "Trzy miesiące po zgłoszeniu incydentu", cs: "Tři měsíce po oznámení incidentu", pt: "Três meses após a notificação do incidente", ro: "Trei luni după notificarea incidentului" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Article 23(4)(d) NIS 2 requires the final report within one month of the incident notification.",
        de: "Artikel 23(4)(d) NIS 2 verlangt den Abschlussbericht innerhalb eines Monats nach der Vorfallsmeldung.",
        fr: "L'article 23(4)(d) NIS 2 exige le rapport final dans un délai d'un mois à compter de la notification d'incident.",
        it: "L'articolo 23(4)(d) NIS 2 richiede la relazione finale entro un mese dalla notifica dell'incidente.",
        es: "El artículo 23(4)(d) NIS 2 exige el informe final dentro de un mes desde la notificación del incidente.",
        pl: "Artykuł 23(4)(d) NIS 2 wymaga raportu końcowego w ciągu jednego miesiąca od zgłoszenia incydentu.",
        cs: "Článek 23(4)(d) NIS 2 vyžaduje závěrečnou zprávu do jednoho měsíce od oznámení incidentu.",
        pt: "O artigo 23(4)(d) NIS 2 exige o relatório final dentro de um mês após a notificação do incidente.",
        ro: "Articolul 23(4)(d) NIS 2 impune raportul final în termen de o lună de la notificarea incidentului.",
      },
    },
    {
      id: "1.1.5",
      question: {
        en: "How does the customer notification duty under Article 23(2) relate to the CSIRT cascade?",
        de: "In welchem Verhältnis steht die Kundenbenachrichtigungs-Pflicht nach Artikel 23(2) zur Meldekette ans CSIRT?",
        fr: "Quel est le rapport entre l'obligation de notification des clients au titre de l'article 23(2) et la chaîne de notification au CSIRT ?",
        it: "Che rapporto ha l'obbligo di notifica ai clienti ai sensi dell'articolo 23(2) con la catena di notifica al CSIRT?",
        es: "¿Qué relación tiene el deber de notificación a los clientes conforme al artículo 23(2) con la cadena de notificación al CSIRT?",
        pl: "W jakim stosunku pozostaje obowiązek powiadomienia klientów na podstawie artykułu 23(2) do łańcucha zgłoszeń do CSIRT?",
        cs: "V jakém vztahu je povinnost informovat zákazníky podle článku 23(2) k řetězci ohlašování CSIRT?",
        pt: "Qual é a relação entre o dever de notificar os clientes nos termos do artigo 23(2) e a cadeia de notificação ao CSIRT?",
        ro: "Care este relația dintre obligația de notificare a clienților prevăzută la articolul 23(2) și lanțul de notificare către CSIRT?",
      },
      options: [
        { en: "It is part of the same cascade and runs on the same clock", de: "Sie ist Teil derselben Meldekette und folgt derselben Uhr", fr: "Elle fait partie de la même chaîne et suit le même délai", it: "Fa parte della stessa catena e segue lo stesso termine", es: "Forma parte de la misma cadena y se rige por el mismo plazo", pl: "Jest częścią tego samego łańcucha i biegnie według tego samego terminu", cs: "Je součástí téhož řetězce a běží podle téže lhůty", pt: "Faz parte da mesma cadeia e corre segundo o mesmo prazo", ro: "Face parte din același lanț și curge după același termen" },
        { en: "It is a separate, parallel duty with its own clock and recipients", de: "Sie ist eine eigenständige, parallele Pflicht mit eigener Uhr und eigenem Empfängerkreis", fr: "Il s'agit d'une obligation distincte et parallèle, avec son propre délai et ses propres destinataires", it: "È un obbligo distinto e parallelo, con un proprio termine e propri destinatari", es: "Es un deber separado y paralelo, con su propio plazo y sus propios destinatarios", pl: "Jest to odrębny, równoległy obowiązek z własnym terminem i własnym kręgiem odbiorców", cs: "Jde o samostatnou, souběžnou povinnost s vlastní lhůtou a vlastními příjemci", pt: "É um dever separado e paralelo, com o seu próprio prazo e os seus próprios destinatários", ro: "Este o obligație distinctă și paralelă, cu propriul termen și proprii destinatari" },
        { en: "It is only triggered after the one-month final report", de: "Sie wird erst nach dem Abschlussbericht nach einem Monat ausgelöst", fr: "Elle n'est déclenchée qu'après le rapport final établi au bout d'un mois", it: "Scatta solo dopo la relazione finale prevista a un mese", es: "Solo se activa después del informe final al cabo de un mes", pl: "Jest uruchamiany dopiero po raporcie końcowym sporządzanym po miesiącu", cs: "Vzniká až po závěrečné zprávě po jednom měsíci", pt: "Só é desencadeado após o relatório final ao fim de um mês", ro: "Se declanșează abia după raportul final întocmit la o lună" },
        { en: "It only applies when personal data is involved", de: "Sie greift nur, wenn personenbezogene Daten betroffen sind", fr: "Elle ne s'applique que lorsque des données à caractère personnel sont concernées", it: "Si applica solo quando sono coinvolti dati personali", es: "Solo se aplica cuando hay datos personales implicados", pl: "Ma zastosowanie tylko wtedy, gdy w grę wchodzą dane osobowe", cs: "Uplatní se pouze tehdy, jsou-li dotčeny osobní údaje", pt: "Só se aplica quando estão envolvidos dados pessoais", ro: "Se aplică numai atunci când sunt implicate date cu caracter personal" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 23(2) NIS 2 is a separate, parallel duty. It runs on its own clock and has its own recipients: the users of the entity's services.",
        de: "Artikel 23(2) NIS 2 ist eine eigenständige, parallele Pflicht. Sie folgt einer eigenen Uhr und hat einen eigenen Empfängerkreis: die Nutzer der Dienste der Einrichtung.",
        fr: "L'article 23(2) NIS 2 est une obligation distincte et parallèle. Elle suit son propre délai et a ses propres destinataires : les utilisateurs des services de l'entité.",
        it: "L'articolo 23(2) NIS 2 è un obbligo distinto e parallelo. Segue un proprio termine e ha propri destinatari: gli utenti dei servizi del soggetto.",
        es: "El artículo 23(2) NIS 2 es un deber separado y paralelo. Se rige por su propio plazo y tiene sus propios destinatarios: los usuarios de los servicios de la entidad.",
        pl: "Artykuł 23(2) NIS 2 to odrębny, równoległy obowiązek. Biegnie według własnego terminu i ma własny krąg odbiorców: użytkowników usług podmiotu.",
        cs: "Článek 23(2) NIS 2 je samostatná, souběžná povinnost. Běží podle vlastní lhůty a má vlastní okruh příjemců: uživatele služeb subjektu.",
        pt: "O artigo 23(2) NIS 2 é um dever separado e paralelo. Corre segundo o seu próprio prazo e tem os seus próprios destinatários: os utilizadores dos serviços da entidade.",
        ro: "Articolul 23(2) NIS 2 este o obligație distinctă și paralelă. Curge după propriul termen și are propriul cerc de destinatari: utilizatorii serviciilor entității.",
      },
    },
  ],
});

export default quiz;
