import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.2",
  passingScore: 75,
  questions: [
    {
      id: "1.2.1",
      question: {
        en: "Why must the management body physically participate in the tabletop?",
        de: "Warum muss die Geschäftsleitung persönlich an der Tabletop-Übung teilnehmen?",
        fr: "Pourquoi l'organe de direction doit-il participer physiquement à l'exercice sur table ?",
        it: "Perché l'organo di gestione deve partecipare fisicamente all'esercitazione da tavolo?",
        es: "¿Por qué debe el órgano de dirección participar físicamente en el ejercicio de mesa?",
        pl: "Dlaczego organ zarządzający musi fizycznie uczestniczyć w ćwiczeniu sztabowym?",
        cs: "Proč se musí vedení (řídicí orgán) fyzicky účastnit štábního cvičení?",
        pt: "Por que motivo deve o órgão de direção participar fisicamente no exercício de mesa?",
        ro: "De ce trebuie organul de conducere să participe fizic la exercițiul pe hârtie?",
      },
      options: [
        { en: "Because Article 20(1) NIS 2 makes the management body personally responsible, and an exercise without them cannot evidence oversight", de: "Weil Artikel 20(1) NIS 2 die Geschäftsleitung persönlich verantwortlich macht und eine Übung ohne sie die Aufsicht nicht nachweisen kann", fr: "Parce que l'article 20(1) NIS 2 rend l'organe de direction personnellement responsable, et qu'un exercice sans lui ne peut attester de la surveillance", it: "Perché l'articolo 20(1) NIS 2 rende l'organo di gestione personalmente responsabile e un'esercitazione senza di esso non può dimostrare la vigilanza", es: "Porque el artículo 20(1) NIS 2 hace al órgano de dirección personalmente responsable, y un ejercicio sin él no puede acreditar la supervisión", pl: "Ponieważ artykuł 20(1) NIS 2 czyni organ zarządzający osobiście odpowiedzialnym, a ćwiczenie bez niego nie może dowieść nadzoru", cs: "Protože článek 20(1) NIS 2 činí řídicí orgán osobně odpovědným a cvičení bez něj nemůže prokázat dohled", pt: "Porque o artigo 20(1) NIS 2 torna o órgão de direção pessoalmente responsável e um exercício sem ele não pode comprovar a supervisão", ro: "Pentru că articolul 20(1) NIS 2 face organul de conducere personal responsabil, iar un exercițiu fără el nu poate dovedi supravegherea" },
        { en: "Because the BSI requires it under Standard 200-4", de: "Weil das BSI es im Standard 200-4 verlangt", fr: "Parce que le BSI l'exige au titre du Standard 200-4", it: "Perché il BSI lo richiede nello Standard 200-4", es: "Porque el BSI lo exige en el Standard 200-4", pl: "Ponieważ BSI wymaga tego w Standard 200-4", cs: "Protože to BSI vyžaduje ve Standardu 200-4", pt: "Porque o BSI o exige no Standard 200-4", ro: "Pentru că BSI impune acest lucru în Standard 200-4" },
        { en: "Because the cyber insurance policy requires it", de: "Weil die Cyber-Versicherungs-Police es verlangt", fr: "Parce que la police d'assurance cyber l'exige", it: "Perché la polizza di assicurazione cyber lo richiede", es: "Porque la póliza de ciberseguro lo exige", pl: "Ponieważ wymaga tego polisa ubezpieczenia cybernetycznego", cs: "Protože to vyžaduje pojistná smlouva kybernetického pojištění", pt: "Porque a apólice de ciberseguro o exige", ro: "Pentru că polița de asigurare cibernetică impune acest lucru" },
        { en: "Because the auditor will refuse to sign the report otherwise", de: "Weil das Audit sonst die Freigabe des Berichts verweigert", fr: "Parce que sinon l'auditeur refusera de signer le rapport", it: "Perché altrimenti l'auditor rifiuterà di firmare la relazione", es: "Porque de lo contrario el auditor se negará a firmar el informe", pl: "Ponieważ w przeciwnym razie audytor odmówi podpisania raportu", cs: "Protože jinak auditor odmítne zprávu podepsat", pt: "Porque, caso contrário, o auditor recusar-se-á a assinar o relatório", ro: "Pentru că altfel auditorul va refuza să semneze raportul" },
      ],
      correctIndex: 0,
      explanation: {
        en: "Article 20(1) NIS 2 makes the management body personally responsible. The exercise must rehearse the decisions the responsible person would make.",
        de: "Artikel 20(1) NIS 2 macht die Geschäftsleitung persönlich verantwortlich. Die Übung muss die Entscheidungen durchspielen, die die verantwortliche Person treffen würde.",
        fr: "L'article 20(1) NIS 2 rend l'organe de direction personnellement responsable. L'exercice doit répéter les décisions que la personne responsable prendrait.",
        it: "L'articolo 20(1) NIS 2 rende l'organo di gestione personalmente responsabile. L'esercitazione deve simulare le decisioni che la persona responsabile prenderebbe.",
        es: "El artículo 20(1) NIS 2 hace al órgano de dirección personalmente responsable. El ejercicio debe ensayar las decisiones que tomaría la persona responsable.",
        pl: "Artykuł 20(1) NIS 2 czyni organ zarządzający osobiście odpowiedzialnym. Ćwiczenie musi przećwiczyć decyzje, które podjęłaby osoba odpowiedzialna.",
        cs: "Článek 20(1) NIS 2 činí řídicí orgán osobně odpovědným. Cvičení musí nacvičit rozhodnutí, která by odpovědná osoba učinila.",
        pt: "O artigo 20(1) NIS 2 torna o órgão de direção pessoalmente responsável. O exercício deve ensaiar as decisões que a pessoa responsável tomaria.",
        ro: "Articolul 20(1) NIS 2 face organul de conducere personal responsabil. Exercițiul trebuie să repete deciziile pe care le-ar lua persoana responsabilă.",
      },
    },
    {
      id: "1.2.2",
      question: {
        en: "Which of the following is NOT a mandatory role in a tabletop?",
        de: "Welche der folgenden Rollen ist KEINE Pflichtrolle bei einer Tabletop-Übung?",
        fr: "Lequel des rôles suivants n'est PAS un rôle obligatoire dans un exercice sur table ?",
        it: "Quale dei seguenti NON è un ruolo obbligatorio in un'esercitazione da tavolo?",
        es: "¿Cuál de los siguientes NO es un rol obligatorio en un ejercicio de mesa?",
        pl: "Która z poniższych ról NIE jest rolą obowiązkową w ćwiczeniu sztabowym?",
        cs: "Která z následujících rolí NENÍ povinnou rolí ve štábním cvičení?",
        pt: "Qual das seguintes funções NÃO é uma função obrigatória num exercício de mesa?",
        ro: "Care dintre următoarele roluri NU este un rol obligatoriu într-un exercițiu pe hârtie?",
      },
      options: [
        { en: "Management body representative", de: "Vertretung der Geschäftsleitung", fr: "Représentant de l'organe de direction", it: "Rappresentante dell'organo di gestione", es: "Representante del órgano de dirección", pl: "Przedstawiciel organu zarządzającego", cs: "Zástupce řídicího orgánu", pt: "Representante do órgão de direção", ro: "Reprezentantul organului de conducere" },
        { en: "IT manager", de: "IT-Verantwortliche", fr: "Responsable informatique", it: "Responsabile IT", es: "Responsable de TI", pl: "Menedżer IT", cs: "Vedoucí IT", pt: "Responsável de TI", ro: "Manager IT" },
        { en: "Communications lead", de: "Kommunikations-Verantwortliche", fr: "Responsable de la communication", it: "Responsabile della comunicazione", es: "Responsable de comunicación", pl: "Osoba odpowiedzialna za komunikację", cs: "Vedoucí komunikace", pt: "Responsável de comunicação", ro: "Responsabilul de comunicare" },
        { en: "External cyber insurance contact", de: "Externer Cyber-Versicherungs-Kontakt", fr: "Contact externe d'assurance cyber", it: "Contatto esterno per l'assicurazione cyber", es: "Contacto externo de ciberseguro", pl: "Zewnętrzny kontakt ds. ubezpieczenia cybernetycznego", cs: "Externí kontakt pro kybernetické pojištění", pt: "Contacto externo de ciberseguro", ro: "Contactul extern pentru asigurarea cibernetică" },
      ],
      correctIndex: 3,
      explanation: {
        en: "The cyber insurance contact is strongly recommended but not mandatory. The four mandatory roles are management body, facilitator, IT manager, and communications or legal lead.",
        de: "Der Cyber-Versicherungs-Kontakt ist dringend empfohlen, aber nicht verpflichtend. Die vier Pflichtrollen sind Geschäftsleitung, Moderation, IT-Verantwortliche und Kommunikations- oder Rechts-Verantwortliche.",
        fr: "Le contact d'assurance cyber est fortement recommandé mais non obligatoire. Les quatre rôles obligatoires sont l'organe de direction, l'animateur, le responsable informatique et le responsable de la communication ou des affaires juridiques.",
        it: "Il contatto per l'assicurazione cyber è vivamente consigliato ma non obbligatorio. I quattro ruoli obbligatori sono l'organo di gestione, il facilitatore, il responsabile IT e il responsabile della comunicazione o legale.",
        es: "El contacto de ciberseguro es muy recomendable pero no obligatorio. Los cuatro roles obligatorios son el órgano de dirección, el facilitador, el responsable de TI y el responsable de comunicación o jurídico.",
        pl: "Kontakt ds. ubezpieczenia cybernetycznego jest zdecydowanie zalecany, ale nie obowiązkowy. Cztery obowiązkowe role to organ zarządzający, facylitator, menedżer IT oraz osoba odpowiedzialna za komunikację lub kwestie prawne.",
        cs: "Kontakt pro kybernetické pojištění je důrazně doporučen, avšak není povinný. Čtyři povinné role jsou řídicí orgán, facilitátor, vedoucí IT a vedoucí komunikace nebo právní vedoucí.",
        pt: "O contacto de ciberseguro é fortemente recomendado, mas não obrigatório. As quatro funções obrigatórias são o órgão de direção, o facilitador, o responsável de TI e o responsável de comunicação ou jurídico.",
        ro: "Contactul pentru asigurarea cibernetică este puternic recomandat, dar nu obligatoriu. Cele patru roluri obligatorii sunt organul de conducere, facilitatorul, managerul IT și responsabilul de comunicare sau juridic.",
      },
    },
    {
      id: "1.2.3",
      question: {
        en: "What is the realistic minimum number of people for a defensible Mittelstand tabletop?",
        de: "Wie viele Personen sind das realistische Minimum für eine verteidigungsfähige Tabletop-Übung im Mittelstand?",
        fr: "Quel est le nombre minimum réaliste de personnes pour un exercice sur table défendable dans une PME ?",
        it: "Qual è il numero minimo realistico di persone per un'esercitazione da tavolo difendibile in una PMI?",
        es: "¿Cuál es el número mínimo realista de personas para un ejercicio de mesa defendible en una pyme?",
        pl: "Jaka jest realistyczna minimalna liczba osób potrzebna do możliwego do obrony ćwiczenia sztabowego w średniej firmie?",
        cs: "Jaký je realistický minimální počet osob pro obhajitelné štábní cvičení ve středně velké firmě?",
        pt: "Qual é o número mínimo realista de pessoas para um exercício de mesa defensável numa pequena ou média empresa?",
        ro: "Care este numărul minim realist de persoane pentru un exercițiu pe hârtie care poate fi susținut într-o întreprindere mijlocie?",
      },
      options: [
        { en: "Two", de: "Zwei", fr: "Deux", it: "Due", es: "Dos", pl: "Dwie", cs: "Dvě", pt: "Duas", ro: "Două" },
        { en: "Four", de: "Vier", fr: "Quatre", it: "Quattro", es: "Cuatro", pl: "Cztery", cs: "Čtyři", pt: "Quatro", ro: "Patru" },
        { en: "Eight", de: "Acht", fr: "Huit", it: "Otto", es: "Ocho", pl: "Osiem", cs: "Osm", pt: "Oito", ro: "Opt" },
        { en: "Twelve", de: "Zwölf", fr: "Douze", it: "Dodici", es: "Doce", pl: "Dwanaście", cs: "Dvanáct", pt: "Doze", ro: "Doisprezece" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Four: management body representative, facilitator, IT manager, and a combined communications/legal lead.",
        de: "Vier: Vertretung der Geschäftsleitung, Moderation, IT-Verantwortliche und eine kombinierte Kommunikations-/Rechts-Verantwortliche.",
        fr: "Quatre : représentant de l'organe de direction, animateur, responsable informatique et un responsable combiné communication/juridique.",
        it: "Quattro: rappresentante dell'organo di gestione, facilitatore, responsabile IT e un responsabile combinato comunicazione/legale.",
        es: "Cuatro: representante del órgano de dirección, facilitador, responsable de TI y un responsable combinado de comunicación/jurídico.",
        pl: "Cztery: przedstawiciel organu zarządzającego, facylitator, menedżer IT oraz połączona osoba odpowiedzialna za komunikację i kwestie prawne.",
        cs: "Čtyři: zástupce řídicího orgánu, facilitátor, vedoucí IT a sloučený vedoucí komunikace a právních záležitostí.",
        pt: "Quatro: representante do órgão de direção, facilitador, responsável de TI e um responsável combinado de comunicação e jurídico.",
        ro: "Patru: reprezentantul organului de conducere, facilitatorul, managerul IT și un responsabil combinat de comunicare și juridic.",
      },
    },
    {
      id: "1.2.4",
      question: {
        en: "What does an auditor conclude when the protocol shows no management body participation?",
        de: "Was schließt ein Audit, wenn das Protokoll keine Teilnahme der Geschäftsleitung zeigt?",
        fr: "Que conclut un auditeur lorsque le protocole ne montre aucune participation de l'organe de direction ?",
        it: "Che cosa conclude un auditor quando il protocollo non mostra alcuna partecipazione dell'organo di gestione?",
        es: "¿Qué concluye un auditor cuando el protocolo no muestra participación del órgano de dirección?",
        pl: "Co stwierdza audytor, gdy protokół nie wykazuje udziału organu zarządzającego?",
        cs: "K jakému závěru dospěje auditor, když protokol neukazuje žádnou účast řídicího orgánu?",
        pt: "O que conclui um auditor quando o protocolo não mostra participação do órgão de direção?",
        ro: "Ce concluzionează un auditor atunci când protocolul nu arată nicio participare a organului de conducere?",
      },
      options: [
        { en: "That the exercise was efficient", de: "Dass die Übung effizient verlief", fr: "Que l'exercice a été efficace", it: "Che l'esercitazione è stata efficiente", es: "Que el ejercicio fue eficiente", pl: "Że ćwiczenie przebiegło sprawnie", cs: "Že cvičení proběhlo efektivně", pt: "Que o exercício foi eficiente", ro: "Că exercițiul a fost eficient" },
        { en: "That the management body delegated correctly", de: "Dass die Geschäftsleitung korrekt delegiert hat", fr: "Que l'organe de direction a délégué correctement", it: "Che l'organo di gestione ha delegato correttamente", es: "Que el órgano de dirección delegó correctamente", pl: "Że organ zarządzający prawidłowo przekazał zadania", cs: "Že řídicí orgán správně delegoval", pt: "Que o órgão de direção delegou corretamente", ro: "Că organul de conducere a delegat corect" },
        { en: "That the Article 20(1) duty is being skipped", de: "Dass die Pflicht aus Artikel 20(1) übersprungen wird", fr: "Que l'obligation de l'article 20(1) est ignorée", it: "Che l'obbligo dell'articolo 20(1) viene eluso", es: "Que se está omitiendo el deber del artículo 20(1)", pl: "Że obowiązek z artykułu 20(1) jest pomijany", cs: "Že povinnost podle článku 20(1) je obcházena", pt: "Que o dever do artigo 20(1) está a ser ignorado", ro: "Că obligația prevăzută la articolul 20(1) este eludată" },
        { en: "That the IT team is well-trained", de: "Dass das IT-Team gut geschult ist", fr: "Que l'équipe informatique est bien formée", it: "Che il team IT è ben formato", es: "Que el equipo de TI está bien formado", pl: "Że zespół IT jest dobrze przeszkolony", cs: "Že IT tým je dobře vyškolen", pt: "Que a equipa de TI está bem formada", ro: "Că echipa IT este bine instruită" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The absence of a management body signature is read as evidence the Article 20(1) NIS 2 personal-responsibility duty is being skipped.",
        de: "Das Fehlen einer Unterschrift der Geschäftsleitung wird als Hinweis gelesen, dass die persönliche Verantwortungspflicht aus Artikel 20(1) NIS 2 übersprungen wird.",
        fr: "L'absence de signature de l'organe de direction est interprétée comme la preuve que l'obligation de responsabilité personnelle de l'article 20(1) NIS 2 est ignorée.",
        it: "L'assenza di una firma dell'organo di gestione è interpretata come prova che l'obbligo di responsabilità personale dell'articolo 20(1) NIS 2 viene eluso.",
        es: "La ausencia de una firma del órgano de dirección se interpreta como prueba de que se está omitiendo el deber de responsabilidad personal del artículo 20(1) NIS 2.",
        pl: "Brak podpisu organu zarządzającego jest odczytywany jako dowód, że obowiązek osobistej odpowiedzialności z artykułu 20(1) NIS 2 jest pomijany.",
        cs: "Chybějící podpis řídicího orgánu se vykládá jako důkaz, že povinnost osobní odpovědnosti podle článku 20(1) NIS 2 je obcházena.",
        pt: "A ausência de uma assinatura do órgão de direção é interpretada como prova de que o dever de responsabilidade pessoal do artigo 20(1) NIS 2 está a ser ignorado.",
        ro: "Absența unei semnături a organului de conducere este interpretată ca dovadă că obligația de responsabilitate personală prevăzută la articolul 20(1) NIS 2 este eludată.",
      },
    },
  ],
});

export default quiz;
