import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.1",
  passingScore: 75,
  questions: [
    {
      id: "3.1.1",
      question: {
        en: "What is the floor an auditor expects for tabletop cadence?",
        de: "Welche Mindesthäufigkeit erwartet ein Audit für Tabletop-Übungen?",
        fr: "Quelle est la fréquence minimale qu'un auditeur attend pour les exercices sur table ?",
        it: "Qual è la frequenza minima che un auditor si aspetta per le esercitazioni da tavolo?",
        es: "¿Cuál es la frecuencia mínima que un auditor espera para los ejercicios de mesa?",
        pl: "Jakiej minimalnej częstotliwości ćwiczeń sztabowych oczekuje audytor?",
      },
      options: [
        { en: "Once every five years", de: "Einmal alle fünf Jahre", fr: "Une fois tous les cinq ans", it: "Una volta ogni cinque anni", es: "Una vez cada cinco años", pl: "Raz na pięć lat" },
        { en: "Once every three years", de: "Einmal alle drei Jahre", fr: "Une fois tous les trois ans", it: "Una volta ogni tre anni", es: "Una vez cada tres años", pl: "Raz na trzy lata" },
        { en: "At least annually", de: "Mindestens einmal jährlich", fr: "Au moins une fois par an", it: "Almeno una volta all'anno", es: "Al menos una vez al año", pl: "Co najmniej raz w roku" },
        { en: "Only after a real incident", de: "Nur nach einem echten Vorfall", fr: "Uniquement après un incident réel", it: "Solo dopo un incidente reale", es: "Solo después de un incidente real", pl: "Tylko po rzeczywistym incydencie" },
      ],
      correctIndex: 2,
      explanation: {
        en: "BSI Standard 200-4 §6.5 and ISO 22301:2019 Section 8.6 converge on at least annual cadence. Less than annually reads as inadequate testing.",
        de: "BSI-Standard 200-4 §6.5 und ISO 22301:2019 Abschnitt 8.6 stimmen auf mindestens jährliche Häufigkeit überein. Seltener wird als unzureichendes Testen gewertet.",
        fr: "Le BSI Standard 200-4 §6.5 et l'ISO 22301:2019 Section 8.6 convergent vers une fréquence au moins annuelle. Une fréquence inférieure est interprétée comme un test inadéquat.",
        it: "Il BSI Standard 200-4 §6.5 e l'ISO 22301:2019 Sezione 8.6 convergono su una frequenza almeno annuale. Una frequenza inferiore viene interpretata come collaudo inadeguato.",
        es: "El BSI Standard 200-4 §6.5 y la ISO 22301:2019 Section 8.6 convergen en una frecuencia al menos anual. Una frecuencia inferior se interpreta como una prueba inadecuada.",
        pl: "BSI Standard 200-4 §6.5 i ISO 22301:2019 Section 8.6 są zbieżne co do co najmniej rocznej częstotliwości. Rzadsza częstotliwość jest odczytywana jako niewystarczające testowanie.",
      },
    },
    {
      id: "3.1.2",
      question: {
        en: "Which of these triggers an ad-hoc exercise outside the annual rhythm?",
        de: "Welches Ereignis löst eine zusätzliche Übung außerhalb des Jahresrhythmus aus?",
        fr: "Lequel de ces événements déclenche un exercice ponctuel en dehors du rythme annuel ?",
        it: "Quale di questi eventi attiva un'esercitazione ad hoc al di fuori del ritmo annuale?",
        es: "¿Cuál de estos eventos desencadena un ejercicio ad hoc fuera del ritmo anual?",
        pl: "Które z tych zdarzeń uruchamia dodatkowe ćwiczenie poza rocznym rytmem?",
      },
      options: [
        { en: "Quarterly board meetings", de: "Quartalsweise Aufsichtsrats-Sitzungen", fr: "Réunions trimestrielles du conseil", it: "Riunioni trimestrali del consiglio", es: "Reuniones trimestrales del consejo", pl: "Kwartalne posiedzenia zarządu" },
        { en: "Major IT change such as a new ERP or core platform migration", de: "Eine größere IT-Änderung wie ein neues ERP oder die Migration einer Kernplattform", fr: "Un changement informatique majeur tel qu'un nouvel ERP ou la migration d'une plateforme centrale", it: "Una modifica IT importante come un nuovo ERP o la migrazione di una piattaforma centrale", es: "Un cambio de TI importante como un nuevo ERP o la migración de una plataforma central", pl: "Poważna zmiana IT, taka jak nowy ERP lub migracja platformy kluczowej" },
        { en: "Hiring a new junior developer", de: "Die Einstellung einer Junior-Entwicklerin", fr: "L'embauche d'un nouveau développeur junior", it: "L'assunzione di un nuovo sviluppatore junior", es: "La contratación de un nuevo desarrollador junior", pl: "Zatrudnienie nowego młodszego programisty" },
        { en: "Receiving a marketing email from a competitor", de: "Eine Marketing-E-Mail eines Wettbewerbers", fr: "La réception d'un courriel marketing d'un concurrent", it: "La ricezione di un'e-mail di marketing da un concorrente", es: "La recepción de un correo de marketing de un competidor", pl: "Otrzymanie e-maila marketingowego od konkurenta" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Major IT changes, new sector entry, new critical supplier, post-real-incident reviews, and leadership change all justify ad-hoc exercises.",
        de: "Größere IT-Änderungen, Eintritt in einen neuen Sektor, ein neuer kritischer Lieferant, Aufarbeitung eines realen Vorfalls und Wechsel in der Führung rechtfertigen zusätzliche Übungen.",
        fr: "Les changements informatiques majeurs, l'entrée dans un nouveau secteur, un nouveau fournisseur critique, les revues après un incident réel et un changement de direction justifient tous des exercices ponctuels.",
        it: "Modifiche IT importanti, l'ingresso in un nuovo settore, un nuovo fornitore critico, i riesami dopo un incidente reale e un cambio alla guida giustificano tutti esercitazioni ad hoc.",
        es: "Los cambios de TI importantes, la entrada en un nuevo sector, un nuevo proveedor crítico, las revisiones tras un incidente real y un cambio de liderazgo justifican todos ejercicios ad hoc.",
        pl: "Poważne zmiany IT, wejście w nowy sektor, nowy krytyczny dostawca, przeglądy po rzeczywistym incydencie oraz zmiana kierownictwa uzasadniają dodatkowe ćwiczenia.",
      },
    },
    {
      id: "3.1.3",
      question: {
        en: "Which training duty does this course attestation discharge?",
        de: "Welche Schulungspflicht erfüllt die Bescheinigung dieses Kurses?",
        fr: "Quelle obligation de formation l'attestation de ce cours permet-elle de remplir ?",
        it: "Quale obbligo di formazione assolve l'attestato di questo corso?",
        es: "¿Qué deber de formación cumple el certificado de este curso?",
        pl: "Który obowiązek szkoleniowy spełnia zaświadczenie z tego kursu?",
      },
      options: [
        { en: "The management body training duty under Article 20(2) NIS 2", de: "Die Schulungspflicht der Geschäftsleitung nach Artikel 20(2) NIS 2", fr: "L'obligation de formation de l'organe de direction au titre de l'article 20(2) NIS 2", it: "L'obbligo di formazione dell'organo di gestione ai sensi dell'articolo 20(2) NIS 2", es: "El deber de formación del órgano de dirección conforme al artículo 20(2) NIS 2", pl: "Obowiązek szkoleniowy organu zarządzającego na podstawie artykułu 20(2) NIS 2" },
        { en: "Role-specific cybersecurity training under Article 21(2)(g) NIS 2 for the facilitator role", de: "Rollenspezifische Cybersicherheits-Schulung nach Artikel 21(2)(g) NIS 2 für die Moderationsrolle", fr: "La formation en cybersécurité propre au rôle au titre de l'article 21(2)(g) NIS 2 pour le rôle d'animateur", it: "La formazione in cybersicurezza specifica per il ruolo ai sensi dell'articolo 21(2)(g) NIS 2 per il ruolo di facilitatore", es: "La formación en ciberseguridad específica del rol conforme al artículo 21(2)(g) NIS 2 para el rol de facilitador", pl: "Szkolenie z cyberbezpieczeństwa specyficzne dla roli na podstawie artykułu 21(2)(g) NIS 2 dla roli facylitatora" },
        { en: "The data protection officer training under Article 39 GDPR", de: "Die Datenschutzbeauftragten-Schulung nach Artikel 39 DSGVO", fr: "La formation du délégué à la protection des données au titre de l'article 39 GDPR", it: "La formazione del responsabile della protezione dei dati ai sensi dell'articolo 39 GDPR", es: "La formación del delegado de protección de datos conforme al artículo 39 GDPR", pl: "Szkolenie inspektora ochrony danych na podstawie artykułu 39 GDPR" },
        { en: "Both Article 20(2) and Article 21(2)(g) simultaneously", de: "Artikel 20(2) und Artikel 21(2)(g) gleichzeitig", fr: "À la fois l'article 20(2) et l'article 21(2)(g) simultanément", it: "Sia l'articolo 20(2) sia l'articolo 21(2)(g) contemporaneamente", es: "Tanto el artículo 20(2) como el artículo 21(2)(g) simultáneamente", pl: "Jednocześnie artykuł 20(2) i artykuł 21(2)(g)" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The attestation discharges Article 21(2)(g) for the facilitator. The management body course is a separate product that discharges Article 20(2).",
        de: "Die Bescheinigung erfüllt Artikel 21(2)(g) für die Moderationsrolle. Der Geschäftsleitungs-Kurs ist ein separates Angebot, das Artikel 20(2) erfüllt.",
        fr: "L'attestation remplit l'article 21(2)(g) pour l'animateur. Le cours destiné à l'organe de direction est un produit distinct qui remplit l'article 20(2).",
        it: "L'attestato assolve l'articolo 21(2)(g) per il facilitatore. Il corso per l'organo di gestione è un prodotto separato che assolve l'articolo 20(2).",
        es: "El certificado cumple el artículo 21(2)(g) para el facilitador. El curso del órgano de dirección es un producto independiente que cumple el artículo 20(2).",
        pl: "Zaświadczenie spełnia artykuł 21(2)(g) dla facylitatora. Kurs dla organu zarządzającego to odrębny produkt, który spełnia artykuł 20(2).",
      },
    },
    {
      id: "3.1.4",
      question: {
        en: "When does the Article 23 clock start in any scenario?",
        de: "Wann startet die Uhr nach Artikel 23 in jedem Szenario?",
        fr: "Quand le délai de l'article 23 commence-t-il à courir dans n'importe quel scénario ?",
        it: "Quando inizia a decorrere il termine dell'articolo 23 in qualsiasi scenario?",
        es: "¿Cuándo empieza a contar el plazo del artículo 23 en cualquier escenario?",
        pl: "Kiedy w dowolnym scenariuszu zaczyna biec termin z artykułu 23?",
      },
      options: [
        { en: "On detection by automated monitoring", de: "Bei der Erkennung durch ein automatisches Monitoring", fr: "Lors de la détection par une surveillance automatisée", it: "Al rilevamento da parte di un monitoraggio automatizzato", es: "En la detección por una supervisión automatizada", pl: "W momencie wykrycia przez zautomatyzowane monitorowanie" },
        { en: "On becoming aware enough to assess the incident as significant", de: "Mit der Kenntniserlangung, die die Beurteilung als erheblich erlaubt", fr: "Au moment où l'on a connaissance suffisamment pour évaluer l'incident comme important", it: "Quando se ne ha conoscenza al punto da poter valutare l'incidente come significativo", es: "Cuando se tiene conocimiento suficiente para evaluar el incidente como significativo", pl: "W chwili powzięcia wiedzy wystarczającej do oceny incydentu jako istotnego" },
        { en: "When the IT team begins remediation", de: "Wenn das IT-Team mit der Behebung beginnt", fr: "Lorsque l'équipe informatique entame la remédiation", it: "Quando il team IT avvia la correzione", es: "Cuando el equipo de TI inicia la corrección", pl: "Gdy zespół IT rozpoczyna usuwanie skutków" },
        { en: "When the CEO is informed", de: "Wenn die Geschäftsführung informiert wird", fr: "Lorsque le PDG est informé", it: "Quando l'amministratore delegato viene informato", es: "Cuando se informa al director ejecutivo", pl: "Gdy prezes zostaje poinformowany" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 23(4)(a) NIS 2 uses 'becoming aware,' not detection. Awareness is when a responsible person knows enough to assess significance.",
        de: "Artikel 23(4)(a) NIS 2 spricht von Kenntniserlangung, nicht von Detektion. Kenntniserlangung bedeutet, dass eine verantwortliche Person genug weiß, um die Erheblichkeit zu beurteilen.",
        fr: "L'article 23(4)(a) NIS 2 emploie « avoir connaissance », et non la détection. La connaissance est le moment où une personne responsable en sait assez pour évaluer le caractère important.",
        it: "L'articolo 23(4)(a) NIS 2 parla di « venire a conoscenza », non di rilevamento. La conoscenza è il momento in cui una persona responsabile sa abbastanza da valutare la significatività.",
        es: "El artículo 23(4)(a) NIS 2 emplea « tener conocimiento », no la detección. El conocimiento es el momento en que una persona responsable sabe lo suficiente para evaluar la significatividad.",
        pl: "Artykuł 23(4)(a) NIS 2 mówi o « powzięciu wiedzy », a nie o wykryciu. Powzięcie wiedzy to moment, w którym osoba odpowiedzialna wie wystarczająco dużo, aby ocenić istotność.",
      },
    },
    {
      id: "3.1.5",
      question: {
        en: "Why does the management body need to be in the room for the tabletop?",
        de: "Warum muss die Geschäftsleitung bei der Tabletop-Übung im Raum sein?",
        fr: "Pourquoi l'organe de direction doit-il être présent dans la salle pour l'exercice sur table ?",
        it: "Perché l'organo di gestione deve essere presente nella sala durante l'esercitazione da tavolo?",
        es: "¿Por qué debe el órgano de dirección estar en la sala durante el ejercicio de mesa?",
        pl: "Dlaczego organ zarządzający musi być obecny w sali podczas ćwiczenia sztabowego?",
      },
      options: [
        { en: "To approve catering", de: "Um die Bewirtung freizugeben", fr: "Pour approuver le traiteur", it: "Per approvare il catering", es: "Para aprobar el catering", pl: "Aby zatwierdzić catering" },
        { en: "Because Article 20(1) NIS 2 makes them personally responsible and the exercise rehearses decisions only they can make in a real crisis", de: "Weil Artikel 20(1) NIS 2 sie persönlich verantwortlich macht und die Übung Entscheidungen probt, die nur sie in einer echten Krise treffen kann", fr: "Parce que l'article 20(1) NIS 2 le rend personnellement responsable et que l'exercice répète des décisions que lui seul peut prendre dans une crise réelle", it: "Perché l'articolo 20(1) NIS 2 lo rende personalmente responsabile e l'esercitazione simula decisioni che solo esso può prendere in una crisi reale", es: "Porque el artículo 20(1) NIS 2 lo hace personalmente responsable y el ejercicio ensaya decisiones que solo él puede tomar en una crisis real", pl: "Ponieważ artykuł 20(1) NIS 2 czyni go osobiście odpowiedzialnym, a ćwiczenie przećwicza decyzje, które tylko on może podjąć w rzeczywistym kryzysie" },
        { en: "Because the IT team needs an audience", de: "Weil das IT-Team ein Publikum braucht", fr: "Parce que l'équipe informatique a besoin d'un public", it: "Perché il team IT ha bisogno di un pubblico", es: "Porque el equipo de TI necesita un público", pl: "Ponieważ zespół IT potrzebuje publiczności" },
        { en: "Because the CSIRT requires it", de: "Weil das CSIRT es verlangt", fr: "Parce que le CSIRT l'exige", it: "Perché il CSIRT lo richiede", es: "Porque el CSIRT lo exige", pl: "Ponieważ CSIRT tego wymaga" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 20(1) NIS 2 personal responsibility cannot be discharged by a memo. The decisions that matter are the management body's.",
        de: "Die persönliche Verantwortung nach Artikel 20(1) NIS 2 lässt sich nicht durch eine Aktennotiz erfüllen. Die entscheidenden Entscheidungen sind Sache der Geschäftsleitung.",
        fr: "La responsabilité personnelle de l'article 20(1) NIS 2 ne peut être remplie par une note de service. Les décisions qui comptent sont celles de l'organe de direction.",
        it: "La responsabilità personale dell'articolo 20(1) NIS 2 non può essere assolta con un promemoria. Le decisioni che contano sono quelle dell'organo di gestione.",
        es: "La responsabilidad personal del artículo 20(1) NIS 2 no puede cumplirse con un memorando. Las decisiones que importan son las del órgano de dirección.",
        pl: "Osobistej odpowiedzialności z artykułu 20(1) NIS 2 nie można spełnić notatką służbową. Decyzje, które się liczą, należą do organu zarządzającego.",
      },
    },
    {
      id: "3.1.6",
      question: {
        en: "Which is NOT a valid response to the facilitator-separation problem in a small team?",
        de: "Welche Option ist KEINE gültige Lösung für das Trennungs-Problem der Moderation in einem kleinen Team?",
        fr: "Laquelle n'est PAS une réponse valable au problème de séparation de l'animateur dans une petite équipe ?",
        it: "Quale NON è una risposta valida al problema della separazione del facilitatore in un piccolo team?",
        es: "¿Cuál NO es una respuesta válida al problema de la separación del facilitador en un equipo pequeño?",
        pl: "Która opcja NIE jest właściwym rozwiązaniem problemu rozdziału funkcji facylitatora w małym zespole?",
      },
      options: [
        { en: "Rotating facilitation across years", de: "Die Moderation jahresweise rotieren", fr: "Faire tourner l'animation d'une année à l'autre", it: "Ruotare la facilitazione di anno in anno", es: "Rotar la facilitación de un año a otro", pl: "Rotacja facylitacji w kolejnych latach" },
        { en: "Swapping facilitators with a peer organisation", de: "Die Moderation mit einem Partnerunternehmen tauschen", fr: "Échanger les animateurs avec une organisation homologue", it: "Scambiare i facilitatori con un'organizzazione omologa", es: "Intercambiar facilitadores con una organización homóloga", pl: "Wymiana facylitatorów z organizacją partnerską" },
        { en: "Engaging an external observer", de: "Eine externe Beobachtung beauftragen", fr: "Faire appel à un observateur externe", it: "Coinvolgere un osservatore esterno", es: "Contratar a un observador externo", pl: "Zaangażowanie zewnętrznego obserwatora" },
        { en: "Having one person be both facilitator and in-scenario IT manager", de: "Eine Person übernimmt Moderation und IT-Rolle im Szenario gleichzeitig", fr: "Faire d'une même personne à la fois l'animateur et le responsable informatique dans le scénario", it: "Far svolgere a una stessa persona sia il ruolo di facilitatore sia quello di responsabile IT nello scenario", es: "Hacer que una misma persona sea a la vez el facilitador y el responsable de TI en el escenario", pl: "Dopuszczenie, by jedna osoba była jednocześnie facylitatorem i menedżerem IT w scenariuszu" },
      ],
      correctIndex: 3,
      explanation: {
        en: "The same person cannot be both facilitator and an in-scenario participant. Rotation, peer swap, or external observer are the three valid options.",
        de: "Dieselbe Person kann nicht gleichzeitig Moderation und Mitspielende im Szenario sein. Rotation, Partnertausch oder externe Beobachtung sind die drei gültigen Lösungen.",
        fr: "La même personne ne peut pas être à la fois animateur et participant dans le scénario. La rotation, l'échange avec un pair ou l'observateur externe sont les trois options valables.",
        it: "La stessa persona non può essere contemporaneamente facilitatore e partecipante allo scenario. Rotazione, scambio con un pari o osservatore esterno sono le tre opzioni valide.",
        es: "La misma persona no puede ser a la vez facilitador y participante en el escenario. La rotación, el intercambio con un par o el observador externo son las tres opciones válidas.",
        pl: "Ta sama osoba nie może być jednocześnie facylitatorem i uczestnikiem scenariusza. Rotacja, wymiana z partnerem lub zewnętrzny obserwator to trzy właściwe opcje.",
      },
    },
    {
      id: "3.1.7",
      question: {
        en: "What goes into an improvement item from the hot wash?",
        de: "Welche Felder gehören zu einem Verbesserungspunkt aus dem Hot Wash?",
        fr: "Que comporte un point d'amélioration issu du hot wash ?",
        it: "Che cosa contiene un elemento di miglioramento emerso dal hot wash?",
        es: "¿Qué contiene un elemento de mejora del hot wash?",
        pl: "Co składa się na punkt usprawnienia wynikający z hot wash?",
      },
      options: [
        { en: "A description and a vague timeline", de: "Eine Beschreibung und eine grobe Zeitvorstellung", fr: "Une description et un calendrier vague", it: "Una descrizione e una tempistica vaga", es: "Una descripción y un calendario vago", pl: "Opis i ogólny harmonogram" },
        { en: "What, owner, deadline, linked Article 21(2) measure, and closure criterion", de: "Was, verantwortliche Person, Frist, Bezug zur Maßnahme aus Artikel 21(2) und Abschluss-Kriterium", fr: "Quoi, responsable, échéance, mesure liée de l'article 21(2) et critère de clôture", it: "Cosa, responsabile, scadenza, misura collegata dell'articolo 21(2) e criterio di chiusura", es: "Qué, responsable, fecha límite, medida vinculada del artículo 21(2) y criterio de cierre", pl: "Co, osoba odpowiedzialna, termin, powiązany środek z artykułu 21(2) oraz kryterium zamknięcia" },
        { en: "Just the owner's name", de: "Nur der Name der verantwortlichen Person", fr: "Uniquement le nom du responsable", it: "Solo il nome del responsabile", es: "Solo el nombre del responsable", pl: "Tylko imię i nazwisko osoby odpowiedzialnej" },
        { en: "Only the description and a priority", de: "Nur Beschreibung und Priorität", fr: "Uniquement la description et une priorité", it: "Solo la descrizione e una priorità", es: "Solo la descripción y una prioridad", pl: "Tylko opis i priorytet" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Five fields make improvement items trackable and audit-ready: what, owner, deadline, statutory link, and closure criterion.",
        de: "Fünf Felder machen Verbesserungspunkte nachverfolgbar und audit-tauglich: was, verantwortliche Person, Frist, rechtlicher Bezug und Abschluss-Kriterium.",
        fr: "Cinq champs rendent les points d'amélioration traçables et prêts pour l'audit : quoi, responsable, échéance, lien légal et critère de clôture.",
        it: "Cinque campi rendono gli elementi di miglioramento tracciabili e pronti per l'audit: cosa, responsabile, scadenza, riferimento normativo e criterio di chiusura.",
        es: "Cinco campos hacen que los elementos de mejora sean rastreables y aptos para auditoría: qué, responsable, fecha límite, vínculo legal y criterio de cierre.",
        pl: "Pięć pól sprawia, że punkty usprawnień są możliwe do śledzenia i gotowe do audytu: co, osoba odpowiedzialna, termin, odniesienie prawne oraz kryterium zamknięcia.",
      },
    },
    {
      id: "3.1.8",
      question: {
        en: "Why is a Live-System Tabletop protocol stronger evidence than a Word-file protocol?",
        de: "Warum ist ein Live-System-Tabletop-Protokoll ein stärkerer Nachweis als ein Word-Datei-Protokoll?",
        fr: "Pourquoi un protocole d'exercice sur table en système réel constitue-t-il une preuve plus solide qu'un protocole sous forme de fichier Word ?",
        it: "Perché un protocollo di esercitazione da tavolo su sistema reale è una prova più solida di un protocollo in file Word?",
        es: "¿Por qué un protocolo de ejercicio de mesa en sistema real es una evidencia más sólida que un protocolo en archivo Word?",
        pl: "Dlaczego protokół ćwiczenia sztabowego w systemie na żywo jest mocniejszym dowodem niż protokół w pliku Word?",
      },
      options: [
        { en: "Because PDFs cannot be edited", de: "Weil PDFs nicht bearbeitet werden können", fr: "Parce que les PDF ne peuvent pas être modifiés", it: "Perché i PDF non possono essere modificati", es: "Porque los PDF no se pueden editar", pl: "Ponieważ plików PDF nie można edytować" },
        { en: "Because it lands in the same audit trail and the same format as real incident reports, making the simulated and real incidents indistinguishable in evidence shape", de: "Weil es im selben Audit-Trail und im selben Format wie echte Vorfallsberichte landet und somit fiktive und reale Vorfälle in der Nachweisform identisch wirken", fr: "Parce qu'il se retrouve dans la même piste d'audit et le même format que les rapports d'incident réels, rendant les incidents simulés et réels indiscernables dans la forme de la preuve", it: "Perché finisce nella stessa pista di controllo e nello stesso formato dei rapporti di incidenti reali, rendendo indistinguibili nella forma della prova gli incidenti simulati e quelli reali", es: "Porque queda en la misma pista de auditoría y el mismo formato que los informes de incidentes reales, lo que hace que los incidentes simulados y reales sean indistinguibles en la forma de la evidencia", pl: "Ponieważ trafia do tej samej ścieżki audytu i tego samego formatu co raporty z rzeczywistych incydentów, czyniąc incydenty symulowane i rzeczywiste nieodróżnialnymi pod względem formy dowodu" },
        { en: "Because the BSI prefers PDFs", de: "Weil das BSI PDFs bevorzugt", fr: "Parce que le BSI préfère les PDF", it: "Perché il BSI preferisce i PDF", es: "Porque el BSI prefiere los PDF", pl: "Ponieważ BSI preferuje pliki PDF" },
        { en: "Because Word files cannot be signed digitally", de: "Weil Word-Dateien nicht digital signiert werden können", fr: "Parce que les fichiers Word ne peuvent pas être signés numériquement", it: "Perché i file Word non possono essere firmati digitalmente", es: "Porque los archivos Word no se pueden firmar digitalmente", pl: "Ponieważ plików Word nie można podpisać cyfrowo" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Structural sameness with real-incident evidence is the underlying claim. The audit trail treats both as the same artefact type, with only the exercise flag distinguishing them.",
        de: "Die strukturelle Gleichheit mit echten Vorfallsnachweisen ist die zentrale Aussage. Der Audit-Trail behandelt beide als denselben Artefakt-Typ; nur das Übungs-Kennzeichen unterscheidet sie.",
        fr: "L'identité structurelle avec les preuves d'incidents réels est l'argument de fond. La piste d'audit traite les deux comme le même type d'artefact, seul l'indicateur d'exercice les distinguant.",
        it: "L'identità strutturale con le prove di incidenti reali è l'argomento di fondo. La pista di controllo tratta entrambi come lo stesso tipo di artefatto, distinguendoli solo con il contrassegno di esercitazione.",
        es: "La identidad estructural con la evidencia de incidentes reales es el argumento de fondo. La pista de auditoría trata a ambos como el mismo tipo de artefacto, distinguiéndolos solo con la marca de ejercicio.",
        pl: "Strukturalna tożsamość z dowodami z rzeczywistych incydentów to zasadnicze twierdzenie. Ścieżka audytu traktuje oba jako ten sam typ artefaktu, a odróżnia je jedynie znacznik ćwiczenia.",
      },
    },
  ],
});

export default quiz;
