import { courseSchema } from "@/lib/training/schemas";

const course = courseSchema.parse({
  id: "nis2-tabletop",
  title: {
    en: "NIS 2 Tabletop Exercise Training",
    de: "NIS-2-Tabletop-Schulung",
    fr: "Formation à l'exercice sur table NIS 2",
    it: "Formazione all'esercitazione tabletop NIS 2",
    es: "Formación en ejercicios de simulación NIS 2",
    pl: "Szkolenie z ćwiczeń sztabowych NIS 2",
    cs: "Školení cvičení tabletop NIS 2",
    pt: "Formação em exercícios tabletop NIS 2",
    ro: "Instruire pentru exercițiul tabletop NIS 2",
  },
  description: {
    en: "Design, run, and document the annual exercise NIS 2 demands. Built for facilitators: information security officers, IT managers, and BCM leads who must run a tabletop that produces audit-grade evidence. EU-wide framing, with German transposition references.",
    de: "Planen, durchführen und dokumentieren Sie die jährliche Übung, die NIS 2 verlangt. Konzipiert für Moderatorinnen und Moderatoren: Informationssicherheits-Beauftragte, IT-Verantwortliche und Notfall- und Krisenmanagement-Leitungen, die eine auditfeste Tabletop-Übung durchführen müssen. EU-weit verständlich, mit Bezügen zur deutschen Umsetzung im BSIG.",
    fr: "Concevez, animez et documentez l'exercice annuel exigé par NIS 2. Conçu pour les animateurs : responsables de la sécurité de l'information, responsables informatiques et responsables de la continuité d'activité qui doivent mener un exercice sur table produisant des preuves recevables en audit. Cadrage à l'échelle de l'UE, avec des références à la transposition allemande.",
    it: "Progetta, conduci e documenta l'esercitazione annuale richiesta da NIS 2. Pensato per i facilitatori: responsabili della sicurezza delle informazioni, responsabili IT e responsabili della continuità operativa che devono condurre un'esercitazione tabletop in grado di produrre prove idonee all'audit. Inquadramento a livello UE, con riferimenti al recepimento tedesco.",
    es: "Diseñe, dirija y documente el ejercicio anual que exige NIS 2. Pensado para facilitadores: responsables de seguridad de la información, responsables de TI y responsables de continuidad de negocio que deben dirigir un ejercicio de simulación capaz de producir evidencia válida para auditoría. Enfoque a escala de la UE, con referencias a la transposición alemana.",
    pl: "Zaprojektuj, przeprowadź i udokumentuj coroczne ćwiczenie wymagane przez NIS 2. Przeznaczone dla prowadzących: pełnomocników ds. bezpieczeństwa informacji, kierowników IT oraz osób odpowiedzialnych za ciągłość działania, którzy muszą przeprowadzić ćwiczenie sztabowe dające dowody wytrzymujące audyt. Ujęcie ogólnounijne, z odniesieniami do niemieckiej transpozycji.",
    cs: "Navrhněte, proveďte a zdokumentujte každoroční cvičení, které NIS 2 vyžaduje. Vytvořeno pro moderátory: manažery bezpečnosti informací, IT manažery a vedoucí řízení kontinuity provozu, kteří musí vést tabletop cvičení produkující důkazy obstojící v auditu. Celounijní rámec s odkazy na německé provedení do národního práva.",
    pt: "Conceba, conduza e documente o exercício anual que a NIS 2 exige. Concebido para facilitadores: responsáveis pela segurança da informação, responsáveis de TI e responsáveis pela continuidade do negócio que têm de conduzir um exercício tabletop capaz de produzir provas com qualidade de auditoria. Enquadramento à escala da UE, com referências à transposição alemã.",
    ro: "Concepeți, derulați și documentați exercițiul anual pe care îl impune NIS 2. Conceput pentru facilitatori: responsabili cu securitatea informațiilor, manageri IT și responsabili de continuitatea activității care trebuie să conducă un exercițiu tabletop ce produce dovezi valabile la audit. Cadru la nivelul UE, cu referințe la transpunerea germană.",
  },
  version: "1.0",
  modules: [
    {
      id: "foundation",
      title: {
        en: "Foundation",
        de: "Grundlagen",
        fr: "Fondations",
        it: "Fondamenti",
        es: "Fundamentos",
        pl: "Podstawy",
        cs: "Základy",
        pt: "Fundamentos",
        ro: "Fundamente",
      },
      order: 0,
      lessonIds: ["0.1"],
    },
    {
      id: "module-1",
      title: {
        en: "Legal Basis and Setup",
        de: "Rechtliche Grundlage und Vorbereitung",
        fr: "Base juridique et préparation",
        it: "Base giuridica e preparazione",
        es: "Base jurídica y preparación",
        pl: "Podstawa prawna i przygotowanie",
        cs: "Právní základ a příprava",
        pt: "Base jurídica e preparação",
        ro: "Baza juridică și pregătirea",
      },
      order: 1,
      lessonIds: ["1.1", "1.2", "1.3"],
    },
    {
      id: "module-2",
      title: {
        en: "Running and Closing the Exercise",
        de: "Durchführung und Abschluss der Übung",
        fr: "Animation et clôture de l'exercice",
        it: "Conduzione e chiusura dell'esercitazione",
        es: "Ejecución y cierre del ejercicio",
        pl: "Przeprowadzenie i zakończenie ćwiczenia",
        cs: "Provedení a uzavření cvičení",
        pt: "Condução e encerramento do exercício",
        ro: "Derularea și încheierea exercițiului",
      },
      order: 2,
      lessonIds: ["2.1", "2.2", "2.3"],
    },
    {
      id: "final",
      title: {
        en: "Final",
        de: "Abschluss",
        fr: "Conclusion",
        it: "Conclusione",
        es: "Cierre",
        pl: "Podsumowanie",
        cs: "Závěr",
        pt: "Conclusão",
        ro: "Încheiere",
      },
      order: 3,
      lessonIds: ["3.1"],
    },
  ],
});

export default course;
