import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.1",
  passingScore: 75,
  questions: [
    {
      id: "1.1.1",
      question: {
        en: "What is the difference between an EU directive and an EU regulation?",
        de: "Was ist der Unterschied zwischen einer EU-Richtlinie und einer EU-Verordnung?",
        nl: "Wat is het verschil tussen een EU-richtlijn en een EU-verordening?",
        fr: "Quelle est la différence entre une directive européenne et un règlement européen ?",
        it: "Qual è la differenza tra una direttiva dell'UE e un regolamento dell'UE?",
        es: "¿Cuál es la diferencia entre una directiva de la UE y un reglamento de la UE?",
        pl: "Jaka jest różnica między dyrektywą UE a rozporządzeniem UE?",
      },
      options: [
        { en: "A directive applies directly; a regulation must be transposed into national law", de: "Eine Richtlinie gilt unmittelbar; eine Verordnung muss in nationales Recht umgesetzt werden", nl: "Een richtlijn geldt rechtstreeks; een verordening moet worden omgezet in nationaal recht", fr: "Une directive s'applique directement ; un règlement doit être transposé en droit national", it: "Una direttiva si applica direttamente; un regolamento deve essere recepito nel diritto nazionale", es: "Una directiva se aplica directamente; un reglamento debe transponerse al derecho nacional", pl: "Dyrektywa obowiązuje bezpośrednio; rozporządzenie musi zostać transponowane do prawa krajowego" },
        { en: "A regulation applies directly; a directive must be transposed into national law", de: "Eine Verordnung gilt unmittelbar; eine Richtlinie muss in nationales Recht umgesetzt werden", nl: "Een verordening geldt rechtstreeks; een richtlijn moet worden omgezet in nationaal recht", fr: "Un règlement s'applique directement ; une directive doit être transposée en droit national", it: "Un regolamento si applica direttamente; una direttiva deve essere recepita nel diritto nazionale", es: "Un reglamento se aplica directamente; una directiva debe transponerse al derecho nacional", pl: "Rozporządzenie obowiązuje bezpośrednio; dyrektywa musi zostać transponowana do prawa krajowego" },
        { en: "There is no difference; both apply directly", de: "Es gibt keinen Unterschied; beide gelten unmittelbar", nl: "Er is geen verschil; beide gelden rechtstreeks", fr: "Il n'y a aucune différence ; les deux s'appliquent directement", it: "Non c'è alcuna differenza; entrambi si applicano direttamente", es: "No hay diferencia; ambos se aplican directamente", pl: "Nie ma różnicy; oba obowiązują bezpośrednio" },
        { en: "A directive only applies to Essential entities; a regulation applies to all", de: "Eine Richtlinie gilt nur für wesentliche Einrichtungen; eine Verordnung gilt für alle", nl: "Een richtlijn geldt alleen voor essentiële entiteiten; een verordening geldt voor iedereen", fr: "Une directive ne s'applique qu'aux entités essentielles ; un règlement s'applique à toutes", it: "Una direttiva si applica solo ai soggetti essenziali; un regolamento si applica a tutti", es: "Una directiva solo se aplica a las entidades esenciales; un reglamento se aplica a todas", pl: "Dyrektywa dotyczy wyłącznie podmiotów kluczowych; rozporządzenie dotyczy wszystkich" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A regulation (like the GDPR or the CIR) applies directly in every country. A directive tells each country what the result has to be, and each country writes its own national law.",
        de: "Eine Verordnung (wie die DSGVO oder die CIR) gilt unmittelbar in jedem Land. Eine Richtlinie gibt jedem Land das Ziel vor, und jedes Land erlässt ein eigenes nationales Gesetz.",
        nl: "Een verordening (zoals de GDPR of de CIR) geldt rechtstreeks in elk land. Een richtlijn geeft elk land aan wat het resultaat moet zijn, en elk land schrijft zijn eigen nationale wet.",
        fr: "Un règlement (comme le GDPR ou la CIR) s'applique directement dans chaque pays. Une directive indique à chaque pays quel doit être le résultat, et chaque pays rédige sa propre loi nationale.",
        it: "Un regolamento (come il GDPR o la CIR) si applica direttamente in ogni paese. Una direttiva indica a ciascun paese quale deve essere il risultato, e ogni paese redige la propria legge nazionale.",
        es: "Un reglamento (como el GDPR o la CIR) se aplica directamente en todos los países. Una directiva indica a cada país cuál debe ser el resultado, y cada país redacta su propia ley nacional.",
        pl: "Rozporządzenie (takie jak GDPR lub CIR) obowiązuje bezpośrednio w każdym kraju. Dyrektywa wskazuje każdemu krajowi, jaki ma być rezultat, a każdy kraj tworzy własne prawo krajowe.",
      },
    },
    {
      id: "1.1.2",
      question: {
        en: "What does the CIR (Commission Implementing Regulation 2024/2690) do?",
        de: "Was regelt die CIR (Durchführungsverordnung 2024/2690 der Kommission)?",
        nl: "Wat doet de CIR (Uitvoeringsverordening 2024/2690 van de Commissie)?",
        fr: "Que fait la CIR (règlement d'exécution 2024/2690 de la Commission) ?",
        it: "Che cosa fa la CIR (regolamento di esecuzione 2024/2690 della Commissione)?",
        es: "¿Qué hace la CIR (Reglamento de Ejecución 2024/2690 de la Comisión)?",
        pl: "Co reguluje CIR (rozporządzenie wykonawcze Komisji 2024/2690)?",
      },
      options: [
        { en: "It replaces the NIS2 Directive entirely", de: "Sie ersetzt die NIS2-Richtlinie vollständig", nl: "Het vervangt de NIS2-richtlijn volledig", fr: "Elle remplace entièrement la directive NIS2", it: "Sostituisce interamente la direttiva NIS2", es: "Sustituye por completo a la Directiva NIS2", pl: "Całkowicie zastępuje dyrektywę NIS2" },
        { en: "It sets the goals that each country must achieve", de: "Sie legt die Ziele fest, die jedes Land erreichen muss", nl: "Het stelt de doelen vast die elk land moet bereiken", fr: "Elle fixe les objectifs que chaque pays doit atteindre", it: "Stabilisce gli obiettivi che ciascun paese deve raggiungere", es: "Establece los objetivos que cada país debe alcanzar", pl: "Określa cele, które każdy kraj musi osiągnąć" },
        { en: "It sets detailed technical requirements that apply directly in all 27 member states", de: "Sie legt detaillierte technische Anforderungen fest, die unmittelbar in allen 27 Mitgliedstaaten gelten", nl: "Het stelt gedetailleerde technische vereisten vast die rechtstreeks gelden in alle 27 lidstaten", fr: "Elle fixe des exigences techniques détaillées qui s'appliquent directement dans les 27 États membres", it: "Stabilisce requisiti tecnici dettagliati che si applicano direttamente in tutti i 27 Stati membri", es: "Establece requisitos técnicos detallados que se aplican directamente en los 27 Estados miembros", pl: "Określa szczegółowe wymagania techniczne, które obowiązują bezpośrednio we wszystkich 27 państwach członkowskich" },
        { en: "It designates the competent authority in each country", de: "Sie bestimmt die zuständige Behörde in jedem Land", nl: "Het wijst de bevoegde autoriteit in elk land aan", fr: "Elle désigne l'autorité compétente dans chaque pays", it: "Designa l'autorità competente in ciascun paese", es: "Designa la autoridad competente en cada país", pl: "Wyznacza właściwy organ w każdym kraju" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The CIR is a regulation that applies directly in all member states, setting detailed technical requirements such as what counts as a significant incident and what policies are mandatory.",
        de: "Die CIR ist eine Verordnung, die unmittelbar in allen Mitgliedstaaten gilt und detaillierte technische Anforderungen festlegt, z. B. was als erheblicher Sicherheitsvorfall gilt und welche Richtlinien verpflichtend sind.",
        nl: "De CIR is een verordening die rechtstreeks van toepassing is in alle lidstaten en gedetailleerde technische vereisten vaststelt, zoals wat als een significant incident geldt en welk beleid verplicht is.",
        fr: "La CIR est un règlement qui s'applique directement dans tous les États membres et qui fixe des exigences techniques détaillées, par exemple ce qui constitue un incident important et quelles politiques sont obligatoires.",
        it: "La CIR è un regolamento che si applica direttamente in tutti gli Stati membri e stabilisce requisiti tecnici dettagliati, ad esempio cosa si considera un incidente significativo e quali politiche sono obbligatorie.",
        es: "La CIR es un reglamento que se aplica directamente en todos los Estados miembros y establece requisitos técnicos detallados, como qué se considera un incidente significativo y qué políticas son obligatorias.",
        pl: "CIR to rozporządzenie, które obowiązuje bezpośrednio we wszystkich państwach członkowskich i określa szczegółowe wymagania techniczne, takie jak co uznaje się za poważny incydent i które polityki są obowiązkowe.",
      },
    },
    {
      id: "1.1.3",
      question: {
        en: "What is the full legal chain described in this lesson?",
        de: "Wie lautet die vollständige Rechtskette, die in dieser Lektion beschrieben wird?",
        nl: "Wat is de volledige juridische keten die in deze les wordt beschreven?",
        fr: "Quelle est la chaîne juridique complète décrite dans cette leçon ?",
        it: "Qual è l'intera catena giuridica descritta in questa lezione?",
        es: "¿Cuál es la cadena jurídica completa descrita en esta lección?",
        pl: "Jak wygląda pełny łańcuch prawny opisany w tej lekcji?",
      },
      options: [
        { en: "CIR sets goals, NIS2 sets rules, national law enforces", de: "Die CIR setzt Ziele, NIS2 setzt Regeln, nationales Recht setzt durch", nl: "CIR stelt doelen, NIS2 stelt regels, nationaal recht handhaaft", fr: "La CIR fixe les objectifs, NIS2 fixe les règles, le droit national applique", it: "La CIR fissa gli obiettivi, NIS2 fissa le regole, il diritto nazionale fa rispettare", es: "La CIR fija los objetivos, NIS2 fija las reglas, el derecho nacional hace cumplir", pl: "CIR wyznacza cele, NIS2 wyznacza zasady, prawo krajowe egzekwuje" },
        { en: "NIS2 Directive sets goals, CIR sets detailed technical rules, national law transposes and the national enforcer audits", de: "Die NIS2-Richtlinie setzt Ziele, die CIR legt detaillierte technische Regeln fest, nationales Recht setzt um und die nationale Aufsichtsbehörde prüft", nl: "NIS2-richtlijn stelt doelen, CIR stelt gedetailleerde technische regels, nationaal recht zet om en de nationale handhaver controleert", fr: "La directive NIS2 fixe les objectifs, la CIR fixe les règles techniques détaillées, le droit national transpose et l'autorité de contrôle nationale audite", it: "La direttiva NIS2 fissa gli obiettivi, la CIR fissa le regole tecniche dettagliate, il diritto nazionale recepisce e l'autorità di vigilanza nazionale verifica", es: "La Directiva NIS2 fija los objetivos, la CIR fija las reglas técnicas detalladas, el derecho nacional transpone y la autoridad supervisora nacional audita", pl: "Dyrektywa NIS2 wyznacza cele, CIR wyznacza szczegółowe zasady techniczne, prawo krajowe transponuje, a krajowy organ nadzoru przeprowadza audyt" },
        { en: "National law sets goals, NIS2 Directive sets rules, CIR enforces", de: "Nationales Recht setzt Ziele, die NIS2-Richtlinie setzt Regeln, die CIR setzt durch", nl: "Nationaal recht stelt doelen, NIS2-richtlijn stelt regels, CIR handhaaft", fr: "Le droit national fixe les objectifs, la directive NIS2 fixe les règles, la CIR applique", it: "Il diritto nazionale fissa gli obiettivi, la direttiva NIS2 fissa le regole, la CIR fa rispettare", es: "El derecho nacional fija los objetivos, la Directiva NIS2 fija las reglas, la CIR hace cumplir", pl: "Prawo krajowe wyznacza cele, dyrektywa NIS2 wyznacza zasady, CIR egzekwuje" },
        { en: "GDPR sets goals, NIS2 sets rules, CIR enforces", de: "Die DSGVO setzt Ziele, NIS2 setzt Regeln, die CIR setzt durch", nl: "GDPR stelt doelen, NIS2 stelt regels, CIR handhaaft", fr: "Le GDPR fixe les objectifs, NIS2 fixe les règles, la CIR applique", it: "Il GDPR fissa gli obiettivi, NIS2 fissa le regole, la CIR fa rispettare", es: "El GDPR fija los objetivos, NIS2 fija las reglas, la CIR hace cumplir", pl: "GDPR wyznacza cele, NIS2 wyznacza zasady, CIR egzekwuje" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The chain is: EU Directive (NIS2) sets the goals, EU Regulation (CIR) sets the detailed technical rules, national law transposes the directive, and the national enforcer audits and fines.",
        de: "Die Kette lautet: EU-Richtlinie (NIS2) setzt die Ziele, EU-Verordnung (CIR) legt die detaillierten technischen Regeln fest, nationales Recht setzt die Richtlinie um, und die nationale Aufsichtsbehörde prüft und verhängt Bußgelder.",
        nl: "De keten is: EU-richtlijn (NIS2) stelt de doelen, EU-verordening (CIR) stelt de gedetailleerde technische regels, nationaal recht zet de richtlijn om, en de nationale handhaver controleert en legt boetes op.",
        fr: "La chaîne est la suivante : la directive de l'UE (NIS2) fixe les objectifs, le règlement de l'UE (CIR) fixe les règles techniques détaillées, le droit national transpose la directive, et l'autorité de contrôle nationale audite et inflige des amendes.",
        it: "La catena è: la direttiva dell'UE (NIS2) fissa gli obiettivi, il regolamento dell'UE (CIR) fissa le regole tecniche dettagliate, il diritto nazionale recepisce la direttiva e l'autorità di vigilanza nazionale verifica e commina le sanzioni.",
        es: "La cadena es: la directiva de la UE (NIS2) fija los objetivos, el reglamento de la UE (CIR) fija las reglas técnicas detalladas, el derecho nacional transpone la directiva, y la autoridad supervisora nacional audita e impone multas.",
        pl: "Łańcuch wygląda tak: dyrektywa UE (NIS2) wyznacza cele, rozporządzenie UE (CIR) wyznacza szczegółowe zasady techniczne, prawo krajowe transponuje dyrektywę, a krajowy organ nadzoru przeprowadza audyty i nakłada kary.",
      },
    },
    {
      id: "1.1.4",
      question: {
        en: "Why does the lesson say NIS1 was replaced?",
        de: "Warum wurde NIS1 laut dieser Lektion abgelöst?",
        nl: "Waarom werd NIS1 volgens deze les vervangen?",
        fr: "Pourquoi la leçon indique-t-elle que NIS1 a été remplacée ?",
        it: "Perché la lezione afferma che NIS1 è stata sostituita?",
        es: "¿Por qué dice la lección que NIS1 fue sustituida?",
        pl: "Dlaczego według lekcji NIS1 została zastąpiona?",
      },
      options: [
        { en: "NIS1 was too strict and costly for companies", de: "NIS1 war zu streng und kostspielig für Unternehmen", nl: "NIS1 was te streng en kostbaar voor bedrijven", fr: "NIS1 était trop stricte et coûteuse pour les entreprises", it: "NIS1 era troppo rigorosa e costosa per le imprese", es: "NIS1 era demasiado estricta y costosa para las empresas", pl: "NIS1 była zbyt rygorystyczna i kosztowna dla firm" },
        { en: "NIS1 only applied to digital infrastructure providers", de: "NIS1 galt nur für Anbieter digitaler Infrastruktur", nl: "NIS1 was alleen van toepassing op aanbieders van digitale infrastructuur", fr: "NIS1 ne s'appliquait qu'aux fournisseurs d'infrastructures numériques", it: "NIS1 si applicava solo ai fornitori di infrastrutture digitali", es: "NIS1 solo se aplicaba a los proveedores de infraestructura digital", pl: "NIS1 dotyczyła wyłącznie dostawców infrastruktury cyfrowej" },
        { en: "NIS1 was widely seen as inconsistent and weakly enforced, with almost no fines ever issued", de: "NIS1 wurde weithin als uneinheitlich und schwach durchgesetzt angesehen, wobei kaum jemals Bußgelder verhängt wurden", nl: "NIS1 werd algemeen beschouwd als inconsistent en zwak gehandhaafd, waarbij bijna nooit boetes werden opgelegd", fr: "NIS1 était largement perçue comme incohérente et faiblement appliquée, presque aucune amende n'ayant jamais été infligée", it: "NIS1 era ampiamente considerata incoerente e applicata in modo debole, con quasi nessuna sanzione mai comminata", es: "NIS1 se consideraba ampliamente incoherente y aplicada con escasa firmeza, sin que casi nunca se impusieran multas", pl: "NIS1 była powszechnie postrzegana jako niespójna i słabo egzekwowana, przy czym kary niemal nigdy nie były nakładane" },
        { en: "NIS1 was a regulation that could not be adapted to local laws", de: "NIS1 war eine Verordnung, die nicht an lokales Recht angepasst werden konnte", nl: "NIS1 was een verordening die niet kon worden aangepast aan lokale wetgeving", fr: "NIS1 était un règlement qui ne pouvait pas être adapté aux lois locales", it: "NIS1 era un regolamento che non poteva essere adattato alle leggi locali", es: "NIS1 era un reglamento que no podía adaptarse a las leyes locales", pl: "NIS1 była rozporządzeniem, którego nie można było dostosować do prawa lokalnego" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The lesson states that NIS1 was widely seen as inconsistent and weakly enforced - almost no fines were ever issued under NIS1 anywhere in the EU.",
        de: "Die Lektion stellt fest, dass NIS1 weithin als uneinheitlich und schwach durchgesetzt galt -- in der gesamten EU wurden unter NIS1 kaum Bußgelder verhängt.",
        nl: "De les stelt dat NIS1 algemeen werd gezien als inconsistent en zwak gehandhaafd — in de gehele EU werden onder NIS1 vrijwel nooit boetes opgelegd.",
        fr: "La leçon indique que NIS1 était largement perçue comme incohérente et faiblement appliquée. Presque aucune amende n'a jamais été infligée au titre de NIS1 dans l'ensemble de l'UE.",
        it: "La lezione afferma che NIS1 era ampiamente considerata incoerente e applicata in modo debole. Quasi nessuna sanzione è mai stata comminata in base a NIS1 in tutta l'UE.",
        es: "La lección señala que NIS1 se consideraba ampliamente incoherente y aplicada con escasa firmeza. Casi nunca se impusieron multas en virtud de NIS1 en toda la UE.",
        pl: "Lekcja stwierdza, że NIS1 była powszechnie postrzegana jako niespójna i słabo egzekwowana. W całej UE kary na podstawie NIS1 niemal nigdy nie były nakładane.",
      },
    },
  ],
});

export default quiz;
