import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.10",
  passingScore: 75,
  questions: [
    {
      id: "1.10.1",
      question: {
        en: "What does the 'all-hazards approach' in Article 21(1) require?",
        de: "Was verlangt der 'gefahrenübergreifende Ansatz' in Artikel 21 Absatz 1?",
        nl: "Wat vereist de 'all-hazards benadering' in artikel 21(1)?",
        fr: "Qu'exige l'« approche tous risques » de l'article 21(1) ?",
        it: "Cosa richiede l'«approccio multirischio» dell'articolo 21(1)?",
        es: "¿Qué exige el «enfoque de todos los peligros» del artículo 21(1)?",
        pl: "Czego wymaga „podejście uwzględniające wszystkie zagrożenia” z artykułu 21(1)?",
        cs: "Co vyžaduje 'přístup zohledňující všechna rizika' v článku 21(1)?",
        pt: "O que exige a 'abordagem de todos os perigos' no artigo 21(1)?",
        ro: "Ce impune 'abordarea bazată pe toate pericolele' din articolul 21(1)?",
      },
      options: [
        { en: "Protection only against cyber attacks", de: "Schutz nur gegen Cyberangriffe", nl: "Bescherming alleen tegen cyberaanvallen", fr: "Une protection uniquement contre les cyberattaques", it: "Protezione solo contro gli attacchi informatici", es: "Protección únicamente frente a los ciberataques", pl: "Ochronę wyłącznie przed cyberatakami", cs: "Ochranu pouze před kybernetickými útoky", pt: "Proteção apenas contra ciberataques", ro: "Protecție doar împotriva atacurilor cibernetice" },
        { en: "Protection against every threat to the systems - cyber attacks, physical threats, environmental events, supplier failures, insider threats, and human error", de: "Schutz gegen jede Bedrohung der Systeme -- Cyberangriffe, physische Bedrohungen, Umweltereignisse, Lieferantenausfälle, Insider-Bedrohungen und menschliche Fehler", nl: "Bescherming tegen elke bedreiging voor de systemen: cyberaanvallen, fysieke bedreigingen, omgevingsgebeurtenissen, leveranciersuitval, interne bedreigingen en menselijke fouten", fr: "Une protection contre toute menace pesant sur les systèmes : cyberattaques, menaces physiques, événements environnementaux, défaillances de fournisseurs, menaces internes et erreurs humaines", it: "Protezione contro ogni minaccia ai sistemi: attacchi informatici, minacce fisiche, eventi ambientali, guasti dei fornitori, minacce interne ed errori umani", es: "Protección frente a toda amenaza para los sistemas: ciberataques, amenazas físicas, eventos ambientales, fallos de proveedores, amenazas internas y errores humanos", pl: "Ochronę przed każdym zagrożeniem dla systemów: cyberatakami, zagrożeniami fizycznymi, zdarzeniami środowiskowymi, awariami dostawców, zagrożeniami wewnętrznymi i błędami ludzkimi", cs: "Ochranu před každou hrozbou pro systémy: kybernetickými útoky, fyzickými hrozbami, environmentálními událostmi, výpadky dodavatelů, vnitřními hrozbami a lidskou chybou", pt: "Proteção contra todas as ameaças aos sistemas: ciberataques, ameaças físicas, eventos ambientais, falhas de fornecedores, ameaças internas e erro humano", ro: "Protecție împotriva oricărei amenințări la adresa sistemelor: atacuri cibernetice, amenințări fizice, evenimente de mediu, defecțiuni ale furnizorilor, amenințări interne și eroare umană" },
        { en: "Protection only against threats that have occurred before", de: "Schutz nur gegen Bedrohungen, die bereits aufgetreten sind", nl: "Bescherming alleen tegen bedreigingen die eerder zijn voorgekomen", fr: "Une protection uniquement contre les menaces déjà survenues", it: "Protezione solo contro le minacce già verificatesi", es: "Protección únicamente frente a las amenazas que ya se han producido", pl: "Ochronę wyłącznie przed zagrożeniami, które już wystąpiły", cs: "Ochranu pouze před hrozbami, které se vyskytly v minulosti", pt: "Proteção apenas contra ameaças que já ocorreram anteriormente", ro: "Protecție doar împotriva amenințărilor care au survenit anterior" },
        { en: "Protection only against threats listed in the company's risk register", de: "Schutz nur gegen Bedrohungen, die im Risikoregister des Unternehmens aufgeführt sind", nl: "Bescherming alleen tegen bedreigingen die zijn opgenomen in het risicoregister van de vennootschap", fr: "Une protection uniquement contre les menaces figurant dans le registre des risques de l'entreprise", it: "Protezione solo contro le minacce elencate nel registro dei rischi dell'impresa", es: "Protección únicamente frente a las amenazas que figuran en el registro de riesgos de la empresa", pl: "Ochronę wyłącznie przed zagrożeniami wymienionymi w rejestrze ryzyka firmy", cs: "Ochranu pouze před hrozbami uvedenými v registru rizik společnosti", pt: "Proteção apenas contra ameaças constantes do registo de riscos da empresa", ro: "Protecție doar împotriva amenințărilor enumerate în registrul de riscuri al companiei" },
      ],
      correctIndex: 1,
      explanation: {
        en: "All-hazards means you must protect IT systems and their physical environment from every threat, not just hackers.",
        de: "Gefahrenübergreifend bedeutet, dass Sie IT-Systeme und deren physische Umgebung vor jeder Bedrohung schützen müssen, nicht nur vor Hackern.",
        nl: "All-hazards benadering betekent dat u IT-systemen en hun fysieke omgeving moet beschermen tegen elke bedreiging, niet alleen tegen hackers.",
        fr: "L'approche tous risques signifie que vous devez protéger les systèmes informatiques et leur environnement physique contre toute menace, et pas seulement contre les pirates.",
        it: "L'approccio multirischio significa che dovete proteggere i sistemi informatici e il loro ambiente fisico da ogni minaccia, non solo dagli hacker.",
        es: "El enfoque de todos los peligros significa que debe proteger los sistemas informáticos y su entorno físico frente a toda amenaza, no solo frente a los piratas informáticos.",
        pl: "Podejście uwzględniające wszystkie zagrożenia oznacza, że muszą Państwo chronić systemy informatyczne i ich środowisko fizyczne przed każdym zagrożeniem, nie tylko przed hakerami.",
        cs: "Přístup zohledňující všechna rizika znamená, že musíte chránit IT systémy a jejich fyzické prostředí před každou hrozbou, nejen před hackery.",
        pt: "A abordagem de todos os perigos significa que tem de proteger os sistemas de TI e o seu ambiente físico contra todas as ameaças, não apenas contra os piratas informáticos.",
        ro: "Abordarea bazată pe toate pericolele înseamnă că trebuie să protejați sistemele IT și mediul lor fizic împotriva oricărei amenințări, nu doar împotriva hackerilor.",
      },
    },
    {
      id: "1.10.2",
      question: {
        en: "Against what point in time does the auditor judge whether controls meet the 'state of the art'?",
        de: "Zu welchem Zeitpunkt beurteilt der Prüfer, ob Kontrollen dem 'Stand der Technik' entsprechen?",
        nl: "Aan de hand van welk tijdstip beoordeelt de auditor of maatregelen voldoen aan de 'stand van de techniek'?",
        fr: "À quel moment l'auditeur juge-t-il si les contrôles correspondent à l'« état de l'art » ?",
        it: "A quale momento il revisore valuta se i controlli rispondono allo 'stato dell'arte'?",
        es: "¿Con respecto a qué momento juzga el auditor si los controles cumplen el 'estado de la técnica'?",
        pl: "Względem jakiego momentu audytor ocenia, czy kontrole odpowiadają „aktualnemu stanowi wiedzy technicznej”?",
        cs: "K jakému okamžiku auditor posuzuje, zda opatření odpovídají 'stavu techniky'?",
        pt: "Em relação a que momento avalia o auditor se os controlos correspondem ao 'estado da técnica'?",
        ro: "În raport cu ce moment evaluează auditorul dacă controalele corespund 'stadiului actual al tehnicii'?",
      },
      options: [
        { en: "When the company was first founded", de: "Zum Zeitpunkt der Unternehmensgründung", nl: "Op het moment dat de vennootschap werd opgericht", fr: "Au moment de la création de l'entreprise", it: "Al momento della costituzione dell'impresa", es: "En el momento de la fundación de la empresa", pl: "W momencie założenia firmy", cs: "K okamžiku, kdy byla společnost založena", pt: "Em relação ao momento em que a empresa foi fundada", ro: "În raport cu momentul în care a fost înființată compania" },
        { en: "When the controls were first implemented", de: "Zum Zeitpunkt der erstmaligen Implementierung der Kontrollen", nl: "Op het moment dat de maatregelen voor het eerst werden geïmplementeerd", fr: "Au moment de la première mise en œuvre des contrôles", it: "Al momento della prima attuazione dei controlli", es: "En el momento en que se implementaron los controles por primera vez", pl: "W momencie pierwszego wdrożenia kontroli", cs: "K okamžiku, kdy byla opatření poprvé zavedena", pt: "Em relação ao momento em que os controlos foram inicialmente implementados", ro: "În raport cu momentul în care controalele au fost implementate prima dată" },
        { en: "The standards current at the time of the audit", de: "Die zum Zeitpunkt der Prüfung geltenden Standards", nl: "De normen die van kracht zijn op het moment van de audit", fr: "Les normes en vigueur au moment de l'audit", it: "Gli standard vigenti al momento dell'audit", es: "Las normas vigentes en el momento de la auditoría", pl: "Normy obowiązujące w momencie audytu", cs: "K normám platným v době auditu", pt: "Em relação às normas em vigor no momento da auditoria", ro: "În raport cu standardele în vigoare la momentul auditului" },
        { en: "The date the NIS2 Directive entered into force", de: "Das Datum des Inkrafttretens der NIS2-Richtlinie", nl: "De datum waarop de NIS2-richtlijn in werking is getreden", fr: "La date d'entrée en vigueur de la directive NIS2", it: "La data di entrata in vigore della direttiva NIS2", es: "La fecha de entrada en vigor de la Directiva NIS2", pl: "Data wejścia w życie dyrektywy NIS2", cs: "K datu, kdy směrnice NIS2 vstoupila v platnost", pt: "Em relação à data de entrada em vigor da Diretiva NIS2", ro: "În raport cu data intrării în vigoare a Directivei NIS2" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The auditor judges against the standards current at the time of audit, not when you first implemented the controls.",
        de: "Der Prüfer beurteilt anhand der zum Prüfungszeitpunkt geltenden Standards, nicht anhand des Zeitpunkts, zu dem Sie die Kontrollen erstmals implementiert haben.",
        nl: "De auditor beoordeelt aan de hand van de normen die van kracht zijn op het moment van de audit, niet op het moment dat u de maatregelen voor het eerst heeft geïmplementeerd.",
        fr: "L'auditeur juge par rapport aux normes en vigueur au moment de l'audit, et non au moment où vous avez mis en œuvre les contrôles pour la première fois.",
        it: "Il revisore valuta in base agli standard vigenti al momento dell'audit, non al momento in cui avete attuato i controlli per la prima volta.",
        es: "El auditor juzga con respecto a las normas vigentes en el momento de la auditoría, no en el momento en que implementó los controles por primera vez.",
        pl: "Audytor ocenia względem norm obowiązujących w momencie audytu, a nie w momencie pierwszego wdrożenia kontroli.",
        cs: "Auditor posuzuje podle norem platných v době auditu, nikoli podle norem platných v době, kdy jste opatření poprvé zavedli.",
        pt: "O auditor avalia em relação às normas em vigor no momento da auditoria, e não no momento em que implementou inicialmente os controlos.",
        ro: "Auditorul evaluează în raport cu standardele în vigoare la momentul auditului, nu cu cele de la momentul implementării inițiale a controalelor.",
      },
    },
    {
      id: "1.10.3",
      question: {
        en: "How often should controls be reviewed at minimum?",
        de: "Wie oft sollten Kontrollen mindestens überprüft werden?",
        nl: "Hoe vaak moeten maatregelen minimaal worden gereviewed?",
        fr: "À quelle fréquence minimale les contrôles doivent-ils être réexaminés ?",
        it: "Con quale frequenza minima dovrebbero essere riesaminati i controlli?",
        es: "¿Con qué frecuencia mínima deben revisarse los controles?",
        pl: "Jak często należy co najmniej przeglądać kontrole?",
        cs: "Jak často by se měla opatření přezkoumávat minimálně?",
        pt: "Com que frequência mínima devem ser revistos os controlos?",
        ro: "Cât de des trebuie revizuite controalele, ca minim?",
      },
      options: [
        { en: "Every five years", de: "Alle fünf Jahre", nl: "Elke vijf jaar", fr: "Tous les cinq ans", it: "Ogni cinque anni", es: "Cada cinco años", pl: "Co pięć lat", cs: "Každých pět let", pt: "De cinco em cinco anos", ro: "O dată la cinci ani" },
        { en: "Only when an incident occurs", de: "Nur wenn ein Vorfall eintritt", nl: "Alleen wanneer er een incident plaatsvindt", fr: "Uniquement lorsqu'un incident survient", it: "Solo quando si verifica un incidente", es: "Solo cuando se produce un incidente", pl: "Tylko gdy wystąpi incydent", cs: "Pouze když dojde k incidentu", pt: "Apenas quando ocorre um incidente", ro: "Doar când survine un incident" },
        { en: "Annually, and whenever relevant standards or business change significantly", de: "Jährlich sowie bei jeder wesentlichen Änderung relevanter Standards oder des Geschäftsbetriebs", nl: "Jaarlijks, en wanneer relevante normen of de bedrijfsvoering ingrijpend veranderen", fr: "Chaque année, et chaque fois que les normes pertinentes ou l'activité changent de manière significative", it: "Annualmente e ogni volta che gli standard pertinenti o l'attività cambiano in modo significativo", es: "Anualmente, y siempre que las normas pertinentes o la actividad cambien de forma significativa", pl: "Co roku oraz zawsze, gdy istotnie zmieniają się odpowiednie normy lub działalność", cs: "Ročně a vždy, když se významně změní příslušné normy nebo podnikání", pt: "Anualmente e sempre que as normas relevantes ou o negócio se alterem significativamente", ro: "Anual și ori de câte ori standardele relevante sau activitatea se modifică semnificativ" },
        { en: "Once, at the time of initial implementation", de: "Einmalig zum Zeitpunkt der erstmaligen Implementierung", nl: "Eenmalig op het moment van eerste implementatie", fr: "Une seule fois, au moment de la mise en œuvre initiale", it: "Una sola volta, al momento dell'attuazione iniziale", es: "Una sola vez, en el momento de la implementación inicial", pl: "Jednorazowo, w momencie pierwszego wdrożenia", cs: "Jednou, v okamžiku počátečního zavedení", pt: "Uma vez, no momento da implementação inicial", ro: "O singură dată, la momentul implementării inițiale" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Your controls need a review cycle - at minimum annually, and whenever relevant standards or your business change significantly.",
        de: "Ihre Kontrollen benötigen einen Überprüfungszyklus -- mindestens jährlich sowie bei jeder wesentlichen Änderung relevanter Standards oder Ihres Geschäftsbetriebs.",
        nl: "Uw maatregelen hebben een reviewcyclus nodig: minimaal jaarlijks, en wanneer relevante normen of uw bedrijfsvoering ingrijpend veranderen.",
        fr: "Vos contrôles nécessitent un cycle de réexamen : au minimum chaque année, et chaque fois que les normes pertinentes ou votre activité changent de manière significative.",
        it: "I vostri controlli necessitano di un ciclo di riesame: almeno annualmente e ogni volta che gli standard pertinenti o la vostra attività cambiano in modo significativo.",
        es: "Sus controles necesitan un ciclo de revisión: como mínimo anualmente, y siempre que las normas pertinentes o su actividad cambien de forma significativa.",
        pl: "Państwa kontrole wymagają cyklu przeglądu: co najmniej raz w roku oraz zawsze, gdy istotnie zmieniają się odpowiednie normy lub Państwa działalność.",
        cs: "Vaše opatření potřebují cyklus přezkumu: minimálně ročně a vždy, když se významně změní příslušné normy nebo vaše podnikání.",
        pt: "Os seus controlos precisam de um ciclo de revisão: no mínimo anualmente e sempre que as normas relevantes ou o seu negócio se alterem significativamente.",
        ro: "Controalele dumneavoastră au nevoie de un ciclu de revizuire: cel puțin anual și ori de câte ori standardele relevante sau activitatea dumneavoastră se modifică semnificativ.",
      },
    },
  ],
});

export default quiz;
