import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.11",
  passingScore: 75,
  questions: [
    {
      id: "1.11.1",
      question: {
        en: "What is the financial threshold for a significant incident under CIR 2024/2690?",
        de: "Was ist die finanzielle Schwelle für einen erheblichen Sicherheitsvorfall gemäß CIR 2024/2690?",
        nl: "Wat is de financiële drempel voor een significant incident onder CIR 2024/2690?",
        fr: "Quel est le seuil financier d'un incident important au titre de la CIR 2024/2690 ?",
        it: "Qual è la soglia finanziaria per un incidente significativo ai sensi della CIR 2024/2690?",
        es: "¿Cuál es el umbral financiero de un incidente significativo en virtud de la CIR 2024/2690?",
        pl: "Jaki jest próg finansowy poważnego incydentu na podstawie CIR 2024/2690?",
      },
      options: [
        { en: "One million euros or 10% of turnover, whichever is higher", de: "Eine Million Euro oder 10 % des Umsatzes, je nachdem welcher Betrag höher ist", nl: "Één miljoen euro of 10% van de omzet, afhankelijk van welk bedrag hoger is", fr: "Un million d'euros ou 10 % du chiffre d'affaires, le montant le plus élevé étant retenu", it: "Un milione di euro o il 10% del fatturato, se superiore", es: "Un millón de euros o el 10% de la facturación, si esta cantidad es mayor", pl: "Milion euro lub 10% obrotu, w zależności od tego, która kwota jest wyższa" },
        { en: "Five hundred thousand euros or 5% of turnover, whichever is lower", de: "Fünfhunderttausend Euro oder 5 % des Umsatzes, je nachdem welcher Betrag niedriger ist", nl: "Vijfhonderdduizend euro of 5% van de omzet, afhankelijk van welk bedrag lager is", fr: "Cinq cent mille euros ou 5 % du chiffre d'affaires, le montant le plus faible étant retenu", it: "Cinquecentomila euro o il 5% del fatturato, se inferiore", es: "Quinientos mil euros o el 5% de la facturación, si esta cantidad es menor", pl: "Pięćset tysięcy euro lub 5% obrotu, w zależności od tego, która kwota jest niższa" },
        { en: "One hundred thousand euros flat", de: "Pauschal einhunderttausend Euro", nl: "Honderdduizend euro vlak", fr: "Cent mille euros forfaitaires", it: "Centomila euro forfettari", es: "Cien mil euros a tanto alzado", pl: "Sto tysięcy euro ryczałtem" },
        { en: "Ten million euros or 2% of turnover", de: "Zehn Millionen Euro oder 2 % des Umsatzes", nl: "Tien miljoen euro of 2% van de omzet", fr: "Dix millions d'euros ou 2 % du chiffre d'affaires", it: "Dieci milioni di euro o il 2% del fatturato", es: "Diez millones de euros o el 2% de la facturación", pl: "Dziesięć milionów euro lub 2% obrotu" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Direct financial loss exceeds five hundred thousand euros or five percent of total annual turnover, whichever is lower.",
        de: "Der direkte finanzielle Schaden übersteigt fünfhunderttausend Euro oder fünf Prozent des gesamten Jahresumsatzes, je nachdem welcher Betrag niedriger ist.",
        nl: "Het directe financiële verlies overschrijdt vijfhonderdduizend euro of vijf procent van de totale jaaromzet, afhankelijk van welk bedrag lager is.",
        fr: "La perte financière directe dépasse cinq cent mille euros ou cinq pour cent du chiffre d'affaires annuel total, le montant le plus faible étant retenu.",
        it: "La perdita finanziaria diretta supera cinquecentomila euro o il cinque per cento del fatturato annuo totale, se inferiore.",
        es: "La pérdida financiera directa supera los quinientos mil euros o el cinco por ciento de la facturación anual total, si esta cantidad es menor.",
        pl: "Bezpośrednia strata finansowa przekracza pięćset tysięcy euro lub pięć procent całkowitego rocznego obrotu, w zależności od tego, która kwota jest niższa.",
      },
    },
    {
      id: "1.11.2",
      question: {
        en: "What are the three stages of the reporting cascade and their deadlines?",
        de: "Was sind die drei Stufen der Meldekaskade und ihre Fristen?",
        nl: "Wat zijn de drie stadia van de meldingscascade en hun deadlines?",
        fr: "Quelles sont les trois étapes de la cascade de notification et leurs délais ?",
        it: "Quali sono le tre fasi della cascata di notifica e le relative scadenze?",
        es: "¿Cuáles son las tres etapas de la cascada de notificación y sus plazos?",
        pl: "Jakie są trzy etapy kaskady zgłaszania i ich terminy?",
      },
      options: [
        { en: "Initial report (48h), detailed report (1 week), final report (3 months)", de: "Erstmeldung (48 Std.), detaillierter Bericht (1 Woche), Abschlussbericht (3 Monate)", nl: "Eerste melding (48u), gedetailleerd rapport (1 week), eindrapport (3 maanden)", fr: "Rapport initial (48 h), rapport détaillé (1 semaine), rapport final (3 mois)", it: "Rapporto iniziale (48 h), rapporto dettagliato (1 settimana), rapporto finale (3 mesi)", es: "Informe inicial (48 h), informe detallado (1 semana), informe final (3 meses)", pl: "Raport wstępny (48 godz.), raport szczegółowy (1 tydzień), raport końcowy (3 miesiące)" },
        { en: "Early warning (24h), incident notification (72h), final report (1 month)", de: "Frühwarnung (24 Std.), Vorfallsmeldung (72 Std.), Abschlussbericht (1 Monat)", nl: "Vroegtijdige waarschuwing (24u), incidentmelding (72u), eindrapport (1 maand)", fr: "Alerte précoce (24 h), notification d'incident (72 h), rapport final (1 mois)", it: "Preallarme (24 h), notifica dell'incidente (72 h), rapporto finale (1 mese)", es: "Alerta temprana (24 h), notificación del incidente (72 h), informe final (1 mes)", pl: "Wczesne ostrzeżenie (24 godz.), zgłoszenie incydentu (72 godz.), raport końcowy (1 miesiąc)" },
        { en: "Alert (12h), notification (48h), closure report (2 weeks)", de: "Alarm (12 Std.), Benachrichtigung (48 Std.), Abschlussbericht (2 Wochen)", nl: "Alarm (12u), kennisgeving (48u), afsluitingsrapport (2 weken)", fr: "Alerte (12 h), notification (48 h), rapport de clôture (2 semaines)", it: "Allerta (12 h), notifica (48 h), rapporto di chiusura (2 settimane)", es: "Alerta (12 h), notificación (48 h), informe de cierre (2 semanas)", pl: "Alert (12 godz.), powiadomienie (48 godz.), raport zamykający (2 tygodnie)" },
        { en: "Detection (24h), assessment (1 week), resolution (1 month)", de: "Erkennung (24 Std.), Bewertung (1 Woche), Behebung (1 Monat)", nl: "Detectie (24u), beoordeling (1 week), afhandeling (1 maand)", fr: "Détection (24 h), évaluation (1 semaine), résolution (1 mois)", it: "Rilevamento (24 h), valutazione (1 settimana), risoluzione (1 mese)", es: "Detección (24 h), evaluación (1 semana), resolución (1 mes)", pl: "Wykrycie (24 godz.), ocena (1 tydzień), rozwiązanie (1 miesiąc)" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The cascade is: early warning within 24 hours, incident notification within 72 hours, and final report within one month.",
        de: "Die Kaskade lautet: Frühwarnung innerhalb von 24 Stunden, Vorfallsmeldung innerhalb von 72 Stunden und Abschlussbericht innerhalb eines Monats.",
        nl: "De cascade luidt: vroegtijdige waarschuwing binnen 24 uur, incidentmelding binnen 72 uur en eindrapport binnen één maand.",
        fr: "La cascade est la suivante : alerte précoce dans les 24 heures, notification d'incident dans les 72 heures et rapport final dans un délai d'un mois.",
        it: "La cascata è: preallarme entro 24 ore, notifica dell'incidente entro 72 ore e rapporto finale entro un mese.",
        es: "La cascada es: alerta temprana en un plazo de 24 horas, notificación del incidente en un plazo de 72 horas e informe final en un plazo de un mes.",
        pl: "Kaskada wygląda tak: wczesne ostrzeżenie w ciągu 24 godzin, zgłoszenie incydentu w ciągu 72 godzin i raport końcowy w ciągu jednego miesiąca.",
      },
    },
    {
      id: "1.11.3",
      question: {
        en: "What does Article 4 of the implementing regulation say about recurring incidents?",
        de: "Was sagt Artikel 4 der Durchführungsverordnung über wiederkehrende Vorfälle?",
        nl: "Wat zegt artikel 4 van de uitvoeringsverordening over terugkerende incidenten?",
        fr: "Que dit l'article 4 du règlement d'exécution au sujet des incidents récurrents ?",
        it: "Cosa dice l'articolo 4 del regolamento di esecuzione sugli incidenti ricorrenti?",
        es: "¿Qué dice el artículo 4 del reglamento de ejecución sobre los incidentes recurrentes?",
        pl: "Co mówi artykuł 4 rozporządzenia wykonawczego o incydentach powtarzających się?",
      },
      options: [
        { en: "Recurring incidents are exempt from reporting", de: "Wiederkehrende Vorfälle sind von der Meldepflicht befreit", nl: "Terugkerende incidenten zijn vrijgesteld van meldingsplicht", fr: "Les incidents récurrents sont exemptés de notification", it: "Gli incidenti ricorrenti sono esentati dalla notifica", es: "Los incidentes recurrentes están exentos de notificación", pl: "Incydenty powtarzające się są zwolnione z obowiązku zgłaszania" },
        { en: "Each recurring incident must be reported separately", de: "Jeder wiederkehrende Vorfall muss einzeln gemeldet werden", nl: "Elk terugkerend incident moet afzonderlijk worden gemeld", fr: "Chaque incident récurrent doit être notifié séparément", it: "Ogni incidente ricorrente deve essere notificato separatamente", es: "Cada incidente recurrente debe notificarse por separado", pl: "Każdy incydent powtarzający się musi być zgłaszany osobno" },
        { en: "Two or more incidents with the same root cause within six months that together cross the threshold count as one significant incident", de: "Zwei oder mehr Vorfälle mit derselben Ursache innerhalb von sechs Monaten, die zusammen die Schwelle überschreiten, gelten als ein erheblicher Sicherheitsvorfall", nl: "Twee of meer incidenten met dezelfde grondoorzaak binnen zes maanden die samen de drempel overschrijden, tellen als één significant incident", fr: "Deux incidents ou plus ayant la même cause profonde sur une période de six mois et franchissant ensemble le seuil comptent comme un seul incident important", it: "Due o più incidenti con la stessa causa principale entro sei mesi che insieme superano la soglia contano come un unico incidente significativo", es: "Dos o más incidentes con la misma causa raíz en un plazo de seis meses que en conjunto superen el umbral cuentan como un único incidente significativo", pl: "Dwa lub więcej incydentów o tej samej przyczynie źródłowej w ciągu sześciu miesięcy, które łącznie przekraczają próg, liczą się jako jeden poważny incydent" },
        { en: "Only the third recurring incident triggers a report", de: "Erst der dritte wiederkehrende Vorfall löst eine Meldung aus", nl: "Alleen het derde terugkerende incident leidt tot een melding", fr: "Seul le troisième incident récurrent déclenche une notification", it: "Solo il terzo incidente ricorrente attiva una notifica", es: "Solo el tercer incidente recurrente activa una notificación", pl: "Dopiero trzeci incydent powtarzający się powoduje obowiązek zgłoszenia" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Two or more incidents with the same apparent root cause, occurring within six months, that together cross the financial threshold are treated as one significant incident.",
        de: "Zwei oder mehr Vorfälle mit derselben offensichtlichen Ursache, die innerhalb von sechs Monaten auftreten und zusammen die finanzielle Schwelle überschreiten, werden als ein erheblicher Sicherheitsvorfall behandelt.",
        nl: "Twee of meer incidenten met dezelfde vermoedelijke grondoorzaak, die binnen zes maanden plaatsvinden en samen de financiële drempel overschrijden, worden behandeld als één significant incident.",
        fr: "Deux incidents ou plus ayant la même cause profonde apparente, survenant dans un délai de six mois et franchissant ensemble le seuil financier, sont traités comme un seul incident important.",
        it: "Due o più incidenti con la stessa apparente causa principale, verificatisi entro sei mesi e che insieme superano la soglia finanziaria, sono trattati come un unico incidente significativo.",
        es: "Dos o más incidentes con la misma causa raíz aparente, ocurridos en un plazo de seis meses y que en conjunto superan el umbral financiero, se tratan como un único incidente significativo.",
        pl: "Dwa lub więcej incydentów o tej samej pozornej przyczynie źródłowej, występujących w ciągu sześciu miesięcy i łącznie przekraczających próg finansowy, traktuje się jako jeden poważny incydent.",
      },
    },
    {
      id: "1.11.4",
      question: {
        en: "Is late reporting a separate violation?",
        de: "Ist eine verspätete Meldung ein eigenständiger Verstoß?",
        nl: "Is te late melding een afzonderlijke overtreding?",
        fr: "Une notification tardive constitue-t-elle une violation distincte ?",
        it: "Una notifica tardiva costituisce una violazione distinta?",
        es: "¿Es la notificación tardía una infracción independiente?",
        pl: "Czy spóźnione zgłoszenie stanowi odrębne naruszenie?",
      },
      options: [
        { en: "No, it is only considered as part of the incident assessment", de: "Nein, sie wird nur im Rahmen der Vorfallsbewertung berücksichtigt", nl: "Nee, het wordt alleen meegewogen als onderdeel van de incidentbeoordeling", fr: "Non, elle n'est prise en compte que dans le cadre de l'évaluation de l'incident", it: "No, viene considerata solo nell'ambito della valutazione dell'incidente", es: "No, solo se tiene en cuenta como parte de la evaluación del incidente", pl: "Nie, jest uwzględniane wyłącznie w ramach oceny incydentu" },
        { en: "Only if the delay exceeds one week", de: "Nur wenn die Verzögerung eine Woche überschreitet", nl: "Alleen als de vertraging meer dan één week bedraagt", fr: "Uniquement si le retard dépasse une semaine", it: "Solo se il ritardo supera una settimana", es: "Solo si el retraso supera una semana", pl: "Tylko jeśli opóźnienie przekracza jeden tydzień" },
        { en: "Yes, late reporting is a separate sanctionable violation", de: "Ja, eine verspätete Meldung ist ein eigenständiger, sanktionsfähiger Verstoß", nl: "Ja, te late melding is een afzonderlijke, sanctioneerbare overtreding", fr: "Oui, une notification tardive est une violation distincte passible de sanction", it: "Sì, una notifica tardiva è una violazione distinta sanzionabile", es: "Sí, la notificación tardía es una infracción independiente sancionable", pl: "Tak, spóźnione zgłoszenie jest odrębnym naruszeniem podlegającym sankcji" },
        { en: "Only for Essential entities", de: "Nur für wesentliche Einrichtungen", nl: "Alleen voor essentiële entiteiten", fr: "Uniquement pour les entités essentielles", it: "Solo per i soggetti essenziali", es: "Solo para las entidades esenciales", pl: "Tylko dla podmiotów kluczowych" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Late reporting is a separate sanctionable violation. Skipping the early warning because the situation is unclear means two violations: the incident itself and the reporting failure.",
        de: "Verspätete Meldung ist ein eigenständiger, sanktionsfähiger Verstoß. Die Frühwarnung auszulassen, weil die Situation unklar ist, bedeutet zwei Verstöße: den Vorfall selbst und das Meldeversäumnis.",
        nl: "Te late melding is een afzonderlijke, sanctioneerbare overtreding. De vroegtijdige waarschuwing overslaan omdat de situatie onduidelijk is, betekent twee overtredingen: het incident zelf en het meldingsverzuim.",
        fr: "Une notification tardive est une violation distincte passible de sanction. Omettre l'alerte précoce parce que la situation est floue entraîne deux violations : l'incident lui-même et le manquement à la notification.",
        it: "Una notifica tardiva è una violazione distinta sanzionabile. Saltare il preallarme perché la situazione è poco chiara comporta due violazioni: l'incidente stesso e il mancato adempimento dell'obbligo di notifica.",
        es: "La notificación tardía es una infracción independiente sancionable. Omitir la alerta temprana porque la situación no está clara supone dos infracciones: el propio incidente y el incumplimiento de la notificación.",
        pl: "Spóźnione zgłoszenie jest odrębnym naruszeniem podlegającym sankcji. Pominięcie wczesnego ostrzeżenia z powodu niejasnej sytuacji oznacza dwa naruszenia: sam incydent oraz uchybienie obowiązkowi zgłoszenia.",
      },
    },
  ],
});

export default quiz;
