import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.12",
  passingScore: 75,
  questions: [
    {
      id: "1.12.1",
      question: {
        en: "What is the difference between customer notification under Article 23(1) and an order under Article 23(7)?",
        de: "Was ist der Unterschied zwischen der Kundenbenachrichtigung nach Artikel 23 Absatz 1 und einer Anordnung nach Artikel 23 Absatz 7?",
        nl: "Wat is het verschil tussen klantnotificatie op grond van artikel 23(1) en een bevel op grond van artikel 23(7)?",
        fr: "Quelle est la différence entre la notification aux clients au titre de l'article 23(1) et une injonction au titre de l'article 23(7) ?",
        it: "Qual è la differenza tra la notifica ai clienti ai sensi dell'articolo 23(1) e un ordine ai sensi dell'articolo 23(7)?",
        es: "¿Cuál es la diferencia entre la notificación a los clientes del artículo 23(1) y una orden del artículo 23(7)?",
        pl: "Jaka jest różnica między powiadomieniem klientów na podstawie artykułu 23(1) a nakazem na podstawie artykułu 23(7)?",
        cs: "Jaký je rozdíl mezi oznámením zákazníkům podle článku 23(1) a příkazem podle článku 23(7)?",
        pt: "Qual é a diferença entre a notificação aos clientes do artigo 23(1) e uma ordem do artigo 23(7)?",
        ro: "Care este diferența dintre notificarea clienților conform articolului 23(1) și o dispoziție conform articolului 23(7)?",
      },
      options: [
        {
          en: "Article 23(1) is a duty towards the regulator only; Article 23(7) is a duty towards customers",
          de: "Artikel 23 Absatz 1 ist nur eine Pflicht gegenüber der Aufsicht; Artikel 23 Absatz 7 ist eine Pflicht gegenüber Kunden",
          nl: "Artikel 23(1) is alleen een verplichting tegenover de toezichthouder; artikel 23(7) is een verplichting tegenover klanten",
          fr: "L'article 23(1) est une obligation envers l'autorité de contrôle uniquement ; l'article 23(7) est une obligation envers les clients",
          it: "L'articolo 23(1) è un obbligo solo nei confronti dell'autorità di vigilanza; l'articolo 23(7) è un obbligo nei confronti dei clienti",
          es: "El artículo 23(1) es un deber solo frente a la autoridad reguladora; el artículo 23(7) es un deber frente a los clientes",
          pl: "Artykuł 23(1) to obowiązek wyłącznie wobec organu nadzoru; artykuł 23(7) to obowiązek wobec klientów",
          cs: "Článek 23(1) je povinnost pouze vůči regulačnímu orgánu, článek 23(7) je povinnost vůči zákazníkům",
          pt: "O artigo 23(1) é um dever apenas perante a autoridade reguladora, o artigo 23(7) é um dever perante os clientes",
          ro: "Articolul 23(1) este o obligație doar față de autoritatea de reglementare, articolul 23(7) este o obligație față de clienți",
        },
        {
          en: "Under Article 23(1) the entity notifies its customers itself, where appropriate; under Article 23(7) the authority can inform the public or require the entity to do so",
          de: "Nach Artikel 23 Absatz 1 unterrichtet die Einrichtung ihre Kunden gegebenenfalls selbst; nach Artikel 23 Absatz 7 kann die Behörde die Öffentlichkeit informieren oder die Einrichtung dazu verpflichten",
          nl: "Op grond van artikel 23(1) stelt de entiteit haar klanten in voorkomend geval zelf in kennis; op grond van artikel 23(7) kan de autoriteit het publiek informeren of van de entiteit verlangen dat zij dit doet",
          fr: "Au titre de l'article 23(1), l'entité notifie elle-même ses clients, le cas échéant ; au titre de l'article 23(7), l'autorité peut informer le public ou exiger de l'entité qu'elle le fasse",
          it: "Ai sensi dell'articolo 23(1) il soggetto informa direttamente i propri clienti, se opportuno; ai sensi dell'articolo 23(7) l'autorità può informare il pubblico o imporre al soggetto di farlo",
          es: "Según el artículo 23(1), la entidad notifica ella misma a sus clientes, cuando proceda; según el artículo 23(7), la autoridad puede informar al público o exigir a la entidad que lo haga",
          pl: "Na podstawie artykułu 23(1) podmiot w stosownych przypadkach sam powiadamia swoich klientów; na podstawie artykułu 23(7) organ może poinformować społeczeństwo lub zobowiązać do tego podmiot",
          cs: "Podle článku 23(1) subjekt v příslušných případech sám informuje své zákazníky, podle článku 23(7) může orgán informovat veřejnost nebo požadovat, aby tak učinil subjekt",
          pt: "Nos termos do artigo 23(1), a própria entidade notifica os seus clientes, se for caso disso; nos termos do artigo 23(7), a autoridade pode informar o público ou exigir que a entidade o faça",
          ro: "Conform articolului 23(1), entitatea își notifică ea însăși clienții, dacă este cazul; conform articolului 23(7), autoritatea poate informa publicul sau poate solicita entității să facă acest lucru",
        },
        {
          en: "Article 23(1) applies only to Essential entities; Article 23(7) applies to all",
          de: "Artikel 23 Absatz 1 gilt nur für wesentliche Einrichtungen; Artikel 23 Absatz 7 gilt für alle",
          nl: "Artikel 23(1) geldt alleen voor essentiële entiteiten; artikel 23(7) geldt voor alle entiteiten",
          fr: "L'article 23(1) ne s'applique qu'aux entités essentielles ; l'article 23(7) s'applique à toutes",
          it: "L'articolo 23(1) si applica solo ai soggetti essenziali; l'articolo 23(7) si applica a tutti",
          es: "El artículo 23(1) se aplica únicamente a las entidades esenciales; el artículo 23(7) se aplica a todas",
          pl: "Artykuł 23(1) dotyczy wyłącznie podmiotów kluczowych; artykuł 23(7) dotyczy wszystkich",
          cs: "Článek 23(1) se vztahuje pouze na základní subjekty, článek 23(7) na všechny",
          pt: "O artigo 23(1) aplica-se apenas a entidades essenciais, o artigo 23(7) aplica-se a todas",
          ro: "Articolul 23(1) se aplică doar entităților esențiale, articolul 23(7) se aplică tuturor",
        },
        {
          en: "There is no difference; they are the same duty",
          de: "Es gibt keinen Unterschied; es handelt sich um dieselbe Pflicht",
          nl: "Er is geen verschil; het betreft dezelfde verplichting",
          fr: "Il n'y a aucune différence ; il s'agit de la même obligation",
          it: "Non c'è alcuna differenza; si tratta dello stesso obbligo",
          es: "No hay diferencia; se trata del mismo deber",
          pl: "Nie ma różnicy; jest to ten sam obowiązek",
          cs: "Není v tom žádný rozdíl, jde o tutéž povinnost",
          pt: "Não há diferença, é o mesmo dever",
          ro: "Nu există nicio diferență, este aceeași obligație",
        },
      ],
      correctIndex: 1,
      explanation: {
        en: "Under Article 23(1) the entity itself notifies the recipients of its services, where appropriate, about significant incidents likely to affect them. Under Article 23(7) the CSIRT or competent authority can inform the public or require the entity to do so. In Germany, § 35(1) BSIG makes the customer notice an order of the BSI.",
        de: "Nach Artikel 23 Absatz 1 unterrichtet die Einrichtung gegebenenfalls selbst die Empfänger ihrer Dienste über erhebliche Sicherheitsvorfälle, die sie beeinträchtigen könnten. Nach Artikel 23 Absatz 7 kann das CSIRT oder die zuständige Behörde die Öffentlichkeit informieren oder die Einrichtung dazu verpflichten. In Deutschland ordnet das BSI die Unterrichtung der Kunden an (§ 35 Abs. 1 BSIG).",
        nl: "Op grond van artikel 23(1) stelt de entiteit zelf de ontvangers van haar diensten in voorkomend geval in kennis van significante incidenten die hen kunnen treffen. Op grond van artikel 23(7) kan het CSIRT of de bevoegde autoriteit het publiek informeren of van de entiteit verlangen dat zij dit doet. In Duitsland maakt § 35(1) BSIG de klantnotificatie tot een bevel van het BSI.",
        fr: "Au titre de l'article 23(1), l'entité notifie elle-même, le cas échéant, aux destinataires de ses services les incidents importants susceptibles de les affecter. Au titre de l'article 23(7), le CSIRT ou l'autorité compétente peut informer le public ou exiger de l'entité qu'elle le fasse. En Allemagne, le § 35(1) BSIG fait de la notification aux clients une injonction du BSI.",
        it: "Ai sensi dell'articolo 23(1) il soggetto stesso notifica, se opportuno, ai destinatari dei suoi servizi gli incidenti significativi che possono ripercuotersi su di loro. Ai sensi dell'articolo 23(7) il CSIRT o l'autorità competente può informare il pubblico o imporre al soggetto di farlo. In Germania il § 35(1) BSIG fa della notifica ai clienti un ordine del BSI.",
        es: "Según el artículo 23(1), la propia entidad notifica, cuando proceda, a los destinatarios de sus servicios los incidentes significativos susceptibles de afectarles. Según el artículo 23(7), el CSIRT o la autoridad competente puede informar al público o exigir a la entidad que lo haga. En Alemania, el § 35(1) BSIG convierte la notificación a los clientes en una orden del BSI.",
        pl: "Na podstawie artykułu 23(1) podmiot sam, w stosownych przypadkach, powiadamia odbiorców swoich usług o poważnych incydentach, które mogą ich dotyczyć. Na podstawie artykułu 23(7) CSIRT lub właściwy organ może poinformować społeczeństwo lub zobowiązać do tego podmiot. W Niemczech § 35(1) BSIG czyni powiadomienie klientów nakazem BSI.",
        cs: "Podle článku 23(1) subjekt v příslušných případech sám oznámí příjemcům svých služeb významné incidenty, které by je mohly ovlivnit. Podle článku 23(7) může tým CSIRT nebo příslušný orgán informovat veřejnost nebo požadovat, aby tak učinil subjekt. V Německu činí § 35(1) BSIG z oznámení zákazníkům příkaz BSI.",
        pt: "Nos termos do artigo 23(1), a própria entidade notifica, se for caso disso, os destinatários dos seus serviços de incidentes significativos suscetíveis de os afetar. Nos termos do artigo 23(7), a CSIRT ou a autoridade competente pode informar o público ou exigir que a entidade o faça. Na Alemanha, o § 35(1) BSIG faz da notificação aos clientes uma ordem do BSI.",
        ro: "Conform articolului 23(1), entitatea însăși notifică, dacă este cazul, destinatarilor serviciilor sale incidentele semnificative care i-ar putea afecta. Conform articolului 23(7), echipa CSIRT sau autoritatea competentă poate informa publicul sau poate solicita entității să facă acest lucru. În Germania, § 35(1) BSIG face din notificarea clienților un ordin al BSI.",
      },
    },
    {
      id: "1.12.2",
      question: {
        en: "Under Article 23(2), what must you tell customers potentially affected by a significant cyber threat?",
        de: "Was müssen Sie gemäß Artikel 23 Absatz 2 Kunden mitteilen, die potenziell von einer erheblichen Cyberbedrohung betroffen sind?",
        nl: "Wat moet u op grond van artikel 23(2) meedelen aan klanten die mogelijkerwijs door een significante cyberdreiging worden getroffen?",
        fr: "Au titre de l'article 23(2), que devez-vous communiquer aux clients potentiellement affectés par une cybermenace importante ?",
        it: "Ai sensi dell'articolo 23(2), cosa dovete comunicare ai clienti potenzialmente interessati da una minaccia informatica significativa?",
        es: "En virtud del artículo 23(2), ¿qué debe comunicar a los clientes que puedan verse afectados por una ciberamenaza significativa?",
        pl: "Na podstawie artykułu 23(2), co muszą Państwo przekazać klientom, których potencjalnie dotyczy poważne cyberzagrożenie?",
        cs: "Co musíte podle článku 23(2) sdělit zákazníkům, kteří mohou být ovlivněni významnou kybernetickou hrozbou?",
        pt: "Nos termos do artigo 23(2), o que tem de comunicar aos clientes potencialmente afetados por uma ciberameaça significativa?",
        ro: "Conform articolului 23(2), ce trebuie să comunicați clienților care ar putea fi afectați de o amenințare cibernetică semnificativă?",
      },
      options: [
        {
          en: "Nothing else is required",
          de: "Es sind keine weiteren Angaben erforderlich",
          nl: "Er zijn geen verdere mededelingen vereist",
          fr: "Aucune autre indication n'est requise",
          it: "Non è richiesta alcuna altra informazione",
          es: "No se requiere ninguna otra información",
          pl: "Nie są wymagane żadne dalsze informacje",
          cs: "Nic dalšího se nevyžaduje",
          pt: "Nada mais é exigido",
          ro: "Nu se mai cere nimic altceva",
        },
        {
          en: "The name of the attacker and their methods",
          de: "Den Namen des Angreifers und seine Methoden",
          nl: "De naam van de aanvaller en hun methoden",
          fr: "Le nom de l'attaquant et ses méthodes",
          it: "Il nome dell'aggressore e i suoi metodi",
          es: "El nombre del atacante y sus métodos",
          pl: "Nazwę napastnika i jego metody",
          cs: "Jméno útočníka a jeho metody",
          pt: "O nome do atacante e os seus métodos",
          ro: "Numele atacatorului și metodele acestuia",
        },
        {
          en: "Any measures or remedies the recipients can take in response to the threat",
          de: "Alle Maßnahmen oder Abhilfemöglichkeiten, die die Empfänger als Reaktion auf die Bedrohung ergreifen können",
          nl: "Alle maatregelen of herstelacties die de ontvangers kunnen nemen als reactie op de dreiging",
          fr: "Toutes les mesures ou solutions que les destinataires peuvent prendre en réponse à la menace",
          it: "Tutte le misure o i rimedi che i destinatari possono adottare in risposta alla minaccia",
          es: "Cualquier medida o solución que los destinatarios puedan adoptar en respuesta a la amenaza",
          pl: "Wszelkie środki lub rozwiązania, które odbiorcy mogą podjąć w odpowiedzi na zagrożenie",
          cs: "Veškerá opatření nebo nápravné kroky, které mohou příjemci v reakci na hrozbu přijmout",
          pt: "Quaisquer medidas ou soluções que os destinatários possam adotar em resposta à ameaça",
          ro: "Orice măsuri sau remedii pe care destinatarii le pot lua ca răspuns la amenințare",
        },
        {
          en: "The amount of the fine the company expects to receive",
          de: "Die Höhe des Bußgeldes, das das Unternehmen erwartet",
          nl: "De hoogte van de boete die de vennootschap verwacht te ontvangen",
          fr: "Le montant de l'amende que l'entreprise s'attend à recevoir",
          it: "L'importo della sanzione che l'impresa si aspetta di ricevere",
          es: "El importe de la multa que la empresa espera recibir",
          pl: "Wysokość kary, jakiej spodziewa się firma",
          cs: "Výši pokuty, kterou společnost očekává",
          pt: "O montante da coima que a empresa espera receber",
          ro: "Cuantumul amenzii pe care compania se așteaptă să o primească",
        },
      ],
      correctIndex: 2,
      explanation: {
        en: "Article 23(2) requires you to disclose any measures or remedies that recipients are able to take in response to the threat.",
        de: "Artikel 23 Absatz 2 verlangt, dass Sie alle Maßnahmen oder Abhilfemöglichkeiten offenlegen, die die Empfänger als Reaktion auf die Bedrohung ergreifen können.",
        nl: "Artikel 23(2) vereist dat u alle maatregelen of herstelacties bekendmaakt die de ontvangers als reactie op de dreiging kunnen nemen.",
        fr: "L'article 23(2) exige que vous communiquiez toutes les mesures ou solutions que les destinataires sont en mesure de prendre en réponse à la menace.",
        it: "L'articolo 23(2) richiede che comunichiate tutte le misure o i rimedi che i destinatari sono in grado di adottare in risposta alla minaccia.",
        es: "El artículo 23(2) exige que comunique cualquier medida o solución que los destinatarios puedan adoptar en respuesta a la amenaza.",
        pl: "Artykuł 23(2) wymaga ujawnienia wszelkich środków lub rozwiązań, które odbiorcy są w stanie podjąć w odpowiedzi na zagrożenie.",
        cs: "Článek 23(2) vyžaduje, abyste sdělili veškerá opatření nebo nápravné kroky, které mohou příjemci v reakci na hrozbu přijmout.",
        pt: "O artigo 23(2) exige que divulgue quaisquer medidas ou soluções que os destinatários possam adotar em resposta à ameaça.",
        ro: "Articolul 23(2) impune să divulgați orice măsuri sau remedii pe care destinatarii le pot lua ca răspuns la amenințare.",
      },
    },
    {
      id: "1.12.3",
      question: {
        en: "What does the lesson recommend having prepared before an incident occurs?",
        de: "Was empfiehlt die Lektion, vor Eintritt eines Vorfalls vorbereitet zu haben?",
        nl: "Wat adviseert de les voorbereid te hebben voordat een incident plaatsvindt?",
        fr: "Que recommande la leçon d'avoir préparé avant qu'un incident ne survienne ?",
        it: "Cosa raccomanda la lezione di avere predisposto prima che si verifichi un incidente?",
        es: "¿Qué recomienda la lección tener preparado antes de que se produzca un incidente?",
        pl: "Co lekcja zaleca przygotować, zanim wystąpi incydent?",
        cs: "Co lekce doporučuje mít připraveno dříve, než dojde k incidentu?",
        pt: "O que recomenda a lição ter preparado antes de ocorrer um incidente?",
        ro: "Ce recomandă lecția să aveți pregatit înainte de a survine un incident?",
      },
      options: [
        {
          en: "A press release template and social media strategy",
          de: "Eine Pressemitteilungsvorlage und Social-Media-Strategie",
          nl: "Een persbericht-sjabloon en sociale-mediastrategie",
          fr: "Un modèle de communiqué de presse et une stratégie de médias sociaux",
          it: "Un modello di comunicato stampa e una strategia per i social media",
          es: "Una plantilla de comunicado de prensa y una estrategia de redes sociales",
          pl: "Szablon komunikatu prasowego i strategię mediów społecznościowych",
          cs: "Šablonu tiskové zprávy a strategii pro sociální sítě",
          pt: "Um modelo de comunicado de imprensa e uma estratégia para redes sociais",
          ro: "Un model de comunicat de presă și o strategie pentru rețelele sociale",
        },
        {
          en: "A pre-drafted customer notification template and a defined approval chain ending with the management body",
          de: "Eine vorbereitete Kundenbenachrichtigungsvorlage und eine definierte Freigabekette, die bei der Geschäftsleitung endet",
          nl: "Een vooraf opgesteld klantnotificatiesjabloon en een vastgestelde goedkeuringsketen die eindigt bij het leidinggevend orgaan",
          fr: "Un modèle de notification aux clients pré-rédigé et une chaîne d'approbation définie se terminant par l'organe de direction",
          it: "Un modello di notifica ai clienti già predisposto e una catena di approvazione definita che termina con l'organo di gestione",
          es: "Una plantilla de notificación a los clientes redactada de antemano y una cadena de aprobación definida que termina en el órgano de dirección",
          pl: "Wcześniej przygotowany szablon powiadomienia klientów oraz zdefiniowaną ścieżkę zatwierdzania kończącą się na organie zarządzającym",
          cs: "Předem připravenou šablonu oznámení zákazníkům a vymezený schvalovací řetězec končící u řídicího orgánu",
          pt: "Um modelo de notificação aos clientes previamente redigido e uma cadeia de aprovação definida que termina no órgão de administração",
          ro: "Un model de notificare a clienților redactat în prealabil și un lanț de aprobare definit care se încheie la organul de conducere",
        },
        {
          en: "An insurance claim form and legal retainer agreement",
          de: "Ein Versicherungsschadenformular und eine Mandatsvereinbarung",
          nl: "Een verzekeringsschadeclaimformulier en een mandaatovereenkomst",
          fr: "Un formulaire de déclaration de sinistre et un contrat de mandat juridique",
          it: "Un modulo di richiesta di risarcimento assicurativo e un contratto di mandato legale",
          es: "Un formulario de reclamación al seguro y un contrato de retención jurídica",
          pl: "Formularz zgłoszenia szkody ubezpieczeniowej i umowę o stałą obsługę prawną",
          cs: "Formulář pojistné události a smlouvu o právním zastoupení",
          pt: "Um formulário de participação de sinistro e um contrato de avença jurídica",
          ro: "Un formular de cerere de despăgubire și un contract de reprezentare juridică",
        },
        {
          en: "A list of customers ranked by revenue for priority notification",
          de: "Eine nach Umsatz sortierte Kundenliste für priorisierte Benachrichtigung",
          nl: "Een lijst van klanten gerangschikt op omzet voor prioriteitsnotificatie",
          fr: "Une liste de clients classés par chiffre d'affaires pour une notification prioritaire",
          it: "Un elenco di clienti ordinati per fatturato per la notifica prioritaria",
          es: "Una lista de clientes ordenados por facturación para una notificación prioritaria",
          pl: "Listę klientów uszeregowaną według przychodów na potrzeby priorytetowego powiadamiania",
          cs: "Seznam zákazníků seřazený podle tržeb pro přednostní oznamování",
          pt: "Uma lista de clientes ordenada por receita para notificação prioritária",
          ro: "O listă de clienți clasați după venituri pentru notificare prioritară",
        },
      ],
      correctIndex: 1,
      explanation: {
        en: "Have a pre-drafted customer notification template and a defined approval chain that ends with the management body.",
        de: "Halten Sie eine vorbereitete Kundenbenachrichtigungsvorlage und eine definierte Freigabekette bereit, die bei der Geschäftsleitung endet.",
        nl: "Zorg voor een vooraf opgesteld klantnotificatiesjabloon en een vastgestelde goedkeuringsketen die eindigt bij het leidinggevend orgaan.",
        fr: "Disposez d'un modèle de notification aux clients pré-rédigé et d'une chaîne d'approbation définie qui se termine par l'organe de direction.",
        it: "Disponete di un modello di notifica ai clienti già predisposto e di una catena di approvazione definita che termina con l'organo di gestione.",
        es: "Disponga de una plantilla de notificación a los clientes redactada de antemano y de una cadena de aprobación definida que termine en el órgano de dirección.",
        pl: "Należy mieć wcześniej przygotowany szablon powiadomienia klientów oraz zdefiniowaną ścieżkę zatwierdzania kończącą się na organie zarządzającym.",
        cs: "Mějte předem připravenou šablonu oznámení zákazníkům a vymezený schvalovací řetězec, který končí u řídicího orgánu.",
        pt: "Tenha um modelo de notificação aos clientes previamente redigido e uma cadeia de aprovação definida que termina no órgão de administração.",
        ro: "Aveți un model de notificare a clienților redactat în prealabil și un lanț de aprobare definit care se încheie la organul de conducere.",
      },
    },
  ],
});

export default quiz;
