import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.2",
  passingScore: 75,
  questions: [
    {
      id: "1.2.1",
      question: {
        en: "What is the size threshold for most companies to fall in scope of NIS2?",
        de: "Ab welcher Unternehmensgröße fallen die meisten Unternehmen in den Anwendungsbereich von NIS2?",
        nl: "Wat is de drempelwaarde voor de omvang van bedrijven om onder de reikwijdte van NIS2 te vallen?",
        fr: "Quel est le seuil de taille à partir duquel la plupart des entreprises entrent dans le champ d'application de NIS2 ?",
        it: "Qual è la soglia dimensionale per cui la maggior parte delle imprese rientra nell'ambito di applicazione di NIS2?",
        es: "¿Cuál es el umbral de tamaño para que la mayoría de las empresas entren en el ámbito de aplicación de NIS2?",
        pl: "Jaki próg wielkości powoduje, że większość firm wchodzi w zakres NIS2?",
        cs: "Jaká je velikostní hranice, při níž většina společností spadá do působnosti NIS2?",
        pt: "Qual é o limiar de dimensão para que a maioria das empresas fique abrangida pela NIS2?",
        ro: "Care este pragul de dimensiune pentru ca majoritatea companiilor să intre în domeniul de aplicare al NIS2?",
      },
      options: [
        { en: "250 or more employees, or 50 million euros in turnover", de: "250 oder mehr Beschäftigte oder 50 Millionen Euro Umsatz", nl: "250 of meer werknemers, of 50 miljoen euro omzet", fr: "250 employés ou plus, ou 50 millions d'euros de chiffre d'affaires", it: "250 o più dipendenti, oppure 50 milioni di euro di fatturato", es: "250 empleados o más, o 50 millones de euros de facturación", pl: "250 lub więcej pracowników albo 50 milionów euro obrotu", cs: "250 nebo více zaměstnanců, nebo obrat 50 milionů eur", pt: "250 ou mais trabalhadores, ou 50 milhões de euros de volume de negócios", ro: "250 sau mai mulți angajați, ori 50 de milioane de euro cifră de afaceri" },
        { en: "50 or more employees, or more than 10 million euros in annual turnover", de: "50 oder mehr Beschäftigte oder mehr als 10 Millionen Euro Jahresumsatz", nl: "50 of meer werknemers, of meer dan 10 miljoen euro jaaromzet", fr: "50 employés ou plus, ou plus de 10 millions d'euros de chiffre d'affaires annuel", it: "50 o più dipendenti, oppure più di 10 milioni di euro di fatturato annuo", es: "50 empleados o más, o más de 10 millones de euros de facturación anual", pl: "50 lub więcej pracowników albo ponad 10 milionów euro rocznego obrotu", cs: "50 nebo více zaměstnanců, nebo roční obrat vyšší než 10 milionů eur", pt: "50 ou mais trabalhadores, ou mais de 10 milhões de euros de volume de negócios anual", ro: "50 sau mai mulți angajați, ori o cifră de afaceri anuală de peste 10 milioane de euro" },
        { en: "10 or more employees, or more than 1 million euros in annual turnover", de: "10 oder mehr Beschäftigte oder mehr als 1 Million Euro Jahresumsatz", nl: "10 of meer werknemers, of meer dan 1 miljoen euro jaaromzet", fr: "10 employés ou plus, ou plus de 1 million d'euros de chiffre d'affaires annuel", it: "10 o più dipendenti, oppure più di 1 milione di euro di fatturato annuo", es: "10 empleados o más, o más de 1 millón de euros de facturación anual", pl: "10 lub więcej pracowników albo ponad 1 milion euro rocznego obrotu", cs: "10 nebo více zaměstnanců, nebo roční obrat vyšší než 1 milion eur", pt: "10 ou mais trabalhadores, ou mais de 1 milhão de euros de volume de negócios anual", ro: "10 sau mai mulți angajați, ori o cifră de afaceri anuală de peste 1 milion de euro" },
        { en: "100 or more employees, or more than 25 million euros in annual turnover", de: "100 oder mehr Beschäftigte oder mehr als 25 Millionen Euro Jahresumsatz", nl: "100 of meer werknemers, of meer dan 25 miljoen euro jaaromzet", fr: "100 employés ou plus, ou plus de 25 millions d'euros de chiffre d'affaires annuel", it: "100 o più dipendenti, oppure più di 25 milioni di euro di fatturato annuo", es: "100 empleados o más, o más de 25 millones de euros de facturación anual", pl: "100 lub więcej pracowników albo ponad 25 milionów euro rocznego obrotu", cs: "100 nebo více zaměstnanců, nebo roční obrat vyšší než 25 milionů eur", pt: "100 ou mais trabalhadores, ou mais de 25 milhões de euros de volume de negócios anual", ro: "100 sau mai mulți angajați, ori o cifră de afaceri anuală de peste 25 de milioane de euro" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Most companies enter scope through fifty or more employees, or more than ten million euros in annual turnover.",
        de: "Die meisten Unternehmen fallen ab fünfzig oder mehr Beschäftigten oder mehr als zehn Millionen Euro Jahresumsatz in den Anwendungsbereich.",
        nl: "De meeste bedrijven vallen binnen de reikwijdte met vijftig of meer werknemers, of meer dan tien miljoen euro jaaromzet.",
        fr: "La plupart des entreprises entrent dans le champ d'application à partir de cinquante employés ou plus, ou de plus de dix millions d'euros de chiffre d'affaires annuel.",
        it: "La maggior parte delle imprese rientra nell'ambito di applicazione a partire da cinquanta o più dipendenti, oppure da più di dieci milioni di euro di fatturato annuo.",
        es: "La mayoría de las empresas entran en el ámbito de aplicación a partir de cincuenta empleados o más, o de más de diez millones de euros de facturación anual.",
        pl: "Większość firm wchodzi w zakres przy pięćdziesięciu lub więcej pracownikach albo przy ponad dziesięciu milionach euro rocznego obrotu.",
        cs: "Většina společností spadá do působnosti při padesáti nebo více zaměstnancích, nebo při ročním obratu vyšším než deset milionů eur.",
        pt: "A maioria das empresas fica abrangida por terem cinquenta ou mais trabalhadores, ou mais de dez milhões de euros de volume de negócios anual.",
        ro: "Majoritatea companiilor intră în domeniul de aplicare prin cincizeci sau mai mulți angajați, ori printr-o cifră de afaceri anuală de peste zece milioane de euro.",
      },
    },
    {
      id: "1.2.2",
      question: {
        en: "What is the key difference between Essential and Important entities?",
        de: "Was ist der wesentliche Unterschied zwischen wesentlichen und wichtigen Einrichtungen?",
        nl: "Wat is het belangrijkste verschil tussen essentiële entiteiten en belangrijke entiteiten?",
        fr: "Quelle est la principale différence entre les entités essentielles et les entités importantes ?",
        it: "Qual è la differenza principale tra soggetti essenziali e soggetti importanti?",
        es: "¿Cuál es la diferencia clave entre las entidades esenciales y las entidades importantes?",
        pl: "Jaka jest kluczowa różnica między podmiotami kluczowymi a podmiotami ważnymi?",
        cs: "Jaký je hlavní rozdíl mezi základními a důležitými subjekty?",
        pt: "Qual é a diferença fundamental entre entidades essenciais e importantes?",
        ro: "Care este diferența esențială dintre entitățile esențiale și cele importante?",
      },
      options: [
        { en: "Essential entities must implement all ten measures; Important entities only implement five", de: "Wesentliche Einrichtungen müssen alle zehn Maßnahmen umsetzen; wichtige Einrichtungen nur fünf", nl: "Essentiële entiteiten moeten alle tien maatregelen implementeren; belangrijke entiteiten slechts vijf", fr: "Les entités essentielles doivent mettre en œuvre les dix mesures ; les entités importantes n'en mettent en œuvre que cinq", it: "I soggetti essenziali devono attuare tutte e dieci le misure; i soggetti importanti ne attuano solo cinque", es: "Las entidades esenciales deben implementar las diez medidas; las entidades importantes solo implementan cinco", pl: "Podmioty kluczowe muszą wdrożyć wszystkie dziesięć środków; podmioty ważne wdrażają tylko pięć", cs: "Základní subjekty musí zavést všech deset opatření, důležité subjekty zavádějí pouze pět", pt: "As entidades essenciais têm de implementar as dez medidas, as entidades importantes implementam apenas cinco", ro: "Entitățile esențiale trebuie să implementeze toate cele zece măsuri, entitățile importante implementează doar cinci" },
        { en: "Essential entities face proactive supervision (audit without cause); Important entities face reactive supervision (audit only when triggered)", de: "Wesentliche Einrichtungen unterliegen proaktiver Aufsicht (Prüfung ohne Anlass); wichtige Einrichtungen unterliegen reaktiver Aufsicht (Prüfung nur bei konkretem Anlass)", nl: "Essentiële entiteiten staan onder proactief toezicht (audit zonder aanleiding); belangrijke entiteiten staan onder reactief toezicht (audit alleen bij aanleiding)", fr: "Les entités essentielles font l'objet d'une surveillance proactive (audit sans motif) ; les entités importantes font l'objet d'une surveillance réactive (audit uniquement en cas de déclencheur)", it: "I soggetti essenziali sono soggetti a vigilanza proattiva (verifica senza motivo); i soggetti importanti sono soggetti a vigilanza reattiva (verifica solo in presenza di un motivo specifico)", es: "Las entidades esenciales están sujetas a supervisión proactiva (auditoría sin causa); las entidades importantes están sujetas a supervisión reactiva (auditoría solo cuando hay un motivo)", pl: "Podmioty kluczowe podlegają nadzorowi proaktywnemu (audyt bez przyczyny); podmioty ważne podlegają nadzorowi reaktywnemu (audyt tylko po wystąpieniu przesłanki)", cs: "Základní subjekty podléhají proaktivnímu dohledu (audit bez podnětu), důležité subjekty reaktivnímu dohledu (audit pouze při podnětu)", pt: "As entidades essenciais estão sujeitas a supervisão proativa (auditoria sem causa), as entidades importantes a supervisão reativa (auditoria apenas quando despoletada)", ro: "Entitățile esențiale sunt supuse unei supravegheri proactive (audit fără cauză), entitățile importante unei supravegheri reactive (audit doar la declanșare)" },
        { en: "Important entities face higher fines than Essential entities", de: "Wichtige Einrichtungen müssen höhere Bußgelder zahlen als wesentliche Einrichtungen", nl: "Belangrijke entiteiten krijgen hogere boetes dan essentiële entiteiten", fr: "Les entités importantes encourent des amendes plus élevées que les entités essentielles", it: "I soggetti importanti subiscono sanzioni più elevate rispetto ai soggetti essenziali", es: "Las entidades importantes se enfrentan a multas más elevadas que las entidades esenciales", pl: "Podmioty ważne podlegają wyższym karom niż podmioty kluczowe", cs: "Důležité subjekty čelí vyšším pokutám než základní subjekty", pt: "As entidades importantes enfrentam coimas mais elevadas do que as entidades essenciais", ro: "Entitățile importante se confruntă cu amenzi mai mari decât entitățile esențiale" },
        { en: "Essential entities are in Annex II; Important entities are in Annex I", de: "Wesentliche Einrichtungen stehen in Anhang II; wichtige Einrichtungen in Anhang I", nl: "Essentiële entiteiten staan in Bijlage II; belangrijke entiteiten staan in Bijlage I", fr: "Les entités essentielles figurent à l'annexe II ; les entités importantes figurent à l'annexe I", it: "I soggetti essenziali sono nell'allegato II; i soggetti importanti sono nell'allegato I", es: "Las entidades esenciales figuran en el anexo II; las entidades importantes figuran en el anexo I", pl: "Podmioty kluczowe są w załączniku II; podmioty ważne są w załączniku I", cs: "Základní subjekty jsou v příloze II, důležité subjekty v příloze I", pt: "As entidades essenciais constam do Anexo II, as entidades importantes do Anexo I", ro: "Entitățile esențiale figurează în Anexa II, entitățile importante în Anexa I" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The substantive obligations apply equally. The difference is enforcement intensity: Essential entities face proactive supervision, Important entities face reactive supervision.",
        de: "Die inhaltlichen Pflichten gelten gleichermaßen. Der Unterschied liegt in der Aufsichtsintensität: Wesentliche Einrichtungen unterliegen proaktiver Aufsicht, wichtige Einrichtungen reaktiver Aufsicht.",
        nl: "De inhoudelijke verplichtingen gelden voor beiden gelijkelijk. Het verschil zit in de handhavingsintensiteit: essentiële entiteiten staan onder proactief toezicht, belangrijke entiteiten onder reactief toezicht.",
        fr: "Les obligations de fond s'appliquent de la même manière. La différence réside dans l'intensité du contrôle : les entités essentielles font l'objet d'une surveillance proactive, les entités importantes d'une surveillance réactive.",
        it: "Gli obblighi sostanziali si applicano allo stesso modo. La differenza sta nell'intensità della vigilanza: i soggetti essenziali sono soggetti a vigilanza proattiva, i soggetti importanti a vigilanza reattiva.",
        es: "Las obligaciones sustantivas se aplican por igual. La diferencia está en la intensidad de la supervisión: las entidades esenciales están sujetas a supervisión proactiva, las entidades importantes a supervisión reactiva.",
        pl: "Obowiązki merytoryczne mają zastosowanie w jednakowym stopniu. Różnica polega na intensywności nadzoru: podmioty kluczowe podlegają nadzorowi proaktywnemu, a podmioty ważne nadzorowi reaktywnemu.",
        cs: "Věcné povinnosti platí stejně. Rozdíl je v intenzitě vymáhání: základní subjekty podléhají proaktivnímu dohledu, důležité subjekty reaktivnímu dohledu.",
        pt: "As obrigações substantivas aplicam-se igualmente. A diferença está na intensidade da fiscalização: as entidades essenciais estão sujeitas a supervisão proativa, as entidades importantes a supervisão reativa.",
        ro: "Obligațiile de fond se aplică în mod egal. Diferența constă în intensitatea aplicării: entitățile esențiale sunt supuse unei supravegheri proactive, entitățile importante unei supravegheri reactive.",
      },
    },
    {
      id: "1.2.3",
      question: {
        en: "Do Essential and Important entities have to implement different security measures?",
        de: "Müssen wesentliche und wichtige Einrichtungen unterschiedliche Sicherheitsmaßnahmen umsetzen?",
        nl: "Moeten essentiële entiteiten en belangrijke entiteiten verschillende beveiligingsmaatregelen implementeren?",
        fr: "Les entités essentielles et les entités importantes doivent-elles mettre en œuvre des mesures de sécurité différentes ?",
        it: "I soggetti essenziali e i soggetti importanti devono attuare misure di sicurezza diverse?",
        es: "¿Tienen las entidades esenciales y las entidades importantes que implementar medidas de seguridad diferentes?",
        pl: "Czy podmioty kluczowe i podmioty ważne muszą wdrażać różne środki bezpieczeństwa?",
        cs: "Musí základní a důležité subjekty zavádět odlišná bezpečnostní opatření?",
        pt: "As entidades essenciais e importantes têm de implementar medidas de segurança diferentes?",
        ro: "Trebuie ca entitățile esențiale și cele importante să implementeze măsuri de securitate diferite?",
      },
      options: [
        { en: "Yes, Essential entities have stricter technical requirements", de: "Ja, wesentliche Einrichtungen haben strengere technische Anforderungen", nl: "Ja, essentiële entiteiten hebben strengere technische vereisten", fr: "Oui, les entités essentielles ont des exigences techniques plus strictes", it: "Sì, i soggetti essenziali hanno requisiti tecnici più rigorosi", es: "Sí, las entidades esenciales tienen requisitos técnicos más estrictos", pl: "Tak, podmioty kluczowe mają surowsze wymagania techniczne", cs: "Ano, základní subjekty mají přísnější technické požadavky", pt: "Sim, as entidades essenciais têm requisitos técnicos mais rigorosos", ro: "Da, entitățile esențiale au cerințe tehnice mai stricte" },
        { en: "Yes, Important entities have additional reporting duties", de: "Ja, wichtige Einrichtungen haben zusätzliche Meldepflichten", nl: "Ja, belangrijke entiteiten hebben aanvullende meldingsverplichtingen", fr: "Oui, les entités importantes ont des obligations de notification supplémentaires", it: "Sì, i soggetti importanti hanno obblighi di notifica aggiuntivi", es: "Sí, las entidades importantes tienen obligaciones de notificación adicionales", pl: "Tak, podmioty ważne mają dodatkowe obowiązki w zakresie zgłaszania", cs: "Ano, důležité subjekty mají další ohlašovací povinnosti", pt: "Sim, as entidades importantes têm deveres de notificação adicionais", ro: "Da, entitățile importante au obligații suplimentare de raportare" },
        { en: "No, both must implement the same ten measures under Article 21", de: "Nein, beide müssen die gleichen zehn Maßnahmen nach Artikel 21 umsetzen", nl: "Nee, beide moeten dezelfde tien maatregelen implementeren op grond van Artikel 21", fr: "Non, les deux doivent mettre en œuvre les mêmes dix mesures au titre de l'article 21", it: "No, entrambi devono attuare le stesse dieci misure ai sensi dell'articolo 21", es: "No, ambas deben implementar las mismas diez medidas en virtud del artículo 21", pl: "Nie, oba muszą wdrożyć te same dziesięć środków na podstawie artykułu 21", cs: "Ne, oba musí zavést stejných deset opatření podle článku 21", pt: "Não, ambas têm de implementar as mesmas dez medidas ao abrigo do artigo 21", ro: "Nu, ambele trebuie să implementeze aceleași zece măsuri în temeiul articolului 21" },
        { en: "No measures apply to Important entities", de: "Für wichtige Einrichtungen gelten keine Maßnahmen", nl: "Er gelden geen maatregelen voor belangrijke entiteiten", fr: "Aucune mesure ne s'applique aux entités importantes", it: "Nessuna misura si applica ai soggetti importanti", es: "No se aplica ninguna medida a las entidades importantes", pl: "Do podmiotów ważnych nie mają zastosowania żadne środki", cs: "Na důležité subjekty se nevztahují žádná opatření", pt: "Não se aplicam quaisquer medidas às entidades importantes", ro: "Nicio măsură nu se aplică entităților importante" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The ten measures under Article 21 apply equally to both categories. The difference is enforcement intensity, not compliance scope.",
        de: "Die zehn Maßnahmen nach Artikel 21 gelten gleichermaßen für beide Kategorien. Der Unterschied liegt in der Aufsichtsintensität, nicht im Umfang der Pflichten.",
        nl: "De tien maatregelen van Artikel 21 gelden voor beide categorieën gelijkelijk. Het verschil zit in de handhavingsintensiteit, niet in de reikwijdte van de naleving.",
        fr: "Les dix mesures de l'article 21 s'appliquent de la même manière aux deux catégories. La différence réside dans l'intensité du contrôle, et non dans l'étendue des obligations.",
        it: "Le dieci misure dell'articolo 21 si applicano allo stesso modo a entrambe le categorie. La differenza sta nell'intensità della vigilanza, non nell'ambito degli obblighi.",
        es: "Las diez medidas del artículo 21 se aplican por igual a ambas categorías. La diferencia está en la intensidad de la supervisión, no en el alcance de las obligaciones.",
        pl: "Dziesięć środków z artykułu 21 ma zastosowanie w jednakowym stopniu do obu kategorii. Różnica polega na intensywności nadzoru, a nie na zakresie obowiązków.",
        cs: "Deset opatření podle článku 21 platí pro obě kategorie stejně. Rozdíl je v intenzitě vymáhání, nikoli v rozsahu povinností.",
        pt: "As dez medidas ao abrigo do artigo 21 aplicam-se igualmente a ambas as categorias. A diferença está na intensidade da fiscalização, não no âmbito de conformidade.",
        ro: "Cele zece măsuri din articolul 21 se aplică în mod egal ambelor categorii. Diferența constă în intensitatea aplicării, nu în domeniul de conformitate.",
      },
    },
  ],
});

export default quiz;
