import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.3",
  passingScore: 75,
  questions: [
    {
      id: "1.3.1",
      question: {
        en: "What is the maximum administrative fine for Essential entities under NIS2?",
        de: "Wie hoch ist das maximale Bußgeld für wesentliche Einrichtungen unter NIS2?",
        nl: "Wat is de maximale bestuurlijke boete voor essentiële entiteiten onder NIS2?",
        fr: "Quel est le montant maximal de l'amende administrative pour les entités essentielles au titre de NIS2 ?",
        it: "Qual è la sanzione amministrativa massima per i soggetti essenziali ai sensi di NIS2?",
        es: "¿Cuál es la multa administrativa máxima para las entidades esenciales en virtud de NIS2?",
        pl: "Jaka jest maksymalna administracyjna kara pieniężna dla podmiotów kluczowych na podstawie NIS2?",
        cs: "Jaká je maximální správní pokuta pro základní subjekty podle NIS2?",
        pt: "Qual é a coima administrativa máxima para entidades essenciais ao abrigo da NIS2?",
        ro: "Care este amenda administrativă maximă pentru entitățile esențiale în temeiul NIS2?",
      },
      options: [
        {
          en: "Seven million euros or 1.4% of worldwide turnover",
          de: "Sieben Millionen Euro oder 1,4 % des weltweiten Umsatzes",
          nl: "Zeven miljoen euro of 1,4% van de wereldwijde omzet",
          fr: "Sept millions d'euros ou 1,4 % du chiffre d'affaires mondial",
          it: "Sette milioni di euro o 1,4% del fatturato mondiale",
          es: "Siete millones de euros o el 1,4% de la facturación mundial",
          pl: "Siedem milionów euro lub 1,4% światowego obrotu",
          cs: "Sedm milionů eur nebo 1,4 % celosvětového obratu",
          pt: "Sete milhões de euros ou 1,4% do volume de negócios mundial",
          ro: "Șapte milioane de euro sau 1,4% din cifra de afaceri mondială",
        },
        {
          en: "Ten million euros or 2% of worldwide annual turnover, whichever is higher",
          de: "Zehn Millionen Euro oder 2 % des weltweiten Jahresumsatzes, je nachdem welcher Betrag höher ist",
          nl: "Tien miljoen euro of 2% van de wereldwijde jaaromzet, afhankelijk van welk bedrag hoger is",
          fr: "Dix millions d'euros ou 2 % du chiffre d'affaires annuel mondial, le montant le plus élevé étant retenu",
          it: "Dieci milioni di euro o 2% del fatturato annuo mondiale, se superiore",
          es: "Diez millones de euros o el 2% de la facturación anual mundial, si esta cantidad es mayor",
          pl: "Dziesięć milionów euro lub 2% światowego rocznego obrotu, w zależności od tego, która kwota jest wyższa",
          cs: "Deset milionů eur nebo 2 % celosvětového ročního obratu, podle toho, co je vyšší",
          pt: "Dez milhões de euros ou 2% do volume de negócios anual mundial, consoante o que for mais elevado",
          ro: "Zece milioane de euro sau 2% din cifra de afaceri anuală mondială, oricare dintre acestea este mai mare",
        },
        {
          en: "Five million euros or 1% of worldwide turnover",
          de: "Fünf Millionen Euro oder 1 % des weltweiten Umsatzes",
          nl: "Vijf miljoen euro of 1% van de wereldwijde omzet",
          fr: "Cinq millions d'euros ou 1 % du chiffre d'affaires mondial",
          it: "Cinque milioni di euro o 1% del fatturato mondiale",
          es: "Cinco millones de euros o el 1% de la facturación mundial",
          pl: "Pięć milionów euro lub 1% światowego obrotu",
          cs: "Pět milionů eur nebo 1 % celosvětového obratu",
          pt: "Cinco milhões de euros ou 1% do volume de negócios mundial",
          ro: "Cinci milioane de euro sau 1% din cifra de afaceri mondială",
        },
        {
          en: "Twenty million euros or 4% of worldwide turnover",
          de: "Zwanzig Millionen Euro oder 4 % des weltweiten Umsatzes",
          nl: "Twintig miljoen euro of 4% van de wereldwijde omzet",
          fr: "Vingt millions d'euros ou 4 % du chiffre d'affaires mondial",
          it: "Venti milioni di euro o 4% del fatturato mondiale",
          es: "Veinte millones de euros o el 4% de la facturación mundial",
          pl: "Dwadzieścia milionów euro lub 4% światowego obrotu",
          cs: "Dvacet milionů eur nebo 4 % celosvětového obratu",
          pt: "Vinte milhões de euros ou 4% do volume de negócios mundial",
          ro: "Douăzeci de milioane de euro sau 4% din cifra de afaceri mondială",
        },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 34(4) sets the maximum for Essential entities at the higher of ten million euros or two percent of total worldwide annual turnover.",
        de: "Artikel 34 Absatz 4 legt das Maximum für wesentliche Einrichtungen auf den höheren der beiden Beträge fest: zehn Millionen Euro oder zwei Prozent des weltweiten Jahresumsatzes.",
        nl: "Artikel 34(4) stelt het maximum voor essentiële entiteiten vast op het hogere van tien miljoen euro of twee procent van de totale wereldwijde jaaromzet.",
        fr: "L'article 34(4) fixe le maximum pour les entités essentielles au montant le plus élevé entre dix millions d'euros et deux pour cent du chiffre d'affaires annuel mondial total.",
        it: "L'articolo 34(4) fissa il massimo per i soggetti essenziali al maggiore tra dieci milioni di euro e il due per cento del fatturato annuo mondiale totale.",
        es: "El artículo 34(4) fija el máximo para las entidades esenciales en la cantidad mayor entre diez millones de euros y el dos por ciento de la facturación anual mundial total.",
        pl: "Artykuł 34(4) ustala maksimum dla podmiotów kluczowych na wyższą z kwot: dziesięć milionów euro lub dwa procent całkowitego światowego rocznego obrotu.",
        cs: "Článek 34(4) stanoví maximum pro základní subjekty jako vyšší z hodnot deset milionů eur nebo dvě procenta celkového celosvětového ročního obratu.",
        pt: "O artigo 34(4) fixa o máximo para as entidades essenciais no valor mais elevado entre dez milhões de euros ou dois por cento do volume de negócios anual mundial total.",
        ro: "Articolul 34(4) stabilește plafonul pentru entitățile esențiale la valoarea cea mai mare dintre zece milioane de euro sau două la sută din cifra de afaceri anuală mondială totală.",
      },
    },
    {
      id: "1.3.2",
      question: {
        en: "What does Article 32(5)(b) allow the regulator to do?",
        de: "Was erlaubt Artikel 32 Absatz 5 Buchstabe b der Aufsichtsbehörde?",
        nl: "Wat staat Artikel 32(5)(b) de toezichthouder toe te doen?",
        fr: "Qu'est-ce que l'article 32(5)(b) permet à l'autorité de contrôle de faire ?",
        it: "Cosa consente l'articolo 32(5)(b) all'autorità di vigilanza di fare?",
        es: "¿Qué permite hacer el artículo 32(5)(b) a la autoridad supervisora?",
        pl: "Na co artykuł 32(5)(b) pozwala organowi nadzoru?",
        cs: "Co článek 32(5)(b) umožňuje regulačnímu orgánu?",
        pt: "O que permite o artigo 32(5)(b) que a autoridade reguladora faça?",
        ro: "Ce permite articolul 32(5)(b) autorității de reglementare să facă?",
      },
      options: [
        {
          en: "Only fine the company",
          de: "Nur das Unternehmen mit einem Bußgeld belegen",
          nl: "Alleen de onderneming beboeten",
          fr: "Uniquement infliger une amende à l'entreprise",
          it: "Solo sanzionare l'impresa",
          es: "Solo multar a la empresa",
          pl: "Wyłącznie nałożyć karę pieniężną na firmę",
          cs: "Pouze pokutovat společnost",
          pt: "Apenas aplicar coima à empresa",
          ro: "Doar să amendeze compania",
        },
        {
          en: "In an Essential entity that ignores its orders past a deadline, have the CEO or legal representative temporarily banned from management functions in that entity",
          de: "Bei einer wesentlichen Einrichtung, die Anordnungen trotz Frist missachtet, ein vorübergehendes Verbot erwirken, Leitungsaufgaben in dieser Einrichtung wahrzunehmen",
          nl: "Bij een essentiële entiteit die de bevelen van de toezichthouder na een gestelde termijn nog negeert, de algemeen directeur of wettelijke vertegenwoordiger tijdelijk laten verbieden leidinggevende functies in die entiteit uit te oefenen",
          fr: "Dans une entité essentielle qui ignore les injonctions de l'autorité au-delà du délai imparti, faire interdire temporairement au directeur général ou au représentant légal d'exercer des responsabilités dirigeantes dans cette entité",
          it: "In un soggetto essenziale che ignora le prescrizioni dell'autorità oltre il termine fissato, far vietare temporaneamente all'amministratore delegato o al rappresentante legale di svolgere funzioni dirigenziali in tale soggetto",
          es: "En una entidad esencial que desatiende los requerimientos de la autoridad una vez vencido el plazo, hacer que se prohíba temporalmente al director general o representante legal ejercer funciones de dirección en dicha entidad",
          pl: "W podmiocie kluczowym, który mimo upływu wyznaczonego terminu ignoruje nakazy organu, doprowadzić do tymczasowego zakazu pełnienia funkcji zarządczych w tym podmiocie przez dyrektora generalnego lub przedstawiciela prawnego",
          cs: "U základního subjektu, který ani po uplynutí stanovené lhůty nerespektuje příkazy orgánu, docílit dočasného zákazu výkonu řídicích funkcí v tomto subjektu pro výkonného ředitele nebo zákonného zástupce",
          pt: "Numa entidade essencial que ignora as ordens da autoridade depois de expirado o prazo fixado, fazer proibir temporariamente o diretor executivo ou representante legal de exercer funções de gestão nessa entidade",
          ro: "Într-o entitate esențială care ignoră dispozițiile autorității după expirarea termenului stabilit, să obțină interzicerea temporară pentru directorul executiv sau reprezentantul legal de a exercita funcții de conducere în cadrul entității respective",
        },
        {
          en: "Shut down the company permanently",
          de: "Das Unternehmen dauerhaft schließen",
          nl: "Het bedrijf permanent sluiten",
          fr: "Fermer définitivement l'entreprise",
          it: "Chiudere definitivamente l'impresa",
          es: "Cerrar la empresa de forma permanente",
          pl: "Trwale zamknąć firmę",
          cs: "Trvale ukončit činnost společnosti",
          pt: "Encerrar a empresa de forma permanente",
          ro: "Să închidă compania în mod permanent",
        },
        {
          en: "Revoke the company's operating licence",
          de: "Die Betriebsgenehmigung des Unternehmens widerrufen",
          nl: "De bedrijfsvergunning van de onderneming intrekken",
          fr: "Révoquer l'autorisation d'exploitation de l'entreprise",
          it: "Revocare l'autorizzazione all'esercizio dell'impresa",
          es: "Revocar la licencia de funcionamiento de la empresa",
          pl: "Cofnąć zezwolenie na prowadzenie działalności firmy",
          cs: "Odejmout společnosti provozní licenci",
          pt: "Revogar a licença de exploração da empresa",
          ro: "Să revoce licența de funcționare a companiei",
        },
      ],
      correctIndex: 1,
      explanation: {
        en: "For Essential entities only, Article 32(5)(b) lets the regulator request that a court or competent body temporarily ban the person at CEO or legal representative level from exercising management functions in that entity, when its orders are ignored past a deadline. The ban lasts until the deficiencies are fixed.",
        de: "Nur bei wesentlichen Einrichtungen kann die Aufsichtsbehörde nach Artikel 32 Absatz 5 Buchstabe b verlangen, dass ein Gericht oder eine zuständige Stelle der Person auf Ebene der Geschäftsführung oder gesetzlichen Vertretung vorübergehend untersagt, Leitungsaufgaben in dieser Einrichtung wahrzunehmen, wenn Anordnungen trotz Frist missachtet werden. Das Verbot gilt, bis die Mängel behoben sind.",
        nl: "Alleen bij essentiële entiteiten kan de toezichthouder op grond van Artikel 32(5)(b) een rechterlijke instantie of bevoegd orgaan verzoeken de persoon op het niveau van algemeen directeur of wettelijke vertegenwoordiger tijdelijk te verbieden leidinggevende functies in die entiteit uit te oefenen, wanneer zijn bevelen na een gestelde termijn worden genegeerd. Het verbod geldt totdat de tekortkomingen zijn verholpen.",
        fr: "Pour les seules entités essentielles, l'article 32(5)(b) permet à l'autorité de contrôle de demander à une juridiction ou à un organe compétent d'interdire temporairement à la personne exerçant des responsabilités dirigeantes au niveau de directeur général ou de représentant légal d'exercer des responsabilités dirigeantes dans cette entité, lorsque ses injonctions sont ignorées au-delà du délai imparti. L'interdiction s'applique jusqu'à ce qu'il soit remédié aux insuffisances.",
        it: "Solo per i soggetti essenziali, l'articolo 32(5)(b) consente all'autorità di vigilanza di chiedere a un organo giurisdizionale o a un organismo competente di vietare temporaneamente alla persona a livello di amministratore delegato o rappresentante legale di svolgere funzioni dirigenziali in tale soggetto, quando le sue prescrizioni sono ignorate oltre il termine fissato. Il divieto si applica finché non si è posto rimedio alle carenze.",
        es: "Solo para las entidades esenciales, el artículo 32(5)(b) permite a la autoridad supervisora solicitar a un órgano jurisdiccional u organismo competente que prohíba temporalmente a la persona a nivel de director general o representante legal ejercer funciones de dirección en dicha entidad, cuando sus requerimientos se desatienden una vez vencido el plazo. La prohibición se aplica hasta que se subsanen las deficiencias.",
        pl: "Wyłącznie w przypadku podmiotów kluczowych artykuł 32(5)(b) pozwala organowi nadzoru zwrócić się do sądu lub właściwej instytucji o nałożenie na osobę na poziomie dyrektora generalnego lub przedstawiciela prawnego tymczasowego zakazu pełnienia funkcji zarządczych w tym podmiocie, jeżeli jego nakazy są ignorowane mimo upływu wyznaczonego terminu. Zakaz obowiązuje do czasu usunięcia uchybień.",
        cs: "Pouze u základních subjektů umožňuje článek 32(5)(b) regulačnímu orgánu požádat soud nebo příslušný orgán, aby osobě na úrovni výkonného ředitele nebo zákonného zástupce dočasně zakázal výkon řídicích funkcí v tomto subjektu, pokud jeho příkazy nejsou respektovány ani po uplynutí stanovené lhůty. Zákaz trvá, dokud nejsou nedostatky napraveny.",
        pt: "Apenas para as entidades essenciais, o artigo 32(5)(b) permite à autoridade reguladora solicitar a um tribunal ou organismo competente que proíba temporariamente a pessoa a nível de diretor executivo ou representante legal de exercer funções de gestão nessa entidade, quando as suas ordens são ignoradas depois de expirado o prazo fixado. A proibição vigora até que as deficiências sejam corrigidas.",
        ro: "Doar pentru entitățile esențiale, articolul 32(5)(b) permite autorității de reglementare să solicite unei instanțe sau unui organism competent interzicerea temporară pentru persoana de la nivelul de director executiv sau reprezentant legal de a exercita funcții de conducere în cadrul entității respective, atunci când dispozițiile sale sunt ignorate după expirarea termenului stabilit. Interdicția se aplică până la remedierea deficiențelor.",
      },
    },
    {
      id: "1.3.3",
      question: {
        en: "How many layers of exposure does the lesson describe?",
        de: "Wie viele Haftungsebenen beschreibt die Lektion?",
        nl: "Hoeveel lagen van blootstelling beschrijft de les?",
        fr: "Combien de niveaux d'exposition la leçon décrit-elle ?",
        it: "Quanti livelli di esposizione descrive la lezione?",
        es: "¿Cuántos niveles de exposición describe la lección?",
        pl: "Ile poziomów odpowiedzialności opisuje lekcja?",
        cs: "Kolik vrstev vystavení riziku lekce popisuje?",
        pt: "Quantas camadas de exposição descreve a lição?",
        ro: "Câte straturi de expunere descrie lecția?",
      },
      options: [
        {
          en: "One: the company fine",
          de: "Eine: das Unternehmensbußgeld",
          nl: "Één: de boete voor de onderneming",
          fr: "Un : l'amende de l'entreprise",
          it: "Uno: la sanzione all'impresa",
          es: "Uno: la multa a la empresa",
          pl: "Jeden: kara pieniężna dla firmy",
          cs: "Jednu: pokutu pro společnost",
          pt: "Uma: a coima à empresa",
          ro: "Unul: amenda pentru companie",
        },
        {
          en: "Two: the company fine and the manager ban",
          de: "Zwei: das Unternehmensbußgeld und das Tätigkeitsverbot für Geschäftsleiter",
          nl: "Twee: de boete voor de onderneming en het bestuursverbod",
          fr: "Deux : l'amende de l'entreprise et l'interdiction d'exercer pour le dirigeant",
          it: "Due: la sanzione all'impresa e il divieto di esercizio per il dirigente",
          es: "Dos: la multa a la empresa y la inhabilitación del directivo",
          pl: "Dwa: kara pieniężna dla firmy i zakaz pełnienia funkcji kierowniczej",
          cs: "Dvě: pokutu pro společnost a zákaz výkonu funkce manažera",
          pt: "Duas: a coima à empresa e a proibição de exercício de funções de gestão",
          ro: "Două: amenda pentru companie și interdicția pentru manager",
        },
        {
          en: "Three: the company fine, the Article 32(5)(b) manager ban, and personal civil liability under corporate law",
          de: "Drei: das Unternehmensbußgeld, das Leitungsverbot nach Artikel 32 Absatz 5 Buchstabe b und die persönliche zivilrechtliche Haftung nach Gesellschaftsrecht",
          nl: "Drie: de boete voor de onderneming, het bestuursverbod van Artikel 32(5)(b) en persoonlijke civielrechtelijke aansprakelijkheid onder vennootschapsrecht",
          fr: "Trois : l'amende de l'entreprise, l'interdiction d'exercer pour le dirigeant au titre de l'article 32(5)(b), et la responsabilité civile personnelle au titre du droit des sociétés",
          it: "Tre: la sanzione all'impresa, il divieto di esercizio per il dirigente ai sensi dell'articolo 32(5)(b) e la responsabilità civile personale ai sensi del diritto societario",
          es: "Tres: la multa a la empresa, la inhabilitación del directivo en virtud del artículo 32(5)(b) y la responsabilidad civil personal en virtud del derecho de sociedades",
          pl: "Trzy: kara pieniężna dla firmy, zakaz pełnienia funkcji kierowniczej na podstawie artykułu 32(5)(b) oraz osobista odpowiedzialność cywilna na podstawie prawa spółek",
          cs: "Tři: pokutu pro společnost, zákaz výkonu funkce manažera podle článku 32(5)(b) a osobní občanskoprávní odpovědnost podle práva obchodních společností",
          pt: "Três: a coima à empresa, a proibição de exercício de funções de gestão do artigo 32(5)(b) e a responsabilidade civil pessoal ao abrigo do direito societário",
          ro: "Trei: amenda pentru companie, interdicția pentru manager prevăzută la articolul 32(5)(b) și răspunderea civilă personală în temeiul dreptului societar",
        },
        {
          en: "Four: fine, ban, civil liability, and criminal prosecution",
          de: "Vier: Bußgeld, Tätigkeitsverbot, Zivilhaftung und strafrechtliche Verfolgung",
          nl: "Vier: boete, verbod, civiele aansprakelijkheid en strafrechtelijke vervolging",
          fr: "Quatre : amende, interdiction d'exercer, responsabilité civile et poursuites pénales",
          it: "Quattro: sanzione, divieto di esercizio, responsabilità civile e azione penale",
          es: "Cuatro: multa, inhabilitación, responsabilidad civil y persecución penal",
          pl: "Cztery: kara pieniężna, zakaz pełnienia funkcji, odpowiedzialność cywilna i ściganie karne",
          cs: "Čtyři: pokutu, zákaz, občanskoprávní odpovědnost a trestní stíhání",
          pt: "Quatro: coima, proibição, responsabilidade civil e processo penal",
          ro: "Patru: amendă, interdicție, răspundere civilă și urmărire penală",
        },
      ],
      correctIndex: 2,
      explanation: {
        en: "The three layers are: (1) the administrative fine on the company, (2) the Article 32(5)(b) manager ban, which applies to Essential entities only, and (3) your own company suing you personally for damages under corporate law.",
        de: "Die drei Ebenen sind: (1) das Bußgeld gegen das Unternehmen, (2) das Leitungsverbot nach Artikel 32 Absatz 5 Buchstabe b, das nur für wesentliche Einrichtungen gilt, und (3) die persönliche Schadensersatzklage Ihres eigenen Unternehmens gegen Sie nach Gesellschaftsrecht.",
        nl: "De drie lagen zijn: (1) de bestuurlijke boete voor de onderneming, (2) het bestuursverbod van Artikel 32(5)(b), dat alleen voor essentiële entiteiten geldt, en (3) uw eigen onderneming die u persoonlijk aanklaagt voor schade op grond van vennootschapsrecht.",
        fr: "Les trois niveaux sont : (1) l'amende administrative infligée à l'entreprise, (2) l'interdiction d'exercer pour le dirigeant au titre de l'article 32(5)(b), qui ne s'applique qu'aux entités essentielles, et (3) votre propre entreprise vous poursuivant personnellement en dommages et intérêts au titre du droit des sociétés.",
        it: "I tre livelli sono: (1) la sanzione amministrativa all'impresa, (2) il divieto di esercizio per il dirigente ai sensi dell'articolo 32(5)(b), che si applica solo ai soggetti essenziali, e (3) la vostra stessa impresa che vi cita personalmente per il risarcimento dei danni ai sensi del diritto societario.",
        es: "Los tres niveles son: (1) la multa administrativa a la empresa, (2) la inhabilitación del directivo en virtud del artículo 32(5)(b), que solo se aplica a las entidades esenciales, y (3) su propia empresa demandándole personalmente por daños y perjuicios en virtud del derecho de sociedades.",
        pl: "Trzy poziomy to: (1) administracyjna kara pieniężna dla firmy, (2) zakaz pełnienia funkcji kierowniczej na podstawie artykułu 32(5)(b), który dotyczy wyłącznie podmiotów kluczowych, oraz (3) pozew o odszkodowanie wytoczony Państwu osobiście przez Państwa własną firmę na podstawie prawa spółek.",
        cs: "Tři vrstvy jsou: (1) správní pokuta pro společnost, (2) zákaz výkonu funkce manažera podle článku 32(5)(b), který se vztahuje pouze na základní subjekty, a (3) vaše vlastní společnost, která vás osobně žaluje o náhradu škody podle práva obchodních společností.",
        pt: "As três camadas são: (1) a coima administrativa à empresa, (2) a proibição de exercício de funções de gestão do artigo 32(5)(b), que se aplica apenas a entidades essenciais, e (3) a sua própria empresa a processá-lo pessoalmente por danos ao abrigo do direito societário.",
        ro: "Cele trei straturi sunt: (1) amenda administrativă pentru companie, (2) interdicția pentru manager prevăzută la articolul 32(5)(b), care se aplică doar entităților esențiale, și (3) propria companie care vă acționează în justiție personal pentru daune în temeiul dreptului societar.",
      },
    },
    {
      id: "1.3.4",
      question: {
        en: "What is the maximum fine cap for Important entities?",
        de: "Wie hoch ist die Bußgeldobergrenze für wichtige Einrichtungen?",
        nl: "Wat is het maximale boeteplafond voor belangrijke entiteiten?",
        fr: "Quel est le plafond maximal de l'amende pour les entités importantes ?",
        it: "Qual è il massimale della sanzione per i soggetti importanti?",
        es: "¿Cuál es el límite máximo de la multa para las entidades importantes?",
        pl: "Jaki jest maksymalny pułap kary pieniężnej dla podmiotów ważnych?",
        cs: "Jaký je maximální strop pokuty pro důležité subjekty?",
        pt: "Qual é o limite máximo da coima para entidades importantes?",
        ro: "Care este plafonul maxim al amenzii pentru entitățile importante?",
      },
      options: [
        {
          en: "Ten million euros or 2% of worldwide turnover",
          de: "Zehn Millionen Euro oder 2 % des weltweiten Umsatzes",
          nl: "Tien miljoen euro of 2% van de wereldwijde omzet",
          fr: "Dix millions d'euros ou 2 % du chiffre d'affaires mondial",
          it: "Dieci milioni di euro o 2% del fatturato mondiale",
          es: "Diez millones de euros o el 2% de la facturación mundial",
          pl: "Dziesięć milionów euro lub 2% światowego obrotu",
          cs: "Deset milionů eur nebo 2 % celosvětového obratu",
          pt: "Dez milhões de euros ou 2% do volume de negócios mundial",
          ro: "Zece milioane de euro sau 2% din cifra de afaceri mondială",
        },
        {
          en: "Seven million euros or 1.4% of worldwide turnover, whichever is higher",
          de: "Sieben Millionen Euro oder 1,4 % des weltweiten Umsatzes, je nachdem welcher Betrag höher ist",
          nl: "Zeven miljoen euro of 1,4% van de wereldwijde omzet, afhankelijk van welk bedrag hoger is",
          fr: "Sept millions d'euros ou 1,4 % du chiffre d'affaires mondial, le montant le plus élevé étant retenu",
          it: "Sette milioni di euro o 1,4% del fatturato mondiale, se superiore",
          es: "Siete millones de euros o el 1,4% de la facturación mundial, si esta cantidad es mayor",
          pl: "Siedem milionów euro lub 1,4% światowego obrotu, w zależności od tego, która kwota jest wyższa",
          cs: "Sedm milionů eur nebo 1,4 % celosvětového obratu, podle toho, co je vyšší",
          pt: "Sete milhões de euros ou 1,4% do volume de negócios mundial, consoante o que for mais elevado",
          ro: "Șapte milioane de euro sau 1,4% din cifra de afaceri mondială, oricare dintre acestea este mai mare",
        },
        {
          en: "Five million euros or 1% of worldwide turnover",
          de: "Fünf Millionen Euro oder 1 % des weltweiten Umsatzes",
          nl: "Vijf miljoen euro of 1% van de wereldwijde omzet",
          fr: "Cinq millions d'euros ou 1 % du chiffre d'affaires mondial",
          it: "Cinque milioni di euro o 1% del fatturato mondiale",
          es: "Cinco millones de euros o el 1% de la facturación mundial",
          pl: "Pięć milionów euro lub 1% światowego obrotu",
          cs: "Pět milionů eur nebo 1 % celosvětového obratu",
          pt: "Cinco milhões de euros ou 1% do volume de negócios mundial",
          ro: "Cinci milioane de euro sau 1% din cifra de afaceri mondială",
        },
        {
          en: "There is no cap for Important entities",
          de: "Es gibt keine Obergrenze für wichtige Einrichtungen",
          nl: "Er is geen plafond voor belangrijke entiteiten",
          fr: "Il n'y a pas de plafond pour les entités importantes",
          it: "Non vi è alcun massimale per i soggetti importanti",
          es: "No hay límite máximo para las entidades importantes",
          pl: "Nie ma pułapu dla podmiotów ważnych",
          cs: "Pro důležité subjekty žádný strop neexistuje",
          pt: "Não existe limite máximo para entidades importantes",
          ro: "Nu există plafon pentru entitățile importante",
        },
      ],
      correctIndex: 1,
      explanation: {
        en: "For Important entities, the cap is the higher of seven million euros or one point four percent of worldwide turnover.",
        de: "Für wichtige Einrichtungen liegt die Obergrenze beim höheren der beiden Beträge: sieben Millionen Euro oder 1,4 Prozent des weltweiten Umsatzes.",
        nl: "Voor belangrijke entiteiten is het plafond het hogere van zeven miljoen euro of één komma vier procent van de wereldwijde omzet.",
        fr: "Pour les entités importantes, le plafond correspond au montant le plus élevé entre sept millions d'euros et un virgule quatre pour cent du chiffre d'affaires mondial.",
        it: "Per i soggetti importanti, il massimale è il maggiore tra sette milioni di euro e l'uno virgola quattro per cento del fatturato mondiale.",
        es: "Para las entidades importantes, el límite es la cantidad mayor entre siete millones de euros y el uno coma cuatro por ciento de la facturación mundial.",
        pl: "Dla podmiotów ważnych pułap stanowi wyższa z kwot: siedem milionów euro lub jeden i cztery dziesiąte procent światowego obrotu.",
        cs: "Pro důležité subjekty je stropem vyšší z hodnot sedm milionů eur nebo jedna celá čtyři desetiny procenta celosvětového obratu.",
        pt: "Para as entidades importantes, o limite máximo é o valor mais elevado entre sete milhões de euros ou um vírgula quatro por cento do volume de negócios mundial.",
        ro: "Pentru entitățile importante, plafonul este valoarea cea mai mare dintre șapte milioane de euro sau unu virgulă patru la sută din cifra de afaceri mondială.",
      },
    },
  ],
});

export default quiz;
