import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.4",
  passingScore: 75,
  questions: [
    {
      id: "1.4.1",
      question: {
        en: "How long does a company have to register with the national regulator after becoming covered by NIS2?",
        de: "Wie lange hat ein Unternehmen Zeit, sich nach Eintritt in den Anwendungsbereich von NIS2 bei der nationalen Aufsichtsbehörde zu registrieren?",
        nl: "Hoeveel tijd heeft een bedrijf om zich te registreren bij de nationale toezichthouder nadat het onder NIS2 valt?",
        fr: "De combien de temps une entreprise dispose-t-elle pour s'enregistrer auprès de l'autorité de contrôle nationale après être entrée dans le champ d'application de NIS2 ?",
        it: "Quanto tempo ha un'impresa per registrarsi presso l'autorità di vigilanza nazionale dopo essere rientrata nell'ambito di applicazione di NIS2?",
        es: "¿De cuánto tiempo dispone una empresa para registrarse ante la autoridad reguladora nacional tras quedar incluida en el ámbito de aplicación de NIS2?",
        pl: "Ile czasu ma firma na rejestrację u krajowego organu nadzoru po objęciu jej zakresem NIS2?",
      },
      options: [
        { en: "One month", de: "Einen Monat", nl: "Één maand", fr: "Un mois", it: "Un mese", es: "Un mes", pl: "Jeden miesiąc" },
        { en: "Three months", de: "Drei Monate", nl: "Drie maanden", fr: "Trois mois", it: "Tre mesi", es: "Tres meses", pl: "Trzy miesiące" },
        { en: "Six months", de: "Sechs Monate", nl: "Zes maanden", fr: "Six mois", it: "Sei mesi", es: "Seis meses", pl: "Sześć miesięcy" },
        { en: "One year", de: "Ein Jahr", nl: "Één jaar", fr: "Un an", it: "Un anno", es: "Un año", pl: "Jeden rok" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 27 requires registration within three months of becoming subject to NIS2.",
        de: "Artikel 27 verlangt die Registrierung innerhalb von drei Monaten nach Eintritt in den Anwendungsbereich von NIS2.",
        nl: "Artikel 27 vereist registratie binnen drie maanden na het van toepassing worden van NIS2.",
        fr: "L'article 27 exige l'enregistrement dans un délai de trois mois à compter de l'assujettissement à NIS2.",
        it: "L'articolo 27 richiede la registrazione entro tre mesi dall'assoggettamento a NIS2.",
        es: "El artículo 27 exige el registro en un plazo de tres meses desde que se queda sujeto a NIS2.",
        pl: "Artykuł 27 wymaga rejestracji w terminie trzech miesięcy od objęcia przepisami NIS2.",
      },
    },
    {
      id: "1.4.2",
      question: {
        en: "Is missing or incorrect registration treated as a violation even without a cyber incident?",
        de: "Wird eine fehlende oder fehlerhafte Registrierung auch ohne Cybervorfall als Verstoß behandelt?",
        nl: "Wordt een ontbrekende of onjuiste registratie behandeld als een overtreding, zelfs zonder een cyberincident?",
        fr: "Un enregistrement manquant ou incorrect est-il considéré comme une violation, même en l'absence d'incident cyber ?",
        it: "Una registrazione mancante o errata è considerata una violazione anche in assenza di un incidente informatico?",
        es: "¿Se considera un registro ausente o incorrecto una infracción incluso sin un incidente cibernético?",
        pl: "Czy brak rejestracji lub nieprawidłowa rejestracja jest traktowana jako naruszenie nawet bez incydentu cybernetycznego?",
      },
      options: [
        { en: "No, a violation requires a cyber incident to have occurred", de: "Nein, ein Verstoß setzt einen Cybervorfall voraus", nl: "Nee, een overtreding vereist dat er een cyberincident heeft plaatsgevonden", fr: "Non, une violation suppose qu'un incident cyber se soit produit", it: "No, una violazione presuppone che si sia verificato un incidente informatico", es: "No, una infracción requiere que se haya producido un incidente cibernético", pl: "Nie, naruszenie wymaga, aby wystąpił incydent cybernetyczny" },
        { en: "Yes, it is a separate violation sanctioned under Article 32, independent of any incident", de: "Ja, es handelt sich um einen eigenständigen Verstoß nach Artikel 32, unabhängig von einem Vorfall", nl: "Ja, het is een afzonderlijke overtreding die wordt gesanctioneerd op grond van Artikel 32, onafhankelijk van enig incident", fr: "Oui, il s'agit d'une violation distincte sanctionnée au titre de l'article 32, indépendamment de tout incident", it: "Sì, si tratta di una violazione distinta sanzionata ai sensi dell'articolo 32, indipendentemente da qualsiasi incidente", es: "Sí, es una infracción independiente sancionada en virtud del artículo 32, con independencia de cualquier incidente", pl: "Tak, jest to odrębne naruszenie podlegające sankcji na podstawie artykułu 32, niezależnie od jakiegokolwiek incydentu" },
        { en: "Only if the regulator has already audited the company", de: "Nur wenn die Aufsichtsbehörde das Unternehmen bereits geprüft hat", nl: "Alleen als de toezichthouder het bedrijf al heeft gecontroleerd", fr: "Uniquement si l'autorité de contrôle a déjà audité l'entreprise", it: "Solo se l'autorità di vigilanza ha già verificato l'impresa", es: "Solo si la autoridad reguladora ya ha auditado la empresa", pl: "Tylko jeśli organ nadzoru już przeprowadził audyt firmy" },
        { en: "Only for Essential entities", de: "Nur für wesentliche Einrichtungen", nl: "Alleen voor essentiële entiteiten", fr: "Uniquement pour les entités essentielles", it: "Solo per i soggetti essenziali", es: "Solo para las entidades esenciales", pl: "Tylko dla podmiotów kluczowych" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Late or incorrect registration is sanctioned separately under Article 32 and does not require a cyber incident to trigger it.",
        de: "Verspätete oder fehlerhafte Registrierung wird nach Artikel 32 eigenständig sanktioniert und erfordert keinen Cybervorfall als Auslöser.",
        nl: "Te late of onjuiste registratie wordt afzonderlijk gesanctioneerd op grond van Artikel 32 en vereist geen cyberincident als aanleiding.",
        fr: "Un enregistrement tardif ou incorrect est sanctionné séparément au titre de l'article 32 et ne nécessite pas d'incident cyber pour être déclenché.",
        it: "Una registrazione tardiva o errata è sanzionata separatamente ai sensi dell'articolo 32 e non richiede un incidente informatico per essere attivata.",
        es: "El registro tardío o incorrecto se sanciona por separado en virtud del artículo 32 y no requiere un incidente cibernético para activarse.",
        pl: "Spóźniona lub nieprawidłowa rejestracja podlega odrębnej sankcji na podstawie artykułu 32 i nie wymaga incydentu cybernetycznego jako przesłanki.",
      },
    },
    {
      id: "1.4.3",
      question: {
        en: "What specific contact detail must be included in the NIS2 registration?",
        de: "Welche spezifische Kontaktangabe muss in der NIS2-Registrierung enthalten sein?",
        nl: "Welk specifiek contactgegeven moet zijn opgenomen in de NIS2-registratie?",
        fr: "Quelle coordonnée spécifique doit figurer dans l'enregistrement NIS2 ?",
        it: "Quale recapito specifico deve essere incluso nella registrazione NIS2?",
        es: "¿Qué dato de contacto específico debe incluirse en el registro NIS2?",
        pl: "Jaki konkretny dane kontaktowe muszą znaleźć się w rejestracji NIS2?",
      },
      options: [
        { en: "The CEO's personal mobile number", de: "Die persönliche Mobilnummer des Geschäftsführers", nl: "Het persoonlijke mobiele nummer van de CEO", fr: "Le numéro de mobile personnel du dirigeant", it: "Il numero di cellulare personale dell'amministratore delegato", es: "El número de móvil personal del director general", pl: "Prywatny numer telefonu komórkowego dyrektora generalnego" },
        { en: "A twenty-four-seven incident contact", de: "Ein rund um die Uhr erreichbarer Kontakt für Sicherheitsvorfälle", nl: "Een vierentwintig-zeven incidentcontact", fr: "Un contact incident disponible vingt-quatre heures sur vingt-quatre, sept jours sur sept", it: "Un contatto per gli incidenti disponibile ventiquattro ore su ventiquattro, sette giorni su sette", es: "Un contacto para incidentes disponible las veinticuatro horas, los siete días de la semana", pl: "Kontakt do zgłaszania incydentów dostępny przez całą dobę, siedem dni w tygodniu" },
        { en: "The company's general email address", de: "Die allgemeine E-Mail-Adresse des Unternehmens", nl: "Het algemene e-mailadres van het bedrijf", fr: "L'adresse e-mail générale de l'entreprise", it: "L'indirizzo e-mail generale dell'impresa", es: "La dirección de correo electrónico general de la empresa", pl: "Ogólny adres e-mail firmy" },
        { en: "The CISO's LinkedIn profile", de: "Das LinkedIn-Profil des CISO", nl: "Het LinkedIn-profiel van de CISO", fr: "Le profil LinkedIn du CISO", it: "Il profilo LinkedIn del CISO", es: "El perfil de LinkedIn del CISO", pl: "Profil CISO w serwisie LinkedIn" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The registration must include a twenty-four-seven incident contact, among other details.",
        de: "Die Registrierung muss unter anderem einen rund um die Uhr erreichbaren Kontakt für Sicherheitsvorfälle enthalten.",
        nl: "De registratie moet onder andere een vierentwintig-zeven incidentcontact bevatten.",
        fr: "L'enregistrement doit inclure, entre autres, un contact incident disponible vingt-quatre heures sur vingt-quatre, sept jours sur sept.",
        it: "La registrazione deve includere, tra gli altri dettagli, un contatto per gli incidenti disponibile ventiquattro ore su ventiquattro, sette giorni su sette.",
        es: "El registro debe incluir, entre otros datos, un contacto para incidentes disponible las veinticuatro horas, los siete días de la semana.",
        pl: "Rejestracja musi zawierać między innymi kontakt do zgłaszania incydentów dostępny przez całą dobę, siedem dni w tygodniu.",
      },
    },
    {
      id: "1.4.4",
      question: {
        en: "As of March 2026, approximately how many of the estimated 29,500 in-scope German companies had registered?",
        de: "Wie viele der geschätzten 29.500 betroffenen deutschen Unternehmen hatten sich bis März 2026 ungefähr registriert?",
        nl: "Hoeveel van de geschatte 29.500 in aanmerking komende Duitse bedrijven hadden zich per maart 2026 geregistreerd?",
        fr: "En mars 2026, combien environ des quelque 29 500 entreprises allemandes concernées s'étaient enregistrées ?",
        it: "A marzo 2026, quante circa delle stimate 29.500 imprese tedesche rientranti nell'ambito si erano registrate?",
        es: "En marzo de 2026, ¿cuántas de las aproximadamente 29.500 empresas alemanas incluidas en el ámbito se habían registrado?",
        pl: "Według stanu na marzec 2026 r., ile spośród szacowanych 29 500 niemieckich firm objętych zakresem zarejestrowało się?",
      },
      options: [
        { en: "About 5,000", de: "Etwa 5.000", nl: "Ongeveer 5.000", fr: "Environ 5 000", it: "Circa 5.000", es: "Aproximadamente 5.000", pl: "Około 5000" },
        { en: "About 11,500", de: "Etwa 11.500", nl: "Ongeveer 11.500", fr: "Environ 11 500", it: "Circa 11.500", es: "Aproximadamente 11.500", pl: "Około 11 500" },
        { en: "About 20,000", de: "Etwa 20.000", nl: "Ongeveer 20.000", fr: "Environ 20 000", it: "Circa 20.000", es: "Aproximadamente 20.000", pl: "Około 20 000" },
        { en: "About 29,000", de: "Etwa 29.000", nl: "Ongeveer 29.000", fr: "Environ 29 000", it: "Circa 29.000", es: "Aproximadamente 29.000", pl: "Około 29 000" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Roughly eleven thousand five hundred of an estimated twenty-nine thousand five hundred in-scope German companies had registered by March 2026.",
        de: "Etwa 11.500 der geschätzten 29.500 betroffenen deutschen Unternehmen hatten sich bis März 2026 registriert.",
        nl: "Ongeveer elfduizend vijfhonderd van de geschatte negenentwintigduizend vijfhonderd in aanmerking komende Duitse bedrijven hadden zich per maart 2026 geregistreerd.",
        fr: "Environ onze mille cinq cents des quelque vingt-neuf mille cinq cents entreprises allemandes concernées s'étaient enregistrées en mars 2026.",
        it: "Circa undicimila cinquecento delle stimate ventinovemila cinquecento imprese tedesche rientranti nell'ambito si erano registrate entro marzo 2026.",
        es: "Aproximadamente once mil quinientas de las estimadas veintinueve mil quinientas empresas alemanas incluidas en el ámbito se habían registrado en marzo de 2026.",
        pl: "Do marca 2026 r. zarejestrowało się około jedenastu tysięcy pięciuset spośród szacowanych dwudziestu dziewięciu tysięcy pięciuset niemieckich firm objętych zakresem.",
      },
    },
  ],
});

export default quiz;
