import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.4",
  passingScore: 75,
  questions: [
    {
      id: "1.4.1",
      question: {
        en: "In Germany, how long does a company have to register with the national regulator after becoming covered by NIS2?",
        de: "Wie lange hat ein Unternehmen in Deutschland Zeit, sich nach Eintritt in den Anwendungsbereich von NIS2 bei der nationalen Aufsichtsbehörde zu registrieren?",
        nl: "Hoeveel tijd heeft een bedrijf in Duitsland om zich te registreren bij de nationale toezichthouder nadat het onder NIS2 valt?",
        fr: "En Allemagne, de combien de temps une entreprise dispose-t-elle pour s'enregistrer auprès de l'autorité de contrôle nationale après être entrée dans le champ d'application de NIS2 ?",
        it: "In Germania, quanto tempo ha un'impresa per registrarsi presso l'autorità di vigilanza nazionale dopo essere rientrata nell'ambito di applicazione di NIS2?",
        es: "En Alemania, ¿de cuánto tiempo dispone una empresa para registrarse ante la autoridad reguladora nacional tras quedar incluida en el ámbito de aplicación de NIS2?",
        pl: "Ile czasu ma firma w Niemczech na rejestrację u krajowego organu nadzoru po objęciu jej zakresem NIS2?",
        cs: "Jak dlouhou lhůtu má společnost v Německu na registraci u vnitrostátního regulačního orgánu poté, co se na ni začne vztahovat NIS2?",
        pt: "Na Alemanha, de quanto tempo dispõe uma empresa para se registar junto da autoridade reguladora nacional após ficar abrangida pela NIS2?",
        ro: "În Germania, cât timp are o companie pentru a se înregistra la autoritatea națională de reglementare după ce intră sub incidența NIS2?",
      },
      options: [
        { en: "One month", de: "Einen Monat", nl: "Één maand", fr: "Un mois", it: "Un mese", es: "Un mes", pl: "Jeden miesiąc", cs: "Jeden měsíc", pt: "Um mês", ro: "O lună" },
        { en: "Three months", de: "Drei Monate", nl: "Drie maanden", fr: "Trois mois", it: "Tre mesi", es: "Tres meses", pl: "Trzy miesiące", cs: "Tři měsíce", pt: "Três meses", ro: "Trei luni" },
        { en: "Six months", de: "Sechs Monate", nl: "Zes maanden", fr: "Six mois", it: "Sei mesi", es: "Seis meses", pl: "Sześć miesięcy", cs: "Šest měsíců", pt: "Seis meses", ro: "Șase luni" },
        { en: "One year", de: "Ein Jahr", nl: "Één jaar", fr: "Un an", it: "Un anno", es: "Un año", pl: "Jeden rok", cs: "Jeden rok", pt: "Um ano", ro: "Un an" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 3(4) NIS2 requires registration; in Germany, Section 33 BSIG sets three months from becoming subject to NIS2.",
        de: "Artikel 3 Absatz 4 NIS2 verlangt die Registrierung; in Deutschland setzt § 33 BSIG dafür drei Monate nach Eintritt in den Anwendungsbereich von NIS2.",
        nl: "Artikel 3, lid 4, NIS2 vereist registratie; in Duitsland geeft § 33 BSIG daarvoor drie maanden na het van toepassing worden van NIS2.",
        fr: "L'article 3, paragraphe 4, de NIS2 exige l'enregistrement ; en Allemagne, le § 33 BSIG fixe un délai de trois mois à compter de l'assujettissement à NIS2.",
        it: "L'articolo 3, paragrafo 4, NIS2 richiede la registrazione; in Germania il § 33 BSIG fissa un termine di tre mesi dall'assoggettamento a NIS2.",
        es: "El artículo 3, apartado 4, de NIS2 exige el registro; en Alemania, el § 33 BSIG fija un plazo de tres meses desde que se queda sujeto a NIS2.",
        pl: "Artykuł 3 ust. 4 NIS2 wymaga rejestracji; w Niemczech § 33 BSIG wyznacza na nią termin trzech miesięcy od objęcia przepisami NIS2.",
        cs: "Čl. 3 odst. 4 NIS2 vyžaduje registraci; v Německu na ni § 33 BSIG dává tři měsíce od okamžiku, kdy se na subjekt začne vztahovat NIS2.",
        pt: "O artigo 3.o, n.o 4, da NIS2 exige o registo; na Alemanha, o § 33 BSIG fixa o prazo de três meses após ficar sujeito à NIS2.",
        ro: "Articolul 3 alineatul (4) din NIS2 impune înregistrarea; în Germania, § 33 BSIG stabilește un termen de trei luni de la momentul în care intrați sub incidența NIS2.",
      },
    },
    {
      id: "1.4.2",
      question: {
        en: "Is missing or incorrect registration treated as a violation even without a cyber incident?",
        de: "Wird eine fehlende oder fehlerhafte Registrierung auch ohne Cybervorfall als Verstoß behandelt?",
        nl: "Wordt een ontbrekende of onjuiste registratie behandeld als een overtreding, zelfs zonder een cyberincident?",
        fr: "Un enregistrement manquant ou incorrect est-il considéré comme une violation, même en l'absence d'incident cyber ?",
        it: "Una registrazione mancante o errata è considerata una violazione anche in assenza di un incidente informatico?",
        es: "¿Se considera un registro ausente o incorrecto una infracción incluso sin un incidente cibernético?",
        pl: "Czy brak rejestracji lub nieprawidłowa rejestracja jest traktowana jako naruszenie nawet bez incydentu cybernetycznego?",
        cs: "Považuje se chybějící nebo nesprávná registrace za porušení i bez kybernetického incidentu?",
        pt: "A falta de registo ou o registo incorreto é tratado como infração mesmo sem um ciberincidente?",
        ro: "Lipsa înregistrării sau înregistrarea incorectă este tratată ca încălcare chiar și în absența unui incident cibernetic?",
      },
      options: [
        { en: "No, a violation requires a cyber incident to have occurred", de: "Nein, ein Verstoß setzt einen Cybervorfall voraus", nl: "Nee, een overtreding vereist dat er een cyberincident heeft plaatsgevonden", fr: "Non, une violation suppose qu'un incident cyber se soit produit", it: "No, una violazione presuppone che si sia verificato un incidente informatico", es: "No, una infracción requiere que se haya producido un incidente cibernético", pl: "Nie, naruszenie wymaga, aby wystąpił incydent cybernetyczny", cs: "Ne, k porušení je nutné, aby došlo ke kybernetickému incidentu", pt: "Não, uma infração exige que tenha ocorrido um ciberincidente", ro: "Nu, o încălcare necesită ca un incident cibernetic să fi survenit" },
        { en: "Yes, it is a separate violation sanctioned under Article 32, independent of any incident", de: "Ja, es handelt sich um einen eigenständigen Verstoß nach Artikel 32, unabhängig von einem Vorfall", nl: "Ja, het is een afzonderlijke overtreding die wordt gesanctioneerd op grond van Artikel 32, onafhankelijk van enig incident", fr: "Oui, il s'agit d'une violation distincte sanctionnée au titre de l'article 32, indépendamment de tout incident", it: "Sì, si tratta di una violazione distinta sanzionata ai sensi dell'articolo 32, indipendentemente da qualsiasi incidente", es: "Sí, es una infracción independiente sancionada en virtud del artículo 32, con independencia de cualquier incidente", pl: "Tak, jest to odrębne naruszenie podlegające sankcji na podstawie artykułu 32, niezależnie od jakiegokolwiek incydentu", cs: "Ano, je to samostatné porušení postižitelné podle článku 32, nezávislé na jakémkoli incidentu", pt: "Sim, constitui uma infração distinta sancionada ao abrigo do artigo 32, independente de qualquer incidente", ro: "Da, este o încălcare distinctă sancționată în temeiul articolului 32, independentă de orice incident" },
        { en: "Only if the regulator has already audited the company", de: "Nur wenn die Aufsichtsbehörde das Unternehmen bereits geprüft hat", nl: "Alleen als de toezichthouder het bedrijf al heeft gecontroleerd", fr: "Uniquement si l'autorité de contrôle a déjà audité l'entreprise", it: "Solo se l'autorità di vigilanza ha già verificato l'impresa", es: "Solo si la autoridad reguladora ya ha auditado la empresa", pl: "Tylko jeśli organ nadzoru już przeprowadził audyt firmy", cs: "Pouze pokud regulační orgán společnost již auditoval", pt: "Apenas se a autoridade reguladora já tiver auditado a empresa", ro: "Doar dacă autoritatea de reglementare a auditat deja compania" },
        { en: "Only for Essential entities", de: "Nur für wesentliche Einrichtungen", nl: "Alleen voor essentiële entiteiten", fr: "Uniquement pour les entités essentielles", it: "Solo per i soggetti essenziali", es: "Solo para las entidades esenciales", pl: "Tylko dla podmiotów kluczowych", cs: "Pouze u základních subjektů", pt: "Apenas para entidades essenciais", ro: "Doar pentru entitățile esențiale" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Late or incorrect registration is sanctioned separately under Article 32 and does not require a cyber incident to trigger it.",
        de: "Verspätete oder fehlerhafte Registrierung wird nach Artikel 32 eigenständig sanktioniert und erfordert keinen Cybervorfall als Auslöser.",
        nl: "Te late of onjuiste registratie wordt afzonderlijk gesanctioneerd op grond van Artikel 32 en vereist geen cyberincident als aanleiding.",
        fr: "Un enregistrement tardif ou incorrect est sanctionné séparément au titre de l'article 32 et ne nécessite pas d'incident cyber pour être déclenché.",
        it: "Una registrazione tardiva o errata è sanzionata separatamente ai sensi dell'articolo 32 e non richiede un incidente informatico per essere attivata.",
        es: "El registro tardío o incorrecto se sanciona por separado en virtud del artículo 32 y no requiere un incidente cibernético para activarse.",
        pl: "Spóźniona lub nieprawidłowa rejestracja podlega odrębnej sankcji na podstawie artykułu 32 i nie wymaga incydentu cybernetycznego jako przesłanki.",
        cs: "Pozdní nebo nesprávná registrace se postihuje samostatně podle článku 32 a k jejímu uplatnění není nutný kybernetický incident.",
        pt: "O registo tardio ou incorreto é sancionado separadamente ao abrigo do artigo 32 e não requer um ciberincidente para ser despoletado.",
        ro: "Înregistrarea tardivă sau incorectă este sancționată separat în temeiul articolului 32 și nu necesită un incident cibernetic pentru a fi declanșată.",
      },
    },
    {
      id: "1.4.3",
      question: {
        en: "What specific contact detail must be included in the NIS2 registration?",
        de: "Welche spezifische Kontaktangabe muss in der NIS2-Registrierung enthalten sein?",
        nl: "Welk specifiek contactgegeven moet zijn opgenomen in de NIS2-registratie?",
        fr: "Quelle coordonnée spécifique doit figurer dans l'enregistrement NIS2 ?",
        it: "Quale recapito specifico deve essere incluso nella registrazione NIS2?",
        es: "¿Qué dato de contacto específico debe incluirse en el registro NIS2?",
        pl: "Jaki konkretny dane kontaktowe muszą znaleźć się w rejestracji NIS2?",
        cs: "Jaký konkrétní kontaktní údaj musí registrace NIS2 obsahovat?",
        pt: "Que dado de contacto específico tem de constar do registo NIS2?",
        ro: "Ce dată de contact specifică trebuie inclusă în înregistrarea NIS2?",
      },
      options: [
        { en: "The CEO's personal mobile number", de: "Die persönliche Mobilnummer des Geschäftsführers", nl: "Het persoonlijke mobiele nummer van de CEO", fr: "Le numéro de mobile personnel du dirigeant", it: "Il numero di cellulare personale dell'amministratore delegato", es: "El número de móvil personal del director general", pl: "Prywatny numer telefonu komórkowego dyrektora generalnego", cs: "Osobní mobilní číslo generálního ředitele", pt: "O número de telemóvel pessoal do diretor executivo", ro: "Numărul de telefon mobil personal al directorului general" },
        { en: "The company's public IP address ranges", de: "Die öffentlichen IP-Adressbereiche des Unternehmens", nl: "De openbare IP-adresbereiken van het bedrijf", fr: "Les plages d'adresses IP publiques de l'entreprise", it: "Gli intervalli di indirizzi IP pubblici dell'impresa", es: "Los rangos de direcciones IP públicas de la empresa", pl: "Publiczne zakresy adresów IP firmy", cs: "Veřejné rozsahy IP adres společnosti", pt: "As gamas de endereços IP públicos da empresa", ro: "Intervalele de adrese IP publice ale companiei" },
        { en: "The home address of each managing director", de: "Die Privatanschrift jedes Geschäftsführers", nl: "Het huisadres van elke bestuurder", fr: "L'adresse personnelle de chaque dirigeant", it: "L'indirizzo di casa di ciascun amministratore", es: "El domicilio particular de cada administrador", pl: "Adres domowy każdego członka zarządu", cs: "Adresa bydliště každého jednatele", pt: "A morada pessoal de cada administrador", ro: "Adresa de domiciliu a fiecărui administrator" },
        { en: "The CISO's LinkedIn profile", de: "Das LinkedIn-Profil des CISO", nl: "Het LinkedIn-profiel van de CISO", fr: "Le profil LinkedIn du CISO", it: "Il profilo LinkedIn del CISO", es: "El perfil de LinkedIn del CISO", pl: "Profil CISO w serwisie LinkedIn", cs: "Profil CISO na LinkedInu", pt: "O perfil de LinkedIn do CISO", ro: "Profilul de LinkedIn al CISO" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The registration must include, among other details, the company's public IP address ranges (Article 3(4) NIS2, Section 33 BSIG). This applies to every covered company.",
        de: "Die Registrierung muss unter anderem die öffentlichen IP-Adressbereiche des Unternehmens enthalten (Artikel 3 Absatz 4 NIS2, § 33 BSIG). Das gilt für jedes betroffene Unternehmen.",
        nl: "De registratie moet onder andere de openbare IP-adresbereiken van het bedrijf bevatten (Artikel 3, lid 4, NIS2, § 33 BSIG). Dat geldt voor elk gedekt bedrijf.",
        fr: "L'enregistrement doit inclure, entre autres, les plages d'adresses IP publiques de l'entreprise (article 3, paragraphe 4, de NIS2, § 33 BSIG). Cela vaut pour toute entreprise concernée.",
        it: "La registrazione deve includere, tra gli altri dettagli, gli intervalli di indirizzi IP pubblici dell'impresa (articolo 3, paragrafo 4, NIS2, § 33 BSIG). Vale per ogni impresa interessata.",
        es: "El registro debe incluir, entre otros datos, los rangos de direcciones IP públicas de la empresa (artículo 3, apartado 4, de NIS2, § 33 BSIG). Se aplica a toda empresa afectada.",
        pl: "Rejestracja musi zawierać między innymi publiczne zakresy adresów IP firmy (artykuł 3 ust. 4 NIS2, § 33 BSIG). Dotyczy to każdej objętej firmy.",
        cs: "Registrace musí mimo jiné obsahovat veřejné rozsahy IP adres společnosti (čl. 3 odst. 4 NIS2, § 33 BSIG). Platí to pro každou dotčenou společnost.",
        pt: "O registo tem de incluir, entre outros dados, as gamas de endereços IP públicos da empresa (artigo 3.o, n.o 4, da NIS2, § 33 BSIG). Isto aplica-se a qualquer empresa abrangida.",
        ro: "Înregistrarea trebuie să includă, printre alte date, intervalele de adrese IP publice ale companiei (Articolul 3 alineatul (4) din NIS2, § 33 BSIG). Aceasta se aplică oricărei companii vizate.",
      },
    },
    {
      id: "1.4.4",
      question: {
        en: "As of March 2026, approximately how many of the estimated 29,500 in-scope German companies had registered?",
        de: "Wie viele der geschätzten 29.500 betroffenen deutschen Unternehmen hatten sich bis März 2026 ungefähr registriert?",
        nl: "Hoeveel van de geschatte 29.500 in aanmerking komende Duitse bedrijven hadden zich per maart 2026 geregistreerd?",
        fr: "En mars 2026, combien environ des quelque 29 500 entreprises allemandes concernées s'étaient enregistrées ?",
        it: "A marzo 2026, quante circa delle stimate 29.500 imprese tedesche rientranti nell'ambito si erano registrate?",
        es: "En marzo de 2026, ¿cuántas de las aproximadamente 29.500 empresas alemanas incluidas en el ámbito se habían registrado?",
        pl: "Według stanu na marzec 2026 r., ile spośród szacowanych 29 500 niemieckich firm objętych zakresem zarejestrowało się?",
        cs: "Kolik z odhadovaných 29 500 dotčených německých společností bylo přibližně zaregistrováno k březnu 2026?",
        pt: "Em março de 2026, aproximadamente quantas das estimadas 29.500 empresas alemãs abrangidas se tinham registado?",
        ro: "În martie 2026, aproximativ câte dintre cele estimate 29.500 de companii germane vizate se înregistraseră?",
      },
      options: [
        { en: "About 5,000", de: "Etwa 5.000", nl: "Ongeveer 5.000", fr: "Environ 5 000", it: "Circa 5.000", es: "Aproximadamente 5.000", pl: "Około 5000", cs: "Přibližně 5 000", pt: "Cerca de 5.000", ro: "Aproximativ 5.000" },
        { en: "About 11,500", de: "Etwa 11.500", nl: "Ongeveer 11.500", fr: "Environ 11 500", it: "Circa 11.500", es: "Aproximadamente 11.500", pl: "Około 11 500", cs: "Přibližně 11 500", pt: "Cerca de 11.500", ro: "Aproximativ 11.500" },
        { en: "About 20,000", de: "Etwa 20.000", nl: "Ongeveer 20.000", fr: "Environ 20 000", it: "Circa 20.000", es: "Aproximadamente 20.000", pl: "Około 20 000", cs: "Přibližně 20 000", pt: "Cerca de 20.000", ro: "Aproximativ 20.000" },
        { en: "About 29,000", de: "Etwa 29.000", nl: "Ongeveer 29.000", fr: "Environ 29 000", it: "Circa 29.000", es: "Aproximadamente 29.000", pl: "Około 29 000", cs: "Přibližně 29 000", pt: "Cerca de 29.000", ro: "Aproximativ 29.000" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Roughly eleven thousand five hundred of an estimated twenty-nine thousand five hundred in-scope German companies had registered by March 2026.",
        de: "Etwa 11.500 der geschätzten 29.500 betroffenen deutschen Unternehmen hatten sich bis März 2026 registriert.",
        nl: "Ongeveer elfduizend vijfhonderd van de geschatte negenentwintigduizend vijfhonderd in aanmerking komende Duitse bedrijven hadden zich per maart 2026 geregistreerd.",
        fr: "Environ onze mille cinq cents des quelque vingt-neuf mille cinq cents entreprises allemandes concernées s'étaient enregistrées en mars 2026.",
        it: "Circa undicimila cinquecento delle stimate ventinovemila cinquecento imprese tedesche rientranti nell'ambito si erano registrate entro marzo 2026.",
        es: "Aproximadamente once mil quinientas de las estimadas veintinueve mil quinientas empresas alemanas incluidas en el ámbito se habían registrado en marzo de 2026.",
        pl: "Do marca 2026 r. zarejestrowało się około jedenastu tysięcy pięciuset spośród szacowanych dwudziestu dziewięciu tysięcy pięciuset niemieckich firm objętych zakresem.",
        cs: "Zhruba jedenáct tisíc pět set z odhadovaných dvaceti devíti tisíc pěti set dotčených německých společností se zaregistrovalo do března 2026.",
        pt: "Cerca de onze mil e quinhentas das estimadas vinte e nove mil e quinhentas empresas alemãs abrangidas tinham-se registado até março de 2026.",
        ro: "Aproximativ unsprezece mii cinci sute dintre cele estimate douăzeci și nouă de mii cinci sute de companii germane vizate se înregistraseră până în martie 2026.",
      },
    },
  ],
});

export default quiz;
