import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.6",
  passingScore: 75,
  questions: [
    {
      id: "1.6.1",
      question: {
        en: "What three competence areas must the training cover under Article 20(2)?",
        de: "Welche drei Kompetenzbereiche muss die Schulung gemäß Artikel 20 Absatz 2 abdecken?",
        nl: "Welke drie competentiegebieden moet de training dekken op grond van Artikel 20(2)?",
        fr: "Quels sont les trois domaines de compétence que la formation doit couvrir au titre de l'article 20(2) ?",
        it: "Quali tre aree di competenza deve coprire la formazione ai sensi dell'articolo 20(2)?",
        es: "¿Qué tres áreas de competencia debe abarcar la formación en virtud del artículo 20(2)?",
        pl: "Jakie trzy obszary kompetencji musi obejmować szkolenie na podstawie artykułu 20(2)?",
        cs: "Jaké tři oblasti kompetencí musí školení podle článku 20(2) pokrýt?",
        pt: "Que três áreas de competência tem a formação de abranger nos termos do artigo 20(2)?",
        ro: "Ce trei domenii de competență trebuie să acopere formarea în temeiul articolului 20(2)?",
      },
      options: [
        { en: "Budgeting, staffing, and vendor selection", de: "Budgetierung, Personalplanung und Lieferantenauswahl", nl: "Budgettering, personeelsplanning en leveranciersselectie", fr: "Budgétisation, gestion du personnel et sélection des fournisseurs", it: "Definizione del budget, gestione del personale e selezione dei fornitori", es: "Presupuestación, dotación de personal y selección de proveedores", pl: "Budżetowanie, obsada kadrowa i wybór dostawców", cs: "Rozpočtování, personální obsazení a výběr dodavatelů", pt: "Orçamentação, dotação de pessoal e seleção de fornecedores", ro: "Bugetare, personal și selecția furnizorilor" },
        { en: "Identifying risks, assessing the measures, and assessing their impact on services", de: "Risiken erkennen, die Maßnahmen bewerten und deren Auswirkungen auf die Dienste beurteilen", nl: "Risico's identificeren, de maatregelen beoordelen en de impact ervan op de diensten beoordelen", fr: "Identifier les risques, évaluer les mesures et évaluer leur impact sur les services", it: "Individuare i rischi, valutare le misure e valutarne l'impatto sui servizi", es: "Identificar los riesgos, evaluar las medidas y evaluar su impacto en los servicios", pl: "Identyfikowanie ryzyka, ocena środków oraz ocena ich wpływu na usługi", cs: "Identifikace rizik, posouzení opatření a posouzení jejich dopadu na služby", pt: "Identificação de riscos, avaliação das medidas e avaliação do seu impacto nos serviços", ro: "Identificarea riscurilor, evaluarea măsurilor și evaluarea impactului acestora asupra serviciilor" },
        { en: "Network security, endpoint security, and cloud security", de: "Netzwerksicherheit, Endgerätesicherheit und Cloud-Sicherheit", nl: "Netwerkbeveiliging, eindpuntbeveiliging en cloudbeveiliging", fr: "Sécurité des réseaux, sécurité des terminaux et sécurité du cloud", it: "Sicurezza delle reti, sicurezza degli endpoint e sicurezza del cloud", es: "Seguridad de redes, seguridad de los dispositivos finales y seguridad en la nube", pl: "Bezpieczeństwo sieci, bezpieczeństwo urządzeń końcowych i bezpieczeństwo chmury", cs: "Zabezpečení sítě, zabezpečení koncových zařízení a zabezpečení cloudu", pt: "Segurança de rede, segurança de terminais e segurança na nuvem", ro: "Securitatea rețelei, securitatea echipamentelor terminale și securitatea în cloud" },
        { en: "Legal compliance, financial reporting, and data governance", de: "Rechtskonformität, Finanzberichterstattung und Daten-Governance", nl: "Juridische naleving, financiële rapportage en datagovernance", fr: "Conformité juridique, information financière et gouvernance des données", it: "Conformità giuridica, rendicontazione finanziaria e governance dei dati", es: "Cumplimiento jurídico, información financiera y gobernanza de datos", pl: "Zgodność prawna, sprawozdawczość finansowa i zarządzanie danymi", cs: "Právní soulad, finanční výkaznictví a správa dat", pt: "Conformidade jurídica, relato financeiro e governação de dados", ro: "Conformitatea juridică, raportarea financiară și guvernanța datelor" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 20(2) requires training to cover identifying risks, assessing the risk-management measures, and assessing their impact on the services the entity provides.",
        de: "Artikel 20 Absatz 2 verlangt, dass die Schulung das Erkennen von Risiken, die Bewertung der Risikomanagementmaßnahmen und die Beurteilung ihrer Auswirkungen auf die von der Einrichtung erbrachten Dienste abdeckt.",
        nl: "Artikel 20(2) vereist dat de training het identificeren van risico's, het beoordelen van de risicobeheermaatregelen en het beoordelen van de impact ervan op de door de entiteit verleende diensten omvat.",
        fr: "L'article 20(2) exige que la formation couvre l'identification des risques, l'évaluation des mesures de gestion des risques et l'évaluation de leur impact sur les services fournis par l'entité.",
        it: "L'articolo 20(2) richiede che la formazione copra l'individuazione dei rischi, la valutazione delle misure di gestione dei rischi e la valutazione del loro impatto sui servizi forniti dal soggetto.",
        es: "El artículo 20(2) exige que la formación abarque la identificación de riesgos, la evaluación de las medidas de gestión de riesgos y la evaluación de su impacto en los servicios que presta la entidad.",
        pl: "Artykuł 20(2) wymaga, aby szkolenie obejmowało identyfikowanie ryzyka, ocenę środków zarządzania ryzykiem oraz ocenę ich wpływu na usługi świadczone przez podmiot.",
        cs: "Článek 20(2) vyžaduje, aby školení pokrylo identifikaci rizik, posouzení opatření k řízení rizik a posouzení jejich dopadu na služby, které subjekt poskytuje.",
        pt: "O artigo 20(2) exige que a formação abranja a identificação de riscos, a avaliação das medidas de gestão de riscos e a avaliação do seu impacto nos serviços que a entidade presta.",
        ro: "Articolul 20(2) impune ca formarea să acopere identificarea riscurilor, evaluarea măsurilor de gestionare a riscurilor și evaluarea impactului acestora asupra serviciilor furnizate de entitate.",
      },
    },
    {
      id: "1.6.2",
      question: {
        en: "Can you send your CISO to attend the management training on your behalf?",
        de: "Können Sie Ihren CISO an Ihrer Stelle zur Geschäftsleitungsschulung schicken?",
        nl: "Kunt u uw CISO namens u naar de managementtraining sturen?",
        fr: "Pouvez-vous envoyer votre CISO assister à la formation de direction à votre place ?",
        it: "Potete inviare il vostro CISO a partecipare alla formazione per la dirigenza al vostro posto?",
        es: "¿Puede enviar a su CISO a asistir a la formación de la dirección en su nombre?",
        pl: "Czy mogą Państwo wysłać swojego CISO na szkolenie dla kierownictwa w Państwa imieniu?",
        cs: "Můžete vyslat svého CISO, aby se zúčastnil školení vedení místo vás?",
        pt: "Pode enviar o seu CISO para assistir à formação da administração em seu nome?",
        ro: "Vă puteți trimite CISO să participe la formarea conducerii în numele dumneavoastră?",
      },
      options: [
        { en: "Yes, if the CISO reports back to you", de: "Ja, wenn der CISO Ihnen anschließend Bericht erstattet", nl: "Ja, als de CISO achteraf aan u rapporteert", fr: "Oui, si le CISO vous en rend compte ensuite", it: "Sì, se il CISO ve ne riferisce successivamente", es: "Sí, si el CISO le informa después", pl: "Tak, jeśli CISO zda Państwu później sprawozdanie", cs: "Ano, pokud vám CISO podá zprávu", pt: "Sim, se o CISO lhe fizer um relato", ro: "Da, dacă CISO vă raportează ulterior" },
        { en: "Yes, the CISO is the designated training delegate", de: "Ja, der CISO ist der vorgesehene Schulungsvertreter", nl: "Ja, de CISO is de aangewezen trainingsvertegenwoordiger", fr: "Oui, le CISO est le délégué désigné pour la formation", it: "Sì, il CISO è il delegato designato per la formazione", es: "Sí, el CISO es el delegado designado para la formación", pl: "Tak, CISO jest wyznaczonym przedstawicielem na szkolenie", cs: "Ano, CISO je určeným zástupcem pro školení", pt: "Sim, o CISO é o delegado designado para a formação", ro: "Da, CISO este delegatul desemnat pentru formare" },
        { en: "No, the training duty is personal and non-delegable", de: "Nein, die Schulungspflicht ist persönlich und nicht delegierbar", nl: "Nee, de trainingsplicht is persoonlijk en niet delegeerbaar", fr: "Non, l'obligation de formation est personnelle et non délégable", it: "No, l'obbligo di formazione è personale e non delegabile", es: "No, el deber de formación es personal e indelegable", pl: "Nie, obowiązek szkolenia jest osobisty i nie podlega delegowaniu", cs: "Ne, povinnost školení je osobní a nedelegovatelná", pt: "Não, o dever de formação é pessoal e indelegável", ro: "Nu, obligația de formare este personală și nedelegabilă" },
        { en: "Only if the CISO is also a member of the management body", de: "Nur wenn der CISO auch Mitglied der Geschäftsleitung ist", nl: "Alleen als de CISO ook lid is van het leidinggevend orgaan", fr: "Uniquement si le CISO est également membre de l'organe de direction", it: "Solo se il CISO è anche membro dell'organo di gestione", es: "Solo si el CISO también es miembro del órgano de dirección", pl: "Tylko jeśli CISO jest również członkiem organu zarządzającego", cs: "Pouze pokud je CISO zároveň členem řídicího orgánu", pt: "Apenas se o CISO for também membro do órgão de administração", ro: "Doar dacă CISO este și membru al organului de conducere" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The training duty is personal and non-delegable. You cannot send your CISO, your lawyer, or your assistant to attend on your behalf.",
        de: "Die Schulungspflicht ist persönlich und nicht delegierbar. Sie können nicht Ihren CISO, Ihren Anwalt oder Ihren Assistenten an Ihrer Stelle teilnehmen lassen.",
        nl: "De trainingsplicht is persoonlijk en niet delegeerbaar. U kunt niet uw CISO, uw advocaat of uw assistent namens u laten deelnemen.",
        fr: "L'obligation de formation est personnelle et non délégable. Vous ne pouvez pas envoyer votre CISO, votre avocat ou votre assistant assister à votre place.",
        it: "L'obbligo di formazione è personale e non delegabile. Non potete inviare il vostro CISO, il vostro avvocato o il vostro assistente a partecipare al vostro posto.",
        es: "El deber de formación es personal e indelegable. No puede enviar a su CISO, a su abogado ni a su asistente a asistir en su nombre.",
        pl: "Obowiązek szkolenia jest osobisty i nie podlega delegowaniu. Nie mogą Państwo wysłać swojego CISO, prawnika ani asystenta, aby uczestniczyli w Państwa imieniu.",
        cs: "Povinnost školení je osobní a nedelegovatelná. Nemůžete místo sebe vyslat svého CISO, svého právníka ani svého asistenta.",
        pt: "O dever de formação é pessoal e indelegável. Não pode enviar o seu CISO, o seu advogado ou o seu assistente para assistir em seu nome.",
        ro: "Obligația de formare este personală și nedelegabilă. Nu vă puteți trimite CISO, avocatul sau asistentul să participe în numele dumneavoastră.",
      },
    },
    {
      id: "1.6.3",
      question: {
        en: "What is the minimum training frequency in Germany?",
        de: "Was ist die Mindesthäufigkeit der Schulung in Deutschland?",
        nl: "Wat is de minimale trainingsfrequentie in Duitsland?",
        fr: "Quelle est la fréquence minimale de formation en Allemagne ?",
        it: "Qual è la frequenza minima di formazione in Germania?",
        es: "¿Cuál es la frecuencia mínima de formación en Alemania?",
        pl: "Jaka jest minimalna częstotliwość szkoleń w Niemczech?",
        cs: "Jaká je minimální četnost školení v Německu?",
        pt: "Qual é a frequência mínima de formação na Alemanha?",
        ro: "Care este frecvența minimă de formare în Germania?",
      },
      options: [
        { en: "Every year, mandatory", de: "Jedes Jahr, verpflichtend", nl: "Elk jaar, verplicht", fr: "Chaque année, obligatoire", it: "Ogni anno, obbligatoria", es: "Cada año, obligatoria", pl: "Co roku, obowiązkowo", cs: "Každý rok, povinně", pt: "Todos os anos, obrigatória", ro: "În fiecare an, obligatoriu" },
        { en: "Every three years at minimum, with annual recommended by the BSI", de: "Mindestens alle drei Jahre, wobei das BSI eine jährliche Schulung empfiehlt", nl: "Minimaal elke drie jaar, waarbij het BSI jaarlijks aanbeveelt", fr: "Tous les trois ans au minimum, le BSI recommandant une formation annuelle", it: "Almeno ogni tre anni, con cadenza annuale raccomandata dal BSI", es: "Cada tres años como mínimo, con periodicidad anual recomendada por el BSI", pl: "Co najmniej raz na trzy lata, przy czym BSI zaleca coroczne", cs: "Minimálně každé tři roky, přičemž BSI doporučuje ročně", pt: "No mínimo de três em três anos, sendo a frequência anual recomendada pelo BSI", ro: "Cel puțin o dată la trei ani, frecvența anuală fiind recomandată de BSI" },
        { en: "Every five years", de: "Alle fünf Jahre", nl: "Elke vijf jaar", fr: "Tous les cinq ans", it: "Ogni cinque anni", es: "Cada cinco años", pl: "Co pięć lat", cs: "Každých pět let", pt: "De cinco em cinco anos", ro: "O dată la cinci ani" },
        { en: "Once, when you first take office", de: "Einmalig bei Amtsantritt", nl: "Eenmalig bij aantreden", fr: "Une seule fois, lors de votre entrée en fonction", it: "Una sola volta, all'assunzione dell'incarico", es: "Una sola vez, al asumir el cargo", pl: "Jednorazowo, przy objęciu stanowiska", cs: "Jednou, při nástupu do funkce", pt: "Uma vez, ao assumir o cargo pela primeira vez", ro: "O singură dată, la preluarea inițială a funcției" },
      ],
      correctIndex: 1,
      explanation: {
        en: "In Germany, the floor is every three years; the BSI recommends annual in practice.",
        de: "In Deutschland liegt das Minimum bei drei Jahren; das BSI empfiehlt in der Praxis eine jährliche Schulung.",
        nl: "In Duitsland is het minimum elke drie jaar; het BSI beveelt in de praktijk jaarlijks aan.",
        fr: "En Allemagne, le plancher est de tous les trois ans ; le BSI recommande en pratique une formation annuelle.",
        it: "In Germania, il limite minimo è ogni tre anni; nella pratica il BSI raccomanda una cadenza annuale.",
        es: "En Alemania, el mínimo es cada tres años; en la práctica el BSI recomienda una periodicidad anual.",
        pl: "W Niemczech dolna granica to co trzy lata; w praktyce BSI zaleca coroczne szkolenia.",
        cs: "V Německu je dolní hranicí každé tři roky, BSI však v praxi doporučuje ročně.",
        pt: "Na Alemanha, o mínimo é de três em três anos, embora o BSI recomende na prática a frequência anual.",
        ro: "În Germania, pragul minim este o dată la trei ani, însă BSI recomandă în practică frecvența anuală.",
      },
    },
    {
      id: "1.6.4",
      question: {
        en: "How does the regulator judge the sufficiency of your training?",
        de: "Wie beurteilt die Aufsichtsbehörde die Angemessenheit Ihrer Schulung?",
        nl: "Hoe beoordeelt de toezichthouder de toereikendheid van uw training?",
        fr: "Comment l'autorité de contrôle juge-t-elle la suffisance de votre formation ?",
        it: "Come valuta l'autorità di vigilanza l'adeguatezza della vostra formazione?",
        es: "¿Cómo juzga la autoridad reguladora la suficiencia de su formación?",
        pl: "W jaki sposób organ nadzoru ocenia wystarczalność Państwa szkolenia?",
        cs: "Jak regulační orgán posuzuje dostatečnost vašeho školení?",
        pt: "Como avalia a autoridade reguladora a suficiência da sua formação?",
        ro: "Cum evaluează autoritatea de reglementare suficiența formării dumneavoastră?",
      },
      options: [
        { en: "By verifying you passed a standardised exam", de: "Durch Überprüfung, ob Sie eine standardisierte Prüfung bestanden haben", nl: "Door te verifiëren of u een gestandaardiseerd examen hebt gehaald", fr: "En vérifiant que vous avez réussi un examen standardisé", it: "Verificando che abbiate superato un esame standardizzato", es: "Verificando que ha aprobado un examen estandarizado", pl: "Sprawdzając, czy zdali Państwo standaryzowany egzamin", cs: "Ověřením, že jste složili standardizovanou zkoušku", pt: "Verificando se foi aprovado num exame normalizado", ro: "Verificând dacă ați promovat un examen standardizat" },
        { en: "By checking which certification body issued your certificate", de: "Durch Prüfung, welche Zertifizierungsstelle Ihr Zertifikat ausgestellt hat", nl: "Door te controleren welke certificeringsinstantie uw certificaat heeft uitgegeven", fr: "En vérifiant quel organisme de certification a délivré votre certificat", it: "Verificando quale organismo di certificazione ha rilasciato il vostro certificato", es: "Comprobando qué organismo de certificación emitió su certificado", pl: "Sprawdzając, która jednostka certyfikująca wydała Państwa certyfikat", cs: "Kontrolou, který certifikační orgán vydal váš certifikát", pt: "Verificando qual o organismo de certificação que emitiu o seu certificado", ro: "Verificând ce organism de certificare a emis certificatul dumneavoastră" },
        { en: "Based on content covered, time spent, and documentation retained", de: "Anhand der behandelten Inhalte, der aufgewendeten Zeit und der aufbewahrten Dokumentation", nl: "Op basis van behandelde inhoud, bestede tijd en bewaarde documentatie", fr: "En fonction du contenu abordé, du temps consacré et de la documentation conservée", it: "In base ai contenuti trattati, al tempo impiegato e alla documentazione conservata", es: "En función del contenido tratado, el tiempo dedicado y la documentación conservada", pl: "Na podstawie omówionych treści, poświęconego czasu i zachowanej dokumentacji", cs: "Na základě probrané látky, stráveného času a uchované dokumentace", pt: "Com base no conteúdo abrangido, no tempo dedicado e na documentação conservada", ro: "Pe baza conținutului acoperit, a timpului alocat și a documentației păstrate" },
        { en: "By interviewing your CISO about your knowledge", de: "Durch Befragung Ihres CISO über Ihren Wissensstand", nl: "Door uw CISO te ondervragen over uw kennis", fr: "En interrogeant votre CISO sur vos connaissances", it: "Intervistando il vostro CISO sulle vostre conoscenze", es: "Entrevistando a su CISO sobre sus conocimientos", pl: "Przeprowadzając rozmowę z Państwa CISO na temat Państwa wiedzy", cs: "Pohovorem s vaším CISO o vašich znalostech", pt: "Entrevistando o seu CISO sobre os seus conhecimentos", ro: "Intervievându-vă CISO cu privire la cunoștințele dumneavoastră" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The regulator judges sufficiency based on three things: what was covered, for how long, and how it was documented.",
        de: "Die Aufsichtsbehörde beurteilt die Angemessenheit anhand von drei Kriterien: welche Inhalte behandelt wurden, wie lange die Schulung dauerte und wie sie dokumentiert wurde.",
        nl: "De bevoegde autoriteit beoordeelt de toereikendheid op basis van drie dingen: wat werd behandeld, hoe lang, en hoe het werd gedocumenteerd.",
        fr: "L'autorité de contrôle juge la suffisance sur la base de trois éléments : ce qui a été abordé, pendant combien de temps et comment cela a été documenté.",
        it: "L'autorità di vigilanza valuta l'adeguatezza in base a tre elementi: cosa è stato trattato, per quanto tempo e come è stato documentato.",
        es: "La autoridad reguladora juzga la suficiencia en función de tres elementos: qué se trató, durante cuánto tiempo y cómo se documentó.",
        pl: "Organ nadzoru ocenia wystarczalność na podstawie trzech elementów: co zostało omówione, jak długo i w jaki sposób zostało udokumentowane.",
        cs: "Regulační orgán posuzuje dostatečnost na základě tří věcí: co bylo probráno, jak dlouho a jak to bylo zdokumentováno.",
        pt: "A autoridade reguladora avalia a suficiência com base em três aspetos: o que foi abrangido, durante quanto tempo e como foi documentado.",
        ro: "Autoritatea de reglementare evaluează suficiența pe baza a trei aspecte: ce a fost acoperit, pentru cât timp și cum a fost documentat.",
      },
    },
  ],
});

export default quiz;
