import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.8",
  passingScore: 75,
  questions: [
    {
      id: "1.8.1",
      question: {
        en: "Does the Business Judgment Rule protect a decision not to implement NIS2 measures?",
        de: "Schützt die Business Judgment Rule eine Entscheidung, NIS2-Maßnahmen nicht umzusetzen?",
        nl: "Beschermt de business judgment rule een beslissing om NIS2-maatregelen niet te implementeren?",
        fr: "La Business Judgment Rule protège-t-elle une décision de ne pas mettre en œuvre les mesures NIS2 ?",
        it: "La Business Judgment Rule protegge una decisione di non attuare le misure NIS2?",
        es: "¿Protege la Business Judgment Rule una decisión de no implementar las medidas de NIS2?",
        pl: "Czy Business Judgment Rule chroni decyzję o niewdrażaniu środków NIS2?",
        cs: "Chrání pravidlo podnikatelského úsudku rozhodnutí nezavést opatření NIS2?",
        pt: "A regra do juízo empresarial protege a decisão de não implementar as medidas NIS2?",
        ro: "Regula judecății de afaceri protejează decizia de a nu implementa măsurile NIS2?",
      },
      options: [
        { en: "Yes, if the decision was made in good faith with reasonable information", de: "Ja, wenn die Entscheidung gutgläubig und auf angemessener Informationsgrundlage getroffen wurde", nl: "Ja, als de beslissing te goeder trouw is genomen op basis van redelijke informatie", fr: "Oui, si la décision a été prise de bonne foi sur la base d'informations raisonnables", it: "Sì, se la decisione è stata presa in buona fede sulla base di informazioni ragionevoli", es: "Sí, si la decisión se tomó de buena fe con información razonable", pl: "Tak, jeśli decyzja została podjęta w dobrej wierze na podstawie rozsądnych informacji", cs: "Ano, pokud bylo rozhodnutí učiněno v dobré víře na základě přiměřených informací", pt: "Sim, se a decisão tiver sido tomada de boa-fé com informação razoável", ro: "Da, dacă decizia a fost luată cu bună-credință, pe baza unor informații rezonabile" },
        { en: "Yes, all board decisions are protected by the Business Judgment Rule", de: "Ja, alle Vorstandsentscheidungen werden durch die Business Judgment Rule geschützt", nl: "Ja, alle bestuursbesluiten worden beschermd door de business judgment rule", fr: "Oui, toutes les décisions du conseil sont protégées par la Business Judgment Rule", it: "Sì, tutte le decisioni del consiglio sono protette dalla Business Judgment Rule", es: "Sí, todas las decisiones del consejo están protegidas por la Business Judgment Rule", pl: "Tak, wszystkie decyzje zarządu są chronione przez Business Judgment Rule", cs: "Ano, všechna rozhodnutí orgánu chrání pravidlo podnikatelského úsudku", pt: "Sim, todas as decisões do órgão de administração estão protegidas pela regra do juízo empresarial", ro: "Da, toate deciziile organului de conducere sunt protejate de regula judecății de afaceri" },
        { en: "No, NIS2 creates statutory duties under the duty of legality, which sits above the Business Judgment Rule", de: "Nein, NIS2 begründet gesetzliche Pflichten im Rahmen der Legalitätspflicht, die über der Business Judgment Rule steht", nl: "Nee, NIS2 schept wettelijke verplichtingen op grond van de legaliteitsplicht, die boven de business judgment rule staat", fr: "Non, NIS2 crée des obligations légales au titre du devoir de légalité, qui prime sur la Business Judgment Rule", it: "No, NIS2 crea obblighi di legge ai sensi del dovere di legalità, che prevale sulla Business Judgment Rule", es: "No, NIS2 crea deberes legales en virtud del deber de legalidad, que prevalece sobre la Business Judgment Rule", pl: "Nie, NIS2 tworzy ustawowe obowiązki w ramach obowiązku legalności, który stoi ponad Business Judgment Rule", cs: "Ne, NIS2 vytváří zákonné povinnosti v rámci povinnosti dodržovat právo, která stojí nad pravidlem podnikatelského úsudku", pt: "Não, a NIS2 cria deveres legais ao abrigo do dever de legalidade, que se sobrepõe à regra do juízo empresarial", ro: "Nu, NIS2 creează obligații legale în temeiul obligației de legalitate, care se situează deasupra regulii judecății de afaceri" },
        { en: "Only if the company documents why it chose not to implement", de: "Nur wenn das Unternehmen dokumentiert, warum es sich gegen die Umsetzung entschieden hat", nl: "Alleen als de vennootschap documenteert waarom zij ervoor heeft gekozen niet te implementeren", fr: "Uniquement si l'entreprise documente pourquoi elle a choisi de ne pas mettre en œuvre", it: "Solo se l'impresa documenta perché ha scelto di non attuare", es: "Solo si la empresa documenta por qué optó por no implementar", pl: "Tylko jeśli firma udokumentuje, dlaczego zdecydowała się nie wdrażać", cs: "Pouze pokud společnost zdokumentuje, proč se rozhodla nezavádět", pt: "Apenas se a empresa documentar por que razão optou por não implementar", ro: "Doar dacă compania documentează de ce a ales să nu implementeze" },
      ],
      correctIndex: 2,
      explanation: {
        en: "NIS2 Articles 20 and 21 create statutory duties. The duty of legality means no judgment is permitted about whether to follow a legal duty.",
        de: "Artikel 20 und 21 NIS2 begründen gesetzliche Pflichten. Die Legalitätspflicht bedeutet, dass kein Ermessensspielraum besteht, ob eine gesetzliche Pflicht befolgt wird.",
        nl: "NIS2 artikelen 20 en 21 scheppen wettelijke verplichtingen. De legaliteitsplicht betekent dat er geen beoordelingsruimte bestaat over de vraag of een wettelijke verplichting moet worden nageleefd.",
        fr: "Les articles 20 et 21 de NIS2 créent des obligations légales. Le devoir de légalité signifie qu'aucune appréciation n'est permise quant à savoir s'il faut respecter une obligation légale.",
        it: "Gli articoli 20 e 21 di NIS2 creano obblighi di legge. Il dovere di legalità significa che non è ammessa alcuna valutazione discrezionale sull'opportunità di rispettare un obbligo di legge.",
        es: "Los artículos 20 y 21 de NIS2 crean deberes legales. El deber de legalidad significa que no se permite ningún juicio sobre si se debe cumplir un deber legal.",
        pl: "Artykuły 20 i 21 NIS2 tworzą ustawowe obowiązki. Obowiązek legalności oznacza, że nie jest dopuszczalna żadna ocena tego, czy należy wykonać obowiązek prawny.",
        cs: "Články 20 a 21 NIS2 vytvářejí zákonné povinnosti. Povinnost dodržovat právo znamená, že o tom, zda zákonnou povinnost splnit, není dovolen žádný úsudek.",
        pt: "Os artigos 20 e 21 da NIS2 criam deveres legais. O dever de legalidade significa que não é permitido qualquer juízo sobre se deve ou não cumprir um dever legal.",
        ro: "Articolele 20 și 21 din NIS2 creează obligații legale. Obligația de legalitate înseamnă că nu este permisă nicio judecată cu privire la respectarea unei obligații legale.",
      },
    },
    {
      id: "1.8.2",
      question: {
        en: "What does the Business Judgment Rule protect, according to the lesson?",
        de: "Was schützt die Business Judgment Rule laut dieser Lektion?",
        nl: "Wat beschermt de business judgment rule volgens de les?",
        fr: "Que protège la Business Judgment Rule, selon la leçon ?",
        it: "Cosa protegge la Business Judgment Rule, secondo la lezione?",
        es: "¿Qué protege la Business Judgment Rule, según la lección?",
        pl: "Co chroni Business Judgment Rule, według lekcji?",
        cs: "Co podle lekce pravidlo podnikatelského úsudku chrání?",
        pt: "O que protege a regra do juízo empresarial, segundo a lição?",
        ro: "Ce protejează regula judecății de afaceri, potrivit lecției?",
      },
      options: [
        { en: "Decisions about whether to comply with NIS2", de: "Entscheidungen darüber, ob NIS2 eingehalten wird", nl: "Beslissingen over de vraag of NIS2 moet worden nageleefd", fr: "Les décisions quant à savoir s'il faut se conformer à NIS2", it: "Le decisioni sull'opportunità di conformarsi a NIS2", es: "Las decisiones sobre si cumplir con NIS2", pl: "Decyzje o tym, czy przestrzegać NIS2", cs: "Rozhodnutí o tom, zda NIS2 dodržovat", pt: "Decisões sobre se deve ou não cumprir a NIS2", ro: "Decizii privind dacă să respectați sau nu NIS2" },
        { en: "Decisions about how to implement - which vendor, standard, or budget split", de: "Entscheidungen über das Wie der Umsetzung -- welcher Anbieter, welcher Standard, welche Budgetaufteilung", nl: "Beslissingen over hoe te implementeren — welke leverancier, welke norm of welke budgetverdeling", fr: "Les décisions sur la manière de mettre en œuvre : quel fournisseur, quelle norme ou quelle répartition budgétaire", it: "Le decisioni su come attuare: quale fornitore, quale standard o quale ripartizione del budget", es: "Las decisiones sobre cómo implementar: qué proveedor, qué norma o qué reparto del presupuesto", pl: "Decyzje o tym, jak wdrażać: który dostawca, który standard lub jaki podział budżetu", cs: "Rozhodnutí o tom, jak zavádět: který dodavatel, norma nebo rozdělení rozpočtu", pt: "Decisões sobre como implementar: que fornecedor, norma ou repartição orçamental", ro: "Decizii privind modul de implementare: ce furnizor, ce standard sau ce repartizare a bugetului" },
        { en: "All decisions made during board meetings", de: "Alle Entscheidungen, die in Vorstandssitzungen getroffen werden", nl: "Alle beslissingen die tijdens bestuursvergaderingen worden genomen", fr: "Toutes les décisions prises lors des réunions du conseil", it: "Tutte le decisioni prese durante le riunioni del consiglio", es: "Todas las decisiones tomadas durante las reuniones del consejo", pl: "Wszystkie decyzje podejmowane podczas posiedzeń zarządu", cs: "Všechna rozhodnutí přijatá na jednáních orgánu", pt: "Todas as decisões tomadas nas reuniões do órgão de administração", ro: "Toate deciziile luate în ședințele organului de conducere" },
        { en: "Decisions to delay compliance until the next fiscal year", de: "Entscheidungen, die Compliance auf das nächste Geschäftsjahr zu verschieben", nl: "Beslissingen om naleving uit te stellen tot het volgende boekjaar", fr: "Les décisions de reporter la conformité à l'exercice suivant", it: "Le decisioni di rinviare la conformità all'esercizio successivo", es: "Las decisiones de aplazar el cumplimiento hasta el ejercicio siguiente", pl: "Decyzje o odłożeniu zgodności do następnego roku obrotowego", cs: "Rozhodnutí odložit dodržování předpisů do příštího účetního roku", pt: "Decisões de adiar a conformidade para o exercício seguinte", ro: "Decizii de a amâna conformitatea până în exercițiul financiar următor" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The rule may protect your choice of how to implement - which vendor, which standard, which budget split - but it cannot protect a decision on whether to implement.",
        de: "Die Regel kann Ihre Wahl des Wie der Umsetzung schützen -- welcher Anbieter, welcher Standard, welche Budgetaufteilung -- aber sie kann keine Entscheidung über das Ob der Umsetzung schützen.",
        nl: "De regel kan uw keuze over hoe te implementeren beschermen — welke leverancier, welke norm, welke budgetverdeling — maar zij kan een beslissing over de vraag óf te implementeren niet beschermen.",
        fr: "La règle peut protéger votre choix sur la manière de mettre en œuvre : quel fournisseur, quelle norme, quelle répartition budgétaire, mais elle ne peut pas protéger une décision quant à savoir s'il faut mettre en œuvre.",
        it: "La regola può proteggere la vostra scelta su come attuare: quale fornitore, quale standard, quale ripartizione del budget, ma non può proteggere una decisione sull'opportunità di attuare.",
        es: "La regla puede proteger su elección sobre cómo implementar: qué proveedor, qué norma, qué reparto del presupuesto, pero no puede proteger una decisión sobre si implementar.",
        pl: "Reguła może chronić Państwa wybór dotyczący sposobu wdrażania: który dostawca, który standard, jaki podział budżetu, ale nie może chronić decyzji o tym, czy wdrażać.",
        cs: "Pravidlo může chránit vaši volbu, jak zavádět: kterého dodavatele, kterou normu, jaké rozdělení rozpočtu. Nemůže však chránit rozhodnutí o tom, zda vůbec zavádět.",
        pt: "A regra pode proteger a sua escolha sobre como implementar: que fornecedor, que norma, que repartição orçamental. Mas não pode proteger uma decisão sobre se deve ou não implementar.",
        ro: "Regula vă poate proteja alegerea privind modul de implementare: ce furnizor, ce standard, ce repartizare a bugetului. Dar nu poate proteja o decizie privind dacă să implementați sau nu.",
      },
    },
    {
      id: "1.8.3",
      question: {
        en: "What is the 'duty of legality' described in this lesson?",
        de: "Was ist die in dieser Lektion beschriebene 'Legalitätspflicht'?",
        nl: "Wat is de in deze les beschreven 'legaliteitsplicht'?",
        fr: "Qu'est-ce que le 'devoir de légalité' décrit dans cette leçon ?",
        it: "Che cos'è il 'dovere di legalità' descritto in questa lezione?",
        es: "¿Qué es el 'deber de legalidad' descrito en esta lección?",
        pl: "Czym jest 'obowiązek legalności' opisany w tej lekcji?",
        cs: "Co je 'povinnost dodržovat právo' popsaná v této lekci?",
        pt: "O que é o 'dever de legalidade' descrito nesta lição?",
        ro: "Ce este 'obligația de legalitate' descrisă în această lecție?",
      },
      options: [
        { en: "The duty to consult a lawyer before making any business decision", de: "Die Pflicht, vor jeder geschäftlichen Entscheidung einen Anwalt zu konsultieren", nl: "De plicht om een advocaat te raadplegen voordat een zakelijke beslissing wordt genomen", fr: "L'obligation de consulter un avocat avant de prendre toute décision commerciale", it: "L'obbligo di consultare un avvocato prima di prendere qualsiasi decisione aziendale", es: "El deber de consultar a un abogado antes de tomar cualquier decisión empresarial", pl: "Obowiązek konsultacji z prawnikiem przed podjęciem jakiejkolwiek decyzji biznesowej", cs: "Povinnost poradit se s právníkem před každým podnikatelským rozhodnutím", pt: "O dever de consultar um advogado antes de tomar qualquer decisão empresarial", ro: "Obligația de a consulta un avocat înainte de a lua orice decizie de afaceri" },
        { en: "The specific duty of a director to comply with applicable law, which sits above the Business Judgment Rule", de: "Die spezifische Pflicht eines Geschäftsleiters, geltendes Recht einzuhalten, die über der Business Judgment Rule steht", nl: "De specifieke plicht van een bestuurder om het toepasselijke recht na te leven, die boven de business judgment rule staat", fr: "L'obligation spécifique d'un dirigeant de respecter le droit applicable, qui prime sur la Business Judgment Rule", it: "L'obbligo specifico di un amministratore di rispettare il diritto applicabile, che prevale sulla Business Judgment Rule", es: "El deber específico de un administrador de cumplir el derecho aplicable, que prevalece sobre la Business Judgment Rule", pl: "Szczególny obowiązek członka zarządu przestrzegania obowiązującego prawa, który stoi ponad Business Judgment Rule", cs: "Konkrétní povinnost člena orgánu dodržovat platné právo, která stojí nad pravidlem podnikatelského úsudku", pt: "O dever específico de um administrador de cumprir a lei aplicável, que se sobrepõe à regra do juízo empresarial", ro: "Obligația specifică a unui administrator de a respecta legea aplicabilă, care se situează deasupra regulii judecății de afaceri" },
        { en: "The obligation to file annual compliance reports with the regulator", de: "Die Pflicht, jährliche Compliance-Berichte bei der Aufsichtsbehörde einzureichen", nl: "De verplichting om jaarlijkse nalevingsrapporten in te dienen bij de toezichthouder", fr: "L'obligation de déposer des rapports de conformité annuels auprès de l'autorité de contrôle", it: "L'obbligo di presentare relazioni annuali di conformità all'autorità di vigilanza", es: "La obligación de presentar informes anuales de cumplimiento a la autoridad reguladora", pl: "Obowiązek składania rocznych raportów zgodności organowi nadzoru", cs: "Povinnost předkládat regulačnímu orgánu roční zprávy o dodržování předpisů", pt: "A obrigação de apresentar relatórios anuais de conformidade à autoridade reguladora", ro: "Obligația de a depune rapoarte anuale de conformitate la autoritatea de reglementare" },
        { en: "The requirement to maintain legal counsel on retainer", de: "Die Anforderung, einen Rechtsberater dauerhaft unter Vertrag zu haben", nl: "De vereiste om een juridisch adviseur op permanente basis beschikbaar te hebben", fr: "L'exigence de disposer d'un conseiller juridique sous contrat permanent", it: "Il requisito di mantenere un consulente legale a contratto permanente", es: "El requisito de mantener a un asesor jurídico bajo contrato permanente", pl: "Wymóg utrzymywania stałego doradcy prawnego", cs: "Požadavek mít trvale zajištěné právní zastoupení", pt: "A exigência de manter um advogado em regime de avença", ro: "Cerința de a menține un consilier juridic permanent" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The duty of legality is the specific duty of a director to comply with applicable law. No business judgment is permitted about whether to follow a legal duty.",
        de: "Die Legalitätspflicht ist die spezifische Pflicht eines Geschäftsleiters, geltendes Recht einzuhalten. Bei gesetzlichen Pflichten besteht kein unternehmerischer Ermessensspielraum über das Ob der Befolgung.",
        nl: "De legaliteitsplicht is de specifieke plicht van een bestuurder om het toepasselijke recht na te leven. Er bestaat geen bedrijfsmatige beoordelingsruimte over de vraag of een wettelijke verplichting moet worden opgevolgd.",
        fr: "Le devoir de légalité est l'obligation spécifique d'un dirigeant de respecter le droit applicable. Aucune appréciation commerciale n'est permise quant à savoir s'il faut respecter une obligation légale.",
        it: "Il dovere di legalità è l'obbligo specifico di un amministratore di rispettare il diritto applicabile. Non è ammessa alcuna valutazione discrezionale sull'opportunità di rispettare un obbligo di legge.",
        es: "El deber de legalidad es el deber específico de un administrador de cumplir el derecho aplicable. No se permite ningún juicio empresarial sobre si se debe cumplir un deber legal.",
        pl: "Obowiązek legalności to szczególny obowiązek członka zarządu przestrzegania obowiązującego prawa. Nie jest dopuszczalna żadna ocena biznesowa tego, czy należy wykonać obowiązek prawny.",
        cs: "Povinnost dodržovat právo je konkrétní povinnost člena orgánu dodržovat platné právo. O tom, zda zákonnou povinnost splnit, není dovolen žádný podnikatelský úsudek.",
        pt: "O dever de legalidade é o dever específico de um administrador de cumprir a lei aplicável. Não é permitido qualquer juízo empresarial sobre se deve ou não cumprir um dever legal.",
        ro: "Obligația de legalitate este obligația specifică a unui administrator de a respecta legea aplicabilă. Nu este permisă nicio judecată de afaceri cu privire la respectarea unei obligații legale.",
      },
    },
  ],
});

export default quiz;
