import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.1",
  passingScore: 75,
  questions: [
    {
      id: "2.1.1",
      question: {
        en: "What two factors does Article 21(1) use to measure a company's cybersecurity exposure?",
        de: "Welche zwei Faktoren verwendet Artikel 21 Absatz 1 zur Bewertung der Cybersicherheitsexposition eines Unternehmens?",
        nl: "Welke twee factoren gebruikt Artikel 21(1) om de cyberbeveiligingsblootstelling van een bedrijf te meten?",
        fr: "Quels sont les deux facteurs que l'article 21(1) utilise pour mesurer l'exposition d'une entreprise en matière de cybersécurité ?",
        it: "Quali due fattori utilizza l'articolo 21(1) per misurare l'esposizione di un'impresa in materia di cybersicurezza?",
        es: "¿Qué dos factores utiliza el artículo 21(1) para medir la exposición de una empresa en materia de ciberseguridad?",
        pl: "Jakich dwóch czynników używa artykuł 21(1) do pomiaru ekspozycji firmy w zakresie cyberbezpieczeństwa?",
        cs: "Jaké dva faktory používá článek 21(1) k měření vystavení společnosti kybernetickému riziku?",
        pt: "Que dois fatores utiliza o artigo 21(1) para medir a exposição de uma empresa à cibersegurança?",
        ro: "Ce doi factori utilizează articolul 21(1) pentru a măsura expunerea unei companii la riscul cibernetic?",
      },
      options: [
        { en: "Budget and headcount", de: "Budget und Mitarbeiterzahl", nl: "Budget en personeelsomvang", fr: "Le budget et l'effectif", it: "Il budget e il numero di dipendenti", es: "El presupuesto y la plantilla", pl: "Budżet i liczbę pracowników", cs: "Rozpočet a počet zaměstnanců", pt: "Orçamento e número de trabalhadores", ro: "Bugetul și numărul de angajați" },
        { en: "Likelihood and impact", de: "Eintrittswahrscheinlichkeit und Auswirkung", nl: "Waarschijnlijkheid en impact", fr: "La probabilité et l'impact", it: "La probabilità e l'impatto", es: "La probabilidad y el impacto", pl: "Prawdopodobieństwo i skutek", cs: "Pravděpodobnost a dopad", pt: "Probabilidade e impacto", ro: "Probabilitate și impact" },
        { en: "Revenue and employee count", de: "Umsatz und Mitarbeiterzahl", nl: "Omzet en aantal medewerkers", fr: "Le chiffre d'affaires et le nombre d'employés", it: "Il fatturato e il numero di dipendenti", es: "La facturación y el número de empleados", pl: "Przychody i liczbę pracowników", cs: "Tržby a počet zaměstnanců", pt: "Receita e número de trabalhadores", ro: "Venitul și numărul de angajați" },
        { en: "Compliance score and audit grade", de: "Compliance-Bewertung und Audit-Ergebnis", nl: "Compliance-score en auditbeoordeling", fr: "Le score de conformité et la note d'audit", it: "Il punteggio di conformità e il giudizio di audit", es: "La puntuación de cumplimiento y la calificación de la auditoría", pl: "Wynik zgodności i ocenę audytu", cs: "Skóre dodržování předpisů a hodnocení z auditu", pt: "Pontuação de conformidade e classificação de auditoria", ro: "Scorul de conformitate și nota de audit" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 21(1) requires 'appropriate and proportionate' measures based on how likely a bad event is and how bad it would be - likelihood and impact.",
        de: "Artikel 21 Absatz 1 verlangt 'angemessene und verhältnismäßige' Maßnahmen basierend auf der Wahrscheinlichkeit eines Vorfalls und dessen Schwere - Eintrittswahrscheinlichkeit und Auswirkung.",
        nl: "Artikel 21(1) vereist 'passende en evenredige' maatregelen op basis van hoe waarschijnlijk een incident is en hoe ernstig de gevolgen zouden zijn - waarschijnlijkheid en impact.",
        fr: "L'article 21(1) exige des mesures 'appropriées et proportionnées' fondées sur la probabilité d'un événement néfaste et sur sa gravité : probabilité et impact.",
        it: "L'articolo 21(1) richiede misure 'appropriate e proporzionate' basate sulla probabilità di un evento dannoso e sulla sua gravità: probabilità e impatto.",
        es: "El artículo 21(1) exige medidas 'adecuadas y proporcionadas' basadas en la probabilidad de un suceso adverso y en su gravedad: probabilidad e impacto.",
        pl: "Artykuł 21(1) wymaga środków 'odpowiednich i proporcjonalnych' opartych na tym, jak prawdopodobne jest niekorzystne zdarzenie i jak poważne byłyby jego skutki: prawdopodobieństwo i skutek.",
        cs: "Článek 21(1) vyžaduje 'vhodná a přiměřená' opatření podle toho, jak pravděpodobná je nepříznivá událost a jak by byla závažná: pravděpodobnost a dopad.",
        pt: "O artigo 21(1) exige medidas 'adequadas e proporcionadas' com base na probabilidade de um acontecimento adverso e na sua gravidade: probabilidade e impacto.",
        ro: "Articolul 21(1) impune măsuri 'adecvate și proporționale' în funcție de cât de probabil este un eveniment nefavorabil și cât de grav ar fi: probabilitate și impact.",
      },
    },
    {
      id: "2.1.2",
      question: {
        en: "Which part of the risk matrix should the management body focus on first?",
        de: "Auf welchen Teil der Risikomatrix sollte die Geschäftsleitung zuerst fokussieren?",
        nl: "Op welk deel van de risicomatrix moet het bestuur zich het eerst richten?",
        fr: "Sur quelle partie de la matrice des risques l'organe de direction doit-il se concentrer en premier ?",
        it: "Su quale parte della matrice dei rischi dovrebbe concentrarsi per prima l'organo di gestione?",
        es: "¿En qué parte de la matriz de riesgos debe centrarse primero el órgano de dirección?",
        pl: "Na której części macierzy ryzyka organ zarządzający powinien skupić się w pierwszej kolejności?",
        cs: "Na kterou část matice rizik by se měl řídicí orgán zaměřit jako první?",
        pt: "Em que parte da matriz de risco se deve o órgão de administração concentrar primeiro?",
        ro: "Pe ce parte a matricei de risc trebuie să se concentreze mai întâi organul de conducere?",
      },
      options: [
        { en: "The bottom-left corner (low likelihood, low impact)", de: "Die untere linke Ecke (geringe Wahrscheinlichkeit, geringe Auswirkung)", nl: "De linkerbenedenhoek (lage waarschijnlijkheid, lage impact)", fr: "Le coin inférieur gauche (faible probabilité, faible impact)", it: "L'angolo in basso a sinistra (bassa probabilità, basso impatto)", es: "La esquina inferior izquierda (baja probabilidad, bajo impacto)", pl: "Lewy dolny róg (niskie prawdopodobieństwo, niski skutek)", cs: "Levý dolní roh (nízká pravděpodobnost, nízký dopad)", pt: "O canto inferior esquerdo (baixa probabilidade, baixo impacto)", ro: "Colțul din stânga jos (probabilitate scăzută, impact scăzut)" },
        { en: "The top-right corner (high likelihood, high impact)", de: "Die obere rechte Ecke (hohe Wahrscheinlichkeit, hohe Auswirkung)", nl: "De rechterbovenhoek (hoge waarschijnlijkheid, hoge impact)", fr: "Le coin supérieur droit (forte probabilité, fort impact)", it: "L'angolo in alto a destra (alta probabilità, alto impatto)", es: "La esquina superior derecha (alta probabilidad, alto impacto)", pl: "Prawy górny róg (wysokie prawdopodobieństwo, wysoki skutek)", cs: "Pravý horní roh (vysoká pravděpodobnost, vysoký dopad)", pt: "O canto superior direito (alta probabilidade, alto impacto)", ro: "Colțul din dreapta sus (probabilitate ridicată, impact ridicat)" },
        { en: "The centre of the matrix", de: "Die Mitte der Matrix", nl: "Het midden van de matrix", fr: "Le centre de la matrice", it: "Il centro della matrice", es: "El centro de la matriz", pl: "Środek macierzy", cs: "Střed matice", pt: "O centro da matriz", ro: "Centrul matricei" },
        { en: "The bottom-right corner (low likelihood, high impact)", de: "Die untere rechte Ecke (geringe Wahrscheinlichkeit, hohe Auswirkung)", nl: "De rechterbenedenhoek (lage waarschijnlijkheid, hoge impact)", fr: "Le coin inférieur droit (faible probabilité, fort impact)", it: "L'angolo in basso a destra (bassa probabilità, alto impatto)", es: "La esquina inferior derecha (baja probabilidad, alto impacto)", pl: "Prawy dolny róg (niskie prawdopodobieństwo, wysoki skutek)", cs: "Pravý dolní roh (nízká pravděpodobnost, vysoký dopad)", pt: "O canto inferior direito (baixa probabilidade, alto impacto)", ro: "Colțul din dreapta jos (probabilitate scăzută, impact ridicat)" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The top-right corner - where 'very likely' meets 'very serious' - is where the company faces the most exposure and where the management body's job begins.",
        de: "Die obere rechte Ecke - wo 'sehr wahrscheinlich' auf 'sehr schwerwiegend' trifft - ist der Bereich mit der größten Exposition und dort beginnt die Aufgabe der Geschäftsleitung.",
        nl: "De rechterbovenhoek - waar 'zeer waarschijnlijk' en 'zeer ernstig' samenkomen - is waar de blootstelling het grootst is en waar de taak van het bestuur begint.",
        fr: "Le coin supérieur droit, là où 'très probable' rencontre 'très grave', est la zone où l'entreprise est la plus exposée et où commence la mission de l'organe de direction.",
        it: "L'angolo in alto a destra, dove 'molto probabile' incontra 'molto grave', è il punto in cui l'impresa è maggiormente esposta e in cui inizia il compito dell'organo di gestione.",
        es: "La esquina superior derecha, donde 'muy probable' se encuentra con 'muy grave', es donde la empresa está más expuesta y donde comienza la labor del órgano de dirección.",
        pl: "Prawy górny róg, gdzie 'bardzo prawdopodobne' spotyka się z 'bardzo poważne', to obszar największej ekspozycji firmy i tam zaczyna się zadanie organu zarządzającego.",
        cs: "Pravý horní roh, kde se 'velmi pravděpodobné' setkává s 'velmi závažným', je místo, kde je společnost nejvíce vystavena riziku a kde začíná úkol řídicího orgánu.",
        pt: "O canto superior direito, onde 'muito provável' se cruza com 'muito grave', é onde a empresa enfrenta a maior exposição e onde começa o trabalho do órgão de administração.",
        ro: "Colțul din dreapta sus, unde 'foarte probabil' se întâlnește cu 'foarte grav', este locul în care compania se confruntă cu cea mai mare expunere și unde începe sarcina organului de conducere.",
      },
    },
    {
      id: "2.1.3",
      question: {
        en: "What is the risk register's role in the budget conversation?",
        de: "Welche Rolle spielt das Risikoregister in der Budgetdiskussion?",
        nl: "Welke rol speelt het risicoregister in het budgetgesprek?",
        fr: "Quel est le rôle du registre des risques dans la discussion budgétaire ?",
        it: "Qual è il ruolo del registro dei rischi nella discussione sul budget?",
        es: "¿Cuál es el papel del registro de riesgos en la conversación sobre el presupuesto?",
        pl: "Jaką rolę odgrywa rejestr ryzyka w rozmowie o budżecie?",
        cs: "Jakou roli hraje registr rizik v jednání o rozpočtu?",
        pt: "Qual é o papel do registo de riscos na conversa sobre o orçamento?",
        ro: "Care este rolul registrului de riscuri în discuția despre buget?",
      },
      options: [
        { en: "It replaces the need for a CFO's approval", de: "Es ersetzt die Notwendigkeit einer Genehmigung durch den CFO", nl: "Het vervangt de behoefte aan goedkeuring van de CFO", fr: "Il remplace la nécessité d'une approbation du CFO", it: "Sostituisce la necessità dell'approvazione del CFO", es: "Sustituye la necesidad de la aprobación del CFO", pl: "Zastępuje konieczność zatwierdzenia przez CFO", cs: "Nahrazuje potřebu schválení finančním ředitelem", pt: "Substitui a necessidade de aprovação do diretor financeiro", ro: "Înlocuiește necesitatea aprobării de către directorul financiar" },
        { en: "It turns the budget argument from opinion into evidence", de: "Es verwandelt die Budgetdiskussion von Meinung in Evidenz", nl: "Het verandert het budgetdebat van mening in bewijs", fr: "Il transforme l'argument budgétaire d'une opinion en une preuve", it: "Trasforma l'argomentazione sul budget da opinione in prova", es: "Convierte el argumento presupuestario de una opinión en una prueba", pl: "Zamienia argument budżetowy z opinii w dowód", cs: "Mění argument o rozpočtu z názoru na důkaz", pt: "Transforma o argumento orçamental de opinião em prova", ro: "Transformă argumentul bugetar din opinie în dovadă" },
        { en: "It sets the exact euro amount to spend on security", de: "Es legt den genauen Euro-Betrag für Sicherheitsausgaben fest", nl: "Het stelt het exacte bedrag vast dat aan beveiliging besteed moet worden", fr: "Il fixe le montant exact en euros à consacrer à la sécurité", it: "Stabilisce l'importo esatto in euro da destinare alla sicurezza", es: "Fija la cantidad exacta en euros que se debe gastar en seguridad", pl: "Ustala dokładną kwotę w euro do wydania na bezpieczeństwo", cs: "Stanoví přesnou částku v eurech, kterou utratit na bezpečnost", pt: "Define o montante exato em euros a gastar em segurança", ro: "Stabilește suma exactă în euro de cheltuit pentru securitate" },
        { en: "It is only used after the budget is already approved", de: "Es wird erst nach der Budgetfreigabe verwendet", nl: "Het wordt pas gebruikt nadat het budget al is goedgekeurd", fr: "Il n'est utilisé qu'une fois le budget déjà approuvé", it: "Viene utilizzato solo dopo che il budget è già stato approvato", es: "Solo se utiliza después de que el presupuesto ya esté aprobado", pl: "Jest używany dopiero po zatwierdzeniu budżetu", cs: "Používá se až poté, co je rozpočet schválen", pt: "É utilizado apenas depois de o orçamento já estar aprovado", ro: "Este utilizat doar după ce bugetul a fost deja aprobat" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The risk register is the document that turns the budget debate from opinion into a decision backed by evidence - scored risks with treatment plans.",
        de: "Das Risikoregister ist das Dokument, das die Budgetdebatte von einer Meinungsdiskussion in eine evidenzbasierte Entscheidung verwandelt - bewertete Risiken mit Behandlungsplänen.",
        nl: "Het risicoregister is het document dat het budgetdebat omzet van mening naar een beslissing onderbouwd door bewijs - beoordeelde risico's met behandelplannen.",
        fr: "Le registre des risques est le document qui transforme le débat budgétaire d'une opinion en une décision étayée par des preuves : des risques notés assortis de plans de traitement.",
        it: "Il registro dei rischi è il documento che trasforma il dibattito sul budget da opinione in una decisione supportata da prove: rischi valutati con relativi piani di trattamento.",
        es: "El registro de riesgos es el documento que convierte el debate presupuestario de una opinión en una decisión respaldada por pruebas: riesgos puntuados con planes de tratamiento.",
        pl: "Rejestr ryzyka to dokument, który zamienia debatę budżetową z opinii w decyzję popartą dowodami: ocenione ryzyka wraz z planami postępowania.",
        cs: "Registr rizik je dokument, který mění rozpravu o rozpočtu z názoru na rozhodnutí podložené důkazy: ohodnocená rizika s plány ošetření.",
        pt: "O registo de riscos é o documento que transforma o debate orçamental de opinião numa decisão fundamentada em provas: riscos pontuados com planos de tratamento.",
        ro: "Registrul de riscuri este documentul care transformă dezbaterea bugetară din opinie într-o decizie susținută de dovezi: riscuri evaluate cu planuri de tratare.",
      },
    },
    {
      id: "2.1.4",
      question: {
        en: "Why does an uninformed sign-off on cybersecurity measures fail to protect the CEO under Article 20(1)?",
        de: "Warum schützt eine uninformierte Freigabe von Cybersicherheitsmaßnahmen den CEO nicht gemäß Artikel 20 Absatz 1?",
        nl: "Waarom biedt een ongeïnformeerde goedkeuring van cyberbeveiligingsmaatregelen de CEO geen bescherming onder Artikel 20(1)?",
        fr: "Pourquoi une approbation non éclairée des mesures de cybersécurité ne protège-t-elle pas le dirigeant au titre de l'article 20(1) ?",
        it: "Perché un'approvazione non informata delle misure di cybersicurezza non protegge l'amministratore delegato ai sensi dell'articolo 20(1)?",
        es: "¿Por qué una aprobación no informada de las medidas de ciberseguridad no protege al director general en virtud del artículo 20(1)?",
        pl: "Dlaczego nieświadoma akceptacja środków cyberbezpieczeństwa nie chroni dyrektora generalnego na podstawie artykułu 20(1)?",
        cs: "Proč neinformovaný souhlas s kybernetickými bezpečnostními opatřeními generálního ředitele podle článku 20(1) nechrání?",
        pt: "Por que razão uma aprovação não informada das medidas de cibersegurança não protege o diretor executivo nos termos do artigo 20(1)?",
        ro: "De ce o aprobare neinformată a măsurilor de securitate cibernetică nu îl protejează pe directorul general în temeiul articolului 20(1)?",
      },
      options: [
        { en: "Because the CFO must co-sign every security decision", de: "Weil der CFO jede Sicherheitsentscheidung mitzeichnen muss", nl: "Omdat de CFO elke beveiligingsbeslissing moet medeondertekenen", fr: "Parce que le CFO doit cosigner chaque décision de sécurité", it: "Perché il CFO deve controfirmare ogni decisione di sicurezza", es: "Porque el CFO debe co-firmar cada decisión de seguridad", pl: "Ponieważ CFO musi współpodpisać każdą decyzję dotyczącą bezpieczeństwa", cs: "Protože finanční ředitel musí spolupodepsat každé bezpečnostní rozhodnutí", pt: "Porque o diretor financeiro tem de coassinar cada decisão de segurança", ro: "Pentru că directorul financiar trebuie să cosemneze fiecare decizie de securitate" },
        { en: "Because the sign-off must show the CEO understood the risk picture behind the measures", de: "Weil die Freigabe belegen muss, dass der CEO das Risikobild hinter den Maßnahmen verstanden hat", nl: "Omdat de goedkeuring moet aantonen dat de CEO het risicoprofiel achter de maatregelen heeft begrepen", fr: "Parce que l'approbation doit démontrer que le dirigeant a compris le tableau des risques sous-jacent aux mesures", it: "Perché l'approvazione deve dimostrare che l'amministratore delegato ha compreso il quadro dei rischi alla base delle misure", es: "Porque la aprobación debe demostrar que el director general comprendió el panorama de riesgos que hay detrás de las medidas", pl: "Ponieważ akceptacja musi wykazywać, że dyrektor generalny zrozumiał obraz ryzyka stojący za środkami", cs: "Protože souhlas musí prokázat, že generální ředitel pochopil obraz rizik stojící za opatřeními", pt: "Porque a aprovação tem de demonstrar que o diretor executivo compreendeu o panorama de risco subjacente às medidas", ro: "Pentru că aprobarea trebuie să demonstreze că directorul general a înțeles tabloul de risc din spatele măsurilor" },
        { en: "Because Article 20(1) only applies to the CISO", de: "Weil Artikel 20 Absatz 1 nur für den CISO gilt", nl: "Omdat Artikel 20(1) alleen van toepassing is op de CISO", fr: "Parce que l'article 20(1) ne s'applique qu'au CISO", it: "Perché l'articolo 20(1) si applica solo al CISO", es: "Porque el artículo 20(1) solo se aplica al CISO", pl: "Ponieważ artykuł 20(1) dotyczy wyłącznie CISO", cs: "Protože článek 20(1) se vztahuje pouze na CISO", pt: "Porque o artigo 20(1) se aplica apenas ao CISO", ro: "Pentru că articolul 20(1) se aplică doar CISO" },
        { en: "Because the auditor requires a separate budget document", de: "Weil der Auditor ein separates Budgetdokument verlangt", nl: "Omdat de auditor een apart budgetdocument vereist", fr: "Parce que l'auditeur exige un document budgétaire distinct", it: "Perché il revisore richiede un documento di budget separato", es: "Porque el auditor exige un documento presupuestario aparte", pl: "Ponieważ audytor wymaga osobnego dokumentu budżetowego", cs: "Protože auditor vyžaduje samostatný rozpočtový dokument", pt: "Porque o auditor exige um documento orçamental separado", ro: "Pentru că auditorul solicită un document bugetar separat" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A sign-off without understanding the risk picture is decorative - Article 20(1) requires the management body to understand what they are approving.",
        de: "Eine Freigabe ohne Verständnis des Risikobilds ist rein dekorativ - Artikel 20 Absatz 1 verlangt, dass die Geschäftsleitung versteht, was sie genehmigt.",
        nl: "Een goedkeuring zonder begrip van het risicoprofiel is louter decoratief - Artikel 20(1) vereist dat het bestuur begrijpt wat het goedkeurt.",
        fr: "Une approbation sans compréhension du tableau des risques est purement décorative : l'article 20(1) exige que l'organe de direction comprenne ce qu'il approuve.",
        it: "Un'approvazione senza la comprensione del quadro dei rischi è puramente decorativa: l'articolo 20(1) richiede che l'organo di gestione comprenda ciò che approva.",
        es: "Una aprobación sin comprender el panorama de riesgos es meramente decorativa: el artículo 20(1) exige que el órgano de dirección comprenda lo que aprueba.",
        pl: "Akceptacja bez zrozumienia obrazu ryzyka jest jedynie dekoracyjna: artykuł 20(1) wymaga, aby organ zarządzający rozumiał, co zatwierdza.",
        cs: "Souhlas bez porozumění obrazu rizik je jen formální. Článek 20(1) vyžaduje, aby řídicí orgán rozuměl tomu, co schvaluje.",
        pt: "Uma aprovação sem a compreensão do panorama de risco é decorativa. O artigo 20(1) exige que o órgão de administração compreenda o que está a aprovar.",
        ro: "O aprobare lipsită de înțelegerea tabloului de risc este decorativă. Articolul 20(1) impune ca organul de conducere să înțeleagă ce aprobă.",
      },
    },
  ],
});

export default quiz;
