import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.10",
  passingScore: 75,
  questions: [
    {
      id: "2.10.1",
      question: {
        en: "What are the three duties bundled into Measure 5?",
        de: "Welche drei Pflichten sind in Maßnahme 5 gebündelt?",
        nl: "Wat zijn de drie verplichtingen die in Maatregel 5 zijn gebundeld?",
        fr: "Quelles sont les trois obligations regroupées dans la mesure 5 ?",
        it: "Quali sono i tre obblighi raggruppati nella misura 5?",
        es: "¿Cuáles son los tres deberes agrupados en la medida 5?",
        pl: "Jakie trzy obowiązki są połączone w środku 5?",
        cs: "Které tři povinnosti jsou sdruženy v opatření 5?",
        pt: "Que três deveres estão agrupados na Medida 5?",
        ro: "Care sunt cele trei obligații grupate în Măsura 5?",
      },
      options: [
        { en: "Backup, recovery, and crisis management", de: "Backup, Wiederherstellung und Krisenmanagement", nl: "Back-up, herstel en crisismanagement", fr: "Sauvegarde, rétablissement et gestion de crise", it: "Backup, ripristino e gestione delle crisi", es: "Copia de seguridad, recuperación y gestión de crisis", pl: "Kopia zapasowa, odtwarzanie i zarządzanie kryzysowe", cs: "Zálohování, obnovu a krizové řízení", pt: "Cópia de segurança, recuperação e gestão de crises", ro: "Copii de rezervă, recuperare și gestionarea crizelor" },
        { en: "Secure acquisition, secure development, and vulnerability handling", de: "Sichere Beschaffung, sichere Entwicklung und Schwachstellenbehandlung", nl: "Veilige inkoop, veilige ontwikkeling en kwetsbaarheidsbeheer", fr: "Acquisition sécurisée, développement sécurisé et traitement des vulnérabilités", it: "Acquisizione sicura, sviluppo sicuro e gestione delle vulnerabilità", es: "Adquisición segura, desarrollo seguro y gestión de vulnerabilidades", pl: "Bezpieczne nabywanie, bezpieczne tworzenie oprogramowania i obsługa podatności", cs: "Bezpečné pořizování, bezpečný vývoj a řešení zranitelností", pt: "Aquisição segura, desenvolvimento seguro e tratamento de vulnerabilidades", ro: "Achiziție securizată, dezvoltare securizată și tratarea vulnerabilităților" },
        { en: "Risk analysis, risk treatment, and risk acceptance", de: "Risikoanalyse, Risikobehandlung und Risikoakzeptanz", nl: "Risicoanalyse, risicobehandeling en risicoacceptatie", fr: "Analyse des risques, traitement des risques et acceptation des risques", it: "Analisi dei rischi, trattamento dei rischi e accettazione dei rischi", es: "Análisis de riesgos, tratamiento de riesgos y aceptación de riesgos", pl: "Analiza ryzyka, postępowanie z ryzykiem i akceptacja ryzyka", cs: "Analýzu rizik, ošetření rizik a přijetí rizik", pt: "Análise de riscos, tratamento de riscos e aceitação de riscos", ro: "Analiza riscurilor, tratarea riscurilor și acceptarea riscurilor" },
        { en: "Training, awareness, and phishing simulations", de: "Schulung, Sensibilisierung und Phishing-Simulationen", nl: "Training, bewustwording en phishingsimulaties", fr: "Formation, sensibilisation et simulations d'hameçonnage", it: "Formazione, sensibilizzazione e simulazioni di phishing", es: "Formación, concienciación y simulaciones de phishing", pl: "Szkolenia, podnoszenie świadomości i symulacje phishingu", cs: "Školení, osvětu a simulace phishingu", pt: "Formação, sensibilização e simulações de phishing", ro: "Formare, conștientizare și simulări de phishing" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Measure 5 bundles secure acquisition, secure development, and vulnerability handling - with patching being the most important month to month.",
        de: "Maßnahme 5 bündelt sichere Beschaffung, sichere Entwicklung und Schwachstellenbehandlung - wobei das Patching im Tagesgeschäft am wichtigsten ist.",
        nl: "Maatregel 5 bundelt veilige inkoop, veilige ontwikkeling en kwetsbaarheidsbeheer - waarbij patching van maand tot maand het belangrijkst is.",
        fr: "La mesure 5 regroupe l'acquisition sécurisée, le développement sécurisé et le traitement des vulnérabilités, l'application de correctifs étant la plus importante au quotidien.",
        it: "La misura 5 raggruppa acquisizione sicura, sviluppo sicuro e gestione delle vulnerabilità, con l'applicazione delle patch come attività più importante mese per mese.",
        es: "La medida 5 agrupa la adquisición segura, el desarrollo seguro y la gestión de vulnerabilidades, siendo la aplicación de parches lo más importante mes a mes.",
        pl: "Środek 5 łączy bezpieczne nabywanie, bezpieczne tworzenie oprogramowania i obsługę podatności, przy czym instalowanie łatek jest najważniejsze z miesiąca na miesiąc.",
        cs: "Opatření 5 sdružuje bezpečné pořizování, bezpečný vývoj a řešení zranitelností, přičemž z měsíce na měsíc je nejdůležitější instalace oprav.",
        pt: "A Medida 5 agrupa a aquisição segura, o desenvolvimento seguro e o tratamento de vulnerabilidades, sendo a aplicação de correções a tarefa mais importante mês a mês.",
        ro: "Măsura 5 grupează achiziția securizată, dezvoltarea securizată și tratarea vulnerabilităților, aplicarea corecțiilor fiind cea mai importantă activitate lunară.",
      },
    },
    {
      id: "2.10.2",
      question: {
        en: "What is a 'patch SLA'?",
        de: "Was ist ein 'Patch-SLA'?",
        nl: "Wat is een 'patch-SLA'?",
        fr: "Qu'est-ce qu'un 'SLA de correctifs' ?",
        it: "Che cos'è un 'SLA per le patch'?",
        es: "¿Qué es un 'SLA de parches'?",
        pl: "Czym jest 'SLA dla łatek'?",
        cs: "Co je 'SLA pro opravy'?",
        pt: "O que é um 'SLA de correções'?",
        ro: "Ce este un 'SLA pentru corecții'?",
      },
      options: [
        { en: "A service contract with the software vendor for updates", de: "Ein Servicevertrag mit dem Softwareanbieter für Updates", nl: "Een servicecontract met de softwareleverancier voor updates", fr: "Un contrat de service avec l'éditeur de logiciel pour les mises à jour", it: "Un contratto di servizio con il fornitore di software per gli aggiornamenti", es: "Un contrato de servicio con el proveedor de software para las actualizaciones", pl: "Umowa serwisowa z dostawcą oprogramowania na aktualizacje", cs: "Servisní smlouva s dodavatelem softwaru na aktualizace", pt: "Um contrato de serviço com o fornecedor de software para atualizações", ro: "Un contract de servicii cu furnizorul de software pentru actualizări" },
        { en: "A written deadline for applying patches, set by severity level", de: "Eine schriftlich festgelegte Frist für das Einspielen von Patches, gestaffelt nach Schweregrad", nl: "Een schriftelijk vastgelegde deadline voor het toepassen van patches, ingedeeld naar ernst", fr: "Un délai écrit pour l'application des correctifs, défini par niveau de gravité", it: "Una scadenza scritta per l'applicazione delle patch, definita per livello di gravità", es: "Un plazo por escrito para aplicar los parches, establecido por nivel de gravedad", pl: "Pisemny termin instalowania łatek, ustalony według poziomu istotności", cs: "Písemná lhůta pro instalaci oprav stanovená podle úrovně závažnosti", pt: "Um prazo escrito para a aplicação de correções, definido por nível de gravidade", ro: "Un termen scris pentru aplicarea corecțiilor, stabilit în funcție de nivelul de gravitate" },
        { en: "A report generated after each patch is applied", de: "Ein Bericht, der nach jedem eingespielten Patch erstellt wird", nl: "Een rapport dat na elke toegepaste patch wordt gegenereerd", fr: "Un rapport généré après l'application de chaque correctif", it: "Un rapporto generato dopo l'applicazione di ogni patch", es: "Un informe generado después de aplicar cada parche", pl: "Raport generowany po zainstalowaniu każdej łatki", cs: "Zpráva vytvořená po instalaci každé opravy", pt: "Um relatório gerado após a aplicação de cada correção", ro: "Un raport generat după aplicarea fiecărei corecții" },
        { en: "A legal agreement between the company and the auditor", de: "Eine rechtliche Vereinbarung zwischen dem Unternehmen und dem Auditor", nl: "Een juridische overeenkomst tussen het bedrijf en de auditor", fr: "Un accord juridique entre l'entreprise et l'auditeur", it: "Un accordo legale tra l'impresa e il revisore", es: "Un acuerdo jurídico entre la empresa y el auditor", pl: "Umowa prawna między firmą a audytorem", cs: "Právní dohoda mezi společností a auditorem", pt: "Um acordo jurídico entre a empresa e o auditor", ro: "Un acord juridic între companie și auditor" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A patch SLA is the written deadline for applying patches, grouped by severity level - the specific timelines are yours to set but must exist on paper.",
        de: "Ein Patch-SLA ist die schriftlich festgelegte Frist für das Einspielen von Patches, gestaffelt nach Schweregrad - die konkreten Zeitvorgaben legen Sie selbst fest, müssen aber dokumentiert sein.",
        nl: "Een patch-SLA is de schriftelijk vastgelegde deadline voor het toepassen van patches, gegroepeerd naar ernstniveau - de concrete tijdlijnen stelt u zelf vast, maar ze moeten op papier bestaan.",
        fr: "Un SLA de correctifs est le délai écrit pour l'application des correctifs, regroupé par niveau de gravité : les échéances précises vous appartiennent mais doivent figurer par écrit.",
        it: "Un SLA per le patch è la scadenza scritta per l'applicazione delle patch, raggruppata per livello di gravità: le tempistiche specifiche le stabilite voi, ma devono esistere per iscritto.",
        es: "Un SLA de parches es el plazo por escrito para aplicar los parches, agrupado por nivel de gravedad: los plazos concretos los fija usted, pero deben constar por escrito.",
        pl: "SLA dla łatek to pisemny termin instalowania łatek, pogrupowany według poziomu istotności - konkretne terminy ustalają Państwo sami, ale muszą istnieć na piśmie.",
        cs: "SLA pro opravy je písemná lhůta pro instalaci oprav, seskupená podle úrovně závažnosti. Konkrétní lhůty si stanovíte sami, ale musí existovat na papíře.",
        pt: "Um SLA de correções é o prazo escrito para a aplicação de correções, agrupado por nível de gravidade. Os prazos específicos são definidos por si, mas têm de existir por escrito.",
        ro: "Un SLA pentru corecții este termenul scris pentru aplicarea corecțiilor, grupat în funcție de nivelul de gravitate. Termenele specifice le stabiliți dumneavoastră, dar trebuie să existe pe hârtie.",
      },
    },
    {
      id: "2.10.3",
      question: {
        en: "What is the single most important operational evidence for Measure 5?",
        de: "Was ist der wichtigste operative Nachweis für Maßnahme 5?",
        nl: "Wat is het belangrijkste operationele bewijs voor Maatregel 5?",
        fr: "Quelle est la preuve opérationnelle la plus importante pour la mesure 5 ?",
        it: "Qual è la prova operativa più importante in assoluto per la misura 5?",
        es: "¿Cuál es la prueba operativa más importante para la medida 5?",
        pl: "Jaki jest najważniejszy dowód operacyjny dla środka 5?",
        cs: "Jaký je nejdůležitější provozní důkaz pro opatření 5?",
        pt: "Qual é a prova operacional mais importante para a Medida 5?",
        ro: "Care este cea mai importantă dovadă operațională pentru Măsura 5?",
      },
      options: [
        { en: "A list of all software the company uses", de: "Eine Liste aller vom Unternehmen genutzten Software", nl: "Een lijst van alle software die het bedrijf gebruikt", fr: "Une liste de tous les logiciels utilisés par l'entreprise", it: "Un elenco di tutto il software utilizzato dall'impresa", es: "Una lista de todo el software que utiliza la empresa", pl: "Lista całego oprogramowania używanego przez firmę", cs: "Seznam veškerého softwaru, který společnost používá", pt: "Uma lista de todo o software que a empresa utiliza", ro: "O listă cu tot software-ul pe care îl utilizează compania" },
        { en: "A written patch SLA and a quarterly report on whether you are meeting it", de: "Ein schriftlicher Patch-SLA und ein vierteljährlicher Bericht über dessen Einhaltung", nl: "Een schriftelijke patch-SLA en een kwartaalrapportage over de naleving ervan", fr: "Un SLA de correctifs écrit et un rapport trimestriel indiquant si vous le respectez", it: "Un SLA per le patch scritto e un rapporto trimestrale sul suo rispetto", es: "Un SLA de parches por escrito y un informe trimestral sobre si se está cumpliendo", pl: "Pisemny SLA dla łatek oraz kwartalny raport o tym, czy jest on dotrzymywany", cs: "Písemné SLA pro opravy a čtvrtletní zprávu o tom, zda je plníte", pt: "Um SLA de correções escrito e um relatório trimestral sobre se o está a cumprir", ro: "Un SLA scris pentru corecții și un raport trimestrial privind respectarea acestuia" },
        { en: "A copy of every patch applied in the last year", de: "Eine Kopie jedes im letzten Jahr eingespielten Patches", nl: "Een kopie van elke patch die het afgelopen jaar is toegepast", fr: "Une copie de chaque correctif appliqué au cours de l'année écoulée", it: "Una copia di ogni patch applicata nell'ultimo anno", es: "Una copia de cada parche aplicado en el último año", pl: "Kopia każdej łatki zainstalowanej w ostatnim roku", cs: "Kopii každé opravy nainstalované za poslední rok", pt: "Uma cópia de cada correção aplicada no último ano", ro: "O copie a fiecărei corecții aplicate în ultimul an" },
        { en: "A signed policy document from the CISO", de: "Ein vom CISO unterschriebenes Richtliniendokument", nl: "Een door de CISO ondertekend beleidsdocument", fr: "Un document de politique signé par le CISO", it: "Un documento di politica firmato dal CISO", es: "Un documento de política firmado por el CISO", pl: "Podpisany przez CISO dokument polityki", cs: "Podepsaný dokument politiky od CISO", pt: "Um documento de política assinado pelo CISO", ro: "Un document de politică semnat de CISO" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A written patch SLA and a quarterly report on SLA compliance is the single most important operational evidence - the auditor asks for both.",
        de: "Ein schriftlicher Patch-SLA und ein vierteljährlicher Bericht über die SLA-Einhaltung sind der wichtigste operative Nachweis - der Auditor fragt nach beidem.",
        nl: "Een schriftelijke patch-SLA en een kwartaalrapportage over de SLA-naleving zijn het belangrijkste operationele bewijs - de auditor vraagt naar allebei.",
        fr: "Un SLA de correctifs écrit et un rapport trimestriel sur le respect du SLA constituent la preuve opérationnelle la plus importante : l'auditeur demande les deux.",
        it: "Un SLA per le patch scritto e un rapporto trimestrale sul rispetto del SLA costituiscono la prova operativa più importante in assoluto: il revisore richiede entrambi.",
        es: "Un SLA de parches por escrito y un informe trimestral sobre el cumplimiento del SLA constituyen la prueba operativa más importante: el auditor pide ambos.",
        pl: "Pisemny SLA dla łatek oraz kwartalny raport o przestrzeganiu SLA to najważniejszy dowód operacyjny - audytor prosi o oba.",
        cs: "Písemné SLA pro opravy a čtvrtletní zpráva o dodržování SLA jsou nejdůležitějším provozním důkazem. Auditor si vyžádá obojí.",
        pt: "Um SLA de correções escrito e um relatório trimestral sobre o cumprimento do SLA são a prova operacional mais importante. O auditor pede ambos.",
        ro: "Un SLA scris pentru corecții și un raport trimestrial privind respectarea SLA sunt cea mai importantă dovadă operațională. Auditorul le solicită pe ambele.",
      },
    },
    {
      id: "2.10.4",
      question: {
        en: "What is 'vulnerability disclosure' in the context of Measure 5?",
        de: "Was bedeutet 'Vulnerability Disclosure' im Kontext von Maßnahme 5?",
        nl: "Wat is 'kwetsbaarheidsmelding' in de context van Maatregel 5?",
        fr: "Qu'est-ce que la 'divulgation des vulnérabilités' dans le contexte de la mesure 5 ?",
        it: "Cos'è la 'divulgazione delle vulnerabilità' nel contesto della misura 5?",
        es: "¿Qué es la 'divulgación de vulnerabilidades' en el contexto de la medida 5?",
        pl: "Czym jest 'ujawnianie podatności' w kontekście środka 5?",
        cs: "Co je 'zveřejňování zranitelností' v kontextu opatření 5?",
        pt: "O que é a 'divulgação de vulnerabilidades' no contexto da Medida 5?",
        ro: "Ce este 'divulgarea vulnerabilităților' în contextul Măsurii 5?",
      },
      options: [
        { en: "Publicly announcing every vulnerability found in your own systems", de: "Jede in den eigenen Systemen gefundene Schwachstelle öffentlich bekannt zu geben", nl: "Elke kwetsbaarheid die in uw eigen systemen wordt gevonden openbaar bekendmaken", fr: "Annoncer publiquement chaque vulnérabilité trouvée dans vos propres systèmes", it: "Annunciare pubblicamente ogni vulnerabilità rilevata nei propri sistemi", es: "Anunciar públicamente cada vulnerabilidad encontrada en sus propios sistemas", pl: "Publiczne ogłaszanie każdej podatności znalezionej we własnych systemach", cs: "Veřejné oznamování každé zranitelnosti nalezené ve vlastních systémech", pt: "Anunciar publicamente todas as vulnerabilidades encontradas nos seus próprios sistemas", ro: "Anunțarea publică a fiecărei vulnerabilități descoperite în propriile sisteme" },
        { en: "A published way for outside security researchers to report bugs to your company", de: "Ein veröffentlichter Weg, über den externe Sicherheitsforscher Schwachstellen an Ihr Unternehmen melden können", nl: "Een gepubliceerde manier voor externe beveiligingsonderzoekers om kwetsbaarheden aan uw bedrijf te melden", fr: "Un moyen publié permettant aux chercheurs en sécurité externes de signaler des failles à votre entreprise", it: "Un canale pubblicato che consente a ricercatori di sicurezza esterni di segnalare le falle alla vostra impresa", es: "Una vía publicada para que los investigadores de seguridad externos comuniquen fallos a su empresa", pl: "Opublikowany sposób, w jaki zewnętrzni badacze bezpieczeństwa mogą zgłaszać błędy Państwa firmie", cs: "Zveřejněný způsob, jak mohou externí bezpečnostní výzkumníci nahlásit chyby vaší společnosti", pt: "Uma via publicada para que investigadores de segurança externos comuniquem falhas à sua empresa", ro: "O modalitate publicată prin care cercetătorii externi de securitate pot raporta defecte companiei dumneavoastră" },
        { en: "Sharing vulnerability data with competitors", de: "Schwachstellendaten mit Wettbewerbern zu teilen", nl: "Kwetsbaarheidsgegevens delen met concurrenten", fr: "Partager les données de vulnérabilité avec les concurrents", it: "Condividere i dati sulle vulnerabilità con i concorrenti", es: "Compartir datos de vulnerabilidades con los competidores", pl: "Udostępnianie danych o podatnościach konkurentom", cs: "Sdílení dat o zranitelnostech s konkurenty", pt: "Partilhar dados de vulnerabilidades com concorrentes", ro: "Partajarea datelor despre vulnerabilități cu concurenții" },
        { en: "The CISO's annual report to the board on known vulnerabilities", de: "Der jährliche Bericht des CISO an den Vorstand über bekannte Schwachstellen", nl: "Het jaarlijkse rapport van de CISO aan het bestuur over bekende kwetsbaarheden", fr: "Le rapport annuel du CISO au conseil sur les vulnérabilités connues", it: "Il rapporto annuale del CISO al consiglio sulle vulnerabilità note", es: "El informe anual del CISO al consejo sobre las vulnerabilidades conocidas", pl: "Roczny raport CISO dla zarządu o znanych podatnościach", cs: "Roční zprávu CISO orgánu o známých zranitelnostech", pt: "O relatório anual do CISO ao órgão de administração sobre vulnerabilidades conhecidas", ro: "Raportul anual al CISO către organul de conducere privind vulnerabilitățile cunoscute" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Vulnerability disclosure means having a published process for outsiders to report bugs - some NIS2 entities are required to have a public disclosure page.",
        de: "Vulnerability Disclosure bedeutet, einen veröffentlichten Prozess zu haben, über den Externe Schwachstellen melden können - einige NIS2-Einrichtungen sind verpflichtet, eine öffentliche Disclosure-Seite bereitzustellen.",
        nl: "Kwetsbaarheidsmelding betekent een gepubliceerd proces hebben waarmee buitenstaanders kwetsbaarheden kunnen melden - sommige NIS2-entiteiten zijn verplicht een openbare meldingspagina te hebben.",
        fr: "La divulgation des vulnérabilités consiste à disposer d'un processus publié permettant à des tiers de signaler des failles : certaines entités NIS2 sont tenues d'avoir une page de divulgation publique.",
        it: "La divulgazione delle vulnerabilità consiste nell'avere un processo pubblicato che consente agli esterni di segnalare le falle: alcuni soggetti NIS2 sono tenuti ad avere una pagina di divulgazione pubblica.",
        es: "La divulgación de vulnerabilidades consiste en disponer de un proceso publicado para que terceros comuniquen fallos: algunas entidades NIS2 están obligadas a tener una página de divulgación pública.",
        pl: "Ujawnianie podatności oznacza posiadanie opublikowanego procesu umożliwiającego osobom z zewnątrz zgłaszanie błędów - niektóre podmioty NIS2 są zobowiązane do posiadania publicznej strony do zgłaszania podatności.",
        cs: "Zveřejňování zranitelností znamená mít zveřejněný postup, jak mohou externí osoby nahlásit chyby. Některé subjekty NIS2 musí mít veřejnou stránku pro zveřejňování.",
        pt: "A divulgação de vulnerabilidades significa ter um processo publicado para que pessoas externas comuniquem falhas. Algumas entidades NIS2 são obrigadas a ter uma página pública de divulgação.",
        ro: "Divulgarea vulnerabilităților înseamnă a avea un proces publicat prin care persoane externe pot raporta defecte. Unele entități NIS2 sunt obligate să aibă o pagină publică de divulgare.",
      },
    },
  ],
});

export default quiz;
