import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.14",
  passingScore: 75,
  questions: [
    {
      id: "2.14.1",
      question: {
        en: "Why does Article 21(2)(i) bundle HR security, access control, and asset management in the same clause?",
        de: "Warum bündelt Artikel 21 Absatz 2(i) Personalsicherheit, Zugangskontrolle und Asset-Management in derselben Klausel?",
        nl: "Waarom bundelt Artikel 21(2)(i) HR-beveiliging, toegangscontrole en middelenbeheer in dezelfde clausule?",
        fr: "Pourquoi l'article 21(2)(i) regroupe-t-il la sécurité des ressources humaines, le contrôle d'accès et la gestion des actifs dans la même clause ?",
        it: "Perché l'articolo 21(2)(i) raggruppa la sicurezza delle risorse umane, il controllo degli accessi e la gestione degli asset nella stessa clausola?",
        es: "¿Por qué el artículo 21(2)(i) agrupa la seguridad de los recursos humanos, el control de acceso y la gestión de activos en la misma cláusula?",
        pl: "Dlaczego artykuł 21(2)(i) łączy bezpieczeństwo kadrowe, kontrolę dostępu i zarządzanie zasobami w jednym przepisie?",
      },
      options: [
        { en: "To reduce the total number of articles in the directive", de: "Um die Gesamtzahl der Artikel in der Richtlinie zu reduzieren", nl: "Om het totale aantal artikelen in de richtlijn te verminderen", fr: "Pour réduire le nombre total d'articles dans la directive", it: "Per ridurre il numero totale di articoli nella direttiva", es: "Para reducir el número total de artículos de la directiva", pl: "Aby zmniejszyć całkowitą liczbę artykułów w dyrektywie" },
        { en: "Because they are one system - a person who left and still has access is a failure of all three", de: "Weil sie ein System bilden - eine Person, die ausgeschieden ist und noch Zugang hat, ist ein Versagen aller drei", nl: "Omdat ze één systeem vormen - een persoon die vertrokken is maar nog steeds toegang heeft, is een falen van alle drie", fr: "Parce qu'ils forment un seul système : une personne partie qui conserve un accès constitue une défaillance des trois", it: "Perché costituiscono un unico sistema: una persona che ha lasciato l'azienda e ha ancora accesso rappresenta un fallimento di tutti e tre", es: "Porque forman un solo sistema: una persona que se marchó y todavía tiene acceso es un fallo de los tres", pl: "Ponieważ stanowią jeden system - osoba, która odeszła i nadal ma dostęp, to porażka wszystkich trzech" },
        { en: "Because they are all the responsibility of the HR department", de: "Weil sie alle in der Verantwortung der Personalabteilung liegen", nl: "Omdat ze alle drie de verantwoordelijkheid zijn van de HR-afdeling", fr: "Parce qu'ils relèvent tous de la responsabilité du service des ressources humaines", it: "Perché sono tutti di competenza del reparto risorse umane", es: "Porque todos son responsabilidad del departamento de recursos humanos", pl: "Ponieważ wszystkie należą do obowiązków działu kadr" },
        { en: "Because they only apply to companies with more than 250 employees", de: "Weil sie nur für Unternehmen mit mehr als 250 Mitarbeitenden gelten", nl: "Omdat ze alleen van toepassing zijn op bedrijven met meer dan 250 werknemers", fr: "Parce qu'ils ne s'appliquent qu'aux entreprises de plus de 250 employés", it: "Perché si applicano solo alle imprese con più di 250 dipendenti", es: "Porque solo se aplican a las empresas con más de 250 empleados", pl: "Ponieważ dotyczą wyłącznie firm zatrudniających ponad 250 pracowników" },
      ],
      correctIndex: 1,
      explanation: {
        en: "They are bundled because they only work as a system - when HR and IT do not talk, former employees keep access, which is a failure of all three duties.",
        de: "Sie sind gebündelt, weil sie nur als System funktionieren - wenn HR und IT nicht kommunizieren, behalten ehemalige Mitarbeitende ihren Zugang, was ein Versagen aller drei Pflichten darstellt.",
        nl: "Ze zijn gebundeld omdat ze alleen als systeem werken - wanneer HR en IT niet communiceren, behouden voormalige medewerkers toegang, wat een falen is van alle drie de plichten.",
        fr: "Ils sont regroupés parce qu'ils ne fonctionnent qu'en tant que système : lorsque les RH et l'informatique ne communiquent pas, les anciens employés conservent leur accès, ce qui constitue une défaillance des trois obligations.",
        it: "Sono raggruppati perché funzionano solo come sistema: quando risorse umane e IT non comunicano, gli ex dipendenti mantengono l'accesso, il che rappresenta un fallimento di tutti e tre gli obblighi.",
        es: "Se agrupan porque solo funcionan como un sistema: cuando recursos humanos y TI no se comunican, los antiguos empleados conservan el acceso, lo que constituye un fallo de los tres deberes.",
        pl: "Są połączone, ponieważ działają tylko jako system - gdy dział kadr i IT się nie komunikują, byli pracownicy zachowują dostęp, co stanowi porażkę wszystkich trzech obowiązków.",
      },
    },
    {
      id: "2.14.2",
      question: {
        en: "What is the single most common audit finding in Measure 9?",
        de: "Was ist die häufigste Audit-Feststellung bei Maßnahme 9?",
        nl: "Wat is de meest voorkomende auditbevinding bij Maatregel 9?",
        fr: "Quelle est la constatation d'audit la plus fréquente dans la mesure 9 ?",
        it: "Qual è il rilievo di audit più comune in assoluto nella misura 9?",
        es: "¿Cuál es el hallazgo de auditoría más común en la medida 9?",
        pl: "Jakie jest najczęstsze ustalenie audytowe w środku 9?",
      },
      options: [
        { en: "Missing asset inventory entries", de: "Fehlende Einträge im Asset-Inventar", nl: "Ontbrekende vermeldingen in het middelenregister", fr: "Des entrées manquantes dans l'inventaire des actifs", it: "Voci mancanti nell'inventario degli asset", es: "Entradas faltantes en el inventario de activos", pl: "Brakujące wpisy w inwentaryzacji zasobów" },
        { en: "The leaver step - former employees still holding active access", de: "Der Austrittsschritt - ehemalige Mitarbeitende mit noch aktivem Zugang", nl: "De vertrekstap - voormalige medewerkers die nog actieve toegang hebben", fr: "L'étape du départ : d'anciens employés conservant un accès actif", it: "La fase di uscita: ex dipendenti che mantengono un accesso attivo", es: "El paso de la baja: antiguos empleados que conservan acceso activo", pl: "Etap odejścia - byli pracownicy nadal posiadający aktywny dostęp" },
        { en: "Lack of role-based access control", de: "Fehlen einer rollenbasierten Zugangskontrolle", nl: "Ontbreken van op rollen gebaseerde toegangscontrole", fr: "L'absence de contrôle d'accès basé sur les rôles", it: "L'assenza di un controllo degli accessi basato sui ruoli", es: "La falta de control de acceso basado en roles", pl: "Brak kontroli dostępu opartej na rolach" },
        { en: "Incomplete onboarding documentation", de: "Unvollständige Onboarding-Dokumentation", nl: "Onvolledige onboardingdocumentatie", fr: "Une documentation d'intégration incomplète", it: "Documentazione di onboarding incompleta", es: "Documentación de incorporación incompleta", pl: "Niekompletna dokumentacja wdrożeniowa" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The leaver step is the most common finding - a former employee still holding a live VPN login or admin account weeks after departure.",
        de: "Der Austrittsschritt ist die häufigste Feststellung - ein ehemaliger Mitarbeitender, der Wochen nach dem Austritt noch einen aktiven VPN-Zugang oder Administratorkonto besitzt.",
        nl: "De vertrekstap is de meest voorkomende bevinding - een voormalige medewerker die weken na het vertrek nog een actieve VPN-login of beheerdersaccount heeft.",
        fr: "L'étape du départ est la constatation la plus fréquente : un ancien employé conservant un identifiant VPN actif ou un compte administrateur des semaines après son départ.",
        it: "La fase di uscita è il rilievo più comune: un ex dipendente che mantiene un accesso VPN attivo o un account amministratore settimane dopo la partenza.",
        es: "El paso de la baja es el hallazgo más común: un antiguo empleado que conserva un inicio de sesión VPN activo o una cuenta de administrador semanas después de su marcha.",
        pl: "Etap odejścia jest najczęstszym ustaleniem - były pracownik nadal posiadający aktywny login VPN lub konto administratora tygodnie po odejściu.",
      },
    },
    {
      id: "2.14.3",
      question: {
        en: "What does 'least privilege' mean?",
        de: "Was bedeutet 'Least Privilege'?",
        nl: "Wat betekent 'least privilege'?",
        fr: "Que signifie le « moindre privilège » ?",
        it: "Cosa significa 'privilegio minimo'?",
        es: "¿Qué significa 'mínimo privilegio'?",
        pl: "Co oznacza 'najmniejsze uprawnienia'?",
      },
      options: [
        { en: "Only the CEO has access to all systems", de: "Nur der CEO hat Zugang zu allen Systemen", nl: "Alleen de CEO heeft toegang tot alle systemen", fr: "Seul le dirigeant a accès à tous les systèmes", it: "Solo l'amministratore delegato ha accesso a tutti i sistemi", es: "Solo el director general tiene acceso a todos los sistemas", pl: "Tylko dyrektor generalny ma dostęp do wszystkich systemów" },
        { en: "Every user has only the access they need for their job", de: "Jeder Benutzer hat nur den Zugang, den er für seine Arbeit benötigt", nl: "Elke gebruiker heeft alleen de toegang die hij voor zijn werk nodig heeft", fr: "Chaque utilisateur n'a que l'accès dont il a besoin pour son travail", it: "Ogni utente ha solo l'accesso necessario per il proprio lavoro", es: "Cada usuario tiene únicamente el acceso que necesita para su trabajo", pl: "Każdy użytkownik ma tylko taki dostęp, jakiego potrzebuje do swojej pracy" },
        { en: "Access is granted on a first-come, first-served basis", de: "Zugang wird nach dem Prinzip 'wer zuerst kommt' vergeben", nl: "Toegang wordt verleend op basis van wie het eerst komt", fr: "L'accès est accordé selon le principe du premier arrivé, premier servi", it: "L'accesso è concesso in base all'ordine di arrivo", es: "El acceso se concede por orden de llegada", pl: "Dostęp jest przyznawany według kolejności zgłoszeń" },
        { en: "Only IT staff have any system access", de: "Nur IT-Mitarbeitende haben Systemzugang", nl: "Alleen IT-medewerkers hebben systeemtoegang", fr: "Seul le personnel informatique a un accès quelconque aux systèmes", it: "Solo il personale IT ha qualsiasi accesso ai sistemi", es: "Solo el personal de TI tiene algún acceso a los sistemas", pl: "Tylko pracownicy IT mają jakikolwiek dostęp do systemów" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Least privilege means every user has only the permissions they need for their job - no more, no less.",
        de: "Least Privilege bedeutet, dass jeder Benutzer nur die Berechtigungen hat, die er für seine Arbeit benötigt - nicht mehr und nicht weniger.",
        nl: "Least privilege betekent dat elke gebruiker alleen de rechten heeft die hij voor zijn werk nodig heeft - niet meer en niet minder.",
        fr: "Le moindre privilège signifie que chaque utilisateur ne dispose que des autorisations dont il a besoin pour son travail, ni plus ni moins.",
        it: "Il privilegio minimo significa che ogni utente ha solo le autorizzazioni necessarie per il proprio lavoro, né più né meno.",
        es: "El mínimo privilegio significa que cada usuario tiene únicamente los permisos que necesita para su trabajo, ni más ni menos.",
        pl: "Najmniejsze uprawnienia oznaczają, że każdy użytkownik ma tylko te uprawnienia, których potrzebuje do swojej pracy - nie więcej i nie mniej.",
      },
    },
    {
      id: "2.14.4",
      question: {
        en: "What does the CIR (Annex 11.3) specifically require for privileged accounts?",
        de: "Was verlangt die CIR (Anhang 11.3) konkret für privilegierte Konten?",
        nl: "Wat vereist de CIR (Bijlage 11.3) specifiek voor geprivilegieerde accounts?",
        fr: "Qu'exige précisément la CIR (Annexe 11.3) pour les comptes à privilèges ?",
        it: "Cosa richiede specificamente la CIR (Allegato 11.3) per gli account con privilegi?",
        es: "¿Qué exige específicamente la CIR (Anexo 11.3) para las cuentas con privilegios?",
        pl: "Czego CIR (załącznik 11.3) konkretnie wymaga w odniesieniu do kont uprzywilejowanych?",
      },
      options: [
        { en: "That they be eliminated entirely", de: "Dass sie vollständig abgeschafft werden", nl: "Dat ze volledig worden afgeschaft", fr: "Qu'ils soient entièrement supprimés", it: "Che vengano eliminati del tutto", es: "Que se eliminen por completo", pl: "Aby zostały całkowicie zlikwidowane" },
        { en: "A dedicated policy with stronger controls and its own review cadence", de: "Eine eigene Richtlinie mit strengeren Maßnahmen und eigenem Überprüfungszyklus", nl: "Een specifiek beleid met sterkere maatregelen en een eigen beoordelingscyclus", fr: "Une politique dédiée avec des contrôles plus stricts et son propre cycle de réexamen", it: "Una politica dedicata con controlli più rigorosi e un proprio ciclo di riesame", es: "Una política específica con controles más estrictos y su propio ciclo de revisión", pl: "Dedykowaną politykę z silniejszymi kontrolami i własnym cyklem przeglądu" },
        { en: "That they only be used by the CISO", de: "Dass sie nur vom CISO verwendet werden", nl: "Dat ze alleen door de CISO worden gebruikt", fr: "Qu'ils ne soient utilisés que par le CISO", it: "Che vengano utilizzati solo dal CISO", es: "Que solo los utilice el CISO", pl: "Aby były używane wyłącznie przez CISO" },
        { en: "That they be shared among the IT team for efficiency", de: "Dass sie aus Effizienzgründen im IT-Team geteilt werden", nl: "Dat ze worden gedeeld binnen het IT-team voor efficiëntie", fr: "Qu'ils soient partagés au sein de l'équipe informatique par souci d'efficacité", it: "Che vengano condivisi all'interno del team IT per efficienza", es: "Que se compartan entre el equipo de TI por eficiencia", pl: "Aby były współdzielone w zespole IT dla efektywności" },
      ],
      correctIndex: 1,
      explanation: {
        en: "CIR Annex 11.3 requires privileged accounts to have their own dedicated policy with stronger controls - it is one of the eleven required policies.",
        de: "CIR Anhang 11.3 verlangt, dass privilegierte Konten eine eigene Richtlinie mit strengeren Maßnahmen haben - sie ist eine der elf geforderten Richtlinien.",
        nl: "CIR Bijlage 11.3 vereist dat geprivilegieerde accounts een eigen specifiek beleid hebben met sterkere maatregelen - het is een van de elf vereiste beleidslijnen.",
        fr: "L'Annexe 11.3 de la CIR exige que les comptes à privilèges disposent de leur propre politique dédiée assortie de contrôles plus stricts : c'est l'une des onze politiques requises.",
        it: "L'Allegato 11.3 della CIR richiede che gli account con privilegi abbiano una propria politica dedicata con controlli più rigorosi: è una delle undici politiche richieste.",
        es: "El Anexo 11.3 de la CIR exige que las cuentas con privilegios tengan su propia política específica con controles más estrictos: es una de las once políticas requeridas.",
        pl: "Załącznik 11.3 do CIR wymaga, aby konta uprzywilejowane miały własną, dedykowaną politykę z silniejszymi kontrolami - jest to jedna z jedenastu wymaganych polityk.",
      },
    },
  ],
});

export default quiz;
