import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.3",
  passingScore: 75,
  questions: [
    {
      id: "2.3.1",
      question: {
        en: "What are the four risk treatment options?",
        de: "Welche vier Risikobehandlungsoptionen gibt es?",
        nl: "Wat zijn de vier opties voor risicobehandeling?",
        fr: "Quelles sont les quatre options de traitement du risque ?",
        it: "Quali sono le quattro opzioni di trattamento del rischio?",
        es: "¿Cuáles son las cuatro opciones de tratamiento del riesgo?",
        pl: "Jakie są cztery opcje postępowania z ryzykiem?",
      },
      options: [
        { en: "Detect, respond, recover, report", de: "Erkennen, reagieren, wiederherstellen, melden", nl: "Detecteren, reageren, herstellen, melden", fr: "Détecter, réagir, rétablir, notifier", it: "Rilevare, rispondere, ripristinare, notificare", es: "Detectar, responder, recuperar, notificar", pl: "Wykrywać, reagować, przywracać, zgłaszać" },
        { en: "Avoid, mitigate, transfer, accept", de: "Vermeiden, mindern, übertragen, akzeptieren", nl: "Vermijden, beperken, overdragen, accepteren", fr: "Éviter, atténuer, transférer, accepter", it: "Evitare, attenuare, trasferire, accettare", es: "Evitar, mitigar, transferir, aceptar", pl: "Unikać, ograniczać, przenosić, akceptować" },
        { en: "Identify, analyse, treat, monitor", de: "Identifizieren, analysieren, behandeln, überwachen", nl: "Identificeren, analyseren, behandelen, monitoren", fr: "Identifier, analyser, traiter, surveiller", it: "Individuare, analizzare, trattare, monitorare", es: "Identificar, analizar, tratar, supervisar", pl: "Identyfikować, analizować, postępować, monitorować" },
        { en: "Prevent, insure, outsource, ignore", de: "Verhindern, versichern, auslagern, ignorieren", nl: "Voorkomen, verzekeren, uitbesteden, negeren", fr: "Prévenir, assurer, externaliser, ignorer", it: "Prevenire, assicurare, esternalizzare, ignorare", es: "Prevenir, asegurar, externalizar, ignorar", pl: "Zapobiegać, ubezpieczać, zlecać na zewnątrz, ignorować" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The four options are avoid, mitigate, transfer, and accept - and for NIS2 entities, mitigate is the workhorse for serious risks.",
        de: "Die vier Optionen sind vermeiden, mindern, übertragen und akzeptieren - und für NIS2-Einrichtungen ist das Mindern die wichtigste Option bei schwerwiegenden Risiken.",
        nl: "De vier opties zijn vermijden, beperken, overdragen en accepteren - en voor NIS2-entiteiten is beperken de voornaamste optie voor ernstige risico's.",
        fr: "Les quatre options sont éviter, atténuer, transférer et accepter, et pour les entités NIS2, l'atténuation est l'option de référence pour les risques sérieux.",
        it: "Le quattro opzioni sono evitare, attenuare, trasferire e accettare, e per i soggetti NIS2 l'attenuazione è l'opzione principale per i rischi gravi.",
        es: "Las cuatro opciones son evitar, mitigar, transferir y aceptar, y para las entidades NIS2 la mitigación es la opción principal para los riesgos graves.",
        pl: "Cztery opcje to unikać, ograniczać, przenosić i akceptować, a dla podmiotów NIS2 ograniczanie jest podstawową opcją w przypadku poważnych ryzyk.",
      },
    },
    {
      id: "2.3.2",
      question: {
        en: "Which document does CIR 2024/2690 Annex 2.1.1 require the management body to personally accept?",
        de: "Welches Dokument verlangt DVO 2024/2690 Anhang 2.1.1 zur persönlichen Akzeptanz durch das Leitungsorgan?",
        nl: "Welk document moet het leidinggevend orgaan volgens CIR 2024/2690 Bijlage 2.1.1 persoonlijk accepteren?",
        fr: "Quel document la CIR 2024/2690 Annexe 2.1.1 impose-t-elle à l'organe de direction d'accepter personnellement ?",
        it: "Quale documento la CIR 2024/2690 Allegato 2.1.1 richiede che l'organo di gestione accetti personalmente?",
        es: "¿Qué documento exige la CIR 2024/2690 Anexo 2.1.1 que el órgano de dirección acepte personalmente?",
        pl: "Który dokument CIR 2024/2690 załącznik 2.1.1 wymaga osobistego zaakceptowania przez organ zarządzający?",
      },
      options: [
        { en: "The risk matrix", de: "Die Risikomatrix", nl: "De risicomatrix", fr: "La matrice des risques", it: "La matrice dei rischi", es: "La matriz de riesgos", pl: "Macierz ryzyka" },
        { en: "The signed residual risk acceptance", de: "Die unterschriebene Restrisiko-Akzeptanz", nl: "De ondertekende acceptatie van het restrisico", fr: "L'acceptation signée du risque résiduel", it: "L'accettazione firmata del rischio residuo", es: "La aceptación firmada del riesgo residual", pl: "Podpisaną akceptację ryzyka rezydualnego" },
        { en: "The information security policy", de: "Die Informationssicherheitsrichtlinie", nl: "Het informatiebeveiligingsbeleid", fr: "La politique de sécurité de l'information", it: "La politica di sicurezza delle informazioni", es: "La política de seguridad de la información", pl: "Politykę bezpieczeństwa informacji" },
        { en: "The asset inventory", de: "Das Asset-Inventar", nl: "Het asset-inventaris", fr: "L'inventaire des actifs", it: "L'inventario degli asset", es: "El inventario de activos", pl: "Inwentaryzację zasobów" },
      ],
      correctIndex: 1,
      explanation: {
        en: "CIR 2024/2690 Annex 2.1.1 requires the management body to personally accept each residual risk - without the signed acceptance, the rest of risk management is treated as unapproved.",
        de: "DVO 2024/2690 Anhang 2.1.1 verlangt, dass das Leitungsorgan jedes Restrisiko persönlich akzeptiert - ohne unterschriebene Akzeptanz wird der Rest des Risikomanagements als nicht genehmigt behandelt.",
        nl: "CIR 2024/2690 Bijlage 2.1.1 vereist dat het leidinggevend orgaan elk restrisico persoonlijk accepteert - zonder ondertekende acceptatie wordt de rest van het risicobeheer als niet-goedgekeurd behandeld.",
        fr: "La CIR 2024/2690 Annexe 2.1.1 impose à l'organe de direction d'accepter personnellement chaque risque résiduel : sans l'acceptation signée, le reste de la gestion des risques est considéré comme non approuvé.",
        it: "La CIR 2024/2690 Allegato 2.1.1 richiede che l'organo di gestione accetti personalmente ciascun rischio residuo: senza l'accettazione firmata, il resto della gestione dei rischi è considerato non approvato.",
        es: "La CIR 2024/2690 Anexo 2.1.1 exige que el órgano de dirección acepte personalmente cada riesgo residual: sin la aceptación firmada, el resto de la gestión de riesgos se considera no aprobado.",
        pl: "CIR 2024/2690 załącznik 2.1.1 wymaga, aby organ zarządzający osobiście zaakceptował każde ryzyko rezydualne: bez podpisanej akceptacji pozostała część zarządzania ryzykiem jest traktowana jako niezatwierdzona.",
      },
    },
    {
      id: "2.3.3",
      question: {
        en: "Who sets the risk appetite - the level of risk the company is willing to live with?",
        de: "Wer legt den Risikoappetit fest - das Risikoniveau, das das Unternehmen bereit ist zu tragen?",
        nl: "Wie stelt de risicobereidheid vast - het risiconiveau dat het bedrijf bereid is te accepteren?",
        fr: "Qui définit l'appétence au risque, c'est-à-dire le niveau de risque que l'entreprise est prête à accepter ?",
        it: "Chi definisce la propensione al rischio, ovvero il livello di rischio che l'impresa è disposta ad accettare?",
        es: "¿Quién establece el apetito de riesgo, es decir, el nivel de riesgo que la empresa está dispuesta a asumir?",
        pl: "Kto ustala apetyt na ryzyko, czyli poziom ryzyka, który firma jest gotowa zaakceptować?",
      },
      options: [
        { en: "The CISO", de: "Der CISO", nl: "De CISO", fr: "Le CISO", it: "Il CISO", es: "El CISO", pl: "CISO" },
        { en: "The auditor", de: "Der Auditor", nl: "De auditor", fr: "L'auditeur", it: "Il revisore", es: "El auditor", pl: "Audytor" },
        { en: "The CEO / management body", de: "Der CEO / die Geschäftsleitung", nl: "De CEO / het bestuur", fr: "Le dirigeant / l'organe de direction", it: "L'amministratore delegato / l'organo di gestione", es: "El director general / el órgano de dirección", pl: "Dyrektor generalny / organ zarządzający" },
        { en: "The IT department", de: "Die IT-Abteilung", nl: "De IT-afdeling", fr: "Le service informatique", it: "Il reparto IT", es: "El departamento de TI", pl: "Dział IT" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The risk appetite is the CEO's boundary, not the CISO's - it must be written down so the CISO can operate within it.",
        de: "Der Risikoappetit ist die Vorgabe des CEO, nicht des CISO - er muss schriftlich festgehalten werden, damit der CISO innerhalb dieses Rahmens handeln kann.",
        nl: "De risicobereidheid is de grens van de CEO, niet die van de CISO - die moet schriftelijk worden vastgelegd zodat de CISO er binnen kan opereren.",
        fr: "L'appétence au risque est la limite fixée par le dirigeant, pas par le CISO : elle doit être consignée par écrit pour que le CISO puisse agir dans ce cadre.",
        it: "La propensione al rischio è il limite fissato dall'amministratore delegato, non dal CISO: deve essere messa per iscritto affinché il CISO possa operare entro tale ambito.",
        es: "El apetito de riesgo es el límite que fija el director general, no el CISO: debe ponerse por escrito para que el CISO pueda operar dentro de él.",
        pl: "Apetyt na ryzyko to granica wyznaczona przez dyrektora generalnego, a nie przez CISO: musi zostać spisana, aby CISO mógł działać w jej ramach.",
      },
    },
    {
      id: "2.3.4",
      question: {
        en: "Why are 'transfer' and 'accept' rarely defensible for serious risks under NIS2?",
        de: "Warum sind 'Übertragen' und 'Akzeptieren' bei schwerwiegenden Risiken unter NIS2 selten vertretbar?",
        nl: "Waarom zijn 'overdragen' en 'accepteren' zelden verdedigbaar voor ernstige risico's onder NIS2?",
        fr: "Pourquoi le 'transfert' et l'« acceptation » sont-ils rarement défendables pour les risques sérieux au titre de NIS2 ?",
        it: "Perché 'trasferire' e 'accettare' sono raramente difendibili per i rischi gravi ai sensi di NIS2?",
        es: "¿Por qué 'transferir' y 'aceptar' rara vez son defendibles para los riesgos graves en virtud de NIS2?",
        pl: "Dlaczego 'przeniesienie' i 'akceptacja' rzadko dają się obronić w przypadku poważnych ryzyk na podstawie NIS2?",
      },
      options: [
        { en: "Because insurance is too expensive for NIS2 entities", de: "Weil Versicherungen für NIS2-Einrichtungen zu teuer sind", nl: "Omdat verzekeringen te duur zijn voor NIS2-entiteiten", fr: "Parce que l'assurance est trop coûteuse pour les entités NIS2", it: "Perché l'assicurazione è troppo costosa per i soggetti NIS2", es: "Porque el seguro es demasiado caro para las entidades NIS2", pl: "Ponieważ ubezpieczenie jest zbyt drogie dla podmiotów NIS2" },
        { en: "Because the regulator cares whether the service is running and controls are in place, not whether you are insured", de: "Weil es der Aufsichtsbehörde darum geht, ob der Dienst läuft und Maßnahmen umgesetzt sind, nicht ob Sie versichert sind", nl: "Omdat de toezichthouder wil weten of de dienst draait en de maatregelen aanwezig zijn, niet of u verzekerd bent", fr: "Parce que l'autorité de contrôle se soucie de savoir si le service fonctionne et si les contrôles sont en place, pas de savoir si vous êtes assuré", it: "Perché all'autorità di vigilanza interessa se il servizio è operativo e i controlli sono in atto, non se siete assicurati", es: "Porque a la autoridad reguladora le importa si el servicio está funcionando y los controles están implantados, no si está asegurado", pl: "Ponieważ organowi nadzoru zależy na tym, czy usługa działa i czy kontrole są wdrożone, a nie na tym, czy są Państwo ubezpieczeni" },
        { en: "Because only the CISO can decide to transfer or accept a risk", de: "Weil nur der CISO entscheiden kann, ein Risiko zu übertragen oder zu akzeptieren", nl: "Omdat alleen de CISO kan beslissen een risico over te dragen of te accepteren", fr: "Parce que seul le CISO peut décider de transférer ou d'accepter un risque", it: "Perché solo il CISO può decidere di trasferire o accettare un rischio", es: "Porque solo el CISO puede decidir transferir o aceptar un riesgo", pl: "Ponieważ tylko CISO może zdecydować o przeniesieniu lub zaakceptowaniu ryzyka" },
        { en: "Because the CIR explicitly bans both options", de: "Weil die CIR beide Optionen ausdrücklich verbietet", nl: "Omdat de CIR beide opties uitdrukkelijk verbiedt", fr: "Parce que la CIR interdit explicitement les deux options", it: "Perché la CIR vieta esplicitamente entrambe le opzioni", es: "Porque la CIR prohíbe explícitamente ambas opciones", pl: "Ponieważ CIR wyraźnie zakazuje obu opcji" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The regulator does not care that you are insured - they care whether the service is running and the controls are in place.",
        de: "Der Aufsichtsbehörde ist es gleichgültig, ob Sie versichert sind - sie prüft, ob der Dienst funktioniert und die Maßnahmen umgesetzt sind.",
        nl: "De toezichthouder geeft er niet om of u verzekerd bent - zij controleren of de dienst functioneert en de maatregelen van kracht zijn.",
        fr: "L'autorité de contrôle ne se soucie pas de savoir si vous êtes assuré : elle vérifie si le service fonctionne et si les contrôles sont en place.",
        it: "All'autorità di vigilanza non interessa se siete assicurati: verifica se il servizio è operativo e i controlli sono in atto.",
        es: "A la autoridad reguladora no le importa si está asegurado: comprueba si el servicio está funcionando y los controles están implantados.",
        pl: "Organowi nadzoru nie zależy na tym, czy są Państwo ubezpieczeni: sprawdza, czy usługa działa i czy kontrole są wdrożone.",
      },
    },
  ],
});

export default quiz;
