import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.5",
  passingScore: 75,
  questions: [
    {
      id: "2.5.1",
      question: {
        en: "What are the three components of the CIA triad?",
        de: "Was sind die drei Komponenten der CIA-Triade?",
        nl: "Wat zijn de drie componenten van de CIA-triade?",
        fr: "Quels sont les trois composants de la triade CIA ?",
        it: "Quali sono i tre componenti della triade CIA?",
        es: "¿Cuáles son los tres componentes de la triada CIA?",
        pl: "Jakie są trzy komponenty triady CIA?",
        cs: "Jaké jsou tři složky triády CIA?",
        pt: "Quais são os três componentes da tríade CIA?",
        ro: "Care sunt cele trei componente ale triadei CIA?",
      },
      options: [
        { en: "Cost, implementation, availability", de: "Kosten, Implementierung, Verfügbarkeit", nl: "Kosten, implementatie, beschikbaarheid", fr: "Coût, mise en œuvre, disponibilité", it: "Costo, attuazione, disponibilità", es: "Coste, implementación, disponibilidad", pl: "Koszt, wdrożenie, dostępność", cs: "Náklady, zavedení, dostupnost", pt: "Custo, implementação, disponibilidade", ro: "Cost, implementare, disponibilitate" },
        { en: "Confidentiality, integrity, availability", de: "Vertraulichkeit, Integrität, Verfügbarkeit", nl: "Vertrouwelijkheid, integriteit, beschikbaarheid", fr: "Confidentialité, intégrité, disponibilité", it: "Riservatezza, integrità, disponibilità", es: "Confidencialidad, integridad, disponibilidad", pl: "Poufność, integralność, dostępność", cs: "Důvěrnost, integrita, dostupnost", pt: "Confidencialidade, integridade, disponibilidade", ro: "Confidențialitate, integritate, disponibilitate" },
        { en: "Compliance, insurance, accountability", de: "Compliance, Versicherung, Verantwortlichkeit", nl: "Naleving, verzekering, verantwoordelijkheid", fr: "Conformité, assurance, responsabilité", it: "Conformità, assicurazione, responsabilità", es: "Cumplimiento, seguro, rendición de cuentas", pl: "Zgodność, ubezpieczenie, rozliczalność", cs: "Soulad, pojištění, odpovědnost", pt: "Conformidade, seguro, responsabilização", ro: "Conformitate, asigurare, responsabilizare" },
        { en: "Continuity, incident response, auditing", de: "Kontinuität, Incident Response, Auditierung", nl: "Continuïteit, incidentrespons, auditing", fr: "Continuité, réponse aux incidents, audit", it: "Continuità, risposta agli incidenti, audit", es: "Continuidad, respuesta a incidentes, auditoría", pl: "Ciągłość, reagowanie na incydenty, audyt", cs: "Kontinuita, reakce na incidenty, audit", pt: "Continuidade, resposta a incidentes, auditoria", ro: "Continuitate, răspuns la incidente, audit" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The CIA triad is confidentiality (data only accessible to authorised people), integrity (data is accurate and untampered), and availability (systems are accessible when needed).",
        de: "Die CIA-Triade besteht aus Vertraulichkeit (Daten nur für berechtigte Personen zugänglich), Integrität (Daten sind korrekt und unverändert) und Verfügbarkeit (Systeme sind bei Bedarf erreichbar).",
        nl: "De CIA-triade bestaat uit vertrouwelijkheid (gegevens alleen toegankelijk voor bevoegden), integriteit (gegevens zijn juist en ongewijzigd) en beschikbaarheid (systemen zijn bereikbaar wanneer nodig).",
        fr: "La triade CIA est la confidentialité (données accessibles uniquement aux personnes autorisées), l'intégrité (les données sont exactes et non altérées) et la disponibilité (les systèmes sont accessibles en cas de besoin).",
        it: "La triade CIA è riservatezza (dati accessibili solo alle persone autorizzate), integrità (i dati sono accurati e non manomessi) e disponibilità (i sistemi sono accessibili quando necessario).",
        es: "La triada CIA es confidencialidad (datos accesibles únicamente para las personas autorizadas), integridad (los datos son exactos y no han sido manipulados) y disponibilidad (los sistemas son accesibles cuando se necesitan).",
        pl: "Triada CIA to poufność (dane dostępne wyłącznie dla osób upoważnionych), integralność (dane są dokładne i nienaruszone) oraz dostępność (systemy są dostępne, gdy są potrzebne).",
        cs: "Triáda CIA je důvěrnost (data dostupná pouze oprávněným osobám), integrita (data jsou přesná a nepozměněná) a dostupnost (systémy jsou přístupné, když jsou potřeba).",
        pt: "A tríade CIA é a confidencialidade (os dados só são acessíveis a pessoas autorizadas), a integridade (os dados são exatos e não adulterados) e a disponibilidade (os sistemas estão acessíveis quando necessário).",
        ro: "Triada CIA este confidențialitatea (datele sunt accesibile doar persoanelor autorizate), integritatea (datele sunt exacte și nealterate) și disponibilitatea (sistemele sunt accesibile când este nevoie).",
      },
    },
    {
      id: "2.5.2",
      question: {
        en: "What is the purpose of a business impact analysis (BIA)?",
        de: "Wozu dient eine Business Impact Analyse (BIA)?",
        nl: "Wat is het doel van een business impact analyse (BIA)?",
        fr: "Quel est l'objectif d'une analyse d'impact sur l'activité (BIA) ?",
        it: "Qual è lo scopo di un'analisi di impatto sul business (BIA)?",
        es: "¿Cuál es el propósito de un análisis de impacto en el negocio (BIA)?",
        pl: "Jaki jest cel analizy wpływu na działalność (BIA)?",
        cs: "Jaký je účel analýzy dopadů na podnikání (BIA)?",
        pt: "Qual é o objetivo de uma análise de impacto no negócio (BIA)?",
        ro: "Care este scopul unei analize a impactului asupra activității (BIA)?",
      },
      options: [
        { en: "To calculate the company's annual revenue", de: "Zur Berechnung des Jahresumsatzes des Unternehmens", nl: "Om de jaarlijkse omzet van het bedrijf te berekenen", fr: "Calculer le chiffre d'affaires annuel de l'entreprise", it: "Calcolare il fatturato annuo dell'impresa", es: "Calcular la facturación anual de la empresa", pl: "Obliczenie rocznego przychodu firmy", cs: "Vypočítat roční tržby společnosti", pt: "Calcular a receita anual da empresa", ro: "Calcularea venitului anual al companiei" },
        { en: "To translate technical risk categories into business numbers for each critical asset", de: "Zur Übersetzung technischer Risikokategorien in betriebswirtschaftliche Kennzahlen für jedes kritische Asset", nl: "Om technische risicocategorieën te vertalen naar bedrijfscijfers voor elk kritiek asset", fr: "Traduire les catégories de risques techniques en chiffres métier pour chaque actif critique", it: "Tradurre le categorie di rischio tecnico in dati aziendali per ciascun asset critico", es: "Traducir las categorías de riesgo técnico en cifras de negocio para cada activo crítico", pl: "Przełożenie technicznych kategorii ryzyka na liczby biznesowe dla każdego krytycznego zasobu", cs: "Převést technické kategorie rizik na podnikové údaje pro každé kritické aktivum", pt: "Traduzir as categorias técnicas de risco em números de negócio para cada ativo crítico", ro: "Transpunerea categoriilor tehnice de risc în cifre de afaceri pentru fiecare activ critic" },
        { en: "To replace the risk matrix with financial projections", de: "Zum Ersetzen der Risikomatrix durch Finanzprognosen", nl: "Om de risicomatrix te vervangen door financiële prognoses", fr: "Remplacer la matrice des risques par des projections financières", it: "Sostituire la matrice dei rischi con proiezioni finanziarie", es: "Sustituir la matriz de riesgos por proyecciones financieras", pl: "Zastąpienie macierzy ryzyka prognozami finansowymi", cs: "Nahradit matici rizik finančními prognózami", pt: "Substituir a matriz de risco por projeções financeiras", ro: "Înlocuirea matricei de risc cu proiecții financiare" },
        { en: "To assign blame after a security incident", de: "Zur Schuldzuweisung nach einem Sicherheitsvorfall", nl: "Om verantwoordelijkheid toe te wijzen na een beveiligingsincident", fr: "Attribuer les responsabilités après un incident de sécurité", it: "Attribuire le colpe dopo un incidente di sicurezza", es: "Atribuir la culpa después de un incidente de seguridad", pl: "Przypisanie winy po incydencie bezpieczeństwa", cs: "Určit viníka po bezpečnostním incidentu", pt: "Atribuir culpas após um incidente de segurança", ro: "Atribuirea vinovăției după un incident de securitate" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The BIA translates CIA categories into business numbers - recovery targets and business consequences - making the risk matrix actionable.",
        de: "Die BIA übersetzt CIA-Kategorien in betriebswirtschaftliche Kennzahlen - Wiederherstellungsziele und geschäftliche Auswirkungen - und macht die Risikomatrix handlungsfähig.",
        nl: "De BIA vertaalt CIA-categorieën naar bedrijfscijfers - hersteldoelstellingen en bedrijfsgevolgen - waardoor de risicomatrix uitvoerbaar wordt.",
        fr: "La BIA traduit les catégories CIA en chiffres métier - objectifs de rétablissement et conséquences pour l'activité - rendant la matrice des risques exploitable.",
        it: "La BIA traduce le categorie CIA in dati aziendali - obiettivi di ripristino e conseguenze per l'attività - rendendo la matrice dei rischi operativa.",
        es: "La BIA traduce las categorías CIA en cifras de negocio - objetivos de recuperación y consecuencias para la actividad - haciendo que la matriz de riesgos sea accionable.",
        pl: "BIA przekłada kategorie CIA na liczby biznesowe - cele odtworzenia i konsekwencje biznesowe - dzięki czemu macierz ryzyka staje się użyteczna w działaniu.",
        cs: "BIA převádí kategorie CIA na podnikové údaje, cíle obnovy a podnikové důsledky, čímž činí matici rizik použitelnou.",
        pt: "A BIA traduz as categorias CIA em números de negócio, objetivos de recuperação e consequências para o negócio, tornando a matriz de risco operacional.",
        ro: "BIA transpune categoriile CIA în cifre de afaceri, ținte de recuperare și consecințe pentru activitate, făcând matricea de risc operațională.",
      },
    },
    {
      id: "2.5.3",
      question: {
        en: "What is the management body's specific role regarding the BIA?",
        de: "Welche konkrete Rolle hat die Geschäftsleitung bei der BIA?",
        nl: "Wat is de specifieke rol van het bestuur met betrekking tot de BIA?",
        fr: "Quel est le rôle spécifique de l'organe de direction à l'égard de la BIA ?",
        it: "Qual è il ruolo specifico dell'organo di gestione riguardo alla BIA?",
        es: "¿Cuál es el papel específico del órgano de dirección con respecto a la BIA?",
        pl: "Jaka jest konkretna rola organu zarządzającego w odniesieniu do BIA?",
        cs: "Jaká je konkrétní role řídicího orgánu ve vztahu k BIA?",
        pt: "Qual é o papel específico do órgão de administração em relação à BIA?",
        ro: "Care este rolul specific al organului de conducere în legătură cu BIA?",
      },
      options: [
        { en: "To perform the technical analysis themselves", de: "Die technische Analyse selbst durchzuführen", nl: "De technische analyse zelf uitvoeren", fr: "Réaliser elle-même l'analyse technique", it: "Eseguire personalmente l'analisi tecnica", es: "Realizar el análisis técnico por sí mismo", pl: "Samodzielne przeprowadzenie analizy technicznej", cs: "Provádět technickou analýzu sám", pt: "Realizar pessoalmente a análise técnica", ro: "Să efectueze el însuși analiza tehnică" },
        { en: "To delegate it entirely to the CISO without review", de: "Sie vollständig an den CISO zu delegieren ohne Überprüfung", nl: "Het volledig delegeren aan de CISO zonder beoordeling", fr: "La déléguer entièrement au CISO sans réexamen", it: "Delegarla interamente al CISO senza riesame", es: "Delegarla por completo en el CISO sin revisión", pl: "Całkowite delegowanie jej CISO bez przeglądu", cs: "Zcela ji delegovat na CISO bez přezkumu", pt: "Delegá-la inteiramente no CISO sem revisão", ro: "Să o delege integral către CISO fără revizuire" },
        { en: "To validate the business assumptions in the BIA", de: "Die betriebswirtschaftlichen Annahmen in der BIA zu validieren", nl: "De bedrijfsaannames in de BIA valideren", fr: "Valider les hypothèses métier de la BIA", it: "Convalidare le ipotesi aziendali della BIA", es: "Validar las hipótesis de negocio de la BIA", pl: "Walidacja założeń biznesowych w BIA", cs: "Ověřit podnikové předpoklady v BIA", pt: "Validar os pressupostos de negócio na BIA", ro: "Să valideze ipotezele de afaceri din BIA" },
        { en: "To sign it without reading it", de: "Sie zu unterschreiben ohne sie zu lesen", nl: "Het ondertekenen zonder het te lezen", fr: "La signer sans la lire", it: "Firmarla senza leggerla", es: "Firmarla sin leerla", pl: "Podpisanie jej bez przeczytania", cs: "Podepsat ji, aniž by ji četl", pt: "Assiná-la sem a ler", ro: "Să o semneze fără a o citi" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The CEO's role is to validate the business assumptions - only the management body has the business context to check whether recovery targets match what the company can survive.",
        de: "Die Rolle des CEO ist die Validierung der betriebswirtschaftlichen Annahmen - nur die Geschäftsleitung hat den geschäftlichen Kontext, um zu prüfen, ob die Wiederherstellungsziele dem entsprechen, was das Unternehmen überstehen kann.",
        nl: "De rol van de CEO is het valideren van de bedrijfsaannames - alleen het bestuur heeft de bedrijfscontext om te controleren of de hersteldoelstellingen overeenkomen met wat het bedrijf kan overleven.",
        fr: "Le rôle du dirigeant est de valider les hypothèses métier : seul l'organe de direction dispose du contexte commercial nécessaire pour vérifier que les objectifs de rétablissement correspondent à ce que l'entreprise peut supporter.",
        it: "Il ruolo dell'amministratore delegato è convalidare le ipotesi aziendali: solo l'organo di gestione possiede il contesto aziendale per verificare che gli obiettivi di ripristino corrispondano a ciò a cui l'impresa può sopravvivere.",
        es: "El papel del director general es validar las hipótesis de negocio: solo el órgano de dirección tiene el contexto empresarial para comprobar si los objetivos de recuperación se ajustan a lo que la empresa puede soportar.",
        pl: "Rolą dyrektora generalnego jest walidacja założeń biznesowych: tylko organ zarządzający ma kontekst biznesowy, aby sprawdzić, czy cele odtworzenia odpowiadają temu, co firma jest w stanie przetrwać.",
        cs: "Úkolem generálního ředitele je ověřit podnikové předpoklady. Pouze řídicí orgán má podnikový kontext k tomu, aby zkontroloval, zda cíle obnovy odpovídají tomu, co společnost přežije.",
        pt: "O papel do diretor executivo é validar os pressupostos de negócio. Só o órgão de administração tem o contexto de negócio para verificar se os objetivos de recuperação correspondem àquilo a que a empresa consegue sobreviver.",
        ro: "Rolul directorului general este de a valida ipotezele de afaceri. Doar organul de conducere are contextul de afaceri pentru a verifica dacă țintele de recuperare corespund cu ceea ce poate supraviețui compania.",
      },
    },
    {
      id: "2.5.4",
      question: {
        en: "According to the lesson, what happens to risk matrix scores without a BIA?",
        de: "Was passiert laut der Lektion mit den Bewertungen der Risikomatrix ohne eine BIA?",
        nl: "Wat gebeurt er volgens de les met risicomatrixscores zonder een BIA?",
        fr: "Selon la leçon, qu'advient-il des scores de la matrice des risques en l'absence de BIA ?",
        it: "Secondo la lezione, cosa accade ai punteggi della matrice dei rischi in assenza di una BIA?",
        es: "Según la lección, ¿qué ocurre con las puntuaciones de la matriz de riesgos sin una BIA?",
        pl: "Według lekcji, co dzieje się z ocenami macierzy ryzyka bez BIA?",
        cs: "Co se podle lekce stane se skóre matice rizik bez BIA?",
        pt: "Segundo a lição, o que acontece às pontuações da matriz de risco sem uma BIA?",
        ro: "Potrivit lecției, ce se întâmplă cu scorurile matricei de risc fără o BIA?",
      },
      options: [
        { en: "They become legally binding", de: "Sie werden rechtlich bindend", nl: "Ze worden juridisch bindend", fr: "Ils deviennent juridiquement contraignants", it: "Diventano giuridicamente vincolanti", es: "Se vuelven jurídicamente vinculantes", pl: "Stają się prawnie wiążące", cs: "Stávají se právně závaznými", pt: "Tornam-se juridicamente vinculativas", ro: "Devin obligatorii din punct de vedere juridic" },
        { en: "They remain accurate but incomplete", de: "Sie bleiben korrekt, aber unvollständig", nl: "Ze blijven nauwkeurig maar onvolledig", fr: "Ils restent exacts mais incomplets", it: "Rimangono accurati ma incompleti", es: "Siguen siendo exactos pero incompletos", pl: "Pozostają dokładne, lecz niekompletne", cs: "Zůstávají přesné, ale neúplné", pt: "Mantêm-se exatas mas incompletas", ro: "Rămân exacte, dar incomplete" },
        { en: "They are guesses", de: "Sie sind Schätzungen", nl: "Het zijn schattingen", fr: "Ce sont des estimations approximatives", it: "Sono delle congetture", es: "Son meras conjeturas", pl: "Są zgadywaniem", cs: "Jsou to odhady", pt: "São suposições", ro: "Sunt presupuneri" },
        { en: "They are automatically generated by the auditor", de: "Sie werden automatisch vom Auditor generiert", nl: "Ze worden automatisch gegenereerd door de auditor", fr: "Ils sont générés automatiquement par l'auditeur", it: "Vengono generati automaticamente dal revisore", es: "Los genera automáticamente el auditor", pl: "Są generowane automatycznie przez audytora", cs: "Generuje je automaticky auditor", pt: "São geradas automaticamente pelo auditor", ro: "Sunt generate automat de auditor" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Without business-impact numbers attached to each asset, the risk matrix scores are guesses - the BIA is what makes the matrix actionable.",
        de: "Ohne betriebswirtschaftliche Auswirkungszahlen für jedes Asset sind die Bewertungen der Risikomatrix Schätzungen - die BIA macht die Matrix erst handlungsfähig.",
        nl: "Zonder bedrijfsimpactcijfers gekoppeld aan elk asset zijn de risicomatrixscores schattingen - de BIA is wat de matrix uitvoerbaar maakt.",
        fr: "Sans chiffres d'impact métier rattachés à chaque actif, les scores de la matrice des risques sont des estimations approximatives : c'est la BIA qui rend la matrice exploitable.",
        it: "Senza dati di impatto aziendale associati a ciascun asset, i punteggi della matrice dei rischi sono congetture: è la BIA a rendere la matrice operativa.",
        es: "Sin cifras de impacto en el negocio asociadas a cada activo, las puntuaciones de la matriz de riesgos son conjeturas: es la BIA la que hace que la matriz sea accionable.",
        pl: "Bez liczb dotyczących wpływu biznesowego przypisanych do każdego zasobu oceny macierzy ryzyka są zgadywaniem: to BIA sprawia, że macierz staje się użyteczna w działaniu.",
        cs: "Bez údajů o dopadu na podnikání připojených ke každému aktivu jsou skóre matice rizik jen odhady. Použitelnou matici dělá teprve BIA.",
        pt: "Sem números de impacto no negócio associados a cada ativo, as pontuações da matriz de risco são suposições. É a BIA que torna a matriz operacional.",
        ro: "Fără cifre privind impactul asupra activității asociate fiecărui activ, scorurile matricei de risc sunt presupuneri. BIA este cea care face matricea operațională.",
      },
    },
  ],
});

export default quiz;
