import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.6",
  passingScore: 75,
  questions: [
    {
      id: "2.6.1",
      question: {
        en: "How many distinct policies does the CIR require for Measure 1?",
        de: "Wie viele separate Richtlinien verlangt die CIR für Maßnahme 1?",
        nl: "Hoeveel afzonderlijke beleidslijnen vereist de CIR voor Maatregel 1?",
        fr: "Combien de politiques distinctes la CIR exige-t-elle pour la mesure 1 ?",
        it: "Quante politiche distinte richiede la CIR per la misura 1?",
        es: "¿Cuántas políticas distintas exige la CIR para la medida 1?",
        pl: "Ile odrębnych polityk wymaga CIR dla środka 1?",
        cs: "Kolik samostatných politik vyžaduje CIR pro opatření 1?",
        pt: "Quantas políticas distintas exige o CIR para a Medida 1?",
        ro: "Câte politici distincte impune CIR pentru Măsura 1?",
      },
      options: [
        { en: "One comprehensive security policy", de: "Eine umfassende Sicherheitsrichtlinie", nl: "Één uitgebreid beveiligingsbeleid", fr: "Une politique de sécurité globale", it: "Un'unica politica di sicurezza completa", es: "Una política de seguridad integral", pl: "Jedną kompleksową politykę bezpieczeństwa", cs: "Jednu komplexní bezpečnostní politiku", pt: "Uma política de segurança abrangente", ro: "O politică de securitate cuprinzătoare" },
        { en: "Five core policies", de: "Fünf Kernrichtlinien", nl: "Vijf kernbeleidslijnen", fr: "Cinq politiques fondamentales", it: "Cinque politiche fondamentali", es: "Cinco políticas fundamentales", pl: "Pięć podstawowych polityk", cs: "Pět základních politik", pt: "Cinco políticas fundamentais", ro: "Cinci politici de bază" },
        { en: "Eleven (one top-level plus ten topic-specific)", de: "Elf (eine übergeordnete plus zehn themenspezifische)", nl: "Elf (één overkoepelend plus tien onderwerpspecifieke)", fr: "Onze (une de haut niveau plus dix thématiques)", it: "Undici (una di livello superiore più dieci tematiche)", es: "Once (una de nivel superior más diez temáticas)", pl: "Jedenaście (jedną nadrzędną plus dziesięć tematycznych)", cs: "Jedenáct (jednu nadřazenou a deset tematických)", pt: "Onze (uma de nível superior mais dez específicas por tema)", ro: "Unsprezece (una de nivel superior plus zece specifice pe teme)" },
        { en: "Three (risk, incident, access)", de: "Drei (Risiko, Vorfall, Zugang)", nl: "Drie (risico, incident, toegang)", fr: "Trois (risque, incident, accès)", it: "Tre (rischio, incidente, accesso)", es: "Tres (riesgo, incidente, acceso)", pl: "Trzy (ryzyko, incydent, dostęp)", cs: "Tři (riziko, incident, přístup)", pt: "Três (risco, incidente, acesso)", ro: "Trei (risc, incident, acces)" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The CIR requires a top-level information security policy plus ten topic-specific policies - eleven in total.",
        de: "Die CIR verlangt eine übergeordnete Informationssicherheitsrichtlinie plus zehn themenspezifische Richtlinien - insgesamt elf.",
        nl: "De CIR vereist één overkoepelend informatiebeveiligingsbeleid plus tien onderwerpspecifieke beleidslijnen - elf in totaal.",
        fr: "La CIR exige une politique de sécurité de l'information de haut niveau plus dix politiques thématiques, soit onze au total.",
        it: "La CIR richiede una politica di sicurezza delle informazioni di livello superiore più dieci politiche tematiche, undici in totale.",
        es: "La CIR exige una política de seguridad de la información de nivel superior más diez políticas temáticas, once en total.",
        pl: "CIR wymaga nadrzędnej polityki bezpieczeństwa informacji plus dziesięciu polityk tematycznych - łącznie jedenastu.",
        cs: "CIR vyžaduje nadřazenou politiku bezpečnosti informací a deset tematických politik, celkem tedy jedenáct.",
        pt: "O CIR exige uma política de segurança da informação de nível superior mais dez políticas específicas por tema, onze no total.",
        ro: "CIR impune o politică de securitate a informației de nivel superior plus zece politici specifice pe teme, unsprezece în total.",
      },
    },
    {
      id: "2.6.2",
      question: {
        en: "Which three CIR Annex topic-specific policies does this lesson call out as worth double-checking?",
        de: "Welche drei DVO-Anhang-Spezialrichtlinien hebt diese Lektion zur Gegenkontrolle hervor?",
        nl: "Welke drie CIR-bijlage onderwerpspecifieke beleidsregels noemt deze les expliciet om dubbel te controleren?",
        fr: "Quelles sont les trois politiques thématiques de l'Annexe de la CIR que cette leçon signale comme méritant une double vérification ?",
        it: "Quali tre politiche tematiche dell'Allegato della CIR questa lezione segnala come meritevoli di una doppia verifica?",
        es: "¿Qué tres políticas temáticas del Anexo de la CIR señala esta lección como dignas de una doble comprobación?",
        pl: "Które trzy tematyczne polityki z załącznika CIR ta lekcja wskazuje jako warte podwójnego sprawdzenia?",
        cs: "Které tři tematické politiky z přílohy CIR tato lekce označuje za vhodné dvojí kontroly?",
        pt: "Que três políticas específicas por tema do Anexo do CIR destaca esta lição como merecedoras de dupla verificação?",
        ro: "Care trei politici specifice pe teme din Anexa CIR sunt evidențiate de această lecție ca meritând o verificare suplimentară?",
      },
      options: [
        { en: "Risk management, incident handling, access control", de: "Risikomanagement, Vorfallbehandlung, Zugangskontrolle", nl: "Risicobeheer, incidentbeheer, toegangscontrole", fr: "Gestion des risques, traitement des incidents, contrôle d'accès", it: "Gestione dei rischi, gestione degli incidenti, controllo degli accessi", es: "Gestión de riesgos, gestión de incidentes, control de acceso", pl: "Zarządzanie ryzykiem, obsługa incydentów, kontrola dostępu", cs: "Řízení rizik, řešení incidentů, řízení přístupu", pt: "Gestão de riscos, tratamento de incidentes, controlo de acessos", ro: "Gestionarea riscurilor, tratarea incidentelor, controlul accesului" },
        { en: "Security testing, privileged accounts, removable media", de: "Sicherheitstests, privilegierte Konten, Wechseldatenträger", nl: "Beveiligingstests, geprivilegieerde accounts, verwijderbare media", fr: "Tests de sécurité, comptes à privilèges, supports amovibles", it: "Test di sicurezza, account con privilegi, supporti rimovibili", es: "Pruebas de seguridad, cuentas con privilegios, soportes extraíbles", pl: "Testy bezpieczeństwa, konta uprzywilejowane, nośniki wymienne", cs: "Bezpečnostní testování, privilegované účty, vyměnitelná média", pt: "Testes de segurança, contas privilegiadas, suportes amovíveis", ro: "Testarea securității, conturi privilegiate, suporturi amovibile" },
        { en: "Cryptography, supply chain, effectiveness assessment", de: "Kryptografie, Supply Chain, Wirksamkeitsbewertung", nl: "Cryptografie, toeleveringsketen, effectiviteitsbeoordeling", fr: "Cryptographie, chaîne d'approvisionnement, évaluation de l'efficacité", it: "Crittografia, catena di approvvigionamento, valutazione dell'efficacia", es: "Criptografía, cadena de suministro, evaluación de la eficacia", pl: "Kryptografia, łańcuch dostaw, ocena skuteczności", cs: "Kryptografie, dodavatelský řetězec, posouzení účinnosti", pt: "Criptografia, cadeia de abastecimento, avaliação da eficácia", ro: "Criptografie, lanț de aprovizionare, evaluarea eficacității" },
        { en: "Backup, disaster recovery, crisis management", de: "Backup, Notfallwiederherstellung, Krisenmanagement", nl: "Back-up, herstel na rampen, crisismanagement", fr: "Sauvegarde, reprise après sinistre, gestion de crise", it: "Backup, ripristino di emergenza, gestione delle crisi", es: "Copia de seguridad, recuperación ante desastres, gestión de crisis", pl: "Kopie zapasowe, odtwarzanie po awarii, zarządzanie kryzysowe", cs: "Zálohování, obnova po havárii, krizové řízení", pt: "Cópia de segurança, recuperação de desastres, gestão de crises", ro: "Copii de rezervă, recuperare în caz de dezastru, gestionarea crizelor" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Security testing, privileged accounts, and removable media are three niche policies the CIR Annex explicitly requires - worth double-checking against an existing ISO policy set.",
        de: "Sicherheitstests, privilegierte Konten und Wechseldatenträger sind drei Nischenrichtlinien, die der DVO-Anhang explizit verlangt - bei einem bestehenden ISO-Richtlinienkanon zur Gegenkontrolle empfehlenswert.",
        nl: "Beveiligingstesten, geprivilegieerde accounts en verwijderbare media zijn drie nichebeleidsregels die de CIR-bijlage uitdrukkelijk vereist - aanbevolen om dubbel te controleren tegen een bestaande ISO-set.",
        fr: "Les tests de sécurité, les comptes à privilèges et les supports amovibles sont trois politiques de niche que l'Annexe de la CIR exige explicitement, à double vérifier par rapport à un ensemble de politiques ISO existant.",
        it: "I test di sicurezza, gli account con privilegi e i supporti rimovibili sono tre politiche di nicchia che l'Allegato della CIR richiede esplicitamente, da verificare due volte rispetto a un set di politiche ISO esistente.",
        es: "Las pruebas de seguridad, las cuentas con privilegios y los soportes extraíbles son tres políticas específicas que el Anexo de la CIR exige explícitamente, conviene comprobarlas dos veces frente a un conjunto de políticas ISO existente.",
        pl: "Testy bezpieczeństwa, konta uprzywilejowane i nośniki wymienne to trzy niszowe polityki, których załącznik CIR wyraźnie wymaga - warto je podwójnie sprawdzić względem istniejącego zestawu polityk ISO.",
        cs: "Bezpečnostní testování, privilegované účty a vyměnitelná média jsou tři specifické politiky, které příloha CIR výslovně vyžaduje. Stojí za to je dvakrát zkontrolovat oproti stávající sadě politik ISO.",
        pt: "Os testes de segurança, as contas privilegiadas e os suportes amovíveis são três políticas de nicho que o Anexo do CIR exige expressamente. Vale a pena verificá-las duplamente face a um conjunto de políticas ISO existente.",
        ro: "Testarea securității, conturile privilegiate și suporturile amovibile sunt trei politici de nișă pe care Anexa CIR le impune în mod expres. Merită verificate suplimentar față de un set de politici ISO existent.",
      },
    },
    {
      id: "2.6.3",
      question: {
        en: "What makes an undated or unsigned top-level policy the 'fastest path to an audit finding'?",
        de: "Warum ist eine undatierte oder nicht unterschriebene übergeordnete Richtlinie der 'schnellste Weg zu einer Audit-Feststellung'?",
        nl: "Waarom is een ongedateerd of niet-ondertekend overkoepelend beleid 'de snelste weg naar een auditbevinding'?",
        fr: "Pourquoi une politique de haut niveau non datée ou non signée est-elle 'le chemin le plus rapide vers une constatation d'audit' ?",
        it: "Perché una politica di livello superiore non datata o non firmata è 'la via più rapida verso un rilievo di audit'?",
        es: "¿Por qué una política de nivel superior sin fecha o sin firmar es 'el camino más rápido hacia un hallazgo de auditoría'?",
        pl: "Dlaczego niedatowana lub niepodpisana polityka nadrzędna jest „najszybszą drogą do ustalenia audytowego”?",
        cs: "Proč je nedatovaná nebo nepodepsaná nadřazená politika 'nejrychlejší cestou ke zjištění auditu'?",
        pt: "O que torna uma política de nível superior não datada ou não assinada o 'caminho mais rápido para uma constatação de auditoria'?",
        ro: "Ce face dintr-o politică de nivel superior nedatată sau nesemnată 'cea mai rapidă cale către o constatare de audit'?",
      },
      options: [
        { en: "It means the IT department forgot to file the paperwork", de: "Es bedeutet, dass die IT-Abteilung den Papierkram vergessen hat", nl: "Het betekent dat de IT-afdeling de papierwinkel is vergeten", fr: "Cela signifie que le service informatique a oublié de classer les documents", it: "Significa che il reparto IT ha dimenticato di archiviare la documentazione", es: "Significa que el departamento de TI olvidó archivar la documentación", pl: "Oznacza, że dział IT zapomniał zarejestrować dokumentację", cs: "Znamená to, že oddělení IT zapomnělo založit dokumentaci", pt: "Significa que o departamento de TI se esqueceu de arquivar a documentação", ro: "Înseamnă că departamentul IT a uitat să depună documentația" },
        { en: "It means the management body either did not approve the security approach or cannot prove they did", de: "Es bedeutet, dass die Geschäftsleitung den Sicherheitsansatz entweder nicht genehmigt hat oder dies nicht nachweisen kann", nl: "Het betekent dat het leidinggevend orgaan de beveiligingsaanpak niet heeft goedgekeurd of dit niet kan bewijzen", fr: "Cela signifie que l'organe de direction n'a pas approuvé l'approche de sécurité ou ne peut pas prouver qu'il l'a fait", it: "Significa che l'organo di gestione non ha approvato l'approccio alla sicurezza oppure non può dimostrare di averlo fatto", es: "Significa que el órgano de dirección o no aprobó el enfoque de seguridad o no puede demostrar que lo hizo", pl: "Oznacza, że organ zarządzający albo nie zatwierdził podejścia do bezpieczeństwa, albo nie może tego udowodnić", cs: "Znamená to, že řídicí orgán buď bezpečnostní přístup neschválil, nebo to nemůže prokázat", pt: "Significa que o órgão de administração ou não aprovou a abordagem de segurança ou não consegue provar que o fez", ro: "Înseamnă că organul de conducere fie nu a aprobat abordarea de securitate, fie nu poate dovedi că a făcut-o" },
        { en: "It means the policies are technically incorrect", de: "Es bedeutet, dass die Richtlinien fachlich falsch sind", nl: "Het betekent dat de beleidslijnen technisch onjuist zijn", fr: "Cela signifie que les politiques sont techniquement incorrectes", it: "Significa che le politiche sono tecnicamente errate", es: "Significa que las políticas son técnicamente incorrectas", pl: "Oznacza, że polityki są technicznie nieprawidłowe", cs: "Znamená to, že politiky jsou technicky nesprávné", pt: "Significa que as políticas estão tecnicamente incorretas", ro: "Înseamnă că politicile sunt incorecte din punct de vedere tehnic" },
        { en: "It means the auditor has to write a longer report", de: "Es bedeutet, dass der Auditor einen längeren Bericht schreiben muss", nl: "Het betekent dat de auditor een langer rapport moet schrijven", fr: "Cela signifie que l'auditeur doit rédiger un rapport plus long", it: "Significa che il revisore deve redigere un rapporto più lungo", es: "Significa que el auditor tiene que redactar un informe más largo", pl: "Oznacza, że audytor musi napisać dłuższy raport", cs: "Znamená to, že auditor musí napsat delší zprávu", pt: "Significa que o auditor tem de escrever um relatório mais longo", ro: "Înseamnă că auditorul trebuie să redacteze un raport mai lung" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The CIR requires the top-level policy to carry the date of formal approval by the management body - without it, the approval cannot be proven.",
        de: "Die CIR verlangt, dass die übergeordnete Richtlinie das Datum der formellen Genehmigung durch die Geschäftsleitung trägt - ohne dieses kann die Genehmigung nicht nachgewiesen werden.",
        nl: "De CIR vereist dat het overkoepelende beleid de datum van formele goedkeuring door het leidinggevend orgaan bevat - zonder die datum kan de goedkeuring niet worden aangetoond.",
        fr: "La CIR exige que la politique de haut niveau porte la date d'approbation formelle par l'organe de direction : sans elle, l'approbation ne peut pas être prouvée.",
        it: "La CIR richiede che la politica di livello superiore rechi la data di approvazione formale da parte dell'organo di gestione: senza di essa, l'approvazione non può essere dimostrata.",
        es: "La CIR exige que la política de nivel superior lleve la fecha de aprobación formal por parte del órgano de dirección: sin ella, no se puede demostrar la aprobación.",
        pl: "CIR wymaga, aby polityka nadrzędna zawierała datę formalnego zatwierdzenia przez organ zarządzający: bez niej zatwierdzenia nie można udowodnić.",
        cs: "CIR vyžaduje, aby nadřazená politika nesla datum formálního schválení řídicím orgánem. Bez něj nelze schválení prokázat.",
        pt: "O CIR exige que a política de nível superior contenha a data da aprovação formal pelo órgão de administração. Sem ela, a aprovação não pode ser provada.",
        ro: "CIR impune ca politica de nivel superior să poarte data aprobării formale de către organul de conducere. Fără aceasta, aprobarea nu poate fi dovedită.",
      },
    },
    {
      id: "2.6.4",
      question: {
        en: "How often must the top-level information security policy be reviewed?",
        de: "Wie oft muss die übergeordnete Informationssicherheitsrichtlinie überprüft werden?",
        nl: "Hoe vaak moet het overkoepelende informatiebeveiligingsbeleid worden herzien?",
        fr: "À quelle fréquence la politique de sécurité de l'information de haut niveau doit-elle être réexaminée ?",
        it: "Con quale frequenza deve essere riesaminata la politica di sicurezza delle informazioni di livello superiore?",
        es: "¿Con qué frecuencia debe revisarse la política de seguridad de la información de nivel superior?",
        pl: "Jak często należy przeglądać nadrzędną politykę bezpieczeństwa informacji?",
        cs: "Jak často se musí přezkoumávat nadřazená politika bezpečnosti informací?",
        pt: "Com que frequência tem de ser revista a política de segurança da informação de nível superior?",
        ro: "Cât de des trebuie revizuită politica de securitate a informației de nivel superior?",
      },
      options: [
        { en: "Every six months", de: "Alle sechs Monate", nl: "Elke zes maanden", fr: "Tous les six mois", it: "Ogni sei mesi", es: "Cada seis meses", pl: "Co sześć miesięcy", cs: "Každých šest měsíců", pt: "De seis em seis meses", ro: "O dată la șase luni" },
        { en: "Annually", de: "Jährlich", nl: "Jaarlijks", fr: "Chaque année", it: "Annualmente", es: "Anualmente", pl: "Co roku", cs: "Ročně", pt: "Anualmente", ro: "Anual" },
        { en: "Every two years", de: "Alle zwei Jahre", nl: "Elke twee jaar", fr: "Tous les deux ans", it: "Ogni due anni", es: "Cada dos años", pl: "Co dwa lata", cs: "Každé dva roky", pt: "De dois em dois anos", ro: "O dată la doi ani" },
        { en: "Only when a breach occurs", de: "Nur bei einem Sicherheitsvorfall", nl: "Alleen na een incident", fr: "Uniquement en cas de violation", it: "Solo quando si verifica una violazione", es: "Solo cuando se produce una brecha", pl: "Tylko gdy dojdzie do naruszenia", cs: "Pouze když dojde k narušení", pt: "Apenas quando ocorre uma violação", ro: "Doar când survine o breșă" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The top-level policy must be reviewed annually with a dated management body approval.",
        de: "Die übergeordnete Richtlinie muss jährlich überprüft werden, mit datierter Genehmigung durch die Geschäftsleitung.",
        nl: "Het overkoepelende beleid moet jaarlijks worden herzien met een gedateerde goedkeuring van het leidinggevend orgaan.",
        fr: "La politique de haut niveau doit être réexaminée chaque année avec une approbation datée de l'organe de direction.",
        it: "La politica di livello superiore deve essere riesaminata annualmente con un'approvazione datata dell'organo di gestione.",
        es: "La política de nivel superior debe revisarse anualmente con una aprobación fechada del órgano de dirección.",
        pl: "Politykę nadrzędną należy przeglądać co roku, wraz z datowanym zatwierdzeniem przez organ zarządzający.",
        cs: "Nadřazená politika se musí přezkoumávat ročně s datovaným schválením řídicím orgánem.",
        pt: "A política de nível superior tem de ser revista anualmente com uma aprovação datada do órgão de administração.",
        ro: "Politica de nivel superior trebuie revizuită anual, cu o aprobare datată din partea organului de conducere.",
      },
    },
  ],
});

export default quiz;
