import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.6",
  passingScore: 75,
  questions: [
    {
      id: "2.6.1",
      question: {
        en: "For a company outside the CIR's digital providers, how many policy documents does Article 21(2)(a) require for Measure 1?",
        de: "Wie viele Richtliniendokumente verlangt Artikel 21(2)(a) für Maßnahme 1 von einem Unternehmen, das nicht zu den digitalen Anbietern der DVO gehört?",
        nl: "Hoeveel beleidsdocumenten vereist artikel 21(2)(a) voor Maatregel 1 van een onderneming die niet tot de digitale aanbieders van de CIR behoort?",
        fr: "Pour une entreprise qui ne fait pas partie des fournisseurs numériques visés par la CIR, combien de documents de politique l'article 21(2)(a) exige-t-il pour la mesure 1 ?",
        it: "Per un'impresa che non rientra tra i fornitori digitali della CIR, quanti documenti di politica richiede l'articolo 21(2)(a) per la misura 1?",
        es: "Para una empresa que no forma parte de los proveedores digitales de la CIR, ¿cuántos documentos de política exige el artículo 21(2)(a) para la medida 1?",
        pl: "Ile dokumentów polityk wymaga artykuł 21(2)(a) dla środka 1 od firmy, która nie należy do dostawców cyfrowych objętych CIR?",
        cs: "Kolik dokumentů politik vyžaduje článek 21(2)(a) pro opatření 1 od společnosti, která nepatří mezi digitální poskytovatele podle CIR?",
        pt: "Para uma empresa que não pertence aos prestadores digitais do CIR, quantos documentos de política exige o artigo 21(2)(a) para a Medida 1?",
        ro: "Pentru o companie care nu se numără printre furnizorii digitali vizați de CIR, câte documente de politică impune articolul 21(2)(a) pentru Măsura 1?",
      },
      options: [
        {
          en: "Exactly one comprehensive security policy",
          de: "Genau eine umfassende Sicherheitsrichtlinie",
          nl: "Precies één uitgebreid beveiligingsbeleid",
          fr: "Exactement une politique de sécurité globale",
          it: "Esattamente una politica di sicurezza completa",
          es: "Exactamente una política de seguridad integral",
          pl: "Dokładnie jedną kompleksową politykę bezpieczeństwa",
          cs: "Přesně jednu komplexní bezpečnostní politiku",
          pt: "Exatamente uma política de segurança abrangente",
          ro: "Exact o politică de securitate cuprinzătoare",
        },
        {
          en: "Exactly five core policies",
          de: "Genau fünf Kernrichtlinien",
          nl: "Precies vijf kernbeleidslijnen",
          fr: "Exactement cinq politiques fondamentales",
          it: "Esattamente cinque politiche fondamentali",
          es: "Exactamente cinco políticas fundamentales",
          pl: "Dokładnie pięć podstawowych polityk",
          cs: "Přesně pět základních politik",
          pt: "Exatamente cinco políticas fundamentais",
          ro: "Exact cinci politici de bază",
        },
        {
          en: "No fixed number: policies on risk analysis and information system security",
          de: "Keine feste Zahl: Konzepte zur Risikoanalyse und zur Sicherheit der Informationssysteme",
          nl: "Geen vast aantal: beleid inzake risicoanalyse en beveiliging van informatiesystemen",
          fr: "Aucun nombre fixe : des politiques relatives à l'analyse des risques et à la sécurité des systèmes d'information",
          it: "Nessun numero fisso: politiche di analisi dei rischi e di sicurezza dei sistemi informatici",
          es: "Ningún número fijo: políticas de seguridad de los sistemas de información y análisis de riesgos",
          pl: "Bez stałej liczby: politykę analizy ryzyka i bezpieczeństwa systemów informatycznych",
          cs: "Žádný pevný počet: politiku analýzy rizik a politiku bezpečnosti informačních systémů",
          pt: "Nenhum número fixo: políticas de análise dos riscos e de segurança dos sistemas de informação",
          ro: "Niciun număr fix: politici referitoare la analiza riscurilor și securitatea sistemelor informatice",
        },
        {
          en: "Exactly eleven: one top-level plus ten topic-specific",
          de: "Genau elf: eine übergeordnete plus zehn themenspezifische",
          nl: "Precies elf: één overkoepelend plus tien onderwerpspecifieke",
          fr: "Exactement onze : une de haut niveau plus dix thématiques",
          it: "Esattamente undici: una di livello superiore più dieci tematiche",
          es: "Exactamente once: una de nivel superior más diez temáticas",
          pl: "Dokładnie jedenaście: jedną nadrzędną plus dziesięć tematycznych",
          cs: "Přesně jedenáct: jednu nadřazenou a deset tematických",
          pt: "Exatamente onze: uma de nível superior mais dez específicas por tema",
          ro: "Exact unsprezece: una de nivel superior plus zece specifice pe teme",
        },
      ],
      correctIndex: 2,
      explanation: {
        en: "Article 21(2)(a) asks for policies on risk analysis and information system security and sets no number of documents. Only the digital providers the CIR covers must have the top-level policy plus the topic-specific policies its Annex lists.",
        de: "Artikel 21(2)(a) verlangt Konzepte zur Risikoanalyse und zur Sicherheit der Informationssysteme und nennt keine Zahl von Dokumenten. Nur die digitalen Anbieter, für die die DVO gilt, brauchen die übergeordnete Richtlinie und die themenspezifischen Richtlinien aus ihrem Anhang.",
        nl: "Artikel 21(2)(a) vraagt om beleid inzake risicoanalyse en beveiliging van informatiesystemen en noemt geen aantal documenten. Alleen de digitale aanbieders waarop de CIR van toepassing is, moeten het overkoepelende beleid plus de onderwerpspecifieke beleidslijnen uit de bijlage hebben.",
        fr: "L'article 21(2)(a) demande des politiques relatives à l'analyse des risques et à la sécurité des systèmes d'information et ne fixe aucun nombre de documents. Seuls les fournisseurs numériques couverts par la CIR doivent disposer de la politique de haut niveau et des politiques thématiques énumérées dans son annexe.",
        it: "L'articolo 21(2)(a) chiede politiche di analisi dei rischi e di sicurezza dei sistemi informatici e non fissa alcun numero di documenti. Solo i fornitori digitali coperti dalla CIR devono disporre della politica di livello superiore più le politiche tematiche elencate nel suo allegato.",
        es: "El artículo 21(2)(a) pide políticas de seguridad de los sistemas de información y análisis de riesgos y no fija ningún número de documentos. Solo los proveedores digitales a los que se aplica la CIR deben tener la política de nivel superior más las políticas temáticas que enumera su anexo.",
        pl: "Artykuł 21(2)(a) wymaga polityki analizy ryzyka i bezpieczeństwa systemów informatycznych i nie określa liczby dokumentów. Tylko dostawcy cyfrowi objęci CIR muszą mieć politykę nadrzędną plus polityki tematyczne wymienione w jego załączniku.",
        cs: "Článek 21(2)(a) požaduje politiku analýzy rizik a politiku bezpečnosti informačních systémů a nestanoví žádný počet dokumentů. Pouze digitální poskytovatelé, na které se CIR vztahuje, musí mít nadřazenou politiku a tematické politiky uvedené v jeho příloze.",
        pt: "O artigo 21(2)(a) pede políticas de análise dos riscos e de segurança dos sistemas de informação e não fixa nenhum número de documentos. Só os prestadores digitais abrangidos pelo CIR têm de ter a política de nível superior mais as políticas específicas por tema enumeradas no seu anexo.",
        ro: "Articolul 21(2)(a) cere politici referitoare la analiza riscurilor și securitatea sistemelor informatice și nu stabilește un număr de documente. Doar furnizorii digitali vizați de CIR trebuie să aibă politica de nivel superior plus politicile specifice pe teme enumerate în anexa sa.",
      },
    },
    {
      id: "2.6.2",
      question: {
        en: "Which three CIR Annex topic-specific policies does this lesson call out as worth double-checking?",
        de: "Welche drei DVO-Anhang-Spezialrichtlinien hebt diese Lektion zur Gegenkontrolle hervor?",
        nl: "Welke drie CIR-bijlage onderwerpspecifieke beleidsregels noemt deze les expliciet om dubbel te controleren?",
        fr: "Quelles sont les trois politiques thématiques de l'Annexe de la CIR que cette leçon signale comme méritant une double vérification ?",
        it: "Quali tre politiche tematiche dell'Allegato della CIR questa lezione segnala come meritevoli di una doppia verifica?",
        es: "¿Qué tres políticas temáticas del Anexo de la CIR señala esta lección como dignas de una doble comprobación?",
        pl: "Które trzy tematyczne polityki z załącznika CIR ta lekcja wskazuje jako warte podwójnego sprawdzenia?",
        cs: "Které tři tematické politiky z přílohy CIR tato lekce označuje za vhodné dvojí kontroly?",
        pt: "Que três políticas específicas por tema do Anexo do CIR destaca esta lição como merecedoras de dupla verificação?",
        ro: "Care trei politici specifice pe teme din Anexa CIR sunt evidențiate de această lecție ca meritând o verificare suplimentară?",
      },
      options: [
        {
          en: "Risk management, incident handling, access control",
          de: "Risikomanagement, Vorfallbehandlung, Zugangskontrolle",
          nl: "Risicobeheer, incidentbeheer, toegangscontrole",
          fr: "Gestion des risques, traitement des incidents, contrôle d'accès",
          it: "Gestione dei rischi, gestione degli incidenti, controllo degli accessi",
          es: "Gestión de riesgos, gestión de incidentes, control de acceso",
          pl: "Zarządzanie ryzykiem, obsługa incydentów, kontrola dostępu",
          cs: "Řízení rizik, řešení incidentů, řízení přístupu",
          pt: "Gestão de riscos, tratamento de incidentes, controlo de acessos",
          ro: "Gestionarea riscurilor, tratarea incidentelor, controlul accesului",
        },
        {
          en: "Security testing, privileged accounts, removable media",
          de: "Sicherheitstests, privilegierte Konten, Wechseldatenträger",
          nl: "Beveiligingstests, geprivilegieerde accounts, verwijderbare media",
          fr: "Tests de sécurité, comptes à privilèges, supports amovibles",
          it: "Test di sicurezza, account con privilegi, supporti rimovibili",
          es: "Pruebas de seguridad, cuentas con privilegios, soportes extraíbles",
          pl: "Testy bezpieczeństwa, konta uprzywilejowane, nośniki wymienne",
          cs: "Bezpečnostní testování, privilegované účty, vyměnitelná média",
          pt: "Testes de segurança, contas privilegiadas, suportes amovíveis",
          ro: "Testarea securității, conturi privilegiate, suporturi amovibile",
        },
        {
          en: "Cryptography, supply chain, effectiveness assessment",
          de: "Kryptografie, Supply Chain, Wirksamkeitsbewertung",
          nl: "Cryptografie, toeleveringsketen, effectiviteitsbeoordeling",
          fr: "Cryptographie, chaîne d'approvisionnement, évaluation de l'efficacité",
          it: "Crittografia, catena di approvvigionamento, valutazione dell'efficacia",
          es: "Criptografía, cadena de suministro, evaluación de la eficacia",
          pl: "Kryptografia, łańcuch dostaw, ocena skuteczności",
          cs: "Kryptografie, dodavatelský řetězec, posouzení účinnosti",
          pt: "Criptografia, cadeia de abastecimento, avaliação da eficácia",
          ro: "Criptografie, lanț de aprovizionare, evaluarea eficacității",
        },
        {
          en: "Backup, disaster recovery, crisis management",
          de: "Backup, Notfallwiederherstellung, Krisenmanagement",
          nl: "Back-up, herstel na rampen, crisismanagement",
          fr: "Sauvegarde, reprise après sinistre, gestion de crise",
          it: "Backup, ripristino di emergenza, gestione delle crisi",
          es: "Copia de seguridad, recuperación ante desastres, gestión de crisis",
          pl: "Kopie zapasowe, odtwarzanie po awarii, zarządzanie kryzysowe",
          cs: "Zálohování, obnova po havárii, krizové řízení",
          pt: "Cópia de segurança, recuperação de desastres, gestão de crises",
          ro: "Copii de rezervă, recuperare în caz de dezastru, gestionarea crizelor",
        },
      ],
      correctIndex: 1,
      explanation: {
        en: "Security testing, privileged accounts (as part of access control), and removable media are three topics the CIR Annex names explicitly and a generic ISO policy set often misses - worth double-checking.",
        de: "Sicherheitstests, privilegierte Konten (als Teil der Zugangskontrolle) und Wechseldatenträger sind drei Themen, die der DVO-Anhang ausdrücklich nennt und die ein generischer ISO-Richtlinienkanon oft übersieht - zur Gegenkontrolle empfehlenswert.",
        nl: "Beveiligingstesten, geprivilegieerde accounts (als onderdeel van toegangscontrole) en verwijderbare media zijn drie onderwerpen die de CIR-bijlage uitdrukkelijk noemt en die een generieke ISO-beleidsset vaak mist - aanbevolen om dubbel te controleren.",
        fr: "Les tests de sécurité, les comptes à privilèges (dans le cadre du contrôle d'accès) et les supports amovibles sont trois sujets que l'Annexe de la CIR nomme explicitement et qu'un ensemble générique de politiques ISO omet souvent, à double vérifier.",
        it: "I test di sicurezza, gli account con privilegi (come parte del controllo degli accessi) e i supporti rimovibili sono tre temi che l'Allegato della CIR nomina esplicitamente e che un set generico di politiche ISO spesso trascura, da verificare due volte.",
        es: "Las pruebas de seguridad, las cuentas con privilegios (como parte del control de acceso) y los soportes extraíbles son tres temas que el Anexo de la CIR nombra explícitamente y que un conjunto genérico de políticas ISO a menudo omite, conviene comprobarlos dos veces.",
        pl: "Testy bezpieczeństwa, konta uprzywilejowane (jako część kontroli dostępu) i nośniki wymienne to trzy tematy, które załącznik CIR wyraźnie wymienia, a ogólny zestaw polityk ISO często pomija - warto je podwójnie sprawdzić.",
        cs: "Bezpečnostní testování, privilegované účty (jako součást řízení přístupu) a vyměnitelná média jsou tři témata, která příloha CIR výslovně uvádí a obecná sada politik ISO je často opomíjí. Stojí za to je dvakrát zkontrolovat.",
        pt: "Os testes de segurança, as contas privilegiadas (como parte do controlo de acessos) e os suportes amovíveis são três temas que o Anexo do CIR nomeia expressamente e que um conjunto genérico de políticas ISO muitas vezes omite. Vale a pena verificá-los duplamente.",
        ro: "Testarea securității, conturile privilegiate (ca parte a controlului accesului) și suporturile amovibile sunt trei teme pe care Anexa CIR le numește în mod expres și pe care un set generic de politici ISO le omite adesea. Merită verificate suplimentar.",
      },
    },
    {
      id: "2.6.3",
      question: {
        en: "What makes an undated or unsigned top-level policy the 'fastest path to an audit finding'?",
        de: "Warum ist eine undatierte oder nicht unterschriebene übergeordnete Richtlinie der 'schnellste Weg zu einer Audit-Feststellung'?",
        nl: "Waarom is een ongedateerd of niet-ondertekend overkoepelend beleid 'de snelste weg naar een auditbevinding'?",
        fr: "Pourquoi une politique de haut niveau non datée ou non signée est-elle 'le chemin le plus rapide vers une constatation d'audit' ?",
        it: "Perché una politica di livello superiore non datata o non firmata è 'la via più rapida verso un rilievo di audit'?",
        es: "¿Por qué una política de nivel superior sin fecha o sin firmar es 'el camino más rápido hacia un hallazgo de auditoría'?",
        pl: "Dlaczego niedatowana lub niepodpisana polityka nadrzędna jest „najszybszą drogą do ustalenia audytowego”?",
        cs: "Proč je nedatovaná nebo nepodepsaná nadřazená politika 'nejrychlejší cestou ke zjištění auditu'?",
        pt: "O que torna uma política de nível superior não datada ou não assinada o 'caminho mais rápido para uma constatação de auditoria'?",
        ro: "Ce face dintr-o politică de nivel superior nedatată sau nesemnată 'cea mai rapidă cale către o constatare de audit'?",
      },
      options: [
        {
          en: "It means the IT department forgot to file the paperwork",
          de: "Es bedeutet, dass die IT-Abteilung den Papierkram vergessen hat",
          nl: "Het betekent dat de IT-afdeling de papierwinkel is vergeten",
          fr: "Cela signifie que le service informatique a oublié de classer les documents",
          it: "Significa che il reparto IT ha dimenticato di archiviare la documentazione",
          es: "Significa que el departamento de TI olvidó archivar la documentación",
          pl: "Oznacza, że dział IT zapomniał zarejestrować dokumentację",
          cs: "Znamená to, že oddělení IT zapomnělo založit dokumentaci",
          pt: "Significa que o departamento de TI se esqueceu de arquivar a documentação",
          ro: "Înseamnă că departamentul IT a uitat să depună documentația",
        },
        {
          en: "It means the management body either did not approve the security approach or cannot prove they did",
          de: "Es bedeutet, dass die Geschäftsleitung den Sicherheitsansatz entweder nicht genehmigt hat oder dies nicht nachweisen kann",
          nl: "Het betekent dat het leidinggevend orgaan de beveiligingsaanpak niet heeft goedgekeurd of dit niet kan bewijzen",
          fr: "Cela signifie que l'organe de direction n'a pas approuvé l'approche de sécurité ou ne peut pas prouver qu'il l'a fait",
          it: "Significa che l'organo di gestione non ha approvato l'approccio alla sicurezza oppure non può dimostrare di averlo fatto",
          es: "Significa que el órgano de dirección o no aprobó el enfoque de seguridad o no puede demostrar que lo hizo",
          pl: "Oznacza, że organ zarządzający albo nie zatwierdził podejścia do bezpieczeństwa, albo nie może tego udowodnić",
          cs: "Znamená to, že řídicí orgán buď bezpečnostní přístup neschválil, nebo to nemůže prokázat",
          pt: "Significa que o órgão de administração ou não aprovou a abordagem de segurança ou não consegue provar que o fez",
          ro: "Înseamnă că organul de conducere fie nu a aprobat abordarea de securitate, fie nu poate dovedi că a făcut-o",
        },
        {
          en: "It means the policies are technically incorrect",
          de: "Es bedeutet, dass die Richtlinien fachlich falsch sind",
          nl: "Het betekent dat de beleidslijnen technisch onjuist zijn",
          fr: "Cela signifie que les politiques sont techniquement incorrectes",
          it: "Significa che le politiche sono tecnicamente errate",
          es: "Significa que las políticas son técnicamente incorrectas",
          pl: "Oznacza, że polityki są technicznie nieprawidłowe",
          cs: "Znamená to, že politiky jsou technicky nesprávné",
          pt: "Significa que as políticas estão tecnicamente incorretas",
          ro: "Înseamnă că politicile sunt incorecte din punct de vedere tehnic",
        },
        {
          en: "It means the auditor has to write a longer report",
          de: "Es bedeutet, dass der Auditor einen längeren Bericht schreiben muss",
          nl: "Het betekent dat de auditor een langer rapport moet schrijven",
          fr: "Cela signifie que l'auditeur doit rédiger un rapport plus long",
          it: "Significa che il revisore deve redigere un rapporto più lungo",
          es: "Significa que el auditor tiene que redactar un informe más largo",
          pl: "Oznacza, że audytor musi napisać dłuższy raport",
          cs: "Znamená to, že auditor musí napsat delší zprávu",
          pt: "Significa que o auditor tem de escrever um relatório mais longo",
          ro: "Înseamnă că auditorul trebuie să redacteze un raport mai lung",
        },
      ],
      correctIndex: 1,
      explanation: {
        en: "Without a signature and a date, management cannot prove it approved the security approach. CIR providers must also state the approval date in the policy itself (CIR Annex 1.1.1(k)).",
        de: "Ohne Unterschrift und Datum kann die Geschäftsleitung nicht nachweisen, dass sie den Sicherheitsansatz mitgetragen hat. DVO-Anbieter müssen das Datum der Genehmigung zudem in der Richtlinie selbst angeben (DVO Anhang 1.1.1 Buchstabe k).",
        nl: "Zonder handtekening en datum kan het leidinggevend orgaan niet aantonen dat het de beveiligingsaanpak heeft goedgekeurd. Aanbieders onder de CIR moeten de goedkeuringsdatum bovendien in het beleid zelf vermelden (CIR-bijlage 1.1.1(k)).",
        fr: "Sans signature ni date, la direction ne peut pas prouver qu'elle a approuvé l'approche de sécurité. Les fournisseurs relevant de la CIR doivent en outre indiquer la date d'approbation dans la politique elle-même (Annexe de la CIR, 1.1.1(k)).",
        it: "Senza firma e data, la direzione non può dimostrare di aver approvato l'approccio alla sicurezza. I fornitori soggetti alla CIR devono inoltre indicare la data di approvazione nella politica stessa (Allegato della CIR, 1.1.1(k)).",
        es: "Sin firma ni fecha, la dirección no puede demostrar que aprobó el enfoque de seguridad. Los proveedores sujetos a la CIR deben además indicar la fecha de aprobación en la propia política (Anexo de la CIR, 1.1.1(k)).",
        pl: "Bez podpisu i daty kierownictwo nie może udowodnić, że zatwierdziło podejście do bezpieczeństwa. Dostawcy objęci CIR muszą ponadto podać datę zatwierdzenia w samej polityce (załącznik CIR, pkt 1.1.1(k)).",
        cs: "Bez podpisu a data nemůže vedení prokázat, že bezpečnostní přístup schválilo. Poskytovatelé podle CIR musí navíc uvést datum schválení přímo v politice (příloha CIR, bod 1.1.1(k)).",
        pt: "Sem assinatura e data, a gestão não consegue provar que aprovou a abordagem de segurança. Os prestadores abrangidos pelo CIR têm ainda de indicar a data de aprovação na própria política (Anexo do CIR, ponto 1.1.1(k)).",
        ro: "Fără semnătură și dată, conducerea nu poate dovedi că a aprobat abordarea de securitate. Furnizorii vizați de CIR trebuie, de asemenea, să indice data aprobării în politica însăși (Anexa CIR, punctul 1.1.1(k)).",
      },
    },
    {
      id: "2.6.4",
      question: {
        en: "How often must a provider covered by the CIR review its top-level information security policy?",
        de: "Wie oft muss ein Anbieter, für den die DVO gilt, seine übergeordnete Informationssicherheitsrichtlinie überprüfen?",
        nl: "Hoe vaak moet een aanbieder waarop de CIR van toepassing is zijn overkoepelende informatiebeveiligingsbeleid herzien?",
        fr: "À quelle fréquence un fournisseur couvert par la CIR doit-il réexaminer sa politique de sécurité de l'information de haut niveau ?",
        it: "Con quale frequenza un fornitore coperto dalla CIR deve riesaminare la propria politica di sicurezza delle informazioni di livello superiore?",
        es: "¿Con qué frecuencia debe un proveedor sujeto a la CIR revisar su política de seguridad de la información de nivel superior?",
        pl: "Jak często dostawca objęty CIR musi przeglądać swoją nadrzędną politykę bezpieczeństwa informacji?",
        cs: "Jak často musí poskytovatel, na kterého se vztahuje CIR, přezkoumávat svou nadřazenou politiku bezpečnosti informací?",
        pt: "Com que frequência um prestador abrangido pelo CIR tem de rever a sua política de segurança da informação de nível superior?",
        ro: "Cât de des trebuie un furnizor vizat de CIR să își revizuiască politica de securitate a informației de nivel superior?",
      },
      options: [
        {
          en: "Every six months",
          de: "Alle sechs Monate",
          nl: "Elke zes maanden",
          fr: "Tous les six mois",
          it: "Ogni sei mesi",
          es: "Cada seis meses",
          pl: "Co sześć miesięcy",
          cs: "Každých šest měsíců",
          pt: "De seis em seis meses",
          ro: "O dată la șase luni",
        },
        {
          en: "Annually",
          de: "Jährlich",
          nl: "Jaarlijks",
          fr: "Chaque année",
          it: "Annualmente",
          es: "Anualmente",
          pl: "Co roku",
          cs: "Ročně",
          pt: "Anualmente",
          ro: "Anual",
        },
        {
          en: "Every two years",
          de: "Alle zwei Jahre",
          nl: "Elke twee jaar",
          fr: "Tous les deux ans",
          it: "Ogni due anni",
          es: "Cada dos años",
          pl: "Co dwa lata",
          cs: "Každé dva roky",
          pt: "De dois em dois anos",
          ro: "O dată la doi ani",
        },
        {
          en: "Only when a breach occurs",
          de: "Nur bei einem Sicherheitsvorfall",
          nl: "Alleen na een incident",
          fr: "Uniquement en cas de violation",
          it: "Solo quando si verifica una violazione",
          es: "Solo cuando se produce una brecha",
          pl: "Tylko gdy dojdzie do naruszenia",
          cs: "Pouze když dojde k narušení",
          pt: "Apenas quando ocorre uma violação",
          ro: "Doar când survine o breșă",
        },
      ],
      correctIndex: 1,
      explanation: {
        en: "CIR Annex 1.1.2: at least annually, and after significant incidents or significant changes. Outside the CIR the law sets no interval; the BSI recommends reviewing it at least every two years.",
        de: "DVO Anhang 1.1.2: mindestens jährlich und nach erheblichen Vorfällen oder wesentlichen Änderungen. Außerhalb der DVO nennt das Gesetz kein Intervall; das BSI empfiehlt, sie spätestens alle zwei Jahre zu überprüfen.",
        nl: "CIR-bijlage 1.1.2: ten minste jaarlijks, en na significante incidenten of significante wijzigingen. Buiten de CIR schrijft de wet geen interval voor; het BSI beveelt aan het ten minste om de twee jaar te herzien.",
        fr: "Annexe de la CIR, point 1.1.2 : au moins une fois par an, ainsi qu'après des incidents importants ou des changements importants. En dehors de la CIR, la loi ne fixe aucun intervalle ; le BSI recommande de la réexaminer au moins tous les deux ans.",
        it: "Allegato della CIR, punto 1.1.2: almeno annualmente e dopo incidenti significativi o cambiamenti significativi. Al di fuori della CIR la legge non fissa alcun intervallo; il BSI raccomanda di riesaminarla almeno ogni due anni.",
        es: "Anexo de la CIR, punto 1.1.2: al menos una vez al año y tras incidentes significativos o cambios significativos. Fuera de la CIR, la ley no fija ningún intervalo; el BSI recomienda revisarla al menos cada dos años.",
        pl: "Załącznik CIR, pkt 1.1.2: co najmniej raz w roku oraz po poważnych incydentach lub istotnych zmianach. Poza CIR prawo nie określa żadnego interwału; BSI zaleca przegląd co najmniej co dwa lata.",
        cs: "Příloha CIR, bod 1.1.2: alespoň jednou ročně a po významných incidentech nebo významných změnách. Mimo CIR zákon žádný interval nestanoví; BSI doporučuje ji přezkoumávat alespoň jednou za dva roky.",
        pt: "Anexo do CIR, ponto 1.1.2: pelo menos anualmente e após incidentes significativos ou alterações significativas. Fora do CIR, a lei não fixa nenhum intervalo; o BSI recomenda revê-la pelo menos de dois em dois anos.",
        ro: "Anexa CIR, punctul 1.1.2: cel puțin anual și după incidente semnificative sau modificări semnificative. În afara CIR, legea nu stabilește niciun interval; BSI recomandă revizuirea ei cel puțin o dată la doi ani.",
      },
    },
  ],
});

export default quiz;
