import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.7",
  passingScore: 75,
  questions: [
    {
      id: "2.7.1",
      question: {
        en: "What are the five parts of an incident response plan?",
        de: "Was sind die fünf Bestandteile eines Incident-Response-Plans?",
        nl: "Wat zijn de vijf onderdelen van een incidentresponsplan?",
        fr: "Quelles sont les cinq parties d'un plan de réponse aux incidents ?",
        it: "Quali sono le cinque parti di un piano di risposta agli incidenti?",
        es: "¿Cuáles son las cinco partes de un plan de respuesta a incidentes?",
        pl: "Jakie jest pięć części planu reagowania na incydenty?",
        cs: "Jakých pět částí má plán reakce na incidenty?",
        pt: "Quais são as cinco partes de um plano de resposta a incidentes?",
        ro: "Care sunt cele cinci părți ale unui plan de răspuns la incidente?",
      },
      options: [
        { en: "Plan, execute, review, report, archive", de: "Planen, ausführen, überprüfen, melden, archivieren", nl: "Plannen, uitvoeren, beoordelen, rapporteren, archiveren", fr: "Planifier, exécuter, réexaminer, notifier, archiver", it: "Pianificare, eseguire, riesaminare, notificare, archiviare", es: "Planificar, ejecutar, revisar, notificar, archivar", pl: "Planować, wykonywać, przeglądać, zgłaszać, archiwizować", cs: "Plánovat, provést, přezkoumat, ohlásit, archivovat", pt: "Planear, executar, rever, notificar, arquivar", ro: "A planifica, a executa, a revizui, a raporta, a arhiva" },
        { en: "Detection, classification, response, recovery, lessons learned", de: "Erkennung, Klassifizierung, Reaktion, Wiederherstellung, Lessons Learned", nl: "Detectie, classificatie, respons, herstel, geleerde lessen", fr: "Détection, classification, réponse, rétablissement, enseignements tirés", it: "Rilevamento, classificazione, risposta, ripristino, lezioni apprese", es: "Detección, clasificación, respuesta, recuperación, lecciones aprendidas", pl: "Wykrywanie, klasyfikacja, reagowanie, odtwarzanie, wnioski wyciągnięte", cs: "Detekce, klasifikace, reakce, obnova, poučení", pt: "Deteção, classificação, resposta, recuperação, lições aprendidas", ro: "Detectare, clasificare, răspuns, recuperare, lecții învățate" },
        { en: "Alert, escalate, contain, notify, close", de: "Alarmieren, eskalieren, eindämmen, benachrichtigen, abschließen", nl: "Alarmeren, escaleren, indammen, melden, afsluiten", fr: "Alerter, escalader, contenir, notifier, clôturer", it: "Allertare, escalare, contenere, notificare, chiudere", es: "Alertar, escalar, contener, notificar, cerrar", pl: "Alarmować, eskalować, ograniczać, powiadamiać, zamykać", cs: "Výstraha, eskalace, omezení, oznámení, uzavření", pt: "Alerta, escalar, conter, notificar, encerrar", ro: "Alertă, escaladare, izolare, notificare, închidere" },
        { en: "Identify, protect, detect, respond, recover", de: "Identifizieren, schützen, erkennen, reagieren, wiederherstellen", nl: "Identificeren, beschermen, detecteren, reageren, herstellen", fr: "Identifier, protéger, détecter, réagir, rétablir", it: "Identificare, proteggere, rilevare, rispondere, ripristinare", es: "Identificar, proteger, detectar, responder, recuperar", pl: "Identyfikować, chronić, wykrywać, reagować, odtwarzać", cs: "Identifikovat, chránit, detekovat, reagovat, obnovit", pt: "Identificar, proteger, detetar, responder, recuperar", ro: "A identifica, a proteja, a detecta, a răspunde, a recupera" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The five parts are detection, classification, response, recovery, and lessons learned - the auditor checks whether all five exist and have been tested.",
        de: "Die fünf Bestandteile sind Erkennung, Klassifizierung, Reaktion, Wiederherstellung und Lessons Learned - der Auditor prüft, ob alle fünf vorhanden sind und getestet wurden.",
        nl: "De vijf onderdelen zijn detectie, classificatie, respons, herstel en geleerde lessen - de auditor controleert of alle vijf aanwezig zijn en getest.",
        fr: "Les cinq parties sont la détection, la classification, la réponse, le rétablissement et les enseignements tirés : l'auditeur vérifie si les cinq existent et ont été testées.",
        it: "Le cinque parti sono rilevamento, classificazione, risposta, ripristino e lezioni apprese: il revisore verifica se tutte e cinque esistono e sono state testate.",
        es: "Las cinco partes son detección, clasificación, respuesta, recuperación y lecciones aprendidas: el auditor comprueba si las cinco existen y se han probado.",
        pl: "Pięć części to wykrywanie, klasyfikacja, reagowanie, odtwarzanie i wyciągnięte wnioski - audytor sprawdza, czy wszystkie pięć istnieje i zostało przetestowanych.",
        cs: "Pět částí je detekce, klasifikace, reakce, obnova a poučení. Auditor kontroluje, zda všech pět existuje a zda byly otestovány.",
        pt: "As cinco partes são deteção, classificação, resposta, recuperação e lições aprendidas. O auditor verifica se as cinco existem e se foram testadas.",
        ro: "Cele cinci părți sunt detectarea, clasificarea, răspunsul, recuperarea și lecțiile învățate. Auditorul verifică dacă toate cele cinci există și dacă au fost testate.",
      },
    },
    {
      id: "2.7.2",
      question: {
        en: "Which CEO decisions must be pre-assigned by name in the incident response plan?",
        de: "Welche CEO-Entscheidungen müssen im Incident-Response-Plan namentlich vorab zugewiesen werden?",
        nl: "Welke CEO-beslissingen moeten op naam zijn vooraf toegewezen in het incidentresponsplan?",
        fr: "Quelles décisions du dirigeant doivent être attribuées nominativement à l'avance dans le plan de réponse aux incidents ?",
        it: "Quali decisioni dell'amministratore delegato devono essere assegnate nominativamente in anticipo nel piano di risposta agli incidenti?",
        es: "¿Qué decisiones del director general deben asignarse de antemano por nombre en el plan de respuesta a incidentes?",
        pl: "Które decyzje dyrektora generalnego muszą być z góry przypisane imiennie w planie reagowania na incydenty?",
        cs: "Která rozhodnutí generálního ředitele musí být v plánu reakce na incidenty předem jmenovitě přidělena?",
        pt: "Que decisões do diretor executivo têm de ser previamente atribuídas pelo nome no plano de resposta a incidentes?",
        ro: "Ce decizii ale directorului general trebuie atribuite în prealabil nominal în planul de răspuns la incidente?",
      },
      options: [
        { en: "Choosing the antivirus software and approving IT hires", de: "Auswahl der Antivirensoftware und Genehmigung von IT-Einstellungen", nl: "De antivirussoftware kiezen en IT-aanwervingen goedkeuren", fr: "Le choix du logiciel antivirus et l'approbation des recrutements informatiques", it: "La scelta del software antivirus e l'approvazione delle assunzioni IT", es: "Elegir el software antivirus y aprobar las contrataciones de TI", pl: "Wybór oprogramowania antywirusowego i zatwierdzanie zatrudnień w IT", cs: "Volba antivirového softwaru a schvalování náboru pracovníků IT", pt: "A escolha do software antivírus e a aprovação de contratações de TI", ro: "Alegerea software-ului antivirus și aprobarea angajărilor în IT" },
        { en: "Declaring a crisis, authorising spending, approving communications, and the ransom decision", de: "Krisenausrufung, Ausgabenfreigabe, Freigabe der Kommunikation und die Lösegeldfrage", nl: "Een crisis declareren, uitgaven autoriseren, communicatie goedkeuren en de losgeldkeuze", fr: "Déclarer une crise, autoriser les dépenses, approuver les communications et la décision relative à la rançon", it: "Dichiarare una crisi, autorizzare le spese, approvare le comunicazioni e la decisione sul riscatto", es: "Declarar una crisis, autorizar gastos, aprobar comunicaciones y la decisión sobre el rescate", pl: "Ogłoszenie kryzysu, autoryzacja wydatków, zatwierdzanie komunikacji oraz decyzja o okupie", cs: "Vyhlášení krize, schválení výdajů, schválení komunikace a rozhodnutí o výkupném", pt: "Declarar uma crise, autorizar despesas, aprovar comunicações e a decisão sobre o resgate", ro: "Declararea unei crize, autorizarea cheltuielilor, aprobarea comunicărilor și decizia privind răscumpărarea" },
        { en: "Setting the IT budget and selecting cloud providers", de: "Festlegung des IT-Budgets und Auswahl von Cloud-Anbietern", nl: "Het IT-budget vaststellen en cloudproviders selecteren", fr: "Fixer le budget informatique et sélectionner les fournisseurs cloud", it: "Definire il budget IT e selezionare i fornitori cloud", es: "Fijar el presupuesto de TI y seleccionar proveedores de nube", pl: "Ustalanie budżetu IT i wybór dostawców chmury", cs: "Stanovení rozpočtu na IT a výběr poskytovatelů cloudu", pt: "Definir o orçamento de TI e selecionar fornecedores de nuvem", ro: "Stabilirea bugetului IT și selectarea furnizorilor de cloud" },
        { en: "Reviewing the annual security report and approving leave", de: "Überprüfung des jährlichen Sicherheitsberichts und Urlaubsgenehmigung", nl: "Het jaarlijkse beveiligingsrapport beoordelen en verlof goedkeuren", fr: "Réexaminer le rapport annuel de sécurité et approuver les congés", it: "Riesaminare il rapporto annuale sulla sicurezza e approvare le ferie", es: "Revisar el informe anual de seguridad y aprobar las vacaciones", pl: "Przegląd rocznego raportu bezpieczeństwa i zatwierdzanie urlopów", cs: "Přezkum roční bezpečnostní zprávy a schvalování dovolených", pt: "Rever o relatório anual de segurança e aprovar férias", ro: "Revizuirea raportului anual de securitate și aprobarea concediilor" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The CEO's crisis declaration, emergency spending authority, external communication approval, and ransom decision must all be pre-assigned by name.",
        de: "Die Krisenausrufung, die Notfall-Ausgabenbefugnis, die Freigabe externer Kommunikation und die Lösegeldfrage müssen alle namentlich vorab zugewiesen werden.",
        nl: "De crisisdeclaratie van de CEO, de bevoegdheid voor nooduitgaven, de goedkeuring van externe communicatie en de losgeldkeuze moeten allemaal op naam zijn vooraf toegewezen.",
        fr: "La déclaration de crise du dirigeant, le pouvoir de dépenses d'urgence, l'approbation des communications externes et la décision relative à la rançon doivent tous être attribués nominativement à l'avance.",
        it: "La dichiarazione di crisi dell'amministratore delegato, il potere di spesa d'emergenza, l'approvazione delle comunicazioni esterne e la decisione sul riscatto devono essere tutti assegnati nominativamente in anticipo.",
        es: "La declaración de crisis del director general, la facultad de gasto de emergencia, la aprobación de las comunicaciones externas y la decisión sobre el rescate deben asignarse de antemano por nombre.",
        pl: "Ogłoszenie kryzysu przez dyrektora generalnego, uprawnienie do wydatków awaryjnych, zatwierdzanie komunikacji zewnętrznej oraz decyzja o okupie muszą być z góry przypisane imiennie.",
        cs: "Vyhlášení krize generálním ředitelem, pravomoc k nouzovým výdajům, schvalování externí komunikace a rozhodnutí o výkupném musí být všechny předem jmenovitě přiděleny.",
        pt: "A declaração de crise pelo diretor executivo, a autoridade para despesas de emergência, a aprovação da comunicação externa e a decisão sobre o resgate têm todas de ser previamente atribuídas pelo nome.",
        ro: "Declararea crizei de către directorul general, autoritatea de a efectua cheltuieli de urgență, aprobarea comunicării externe și decizia privind răscumpărarea trebuie atribuite toate în prealabil nominal.",
      },
    },
    {
      id: "2.7.3",
      question: {
        en: "What is a tabletop exercise?",
        de: "Was ist eine Tabletop-Übung?",
        nl: "Wat is een tabletop-oefening?",
        fr: "Qu'est-ce qu'un exercice sur table ?",
        it: "Che cos'è un'esercitazione teorica (tabletop)?",
        es: "¿Qué es un ejercicio de simulación teórica (tabletop)?",
        pl: "Czym jest ćwiczenie symulacyjne przy stole (tabletop)?",
        cs: "Co je cvičení u stolu (tabletop)?",
        pt: "O que é um exercício de simulação teórica?",
        ro: "Ce este un exercițiu teoretic de tip tabletop?",
      },
      options: [
        { en: "A technical penetration test of the company's network", de: "Ein technischer Penetrationstest des Unternehmensnetzwerks", nl: "Een technische penetratietest van het bedrijfsnetwerk", fr: "Un test d'intrusion technique du réseau de l'entreprise", it: "Un test di penetrazione tecnico della rete dell'impresa", es: "Una prueba de penetración técnica de la red de la empresa", pl: "Techniczny test penetracyjny sieci firmowej", cs: "Technický penetrační test sítě společnosti", pt: "Um teste técnico de penetração à rede da empresa", ro: "Un test tehnic de penetrare a rețelei companiei" },
        { en: "A paper rehearsal of the incident response plan against a scenario", de: "Eine Planübung des Incident-Response-Plans anhand eines Szenarios", nl: "Een papieren doorloop van het incidentresponsplan aan de hand van een scenario", fr: "Une répétition sur papier du plan de réponse aux incidents face à un scénario", it: "Una prova teorica del piano di risposta agli incidenti rispetto a uno scenario", es: "Un ensayo sobre papel del plan de respuesta a incidentes frente a un escenario", pl: "Symulacja planu reagowania na incydenty na papierze w oparciu o scenariusz", cs: "Nácvik plánu reakce na incidenty na papíře proti scénáři", pt: "Um ensaio em papel do plano de resposta a incidentes face a um cenário", ro: "O repetiție pe hârtie a planului de răspuns la incidente față de un scenariu" },
        { en: "A training course for new IT employees", de: "Ein Schulungskurs für neue IT-Mitarbeitende", nl: "Een trainingscursus voor nieuwe IT-medewerkers", fr: "Une formation pour les nouveaux employés informatiques", it: "Un corso di formazione per i nuovi dipendenti IT", es: "Un curso de formación para los nuevos empleados de TI", pl: "Kurs szkoleniowy dla nowych pracowników IT", cs: "Školicí kurz pro nové pracovníky IT", pt: "Um curso de formação para novos trabalhadores de TI", ro: "Un curs de formare pentru noii angajați IT" },
        { en: "A physical security inspection of the server room", de: "Eine physische Sicherheitsinspektion des Serverraums", nl: "Een fysieke beveiligingsinspectie van de serverruimte", fr: "Une inspection de sécurité physique de la salle des serveurs", it: "Un'ispezione di sicurezza fisica della sala server", es: "Una inspección de seguridad física de la sala de servidores", pl: "Fizyczna inspekcja bezpieczeństwa serwerowni", cs: "Kontrolu fyzické bezpečnosti serverovny", pt: "Uma inspeção de segurança física à sala de servidores", ro: "O inspecție de securitate fizică a camerei serverelor" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A tabletop exercise is a paper rehearsal against a scenario, used to find gaps before a real incident does.",
        de: "Eine Tabletop-Übung ist eine Planübung anhand eines Szenarios, die dazu dient, Lücken zu finden, bevor ein echter Vorfall dies tut.",
        nl: "Een tabletop-oefening is een papieren doorloop aan de hand van een scenario, gebruikt om lacunes te vinden voordat een echt incident dat doet.",
        fr: "Un exercice sur table est une répétition sur papier face à un scénario, utilisée pour repérer les lacunes avant qu'un incident réel ne le fasse.",
        it: "Un'esercitazione teorica è una prova su carta rispetto a uno scenario, utilizzata per individuare le lacune prima che lo faccia un incidente reale.",
        es: "Un ejercicio de simulación teórica es un ensayo sobre papel frente a un escenario, que se utiliza para detectar lagunas antes de que lo haga un incidente real.",
        pl: "Ćwiczenie symulacyjne przy stole to próba na papierze w oparciu o scenariusz, służąca wykryciu luk, zanim zrobi to prawdziwy incydent.",
        cs: "Cvičení u stolu je nácvik na papíře proti scénáři, který slouží k odhalení mezer dříve, než je odhalí skutečný incident.",
        pt: "Um exercício de simulação teórica é um ensaio em papel face a um cenário, utilizado para encontrar lacunas antes de um incidente real o fazer.",
        ro: "Un exercițiu teoretic de tip tabletop este o repetiție pe hârtie față de un scenariu, folosită pentru a identifica lacunele înainte să o facă un incident real.",
      },
    },
    {
      id: "2.7.4",
      question: {
        en: "What does BSI IT-Grundschutz DER.2.1.A17 require?",
        de: "Was verlangt BSI IT-Grundschutz DER.2.1.A17?",
        nl: "Wat vereist BSI IT-Grundschutz DER.2.1.A17?",
        fr: "Qu'exige le BSI IT-Grundschutz DER.2.1.A17 ?",
        it: "Cosa richiede il BSI IT-Grundschutz DER.2.1.A17?",
        es: "¿Qué exige el BSI IT-Grundschutz DER.2.1.A17?",
        pl: "Czego wymaga BSI IT-Grundschutz DER.2.1.A17?",
        cs: "Co vyžaduje BSI IT-Grundschutz DER.2.1.A17?",
        pt: "O que exige o BSI IT-Grundschutz DER.2.1.A17?",
        ro: "Ce impune BSI IT-Grundschutz DER.2.1.A17?",
      },
      options: [
        { en: "Monthly vulnerability scans on all systems", de: "Monatliche Schwachstellenscans aller Systeme", nl: "Maandelijkse kwetsbaarheidsscans op alle systemen", fr: "Des analyses de vulnérabilité mensuelles sur tous les systèmes", it: "Scansioni mensili delle vulnerabilità su tutti i sistemi", es: "Análisis de vulnerabilidades mensuales en todos los sistemas", pl: "Comiesięczne skanowanie podatności na wszystkich systemach", cs: "Měsíční kontroly zranitelností všech systémů", pt: "Análises mensais de vulnerabilidades em todos os sistemas", ro: "Scanări lunare de vulnerabilități pe toate sistemele" },
        { en: "An annual lessons-learned report from incidents to management", de: "Einen jährlichen Lessons-Learned-Bericht aus Vorfällen an die Geschäftsleitung", nl: "Een jaarlijks rapport met geleerde lessen van incidenten aan de directie", fr: "Un rapport annuel sur les enseignements tirés des incidents, adressé à la direction", it: "Un rapporto annuale alla direzione sulle lezioni apprese dagli incidenti", es: "Un informe anual a la dirección sobre las lecciones aprendidas de los incidentes", pl: "Roczny raport dla kierownictwa o wnioskach wyciągniętych z incydentów", cs: "Roční zprávu o poučení z incidentů pro vedení", pt: "Um relatório anual de lições aprendidas com incidentes para a administração", ro: "Un raport anual privind lecțiile învățate din incidente, adresat conducerii" },
        { en: "Quarterly tabletop exercises for the full company", de: "Vierteljährliche Tabletop-Übungen für das gesamte Unternehmen", nl: "Kwartaallijkse tabletop-oefeningen voor het gehele bedrijf", fr: "Des exercices sur table trimestriels pour l'ensemble de l'entreprise", it: "Esercitazioni teoriche trimestrali per l'intera impresa", es: "Ejercicios de simulación teórica trimestrales para toda la empresa", pl: "Kwartalne ćwiczenia symulacyjne dla całej firmy", cs: "Čtvrtletní cvičení u stolu pro celou společnost", pt: "Exercícios de simulação teórica trimestrais para toda a empresa", ro: "Exerciții teoretice de tip tabletop trimestriale pentru întreaga companie" },
        { en: "Daily incident classification reviews", de: "Tägliche Überprüfungen der Vorfallklassifizierung", nl: "Dagelijkse beoordelingen van incidentclassificatie", fr: "Des examens quotidiens de la classification des incidents", it: "Revisioni giornaliere della classificazione degli incidenti", es: "Revisiones diarias de la clasificación de incidentes", pl: "Codzienne przeglądy klasyfikacji incydentów", cs: "Denní přezkumy klasifikace incidentů", pt: "Revisões diárias da classificação de incidentes", ro: "Revizuiri zilnice ale clasificării incidentelor" },
      ],
      correctIndex: 1,
      explanation: {
        en: "DER.2.1.A17 requires lessons learned from incidents to be reported to management annually - if that report does not exist, the auditor notes it.",
        de: "DER.2.1.A17 verlangt, dass Lessons Learned aus Vorfällen jährlich an die Geschäftsleitung berichtet werden - existiert dieser Bericht nicht, vermerkt der Auditor dies als Feststellung.",
        nl: "DER.2.1.A17 vereist dat geleerde lessen van incidenten jaarlijks aan de directie worden gerapporteerd - als dat rapport niet bestaat, noteert de auditor dat.",
        fr: "DER.2.1.A17 exige que les enseignements tirés des incidents soient rapportés à la direction chaque année : si ce rapport n'existe pas, l'auditeur le relève.",
        it: "DER.2.1.A17 richiede che le lezioni apprese dagli incidenti siano riferite alla direzione annualmente: se questo rapporto non esiste, il revisore lo annota.",
        es: "DER.2.1.A17 exige que las lecciones aprendidas de los incidentes se informen a la dirección anualmente: si ese informe no existe, el auditor lo señala.",
        pl: "DER.2.1.A17 wymaga, aby wnioski wyciągnięte z incydentów były co roku przekazywane kierownictwu - jeśli taki raport nie istnieje, audytor to odnotowuje.",
        cs: "DER.2.1.A17 vyžaduje, aby se poučení z incidentů hlásilo vedení ročně. Pokud taková zpráva neexistuje, auditor to zaznamená.",
        pt: "O DER.2.1.A17 exige que as lições aprendidas com incidentes sejam comunicadas à administração anualmente. Se esse relatório não existir, o auditor regista-o.",
        ro: "DER.2.1.A17 impune ca lecțiile învățate din incidente să fie raportate conducerii anual. Dacă acel raport nu există, auditorul îl consemnează.",
      },
    },
  ],
});

export default quiz;
