import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.8",
  passingScore: 75,
  questions: [
    {
      id: "2.8.1",
      question: {
        en: "What are the three components of business continuity under Article 21(2)(c)?",
        de: "Was sind die drei Komponenten der Betriebskontinuität gemäß Artikel 21 Absatz 2(c)?",
        nl: "Wat zijn de drie componenten van bedrijfscontinuïteit op grond van Artikel 21(2)(c)?",
        fr: "Quels sont les trois composants de la continuité d'activité au titre de l'article 21(2)(c) ?",
        it: "Quali sono i tre componenti della continuità operativa ai sensi dell'articolo 21(2)(c)?",
        es: "¿Cuáles son los tres componentes de la continuidad de negocio en virtud del artículo 21(2)(c)?",
        pl: "Jakie są trzy komponenty ciągłości działania na podstawie artykułu 21(2)(c)?",
      },
      options: [
        { en: "Risk analysis, incident handling, and training", de: "Risikoanalyse, Vorfallbehandlung und Schulung", nl: "Risicoanalyse, incidentbeheer en training", fr: "Analyse des risques, traitement des incidents et formation", it: "Analisi dei rischi, gestione degli incidenti e formazione", es: "Análisis de riesgos, gestión de incidentes y formación", pl: "Analiza ryzyka, obsługa incydentów i szkolenia" },
        { en: "Backup management, disaster recovery, and crisis management", de: "Backup-Management, Notfallwiederherstellung und Krisenmanagement", nl: "Back-upbeheer, herstel na rampen en crisismanagement", fr: "Gestion des sauvegardes, reprise après sinistre et gestion de crise", it: "Gestione dei backup, ripristino di emergenza e gestione delle crisi", es: "Gestión de copias de seguridad, recuperación ante desastres y gestión de crisis", pl: "Zarządzanie kopiami zapasowymi, odtwarzanie po awarii i zarządzanie kryzysowe" },
        { en: "Encryption, access control, and monitoring", de: "Verschlüsselung, Zugangskontrolle und Überwachung", nl: "Versleuteling, toegangscontrole en monitoring", fr: "Chiffrement, contrôle d'accès et surveillance", it: "Crittografia, controllo degli accessi e monitoraggio", es: "Cifrado, control de acceso y supervisión", pl: "Szyfrowanie, kontrola dostępu i monitorowanie" },
        { en: "Asset inventory, supplier review, and patching", de: "Asset-Inventar, Lieferantenüberprüfung und Patching", nl: "Middelenregister, leveranciersbeoordeling en patching", fr: "Inventaire des actifs, évaluation des fournisseurs et application de correctifs", it: "Inventario degli asset, valutazione dei fornitori e applicazione delle patch", es: "Inventario de activos, evaluación de proveedores y aplicación de parches", pl: "Inwentaryzacja zasobów, ocena dostawców i instalowanie łatek" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 21(2)(c) requires three distinct components: backup management, disaster recovery, and crisis management.",
        de: "Artikel 21 Absatz 2(c) verlangt drei eigenständige Komponenten: Backup-Management, Notfallwiederherstellung und Krisenmanagement.",
        nl: "Artikel 21(2)(c) vereist drie afzonderlijke componenten: back-upbeheer, herstel na rampen en crisismanagement.",
        fr: "L'article 21(2)(c) exige trois composants distincts : la gestion des sauvegardes, la reprise après sinistre et la gestion de crise.",
        it: "L'articolo 21(2)(c) richiede tre componenti distinti: gestione dei backup, ripristino di emergenza e gestione delle crisi.",
        es: "El artículo 21(2)(c) exige tres componentes distintos: gestión de copias de seguridad, recuperación ante desastres y gestión de crisis.",
        pl: "Artykuł 21(2)(c) wymaga trzech odrębnych komponentów: zarządzania kopiami zapasowymi, odtwarzania po awarii i zarządzania kryzysowego.",
      },
    },
    {
      id: "2.8.2",
      question: {
        en: "What is the difference between RTO and RPO?",
        de: "Was ist der Unterschied zwischen RTO und RPO?",
        nl: "Wat is het verschil tussen RTO en RPO?",
        fr: "Quelle est la différence entre RTO et RPO ?",
        it: "Qual è la differenza tra RTO e RPO?",
        es: "¿Cuál es la diferencia entre RTO y RPO?",
        pl: "Jaka jest różnica między RTO a RPO?",
      },
      options: [
        { en: "RTO is the budget for recovery; RPO is the budget for prevention", de: "RTO ist das Budget für die Wiederherstellung; RPO ist das Budget für die Prävention", nl: "RTO is het budget voor herstel; RPO is het budget voor preventie", fr: "Le RTO est le budget de rétablissement ; le RPO est le budget de prévention", it: "L'RTO è il budget per il ripristino; l'RPO è il budget per la prevenzione", es: "El RTO es el presupuesto para la recuperación; el RPO es el presupuesto para la prevención", pl: "RTO to budżet na odtwarzanie; RPO to budżet na zapobieganie" },
        { en: "RTO is how quickly you must be back up; RPO is how much data you can afford to lose", de: "RTO ist, wie schnell Sie wieder betriebsfähig sein müssen; RPO ist, wie viel Datenverlust Sie sich leisten können", nl: "RTO is hoe snel u weer operationeel moet zijn; RPO is hoeveel dataverlies u zich kunt veroorloven", fr: "Le RTO indique la rapidité avec laquelle vous devez être rétabli ; le RPO indique la quantité de données que vous pouvez vous permettre de perdre", it: "L'RTO indica quanto rapidamente dovete tornare operativi; l'RPO indica quanti dati potete permettervi di perdere", es: "El RTO indica con qué rapidez debe estar restablecido; el RPO indica cuántos datos puede permitirse perder", pl: "RTO określa, jak szybko muszą Państwo wrócić do działania; RPO określa, ile danych mogą Państwo stracić" },
        { en: "RTO applies to hardware; RPO applies to software", de: "RTO gilt für Hardware; RPO gilt für Software", nl: "RTO geldt voor hardware; RPO geldt voor software", fr: "Le RTO s'applique au matériel ; le RPO s'applique au logiciel", it: "L'RTO si applica all'hardware; l'RPO si applica al software", es: "El RTO se aplica al hardware; el RPO se aplica al software", pl: "RTO dotyczy sprzętu; RPO dotyczy oprogramowania" },
        { en: "RTO is set by the auditor; RPO is set by the CISO", de: "RTO wird vom Auditor festgelegt; RPO wird vom CISO festgelegt", nl: "RTO wordt bepaald door de auditor; RPO door de CISO", fr: "Le RTO est fixé par l'auditeur ; le RPO est fixé par le CISO", it: "L'RTO è fissato dal revisore; l'RPO è fissato dal CISO", es: "El RTO lo fija el auditor; el RPO lo fija el CISO", pl: "RTO ustala audytor; RPO ustala CISO" },
      ],
      correctIndex: 1,
      explanation: {
        en: "RTO (Recovery Time Objective) is the maximum acceptable time to restore service; RPO (Recovery Point Objective) is the maximum acceptable data loss, measured in time.",
        de: "RTO (Recovery Time Objective) ist die maximal akzeptable Zeit zur Wiederherstellung des Dienstes; RPO (Recovery Point Objective) ist der maximal akzeptable Datenverlust, gemessen in Zeit.",
        nl: "RTO (Recovery Time Objective) is de maximaal aanvaardbare tijd om de dienst te herstellen; RPO (Recovery Point Objective) is het maximaal aanvaardbare dataverlies, gemeten in tijd.",
        fr: "Le RTO (Recovery Time Objective) est le délai maximal acceptable pour rétablir le service ; le RPO (Recovery Point Objective) est la perte de données maximale acceptable, mesurée en temps.",
        it: "L'RTO (Recovery Time Objective) è il tempo massimo accettabile per ripristinare il servizio; l'RPO (Recovery Point Objective) è la perdita di dati massima accettabile, misurata in tempo.",
        es: "El RTO (Recovery Time Objective) es el tiempo máximo aceptable para restablecer el servicio; el RPO (Recovery Point Objective) es la pérdida de datos máxima aceptable, medida en tiempo.",
        pl: "RTO (Recovery Time Objective) to maksymalny dopuszczalny czas przywrócenia usługi; RPO (Recovery Point Objective) to maksymalna dopuszczalna utrata danych, mierzona w czasie.",
      },
    },
    {
      id: "2.8.3",
      question: {
        en: "Why is a CEO who has never attended a crisis exercise at risk of an audit finding?",
        de: "Warum riskiert ein CEO, der nie an einer Krisenübung teilgenommen hat, eine Audit-Feststellung?",
        nl: "Waarom loopt een CEO die nooit aan een crisisoefening heeft deelgenomen risico op een auditbevinding?",
        fr: "Pourquoi un dirigeant n'ayant jamais participé à un exercice de crise risque-t-il une constatation d'audit ?",
        it: "Perché un amministratore delegato che non ha mai partecipato a un'esercitazione di crisi rischia un rilievo di audit?",
        es: "¿Por qué un director general que nunca ha participado en un ejercicio de crisis corre el riesgo de un hallazgo de auditoría?",
        pl: "Dlaczego dyrektor generalny, który nigdy nie uczestniczył w ćwiczeniu kryzysowym, jest narażony na ustalenie audytowe?",
      },
      options: [
        { en: "Because DER.4 names the management body in nine of sixteen requirements and expects their participation", de: "Weil DER.4 die Geschäftsleitung in neun von sechzehn Anforderungen nennt und deren Teilnahme erwartet", nl: "Omdat DER.4 het leidinggevend orgaan noemt in negen van de zestien vereisten en hun deelname verwacht", fr: "Parce que DER.4 nomme l'organe de direction dans neuf des seize exigences et attend sa participation", it: "Perché DER.4 nomina l'organo di gestione in nove dei sedici requisiti e ne prevede la partecipazione", es: "Porque DER.4 nombra al órgano de dirección en nueve de los dieciséis requisitos y espera su participación", pl: "Ponieważ DER.4 wymienia organ zarządzający w dziewięciu z szesnastu wymagań i oczekuje jego udziału" },
        { en: "Because the CEO must personally run the IT recovery process", de: "Weil der CEO den IT-Wiederherstellungsprozess persönlich leiten muss", nl: "Omdat de CEO het IT-herstelproces persoonlijk moet leiden", fr: "Parce que le dirigeant doit personnellement piloter le processus de rétablissement informatique", it: "Perché l'amministratore delegato deve gestire personalmente il processo di ripristino IT", es: "Porque el director general debe dirigir personalmente el proceso de recuperación de TI", pl: "Ponieważ dyrektor generalny musi osobiście kierować procesem odtwarzania IT" },
        { en: "Because the crisis exercise can only be scheduled by the CEO", de: "Weil die Krisenübung nur vom CEO angesetzt werden kann", nl: "Omdat de crisisoefening alleen door de CEO kan worden gepland", fr: "Parce que l'exercice de crise ne peut être programmé que par le dirigeant", it: "Perché l'esercitazione di crisi può essere programmata solo dall'amministratore delegato", es: "Porque el ejercicio de crisis solo puede programarlo el director general", pl: "Ponieważ ćwiczenie kryzysowe może zaplanować wyłącznie dyrektor generalny" },
        { en: "Because the insurance policy requires CEO attendance at exercises", de: "Weil die Versicherungspolice die Teilnahme des CEO an Übungen verlangt", nl: "Omdat de verzekeringspolis aanwezigheid van de CEO bij oefeningen vereist", fr: "Parce que la police d'assurance exige la présence du dirigeant aux exercices", it: "Perché la polizza assicurativa richiede la presenza dell'amministratore delegato alle esercitazioni", es: "Porque la póliza de seguro exige la asistencia del director general a los ejercicios", pl: "Ponieważ polisa ubezpieczeniowa wymaga obecności dyrektora generalnego na ćwiczeniach" },
      ],
      correctIndex: 0,
      explanation: {
        en: "BSI DER.4 names the management body in nine of sixteen requirements - a CEO who has never attended a crisis exercise has created an audit finding.",
        de: "BSI DER.4 nennt die Geschäftsleitung in neun von sechzehn Anforderungen - ein CEO, der nie an einer Krisenübung teilgenommen hat, hat eine Audit-Feststellung erzeugt.",
        nl: "BSI DER.4 noemt het leidinggevend orgaan in negen van de zestien vereisten - een CEO die nooit aan een crisisoefening heeft deelgenomen heeft een auditbevinding gecreëerd.",
        fr: "Le BSI DER.4 nomme l'organe de direction dans neuf des seize exigences : un dirigeant n'ayant jamais participé à un exercice de crise a généré une constatation d'audit.",
        it: "Il BSI DER.4 nomina l'organo di gestione in nove dei sedici requisiti: un amministratore delegato che non ha mai partecipato a un'esercitazione di crisi ha generato un rilievo di audit.",
        es: "El BSI DER.4 nombra al órgano de dirección en nueve de los dieciséis requisitos: un director general que nunca ha participado en un ejercicio de crisis ha generado un hallazgo de auditoría.",
        pl: "BSI DER.4 wymienia organ zarządzający w dziewięciu z szesnastu wymagań - dyrektor generalny, który nigdy nie uczestniczył w ćwiczeniu kryzysowym, stworzył ustalenie audytowe.",
      },
    },
    {
      id: "2.8.4",
      question: {
        en: "According to the lesson, what lesson does the Maersk case illustrate?",
        de: "Welche Erkenntnis verdeutlicht der Maersk-Fall laut der Lektion?",
        nl: "Welke les illustreert de casus Maersk volgens de les?",
        fr: "Selon la leçon, quel enseignement illustre le cas Maersk ?",
        it: "Secondo la lezione, quale insegnamento illustra il caso Maersk?",
        es: "Según la lección, ¿qué enseñanza ilustra el caso Maersk?",
        pl: "Według lekcji, jaką naukę ilustruje przypadek Maersk?",
      },
      options: [
        { en: "That malware only affects shipping companies", de: "Dass Malware nur Reedereien betrifft", nl: "Dat malware alleen rederijen treft", fr: "Que les logiciels malveillants n'affectent que les compagnies maritimes", it: "Che il malware colpisce solo le compagnie di navigazione", es: "Que el malware solo afecta a las empresas navieras", pl: "Że złośliwe oprogramowanie dotyka wyłącznie firm żeglugowych" },
        { en: "That antivirus software is sufficient protection", de: "Dass Antivirensoftware ausreichender Schutz ist", nl: "Dat antivirussoftware voldoende bescherming biedt", fr: "Qu'un logiciel antivirus constitue une protection suffisante", it: "Che il software antivirus è una protezione sufficiente", es: "Que el software antivirus es protección suficiente", pl: "Że oprogramowanie antywirusowe stanowi wystarczającą ochronę" },
        { en: "That luck - not a tested backup programme - was the only thing between Maersk and a months-long outage", de: "Dass Glück - nicht ein getestetes Backup-Programm - das Einzige war, das Maersk vor einem monatelangen Ausfall bewahrte", nl: "Dat geluk - en niet een getest back-upprogramma - het enige was dat Maersk voor een maandenlange uitval behoedde", fr: "Que la chance, et non un programme de sauvegarde testé, était la seule chose qui séparait Maersk d'une panne de plusieurs mois", it: "Che la fortuna, e non un programma di backup testato, è stata l'unica cosa a separare Maersk da un'interruzione di mesi", es: "Que la suerte, y no un programa de copias de seguridad probado, fue lo único que separó a Maersk de una interrupción de meses", pl: "Że szczęście, a nie przetestowany program kopii zapasowych, było jedyną rzeczą dzielącą Maersk od wielomiesięcznej przerwy w działaniu" },
        { en: "That disaster recovery plans are unnecessary for large companies", de: "Dass Notfallwiederherstellungspläne für große Unternehmen unnötig sind", nl: "Dat herstelplannen na rampen overbodig zijn voor grote bedrijven", fr: "Que les plans de reprise après sinistre sont inutiles pour les grandes entreprises", it: "Che i piani di ripristino di emergenza sono superflui per le grandi imprese", es: "Que los planes de recuperación ante desastres son innecesarios para las grandes empresas", pl: "Że plany odtwarzania po awarii są zbędne dla dużych firm" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Maersk's only surviving backup was offline due to a power cut in Ghana - luck, not a control, saved them from a months-long recovery.",
        de: "Maersks einziges überlebendes Backup war wegen eines Stromausfalls in Ghana offline - Glück, nicht eine Maßnahme, bewahrte sie vor einer monatelangen Wiederherstellung.",
        nl: "De enige overgebleven back-up van Maersk was offline door een stroomuitval in Ghana - geluk, geen maatregel, bewaarde hen voor een maandenlange herstelprocedure.",
        fr: "La seule sauvegarde survivante de Maersk était hors ligne en raison d'une coupure de courant au Ghana : c'est la chance, et non un contrôle, qui leur a évité un rétablissement de plusieurs mois.",
        it: "L'unico backup superstite di Maersk era offline a causa di un'interruzione di corrente in Ghana: è stata la fortuna, non un controllo, a salvarli da un ripristino di mesi.",
        es: "La única copia de seguridad superviviente de Maersk estaba sin conexión debido a un corte de electricidad en Ghana: la suerte, y no un control, los salvó de una recuperación de meses.",
        pl: "Jedyna ocalała kopia zapasowa Maersk była offline z powodu przerwy w dostawie prądu w Ghanie - to szczęście, a nie kontrola, uchroniło ich przed wielomiesięcznym odtwarzaniem.",
      },
    },
  ],
});

export default quiz;
