import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.1",
  passingScore: 75,
  questions: [
    {
      id: "3.1.1",
      question: {
        en: "How many structured question areas does the BSI use to test a CEO's cybersecurity knowledge?",
        de: "Wie viele strukturierte Fragenbereiche verwendet das BSI, um das Cybersicherheitswissen eines CEO zu prüfen?",
        nl: "Hoeveel gestructureerde vraaggebieden gebruikt het BSI om de cybersecuritykennis van een CEO te toetsen?",
        fr: "Combien de domaines de questions structurées le BSI utilise-t-il pour évaluer les connaissances d'un CEO en cybersécurité ?",
        it: "Quante aree di domande strutturate utilizza il BSI per valutare le conoscenze di cybersicurezza di un CEO?",
        es: "¿Cuántas áreas de preguntas estructuradas utiliza el BSI para evaluar los conocimientos de ciberseguridad de un CEO?",
        pl: "Ilu ustrukturyzowanych obszarów pytań używa BSI do sprawdzenia wiedzy CEO z zakresu cyberbezpieczeństwa?",
        cs: "Kolik strukturovaných okruhů otázek používá BSI k ověření znalostí generálního ředitele v oblasti kybernetické bezpečnosti?",
        pt: "Quantas áreas estruturadas de perguntas utiliza o BSI para testar os conhecimentos de cibersegurança de um diretor executivo?",
        ro: "Câte domenii structurate de întrebări utilizează BSI pentru a testa cunoștințele de securitate cibernetică ale unui director general?",
      },
      options: [
        { en: "Five", de: "Fünf", nl: "Vijf", fr: "Cinq", it: "Cinque", es: "Cinco", pl: "Pięć", cs: "Pět", pt: "Cinco", ro: "Cinci" },
        { en: "Ten", de: "Zehn", nl: "Tien", fr: "Dix", it: "Dieci", es: "Diez", pl: "Dziesięć", cs: "Deset", pt: "Dez", ro: "Zece" },
        { en: "Fifteen", de: "Fünfzehn", nl: "Vijftien", fr: "Quinze", it: "Quindici", es: "Quince", pl: "Piętnaście", cs: "Patnáct", pt: "Quinze", ro: "Cincisprezece" },
        { en: "Twenty", de: "Zwanzig", nl: "Twintig", fr: "Vingt", it: "Venti", es: "Veinte", pl: "Dwadzieścia", cs: "Dvacet", pt: "Vinte", ro: "Douăzeci" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The BSI organises its test into ten areas - five foundation questions, one area with ten sub-questions on the mandatory measures, and four deeper checks.",
        de: "Das BSI gliedert seinen Test in zehn Bereiche - fünf Grundlagenfragen, einen Bereich mit zehn Unterfragen zu den Pflichtmaßnahmen und vier vertiefende Prüfungen.",
        nl: "Het BSI organiseert zijn toets in tien gebieden - vijf basisvragen, één gebied met tien deelvragen over de verplichte maatregelen, en vier diepgaandere controles.",
        fr: "Le BSI organise son test en dix domaines - cinq questions fondamentales, un domaine avec dix sous-questions sur les mesures obligatoires, et quatre vérifications plus approfondies.",
        it: "Il BSI organizza il suo test in dieci aree - cinque domande fondamentali, un'area con dieci sotto-domande sulle misure obbligatorie e quattro verifiche più approfondite.",
        es: "El BSI organiza su prueba en diez áreas: cinco preguntas fundamentales, un área con diez subpreguntas sobre las medidas obligatorias y cuatro comprobaciones más profundas.",
        pl: "BSI dzieli swój test na dziesięć obszarów - pięć pytań podstawowych, jeden obszar z dziesięcioma podpytaniami dotyczącymi obowiązkowych środków oraz cztery pogłębione sprawdzenia.",
        cs: "BSI člení svůj test do deseti okruhů: pět základních otázek, jeden okruh s deseti dílčími otázkami k povinným opatřením a čtyři hlubší kontroly.",
        pt: "O BSI organiza o seu teste em dez áreas: cinco perguntas de base, uma área com dez subperguntas sobre as medidas obrigatórias e quatro verificações mais aprofundadas.",
        ro: "BSI își organizează testul în zece domenii: cinci întrebări de bază, un domeniu cu zece subîntrebări privind măsurile obligatorii și patru verificări mai aprofundate.",
      },
    },
    {
      id: "3.1.2",
      question: {
        en: "What is the legal basis for the requirement that CEOs must be trained in cybersecurity?",
        de: "Was ist die Rechtsgrundlage für die Pflicht zur Cybersicherheitsschulung der Geschäftsführung?",
        nl: "Wat is de wettelijke grondslag voor de verplichting dat CEO's een opleiding in cybersecurity moeten volgen?",
        fr: "Quelle est la base juridique de l'obligation pour les CEO de suivre une formation en cybersécurité ?",
        it: "Qual è la base giuridica dell'obbligo per i CEO di seguire una formazione in cybersicurezza?",
        es: "¿Cuál es la base jurídica del requisito de que los CEO deban recibir formación en ciberseguridad?",
        pl: "Jaka jest podstawa prawna obowiązku szkolenia CEO w zakresie cyberbezpieczeństwa?",
        cs: "Jaký je právní základ pro požadavek, aby se generální ředitelé školili v kybernetické bezpečnosti?",
        pt: "Qual é a base jurídica para a exigência de que os diretores executivos têm de receber formação em cibersegurança?",
        ro: "Care este temeiul juridic pentru cerința ca directorii generali să fie formați în domeniul securității cibernetice?",
      },
      options: [
        { en: "Article 21 of the NIS2 Directive", de: "Artikel 21 der NIS2-Richtlinie", nl: "Artikel 21 van de NIS2-richtlijn", fr: "Article 21 de la directive NIS2", it: "Articolo 21 della direttiva NIS2", es: "Artículo 21 de la Directiva NIS2", pl: "Artykuł 21 dyrektywy NIS2", cs: "Článek 21 směrnice NIS2", pt: "O artigo 21 da Diretiva NIS2", ro: "Articolul 21 din Directiva NIS2" },
        { en: "Article 20(2) of the NIS2 Directive", de: "Artikel 20 Absatz 2 der NIS2-Richtlinie", nl: "Artikel 20, lid 2 van de NIS2-richtlijn", fr: "Article 20(2) de la directive NIS2", it: "Articolo 20(2) della direttiva NIS2", es: "Artículo 20(2) de la Directiva NIS2", pl: "Artykuł 20(2) dyrektywy NIS2", cs: "Článek 20(2) směrnice NIS2", pt: "O artigo 20(2) da Diretiva NIS2", ro: "Articolul 20(2) din Directiva NIS2" },
        { en: "Article 23 of the NIS2 Directive", de: "Artikel 23 der NIS2-Richtlinie", nl: "Artikel 23 van de NIS2-richtlijn", fr: "Article 23 de la directive NIS2", it: "Articolo 23 della direttiva NIS2", es: "Artículo 23 de la Directiva NIS2", pl: "Artykuł 23 dyrektywy NIS2", cs: "Článek 23 směrnice NIS2", pt: "O artigo 23 da Diretiva NIS2", ro: "Articolul 23 din Directiva NIS2" },
        { en: "BSI-Standard 200-1", de: "BSI-Standard 200-1", nl: "BSI-Standard 200-1", fr: "BSI-Standard 200-1", it: "BSI-Standard 200-1", es: "BSI-Standard 200-1", pl: "BSI-Standard 200-1", cs: "BSI-Standard 200-1", pt: "BSI-Standard 200-1", ro: "BSI-Standard 200-1" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 20(2) states that members of management bodies of essential and important entities are required to follow training.",
        de: "Artikel 20 Absatz 2 legt fest, dass Mitglieder der Leitungsorgane wesentlicher und wichtiger Einrichtungen an Schulungen teilnehmen müssen.",
        nl: "Artikel 20, lid 2 bepaalt dat leden van het leidinggevend orgaan van essentiële en belangrijke entiteiten verplicht zijn een opleiding te volgen.",
        fr: "L'article 20(2) dispose que les membres des organes de direction des entités essentielles et importantes sont tenus de suivre une formation.",
        it: "L'articolo 20(2) stabilisce che i membri degli organi di gestione dei soggetti essenziali e importanti sono tenuti a seguire una formazione.",
        es: "El artículo 20(2) establece que los miembros de los órganos de dirección de las entidades esenciales e importantes están obligados a seguir formación.",
        pl: "Artykuł 20(2) stanowi, że członkowie organów zarządzających podmiotów kluczowych i ważnych są zobowiązani do odbycia szkolenia.",
        cs: "Článek 20(2) stanoví, že členové řídicích orgánů základních a důležitých subjektů jsou povinni absolvovat školení.",
        pt: "O artigo 20(2) estabelece que os membros dos órgãos de administração das entidades essenciais e importantes são obrigados a frequentar formação.",
        ro: "Articolul 20(2) prevede că membrii organelor de conducere ale entităților esențiale și importante sunt obligați să urmeze formare.",
      },
    },
    {
      id: "3.1.3",
      question: {
        en: "What should you do with the BSI's question list according to the lesson?",
        de: "Was sollten Sie laut der Lektion mit der Fragenliste des BSI tun?",
        nl: "Wat moet u volgens de les doen met de vragenlijst van het BSI?",
        fr: "Que devez-vous faire de la liste de questions du BSI selon la leçon ?",
        it: "Cosa dovreste fare con l'elenco di domande del BSI secondo la lezione?",
        es: "¿Qué debe hacer con la lista de preguntas del BSI según la lección?",
        pl: "Co powinieneś zrobić z listą pytań BSI według lekcji?",
        cs: "Co byste podle lekce měli udělat se seznamem otázek BSI?",
        pt: "O que deve fazer com a lista de perguntas do BSI segundo a lição?",
        ro: "Ce ar trebui să faceți cu lista de întrebări a BSI potrivit lecției?",
      },
      options: [
        { en: "Submit it to the regulator as proof of compliance", de: "Sie bei der Aufsichtsbehörde als Compliance-Nachweis einreichen", nl: "Indienen bij de toezichthouder als bewijs van naleving", fr: "La soumettre à l'autorité de régulation comme preuve de conformité", it: "Presentarlo all'autorità di regolamentazione come prova di conformità", es: "Presentarla al regulador como prueba de cumplimiento", pl: "Przedłożyć ją organowi nadzoru jako dowód zgodności", cs: "Předložit ho regulačnímu orgánu jako důkaz souladu", pt: "Apresentá-la à autoridade reguladora como prova de conformidade", ro: "Să o transmiteți autorității de reglementare ca dovadă de conformitate" },
        { en: "Print it and rate each question with your CISO as confident, with help, or cannot answer", de: "Ausdrucken und gemeinsam mit Ihrem CISO jede Frage als sicher, mit Hilfe oder nicht beantwortbar bewerten", nl: "Afdrukken en met uw CISO elke vraag beoordelen als zeker, met hulp, of niet te beantwoorden", fr: "L'imprimer et évaluer chaque question avec votre CISO comme sûr, avec aide, ou ne peut pas répondre", it: "Stamparlo e valutare ogni domanda con il vostro CISO come sicuro, con aiuto o non in grado di rispondere", es: "Imprimirla y calificar cada pregunta con su CISO como seguro, con ayuda o no puede responder", pl: "Wydrukować ją i wraz z CISO ocenić każde pytanie jako pewny, z pomocą lub nie potrafię odpowiedzieć", cs: "Vytisknout ho a u každé otázky s vaším CISO ohodnotit, zda jste si jistí, potřebujete pomoc, nebo nedokážete odpovědět", pt: "Imprimi-la e classificar cada pergunta com o seu CISO como confiante, com ajuda ou não sei responder", ro: "Să o tipăriți și să evaluați fiecare întrebare împreună cu CISO ca sigur, cu ajutor sau nu pot răspunde" },
        { en: "Delegate it to your IT department for review", de: "An Ihre IT-Abteilung zur Prüfung delegieren", nl: "Delegeren aan uw IT-afdeling ter beoordeling", fr: "La déléguer à votre service informatique pour examen", it: "Delegarlo al vostro reparto IT per la revisione", es: "Delegarla a su departamento de TI para su revisión", pl: "Przekazać ją działowi IT do przeglądu", cs: "Delegovat ho na oddělení IT k přezkumu", pt: "Delegá-la no departamento de TI para revisão", ro: "Să o delegați departamentului IT pentru revizuire" },
        { en: "File it as part of your annual audit documentation", de: "Als Teil Ihrer jährlichen Auditdokumentation ablegen", nl: "Opslaan als onderdeel van uw jaarlijkse auditdocumentatie", fr: "La classer dans votre documentation d'audit annuelle", it: "Archiviarlo come parte della documentazione di audit annuale", es: "Archivarla como parte de su documentación de auditoría anual", pl: "Zarchiwizować ją jako część rocznej dokumentacji audytowej", cs: "Založit ho jako součást roční auditní dokumentace", pt: "Arquivá-la como parte da documentação anual de auditoria", ro: "Să o arhivați ca parte a documentației anuale de audit" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The lesson advises printing the questions and going through them with your CISO, rating each as confident, with help, or cannot answer - every question in the third column is a gap your training must close.",
        de: "Die Lektion empfiehlt, die Fragen auszudrucken und mit Ihrem CISO durchzugehen, wobei jede als sicher, mit Hilfe oder nicht beantwortbar eingestuft wird - jede Frage in der dritten Spalte ist eine Lücke, die Ihre Schulung schließen muss.",
        nl: "De les adviseert de vragen af te drukken en met uw CISO door te nemen, waarbij elke vraag wordt beoordeeld als zeker, met hulp, of niet te beantwoorden - elke vraag in de derde kolom is een lacune die uw opleiding moet dichten.",
        fr: "La leçon conseille d'imprimer les questions et de les passer en revue avec votre CISO, en évaluant chacune comme sûr, avec aide, ou ne peut pas répondre - chaque question de la troisième colonne est une lacune que votre formation doit combler.",
        it: "La lezione consiglia di stampare le domande ed esaminarle con il vostro CISO, valutando ciascuna come sicuro, con aiuto o non in grado di rispondere - ogni domanda nella terza colonna è una lacuna che la vostra formazione deve colmare.",
        es: "La lección aconseja imprimir las preguntas y revisarlas con su CISO, calificando cada una como seguro, con ayuda o no puede responder - cada pregunta de la tercera columna es una brecha que su formación debe cerrar.",
        pl: "Lekcja zaleca wydrukowanie pytań i omówienie ich z CISO, oceniając każde jako pewny, z pomocą lub nie potrafię odpowiedzieć - każde pytanie w trzeciej kolumnie to luka, którą musi zamknąć Twoje szkolenie.",
        cs: "Lekce doporučuje otázky vytisknout a projít je s vaším CISO, přičemž u každé ohodnotíte, zda jste si jistí, potřebujete pomoc, nebo nedokážete odpovědět. Každá otázka ve třetím sloupci je mezera, kterou musí vaše školení uzavřít.",
        pt: "A lição aconselha a imprimir as perguntas e a analisá-las com o seu CISO, classificando cada uma como confiante, com ajuda ou não sei responder. Cada pergunta na terceira coluna é uma lacuna que a sua formação tem de colmatar.",
        ro: "Lecția recomandă tipărirea întrebărilor și parcurgerea acestora împreună cu CISO, evaluând fiecare ca sigur, cu ajutor sau nu pot răspunde. Fiecare întrebare din a treia coloană este o lacună pe care formarea dumneavoastră trebuie să o acopere.",
      },
    },
    {
      id: "3.1.4",
      question: {
        en: "Are the BSI's structured questions legally binding?",
        de: "Sind die strukturierten Fragen des BSI rechtlich bindend?",
        nl: "Zijn de gestructureerde vragen van het BSI juridisch bindend?",
        fr: "Les questions structurées du BSI sont-elles juridiquement contraignantes ?",
        it: "Le domande strutturate del BSI sono giuridicamente vincolanti?",
        es: "¿Son jurídicamente vinculantes las preguntas estructuradas del BSI?",
        pl: "Czy ustrukturyzowane pytania BSI są prawnie wiążące?",
        cs: "Jsou strukturované otázky BSI právně závazné?",
        pt: "As perguntas estruturadas do BSI são juridicamente vinculativas?",
        ro: "Întrebările structurate ale BSI sunt obligatorii din punct de vedere juridic?",
      },
      options: [
        { en: "Yes, they are part of the NIS2 Directive", de: "Ja, sie sind Teil der NIS2-Richtlinie", nl: "Ja, ze maken deel uit van de NIS2-richtlijn", fr: "Oui, elles font partie de la directive NIS2", it: "Sì, fanno parte della direttiva NIS2", es: "Sí, forman parte de la Directiva NIS2", pl: "Tak, są częścią dyrektywy NIS2", cs: "Ano, jsou součástí směrnice NIS2", pt: "Sim, fazem parte da Diretiva NIS2", ro: "Da, fac parte din Directiva NIS2" },
        { en: "Yes, they are part of German national law", de: "Ja, sie sind Teil des deutschen Bundesrechts", nl: "Ja, ze maken deel uit van het Duitse nationale recht", fr: "Oui, elles font partie du droit national allemand", it: "Sì, fanno parte del diritto nazionale tedesco", es: "Sí, forman parte del derecho nacional alemán", pl: "Tak, są częścią niemieckiego prawa krajowego", cs: "Ano, jsou součástí německého vnitrostátního práva", pt: "Sim, fazem parte do direito nacional alemão", ro: "Da, fac parte din dreptul național german" },
        { en: "No, but they are the published baseline every European regulator will use", de: "Nein, aber sie sind der veröffentlichte Maßstab, den jede europäische Aufsichtsbehörde verwenden wird", nl: "Nee, maar ze zijn de gepubliceerde standaard die elke Europese toezichthouder zal hanteren", fr: "Non, mais elles constituent le référentiel publié que toute autorité de régulation européenne utilisera", it: "No, ma costituiscono il riferimento pubblicato che ogni autorità di regolamentazione europea utilizzerà", es: "No, pero son el referente publicado que utilizará todo regulador europeo", pl: "Nie, ale stanowią opublikowany punkt odniesienia, którego użyje każdy europejski organ nadzoru", cs: "Ne, ale jsou zveřejněnou základní úrovní, kterou použije každý evropský regulační orgán", pt: "Não, mas são o referencial publicado que todas as autoridades reguladoras europeias utilizarão", ro: "Nu, dar reprezintă referința publicată pe care o va utiliza fiecare autoritate de reglementare europeană" },
        { en: "No, they are only relevant for Essential entities", de: "Nein, sie gelten nur für wesentliche Einrichtungen", nl: "Nee, ze zijn alleen relevant voor essentiële entiteiten", fr: "Non, elles ne concernent que les entités essentielles", it: "No, sono rilevanti solo per i soggetti essenziali", es: "No, solo son relevantes para las entidades esenciales", pl: "Nie, dotyczą wyłącznie podmiotów kluczowych", cs: "Ne, jsou relevantní pouze pro základní subjekty", pt: "Não, só são relevantes para entidades essenciais", ro: "Nu, sunt relevante doar pentru entitățile esențiale" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The questions are not legally binding, but they are the published baseline every European regulator will use to judge whether a CEO has sufficient knowledge under Article 20(2).",
        de: "Die Fragen sind nicht rechtlich bindend, aber sie sind der veröffentlichte Maßstab, anhand dessen jede europäische Aufsichtsbehörde beurteilen wird, ob ein CEO über ausreichendes Wissen gemäß Artikel 20 Absatz 2 verfügt.",
        nl: "De vragen zijn niet juridisch bindend, maar ze vormen de gepubliceerde standaard die elke Europese toezichthouder zal gebruiken om te beoordelen of een CEO over voldoende kennis beschikt op grond van artikel 20, lid 2.",
        fr: "Les questions ne sont pas juridiquement contraignantes, mais elles constituent le référentiel publié que toute autorité de régulation européenne utilisera pour juger si un CEO dispose de connaissances suffisantes au titre de l'article 20(2).",
        it: "Le domande non sono giuridicamente vincolanti, ma costituiscono il riferimento pubblicato che ogni autorità di regolamentazione europea utilizzerà per valutare se un CEO disponga di conoscenze sufficienti ai sensi dell'articolo 20(2).",
        es: "Las preguntas no son jurídicamente vinculantes, pero son el referente publicado que utilizará todo regulador europeo para juzgar si un CEO posee conocimientos suficientes con arreglo al artículo 20(2).",
        pl: "Pytania nie są prawnie wiążące, ale stanowią opublikowany punkt odniesienia, którego użyje każdy europejski organ nadzoru do oceny, czy CEO posiada wystarczającą wiedzę zgodnie z artykułem 20(2).",
        cs: "Otázky nejsou právně závazné, ale jsou zveřejněnou základní úrovní, kterou každý evropský regulační orgán použije k posouzení, zda má generální ředitel dostatečné znalosti podle článku 20(2).",
        pt: "As perguntas não são juridicamente vinculativas, mas são o referencial publicado que todas as autoridades reguladoras europeias utilizarão para avaliar se um diretor executivo tem conhecimentos suficientes nos termos do artigo 20(2).",
        ro: "Întrebările nu sunt obligatorii din punct de vedere juridic, dar reprezintă referința publicată pe care fiecare autoritate de reglementare europeană o va utiliza pentru a evalua dacă un director general are cunoștințe suficiente în temeiul articolului 20(2).",
      },
    },
  ],
});

export default quiz;
