import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.10",
  passingScore: 75,
  questions: [
    {
      id: "3.10.1",
      question: {
        en: "What is the financial threshold for a significant incident under CIR 2024/2690?",
        de: "Welcher finanzielle Schwellenwert gilt für einen erheblichen Vorfall gemäß CIR 2024/2690?",
        nl: "Wat is de financiële drempelwaarde voor een significant incident op grond van CIR 2024/2690?",
        fr: "Quel est le seuil financier d'un incident important au titre du CIR 2024/2690 ?",
        it: "Qual è la soglia finanziaria per un incidente significativo ai sensi del CIR 2024/2690?",
        es: "¿Cuál es el umbral financiero de un incidente significativo con arreglo al CIR 2024/2690?",
        pl: "Jaki jest próg finansowy poważnego incydentu na mocy CIR 2024/2690?",
        cs: "Jaká je finanční hranice pro významný incident podle CIR 2024/2690?",
        pt: "Qual é o limiar financeiro para um incidente significativo ao abrigo do CIR 2024/2690?",
        ro: "Care este pragul financiar pentru un incident semnificativ în temeiul CIR 2024/2690?",
      },
      options: [
        { en: "One million euros", de: "Eine Million Euro", nl: "Één miljoen euro", fr: "Un million d'euros", it: "Un milione di euro", es: "Un millón de euros", pl: "Jeden milion euro", cs: "Jeden milion eur", pt: "Um milhão de euros", ro: "Un milion de euro" },
        { en: "Five hundred thousand euros or five percent of turnover, whichever is lower", de: "Fünfhunderttausend Euro oder fünf Prozent des Umsatzes, je nachdem welcher Wert niedriger ist", nl: "Vijfhonderdduizend euro of vijf procent van de omzet, afhankelijk van wat lager is", fr: "Cinq cent mille euros ou cinq pour cent du chiffre d'affaires, le montant le plus bas étant retenu", it: "Cinquecentomila euro o il cinque percento del fatturato, a seconda di quale sia inferiore", es: "Quinientos mil euros o el cinco por ciento de la facturación, lo que sea menor", pl: "Pięćset tysięcy euro lub pięć procent obrotu, w zależności od tego, która wartość jest niższa", cs: "Pět set tisíc eur nebo pět procent obratu, podle toho, co je nižší", pt: "Quinhentos mil euros ou cinco por cento do volume de negócios, consoante o que for mais baixo", ro: "Cinci sute de mii de euro sau cinci la sută din cifra de afaceri, oricare dintre acestea este mai mică" },
        { en: "Ten percent of annual revenue", de: "Zehn Prozent des Jahresumsatzes", nl: "Tien procent van de jaaromzet", fr: "Dix pour cent du chiffre d'affaires annuel", it: "Dieci percento del fatturato annuo", es: "El diez por ciento de los ingresos anuales", pl: "Dziesięć procent rocznego przychodu", cs: "Deset procent ročních tržeb", pt: "Dez por cento da receita anual", ro: "Zece la sută din venitul anual" },
        { en: "Two hundred fifty thousand euros", de: "Zweihundertfünfzigtausend Euro", nl: "Tweehonderdvijftigduizend euro", fr: "Deux cent cinquante mille euros", it: "Duecentocinquantamila euro", es: "Doscientos cincuenta mil euros", pl: "Dwieście pięćdziesiąt tysięcy euro", cs: "Dvě stě padesát tisíc eur", pt: "Duzentos e cinquenta mil euros", ro: "Două sute cincizeci de mii de euro" },
      ],
      correctIndex: 1,
      explanation: {
        en: "CIR 2024/2690 Article 3: significant if financial loss exceeds five hundred thousand euros or five percent of turnover, whichever is lower.",
        de: "CIR 2024/2690 Artikel 3: erheblich, wenn der finanzielle Verlust fünfhunderttausend Euro oder fünf Prozent des Umsatzes übersteigt, je nachdem welcher Wert niedriger ist.",
        nl: "CIR 2024/2690 Artikel 3: significant als het financieel verlies vijfhonderdduizend euro of vijf procent van de omzet overschrijdt, afhankelijk van wat lager is.",
        fr: "CIR 2024/2690 article 3 : important si la perte financière dépasse cinq cent mille euros ou cinq pour cent du chiffre d'affaires, le montant le plus bas étant retenu.",
        it: "CIR 2024/2690 articolo 3: significativo se la perdita finanziaria supera cinquecentomila euro o il cinque percento del fatturato, a seconda di quale sia inferiore.",
        es: "CIR 2024/2690 artículo 3: significativo si la pérdida financiera supera los quinientos mil euros o el cinco por ciento de la facturación, lo que sea menor.",
        pl: "CIR 2024/2690 artykuł 3: poważny, jeśli strata finansowa przekracza pięćset tysięcy euro lub pięć procent obrotu, w zależności od tego, która wartość jest niższa.",
        cs: "CIR 2024/2690 článek 3: incident je významný, pokud finanční ztráta přesáhne pět set tisíc eur nebo pět procent obratu, podle toho, co je nižší.",
        pt: "CIR 2024/2690 artigo 3: significativo se a perda financeira exceder quinhentos mil euros ou cinco por cento do volume de negócios, consoante o que for mais baixo.",
        ro: "CIR 2024/2690 articolul 3: semnificativ dacă pierderea financiară depășește cinci sute de mii de euro sau cinci la sută din cifra de afaceri, oricare dintre acestea este mai mică.",
      },
    },
    {
      id: "3.10.2",
      question: {
        en: "What does the recurring incidents rule under CIR Article 4 say?",
        de: "Was besagt die Regel zu wiederkehrenden Vorfaellen gemäß CIR Artikel 4?",
        nl: "Wat zegt de regel voor terugkerende incidenten van CIR Artikel 4?",
        fr: "Que dit la règle relative aux incidents récurrents prévue à l'article 4 du CIR ?",
        it: "Cosa dice la regola sugli incidenti ricorrenti ai sensi dell'articolo 4 del CIR?",
        es: "¿Qué dice la regla de incidentes recurrentes con arreglo al artículo 4 del CIR?",
        pl: "Co mówi reguła dotycząca powracających incydentów na mocy artykułu 4 CIR?",
        cs: "Co říká pravidlo o opakujících se incidentech podle článku 4 CIR?",
        pt: "O que diz a regra dos incidentes recorrentes ao abrigo do artigo 4 do CIR?",
        ro: "Ce prevede regula incidentelor recurente în temeiul articolului 4 din CIR?",
      },
      options: [
        { en: "Each incident must be reported individually regardless of size", de: "Jeder Vorfall muss einzeln gemeldet werden, unabhaengig von der Groesse", nl: "Elk incident moet afzonderlijk worden gemeld ongeacht de omvang", fr: "Chaque incident doit être signalé individuellement quelle que soit son ampleur", it: "Ogni incidente deve essere segnalato individualmente indipendentemente dalle dimensioni", es: "Cada incidente debe notificarse individualmente independientemente de su tamaño", pl: "Każdy incydent musi być zgłaszany indywidualnie, niezależnie od rozmiaru", cs: "Každý incident musí být ohlášen samostatně bez ohledu na rozsah", pt: "Cada incidente tem de ser notificado individualmente, independentemente da dimensão", ro: "Fiecare incident trebuie raportat individual, indiferent de amploare" },
        { en: "Two or more incidents in six months sharing the same root cause that together cross the threshold count as one significant incident", de: "Zwei oder mehr Vorfaelle innerhalb von sechs Monaten mit derselben Ursache, die zusammen den Schwellenwert überschreiten, gelten als ein erheblicher Vorfall", nl: "Twee of meer incidenten in zes maanden met dezelfde hoofdoorzaak die samen de drempel overschrijden, tellen als één significant incident", fr: "Deux incidents ou plus en six mois partageant la même cause profonde et qui dépassent ensemble le seuil comptent comme un seul incident important", it: "Due o più incidenti in sei mesi con la stessa causa principale che insieme superano la soglia contano come un unico incidente significativo", es: "Dos o más incidentes en seis meses con la misma causa raíz que juntos superan el umbral cuentan como un único incidente significativo", pl: "Dwa lub więcej incydentów w ciągu sześciu miesięcy o tej samej przyczynie źródłowej, które razem przekraczają próg, liczą się jako jeden poważny incydent", cs: "Dva nebo více incidentů za šest měsíců se stejnou hlavní příčinou, které společně překročí hranici, se počítají jako jeden významný incident", pt: "Dois ou mais incidentes em seis meses com a mesma causa raiz que, em conjunto, ultrapassem o limiar contam como um único incidente significativo", ro: "Două sau mai multe incidente în șase luni care au aceeași cauză primară și care, împreună, depășesc pragul se consideră un singur incident semnificativ" },
        { en: "Incidents more than six months old are no longer reportable", de: "Vorfaelle, die aelter als sechs Monate sind, sind nicht mehr meldepflichtig", nl: "Incidenten ouder dan zes maanden zijn niet meer meldingsplichtig", fr: "Les incidents de plus de six mois ne sont plus à déclarer", it: "Gli incidenti di oltre sei mesi non sono più soggetti a notifica", es: "Los incidentes de más de seis meses ya no son notificables", pl: "Incydenty starsze niż sześć miesięcy nie podlegają już zgłoszeniu", cs: "Incidenty starší než šest měsíců již nelze ohlašovat", pt: "Os incidentes com mais de seis meses já não são notificáveis", ro: "Incidentele mai vechi de șase luni nu mai pot fi raportate" },
        { en: "Recurring incidents are exempt from reporting if each one is individually below the threshold", de: "Wiederkehrende Vorfaelle sind von der Meldepflicht befreit, wenn jeder einzelne unter dem Schwellenwert liegt", nl: "Terugkerende incidenten zijn vrijgesteld van melding als elk afzonderlijk incident onder de drempel ligt", fr: "Les incidents récurrents sont exemptés de déclaration si chacun est individuellement en deçà du seuil", it: "Gli incidenti ricorrenti sono esenti dalla notifica se ciascuno è individualmente al di sotto della soglia", es: "Los incidentes recurrentes están exentos de notificación si cada uno está individualmente por debajo del umbral", pl: "Powracające incydenty są zwolnione ze zgłaszania, jeśli każdy z osobna jest poniżej progu", cs: "Opakující se incidenty jsou z ohlašování vyňaty, pokud je každý z nich jednotlivě pod hranicí", pt: "Os incidentes recorrentes estão isentos de notificação se cada um deles estiver individualmente abaixo do limiar", ro: "Incidentele recurente sunt scutite de raportare dacă fiecare se află individual sub prag" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The recurring incidents rule chains multiple small incidents with the same root cause into one reportable event if they collectively cross the financial threshold within six months.",
        de: "Die Regel zu wiederkehrenden Vorfaellen verkettet mehrere kleine Vorfaelle mit derselben Ursache zu einem meldepflichtigen Ereignis, wenn sie gemeinsam den finanziellen Schwellenwert innerhalb von sechs Monaten überschreiten.",
        nl: "De regel voor terugkerende incidenten koppelt meerdere kleine incidenten met dezelfde hoofdoorzaak tot één meldingsplichtige gebeurtenis als ze samen de financiële drempel overschrijden binnen zes maanden.",
        fr: "La règle relative aux incidents récurrents regroupe plusieurs petits incidents ayant la même cause profonde en un seul événement à déclarer s'ils dépassent collectivement le seuil financier en six mois.",
        it: "La regola sugli incidenti ricorrenti concatena più piccoli incidenti con la stessa causa principale in un unico evento soggetto a notifica se superano collettivamente la soglia finanziaria entro sei mesi.",
        es: "La regla de incidentes recurrentes encadena varios incidentes pequeños con la misma causa raíz en un único evento notificable si colectivamente superan el umbral financiero en seis meses.",
        pl: "Reguła powracających incydentów łączy wiele małych incydentów o tej samej przyczynie źródłowej w jedno zdarzenie podlegające zgłoszeniu, jeśli łącznie przekraczają próg finansowy w ciągu sześciu miesięcy.",
        cs: "Pravidlo o opakujících se incidentech řetězí více malých incidentů se stejnou hlavní příčinou do jedné ohlašované události, pokud společně překročí finanční hranici během šesti měsíců.",
        pt: "A regra dos incidentes recorrentes encadeia vários pequenos incidentes com a mesma causa raiz num único evento notificável se, em conjunto, ultrapassarem o limiar financeiro no prazo de seis meses.",
        ro: "Regula incidentelor recurente înlănțuie mai multe incidente mici cu aceeași cauză primară într-un singur eveniment raportabil dacă, împreună, depășesc pragul financiar în decurs de șase luni.",
      },
    },
    {
      id: "3.10.3",
      question: {
        en: "In the lesson's 'messy version' of the phishing scenario, why did the company file a protective report?",
        de: "Warum hat das Unternehmen in der 'unübersichtlichen Version' des Phishing-Szenarios eine Schutzmeldung eingereicht?",
        nl: "In de 'rommelige versie' van het phishingscenario, waarom diende het bedrijf een voorzorgsmelding in?",
        fr: "Dans la « version désordonnée » du scénario de hameçonnage de la leçon, pourquoi l'entreprise a-t-elle déposé un rapport de précaution ?",
        it: "Nella 'versione disordinata' dello scenario di phishing della lezione, perché l'azienda ha presentato una segnalazione precauzionale?",
        es: "En la «versión desordenada» del escenario de phishing de la lección, ¿por qué presentó la empresa un informe preventivo?",
        pl: "W „chaotycznej wersji” scenariusza phishingu z lekcji, dlaczego firma złożyła zgłoszenie zapobiegawcze?",
        cs: "Proč v 'nepřehledné verzi' phishingového scénáře z lekce společnost podala preventivní hlášení?",
        pt: "Na 'versão confusa' do cenário de phishing da lição, por que razão a empresa apresentou uma notificação preventiva?",
        ro: "În 'versiunea complicată' a scenariului de phishing din lecție, de ce a depus compania o raportare de precauție?",
      },
      options: [
        { en: "Because the financial loss exceeded the threshold", de: "Weil der finanzielle Verlust den Schwellenwert überschritten hat", nl: "Omdat het financieel verlies de drempel overschreed", fr: "Parce que la perte financière dépassait le seuil", it: "Perché la perdita finanziaria superava la soglia", es: "Porque la pérdida financiera superaba el umbral", pl: "Ponieważ strata finansowa przekroczyła próg", cs: "Protože finanční ztráta přesáhla hranici", pt: "Porque a perda financeira excedeu o limiar", ro: "Pentru că pierderea financiară a depășit pragul" },
        { en: "Because trade secrets were confirmed exfiltrated", de: "Weil die Exfiltration von Geschaeftsgeheimnissen bestätigtt wurde", nl: "Omdat de uitlek van bedrijfsgeheimen werd bevestigd", fr: "Parce que l'exfiltration de secrets commerciaux a été confirmée", it: "Perché è stata confermata l'esfiltrazione di segreti commerciali", es: "Porque se confirmó la exfiltración de secretos comerciales", pl: "Ponieważ potwierdzono wyprowadzenie tajemnic handlowych", cs: "Protože bylo potvrzeno odcizení obchodních tajemství", pt: "Porque se confirmou a exfiltração de segredos comerciais", ro: "Pentru că s-a confirmat exfiltrarea secretelor comerciale" },
        { en: "Because the company could not determine whether the attacker reached customer data - they could not prove it was not significant", de: "Weil das Unternehmen nicht feststellen konnte, ob der Angreifer Kundendaten erreicht hat - sie konnten nicht beweisen, dass es nicht erheblich war", nl: "Omdat het bedrijf niet kon bepalen of de aanvaller klantgegevens had bereikt - ze konden niet bewijzen dat het niet significant was", fr: "Parce que l'entreprise ne pouvait pas déterminer si l'attaquant avait atteint les données clients - elle ne pouvait pas prouver que ce n'était pas important", it: "Perché l'azienda non poteva determinare se l'attaccante avesse raggiunto i dati dei clienti - non poteva dimostrare che non fosse significativo", es: "Porque la empresa no podía determinar si el atacante había accedido a los datos de los clientes: no podía demostrar que no fuera significativo", pl: "Ponieważ firma nie mogła ustalić, czy atakujący dotarł do danych klientów - nie mogła udowodnić, że nie był to incydent poważny", cs: "Protože společnost nedokázala určit, zda se útočník dostal k zákaznickým datům: nedokázala prokázat, že incident nebyl významný", pt: "Porque a empresa não conseguiu determinar se o atacante chegou aos dados dos clientes: não conseguiu provar que não era significativo", ro: "Pentru că firma nu a putut determina dacă atacatorul a ajuns la datele clienților: nu a putut dovedi că incidentul nu era semnificativ" },
        { en: "Because the recurring incidents rule applied", de: "Weil die Regel zu wiederkehrenden Vorfaellen griff", nl: "Omdat de regel voor terugkerende incidenten van toepassing was", fr: "Parce que la règle relative aux incidents récurrents s'appliquait", it: "Perché si applicava la regola sugli incidenti ricorrenti", es: "Porque se aplicaba la regla de incidentes recurrentes", pl: "Ponieważ zastosowanie miała reguła powracających incydentów", cs: "Protože se uplatnilo pravidlo o opakujících se incidentech", pt: "Porque se aplicou a regra dos incidentes recorrentes", ro: "Pentru că s-a aplicat regula incidentelor recurente" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The company filed not because the incident was severe, but because they could not prove it was not - uncertainty required a protective filing.",
        de: "Das Unternehmen meldete nicht, weil der Vorfall schwerwiegend war, sondern weil es nicht beweisen konnte, dass er es nicht war - die Unsicherheit erforderte eine Schutzmeldung.",
        nl: "Het bedrijf meldde niet omdat het incident ernstig was, maar omdat ze niet konden bewijzen dat het dat niet was - onzekerheid vereiste een voorzorgsmelding.",
        fr: "L'entreprise a déposé non pas parce que l'incident était grave, mais parce qu'elle ne pouvait pas prouver qu'il ne l'était pas - l'incertitude exigeait un dépôt de précaution.",
        it: "L'azienda ha presentato la segnalazione non perché l'incidente fosse grave, ma perché non poteva dimostrare che non lo fosse - l'incertezza richiedeva una segnalazione precauzionale.",
        es: "La empresa presentó el informe no porque el incidente fuera grave, sino porque no podía demostrar que no lo fuera: la incertidumbre exigía una presentación preventiva.",
        pl: "Firma złożyła zgłoszenie nie dlatego, że incydent był poważny, lecz dlatego, że nie mogła udowodnić, iż nie był - niepewność wymagała zgłoszenia zapobiegawczego.",
        cs: "Společnost podala hlášení ne proto, že byl incident závažný, ale proto, že nedokázala prokázat opak. Nejistota si vyžádala preventivní hlášení.",
        pt: "A empresa apresentou a notificação não porque o incidente fosse grave, mas porque não conseguia provar que não o era. A incerteza obrigou a uma notificação preventiva.",
        ro: "Compania a depus raportarea nu pentru că incidentul era grav, ci pentru că nu putea dovedi contrariul. Incertitudinea a impus o raportare de precauție.",
      },
    },
    {
      id: "3.10.4",
      question: {
        en: "What four questions determine whether a phishing success is reportable?",
        de: "Welche vier Fragen bestimmen, ob ein erfolgreicher Phishing-Angriff meldepflichtig ist?",
        nl: "Welke vier vragen bepalen of een phishingsucces meldingsplichtig is?",
        fr: "Quelles quatre questions déterminent si un hameçonnage réussi est à déclarer ?",
        it: "Quali quattro domande determinano se un phishing riuscito è soggetto a notifica?",
        es: "¿Qué cuatro preguntas determinan si un phishing exitoso es notificable?",
        pl: "Które cztery pytania określają, czy udany phishing podlega zgłoszeniu?",
        cs: "Které čtyři otázky určují, zda je úspěšný phishing ohlašovatelný?",
        pt: "Que quatro perguntas determinam se um phishing bem-sucedido é notificável?",
        ro: "Care patru întrebări determină dacă un phishing reușit este raportabil?",
      },
      options: [
        { en: "Who was phished, what email client was used, was antivirus running, was the password strong", de: "Wer wurde per Phishing angegriffen, welcher E-Mail-Client wurde verwendet, war ein Antivirenprogramm aktiv, war das Passwort stark", nl: "Wie werd gephished, welke e-mailclient werd gebruikt, was antivirus actief, was het wachtwoord sterk", fr: "Qui a été hameçonné, quel client de messagerie a été utilisé, l'antivirus fonctionnait-il, le mot de passe était-il fort", it: "Chi è stato vittima del phishing, quale client di posta è stato usato, l'antivirus era attivo, la password era forte", es: "Quién fue víctima del phishing, qué cliente de correo se usó, estaba activo el antivirus, era fuerte la contraseña", pl: "Kto padł ofiarą phishingu, jakiego klienta poczty użyto, czy antywirus działał, czy hasło było silne", cs: "Kdo byl obětí phishingu, jaký e-mailový klient byl použit, zda běžel antivirus, zda bylo heslo silné", pt: "Quem foi vítima de phishing, que cliente de correio eletrónico foi usado, se o antivírus estava ativo, se a palavra-passe era forte", ro: "Cine a fost ținta phishingului, ce client de e-mail a fost utilizat, dacă antivirusul funcționa, dacă parola era puternică" },
        { en: "Did the attacker use the credentials, what did they access, was data exfiltrated, does the financial impact cross the threshold", de: "Hat der Angreifer die Zugangsdaten verwendet, worauf hat er zugegriffen, wurden Daten exfiltriert, überschreitet die finanzielle Auswirkung den Schwellenwert", nl: "Heeft de aanvaller de inloggegevens gebruikt, waartoe hadden ze toegang, zijn er gegevens uitgelekt, overschrijdt de financiële impact de drempel", fr: "L'attaquant a-t-il utilisé les identifiants, à quoi a-t-il accédé, des données ont-elles été exfiltrées, l'impact financier dépasse-t-il le seuil", it: "L'attaccante ha usato le credenziali, a cosa ha avuto accesso, sono stati esfiltrati dati, l'impatto finanziario supera la soglia", es: "Usó el atacante las credenciales, a qué accedió, se exfiltraron datos, el impacto financiero supera el umbral", pl: "Czy atakujący użył poświadczeń, do czego uzyskał dostęp, czy dane zostały wyprowadzone, czy skutek finansowy przekracza próg", cs: "Zda útočník přihlašovací údaje použil, k čemu získal přístup, zda byla odcizena data, zda finanční dopad překračuje hranici", pt: "Se o atacante usou as credenciais, a que acedeu, se houve exfiltração de dados, se o impacto financeiro ultrapassa o limiar", ro: "Dacă atacatorul a folosit acreditările, la ce a avut acces, dacă s-au exfiltrat date, dacă impactul financiar depășește pragul" },
        { en: "Was the employee trained, was the email flagged, was IT notified, was the account locked", de: "War der Mitarbeiter geschult, wurde die E-Mail markiert, wurde die IT benachrichtigt, wurde das Konto gesperrt", nl: "Was de medewerker getraind, werd de e-mail gemarkeerd, werd IT ingelicht, werd het account vergrendeld", fr: "L'employé était-il formé, l'e-mail a-t-il été signalé, l'informatique a-t-elle été avertie, le compte a-t-il été verrouillé", it: "Il dipendente era formato, l'e-mail è stata segnalata, l'IT è stato avvisato, l'account è stato bloccato", es: "Estaba formado el empleado, se marcó el correo, se notificó a TI, se bloqueó la cuenta", pl: "Czy pracownik był przeszkolony, czy e-mail został oznaczony, czy IT zostało powiadomione, czy konto zostało zablokowane", cs: "Zda byl zaměstnanec proškolen, zda byl e-mail označen, zda bylo informováno IT, zda byl účet uzamčen", pt: "Se o trabalhador tinha formação, se a mensagem foi assinalada, se as TI foram avisadas, se a conta foi bloqueada", ro: "Dacă angajatul era format, dacă mesajul a fost semnalat, dacă IT a fost înștiințat, dacă contul a fost blocat" },
        { en: "How many employees were targeted, how long was the account exposed, was management informed, was the regulator contacted", de: "Wie viele Mitarbeiter waren betroffen, wie lange war das Konto exponiert, wurde die Geschaeftsfuehrung informiert, wurde die Aufsichtsbehörde kontaktiert", nl: "Hoeveel medewerkers werden getarget, hoe lang was het account blootgesteld, werd de directie ingelicht, werd de toezichthouder gecontacteerd", fr: "Combien d'employés ont été ciblés, combien de temps le compte a-t-il été exposé, la direction a-t-elle été informée, l'autorité de régulation a-t-elle été contactée", it: "Quanti dipendenti sono stati presi di mira, per quanto tempo l'account è rimasto esposto, la direzione è stata informata, l'autorità di regolamentazione è stata contattata", es: "Cuántos empleados fueron atacados, cuánto tiempo estuvo expuesta la cuenta, se informó a la dirección, se contactó al regulador", pl: "Ilu pracowników było celem, jak długo konto było narażone, czy poinformowano kierownictwo, czy skontaktowano się z organem nadzoru", cs: "Kolik zaměstnanců bylo terčem, jak dlouho byl účet vystaven, zda bylo informováno vedení, zda byl kontaktován regulační orgán", pt: "Quantos trabalhadores foram visados, durante quanto tempo a conta esteve exposta, se a administração foi informada, se a autoridade reguladora foi contactada", ro: "Câți angajați au fost vizați, cât timp a fost expus contul, dacă a fost informată conducerea, dacă a fost contactată autoritatea de reglementare" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Four questions: has the attacker used the credentials, what did those credentials access, was data exfiltrated, does this cross the CIR thresholds.",
        de: "Vier Fragen: Hat der Angreifer die Zugangsdaten verwendet, worauf hatten diese Zugangsdaten Zugriff, wurden Daten exfiltriert, überschreitet dies die CIR-Schwellenwerte.",
        nl: "Vier vragen: heeft de aanvaller de inloggegevens gebruikt, waartoe gaven die inloggegevens toegang, zijn er gegevens uitgelekt, overschrijdt dit de CIR-drempelwaarden.",
        fr: "Quatre questions : l'attaquant a-t-il utilisé les identifiants, à quoi ces identifiants donnaient-ils accès, des données ont-elles été exfiltrées, cela dépasse-t-il les seuils du CIR.",
        it: "Quattro domande: l'attaccante ha usato le credenziali, a cosa davano accesso tali credenziali, sono stati esfiltrati dati, questo supera le soglie del CIR.",
        es: "Cuatro preguntas: usó el atacante las credenciales, a qué daban acceso esas credenciales, se exfiltraron datos, supera esto los umbrales del CIR.",
        pl: "Cztery pytania: czy atakujący użył poświadczeń, do czego te poświadczenia dawały dostęp, czy dane zostały wyprowadzone, czy przekracza to progi CIR.",
        cs: "Čtyři otázky: zda útočník přihlašovací údaje použil, k čemu tyto údaje umožnily přístup, zda byla odcizena data, zda to překračuje hranice CIR.",
        pt: "Quatro perguntas: se o atacante usou as credenciais, a que essas credenciais davam acesso, se houve exfiltração de dados, se isto ultrapassa os limiares do CIR.",
        ro: "Patru întrebări: dacă atacatorul a folosit acreditările, la ce dădeau acces acele acreditări, dacă s-au exfiltrat date, dacă acest lucru depășește pragurile CIR.",
      },
    },
  ],
});

export default quiz;
