import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.11",
  passingScore: 75,
  questions: [
    {
      id: "3.11.1",
      question: {
        en: "Why does the lesson say Option B (fix it, say nothing) is risky even though the gap is resolved?",
        de: "Warum bezeichnet die Lektion Option B (beheben, nichts sagen) als riskant, obwohl die Lücke behoben ist?",
        nl: "Waarom zegt de les dat Optie B (oplossen, niets zeggen) riskant is, ook al is de lacune verholpen?",
        fr: "Pourquoi la leçon affirme-t-elle que l'option B (corriger, ne rien dire) est risquée même si la lacune est résolue ?",
        it: "Perché la lezione afferma che l'opzione B (correggere, non dire nulla) è rischiosa anche se la lacuna è risolta?",
        es: "¿Por qué dice la lección que la opción B (arreglarlo, no decir nada) es arriesgada aunque la brecha esté resuelta?",
        pl: "Dlaczego lekcja mówi, że opcja B (napraw, nic nie mów) jest ryzykowna, mimo że luka została usunięta?",
      },
      options: [
        { en: "Because the regulator requires disclosure of all past gaps", de: "Weil die Aufsichtsbehörde die Offenlegung aller vergangenen Lücken verlangt", nl: "Omdat de toezichthouder de openbaarmaking van alle vroegere lacunes vereist", fr: "Parce que l'autorité de régulation exige la divulgation de toutes les lacunes passées", it: "Perché l'autorità di regolamentazione richiede la divulgazione di tutte le lacune passate", es: "Porque el regulador exige la divulgación de todas las brechas pasadas", pl: "Ponieważ organ nadzoru wymaga ujawnienia wszystkich przeszłych luk" },
        { en: "Because timestamps exist, old archives survive, and someone may mention the fix in an interview - it sounds like concealment even if unintended", de: "Weil Zeitstempel existieren, alte Archive ueberleben und jemand die Behebung in einem Gespraech erwaehnen koennte - es wirkt wie Vertuschung, selbst wenn unbeabsichtigt", nl: "Omdat tijdstempels bestaan, oude archieven overleven en iemand de oplossing in een gesprek kan noemen - het klinkt als verhulling, ook al was dat niet de bedoeling", fr: "Parce que les horodatages existent, les anciennes archives subsistent, et quelqu'un peut mentionner la correction lors d'un entretien - cela ressemble à une dissimulation même si ce n'est pas intentionnel", it: "Perché i timestamp esistono, i vecchi archivi sopravvivono e qualcuno potrebbe menzionare la correzione in un colloquio - sembra un occultamento anche se non intenzionale", es: "Porque existen marcas de tiempo, sobreviven archivos antiguos y alguien puede mencionar la corrección en una entrevista; parece ocultamiento aunque no sea intencionado", pl: "Ponieważ istnieją znaczniki czasu, stare archiwa przetrwają, a ktoś może wspomnieć o naprawie podczas rozmowy - brzmi to jak ukrywanie, nawet jeśli niezamierzone" },
        { en: "Because fixing without disclosure is a criminal offence", de: "Weil Beheben ohne Offenlegung eine Straftat ist", nl: "Omdat oplossen zonder openbaarmaking een strafbaar feit is", fr: "Parce que corriger sans divulgation est une infraction pénale", it: "Perché correggere senza divulgazione è un reato penale", es: "Porque arreglarlo sin divulgación es un delito penal", pl: "Ponieważ naprawa bez ujawnienia jest przestępstwem" },
        { en: "Because the auditor always checks backup encryption specifically", de: "Weil der Auditor immer gezielt die Backup-Verschluesselung prüft", nl: "Omdat de auditor altijd specifiek back-upversleuteling controleert", fr: "Parce que l'auditeur vérifie toujours spécifiquement le chiffrement des sauvegardes", it: "Perché l'auditor controlla sempre specificamente la cifratura dei backup", es: "Porque el auditor siempre comprueba específicamente el cifrado de las copias de seguridad", pl: "Ponieważ audytor zawsze sprawdza konkretnie szyfrowanie kopii zapasowych" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Timestamps exist, old unencrypted archives survive, and someone may mention the fix in an interview. The auditor pieces the timeline together and it sounds like concealment even if unintended.",
        de: "Zeitstempel existieren, alte unverschluesselte Archive ueberleben und jemand koennte die Behebung in einem Gespraech erwaehnen. Der Auditor setzt die Zeitleiste zusammen und es wirkt wie Vertuschung, selbst wenn unbeabsichtigt.",
        nl: "Tijdstempels bestaan, oude onversleutelde archieven overleven en iemand kan de oplossing noemen in een gesprek. De auditor reconstrueert de tijdlijn en het klinkt als verhulling, ook al was dat niet de bedoeling.",
        fr: "Les horodatages existent, les anciennes archives non chiffrées subsistent, et quelqu'un peut mentionner la correction lors d'un entretien. L'auditeur reconstitue la chronologie et cela ressemble à une dissimulation même si ce n'est pas intentionnel.",
        it: "I timestamp esistono, i vecchi archivi non cifrati sopravvivono e qualcuno potrebbe menzionare la correzione in un colloquio. L'auditor ricostruisce la cronologia e sembra un occultamento anche se non intenzionale.",
        es: "Existen marcas de tiempo, sobreviven archivos antiguos sin cifrar y alguien puede mencionar la corrección en una entrevista. El auditor reconstruye la cronología y parece ocultamiento aunque no sea intencionado.",
        pl: "Istnieją znaczniki czasu, stare niezaszyfrowane archiwa przetrwają, a ktoś może wspomnieć o naprawie podczas rozmowy. Audytor składa oś czasu i brzmi to jak ukrywanie, nawet jeśli niezamierzone.",
      },
    },
    {
      id: "3.11.2",
      question: {
        en: "What does Article 21(2)(f) of NIS2 require that makes finding your own gaps the expected state?",
        de: "Was verlangt Artikel 21 Absatz 2 Buchstabe f der NIS2, das die Entdeckung eigener Lücken zum erwarteten Zustand macht?",
        nl: "Wat vereist Artikel 21(2)(f) van NIS2 dat het vinden van uw eigen lacunes de verwachte toestand maakt?",
        fr: "Qu'exige l'article 21(2)(f) de NIS2 qui fait de la détection de vos propres lacunes l'état attendu ?",
        it: "Cosa richiede l'articolo 21(2)(f) di NIS2 che rende l'individuazione delle proprie lacune lo stato atteso?",
        es: "¿Qué exige el artículo 21(2)(f) de NIS2 que hace que detectar sus propias brechas sea el estado esperado?",
        pl: "Czego wymaga artykuł 21(2)(f) NIS2, co sprawia, że wykrywanie własnych luk jest stanem oczekiwanym?",
      },
      options: [
        { en: "Annual penetration testing by an external firm", de: "Jährliche Penetrationstests durch eine externe Firma", nl: "Jaarlijkse penetratietests door een externe firma", fr: "Des tests d'intrusion annuels par une société externe", it: "Test di penetrazione annuali da parte di una società esterna", es: "Pruebas de penetración anuales por una empresa externa", pl: "Coroczne testy penetracyjne przeprowadzane przez firmę zewnętrzną" },
        { en: "Policies and procedures to assess the effectiveness of cybersecurity risk-management measures", de: "Konzepte und Verfahren zur Bewertung der Wirksamkeit von Risikomanagementmassnahmen im Bereich der Cybersicherheit", nl: "Beleid en procedures om de effectiviteit van cyberbeveiligingsrisicobeheermaatregelen te beoordelen", fr: "Des politiques et des procédures pour évaluer l'efficacité des mesures de gestion des risques de cybersécurité", it: "Politiche e procedure per valutare l'efficacia delle misure di gestione dei rischi di cybersicurezza", es: "Políticas y procedimientos para evaluar la eficacia de las medidas de gestión de riesgos de ciberseguridad", pl: "Polityki i procedury oceny skuteczności środków zarządzania ryzykiem cyberbezpieczeństwa" },
        { en: "Mandatory bug bounty programmes", de: "Verpflichtende Bug-Bounty-Programme", nl: "Verplichte bug-bountyprogramma's", fr: "Des programmes de primes aux bogues obligatoires", it: "Programmi di bug bounty obbligatori", es: "Programas obligatorios de recompensas por errores", pl: "Obowiązkowe programy bug bounty" },
        { en: "Quarterly vulnerability scans of all systems", de: "Vierteljährliche Schwachstellenscans aller Systeme", nl: "Kwartaallijkse kwetsbaarheidsscans van alle systemen", fr: "Des analyses de vulnérabilité trimestrielles de tous les systèmes", it: "Scansioni trimestrali delle vulnerabilità di tutti i sistemi", es: "Análisis trimestrales de vulnerabilidades de todos los sistemas", pl: "Kwartalne skany podatności wszystkich systemów" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 21(2)(f) requires policies and procedures to assess the effectiveness of cybersecurity risk-management measures - the law expects you to find your own gaps.",
        de: "Artikel 21 Absatz 2 Buchstabe f verlangt Konzepte und Verfahren zur Bewertung der Wirksamkeit von Risikomanagementmassnahmen im Bereich der Cybersicherheit - das Gesetz erwartet, dass Sie Ihre eigenen Lücken finden.",
        nl: "Artikel 21(2)(f) vereist beleid en procedures om de effectiviteit van cyberbeveiligingsrisicobeheermaatregelen te beoordelen - de wet verwacht dat u uw eigen lacunes vindt.",
        fr: "L'article 21(2)(f) exige des politiques et des procédures pour évaluer l'efficacité des mesures de gestion des risques de cybersécurité - la loi attend de vous que vous détectiez vos propres lacunes.",
        it: "L'articolo 21(2)(f) richiede politiche e procedure per valutare l'efficacia delle misure di gestione dei rischi di cybersicurezza - la legge si aspetta che individuiate le vostre lacune.",
        es: "El artículo 21(2)(f) exige políticas y procedimientos para evaluar la eficacia de las medidas de gestión de riesgos de ciberseguridad: la ley espera que detecte sus propias brechas.",
        pl: "Artykuł 21(2)(f) wymaga polityk i procedur oceny skuteczności środków zarządzania ryzykiem cyberbezpieczeństwa - prawo oczekuje, że sam wykryjesz swoje luki.",
      },
    },
    {
      id: "3.11.3",
      question: {
        en: "What is the typical outcome of good-faith disclosure versus discovered concealment?",
        de: "Was ist das typische Ergebnis einer gutglaeubigen Offenlegung im Vergleich zu entdeckter Vertuschung?",
        nl: "Wat is het typische resultaat van openbaarmaking te goeder trouw versus ontdekte verhulling?",
        fr: "Quel est le résultat typique d'une divulgation de bonne foi par rapport à une dissimulation découverte ?",
        it: "Qual è il risultato tipico di una divulgazione in buona fede rispetto a un occultamento scoperto?",
        es: "¿Cuál es el resultado típico de la divulgación de buena fe frente al ocultamiento descubierto?",
        pl: "Jaki jest typowy rezultat ujawnienia w dobrej wierze w porównaniu z wykrytym ukrywaniem?",
      },
      options: [
        { en: "Both result in the same fine", de: "Beides fuehrt zur gleichen Geldstrafe", nl: "Beide leiden tot dezelfde boete", fr: "Les deux entraînent la même amende", it: "Entrambi comportano la stessa sanzione", es: "Ambos resultan en la misma multa", pl: "Oba skutkują tą samą karą" },
        { en: "Disclosure typically results in a remediation order or warning; concealment typically results in a fine plus ongoing monitoring", de: "Offenlegung fuehrt typischerweise zu einer Abhilfeanordnung oder Verwarnung; Vertuschung fuehrt typischerweise zu einem Bussgeld plus laufender Ueberwachung", nl: "Openbaarmaking leidt doorgaans tot een herstelorder of waarschuwing; verhulling leidt doorgaans tot een boete plus voortdurende monitoring", fr: "La divulgation entraîne généralement une injonction de remédiation ou un avertissement ; la dissimulation entraîne généralement une amende plus une surveillance continue", it: "La divulgazione comporta tipicamente un'ingiunzione di correzione o un avvertimento; l'occultamento comporta tipicamente una sanzione più un monitoraggio continuo", es: "La divulgación suele resultar en una orden de remediación o advertencia; el ocultamiento suele resultar en una multa más monitorización continua", pl: "Ujawnienie zwykle skutkuje nakazem naprawczym lub ostrzeżeniem; ukrywanie zwykle skutkuje karą oraz stałym monitorowaniem" },
        { en: "Disclosure results in no consequences; concealment results in licence revocation", de: "Offenlegung hat keine Konsequenzen; Vertuschung fuehrt zum Lizenzentzug", nl: "Openbaarmaking heeft geen gevolgen; verhulling leidt tot intrekking van de vergunning", fr: "La divulgation n'a aucune conséquence ; la dissimulation entraîne le retrait de la licence", it: "La divulgazione non ha conseguenze; l'occultamento comporta la revoca della licenza", es: "La divulgación no tiene consecuencias; el ocultamiento resulta en la revocación de la licencia", pl: "Ujawnienie nie ma konsekwencji; ukrywanie skutkuje cofnięciem licencji" },
        { en: "Disclosure results in a public reprimand; concealment results in criminal prosecution", de: "Offenlegung fuehrt zu einer oeffentlichen Ruege; Vertuschung fuehrt zu strafrechtlicher Verfolgung", nl: "Openbaarmaking leidt tot een publieke berisping; verhulling leidt tot strafrechtelijke vervolging", fr: "La divulgation entraîne une réprimande publique ; la dissimulation entraîne des poursuites pénales", it: "La divulgazione comporta un richiamo pubblico; l'occultamento comporta un'azione penale", es: "La divulgación resulta en una amonestación pública; el ocultamiento resulta en un proceso penal", pl: "Ujawnienie skutkuje publiczną naganą; ukrywanie skutkuje postępowaniem karnym" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Good-faith disclosure typically results in a remediation order or warning, not a fine. Discovered concealment typically results in a fine plus ongoing monitoring, and the CEO's credibility is damaged for years.",
        de: "Gutglaeubige Offenlegung fuehrt typischerweise zu einer Abhilfeanordnung oder Verwarnung, nicht zu einem Bussgeld. Entdeckte Vertuschung fuehrt typischerweise zu einem Bussgeld plus laufender Ueberwachung, und die Glaubwürdigkeit des CEO ist für Jahre beschädigt.",
        nl: "Openbaarmaking te goeder trouw leidt doorgaans tot een herstelorder of waarschuwing, niet tot een boete. Ontdekte verhulling leidt doorgaans tot een boete plus voortdurende monitoring, en de geloofwaardigheid van de CEO is jarenlang aangetast.",
        fr: "La divulgation de bonne foi entraîne généralement une injonction de remédiation ou un avertissement, pas une amende. La dissimulation découverte entraîne généralement une amende plus une surveillance continue, et la crédibilité du CEO est entachée pendant des années.",
        it: "La divulgazione in buona fede comporta tipicamente un'ingiunzione di correzione o un avvertimento, non una sanzione. L'occultamento scoperto comporta tipicamente una sanzione più un monitoraggio continuo, e la credibilità del CEO è danneggiata per anni.",
        es: "La divulgación de buena fe suele resultar en una orden de remediación o advertencia, no en una multa. El ocultamiento descubierto suele resultar en una multa más monitorización continua, y la credibilidad del CEO queda dañada durante años.",
        pl: "Ujawnienie w dobrej wierze zwykle skutkuje nakazem naprawczym lub ostrzeżeniem, a nie karą. Wykryte ukrywanie zwykle skutkuje karą oraz stałym monitorowaniem, a wiarygodność CEO jest nadszarpnięta na lata.",
      },
    },
    {
      id: "3.11.4",
      question: {
        en: "In Option C, who should the pre-audit disclosure letter come from?",
        de: "Von wem sollte in Option C der Offenlegungsbrief vor dem Audit stammen?",
        nl: "Van wie moet in Optie C de openbaarmakingsbrief vóór de audit afkomstig zijn?",
        fr: "Dans l'option C, de qui la lettre de divulgation préalable à l'audit doit-elle émaner ?",
        it: "Nell'opzione C, da chi dovrebbe provenire la lettera di divulgazione precedente all'audit?",
        es: "En la opción C, ¿de quién debe proceder la carta de divulgación previa a la auditoría?",
        pl: "W opcji C, od kogo powinno pochodzić pismo ujawniające przed audytem?",
      },
      options: [
        { en: "The CISO", de: "Dem CISO", nl: "De CISO", fr: "Le CISO", it: "Il CISO", es: "El CISO", pl: "CISO" },
        { en: "The compliance officer", de: "Dem Compliance-Beauftragten", nl: "De compliance-officer", fr: "Le responsable de la conformité", it: "Il responsabile della conformità", es: "El responsable de cumplimiento", pl: "Inspektor ds. zgodności" },
        { en: "The CEO personally", de: "Dem CEO persönlich", nl: "De CEO persoonlijk", fr: "Le CEO personnellement", it: "Il CEO personalmente", es: "El CEO personalmente", pl: "Osobiście CEO" },
        { en: "External legal counsel", de: "Externen Rechtsberatern", nl: "Externe juridische adviseurs", fr: "Un conseil juridique externe", it: "Un consulente legale esterno", es: "Asesoría jurídica externa", pl: "Zewnętrzny radca prawny" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The letter comes from you, the CEO. You personally write to the auditor before the audit - what was found, when, what was done, what the new controls look like.",
        de: "Der Brief kommt von Ihnen, dem CEO. Sie schreiben persönlich an den Auditor vor dem Audit - was gefunden wurde, wann, was unternommen wurde und wie die neuen Kontrollen aussehen.",
        nl: "De brief is van u, de CEO. U schrijft persoonlijk aan de auditor vóór de audit - wat er gevonden is, wanneer, wat er gedaan is en hoe de nieuwe maatregelen eruitzien.",
        fr: "La lettre émane de vous, le CEO. Vous écrivez personnellement à l'auditeur avant l'audit - ce qui a été trouvé, quand, ce qui a été fait et à quoi ressemblent les nouveaux contrôles.",
        it: "La lettera proviene da voi, il CEO. Scrivete personalmente all'auditor prima dell'audit - cosa è stato trovato, quando, cosa è stato fatto e come si presentano i nuovi controlli.",
        es: "La carta procede de usted, el CEO. Usted escribe personalmente al auditor antes de la auditoría: qué se encontró, cuándo, qué se hizo y cómo son los nuevos controles.",
        pl: "Pismo pochodzi od Ciebie, CEO. Osobiście piszesz do audytora przed audytem - co znaleziono, kiedy, co zrobiono i jak wyglądają nowe kontrole.",
      },
    },
  ],
});

export default quiz;
