import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.11",
  passingScore: 75,
  questions: [
    {
      id: "3.11.1",
      question: {
        en: "Why does the lesson say Option B (fix it, say nothing) is risky even though the gap is resolved?",
        de: "Warum bezeichnet die Lektion Option B (beheben, nichts sagen) als riskant, obwohl die Lücke behoben ist?",
        nl: "Waarom zegt de les dat Optie B (oplossen, niets zeggen) riskant is, ook al is de lacune verholpen?",
        fr: "Pourquoi la leçon affirme-t-elle que l'option B (corriger, ne rien dire) est risquée même si la lacune est résolue ?",
        it: "Perché la lezione afferma che l'opzione B (correggere, non dire nulla) è rischiosa anche se la lacuna è risolta?",
        es: "¿Por qué dice la lección que la opción B (arreglarlo, no decir nada) es arriesgada aunque la brecha esté resuelta?",
        pl: "Dlaczego lekcja mówi, że opcja B (napraw, nic nie mów) jest ryzykowna, mimo że luka została usunięta?",
        cs: "Proč lekce uvádí, že možnost B (opravit a mlčet) je riziková, přestože je mezera vyřešena?",
        pt: "Por que razão a lição diz que a Opção B (corrigir e nada dizer) é arriscada mesmo com a lacuna resolvida?",
        ro: "De ce afirmă lecția că Opțiunea B (remediezi și nu spui nimic) este riscantă chiar dacă lacuna este rezolvată?",
      },
      options: [
        { en: "Because the regulator requires disclosure of all past gaps", de: "Weil die Aufsichtsbehörde die Offenlegung aller vergangenen Lücken verlangt", nl: "Omdat de toezichthouder de openbaarmaking van alle vroegere lacunes vereist", fr: "Parce que l'autorité de régulation exige la divulgation de toutes les lacunes passées", it: "Perché l'autorità di regolamentazione richiede la divulgazione di tutte le lacune passate", es: "Porque el regulador exige la divulgación de todas las brechas pasadas", pl: "Ponieważ organ nadzoru wymaga ujawnienia wszystkich przeszłych luk", cs: "Protože regulační orgán vyžaduje zveřejnění všech minulých mezer", pt: "Porque a autoridade reguladora exige a divulgação de todas as lacunas passadas", ro: "Pentru că autoritatea de reglementare impune divulgarea tuturor lacunelor anterioare" },
        { en: "Because timestamps exist, old archives survive, and someone may mention the fix in an interview - it sounds like concealment even if unintended", de: "Weil Zeitstempel existieren, alte Archive ueberleben und jemand die Behebung in einem Gespraech erwaehnen koennte - es wirkt wie Vertuschung, selbst wenn unbeabsichtigt", nl: "Omdat tijdstempels bestaan, oude archieven overleven en iemand de oplossing in een gesprek kan noemen - het klinkt als verhulling, ook al was dat niet de bedoeling", fr: "Parce que les horodatages existent, les anciennes archives subsistent, et quelqu'un peut mentionner la correction lors d'un entretien - cela ressemble à une dissimulation même si ce n'est pas intentionnel", it: "Perché i timestamp esistono, i vecchi archivi sopravvivono e qualcuno potrebbe menzionare la correzione in un colloquio - sembra un occultamento anche se non intenzionale", es: "Porque existen marcas de tiempo, sobreviven archivos antiguos y alguien puede mencionar la corrección en una entrevista; parece ocultamiento aunque no sea intencionado", pl: "Ponieważ istnieją znaczniki czasu, stare archiwa przetrwają, a ktoś może wspomnieć o naprawie podczas rozmowy - brzmi to jak ukrywanie, nawet jeśli niezamierzone", cs: "Protože existují časové značky, staré archivy přetrvávají a někdo se může o opravě zmínit při pohovoru. Působí to jako zatajování, i když nezáměrné", pt: "Porque existem marcas temporais, os arquivos antigos sobrevivem e alguém pode mencionar a correção numa entrevista. Parece ocultação, ainda que não intencional", ro: "Pentru că există marcaje temporale, arhivele vechi persistă și cineva poate menționa remedierea într-un interviu. Pare o disimulare, chiar dacă neintenționată" },
        { en: "Because fixing without disclosure is a criminal offence", de: "Weil Beheben ohne Offenlegung eine Straftat ist", nl: "Omdat oplossen zonder openbaarmaking een strafbaar feit is", fr: "Parce que corriger sans divulgation est une infraction pénale", it: "Perché correggere senza divulgazione è un reato penale", es: "Porque arreglarlo sin divulgación es un delito penal", pl: "Ponieważ naprawa bez ujawnienia jest przestępstwem", cs: "Protože oprava bez zveřejnění je trestným činem", pt: "Porque corrigir sem divulgar é um crime", ro: "Pentru că remedierea fără divulgare este o infracțiune" },
        { en: "Because the auditor always checks backup encryption specifically", de: "Weil der Auditor immer gezielt die Backup-Verschluesselung prüft", nl: "Omdat de auditor altijd specifiek back-upversleuteling controleert", fr: "Parce que l'auditeur vérifie toujours spécifiquement le chiffrement des sauvegardes", it: "Perché l'auditor controlla sempre specificamente la cifratura dei backup", es: "Porque el auditor siempre comprueba específicamente el cifrado de las copias de seguridad", pl: "Ponieważ audytor zawsze sprawdza konkretnie szyfrowanie kopii zapasowych", cs: "Protože auditor vždy kontroluje konkrétně šifrování záloh", pt: "Porque o auditor verifica sempre especificamente a cifragem das cópias de segurança", ro: "Pentru că auditorul verifică întotdeauna în mod specific criptarea copiilor de rezervă" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Timestamps exist, old unencrypted archives survive, and someone may mention the fix in an interview. The auditor pieces the timeline together and it sounds like concealment even if unintended.",
        de: "Zeitstempel existieren, alte unverschluesselte Archive ueberleben und jemand koennte die Behebung in einem Gespraech erwaehnen. Der Auditor setzt die Zeitleiste zusammen und es wirkt wie Vertuschung, selbst wenn unbeabsichtigt.",
        nl: "Tijdstempels bestaan, oude onversleutelde archieven overleven en iemand kan de oplossing noemen in een gesprek. De auditor reconstrueert de tijdlijn en het klinkt als verhulling, ook al was dat niet de bedoeling.",
        fr: "Les horodatages existent, les anciennes archives non chiffrées subsistent, et quelqu'un peut mentionner la correction lors d'un entretien. L'auditeur reconstitue la chronologie et cela ressemble à une dissimulation même si ce n'est pas intentionnel.",
        it: "I timestamp esistono, i vecchi archivi non cifrati sopravvivono e qualcuno potrebbe menzionare la correzione in un colloquio. L'auditor ricostruisce la cronologia e sembra un occultamento anche se non intenzionale.",
        es: "Existen marcas de tiempo, sobreviven archivos antiguos sin cifrar y alguien puede mencionar la corrección en una entrevista. El auditor reconstruye la cronología y parece ocultamiento aunque no sea intencionado.",
        pl: "Istnieją znaczniki czasu, stare niezaszyfrowane archiwa przetrwają, a ktoś może wspomnieć o naprawie podczas rozmowy. Audytor składa oś czasu i brzmi to jak ukrywanie, nawet jeśli niezamierzone.",
        cs: "Existují časové značky, staré nešifrované archivy přetrvávají a někdo se může o opravě zmínit při pohovoru. Auditor si časovou osu poskládá a působí to jako zatajování, i když nezáměrné.",
        pt: "Existem marcas temporais, os arquivos antigos não cifrados sobrevivem e alguém pode mencionar a correção numa entrevista. O auditor reconstitui a cronologia e parece ocultação, ainda que não intencional.",
        ro: "Există marcaje temporale, arhivele vechi necriptate persistă și cineva poate menționa remedierea într-un interviu. Auditorul reconstituie cronologia și pare o disimulare, chiar dacă neintenționată.",
      },
    },
    {
      id: "3.11.2",
      question: {
        en: "What does Article 21(2)(f) of NIS2 require that makes finding your own gaps the expected state?",
        de: "Was verlangt Artikel 21 Absatz 2 Buchstabe f der NIS2, das die Entdeckung eigener Lücken zum erwarteten Zustand macht?",
        nl: "Wat vereist Artikel 21(2)(f) van NIS2 dat het vinden van uw eigen lacunes de verwachte toestand maakt?",
        fr: "Qu'exige l'article 21(2)(f) de NIS2 qui fait de la détection de vos propres lacunes l'état attendu ?",
        it: "Cosa richiede l'articolo 21(2)(f) di NIS2 che rende l'individuazione delle proprie lacune lo stato atteso?",
        es: "¿Qué exige el artículo 21(2)(f) de NIS2 que hace que detectar sus propias brechas sea el estado esperado?",
        pl: "Czego wymaga artykuł 21(2)(f) NIS2, co sprawia, że wykrywanie własnych luk jest stanem oczekiwanym?",
        cs: "Co vyžaduje článek 21(2)(f) NIS2, kvůli čemu je odhalování vlastních mezer očekávaným stavem?",
        pt: "O que exige o artigo 21(2)(f) da NIS2 que torna a deteção das suas próprias lacunas o estado esperado?",
        ro: "Ce impune articolul 21(2)(f) din NIS2 care face din identificarea propriilor lacune starea așteptată?",
      },
      options: [
        { en: "Annual penetration testing by an external firm", de: "Jährliche Penetrationstests durch eine externe Firma", nl: "Jaarlijkse penetratietests door een externe firma", fr: "Des tests d'intrusion annuels par une société externe", it: "Test di penetrazione annuali da parte di una società esterna", es: "Pruebas de penetración anuales por una empresa externa", pl: "Coroczne testy penetracyjne przeprowadzane przez firmę zewnętrzną", cs: "Roční penetrační testování externí firmou", pt: "Testes de penetração anuais por uma empresa externa", ro: "Teste de penetrare anuale efectuate de o firmă externă" },
        { en: "Policies and procedures to assess the effectiveness of cybersecurity risk-management measures", de: "Konzepte und Verfahren zur Bewertung der Wirksamkeit von Risikomanagementmassnahmen im Bereich der Cybersicherheit", nl: "Beleid en procedures om de effectiviteit van cyberbeveiligingsrisicobeheermaatregelen te beoordelen", fr: "Des politiques et des procédures pour évaluer l'efficacité des mesures de gestion des risques de cybersécurité", it: "Politiche e procedure per valutare l'efficacia delle misure di gestione dei rischi di cybersicurezza", es: "Políticas y procedimientos para evaluar la eficacia de las medidas de gestión de riesgos de ciberseguridad", pl: "Polityki i procedury oceny skuteczności środków zarządzania ryzykiem cyberbezpieczeństwa", cs: "Politiky a postupy k posouzení účinnosti opatření k řízení kybernetických bezpečnostních rizik", pt: "Políticas e procedimentos para avaliar a eficácia das medidas de gestão de riscos de cibersegurança", ro: "Politici și proceduri pentru evaluarea eficacității măsurilor de gestionare a riscurilor de securitate cibernetică" },
        { en: "Mandatory bug bounty programmes", de: "Verpflichtende Bug-Bounty-Programme", nl: "Verplichte bug-bountyprogramma's", fr: "Des programmes de primes aux bogues obligatoires", it: "Programmi di bug bounty obbligatori", es: "Programas obligatorios de recompensas por errores", pl: "Obowiązkowe programy bug bounty", cs: "Povinné programy odměn za nalezení chyb", pt: "Programas obrigatórios de recompensa por deteção de falhas", ro: "Programe obligatorii de recompensare a descoperirii defectelor" },
        { en: "Quarterly vulnerability scans of all systems", de: "Vierteljährliche Schwachstellenscans aller Systeme", nl: "Kwartaallijkse kwetsbaarheidsscans van alle systemen", fr: "Des analyses de vulnérabilité trimestrielles de tous les systèmes", it: "Scansioni trimestrali delle vulnerabilità di tutti i sistemi", es: "Análisis trimestrales de vulnerabilidades de todos los sistemas", pl: "Kwartalne skany podatności wszystkich systemów", cs: "Čtvrtletní kontroly zranitelností všech systémů", pt: "Análises trimestrais de vulnerabilidades de todos os sistemas", ro: "Scanări trimestriale de vulnerabilități ale tuturor sistemelor" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 21(2)(f) requires policies and procedures to assess the effectiveness of cybersecurity risk-management measures - the law expects you to find your own gaps.",
        de: "Artikel 21 Absatz 2 Buchstabe f verlangt Konzepte und Verfahren zur Bewertung der Wirksamkeit von Risikomanagementmassnahmen im Bereich der Cybersicherheit - das Gesetz erwartet, dass Sie Ihre eigenen Lücken finden.",
        nl: "Artikel 21(2)(f) vereist beleid en procedures om de effectiviteit van cyberbeveiligingsrisicobeheermaatregelen te beoordelen - de wet verwacht dat u uw eigen lacunes vindt.",
        fr: "L'article 21(2)(f) exige des politiques et des procédures pour évaluer l'efficacité des mesures de gestion des risques de cybersécurité - la loi attend de vous que vous détectiez vos propres lacunes.",
        it: "L'articolo 21(2)(f) richiede politiche e procedure per valutare l'efficacia delle misure di gestione dei rischi di cybersicurezza - la legge si aspetta che individuiate le vostre lacune.",
        es: "El artículo 21(2)(f) exige políticas y procedimientos para evaluar la eficacia de las medidas de gestión de riesgos de ciberseguridad: la ley espera que detecte sus propias brechas.",
        pl: "Artykuł 21(2)(f) wymaga polityk i procedur oceny skuteczności środków zarządzania ryzykiem cyberbezpieczeństwa - prawo oczekuje, że sam wykryjesz swoje luki.",
        cs: "Článek 21(2)(f) vyžaduje politiky a postupy k posouzení účinnosti opatření k řízení kybernetických bezpečnostních rizik. Zákon očekává, že své vlastní mezery odhalíte sami.",
        pt: "O artigo 21(2)(f) exige políticas e procedimentos para avaliar a eficácia das medidas de gestão de riscos de cibersegurança. A lei espera que detete as suas próprias lacunas.",
        ro: "Articolul 21(2)(f) impune politici și proceduri pentru evaluarea eficacității măsurilor de gestionare a riscurilor de securitate cibernetică. Legea se așteaptă să vă identificați propriile lacune.",
      },
    },
    {
      id: "3.11.3",
      question: {
        en: "What is the typical outcome of good-faith disclosure versus discovered concealment?",
        de: "Was ist das typische Ergebnis einer gutglaeubigen Offenlegung im Vergleich zu entdeckter Vertuschung?",
        nl: "Wat is het typische resultaat van openbaarmaking te goeder trouw versus ontdekte verhulling?",
        fr: "Quel est le résultat typique d'une divulgation de bonne foi par rapport à une dissimulation découverte ?",
        it: "Qual è il risultato tipico di una divulgazione in buona fede rispetto a un occultamento scoperto?",
        es: "¿Cuál es el resultado típico de la divulgación de buena fe frente al ocultamiento descubierto?",
        pl: "Jaki jest typowy rezultat ujawnienia w dobrej wierze w porównaniu z wykrytym ukrywaniem?",
        cs: "Jaký je obvyklý výsledek zveřejnění v dobré víře oproti odhalenému zatajování?",
        pt: "Qual é o resultado típico de uma divulgação de boa-fé face a uma ocultação descoberta?",
        ro: "Care este rezultatul tipic al divulgării cu bună-credință față de o disimulare descoperită?",
      },
      options: [
        { en: "Both result in the same fine", de: "Beides fuehrt zur gleichen Geldstrafe", nl: "Beide leiden tot dezelfde boete", fr: "Les deux entraînent la même amende", it: "Entrambi comportano la stessa sanzione", es: "Ambos resultan en la misma multa", pl: "Oba skutkują tą samą karą", cs: "Oba vedou ke stejné pokutě", pt: "Ambas resultam na mesma coima", ro: "Ambele duc la aceeași amendă" },
        { en: "Disclosure typically results in a remediation order or warning; concealment typically results in a fine plus ongoing monitoring", de: "Offenlegung fuehrt typischerweise zu einer Abhilfeanordnung oder Verwarnung; Vertuschung fuehrt typischerweise zu einem Bussgeld plus laufender Ueberwachung", nl: "Openbaarmaking leidt doorgaans tot een herstelorder of waarschuwing; verhulling leidt doorgaans tot een boete plus voortdurende monitoring", fr: "La divulgation entraîne généralement une injonction de remédiation ou un avertissement ; la dissimulation entraîne généralement une amende plus une surveillance continue", it: "La divulgazione comporta tipicamente un'ingiunzione di correzione o un avvertimento; l'occultamento comporta tipicamente una sanzione più un monitoraggio continuo", es: "La divulgación suele resultar en una orden de remediación o advertencia; el ocultamiento suele resultar en una multa más monitorización continua", pl: "Ujawnienie zwykle skutkuje nakazem naprawczym lub ostrzeżeniem; ukrywanie zwykle skutkuje karą oraz stałym monitorowaniem", cs: "Zveřejnění obvykle vede k příkazu k nápravě nebo varování, zatajování obvykle vede k pokutě a průběžnému monitorování", pt: "A divulgação resulta normalmente numa ordem de correção ou num aviso, a ocultação resulta normalmente numa coima acrescida de monitorização contínua", ro: "Divulgarea conduce de regulă la un ordin de remediere sau la un avertisment, disimularea conduce de regulă la o amendă plus monitorizare continuă" },
        { en: "Disclosure results in no consequences; concealment results in licence revocation", de: "Offenlegung hat keine Konsequenzen; Vertuschung fuehrt zum Lizenzentzug", nl: "Openbaarmaking heeft geen gevolgen; verhulling leidt tot intrekking van de vergunning", fr: "La divulgation n'a aucune conséquence ; la dissimulation entraîne le retrait de la licence", it: "La divulgazione non ha conseguenze; l'occultamento comporta la revoca della licenza", es: "La divulgación no tiene consecuencias; el ocultamiento resulta en la revocación de la licencia", pl: "Ujawnienie nie ma konsekwencji; ukrywanie skutkuje cofnięciem licencji", cs: "Zveřejnění nemá žádné následky, zatajování vede k odejmutí licence", pt: "A divulgação não tem consequências, a ocultação resulta na revogação da licença", ro: "Divulgarea nu are consecințe, disimularea conduce la revocarea licenței" },
        { en: "Disclosure results in a public reprimand; concealment results in criminal prosecution", de: "Offenlegung fuehrt zu einer oeffentlichen Ruege; Vertuschung fuehrt zu strafrechtlicher Verfolgung", nl: "Openbaarmaking leidt tot een publieke berisping; verhulling leidt tot strafrechtelijke vervolging", fr: "La divulgation entraîne une réprimande publique ; la dissimulation entraîne des poursuites pénales", it: "La divulgazione comporta un richiamo pubblico; l'occultamento comporta un'azione penale", es: "La divulgación resulta en una amonestación pública; el ocultamiento resulta en un proceso penal", pl: "Ujawnienie skutkuje publiczną naganą; ukrywanie skutkuje postępowaniem karnym", cs: "Zveřejnění vede k veřejnému pokárání, zatajování k trestnímu stíhání", pt: "A divulgação resulta numa repreensão pública, a ocultação resulta em processo penal", ro: "Divulgarea conduce la o mustrare publică, disimularea conduce la urmărire penală" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Good-faith disclosure typically results in a remediation order or warning, not a fine. Discovered concealment typically results in a fine plus ongoing monitoring, and the CEO's credibility is damaged for years.",
        de: "Gutglaeubige Offenlegung fuehrt typischerweise zu einer Abhilfeanordnung oder Verwarnung, nicht zu einem Bussgeld. Entdeckte Vertuschung fuehrt typischerweise zu einem Bussgeld plus laufender Ueberwachung, und die Glaubwürdigkeit des CEO ist für Jahre beschädigt.",
        nl: "Openbaarmaking te goeder trouw leidt doorgaans tot een herstelorder of waarschuwing, niet tot een boete. Ontdekte verhulling leidt doorgaans tot een boete plus voortdurende monitoring, en de geloofwaardigheid van de CEO is jarenlang aangetast.",
        fr: "La divulgation de bonne foi entraîne généralement une injonction de remédiation ou un avertissement, pas une amende. La dissimulation découverte entraîne généralement une amende plus une surveillance continue, et la crédibilité du CEO est entachée pendant des années.",
        it: "La divulgazione in buona fede comporta tipicamente un'ingiunzione di correzione o un avvertimento, non una sanzione. L'occultamento scoperto comporta tipicamente una sanzione più un monitoraggio continuo, e la credibilità del CEO è danneggiata per anni.",
        es: "La divulgación de buena fe suele resultar en una orden de remediación o advertencia, no en una multa. El ocultamiento descubierto suele resultar en una multa más monitorización continua, y la credibilidad del CEO queda dañada durante años.",
        pl: "Ujawnienie w dobrej wierze zwykle skutkuje nakazem naprawczym lub ostrzeżeniem, a nie karą. Wykryte ukrywanie zwykle skutkuje karą oraz stałym monitorowaniem, a wiarygodność CEO jest nadszarpnięta na lata.",
        cs: "Zveřejnění v dobré víře obvykle vede k příkazu k nápravě nebo varování, nikoli k pokutě. Odhalené zatajování obvykle vede k pokutě a průběžnému monitorování a důvěryhodnost generálního ředitele je na léta poškozena.",
        pt: "A divulgação de boa-fé resulta normalmente numa ordem de correção ou num aviso, e não numa coima. A ocultação descoberta resulta normalmente numa coima acrescida de monitorização contínua, e a credibilidade do diretor executivo fica afetada durante anos.",
        ro: "Divulgarea cu bună-credință conduce de regulă la un ordin de remediere sau la un avertisment, nu la o amendă. Disimularea descoperită conduce de regulă la o amendă plus monitorizare continuă, iar credibilitatea directorului general este afectată ani de zile.",
      },
    },
    {
      id: "3.11.4",
      question: {
        en: "In Option C, who should the pre-audit disclosure letter come from?",
        de: "Von wem sollte in Option C der Offenlegungsbrief vor dem Audit stammen?",
        nl: "Van wie moet in Optie C de openbaarmakingsbrief vóór de audit afkomstig zijn?",
        fr: "Dans l'option C, de qui la lettre de divulgation préalable à l'audit doit-elle émaner ?",
        it: "Nell'opzione C, da chi dovrebbe provenire la lettera di divulgazione precedente all'audit?",
        es: "En la opción C, ¿de quién debe proceder la carta de divulgación previa a la auditoría?",
        pl: "W opcji C, od kogo powinno pochodzić pismo ujawniające przed audytem?",
        cs: "Od koho by měl v možnosti C pocházet dopis o zveřejnění před auditem?",
        pt: "Na Opção C, de quem deve provir a carta de divulgação anterior à auditoria?",
        ro: "În Opțiunea C, de la cine ar trebui să provină scrisoarea de divulgare anterioară auditului?",
      },
      options: [
        { en: "The CISO", de: "Dem CISO", nl: "De CISO", fr: "Le CISO", it: "Il CISO", es: "El CISO", pl: "CISO", cs: "CISO", pt: "O CISO", ro: "CISO" },
        { en: "The compliance officer", de: "Dem Compliance-Beauftragten", nl: "De compliance-officer", fr: "Le responsable de la conformité", it: "Il responsabile della conformità", es: "El responsable de cumplimiento", pl: "Inspektor ds. zgodności", cs: "Od pověřence pro dodržování předpisů", pt: "Do responsável pela conformidade", ro: "De la responsabilul de conformitate" },
        { en: "The CEO personally", de: "Dem CEO persönlich", nl: "De CEO persoonlijk", fr: "Le CEO personnellement", it: "Il CEO personalmente", es: "El CEO personalmente", pl: "Osobiście CEO", cs: "Osobně od generálního ředitele", pt: "Do diretor executivo pessoalmente", ro: "De la directorul general personal" },
        { en: "External legal counsel", de: "Externen Rechtsberatern", nl: "Externe juridische adviseurs", fr: "Un conseil juridique externe", it: "Un consulente legale esterno", es: "Asesoría jurídica externa", pl: "Zewnętrzny radca prawny", cs: "Od externího právního zástupce", pt: "Do advogado externo", ro: "De la consilierul juridic extern" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The letter comes from you, the CEO. You personally write to the auditor before the audit - what was found, when, what was done, what the new controls look like.",
        de: "Der Brief kommt von Ihnen, dem CEO. Sie schreiben persönlich an den Auditor vor dem Audit - was gefunden wurde, wann, was unternommen wurde und wie die neuen Kontrollen aussehen.",
        nl: "De brief is van u, de CEO. U schrijft persoonlijk aan de auditor vóór de audit - wat er gevonden is, wanneer, wat er gedaan is en hoe de nieuwe maatregelen eruitzien.",
        fr: "La lettre émane de vous, le CEO. Vous écrivez personnellement à l'auditeur avant l'audit - ce qui a été trouvé, quand, ce qui a été fait et à quoi ressemblent les nouveaux contrôles.",
        it: "La lettera proviene da voi, il CEO. Scrivete personalmente all'auditor prima dell'audit - cosa è stato trovato, quando, cosa è stato fatto e come si presentano i nuovi controlli.",
        es: "La carta procede de usted, el CEO. Usted escribe personalmente al auditor antes de la auditoría: qué se encontró, cuándo, qué se hizo y cómo son los nuevos controles.",
        pl: "Pismo pochodzi od Ciebie, CEO. Osobiście piszesz do audytora przed audytem - co znaleziono, kiedy, co zrobiono i jak wyglądają nowe kontrole.",
        cs: "Dopis pochází od vás, generálního ředitele. Auditorovi před auditem píšete osobně: co bylo zjištěno, kdy, co bylo uděláno a jak nová opatření vypadají.",
        pt: "A carta provém de si, o diretor executivo. Escreve pessoalmente ao auditor antes da auditoria: o que foi encontrado, quando, o que foi feito e como são os novos controlos.",
        ro: "Scrisoarea provine de la dumneavoastră, directorul general. Îi scrieți personal auditorului înainte de audit: ce s-a constatat, când, ce s-a făcut și cum arată noile controale.",
      },
    },
  ],
});

export default quiz;
