import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.2",
  passingScore: 75,
  questions: [
    {
      id: "3.2.1",
      question: {
        en: "What four things does your signature on the top-level security policy certify?",
        de: "Welche vier Dinge bestätigt Ihre Unterschrift auf der übergeordneten Sicherheitsrichtlinie?",
        nl: "Welke vier zaken bevestigt uw handtekening op het overkoepelende beveiligingsbeleid?",
        fr: "Quelles quatre choses votre signature sur la politique de sécurité de haut niveau certifie-t-elle ?",
        it: "Quali quattro cose certifica la vostra firma sulla politica di sicurezza di alto livello?",
        es: "¿Qué cuatro cosas certifica su firma en la política de seguridad de alto nivel?",
        pl: "Jakie cztery rzeczy poświadcza Twój podpis na nadrzędnej polityce bezpieczeństwa?",
        cs: "Které čtyři věci osvědčuje váš podpis na nadřazené bezpečnostní politice?",
        pt: "Que quatro coisas certifica a sua assinatura na política de segurança de nível superior?",
        ro: "Ce patru lucruri certifică semnătura dumneavoastră pe politica de securitate de nivel superior?",
      },
      options: [
        { en: "Risk analysis reviewed, measures address risks, budget approved, named people are responsible", de: "Risikoanalyse geprüft, Maßnahmen adressieren Risiken, Budget genehmigt, benannte Personen sind verantwortlich", nl: "Risicoanalyse beoordeeld, maatregelen pakken risico's aan, budget goedgekeurd, benoemde personen zijn verantwoordelijk", fr: "Analyse des risques examinée, les mesures traitent les risques, budget approuvé, des personnes nommées sont responsables", it: "Analisi dei rischi esaminata, le misure affrontano i rischi, budget approvato, persone nominate sono responsabili", es: "Análisis de riesgos revisado, las medidas abordan los riesgos, presupuesto aprobado, personas nombradas son responsables", pl: "Analiza ryzyka sprawdzona, środki odnoszą się do ryzyk, budżet zatwierdzony, wyznaczone osoby są odpowiedzialne", cs: "Analýza rizik byla přezkoumána, opatření řeší rizika, rozpočet je schválen, za realizaci odpovídají jmenované osoby", pt: "A análise de riscos foi revista, as medidas respondem aos riscos, o orçamento foi aprovado, pessoas designadas são responsáveis", ro: "Analiza riscurilor a fost revizuită, măsurile răspund riscurilor, bugetul a fost aprobat, persoane desemnate sunt responsabile" },
        { en: "Policy is complete, IT department approved it, budget exists, auditor signed off", de: "Richtlinie ist vollständig, IT-Abteilung hat zugestimmt, Budget vorhanden, Auditor hat abgezeichnet", nl: "Beleid is volledig, IT-afdeling heeft goedgekeurd, budget is aanwezig, auditor heeft goedkeuring gegeven", fr: "La politique est complète, le service informatique l'a approuvée, le budget existe, l'auditeur a validé", it: "La politica è completa, il reparto IT l'ha approvata, il budget esiste, l'auditor ha controfirmato", es: "La política está completa, el departamento de TI la aprobó, el presupuesto existe, el auditor dio el visto bueno", pl: "Polityka jest kompletna, dział IT ją zatwierdził, budżet istnieje, audytor zaakceptował", cs: "Politika je úplná, oddělení IT ji schválilo, rozpočet existuje, auditor ji podepsal", pt: "A política está completa, o departamento de TI aprovou-a, o orçamento existe, o auditor validou-a", ro: "Politica este completă, departamentul IT a aprobat-o, bugetul există, auditorul a validat-o" },
        { en: "Risks are eliminated, CISO is accountable, budget is unlimited, controls are tested", de: "Risiken sind beseitigt, CISO ist verantwortlich, Budget ist unbegrenzt, Kontrollen sind getestet", nl: "Risico's zijn geëlimineerd, CISO is verantwoordelijk, budget is onbeperkt, controles zijn getest", fr: "Les risques sont éliminés, le CISO est responsable, le budget est illimité, les contrôles sont testés", it: "I rischi sono eliminati, il CISO è responsabile, il budget è illimitato, i controlli sono testati", es: "Los riesgos están eliminados, el CISO es responsable, el presupuesto es ilimitado, los controles están probados", pl: "Ryzyka są wyeliminowane, CISO jest odpowiedzialny, budżet jest nieograniczony, kontrole są przetestowane", cs: "Rizika jsou odstraněna, odpovídá CISO, rozpočet je neomezený, opatření jsou otestována", pt: "Os riscos estão eliminados, o CISO é responsável, o orçamento é ilimitado, os controlos estão testados", ro: "Riscurile sunt eliminate, CISO este responsabil, bugetul este nelimitat, controalele sunt testate" },
        { en: "Compliance is achieved, training is complete, incidents are reported, suppliers are managed", de: "Compliance ist erreicht, Schulungen sind abgeschlossen, Vorfälle werden gemeldet, Lieferanten werden gesteuert", nl: "Naleving is bereikt, opleiding is afgerond, incidenten worden gemeld, leveranciers worden beheerd", fr: "La conformité est atteinte, la formation est terminée, les incidents sont signalés, les fournisseurs sont gérés", it: "La conformità è raggiunta, la formazione è completata, gli incidenti sono segnalati, i fornitori sono gestiti", es: "El cumplimiento se ha alcanzado, la formación está completa, los incidentes se notifican, los proveedores se gestionan", pl: "Zgodność jest osiągnięta, szkolenie jest zakończone, incydenty są zgłaszane, dostawcy są zarządzani", cs: "Soulad je dosažen, školení je dokončeno, incidenty jsou ohlášeny, dodavatelé jsou řízeni", pt: "A conformidade está alcançada, a formação está completa, os incidentes estão notificados, os fornecedores estão geridos", ro: "Conformitatea este atinsă, formarea este finalizată, incidentele sunt raportate, furnizorii sunt gestionați" },
      ],
      correctIndex: 0,
      explanation: {
        en: "Your signature certifies that you reviewed the risk analysis, that the measures address those risks, that the budget to implement them is approved, and that named people are responsible for carrying them out.",
        de: "Ihre Unterschrift bestätigt, dass Sie die Risikoanalyse geprüft haben, dass die Maßnahmen diese Risiken adressieren, dass das Budget zu deren Umsetzung genehmigt ist und dass benannte Personen für die Durchführung verantwortlich sind.",
        nl: "Uw handtekening bevestigt dat u de risicoanalyse heeft beoordeeld, dat de maatregelen die risico's aanpakken, dat het budget voor de uitvoering ervan is goedgekeurd, en dat benoemde personen verantwoordelijk zijn voor de uitvoering.",
        fr: "Votre signature certifie que vous avez examiné l'analyse des risques, que les mesures traitent ces risques, que le budget pour les mettre en œuvre est approuvé, et que des personnes nommées sont responsables de leur exécution.",
        it: "La vostra firma certifica che avete esaminato l'analisi dei rischi, che le misure affrontano tali rischi, che il budget per attuarle è approvato e che persone nominate sono responsabili della loro esecuzione.",
        es: "Su firma certifica que ha revisado el análisis de riesgos, que las medidas abordan esos riesgos, que el presupuesto para implementarlas está aprobado y que personas nombradas son responsables de llevarlas a cabo.",
        pl: "Twój podpis poświadcza, że sprawdziłeś analizę ryzyka, że środki odnoszą się do tych ryzyk, że budżet na ich wdrożenie jest zatwierdzony oraz że wyznaczone osoby są odpowiedzialne za ich realizację.",
        cs: "Váš podpis osvědčuje, že jste přezkoumali analýzu rizik, že opatření tato rizika řeší, že je schválen rozpočet na jejich zavedení a že za jejich realizaci odpovídají jmenované osoby.",
        pt: "A sua assinatura certifica que reviu a análise de riscos, que as medidas respondem a esses riscos, que o orçamento para as implementar está aprovado e que pessoas designadas são responsáveis pela sua execução.",
        ro: "Semnătura dumneavoastră certifică faptul că ați revizuit analiza riscurilor, că măsurile răspund acelor riscuri, că bugetul pentru implementarea lor este aprobat și că persoane desemnate sunt responsabile de executarea acestora.",
      },
    },
    {
      id: "3.2.2",
      question: {
        en: "What happens if you sign a security policy without reviewing it and the company later has an incident?",
        de: "Was passiert, wenn Sie eine Sicherheitsrichtlinie ohne Prüfung unterschreiben und das Unternehmen später einen Vorfall hat?",
        nl: "Wat gebeurt er als u een beveiligingsbeleid ondertekent zonder het te beoordelen en het bedrijf later een incident heeft?",
        fr: "Que se passe-t-il si vous signez une politique de sécurité sans l'examiner et que l'entreprise subit ensuite un incident ?",
        it: "Cosa succede se firmate una politica di sicurezza senza esaminarla e l'azienda subisce in seguito un incidente?",
        es: "¿Qué ocurre si firma una política de seguridad sin revisarla y la empresa sufre después un incidente?",
        pl: "Co się stanie, jeśli podpiszesz politykę bezpieczeństwa bez jej sprawdzenia, a firma później dozna incydentu?",
        cs: "Co se stane, pokud podepíšete bezpečnostní politiku, aniž byste ji přezkoumali, a společnost později zažije incident?",
        pt: "O que acontece se assinar uma política de segurança sem a rever e a empresa tiver mais tarde um incidente?",
        ro: "Ce se întâmplă dacă semnați o politică de securitate fără a o revizui, iar compania are ulterior un incident?",
      },
      options: [
        { en: "The signature still provides legal protection because it was given in good faith", de: "Die Unterschrift bietet weiterhin rechtlichen Schutz, da sie in gutem Glauben geleistet wurde", nl: "De handtekening biedt nog steeds juridische bescherming omdat ze te goeder trouw is gegeven", fr: "La signature offre toujours une protection juridique car elle a été donnée de bonne foi", it: "La firma offre comunque protezione giuridica perché è stata data in buona fede", es: "La firma sigue ofreciendo protección jurídica porque se otorgó de buena fe", pl: "Podpis nadal zapewnia ochronę prawną, ponieważ został złożony w dobrej wierze", cs: "Podpis stále poskytuje právní ochranu, protože byl dán v dobré víře", pt: "A assinatura ainda confere proteção jurídica porque foi dada de boa-fé", ro: "Semnătura oferă în continuare protecție juridică deoarece a fost dată cu bună-credință" },
        { en: "The CISO bears responsibility because they prepared the document", de: "Der CISO trägt die Verantwortung, da er das Dokument erstellt hat", nl: "De CISO draagt de verantwoordelijkheid omdat hij het document heeft opgesteld", fr: "Le CISO porte la responsabilité car il a préparé le document", it: "Il CISO è responsabile perché ha preparato il documento", es: "El CISO asume la responsabilidad porque preparó el documento", pl: "Odpowiedzialność ponosi CISO, ponieważ przygotował dokument", cs: "Odpovědnost nese CISO, protože dokument připravil", pt: "O CISO assume a responsabilidade porque preparou o documento", ro: "CISO poartă responsabilitatea deoarece a pregătit documentul" },
        { en: "Your signature becomes evidence that you approved something you did not read - and works against you in court", de: "Ihre Unterschrift wird zum Beweis, dass Sie etwas genehmigt haben, das Sie nicht gelesen haben - und wirkt vor Gericht gegen Sie", nl: "Uw handtekening wordt bewijs dat u iets heeft goedgekeurd dat u niet heeft gelezen - en werkt tegen u in de rechtbank", fr: "Votre signature devient la preuve que vous avez approuvé quelque chose que vous n'avez pas lu - et joue contre vous au tribunal", it: "La vostra firma diventa la prova che avete approvato qualcosa che non avete letto - e gioca contro di voi in tribunale", es: "Su firma se convierte en prueba de que aprobó algo que no leyó, y actúa en su contra ante los tribunales", pl: "Twój podpis staje się dowodem, że zatwierdziłeś coś, czego nie przeczytałeś - i działa przeciwko Tobie w sądzie", cs: "Váš podpis se stává důkazem, že jste schválili něco, co jste nečetli, a u soudu hraje proti vám", pt: "A sua assinatura torna-se prova de que aprovou algo que não leu e joga contra si em tribunal", ro: "Semnătura dumneavoastră devine dovada că ați aprobat ceva ce nu ați citit și joacă împotriva dumneavoastră în instanță" },
        { en: "The regulator will accept the signature as valid if it was standard practice", de: "Die Aufsichtsbehörde akzeptiert die Unterschrift als gültig, wenn es gängige Praxis war", nl: "De toezichthouder accepteert de handtekening als geldig als het gangbare praktijk was", fr: "L'autorité de régulation acceptera la signature comme valide s'il s'agissait d'une pratique courante", it: "L'autorità di regolamentazione accetterà la firma come valida se era prassi comune", es: "El regulador aceptará la firma como válida si era práctica habitual", pl: "Organ nadzoru uzna podpis za ważny, jeśli była to standardowa praktyka", cs: "Regulační orgán uzná podpis za platný, pokud šlo o běžnou praxi", pt: "A autoridade reguladora aceitará a assinatura como válida se for prática corrente", ro: "Autoritatea de reglementare va accepta semnătura ca validă dacă a fost o practică obișnuită" },
      ],
      correctIndex: 2,
      explanation: {
        en: "An uninformed signature is legally void. If you signed without reviewing, your signature becomes evidence that you approved something you did not read - and that evidence works against you in court.",
        de: "Eine uninformierte Unterschrift ist rechtlich nichtig. Wenn Sie ohne Prüfung unterschrieben haben, wird Ihre Unterschrift zum Beweis, dass Sie etwas genehmigt haben, das Sie nicht gelesen haben - und dieser Beweis wirkt vor Gericht gegen Sie.",
        nl: "Een ondoordachte handtekening is juridisch nietig. Als u heeft ondertekend zonder te beoordelen, wordt uw handtekening bewijs dat u iets heeft goedgekeurd dat u niet heeft gelezen - en dat bewijs werkt tegen u in de rechtbank.",
        fr: "Une signature non éclairée est juridiquement nulle. Si vous avez signé sans examiner, votre signature devient la preuve que vous avez approuvé quelque chose que vous n'avez pas lu - et cette preuve joue contre vous au tribunal.",
        it: "Una firma non informata è giuridicamente nulla. Se avete firmato senza esaminare, la vostra firma diventa la prova che avete approvato qualcosa che non avete letto - e tale prova gioca contro di voi in tribunale.",
        es: "Una firma no informada es jurídicamente nula. Si firmó sin revisar, su firma se convierte en prueba de que aprobó algo que no leyó, y esa prueba actúa en su contra ante los tribunales.",
        pl: "Niepoinformowany podpis jest prawnie nieważny. Jeśli podpisałeś bez sprawdzenia, Twój podpis staje się dowodem, że zatwierdziłeś coś, czego nie przeczytałeś - a dowód ten działa przeciwko Tobie w sądzie.",
        cs: "Neinformovaný podpis je právně neplatný. Pokud jste podepsali bez přezkoumání, váš podpis se stává důkazem, že jste schválili něco, co jste nečetli, a tento důkaz u soudu hraje proti vám.",
        pt: "Uma assinatura não informada é juridicamente nula. Se assinou sem rever, a sua assinatura torna-se prova de que aprovou algo que não leu, e essa prova joga contra si em tribunal.",
        ro: "O semnătură neinformată este nulă din punct de vedere juridic. Dacă ați semnat fără a revizui, semnătura dumneavoastră devine dovada că ați aprobat ceva ce nu ați citit, iar acea dovadă joacă împotriva dumneavoastră în instanță.",
      },
    },
    {
      id: "3.2.3",
      question: {
        en: "According to the lesson, what is the relationship between the management body and the CISO when it comes to the security policy?",
        de: "Welche Beziehung besteht laut der Lektion zwischen dem Leitungsorgan und dem CISO in Bezug auf die Sicherheitsrichtlinie?",
        nl: "Wat is volgens de les de verhouding tussen het leidinggevend orgaan en de CISO als het gaat om het beveiligingsbeleid?",
        fr: "Selon la leçon, quelle est la relation entre l'organe de direction et le CISO concernant la politique de sécurité ?",
        it: "Secondo la lezione, qual è il rapporto tra l'organo di gestione e il CISO per quanto riguarda la politica di sicurezza?",
        es: "Según la lección, ¿cuál es la relación entre el órgano de dirección y el CISO en lo que respecta a la política de seguridad?",
        pl: "Według lekcji, jaka jest relacja między organem zarządzającym a CISO w odniesieniu do polityki bezpieczeństwa?",
        cs: "Jaký je podle lekce vztah mezi řídicím orgánem a CISO, pokud jde o bezpečnostní politiku?",
        pt: "Segundo a lição, qual é a relação entre o órgão de administração e o CISO no que toca à política de segurança?",
        ro: "Potrivit lecției, care este relația dintre organul de conducere și CISO în ceea ce privește politica de securitate?",
      },
      options: [
        { en: "The CISO decides what to do and the management body funds it", de: "Der CISO entscheidet, was zu tun ist, und das Leitungsorgan finanziert es", nl: "De CISO beslist wat er gedaan moet worden en het leidinggevend orgaan financiert het", fr: "Le CISO décide ce qu'il faut faire et l'organe de direction le finance", it: "Il CISO decide cosa fare e l'organo di gestione lo finanzia", es: "El CISO decide qué hacer y el órgano de dirección lo financia", pl: "CISO decyduje, co należy zrobić, a organ zarządzający to finansuje", cs: "CISO rozhoduje, co se má udělat, a řídicí orgán to financuje", pt: "O CISO decide o que fazer e o órgão de administração financia-o", ro: "CISO decide ce trebuie făcut, iar organul de conducere finanțează" },
        { en: "The management body decides what and why; the CISO decides how", de: "Das Leitungsorgan entscheidet über das Was und Warum; der CISO entscheidet über das Wie", nl: "Het leidinggevend orgaan beslist wat en waarom; de CISO beslist hoe", fr: "L'organe de direction décide quoi et pourquoi ; le CISO décide comment", it: "L'organo di gestione decide cosa e perché; il CISO decide come", es: "El órgano de dirección decide qué y por qué; el CISO decide cómo", pl: "Organ zarządzający decyduje, co i dlaczego; CISO decyduje, jak", cs: "Řídicí orgán rozhoduje, co a proč, CISO rozhoduje jak", pt: "O órgão de administração decide o quê e porquê, o CISO decide como", ro: "Organul de conducere decide ce și de ce, CISO decide cum" },
        { en: "The CISO and management body share equal responsibility", de: "CISO und Leitungsorgan teilen sich die Verantwortung gleichermaßen", nl: "De CISO en het leidinggevend orgaan delen de verantwoordelijkheid gelijkelijk", fr: "Le CISO et l'organe de direction partagent une responsabilité égale", it: "Il CISO e l'organo di gestione condividono in egual misura la responsabilità", es: "El CISO y el órgano de dirección comparten la responsabilidad por igual", pl: "CISO i organ zarządzający dzielą odpowiedzialność po równo", cs: "CISO a řídicí orgán nesou stejnou odpovědnost", pt: "O CISO e o órgão de administração partilham a mesma responsabilidade", ro: "CISO și organul de conducere împart aceeași responsabilitate" },
        { en: "The management body delegates all security decisions to the CISO", de: "Das Leitungsorgan delegiert alle Sicherheitsentscheidungen an den CISO", nl: "Het leidinggevend orgaan delegeert alle beveiligingsbeslissingen aan de CISO", fr: "L'organe de direction délègue toutes les décisions de sécurité au CISO", it: "L'organo di gestione delega tutte le decisioni di sicurezza al CISO", es: "El órgano de dirección delega todas las decisiones de seguridad en el CISO", pl: "Organ zarządzający deleguje wszystkie decyzje dotyczące bezpieczeństwa na CISO", cs: "Řídicí orgán deleguje všechna bezpečnostní rozhodnutí na CISO", pt: "O órgão de administração delega todas as decisões de segurança no CISO", ro: "Organul de conducere deleagă toate deciziile de securitate către CISO" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The management body decides what and why. The CISO decides how.",
        de: "Das Leitungsorgan entscheidet über das Was und Warum. Der CISO entscheidet über das Wie.",
        nl: "Het leidinggevend orgaan beslist wat en waarom. De CISO beslist hoe.",
        fr: "L'organe de direction décide quoi et pourquoi. Le CISO décide comment.",
        it: "L'organo di gestione decide cosa e perché. Il CISO decide come.",
        es: "El órgano de dirección decide qué y por qué. El CISO decide cómo.",
        pl: "Organ zarządzający decyduje, co i dlaczego. CISO decyduje, jak.",
        cs: "Řídicí orgán rozhoduje, co a proč. CISO rozhoduje jak.",
        pt: "O órgão de administração decide o quê e porquê. O CISO decide como.",
        ro: "Organul de conducere decide ce și de ce. CISO decide cum.",
      },
    },
    {
      id: "3.2.4",
      question: {
        en: "Which of the four pre-signature questions addresses the risk that a policy promises controls the company has not funded?",
        de: "Welche der vier Fragen vor der Unterschrift adressiert das Risiko, dass eine Richtlinie Kontrollen verspricht, die das Unternehmen nicht finanziert hat?",
        nl: "Welke van de vier vragen vóór ondertekening pakt het risico aan dat een beleid controles belooft die het bedrijf niet heeft gefinancierd?",
        fr: "Laquelle des quatre questions préalables à la signature traite du risque qu'une politique promette des contrôles que l'entreprise n'a pas financés ?",
        it: "Quale delle quattro domande precedenti alla firma affronta il rischio che una politica prometta controlli che l'azienda non ha finanziato?",
        es: "¿Cuál de las cuatro preguntas previas a la firma aborda el riesgo de que una política prometa controles que la empresa no ha financiado?",
        pl: "Które z czterech pytań przed podpisaniem odnosi się do ryzyka, że polityka obiecuje kontrole, których firma nie sfinansowała?",
        cs: "Která ze čtyř otázek před podpisem řeší riziko, že politika slibuje opatření, která společnost nefinancovala?",
        pt: "Qual das quatro perguntas anteriores à assinatura aborda o risco de uma política prometer controlos que a empresa não financiou?",
        ro: "Care dintre cele patru întrebări anterioare semnării abordează riscul ca o politică să promită controale pe care compania nu le-a finanțat?",
      },
      options: [
        { en: "\"Show me the risk analysis this policy refers to\"", de: "\"Zeigen Sie mir die Risikoanalyse, auf die sich diese Richtlinie bezieht\"", nl: "\"Laat me de risicoanalyse zien waarnaar dit beleid verwijst\"", fr: "\"Montrez-moi l'analyse des risques à laquelle cette politique fait référence\"", it: "\"Mostratemi l'analisi dei rischi a cui questa politica fa riferimento\"", es: "\"Muéstreme el análisis de riesgos al que se refiere esta política\"", pl: "\"Pokaż mi analizę ryzyka, do której odnosi się ta polityka\"", cs: "„Ukažte mi analýzu rizik, na kterou tato politika odkazuje“", pt: "«Mostre-me a análise de riscos a que esta política se refere»", ro: "„Arătați-mi analiza riscurilor la care se referă această politică”" },
        { en: "\"What has changed since the last version I signed?\"", de: "\"Was hat sich seit der letzten von mir unterschriebenen Version geändert?\"", nl: "\"Wat is er veranderd sinds de laatste versie die ik heb ondertekend?\"", fr: "\"Qu'est-ce qui a changé depuis la dernière version que j'ai signée ?\"", it: "\"Cosa è cambiato dall'ultima versione che ho firmato?\"", es: "\"¿Qué ha cambiado desde la última versión que firmé?\"", pl: "\"Co się zmieniło od ostatniej wersji, którą podpisałem?\"", cs: "„Co se změnilo od poslední verze, kterou jsem podepsal?“", pt: "«O que mudou desde a última versão que assinei?»", ro: "„Ce s-a schimbat de la ultima versiune pe care am semnat-o?”" },
        { en: "\"Has the budget to implement these measures been approved?\"", de: "\"Wurde das Budget zur Umsetzung dieser Maßnahmen genehmigt?\"", nl: "\"Is het budget voor de uitvoering van deze maatregelen goedgekeurd?\"", fr: "\"Le budget pour mettre en œuvre ces mesures a-t-il été approuvé ?\"", it: "\"Il budget per attuare queste misure è stato approvato?\"", es: "\"¿Se ha aprobado el presupuesto para implementar estas medidas?\"", pl: "\"Czy budżet na wdrożenie tych środków został zatwierdzony?\"", cs: "„Byl schválen rozpočet na zavedení těchto opatření?“", pt: "«O orçamento para implementar estas medidas foi aprovado?»", ro: "„A fost aprobat bugetul pentru implementarea acestor măsuri?”" },
        { en: "\"Who are the named people responsible for each measure?\"", de: "\"Wer sind die benannten Verantwortlichen für jede Maßnahme?\"", nl: "\"Wie zijn de benoemde verantwoordelijken voor elke maatregel?\"", fr: "\"Qui sont les personnes nommées responsables de chaque mesure ?\"", it: "\"Chi sono le persone nominate responsabili di ciascuna misura?\"", es: "\"¿Quiénes son las personas nombradas responsables de cada medida?\"", pl: "\"Kto są wyznaczone osoby odpowiedzialne za każdy środek?\"", cs: "„Které jmenované osoby odpovídají za každé opatření?“", pt: "«Quem são as pessoas designadas responsáveis por cada medida?»", ro: "„Care sunt persoanele desemnate responsabile pentru fiecare măsură?”" },
      ],
      correctIndex: 2,
      explanation: {
        en: "A policy that promises controls the company has not funded is a policy the regulator will use against you - the budget question catches this.",
        de: "Eine Richtlinie, die Kontrollen verspricht, die das Unternehmen nicht finanziert hat, ist eine Richtlinie, die die Aufsichtsbehörde gegen Sie verwenden wird - die Budgetfrage deckt dies auf.",
        nl: "Een beleid dat controles belooft die het bedrijf niet heeft gefinancierd, is een beleid dat de toezichthouder tegen u zal gebruiken - de budgetvraag onderschept dit.",
        fr: "Une politique qui promet des contrôles que l'entreprise n'a pas financés est une politique que l'autorité de régulation utilisera contre vous - la question du budget permet de le détecter.",
        it: "Una politica che promette controlli che l'azienda non ha finanziato è una politica che l'autorità di regolamentazione utilizzerà contro di voi - la domanda sul budget lo intercetta.",
        es: "Una política que promete controles que la empresa no ha financiado es una política que el regulador usará en su contra; la pregunta del presupuesto detecta esto.",
        pl: "Polityka obiecująca kontrole, których firma nie sfinansowała, to polityka, którą organ nadzoru wykorzysta przeciwko Tobie - pytanie o budżet to wychwytuje.",
        cs: "Politika, která slibuje opatření, jež společnost nefinancovala, je politika, kterou regulační orgán použije proti vám. Otázka na rozpočet to odhalí.",
        pt: "Uma política que promete controlos que a empresa não financiou é uma política que a autoridade reguladora usará contra si. A pergunta sobre o orçamento deteta isto.",
        ro: "O politică ce promite controale pe care compania nu le-a finanțat este o politică pe care autoritatea de reglementare o va folosi împotriva dumneavoastră. Întrebarea despre buget surprinde acest lucru.",
      },
    },
  ],
});

export default quiz;
