import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.3",
  passingScore: 75,
  questions: [
    {
      id: "3.3.1",
      question: {
        en: "What is the minimum frequency for a formal management review of the security management system?",
        de: "Was ist die Mindesthäufigkeit für eine formelle Management-Bewertung des Sicherheitsmanagementsystems?",
        nl: "Wat is de minimumfrequentie voor een formele managementbeoordeling van het beveiligingsbeheersysteem?",
        fr: "Quelle est la fréquence minimale d'une revue de direction formelle du système de management de la sécurité ?",
        it: "Qual è la frequenza minima di un riesame formale della direzione del sistema di gestione della sicurezza?",
        es: "¿Cuál es la frecuencia mínima de una revisión formal por la dirección del sistema de gestión de la seguridad?",
        pl: "Jaka jest minimalna częstotliwość formalnego przeglądu zarządzania systemem zarządzania bezpieczeństwem?",
      },
      options: [
        { en: "Quarterly", de: "Vierteljährlich", nl: "Elk kwartaal", fr: "Trimestrielle", it: "Trimestrale", es: "Trimestral", pl: "Kwartalnie" },
        { en: "Annually", de: "Jährlich", nl: "Jaarlijks", fr: "Annuelle", it: "Annuale", es: "Anual", pl: "Rocznie" },
        { en: "Every two years", de: "Alle zwei Jahre", nl: "Elke twee jaar", fr: "Tous les deux ans", it: "Ogni due anni", es: "Cada dos años", pl: "Co dwa lata" },
        { en: "Only after incidents", de: "Nur nach Vorfaellen", nl: "Alleen na incidenten", fr: "Uniquement après des incidents", it: "Solo dopo gli incidenti", es: "Solo después de incidentes", pl: "Tylko po incydentach" },
      ],
      correctIndex: 1,
      explanation: {
        en: "BSI-Standard 200-1, section 7.4 requires a formal annual management review. Annual is the floor, not the ceiling.",
        de: "BSI-Standard 200-1, Abschnitt 7.4 verlangt eine formelle jährliche Management-Bewertung. Jährlich ist das Minimum, nicht das Maximum.",
        nl: "BSI-Standard 200-1, sectie 7.4 vereist een formele jaarlijkse managementbeoordeling. Jaarlijks is het minimum, niet het maximum.",
        fr: "Le BSI-Standard 200-1, section 7.4 exige une revue de direction formelle annuelle. L'annuel est le plancher, pas le plafond.",
        it: "Il BSI-Standard 200-1, sezione 7.4 richiede un riesame formale annuale della direzione. L'annuale è il minimo, non il massimo.",
        es: "El BSI-Standard 200-1, sección 7.4 exige una revisión formal anual por la dirección. Lo anual es el mínimo, no el máximo.",
        pl: "BSI-Standard 200-1, sekcja 7.4 wymaga formalnego rocznego przeglądu zarządzania. Roczny to minimum, a nie maksimum.",
      },
    },
    {
      id: "3.3.2",
      question: {
        en: "How many categories of events require re-sign-off before the annual cycle?",
        de: "Wie viele Kategorien von Ereignissen erfordern eine erneute Freigabe vor dem jährlichen Zyklus?",
        nl: "Hoeveel categorieën gebeurtenissen vereisen een nieuwe goedkeuring vóór de jaarlijkse cyclus?",
        fr: "Combien de catégories d'événements exigent une nouvelle validation avant le cycle annuel ?",
        it: "Quante categorie di eventi richiedono una nuova approvazione prima del ciclo annuale?",
        es: "¿Cuántas categorías de eventos requieren una nueva aprobación antes del ciclo anual?",
        pl: "Ile kategorii zdarzeń wymaga ponownego zatwierdzenia przed rocznym cyklem?",
      },
      options: [
        { en: "Three", de: "Drei", nl: "Drie", fr: "Trois", it: "Tre", es: "Tres", pl: "Trzy" },
        { en: "Four", de: "Vier", nl: "Vier", fr: "Quatre", it: "Quattro", es: "Cuatro", pl: "Cztery" },
        { en: "Six", de: "Sechs", nl: "Zes", fr: "Six", it: "Sei", es: "Seis", pl: "Sześć" },
        { en: "Eight", de: "Acht", nl: "Acht", fr: "Huit", it: "Otto", es: "Ocho", pl: "Osiem" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Six categories: change in leadership, significant business change, major incident, regulatory change, audit finding requiring remediation, and material supplier change.",
        de: "Sechs Kategorien: Wechsel in der Fuehrung, wesentliche Geschaeftsveränderung, schwerwiegender Vorfall, regulatorische Änderung, Auditfeststellung mit Abhilfebedarf und wesentliche Lieferantenänderung.",
        nl: "Zes categorieën: wijziging in leiderschap, significante bedrijfswijziging, groot incident, regelgevingswijziging, auditbevinding die herstel vereist, en wezenlijke leverancierswijziging.",
        fr: "Six catégories : changement de direction, changement significatif d'activité, incident majeur, changement réglementaire, constatation d'audit nécessitant une remédiation, et changement important de fournisseur.",
        it: "Sei categorie: cambio di leadership, cambiamento significativo dell'attività, incidente grave, cambiamento normativo, rilievo di audit che richiede correzione e cambiamento sostanziale di fornitore.",
        es: "Seis categorías: cambio de liderazgo, cambio significativo del negocio, incidente grave, cambio normativo, hallazgo de auditoría que requiere remediación y cambio sustancial de proveedor.",
        pl: "Sześć kategorii: zmiana kierownictwa, istotna zmiana działalności, poważny incydent, zmiana regulacyjna, ustalenie audytowe wymagające naprawy oraz istotna zmiana dostawcy.",
      },
    },
    {
      id: "3.3.3",
      question: {
        en: "What three things must every re-sign-off document?",
        de: "Welche drei Dinge muss jede erneute Freigabe dokumentieren?",
        nl: "Welke drie zaken moet elke nieuwe goedkeuring documenteren?",
        fr: "Quelles trois choses chaque nouvelle validation doit-elle documenter ?",
        it: "Quali tre cose deve documentare ogni nuova approvazione?",
        es: "¿Qué tres cosas debe documentar cada nueva aprobación?",
        pl: "Jakie trzy rzeczy musi dokumentować każde ponowne zatwierdzenie?",
      },
      options: [
        { en: "The incident, the response, and the cost", de: "Den Vorfall, die Reaktion und die Kosten", nl: "Het incident, de respons en de kosten", fr: "L'incident, la réponse et le coût", it: "L'incidente, la risposta e il costo", es: "El incidente, la respuesta y el coste", pl: "Incydent, reakcję i koszt" },
        { en: "The trigger event, the changes to the measures, and the new signature", de: "Das ausloesende Ereignis, die Änderungen an den Maßnahmen und die neue Unterschrift", nl: "De aanleiding, de wijzigingen in de maatregelen en de nieuwe handtekening", fr: "L'événement déclencheur, les modifications des mesures et la nouvelle signature", it: "L'evento scatenante, le modifiche alle misure e la nuova firma", es: "El evento desencadenante, los cambios en las medidas y la nueva firma", pl: "Zdarzenie wyzwalające, zmiany środków i nowy podpis" },
        { en: "The CISO's recommendation, the board vote, and the budget", de: "Die Empfehlung des CISO, die Vorstandsabstimmung und das Budget", nl: "De aanbeveling van de CISO, de bestuursstemming en het budget", fr: "La recommandation du CISO, le vote du conseil et le budget", it: "La raccomandazione del CISO, il voto del consiglio e il budget", es: "La recomendación del CISO, la votación del consejo y el presupuesto", pl: "Zalecenie CISO, głosowanie zarządu i budżet" },
        { en: "The risk analysis, the supplier list, and the training records", de: "Die Risikoanalyse, die Lieferantenliste und die Schulungsnachweise", nl: "De risicoanalyse, de leverancierslijst en de opleidingsregisters", fr: "L'analyse des risques, la liste des fournisseurs et les registres de formation", it: "L'analisi dei rischi, l'elenco dei fornitori e i registri di formazione", es: "El análisis de riesgos, la lista de proveedores y los registros de formación", pl: "Analizę ryzyka, listę dostawców i rejestry szkoleń" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Every re-sign-off needs three things documented: the trigger, the changes since last approval, and the new signature.",
        de: "Jede erneute Freigabe erfordert die Dokumentation von drei Dingen: dem Ausloeser, den Änderungen seit der letzten Genehmigung und der neuen Unterschrift.",
        nl: "Elke nieuwe goedkeuring vereist dat drie zaken worden gedocumenteerd: de aanleiding, de wijzigingen sinds de laatste goedkeuring en de nieuwe handtekening.",
        fr: "Chaque nouvelle validation exige la documentation de trois choses : le déclencheur, les modifications depuis la dernière approbation et la nouvelle signature.",
        it: "Ogni nuova approvazione richiede la documentazione di tre cose: l'evento scatenante, le modifiche dall'ultima approvazione e la nuova firma.",
        es: "Cada nueva aprobación exige documentar tres cosas: el desencadenante, los cambios desde la última aprobación y la nueva firma.",
        pl: "Każde ponowne zatwierdzenie wymaga udokumentowania trzech rzeczy: czynnika wyzwalającego, zmian od ostatniego zatwierdzenia oraz nowego podpisu.",
      },
    },
    {
      id: "3.3.4",
      question: {
        en: "In the acquisition scenario, why does the sign-off wait if the CISO cannot describe the target's systems?",
        de: "Warum wird die Freigabe im Akquisitionsszenario zurueckgehalten, wenn der CISO die Systeme des Zielunternehmens nicht beschreiben kann?",
        nl: "Waarom wacht de goedkeuring in het overnamesscenario als de CISO de systemen van het doelbedrijf niet kan beschrijven?",
        fr: "Dans le scénario d'acquisition, pourquoi la validation attend-elle si le CISO ne peut pas décrire les systèmes de la cible ?",
        it: "Nello scenario di acquisizione, perché l'approvazione attende se il CISO non riesce a descrivere i sistemi dell'azienda target?",
        es: "En el escenario de adquisición, ¿por qué espera la aprobación si el CISO no puede describir los sistemas de la empresa objetivo?",
        pl: "W scenariuszu przejęcia, dlaczego zatwierdzenie czeka, jeśli CISO nie potrafi opisać systemów przejmowanej firmy?",
      },
      options: [
        { en: "Because the regulator requires a waiting period after acquisitions", de: "Weil die Aufsichtsbehörde nach Akquisitionen eine Wartefrist vorschreibt", nl: "Omdat de toezichthouder een wachttijd vereist na overnames", fr: "Parce que l'autorité de régulation impose un délai d'attente après les acquisitions", it: "Perché l'autorità di regolamentazione impone un periodo di attesa dopo le acquisizioni", es: "Porque el regulador exige un período de espera tras las adquisiciones", pl: "Ponieważ organ nadzoru wymaga okresu oczekiwania po przejęciach" },
        { en: "Because the sign-off must be informed - without facts about the target's systems, suppliers, and risk analysis, the approval has nothing to stand on", de: "Weil die Freigabe informiert erfolgen muss - ohne Fakten ueber die Systeme, Lieferanten und Risikoanalyse des Zielunternehmens hat die Genehmigung keine Grundlage", nl: "Omdat de goedkeuring geïnformeerd moet zijn - zonder feiten over de systemen, leveranciers en risicoanalyse van het doelbedrijf heeft de goedkeuring geen basis", fr: "Parce que la validation doit être éclairée - sans faits sur les systèmes, les fournisseurs et l'analyse des risques de la cible, l'approbation n'a aucun fondement", it: "Perché l'approvazione deve essere informata - senza dati sui sistemi, sui fornitori e sull'analisi dei rischi dell'azienda target, l'approvazione non ha alcun fondamento", es: "Porque la aprobación debe ser informada: sin datos sobre los sistemas, proveedores y análisis de riesgos de la empresa objetivo, la aprobación carece de base", pl: "Ponieważ zatwierdzenie musi być poinformowane - bez faktów o systemach, dostawcach i analizie ryzyka przejmowanej firmy zatwierdzenie nie ma podstaw" },
        { en: "Because the previous CEO's sign-off transfers automatically during an acquisition", de: "Weil die Freigabe des vorherigen CEO bei einer Akquisition automatisch uebertragen wird", nl: "Omdat de goedkeuring van de vorige CEO automatisch wordt overgedragen bij een overname", fr: "Parce que la validation du CEO précédent est transférée automatiquement lors d'une acquisition", it: "Perché l'approvazione del CEO precedente si trasferisce automaticamente durante un'acquisizione", es: "Porque la aprobación del CEO anterior se transfiere automáticamente durante una adquisición", pl: "Ponieważ zatwierdzenie poprzedniego CEO przenosi się automatycznie podczas przejęcia" },
        { en: "Because the budget for integration has not been approved yet", de: "Weil das Budget für die Integration noch nicht genehmigt wurde", nl: "Omdat het budget voor integratie nog niet is goedgekeurd", fr: "Parce que le budget d'intégration n'a pas encore été approuvé", it: "Perché il budget per l'integrazione non è ancora stato approvato", es: "Porque el presupuesto para la integración aún no se ha aprobado", pl: "Ponieważ budżet na integrację nie został jeszcze zatwierdzony" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The sign-off waits until the answer exists because an uninformed approval is meaningless - you need to know what systems, suppliers, and risk state the target brings.",
        de: "Die Freigabe wartet, bis die Antwort vorliegt, denn eine uninformierte Genehmigung ist bedeutungslos - Sie müssen wissen, welche Systeme, Lieferanten und welchen Risikostatus das Zielunternehmen mitbringt.",
        nl: "De goedkeuring wacht tot het antwoord er is, want een ondoordachte goedkeuring is zinloos - u moet weten welke systemen, leveranciers en risicostand het doelbedrijf meebrengt.",
        fr: "La validation attend que la réponse existe car une approbation non éclairée n'a aucun sens - vous devez savoir quels systèmes, fournisseurs et état de risque la cible apporte.",
        it: "L'approvazione attende che la risposta esista perché un'approvazione non informata è priva di significato - dovete sapere quali sistemi, fornitori e stato di rischio porta l'azienda target.",
        es: "La aprobación espera hasta que exista la respuesta porque una aprobación no informada carece de sentido: necesita saber qué sistemas, proveedores y estado de riesgo aporta la empresa objetivo.",
        pl: "Zatwierdzenie czeka, aż pojawi się odpowiedź, ponieważ niepoinformowane zatwierdzenie jest bez znaczenia - musisz wiedzieć, jakie systemy, dostawców i stan ryzyka wnosi przejmowana firma.",
      },
    },
  ],
});

export default quiz;
