import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.4",
  passingScore: 75,
  questions: [
    {
      id: "3.4.1",
      question: {
        en: "When your team says \"We have never had a problem,\" what logical error are they making?",
        de: "Wenn Ihr Team sagt \"Wir hatten noch nie ein Problem\" - welchen logischen Fehler begeht es?",
        nl: "Als uw team zegt \"We hebben nooit een probleem gehad\" - welke logische fout maken ze dan?",
        fr: "Lorsque votre équipe dit « Nous n'avons jamais eu de problème », quelle erreur logique commet-elle ?",
        it: "Quando il vostro team dice \"Non abbiamo mai avuto un problema\", quale errore logico commette?",
        es: "Cuando su equipo dice «Nunca hemos tenido un problema», ¿qué error lógico está cometiendo?",
        pl: "Gdy Twój zespół mówi \"Nigdy nie mieliśmy problemu\" - jaki błąd logiczny popełnia?",
        cs: "Když váš tým řekne „Nikdy jsme neměli problém“, jaké logické chyby se dopouští?",
        pt: "Quando a sua equipa diz «Nunca tivemos um problema», que erro lógico está a cometer?",
        ro: "Când echipa dumneavoastră spune „Nu am avut niciodată o problemă”, ce eroare logică face?",
      },
      options: [
        { en: "Appeal to authority", de: "Autoritaetsargument", nl: "Beroep op autoriteit", fr: "Appel à l'autorité", it: "Appello all'autorità", es: "Apelación a la autoridad", pl: "Odwołanie do autorytetu", cs: "Odvolání na autoritu", pt: "Apelo à autoridade", ro: "Apel la autoritate" },
        { en: "Survivor bias - treating the absence of past incidents as proof that current controls work", de: "Survivorship Bias - das Ausbleiben vergangener Vorfaelle als Beweis zu werten, dass die aktuellen Kontrollen funktionieren", nl: "Survivorship bias - het ontbreken van eerdere incidenten beschouwen als bewijs dat de huidige controles werken", fr: "Biais du survivant - considérer l'absence d'incidents passés comme la preuve que les contrôles actuels fonctionnent", it: "Bias del sopravvissuto - considerare l'assenza di incidenti passati come prova che i controlli attuali funzionano", es: "Sesgo del superviviente: tratar la ausencia de incidentes pasados como prueba de que los controles actuales funcionan", pl: "Błąd przeżywalności - traktowanie braku przeszłych incydentów jako dowodu, że obecne kontrole działają", cs: "Zkreslení přeživších: vnímání nepřítomnosti minulých incidentů jako důkazu, že současná opatření fungují", pt: "Viés do sobrevivente: tratar a ausência de incidentes passados como prova de que os controlos atuais funcionam", ro: "Distorsiunea supraviețuitorului: tratarea absenței incidentelor anterioare ca dovadă că actualele controale funcționează" },
        { en: "False equivalence", de: "Falsche Aequivalenz", nl: "Valse gelijkwaardigheid", fr: "Fausse équivalence", it: "Falsa equivalenza", es: "Falsa equivalencia", pl: "Fałszywa równoważność", cs: "Falešná ekvivalence", pt: "Falsa equivalência", ro: "Falsă echivalență" },
        { en: "Confirmation bias", de: "Bestaetigungsfehler", nl: "Bevestigingsvertekening", fr: "Biais de confirmation", it: "Bias di conferma", es: "Sesgo de confirmación", pl: "Błąd potwierdzenia", cs: "Konfirmační zkreslení", pt: "Viés de confirmação", ro: "Distorsiune de confirmare" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Using the absence of past incidents as evidence of present control is survivor bias. The correct reply is to ask for current test results.",
        de: "Das Ausbleiben vergangener Vorfaelle als Beweis für bestehende Kontrollen zu nutzen, ist Survivorship Bias. Die richtige Antwort ist, nach aktuellen Testergebnissen zu fragen.",
        nl: "Het gebruik van het ontbreken van eerdere incidenten als bewijs voor huidige controle is survivorship bias. Het juiste antwoord is om te vragen naar actuele testresultaten.",
        fr: "Utiliser l'absence d'incidents passés comme preuve du contrôle actuel relève du biais du survivant. La bonne réponse est de demander les résultats des tests actuels.",
        it: "Usare l'assenza di incidenti passati come prova del controllo attuale è bias del sopravvissuto. La risposta corretta è chiedere i risultati dei test attuali.",
        es: "Usar la ausencia de incidentes pasados como prueba del control actual es sesgo del superviviente. La respuesta correcta es pedir los resultados de las pruebas actuales.",
        pl: "Wykorzystanie braku przeszłych incydentów jako dowodu obecnej kontroli to błąd przeżywalności. Poprawną odpowiedzią jest poproszenie o aktualne wyniki testów.",
        cs: "Použití nepřítomnosti minulých incidentů jako důkazu současné ovladatelnosti je zkreslením přeživších. Správnou odpovědí je vyžádat si aktuální výsledky testů.",
        pt: "Usar a ausência de incidentes passados como prova de controlo presente é viés do sobrevivente. A resposta correta é pedir os resultados de testes atuais.",
        ro: "Folosirea absenței incidentelor anterioare ca dovadă a controlului prezent reprezintă distorsiunea supraviețuitorului. Răspunsul corect este să solicitați rezultatele testelor actuale.",
      },
    },
    {
      id: "3.4.2",
      question: {
        en: "Why does the lesson say refusing to sign is your strongest tool?",
        de: "Warum bezeichnet die Lektion die Verweigerung der Unterschrift als Ihr staerkstes Instrument?",
        nl: "Waarom zegt de les dat weigeren te tekenen uw sterkste instrument is?",
        fr: "Pourquoi la leçon affirme-t-elle que refuser de signer est votre outil le plus puissant ?",
        it: "Perché la lezione afferma che rifiutarsi di firmare è il vostro strumento più potente?",
        es: "¿Por qué dice la lección que negarse a firmar es su herramienta más poderosa?",
        pl: "Dlaczego lekcja mówi, że odmowa podpisu to Twoje najsilniejsze narzędzie?",
        cs: "Proč lekce uvádí, že odmítnutí podpisu je vaším nejsilnějším nástrojem?",
        pt: "Por que razão a lição diz que recusar assinar é a sua ferramenta mais forte?",
        ro: "De ce afirmă lecția că refuzul de a semna este cel mai puternic instrument al dumneavoastră?",
      },
      options: [
        { en: "Because it delays the audit and gives you more time", de: "Weil es das Audit verzoegert und Ihnen mehr Zeit gibt", nl: "Omdat het de audit uitstelt en u meer tijd geeft", fr: "Parce que cela retarde l'audit et vous donne plus de temps", it: "Perché ritarda l'audit e vi dà più tempo", es: "Porque retrasa la auditoría y le da más tiempo", pl: "Ponieważ opóźnia audyt i daje Ci więcej czasu", cs: "Protože odkládá audit a získává vám více času", pt: "Porque adia a auditoria e lhe dá mais tempo", ro: "Pentru că amână auditul și vă oferă mai mult timp" },
        { en: "Because it forces the right work to happen before your name goes on a document", de: "Weil es erzwingt, dass die richtige Arbeit erledigt wird, bevor Ihr Name auf einem Dokument steht", nl: "Omdat het afdwingt dat het juiste werk wordt gedaan voordat uw naam op een document staat", fr: "Parce que cela force le bon travail à être réalisé avant que votre nom figure sur un document", it: "Perché costringe a svolgere il lavoro giusto prima che il vostro nome compaia su un documento", es: "Porque obliga a que el trabajo correcto se realice antes de que su nombre figure en un documento", pl: "Ponieważ wymusza wykonanie właściwej pracy, zanim Twoje nazwisko trafi na dokument", cs: "Protože vynutí, aby se správná práce odvedla dříve, než se vaše jméno objeví na dokumentu", pt: "Porque obriga a que o trabalho certo seja feito antes de o seu nome constar de um documento", ro: "Pentru că forțează efectuarea muncii corecte înainte ca numele dumneavoastră să apară pe un document" },
        { en: "Because it transfers liability to the CISO", de: "Weil es die Haftung auf den CISO uebertraegt", nl: "Omdat het de aansprakelijkheid overdraagt aan de CISO", fr: "Parce que cela transfère la responsabilité au CISO", it: "Perché trasferisce la responsabilità al CISO", es: "Porque transfiere la responsabilidad al CISO", pl: "Ponieważ przenosi odpowiedzialność na CISO", cs: "Protože přenáší odpovědnost na CISO", pt: "Porque transfere a responsabilidade para o CISO", ro: "Pentru că transferă răspunderea către CISO" },
        { en: "Because the regulator rewards companies that delay sign-offs", de: "Weil die Aufsichtsbehörde Unternehmen belohnt, die Freigaben verzoegern", nl: "Omdat de toezichthouder bedrijven beloont die goedkeuringen uitstellen", fr: "Parce que l'autorité de régulation récompense les entreprises qui retardent les validations", it: "Perché l'autorità di regolamentazione premia le aziende che ritardano le approvazioni", es: "Porque el regulador premia a las empresas que retrasan las aprobaciones", pl: "Ponieważ organ nadzoru nagradza firmy, które opóźniają zatwierdzenia", cs: "Protože regulační orgán odměňuje společnosti, které podpisy odkládají", pt: "Porque a autoridade reguladora premeia as empresas que adiam as aprovações", ro: "Pentru că autoritatea de reglementare recompensează companiile care amână aprobările" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Refusing to sign is the tool the law gave you to force the right work to happen before your name goes on a document.",
        de: "Die Verweigerung der Unterschrift ist das Werkzeug, das Ihnen das Gesetz gegeben hat, um die richtige Arbeit zu erzwingen, bevor Ihr Name auf einem Dokument steht.",
        nl: "Weigeren te tekenen is het instrument dat de wet u heeft gegeven om af te dwingen dat het juiste werk wordt gedaan voordat uw naam op een document staat.",
        fr: "Refuser de signer est l'outil que la loi vous a donné pour forcer le bon travail à être réalisé avant que votre nom figure sur un document.",
        it: "Rifiutarsi di firmare è lo strumento che la legge vi ha dato per costringere a svolgere il lavoro giusto prima che il vostro nome compaia su un documento.",
        es: "Negarse a firmar es la herramienta que la ley le ha dado para obligar a que el trabajo correcto se realice antes de que su nombre figure en un documento.",
        pl: "Odmowa podpisu to narzędzie, które dało Ci prawo, aby wymusić wykonanie właściwej pracy, zanim Twoje nazwisko trafi na dokument.",
        cs: "Odmítnutí podpisu je nástroj, který vám zákon dal, abyste vynutili odvedení správné práce dříve, než se vaše jméno objeví na dokumentu.",
        pt: "Recusar assinar é a ferramenta que a lei lhe deu para obrigar a que o trabalho certo seja feito antes de o seu nome constar de um documento.",
        ro: "Refuzul de a semna este instrumentul pe care legea vi l-a oferit pentru a forța efectuarea muncii corecte înainte ca numele dumneavoastră să apară pe un document.",
      },
    },
    {
      id: "3.4.3",
      question: {
        en: "When your team says \"We will fix it after the audit,\" what is the correct response?",
        de: "Wenn Ihr Team sagt \"Wir beheben es nach dem Audit\" - was ist die richtige Antwort?",
        nl: "Als uw team zegt \"We lossen het op na de audit\" - wat is dan het juiste antwoord?",
        fr: "Lorsque votre équipe dit « Nous le corrigerons après l'audit », quelle est la bonne réponse ?",
        it: "Quando il vostro team dice \"Lo correggeremo dopo l'audit\", qual è la risposta corretta?",
        es: "Cuando su equipo dice «Lo arreglaremos después de la auditoría», ¿cuál es la respuesta correcta?",
        pl: "Gdy Twój zespół mówi \"Naprawimy to po audycie\" - jaka jest właściwa odpowiedź?",
        cs: "Když váš tým řekne „Opravíme to po auditu“, jaká je správná odpověď?",
        pt: "Quando a sua equipa diz «Corrigimos isso depois da auditoria», qual é a resposta correta?",
        ro: "Când echipa dumneavoastră spune „O remediem după audit”, care este răspunsul corect?",
      },
      options: [
        { en: "\"That is a reasonable approach to prioritisation\"", de: "\"Das ist ein vernuenftiger Ansatz zur Priorisierung\"", nl: "\"Dat is een redelijke aanpak voor prioritering\"", fr: "« C'est une approche raisonnable de la priorisation »", it: "\"È un approccio ragionevole alla definizione delle priorità\"", es: "«Es un enfoque razonable para priorizar»", pl: "\"To rozsądne podejście do ustalania priorytetów\"", cs: "„To je rozumný přístup ke stanovení priorit“", pt: "«Essa é uma abordagem razoável de priorização»", ro: "„Aceasta este o abordare rezonabilă a prioritizării”" },
        { en: "\"If it is known, it is already a finding. Fix it now and I will sign the fix.\"", de: "\"Wenn es bekannt ist, ist es bereits eine Feststellung. Beheben Sie es jetzt, und ich unterschreibe die Behebung.\"", nl: "\"Als het bekend is, is het al een bevinding. Los het nu op en ik onderteken de oplossing.\"", fr: "« Si c'est connu, c'est déjà une constatation. Corrigez-le maintenant et je signerai la correction. »", it: "\"Se è noto, è già un rilievo. Correggetelo subito e firmerò la correzione.\"", es: "«Si se conoce, ya es un hallazgo. Arréglelo ahora y firmaré la corrección.»", pl: "\"Jeśli jest znane, to już jest ustalenie. Napraw to teraz, a podpiszę naprawę.\"", cs: "„Pokud je to známo, je to už zjištění. Opravte to hned a já tu opravu podepíšu.“", pt: "«Se é conhecido, já é uma constatação. Corrija-o agora e eu assino a correção.»", ro: "„Dacă este cunoscut, este deja o constatare. Remediați-l acum și voi semna remedierea.”" },
        { en: "\"Let the auditor decide whether it needs fixing\"", de: "\"Lassen Sie den Auditor entscheiden, ob es behoben werden muss\"", nl: "\"Laat de auditor beslissen of het moet worden opgelost\"", fr: "« Laissez l'auditeur décider s'il faut le corriger »", it: "\"Lasciate che sia l'auditor a decidere se va corretto\"", es: "«Deje que el auditor decida si es necesario corregirlo»", pl: "\"Niech audytor zdecyduje, czy wymaga to naprawy\"", cs: "„Ať o nutnosti opravy rozhodne auditor“", pt: "«Deixe o auditor decidir se precisa de ser corrigido»", ro: "„Lăsați auditorul să decidă dacă trebuie remediat”" },
        { en: "\"Document it as a residual risk and I will accept it\"", de: "\"Dokumentieren Sie es als Restrisiko und ich akzeptiere es\"", nl: "\"Documenteer het als restrisico en ik accepteer het\"", fr: "« Documentez-le comme un risque résiduel et je l'accepterai »", it: "\"Documentatelo come rischio residuo e lo accetterò\"", es: "«Documéntelo como riesgo residual y lo aceptaré»", pl: "\"Udokumentuj to jako ryzyko szczątkowe, a ja je zaakceptuję\"", cs: "„Zdokumentujte to jako zbytkové riziko a já ho přijmu“", pt: "«Documente-o como risco residual e eu aceito-o»", ro: "„Documentați-l ca risc rezidual și îl voi accepta”" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A known gap that the plan is to hide is already a finding. The correct response is to fix it now and sign the fix.",
        de: "Eine bekannte Lücke, die man verbergen will, ist bereits eine Feststellung. Die richtige Antwort ist, sie jetzt zu beheben und die Behebung zu unterschreiben.",
        nl: "Een bekende lacune die men van plan is te verbergen, is al een bevinding. Het juiste antwoord is om het nu op te lossen en de oplossing te ondertekenen.",
        fr: "Une lacune connue que l'on prévoit de cacher est déjà une constatation. La bonne réponse est de la corriger maintenant et de signer la correction.",
        it: "Una lacuna nota che si intende nascondere è già un rilievo. La risposta corretta è correggerla subito e firmare la correzione.",
        es: "Una brecha conocida que se pretende ocultar ya es un hallazgo. La respuesta correcta es arreglarla ahora y firmar la corrección.",
        pl: "Znana luka, którą planuje się ukryć, jest już ustaleniem. Właściwą odpowiedzią jest naprawienie jej teraz i podpisanie naprawy.",
        cs: "Známá mezera, kterou se plánuje zatajit, je už zjištěním. Správnou odpovědí je opravit ji hned a opravu podepsat.",
        pt: "Uma lacuna conhecida que se planeia ocultar é já uma constatação. A resposta correta é corrigi-la agora e assinar a correção.",
        ro: "O lacună cunoscută pe care se intenționează să o ascundeți este deja o constatare. Răspunsul corect este să o remediați acum și să semnați remedierea.",
      },
    },
    {
      id: "3.4.4",
      question: {
        en: "What is the lesson's rule for detecting a broken sign-off process?",
        de: "Wie lautet die Regel der Lektion, um einen defekten Freigabeprozess zu erkennen?",
        nl: "Wat is de regel van de les voor het herkennen van een gebrekkig goedkeuringsproces?",
        fr: "Quelle est la règle de la leçon pour détecter un processus de validation défaillant ?",
        it: "Qual è la regola della lezione per individuare un processo di approvazione difettoso?",
        es: "¿Cuál es la regla de la lección para detectar un proceso de aprobación defectuoso?",
        pl: "Jaka jest reguła lekcji służąca do wykrywania wadliwego procesu zatwierdzania?",
        cs: "Jaké je pravidlo lekce pro rozpoznání nefunkčního schvalovacího procesu?",
        pt: "Qual é a regra da lição para detetar um processo de aprovação deficiente?",
        ro: "Care este regula lecției pentru detectarea unui proces de aprobare defectuos?",
      },
      options: [
        { en: "If the document has not changed since last year", de: "Wenn sich das Dokument seit letztem Jahr nicht geändert hat", nl: "Als het document niet is gewijzigd since vorig jaar", fr: "Si le document n'a pas changé depuis l'année dernière", it: "Se il documento non è cambiato dall'anno scorso", es: "Si el documento no ha cambiado desde el año pasado", pl: "Jeśli dokument nie zmienił się od zeszłego roku", cs: "Pokud se dokument od loňského roku nezměnil", pt: "Se o documento não mudou desde o ano passado", ro: "Dacă documentul nu s-a schimbat de anul trecut" },
        { en: "If the CISO is not present at the signing", de: "Wenn der CISO bei der Unterschrift nicht anwesend ist", nl: "Als de CISO niet aanwezig is bij de ondertekening", fr: "Si le CISO n'est pas présent lors de la signature", it: "Se il CISO non è presente alla firma", es: "Si el CISO no está presente en la firma", pl: "Jeśli CISO nie jest obecny przy podpisywaniu", cs: "Pokud CISO není u podpisu přítomen", pt: "Se o CISO não estiver presente na assinatura", ro: "Dacă CISO nu este prezent la semnare" },
        { en: "If the explanation feels faster than the document, the process is broken", de: "Wenn die Erklaerung schneller wirkt als das Dokument, ist der Prozess defekt", nl: "Als de toelichting sneller aanvoelt dan het document, is het proces gebrekkig", fr: "Si l'explication semble plus rapide que le document, le processus est défaillant", it: "Se la spiegazione sembra più rapida del documento, il processo è difettoso", es: "Si la explicación parece más rápida que el documento, el proceso es defectuoso", pl: "Jeśli wyjaśnienie wydaje się szybsze niż dokument, proces jest wadliwy", cs: "Pokud vysvětlení působí rychleji než dokument, je proces nefunkční", pt: "Se a explicação parecer mais rápida do que o documento, o processo está deficiente", ro: "Dacă explicația pare mai rapidă decât documentul, procesul este defectuos" },
        { en: "If the budget has not been updated", de: "Wenn das Budget nicht aktualisiert wurde", nl: "Als het budget niet is bijgewerkt", fr: "Si le budget n'a pas été mis à jour", it: "Se il budget non è stato aggiornato", es: "Si el presupuesto no se ha actualizado", pl: "Jeśli budżet nie został zaktualizowany", cs: "Pokud nebyl aktualizován rozpočet", pt: "Se o orçamento não foi atualizado", ro: "Dacă bugetul nu a fost actualizat" },
      ],
      correctIndex: 2,
      explanation: {
        en: "If the explanation feels faster than the document, the process is broken. Refusing costs hours. Signing blind costs years.",
        de: "Wenn die Erklaerung schneller wirkt als das Dokument, ist der Prozess defekt. Verweigern kostet Stunden. Blind unterschreiben kostet Jahre.",
        nl: "Als de toelichting sneller aanvoelt dan het document, is het proces gebrekkig. Weigeren kost uren. Blind tekenen kost jaren.",
        fr: "Si l'explication semble plus rapide que le document, le processus est défaillant. Refuser coûte des heures. Signer à l'aveugle coûte des années.",
        it: "Se la spiegazione sembra più rapida del documento, il processo è difettoso. Rifiutare costa ore. Firmare alla cieca costa anni.",
        es: "Si la explicación parece más rápida que el documento, el proceso es defectuoso. Negarse cuesta horas. Firmar a ciegas cuesta años.",
        pl: "Jeśli wyjaśnienie wydaje się szybsze niż dokument, proces jest wadliwy. Odmowa kosztuje godziny. Podpisanie w ciemno kosztuje lata.",
        cs: "Pokud vysvětlení působí rychleji než dokument, je proces nefunkční. Odmítnutí stojí hodiny. Podpis naslepo stojí roky.",
        pt: "Se a explicação parecer mais rápida do que o documento, o processo está deficiente. Recusar custa horas. Assinar às cegas custa anos.",
        ro: "Dacă explicația pare mai rapidă decât documentul, procesul este defectuos. Refuzul costă ore. Semnatul orbește costă ani.",
      },
    },
  ],
});

export default quiz;
