import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.5",
  passingScore: 75,
  questions: [
    {
      id: "3.5.1",
      question: {
        en: "How many non-delegable decisions does the lesson identify under NIS2?",
        de: "Wie viele nicht delegierbare Entscheidungen identifiziert die Lektion unter NIS2?",
        nl: "Hoeveel niet-delegeerbare beslissingen identificeert de les onder NIS2?",
        fr: "Combien de décisions non délégables la leçon identifie-t-elle au titre de NIS2 ?",
        it: "Quante decisioni non delegabili individua la lezione nell'ambito di NIS2?",
        es: "¿Cuántas decisiones no delegables identifica la lección en el marco de NIS2?",
        pl: "Ile niedelegowalnych decyzji identyfikuje lekcja w ramach NIS2?",
        cs: "Kolik nedelegovatelných rozhodnutí lekce v rámci NIS2 určuje?",
        pt: "Quantas decisões indelegáveis identifica a lição ao abrigo da NIS2?",
        ro: "Câte decizii nedelegabile identifică lecția în temeiul NIS2?",
      },
      options: [
        { en: "Five", de: "Fünf", nl: "Vijf", fr: "Cinq", it: "Cinque", es: "Cinco", pl: "Pięć", cs: "Pět", pt: "Cinco", ro: "Cinci" },
        { en: "Seven", de: "Sieben", nl: "Zeven", fr: "Sept", it: "Sette", es: "Siete", pl: "Siedem", cs: "Sedm", pt: "Sete", ro: "Șapte" },
        { en: "Nine", de: "Neun", nl: "Negen", fr: "Neuf", it: "Nove", es: "Nueve", pl: "Dziewięć", cs: "Devět", pt: "Nove", ro: "Nouă" },
        { en: "Eleven", de: "Elf", nl: "Elf", fr: "Onze", it: "Undici", es: "Once", pl: "Jedenaście", cs: "Jedenáct", pt: "Onze", ro: "Unsprezece" },
      ],
      correctIndex: 3,
      explanation: {
        en: "The lesson identifies eleven non-delegable decisions, each requiring a signed artefact.",
        de: "Die Lektion identifiziert elf nicht delegierbare Entscheidungen, die jeweils ein unterschriebenes Artefakt erfordern.",
        nl: "De les identificeert elf niet-delegeerbare beslissingen, elk vereist een ondertekend artefact.",
        fr: "La leçon identifie onze décisions non délégables, chacune exigeant un artefact signé.",
        it: "La lezione individua undici decisioni non delegabili, ciascuna delle quali richiede un artefatto firmato.",
        es: "La lección identifica once decisiones no delegables, cada una de las cuales requiere un artefacto firmado.",
        pl: "Lekcja identyfikuje jedenaście niedelegowalnych decyzji, z których każda wymaga podpisanego artefaktu.",
        cs: "Lekce určuje jedenáct nedelegovatelných rozhodnutí, z nichž každé vyžaduje podepsaný artefakt.",
        pt: "A lição identifica onze decisões indelegáveis, exigindo cada uma um artefacto assinado.",
        ro: "Lecția identifică unsprezece decizii nedelegabile, fiecare necesitând un artefact semnat.",
      },
    },
    {
      id: "3.5.2",
      question: {
        en: "Which single artefact do most CEOs fail to produce in an audit?",
        de: "Welches einzelne Artefakt koennen die meisten CEOs bei einem Audit nicht vorlegen?",
        nl: "Welk enkel artefact kunnen de meeste CEO's niet produceren bij een audit?",
        fr: "Quel unique artefact la plupart des CEO ne parviennent-ils pas à produire lors d'un audit ?",
        it: "Quale singolo artefatto la maggior parte dei CEO non riesce a produrre in un audit?",
        es: "¿Qué único artefacto la mayoría de los CEO no logra presentar en una auditoría?",
        pl: "Którego pojedynczego artefaktu większość CEO nie potrafi przedstawić podczas audytu?",
        cs: "Který jediný artefakt většina generálních ředitelů při auditu nedokáže předložit?",
        pt: "Que artefacto único a maioria dos diretores executivos não consegue apresentar numa auditoria?",
        ro: "Care artefact unic nu reușesc majoritatea directorilor generali să îl prezinte într-un audit?",
      },
      options: [
        { en: "The signed top-level security policy", de: "Die unterschriebene übergeordnete Sicherheitsrichtlinie", nl: "Het ondertekende overkoepelende beveiligingsbeleid", fr: "La politique de sécurité de haut niveau signée", it: "La politica di sicurezza di alto livello firmata", es: "La política de seguridad de alto nivel firmada", pl: "Podpisana nadrzędna polityka bezpieczeństwa", cs: "Podepsanou nadřazenou bezpečnostní politiku", pt: "A política de segurança de nível superior assinada", ro: "Politica de securitate de nivel superior semnată" },
        { en: "The signed residual risk acceptance", de: "Die unterschriebene Restrisikoakzeptanz", nl: "De ondertekende restrisico-acceptatie", fr: "L'acceptation signée du risque résiduel", it: "L'accettazione firmata del rischio residuo", es: "La aceptación firmada del riesgo residual", pl: "Podpisana akceptacja ryzyka szczątkowego", cs: "Podepsané přijetí zbytkového rizika", pt: "A aceitação assinada do risco residual", ro: "Acceptarea semnată a riscului rezidual" },
        { en: "The annual management review minutes", de: "Das Protokoll der jährlichen Management-Bewertung", nl: "De notulen van de jaarlijkse managementbeoordeling", fr: "Le compte rendu de la revue de direction annuelle", it: "Il verbale del riesame annuale della direzione", es: "El acta de la revisión anual por la dirección", pl: "Protokół z rocznego przeglądu zarządzania", cs: "Zápis z ročního přezkumu vedením", pt: "A ata da revisão anual pela gestão", ro: "Procesul-verbal al revizuirii anuale efectuate de conducere" },
        { en: "The crisis declaration record", de: "Die Krisenerklaerung", nl: "De crisisdeclaratie", fr: "Le registre de déclaration de crise", it: "Il registro di dichiarazione di crisi", es: "El registro de declaración de crisis", pl: "Zapis ogłoszenia kryzysu", cs: "Záznam o vyhlášení krize", pt: "O registo da declaração de crise", ro: "Înregistrarea declarării crizei" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The residual risk acceptance is the single document auditors look for first and the single document most CEOs cannot produce.",
        de: "Die Restrisikoakzeptanz ist das einzelne Dokument, nach dem Auditoren zuerst suchen, und das einzelne Dokument, das die meisten CEOs nicht vorlegen koennen.",
        nl: "De restrisico-acceptatie is het enige document waarnaar auditors als eerste zoeken en dat de meeste CEO's niet kunnen produceren.",
        fr: "L'acceptation du risque résiduel est le seul document que les auditeurs recherchent en premier et le seul document que la plupart des CEO ne peuvent pas produire.",
        it: "L'accettazione del rischio residuo è l'unico documento che gli auditor cercano per primo e l'unico documento che la maggior parte dei CEO non riesce a produrre.",
        es: "La aceptación del riesgo residual es el único documento que los auditores buscan primero y el único documento que la mayoría de los CEO no puede presentar.",
        pl: "Akceptacja ryzyka szczątkowego to jedyny dokument, którego audytorzy szukają w pierwszej kolejności, i jedyny dokument, którego większość CEO nie potrafi przedstawić.",
        cs: "Přijetí zbytkového rizika je jediným dokumentem, který auditoři hledají jako první, a jediným dokumentem, který většina generálních ředitelů nedokáže předložit.",
        pt: "A aceitação do risco residual é o único documento que os auditores procuram primeiro e o único documento que a maioria dos diretores executivos não consegue apresentar.",
        ro: "Acceptarea riscului rezidual este singurul document pe care auditorii îl caută mai întâi și singurul document pe care majoritatea directorilor generali nu îl pot prezenta.",
      },
    },
    {
      id: "3.5.3",
      question: {
        en: "What three things should each residual risk in the signed risk register include?",
        de: "Welche drei Dinge sollte jedes Restrisiko im unterschriebenen Risikoregister enthalten?",
        nl: "Wat moeten drie dingen zijn voor elk resterend risico in het ondertekende risicoregister?",
        fr: "Quelles trois choses chaque risque résiduel du registre des risques signé doit-il inclure ?",
        it: "Quali tre cose dovrebbe includere ogni rischio residuo nel registro dei rischi firmato?",
        es: "¿Qué tres cosas debe incluir cada riesgo residual en el registro de riesgos firmado?",
        pl: "Jakie trzy rzeczy powinno zawierać każde ryzyko szczątkowe w podpisanym rejestrze ryzyka?",
        cs: "Které tři věci by mělo každé zbytkové riziko v podepsaném registru rizik obsahovat?",
        pt: "Que três coisas deve cada risco residual no registo de riscos assinado incluir?",
        ro: "Ce trei lucruri ar trebui să includă fiecare risc rezidual din registrul de riscuri semnat?",
      },
      options: [
        { en: "A rating, a description of what is being accepted, and a named owner with a review date", de: "Eine Bewertung, eine Beschreibung dessen, was akzeptiert wird, und einen benannten Verantwortlichen mit Prüfungsdatum", nl: "Een beoordeling, een beschrijving van wat wordt geaccepteerd en een benoemde eigenaar met een beoordelingsdatum", fr: "Une évaluation, une description de ce qui est accepté, et un responsable nommé avec une date de révision", it: "Una valutazione, una descrizione di ciò che viene accettato e un responsabile nominato con una data di revisione", es: "Una calificación, una descripción de lo que se acepta y un responsable nombrado con una fecha de revisión", pl: "Ocenę, opis tego, co jest akceptowane, oraz wyznaczonego właściciela z datą przeglądu", cs: "Hodnocení, popis toho, co se přijímá, a jmenovaného vlastníka s datem přezkumu", pt: "Uma classificação, uma descrição do que está a ser aceite e um responsável designado com uma data de revisão", ro: "O evaluare, o descriere a ceea ce se acceptă și un responsabil desemnat cu o dată de revizuire" },
        { en: "A cost estimate, a timeline for elimination, and an insurance policy reference", de: "Eine Kostenschaetzung, einen Zeitplan zur Beseitigung und eine Versicherungspolice-Referenz", nl: "Een kostenraming, een tijdlijn voor eliminatie en een verwijzing naar een verzekeringspolis", fr: "Une estimation des coûts, un calendrier d'élimination et une référence de police d'assurance", it: "Una stima dei costi, una tempistica per l'eliminazione e un riferimento alla polizza assicurativa", es: "Una estimación de costes, un calendario de eliminación y una referencia de la póliza de seguro", pl: "Szacunkowy koszt, harmonogram eliminacji oraz odniesienie do polisy ubezpieczeniowej", cs: "Odhad nákladů, harmonogram odstranění a odkaz na pojistnou smlouvu", pt: "Uma estimativa de custos, um calendário de eliminação e uma referência à apólice de seguro", ro: "O estimare de costuri, un calendar de eliminare și o referință la polița de asigurare" },
        { en: "A CISO recommendation, a legal opinion, and a budget allocation", de: "Eine CISO-Empfehlung, ein Rechtsgutachten und eine Budgetzuweisung", nl: "Een CISO-aanbeveling, een juridisch advies en een budgettoewijzing", fr: "Une recommandation du CISO, un avis juridique et une allocation budgétaire", it: "Una raccomandazione del CISO, un parere legale e uno stanziamento di budget", es: "Una recomendación del CISO, un dictamen jurídico y una asignación presupuestaria", pl: "Zalecenie CISO, opinię prawną oraz przydział budżetu", cs: "Doporučení CISO, právní stanovisko a přidělení rozpočtu", pt: "Uma recomendação do CISO, um parecer jurídico e uma dotação orçamental", ro: "O recomandare a CISO, un aviz juridic și o alocare bugetară" },
        { en: "A threat source, an attack vector, and a vulnerability scan report", de: "Eine Bedrohungsquelle, einen Angriffsvektor und einen Schwachstellen-Scan-Bericht", nl: "Een dreigingsbron, een aanvalsvector en een kwetsbaarheidsrapport", fr: "Une source de menace, un vecteur d'attaque et un rapport d'analyse des vulnérabilités", it: "Una fonte di minaccia, un vettore di attacco e un rapporto di scansione delle vulnerabilità", es: "Una fuente de amenaza, un vector de ataque y un informe de análisis de vulnerabilidades", pl: "Źródło zagrożenia, wektor ataku oraz raport ze skanowania podatności", cs: "Zdroj hrozby, vektor útoku a zprávu z kontroly zranitelností", pt: "Uma fonte de ameaça, um vetor de ataque e um relatório de análise de vulnerabilidades", ro: "O sursă de amenințare, un vector de atac și un raport de scanare a vulnerabilităților" },
      ],
      correctIndex: 0,
      explanation: {
        en: "Each residual risk needs a rating, a description of what is being accepted, and a named owner with a review date.",
        de: "Jedes Restrisiko benoetigt eine Bewertung, eine Beschreibung dessen, was akzeptiert wird, und einen benannten Verantwortlichen mit Prüfungsdatum.",
        nl: "Elk resterend risico heeft een beoordeling nodig, een beschrijving van wat wordt geaccepteerd en een benoemde eigenaar met een beoordelingsdatum.",
        fr: "Chaque risque résiduel nécessite une évaluation, une description de ce qui est accepté et un responsable nommé avec une date de révision.",
        it: "Ogni rischio residuo necessita di una valutazione, di una descrizione di ciò che viene accettato e di un responsabile nominato con una data di revisione.",
        es: "Cada riesgo residual necesita una calificación, una descripción de lo que se acepta y un responsable nombrado con una fecha de revisión.",
        pl: "Każde ryzyko szczątkowe wymaga oceny, opisu tego, co jest akceptowane, oraz wyznaczonego właściciela z datą przeglądu.",
        cs: "Každé zbytkové riziko potřebuje hodnocení, popis toho, co se přijímá, a jmenovaného vlastníka s datem přezkumu.",
        pt: "Cada risco residual precisa de uma classificação, de uma descrição do que está a ser aceite e de um responsável designado com uma data de revisão.",
        ro: "Fiecare risc rezidual are nevoie de o evaluare, de o descriere a ceea ce se acceptă și de un responsabil desemnat cu o dată de revizuire.",
      },
    },
    {
      id: "3.5.4",
      question: {
        en: "What is the lesson's rule for borderline decisions where you are unsure whether your signature is needed?",
        de: "Wie lautet die Regel der Lektion für Grenzfälle, bei denen Sie unsicher sind, ob Ihre Unterschrift erforderlich ist?",
        nl: "Wat is de regel van de les voor grensgevallen waarbij u niet zeker weet of uw handtekening nodig is?",
        fr: "Quelle est la règle de la leçon pour les décisions limites où vous n'êtes pas sûr que votre signature soit nécessaire ?",
        it: "Qual è la regola della lezione per le decisioni borderline in cui non siete sicuri se la vostra firma sia necessaria?",
        es: "¿Cuál es la regla de la lección para las decisiones límite en las que no está seguro de si se necesita su firma?",
        pl: "Jaka jest reguła lekcji dla granicznych decyzji, gdy nie masz pewności, czy Twój podpis jest potrzebny?",
        cs: "Jaké je pravidlo lekce pro hraniční rozhodnutí, u nichž si nejste jisti, zda je váš podpis potřeba?",
        pt: "Qual é a regra da lição para decisões limítrofes em que não tem certeza se a sua assinatura é necessária?",
        ro: "Care este regula lecției pentru deciziile la limită în care nu sunteți sigur dacă semnătura dumneavoastră este necesară?",
      },
      options: [
        { en: "Delegate to the CISO and review later", de: "An den CISO delegieren und spaeter prüfen", nl: "Delegeer aan de CISO en controleer later", fr: "Déléguer au CISO et examiner plus tard", it: "Delegare al CISO ed esaminare in seguito", es: "Delegar en el CISO y revisar más tarde", pl: "Przekazać CISO i sprawdzić później", cs: "Delegovat na CISO a přezkoumat později", pt: "Delegar no CISO e rever mais tarde", ro: "Delegați către CISO și revizuiți ulterior" },
        { en: "Ask the auditor for guidance", de: "Den Auditor um Orientierung bitten", nl: "Vraag de auditor om begeleiding", fr: "Demander conseil à l'auditeur", it: "Chiedere indicazioni all'auditor", es: "Pedir orientación al auditor", pl: "Poprosić audytora o wskazówki", cs: "Požádat auditora o radu", pt: "Pedir orientação ao auditor", ro: "Solicitați îndrumare auditorului" },
        { en: "Treat it as non-delegable and sign it yourself", de: "Als nicht delegierbar behandeln und selbst unterschreiben", nl: "Behandel het als niet-delegeerbaar en onderteken het zelf", fr: "La traiter comme non délégable et la signer vous-même", it: "Trattarla come non delegabile e firmarla voi stessi", es: "Tratarla como no delegable y firmarla usted mismo", pl: "Potraktować ją jako niedelegowalną i podpisać samodzielnie", cs: "Považovat ho za nedelegovatelné a podepsat ho sám", pt: "Tratá-la como indelegável e assiná-la pessoalmente", ro: "Tratați-o ca nedelegabilă și semnați-o personal" },
        { en: "Wait until the annual review cycle", de: "Bis zum jährlichen Prüfungszyklus warten", nl: "Wacht tot de jaarlijkse beoordelingscyclus", fr: "Attendre le cycle de révision annuel", it: "Attendere il ciclo di revisione annuale", es: "Esperar al ciclo de revisión anual", pl: "Poczekać do rocznego cyklu przeglądu", cs: "Počkat na cyklus ročního přezkumu", pt: "Esperar até ao ciclo de revisão anual", ro: "Așteptați până la ciclul de revizuire anuală" },
      ],
      correctIndex: 2,
      explanation: {
        en: "When the line is blurry, treat the decision as non-delegable and sign it yourself.",
        de: "Wenn die Grenze unklar ist, behandeln Sie die Entscheidung als nicht delegierbar und unterschreiben Sie selbst.",
        nl: "Wanneer de grens onduidelijk is, behandel de beslissing als niet-delegeerbaar en onderteken het zelf.",
        fr: "Lorsque la limite est floue, traitez la décision comme non délégable et signez-la vous-même.",
        it: "Quando il confine è sfocato, trattate la decisione come non delegabile e firmatela voi stessi.",
        es: "Cuando el límite es difuso, trate la decisión como no delegable y fírmela usted mismo.",
        pl: "Gdy granica jest niejasna, potraktuj decyzję jako niedelegowalną i podpisz ją samodzielnie.",
        cs: "Když je hranice nejasná, považujte rozhodnutí za nedelegovatelné a podepište ho sami.",
        pt: "Quando a fronteira é difusa, trate a decisão como indelegável e assine-a pessoalmente.",
        ro: "Când limita este neclară, tratați decizia ca nedelegabilă și semnați-o personal.",
      },
    },
  ],
});

export default quiz;
