import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.5",
  passingScore: 75,
  questions: [
    {
      id: "3.5.1",
      question: {
        en: "How many non-delegable decisions does the lesson identify under NIS2?",
        de: "Wie viele nicht delegierbare Entscheidungen identifiziert die Lektion unter NIS2?",
        nl: "Hoeveel niet-delegeerbare beslissingen identificeert de les onder NIS2?",
        fr: "Combien de décisions non délégables la leçon identifie-t-elle au titre de NIS2 ?",
        it: "Quante decisioni non delegabili individua la lezione nell'ambito di NIS2?",
        es: "¿Cuántas decisiones no delegables identifica la lección en el marco de NIS2?",
        pl: "Ile niedelegowalnych decyzji identyfikuje lekcja w ramach NIS2?",
      },
      options: [
        { en: "Five", de: "Fünf", nl: "Vijf", fr: "Cinq", it: "Cinque", es: "Cinco", pl: "Pięć" },
        { en: "Seven", de: "Sieben", nl: "Zeven", fr: "Sept", it: "Sette", es: "Siete", pl: "Siedem" },
        { en: "Nine", de: "Neun", nl: "Negen", fr: "Neuf", it: "Nove", es: "Nueve", pl: "Dziewięć" },
        { en: "Eleven", de: "Elf", nl: "Elf", fr: "Onze", it: "Undici", es: "Once", pl: "Jedenaście" },
      ],
      correctIndex: 3,
      explanation: {
        en: "The lesson identifies eleven non-delegable decisions, each requiring a signed artefact.",
        de: "Die Lektion identifiziert elf nicht delegierbare Entscheidungen, die jeweils ein unterschriebenes Artefakt erfordern.",
        nl: "De les identificeert elf niet-delegeerbare beslissingen, elk vereist een ondertekend artefact.",
        fr: "La leçon identifie onze décisions non délégables, chacune exigeant un artefact signé.",
        it: "La lezione individua undici decisioni non delegabili, ciascuna delle quali richiede un artefatto firmato.",
        es: "La lección identifica once decisiones no delegables, cada una de las cuales requiere un artefacto firmado.",
        pl: "Lekcja identyfikuje jedenaście niedelegowalnych decyzji, z których każda wymaga podpisanego artefaktu.",
      },
    },
    {
      id: "3.5.2",
      question: {
        en: "Which single artefact do most CEOs fail to produce in an audit?",
        de: "Welches einzelne Artefakt koennen die meisten CEOs bei einem Audit nicht vorlegen?",
        nl: "Welk enkel artefact kunnen de meeste CEO's niet produceren bij een audit?",
        fr: "Quel unique artefact la plupart des CEO ne parviennent-ils pas à produire lors d'un audit ?",
        it: "Quale singolo artefatto la maggior parte dei CEO non riesce a produrre in un audit?",
        es: "¿Qué único artefacto la mayoría de los CEO no logra presentar en una auditoría?",
        pl: "Którego pojedynczego artefaktu większość CEO nie potrafi przedstawić podczas audytu?",
      },
      options: [
        { en: "The signed top-level security policy", de: "Die unterschriebene übergeordnete Sicherheitsrichtlinie", nl: "Het ondertekende overkoepelende beveiligingsbeleid", fr: "La politique de sécurité de haut niveau signée", it: "La politica di sicurezza di alto livello firmata", es: "La política de seguridad de alto nivel firmada", pl: "Podpisana nadrzędna polityka bezpieczeństwa" },
        { en: "The signed residual risk acceptance", de: "Die unterschriebene Restrisikoakzeptanz", nl: "De ondertekende restrisico-acceptatie", fr: "L'acceptation signée du risque résiduel", it: "L'accettazione firmata del rischio residuo", es: "La aceptación firmada del riesgo residual", pl: "Podpisana akceptacja ryzyka szczątkowego" },
        { en: "The annual management review minutes", de: "Das Protokoll der jährlichen Management-Bewertung", nl: "De notulen van de jaarlijkse managementbeoordeling", fr: "Le compte rendu de la revue de direction annuelle", it: "Il verbale del riesame annuale della direzione", es: "El acta de la revisión anual por la dirección", pl: "Protokół z rocznego przeglądu zarządzania" },
        { en: "The crisis declaration record", de: "Die Krisenerklaerung", nl: "De crisisdeclaratie", fr: "Le registre de déclaration de crise", it: "Il registro di dichiarazione di crisi", es: "El registro de declaración de crisis", pl: "Zapis ogłoszenia kryzysu" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The residual risk acceptance is the single document auditors look for first and the single document most CEOs cannot produce.",
        de: "Die Restrisikoakzeptanz ist das einzelne Dokument, nach dem Auditoren zuerst suchen, und das einzelne Dokument, das die meisten CEOs nicht vorlegen koennen.",
        nl: "De restrisico-acceptatie is het enige document waarnaar auditors als eerste zoeken en dat de meeste CEO's niet kunnen produceren.",
        fr: "L'acceptation du risque résiduel est le seul document que les auditeurs recherchent en premier et le seul document que la plupart des CEO ne peuvent pas produire.",
        it: "L'accettazione del rischio residuo è l'unico documento che gli auditor cercano per primo e l'unico documento che la maggior parte dei CEO non riesce a produrre.",
        es: "La aceptación del riesgo residual es el único documento que los auditores buscan primero y el único documento que la mayoría de los CEO no puede presentar.",
        pl: "Akceptacja ryzyka szczątkowego to jedyny dokument, którego audytorzy szukają w pierwszej kolejności, i jedyny dokument, którego większość CEO nie potrafi przedstawić.",
      },
    },
    {
      id: "3.5.3",
      question: {
        en: "What three things should each residual risk in the signed risk register include?",
        de: "Welche drei Dinge sollte jedes Restrisiko im unterschriebenen Risikoregister enthalten?",
        nl: "Wat moeten drie dingen zijn voor elk resterend risico in het ondertekende risicoregister?",
        fr: "Quelles trois choses chaque risque résiduel du registre des risques signé doit-il inclure ?",
        it: "Quali tre cose dovrebbe includere ogni rischio residuo nel registro dei rischi firmato?",
        es: "¿Qué tres cosas debe incluir cada riesgo residual en el registro de riesgos firmado?",
        pl: "Jakie trzy rzeczy powinno zawierać każde ryzyko szczątkowe w podpisanym rejestrze ryzyka?",
      },
      options: [
        { en: "A rating, a description of what is being accepted, and a named owner with a review date", de: "Eine Bewertung, eine Beschreibung dessen, was akzeptiert wird, und einen benannten Verantwortlichen mit Prüfungsdatum", nl: "Een beoordeling, een beschrijving van wat wordt geaccepteerd en een benoemde eigenaar met een beoordelingsdatum", fr: "Une évaluation, une description de ce qui est accepté, et un responsable nommé avec une date de révision", it: "Una valutazione, una descrizione di ciò che viene accettato e un responsabile nominato con una data di revisione", es: "Una calificación, una descripción de lo que se acepta y un responsable nombrado con una fecha de revisión", pl: "Ocenę, opis tego, co jest akceptowane, oraz wyznaczonego właściciela z datą przeglądu" },
        { en: "A cost estimate, a timeline for elimination, and an insurance policy reference", de: "Eine Kostenschaetzung, einen Zeitplan zur Beseitigung und eine Versicherungspolice-Referenz", nl: "Een kostenraming, een tijdlijn voor eliminatie en een verwijzing naar een verzekeringspolis", fr: "Une estimation des coûts, un calendrier d'élimination et une référence de police d'assurance", it: "Una stima dei costi, una tempistica per l'eliminazione e un riferimento alla polizza assicurativa", es: "Una estimación de costes, un calendario de eliminación y una referencia de la póliza de seguro", pl: "Szacunkowy koszt, harmonogram eliminacji oraz odniesienie do polisy ubezpieczeniowej" },
        { en: "A CISO recommendation, a legal opinion, and a budget allocation", de: "Eine CISO-Empfehlung, ein Rechtsgutachten und eine Budgetzuweisung", nl: "Een CISO-aanbeveling, een juridisch advies en een budgettoewijzing", fr: "Une recommandation du CISO, un avis juridique et une allocation budgétaire", it: "Una raccomandazione del CISO, un parere legale e uno stanziamento di budget", es: "Una recomendación del CISO, un dictamen jurídico y una asignación presupuestaria", pl: "Zalecenie CISO, opinię prawną oraz przydział budżetu" },
        { en: "A threat source, an attack vector, and a vulnerability scan report", de: "Eine Bedrohungsquelle, einen Angriffsvektor und einen Schwachstellen-Scan-Bericht", nl: "Een dreigingsbron, een aanvalsvector en een kwetsbaarheidsrapport", fr: "Une source de menace, un vecteur d'attaque et un rapport d'analyse des vulnérabilités", it: "Una fonte di minaccia, un vettore di attacco e un rapporto di scansione delle vulnerabilità", es: "Una fuente de amenaza, un vector de ataque y un informe de análisis de vulnerabilidades", pl: "Źródło zagrożenia, wektor ataku oraz raport ze skanowania podatności" },
      ],
      correctIndex: 0,
      explanation: {
        en: "Each residual risk needs a rating, a description of what is being accepted, and a named owner with a review date.",
        de: "Jedes Restrisiko benoetigt eine Bewertung, eine Beschreibung dessen, was akzeptiert wird, und einen benannten Verantwortlichen mit Prüfungsdatum.",
        nl: "Elk resterend risico heeft een beoordeling nodig, een beschrijving van wat wordt geaccepteerd en een benoemde eigenaar met een beoordelingsdatum.",
        fr: "Chaque risque résiduel nécessite une évaluation, une description de ce qui est accepté et un responsable nommé avec une date de révision.",
        it: "Ogni rischio residuo necessita di una valutazione, di una descrizione di ciò che viene accettato e di un responsabile nominato con una data di revisione.",
        es: "Cada riesgo residual necesita una calificación, una descripción de lo que se acepta y un responsable nombrado con una fecha de revisión.",
        pl: "Każde ryzyko szczątkowe wymaga oceny, opisu tego, co jest akceptowane, oraz wyznaczonego właściciela z datą przeglądu.",
      },
    },
    {
      id: "3.5.4",
      question: {
        en: "What is the lesson's rule for borderline decisions where you are unsure whether your signature is needed?",
        de: "Wie lautet die Regel der Lektion für Grenzfälle, bei denen Sie unsicher sind, ob Ihre Unterschrift erforderlich ist?",
        nl: "Wat is de regel van de les voor grensgevallen waarbij u niet zeker weet of uw handtekening nodig is?",
        fr: "Quelle est la règle de la leçon pour les décisions limites où vous n'êtes pas sûr que votre signature soit nécessaire ?",
        it: "Qual è la regola della lezione per le decisioni borderline in cui non siete sicuri se la vostra firma sia necessaria?",
        es: "¿Cuál es la regla de la lección para las decisiones límite en las que no está seguro de si se necesita su firma?",
        pl: "Jaka jest reguła lekcji dla granicznych decyzji, gdy nie masz pewności, czy Twój podpis jest potrzebny?",
      },
      options: [
        { en: "Delegate to the CISO and review later", de: "An den CISO delegieren und spaeter prüfen", nl: "Delegeer aan de CISO en controleer later", fr: "Déléguer au CISO et examiner plus tard", it: "Delegare al CISO ed esaminare in seguito", es: "Delegar en el CISO y revisar más tarde", pl: "Przekazać CISO i sprawdzić później" },
        { en: "Ask the auditor for guidance", de: "Den Auditor um Orientierung bitten", nl: "Vraag de auditor om begeleiding", fr: "Demander conseil à l'auditeur", it: "Chiedere indicazioni all'auditor", es: "Pedir orientación al auditor", pl: "Poprosić audytora o wskazówki" },
        { en: "Treat it as non-delegable and sign it yourself", de: "Als nicht delegierbar behandeln und selbst unterschreiben", nl: "Behandel het als niet-delegeerbaar en onderteken het zelf", fr: "La traiter comme non délégable et la signer vous-même", it: "Trattarla come non delegabile e firmarla voi stessi", es: "Tratarla como no delegable y firmarla usted mismo", pl: "Potraktować ją jako niedelegowalną i podpisać samodzielnie" },
        { en: "Wait until the annual review cycle", de: "Bis zum jährlichen Prüfungszyklus warten", nl: "Wacht tot de jaarlijkse beoordelingscyclus", fr: "Attendre le cycle de révision annuel", it: "Attendere il ciclo di revisione annuale", es: "Esperar al ciclo de revisión anual", pl: "Poczekać do rocznego cyklu przeglądu" },
      ],
      correctIndex: 2,
      explanation: {
        en: "When the line is blurry, treat the decision as non-delegable and sign it yourself.",
        de: "Wenn die Grenze unklar ist, behandeln Sie die Entscheidung als nicht delegierbar und unterschreiben Sie selbst.",
        nl: "Wanneer de grens onduidelijk is, behandel de beslissing als niet-delegeerbaar en onderteken het zelf.",
        fr: "Lorsque la limite est floue, traitez la décision comme non délégable et signez-la vous-même.",
        it: "Quando il confine è sfocato, trattate la decisione come non delegabile e firmatela voi stessi.",
        es: "Cuando el límite es difuso, trate la decisión como no delegable y fírmela usted mismo.",
        pl: "Gdy granica jest niejasna, potraktuj decyzję jako niedelegowalną i podpisz ją samodzielnie.",
      },
    },
  ],
});

export default quiz;
