import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.6",
  passingScore: 75,
  questions: [
    {
      id: "3.6.1",
      question: {
        en: "What does CIR 2024/2690, Annex point 1.2.3 require regarding cybersecurity reporting?",
        de: "Was verlangt CIR 2024/2690, Anhang Punkt 1.2.3 in Bezug auf Cybersicherheitsberichterstattung?",
        nl: "Wat vereist CIR 2024/2690, Bijlage punt 1.2.3 met betrekking tot cyberbeveiligingsrapportage?",
        fr: "Qu'exige le CIR 2024/2690, annexe point 1.2.3 en matière de reporting de cybersécurité ?",
        it: "Cosa richiede il CIR 2024/2690, allegato punto 1.2.3 in materia di reporting sulla cybersicurezza?",
        es: "¿Qué exige el CIR 2024/2690, anexo punto 1.2.3 en materia de reporte de ciberseguridad?",
        pl: "Czego wymaga CIR 2024/2690, załącznik punkt 1.2.3 w zakresie raportowania cyberbezpieczeństwa?",
        cs: "Co vyžaduje CIR 2024/2690, příloha bod 1.2.3, ohledně podávání zpráv o kybernetické bezpečnosti?",
        pt: "O que exige o CIR 2024/2690, Anexo ponto 1.2.3, em matéria de relato de cibersegurança?",
        ro: "Ce impune CIR 2024/2690, Anexa punctul 1.2.3, în privința raportării securității cibernetice?",
      },
      options: [
        { en: "The CISO must report to the IT director quarterly", de: "Der CISO muss vierteljährlich an den IT-Leiter berichten", nl: "De CISO moet elk kwartaal rapporteren aan de IT-directeur", fr: "Le CISO doit rendre compte au directeur informatique chaque trimestre", it: "Il CISO deve riferire al direttore IT ogni trimestre", es: "El CISO debe informar al director de TI trimestralmente", pl: "CISO musi raportować dyrektorowi IT co kwartał", cs: "CISO musí čtvrtletně podávat zprávy řediteli IT", pt: "O CISO tem de reportar trimestralmente ao diretor de TI", ro: "CISO trebuie să raporteze trimestrial directorului IT" },
        { en: "At least one person must report directly to the management body on cybersecurity matters", de: "Mindestens eine Person muss dem Leitungsorgan direkt ueber Cybersicherheitsbelange berichten", nl: "Ten minste één persoon moet rechtstreeks aan het leidinggevend orgaan rapporteren over cyberbeveiligingszaken", fr: "Au moins une personne doit rendre compte directement à l'organe de direction sur les questions de cybersécurité", it: "Almeno una persona deve riferire direttamente all'organo di gestione sulle questioni di cybersicurezza", es: "Al menos una persona debe informar directamente al órgano de dirección sobre asuntos de ciberseguridad", pl: "Co najmniej jedna osoba musi raportować bezpośrednio organowi zarządzającemu w sprawach cyberbezpieczeństwa", cs: "Alespoň jedna osoba musí o záležitostech kybernetické bezpečnosti podávat zprávy přímo řídicímu orgánu", pt: "Pelo menos uma pessoa tem de reportar diretamente ao órgão de administração sobre questões de cibersegurança", ro: "Cel puțin o persoană trebuie să raporteze direct organului de conducere cu privire la chestiunile de securitate cibernetică" },
        { en: "The company must publish an annual cybersecurity report", de: "Das Unternehmen muss einen jährlichen Cybersicherheitsbericht veroeffentlichen", nl: "Het bedrijf moet een jaarlijks cyberbeveiligingsrapport publiceren", fr: "L'entreprise doit publier un rapport annuel de cybersécurité", it: "L'azienda deve pubblicare un rapporto annuale sulla cybersicurezza", es: "La empresa debe publicar un informe anual de ciberseguridad", pl: "Firma musi publikować roczny raport o cyberbezpieczeństwie", cs: "Společnost musí zveřejnit roční zprávu o kybernetické bezpečnosti", pt: "A empresa tem de publicar um relatório anual de cibersegurança", ro: "Compania trebuie să publice un raport anual de securitate cibernetică" },
        { en: "The supervisory board must appoint a dedicated cybersecurity committee", de: "Der Aufsichtsrat muss einen dedizierten Cybersicherheitsausschuss einrichten", nl: "De raad van commissarissen moet een toegewijd cyberbeveiligingscomité instellen", fr: "Le conseil de surveillance doit nommer un comité de cybersécurité dédié", it: "Il consiglio di sorveglianza deve nominare un comitato dedicato alla cybersicurezza", es: "El consejo de supervisión debe nombrar un comité dedicado de ciberseguridad", pl: "Rada nadzorcza musi powołać dedykowany komitet ds. cyberbezpieczeństwa", cs: "Dozorčí rada musí jmenovat vyhrazený výbor pro kybernetickou bezpečnost", pt: "O conselho de supervisão tem de nomear uma comissão de cibersegurança dedicada", ro: "Consiliul de supraveghere trebuie să numească un comitet dedicat de securitate cibernetică" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The regulation requires at least one person to report directly to the management bodies on matters of network and information system security - no layers in between.",
        de: "Die Verordnung verlangt, dass mindestens eine Person dem Leitungsorgan direkt ueber Angelegenheiten der Netz- und Informationssystemsicherheit berichtet - ohne Zwischenebenen.",
        nl: "De verordening vereist dat ten minste één persoon rechtstreeks aan het leidinggevend orgaan rapporteert over netwerk- en informatiesysteembeveiliging - zonder tussenlagen.",
        fr: "Le règlement exige qu'au moins une personne rende compte directement aux organes de direction sur les questions de sécurité des réseaux et des systèmes d'information - sans niveau intermédiaire.",
        it: "Il regolamento richiede che almeno una persona riferisca direttamente agli organi di gestione sulle questioni di sicurezza delle reti e dei sistemi informativi - senza livelli intermedi.",
        es: "El reglamento exige que al menos una persona informe directamente a los órganos de dirección sobre asuntos de seguridad de las redes y sistemas de información, sin niveles intermedios.",
        pl: "Rozporządzenie wymaga, aby co najmniej jedna osoba raportowała bezpośrednio organom zarządzającym w sprawach bezpieczeństwa sieci i systemów informatycznych - bez warstw pośrednich.",
        cs: "Nařízení vyžaduje, aby alespoň jedna osoba podávala zprávy přímo řídicím orgánům v záležitostech bezpečnosti sítí a informačních systémů, bez mezičlánků.",
        pt: "O regulamento exige que pelo menos uma pessoa reporte diretamente aos órgãos de administração sobre questões de segurança das redes e dos sistemas de informação, sem camadas intermédias.",
        ro: "Regulamentul impune ca cel puțin o persoană să raporteze direct organelor de conducere cu privire la chestiunile de securitate a rețelelor și a sistemelor informatice, fără niveluri intermediare.",
      },
    },
    {
      id: "3.6.2",
      question: {
        en: "Why does a CISO reporting through IT lack the authority to enforce security across the company?",
        de: "Warum fehlt einem CISO, der ueber die IT berichtet, die Befugnis, Sicherheit im gesamten Unternehmen durchzusetzen?",
        nl: "Waarom heeft een CISO die via IT rapporteert niet de autoriteit om beveiliging door het hele bedrijf af te dwingen?",
        fr: "Pourquoi un CISO qui rend compte via le service informatique n'a-t-il pas l'autorité pour faire appliquer la sécurité dans toute l'entreprise ?",
        it: "Perché un CISO che riferisce tramite l'IT non ha l'autorità per far rispettare la sicurezza in tutta l'azienda?",
        es: "¿Por qué un CISO que informa a través de TI carece de autoridad para hacer cumplir la seguridad en toda la empresa?",
        pl: "Dlaczego CISO raportujący przez dział IT nie ma uprawnień do egzekwowania bezpieczeństwa w całej firmie?",
        cs: "Proč CISO podávající zprávy přes IT nemá pravomoc prosazovat bezpečnost napříč společností?",
        pt: "Por que razão um CISO que reporta através das TI não tem autoridade para impor a segurança em toda a empresa?",
        ro: "De ce un CISO care raportează prin intermediul IT nu are autoritatea de a impune securitatea în întreaga companie?",
      },
      options: [
        { en: "Because IT departments do not understand business risks", de: "Weil IT-Abteilungen Geschaeftsrisiken nicht verstehen", nl: "Omdat IT-afdelingen bedrijfsrisico's niet begrijpen", fr: "Parce que les services informatiques ne comprennent pas les risques métier", it: "Perché i reparti IT non comprendono i rischi aziendali", es: "Porque los departamentos de TI no comprenden los riesgos de negocio", pl: "Ponieważ działy IT nie rozumieją ryzyk biznesowych", cs: "Protože oddělení IT nerozumějí podnikovým rizikům", pt: "Porque os departamentos de TI não compreendem os riscos de negócio", ro: "Pentru că departamentele IT nu înțeleg riscurile de afaceri" },
        { en: "A CISO under IT has no authority over HR, finance, sales, and operations - their instructions are suggestions from a middle manager", de: "Ein CISO unter der IT hat keine Weisungsbefugnis gegenüber HR, Finanzen, Vertrieb und Betrieb - seine Anweisungen sind Vorschlaege eines mittleren Managers", nl: "Een CISO onder IT heeft geen gezag over HR, financiën, verkoop en operaties - zijn instructies zijn suggesties van een middenkaderlid", fr: "Un CISO sous le service informatique n'a aucune autorité sur les RH, la finance, les ventes et les opérations - ses instructions sont des suggestions d'un cadre intermédiaire", it: "Un CISO sotto l'IT non ha alcuna autorità su HR, finanza, vendite e operazioni - le sue istruzioni sono suggerimenti di un quadro intermedio", es: "Un CISO bajo TI no tiene autoridad sobre RR. HH., finanzas, ventas y operaciones; sus instrucciones son sugerencias de un mando intermedio", pl: "CISO podległy IT nie ma władzy nad HR, finansami, sprzedażą i operacjami - jego polecenia to sugestie menedżera średniego szczebla", cs: "CISO podřízený IT nemá žádnou pravomoc nad personálním oddělením, financemi, obchodem a provozem. Jeho pokyny jsou návrhy středního manažera", pt: "Um CISO sob as TI não tem autoridade sobre os recursos humanos, as finanças, as vendas e as operações. As suas instruções são sugestões de um quadro intermédio", ro: "Un CISO subordonat IT nu are nicio autoritate asupra resurselor umane, finanțelor, vânzărilor și operațiunilor. Instrucțiunile sale sunt sugestii ale unui manager de nivel mediu" },
        { en: "Because IT directors always overrule security recommendations", de: "Weil IT-Leiter Sicherheitsempfehlungen immer überstimmen", nl: "Omdat IT-directeuren altijd beveiligingsaanbevelingen overrulen", fr: "Parce que les directeurs informatiques annulent toujours les recommandations de sécurité", it: "Perché i direttori IT annullano sempre le raccomandazioni di sicurezza", es: "Porque los directores de TI siempre anulan las recomendaciones de seguridad", pl: "Ponieważ dyrektorzy IT zawsze uchylają zalecenia bezpieczeństwa", cs: "Protože ředitelé IT vždy přehlasují bezpečnostní doporučení", pt: "Porque os diretores de TI anulam sempre as recomendações de segurança", ro: "Pentru că directorii IT anulează întotdeauna recomandările de securitate" },
        { en: "Because the law explicitly prohibits CISOs from sitting in IT departments", de: "Weil das Gesetz ausdruecklich verbietet, dass CISOs in IT-Abteilungen angesiedelt sind", nl: "Omdat de wet expliciet verbiedt dat CISO's in IT-afdelingen zijn ondergebracht", fr: "Parce que la loi interdit explicitement aux CISO de siéger dans les services informatiques", it: "Perché la legge vieta esplicitamente ai CISO di far parte dei reparti IT", es: "Porque la ley prohíbe explícitamente que los CISO se ubiquen en los departamentos de TI", pl: "Ponieważ prawo wyraźnie zabrania umieszczania CISO w działach IT", cs: "Protože zákon výslovně zakazuje, aby CISO seděli na odděleních IT", pt: "Porque a lei proíbe expressamente que os CISO estejam nos departamentos de TI", ro: "Pentru că legea interzice în mod expres ca CISO să facă parte din departamentele IT" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A CISO reporting to IT has no authority over the rest of the company. A CISO reporting directly to the CEO inherits the management body's authority, making security decisions executable across departments.",
        de: "Ein CISO, der an die IT berichtet, hat keine Weisungsbefugnis ueber den Rest des Unternehmens. Ein CISO, der direkt an den CEO berichtet, erbt die Autoritaet des Leitungsorgans und kann Sicherheitsentscheidungen abteilungsuebergreifend durchsetzen.",
        nl: "Een CISO die aan IT rapporteert heeft geen gezag over de rest van het bedrijf. Een CISO die rechtstreeks aan de CEO rapporteert erft de autoriteit van het leidinggevend orgaan, waardoor beveiligingsbeslissingen afdelingsoverschrijdend uitvoerbaar worden.",
        fr: "Un CISO qui rend compte au service informatique n'a aucune autorité sur le reste de l'entreprise. Un CISO qui rend compte directement au CEO hérite de l'autorité de l'organe de direction, rendant les décisions de sécurité exécutables dans tous les services.",
        it: "Un CISO che riferisce all'IT non ha alcuna autorità sul resto dell'azienda. Un CISO che riferisce direttamente al CEO eredita l'autorità dell'organo di gestione, rendendo le decisioni di sicurezza eseguibili in tutti i reparti.",
        es: "Un CISO que informa a TI no tiene autoridad sobre el resto de la empresa. Un CISO que informa directamente al CEO hereda la autoridad del órgano de dirección, lo que hace que las decisiones de seguridad sean ejecutables en todos los departamentos.",
        pl: "CISO raportujący do IT nie ma władzy nad resztą firmy. CISO raportujący bezpośrednio do CEO dziedziczy uprawnienia organu zarządzającego, dzięki czemu decyzje bezpieczeństwa są wykonalne we wszystkich działach.",
        cs: "CISO podávající zprávy IT nemá žádnou pravomoc nad zbytkem společnosti. CISO podávající zprávy přímo generálnímu řediteli přebírá pravomoc řídicího orgánu, čímž jsou bezpečnostní rozhodnutí vykonatelná napříč odděleními.",
        pt: "Um CISO que reporta às TI não tem autoridade sobre o resto da empresa. Um CISO que reporta diretamente ao diretor executivo herda a autoridade do órgão de administração, tornando as decisões de segurança executáveis em todos os departamentos.",
        ro: "Un CISO care raportează către IT nu are autoritate asupra restului companiei. Un CISO care raportează direct directorului general moștenește autoritatea organului de conducere, ceea ce face ca deciziile de securitate să fie executabile în toate departamentele.",
      },
    },
    {
      id: "3.6.3",
      question: {
        en: "If the CISO reports through IT or finance, what does the auditor conclude?",
        de: "Was stellt der Auditor fest, wenn der CISO ueber die IT oder Finanzabteilung berichtet?",
        nl: "Als de CISO via IT of financiën rapporteert, wat concludeert de auditor dan?",
        fr: "Si le CISO rend compte via le service informatique ou financier, que conclut l'auditeur ?",
        it: "Se il CISO riferisce tramite l'IT o la finanza, cosa conclude l'auditor?",
        es: "Si el CISO informa a través de TI o finanzas, ¿qué concluye el auditor?",
        pl: "Jeśli CISO raportuje przez IT lub finanse, co stwierdza audytor?",
        cs: "Pokud CISO podává zprávy přes IT nebo finance, k jakému závěru auditor dospěje?",
        pt: "Se o CISO reportar através das TI ou das finanças, o que conclui o auditor?",
        ro: "Dacă CISO raportează prin intermediul IT sau al finanțelor, ce concluzionează auditorul?",
      },
      options: [
        { en: "The requirement is met if the CISO informally briefs the CEO regularly", de: "Die Anforderung ist erfuellt, wenn der CISO den CEO regelmaessig informell informiert", nl: "De vereiste is vervuld als de CISO de CEO regelmatig informeel brieft", fr: "L'exigence est satisfaite si le CISO informe régulièrement le CEO de manière informelle", it: "Il requisito è soddisfatto se il CISO informa regolarmente il CEO in modo informale", es: "El requisito se cumple si el CISO informa al CEO de forma informal con regularidad", pl: "Wymóg jest spełniony, jeśli CISO regularnie nieformalnie informuje CEO", cs: "Požadavek je splněn, pokud CISO pravidelně neformálně informuje generálního ředitele", pt: "O requisito está cumprido se o CISO informar regularmente o diretor executivo de modo informal", ro: "Cerința este îndeplinită dacă CISO îl informează periodic în mod neoficial pe directorul general" },
        { en: "The requirement is not met - regardless of the CISO's competence or how often they brief the CEO", de: "Die Anforderung ist nicht erfuellt - unabhaengig von der Kompetenz des CISO oder wie oft er den CEO informiert", nl: "De vereiste is niet vervuld - ongeacht de competentie van de CISO of hoe vaak hij de CEO brieft", fr: "L'exigence n'est pas satisfaite - quelles que soient la compétence du CISO ou la fréquence à laquelle il informe le CEO", it: "Il requisito non è soddisfatto - indipendentemente dalla competenza del CISO o dalla frequenza con cui informa il CEO", es: "El requisito no se cumple, independientemente de la competencia del CISO o de la frecuencia con que informe al CEO", pl: "Wymóg nie jest spełniony - niezależnie od kompetencji CISO ani częstotliwości informowania CEO", cs: "Požadavek není splněn, bez ohledu na kompetence CISO nebo na to, jak často generálního ředitele informuje", pt: "O requisito não está cumprido, independentemente da competência do CISO ou da frequência com que informa o diretor executivo", ro: "Cerința nu este îndeplinită, indiferent de competența CISO sau de cât de des îl informează pe directorul general" },
        { en: "The requirement is partially met and needs an observation note", de: "Die Anforderung ist teilweise erfuellt und erfordert eine Beobachtungsnotiz", nl: "De vereiste is gedeeltelijk vervuld en vereist een observatieopmerking", fr: "L'exigence est partiellement satisfaite et nécessite une note d'observation", it: "Il requisito è parzialmente soddisfatto e richiede una nota di osservazione", es: "El requisito se cumple parcialmente y necesita una nota de observación", pl: "Wymóg jest częściowo spełniony i wymaga notatki obserwacyjnej", cs: "Požadavek je splněn částečně a vyžaduje poznámku v podobě pozorování", pt: "O requisito está parcialmente cumprido e necessita de uma nota de observação", ro: "Cerința este parțial îndeplinită și necesită o notă de observație" },
        { en: "The requirement is waived for companies under 250 employees", de: "Die Anforderung entfällt für Unternehmen unter 250 Mitarbeitern", nl: "De vereiste vervalt voor bedrijven met minder dan 250 werknemers", fr: "L'exigence est levée pour les entreprises de moins de 250 employés", it: "Il requisito decade per le aziende con meno di 250 dipendenti", es: "El requisito se exime para las empresas de menos de 250 empleados", pl: "Wymóg nie obowiązuje firm zatrudniających poniżej 250 pracowników", cs: "Požadavek se promíjí společnostem s méně než 250 zaměstnanci", pt: "O requisito é dispensado para empresas com menos de 250 trabalhadores", ro: "Cerința este eliminată pentru companiile cu sub 250 de angajați" },
      ],
      correctIndex: 1,
      explanation: {
        en: "If the CISO reports through IT or finance, the requirement is not met - regardless of how competent the CISO is or how often they informally brief you.",
        de: "Wenn der CISO ueber die IT oder Finanzabteilung berichtet, ist die Anforderung nicht erfuellt - unabhaengig davon, wie kompetent der CISO ist oder wie oft er Sie informell informiert.",
        nl: "Als de CISO via IT of financiën rapporteert, is de vereiste niet vervuld - ongeacht hoe competent de CISO is of hoe vaak hij u informeel brieft.",
        fr: "Si le CISO rend compte via le service informatique ou financier, l'exigence n'est pas satisfaite - quelles que soient la compétence du CISO ou la fréquence à laquelle il vous informe de manière informelle.",
        it: "Se il CISO riferisce tramite l'IT o la finanza, il requisito non è soddisfatto - indipendentemente da quanto sia competente il CISO o da quanto spesso vi informi in modo informale.",
        es: "Si el CISO informa a través de TI o finanzas, el requisito no se cumple, independientemente de lo competente que sea el CISO o de la frecuencia con que le informe de forma informal.",
        pl: "Jeśli CISO raportuje przez IT lub finanse, wymóg nie jest spełniony - niezależnie od tego, jak kompetentny jest CISO ani jak często nieformalnie Cię informuje.",
        cs: "Pokud CISO podává zprávy přes IT nebo finance, požadavek není splněn, bez ohledu na to, jak je CISO kompetentní nebo jak často vás neformálně informuje.",
        pt: "Se o CISO reportar através das TI ou das finanças, o requisito não está cumprido, independentemente de quão competente é o CISO ou da frequência com que o informa de modo informal.",
        ro: "Dacă CISO raportează prin intermediul IT sau al finanțelor, cerința nu este îndeplinită, indiferent de cât de competent este CISO sau de cât de des vă informează în mod neoficial.",
      },
    },
    {
      id: "3.6.4",
      question: {
        en: "What practical step does the lesson recommend to meet the reporting requirement?",
        de: "Welchen praktischen Schritt empfiehlt die Lektion, um die Berichtspflicht zu erfuellen?",
        nl: "Welke praktische stap beveelt de les aan om aan de rapportagevereiste te voldoen?",
        fr: "Quelle mesure pratique la leçon recommande-t-elle pour satisfaire à l'exigence de reporting ?",
        it: "Quale passo pratico raccomanda la lezione per soddisfare il requisito di reporting?",
        es: "¿Qué paso práctico recomienda la lección para cumplir el requisito de reporte?",
        pl: "Jaki praktyczny krok zaleca lekcja, aby spełnić wymóg raportowania?",
        cs: "Jaký praktický krok lekce doporučuje ke splnění požadavku na podávání zpráv?",
        pt: "Que medida prática recomenda a lição para cumprir o requisito de relato?",
        ro: "Ce măsură practică recomandă lecția pentru a îndeplini cerința de raportare?",
      },
      options: [
        { en: "Hire a second CISO who reports directly to the board", de: "Einen zweiten CISO einstellen, der direkt an den Vorstand berichtet", nl: "Een tweede CISO aannemen die rechtstreeks aan het bestuur rapporteert", fr: "Embaucher un second CISO qui rend compte directement au conseil", it: "Assumere un secondo CISO che riferisca direttamente al consiglio", es: "Contratar a un segundo CISO que informe directamente al consejo", pl: "Zatrudnić drugiego CISO raportującego bezpośrednio zarządowi", cs: "Najmout druhého CISO, který podává zprávy přímo orgánu", pt: "Contratar um segundo CISO que reporte diretamente ao órgão de administração", ro: "Angajarea unui al doilea CISO care raportează direct organului de conducere" },
        { en: "Change the line on the org chart and schedule recurring monthly meetings with a standing written agenda", de: "Die Berichtslinie im Organigramm ändern und wiederkehrende monatliche Termine mit einer festen schriftlichen Tagesordnung einplanen", nl: "De lijn op het organogram wijzigen en terugkerende maandelijkse vergaderingen inplannen met een vaste schriftelijke agenda", fr: "Modifier la ligne sur l'organigramme et planifier des réunions mensuelles récurrentes avec un ordre du jour écrit permanent", it: "Modificare la linea nell'organigramma e programmare riunioni mensili ricorrenti con un ordine del giorno scritto permanente", es: "Cambiar la línea en el organigrama y programar reuniones mensuales recurrentes con un orden del día escrito permanente", pl: "Zmienić linię na schemacie organizacyjnym i zaplanować cykliczne comiesięczne spotkania ze stałym pisemnym porządkiem obrad", cs: "Změnit linii v organizačním schématu a naplánovat pravidelné měsíční schůzky se stálým písemným programem", pt: "Alterar a linha no organigrama e agendar reuniões mensais recorrentes com uma agenda escrita permanente", ro: "Modificarea liniei din organigramă și programarea unor ședințe lunare recurente cu o ordine de zi scrisă permanentă" },
        { en: "Create a cybersecurity committee on the supervisory board", de: "Einen Cybersicherheitsausschuss im Aufsichtsrat einrichten", nl: "Een cyberbeveiligingscomité instellen bij de raad van commissarissen", fr: "Créer un comité de cybersécurité au sein du conseil de surveillance", it: "Creare un comitato per la cybersicurezza nel consiglio di sorveglianza", es: "Crear un comité de ciberseguridad en el consejo de supervisión", pl: "Utworzyć komitet ds. cyberbezpieczeństwa przy radzie nadzorczej", cs: "Vytvořit výbor pro kybernetickou bezpečnost v dozorčí radě", pt: "Criar uma comissão de cibersegurança no conselho de supervisão", ro: "Crearea unui comitet de securitate cibernetică în cadrul consiliului de supraveghere" },
        { en: "Outsource cybersecurity reporting to an external consultant", de: "Die Cybersicherheitsberichterstattung an einen externen Berater auslagern", nl: "Cyberbeveiligingsrapportage uitbesteden aan een externe adviseur", fr: "Externaliser le reporting de cybersécurité à un consultant externe", it: "Esternalizzare il reporting sulla cybersicurezza a un consulente esterno", es: "Externalizar el reporte de ciberseguridad a un consultor externo", pl: "Zlecić raportowanie cyberbezpieczeństwa zewnętrznemu konsultantowi", cs: "Zadat podávání zpráv o kybernetické bezpečnosti externímu konzultantovi", pt: "Externalizar o relato de cibersegurança a um consultor externo", ro: "Externalizarea raportării securității cibernetice către un consultant extern" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The budget and headcount do not have to change, only the line on the chart. Then schedule a recurring monthly meeting with a standing written agenda.",
        de: "Budget und Personalstaerke müssen sich nicht ändern, nur die Linie im Organigramm. Planen Sie dann ein wiederkehrendes monatliches Treffen mit einer festen schriftlichen Tagesordnung ein.",
        nl: "Het budget en de personeelssterkte hoeven niet te veranderen, alleen de lijn op het organogram. Plan vervolgens een terugkerende maandelijkse vergadering in met een vaste schriftelijke agenda.",
        fr: "Le budget et l'effectif n'ont pas à changer, seulement la ligne sur l'organigramme. Planifiez ensuite une réunion mensuelle récurrente avec un ordre du jour écrit permanent.",
        it: "Il budget e l'organico non devono cambiare, solo la linea nell'organigramma. Programmate poi una riunione mensile ricorrente con un ordine del giorno scritto permanente.",
        es: "El presupuesto y la plantilla no tienen que cambiar, solo la línea en el organigrama. Después, programe una reunión mensual recurrente con un orden del día escrito permanente.",
        pl: "Budżet i liczba pracowników nie muszą się zmieniać, tylko linia na schemacie organizacyjnym. Następnie zaplanuj cykliczne comiesięczne spotkanie ze stałym pisemnym porządkiem obrad.",
        cs: "Rozpočet ani počet zaměstnanců se měnit nemusí, pouze linie ve schématu. Poté naplánujte pravidelnou měsíční schůzku se stálým písemným programem.",
        pt: "O orçamento e o número de trabalhadores não têm de mudar, apenas a linha no organigrama. Depois, agende uma reunião mensal recorrente com uma agenda escrita permanente.",
        ro: "Bugetul și numărul de angajați nu trebuie să se modifice, ci doar linia din organigramă. Apoi programați o ședință lunară recurentă cu o ordine de zi scrisă permanentă.",
      },
    },
  ],
});

export default quiz;
