import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.6",
  passingScore: 75,
  questions: [
    {
      id: "3.6.1",
      question: {
        en: "What does CIR 2024/2690, Annex point 1.2.3 require regarding cybersecurity reporting?",
        de: "Was verlangt CIR 2024/2690, Anhang Punkt 1.2.3 in Bezug auf Cybersicherheitsberichterstattung?",
        nl: "Wat vereist CIR 2024/2690, Bijlage punt 1.2.3 met betrekking tot cyberbeveiligingsrapportage?",
        fr: "Qu'exige le CIR 2024/2690, annexe point 1.2.3 en matière de reporting de cybersécurité ?",
        it: "Cosa richiede il CIR 2024/2690, allegato punto 1.2.3 in materia di reporting sulla cybersicurezza?",
        es: "¿Qué exige el CIR 2024/2690, anexo punto 1.2.3 en materia de reporte de ciberseguridad?",
        pl: "Czego wymaga CIR 2024/2690, załącznik punkt 1.2.3 w zakresie raportowania cyberbezpieczeństwa?",
      },
      options: [
        { en: "The CISO must report to the IT director quarterly", de: "Der CISO muss vierteljährlich an den IT-Leiter berichten", nl: "De CISO moet elk kwartaal rapporteren aan de IT-directeur", fr: "Le CISO doit rendre compte au directeur informatique chaque trimestre", it: "Il CISO deve riferire al direttore IT ogni trimestre", es: "El CISO debe informar al director de TI trimestralmente", pl: "CISO musi raportować dyrektorowi IT co kwartał" },
        { en: "At least one person must report directly to the management body on cybersecurity matters", de: "Mindestens eine Person muss dem Leitungsorgan direkt ueber Cybersicherheitsbelange berichten", nl: "Ten minste één persoon moet rechtstreeks aan het leidinggevend orgaan rapporteren over cyberbeveiligingszaken", fr: "Au moins une personne doit rendre compte directement à l'organe de direction sur les questions de cybersécurité", it: "Almeno una persona deve riferire direttamente all'organo di gestione sulle questioni di cybersicurezza", es: "Al menos una persona debe informar directamente al órgano de dirección sobre asuntos de ciberseguridad", pl: "Co najmniej jedna osoba musi raportować bezpośrednio organowi zarządzającemu w sprawach cyberbezpieczeństwa" },
        { en: "The company must publish an annual cybersecurity report", de: "Das Unternehmen muss einen jährlichen Cybersicherheitsbericht veroeffentlichen", nl: "Het bedrijf moet een jaarlijks cyberbeveiligingsrapport publiceren", fr: "L'entreprise doit publier un rapport annuel de cybersécurité", it: "L'azienda deve pubblicare un rapporto annuale sulla cybersicurezza", es: "La empresa debe publicar un informe anual de ciberseguridad", pl: "Firma musi publikować roczny raport o cyberbezpieczeństwie" },
        { en: "The supervisory board must appoint a dedicated cybersecurity committee", de: "Der Aufsichtsrat muss einen dedizierten Cybersicherheitsausschuss einrichten", nl: "De raad van commissarissen moet een toegewijd cyberbeveiligingscomité instellen", fr: "Le conseil de surveillance doit nommer un comité de cybersécurité dédié", it: "Il consiglio di sorveglianza deve nominare un comitato dedicato alla cybersicurezza", es: "El consejo de supervisión debe nombrar un comité dedicado de ciberseguridad", pl: "Rada nadzorcza musi powołać dedykowany komitet ds. cyberbezpieczeństwa" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The regulation requires at least one person to report directly to the management bodies on matters of network and information system security - no layers in between.",
        de: "Die Verordnung verlangt, dass mindestens eine Person dem Leitungsorgan direkt ueber Angelegenheiten der Netz- und Informationssystemsicherheit berichtet - ohne Zwischenebenen.",
        nl: "De verordening vereist dat ten minste één persoon rechtstreeks aan het leidinggevend orgaan rapporteert over netwerk- en informatiesysteembeveiliging - zonder tussenlagen.",
        fr: "Le règlement exige qu'au moins une personne rende compte directement aux organes de direction sur les questions de sécurité des réseaux et des systèmes d'information - sans niveau intermédiaire.",
        it: "Il regolamento richiede che almeno una persona riferisca direttamente agli organi di gestione sulle questioni di sicurezza delle reti e dei sistemi informativi - senza livelli intermedi.",
        es: "El reglamento exige que al menos una persona informe directamente a los órganos de dirección sobre asuntos de seguridad de las redes y sistemas de información, sin niveles intermedios.",
        pl: "Rozporządzenie wymaga, aby co najmniej jedna osoba raportowała bezpośrednio organom zarządzającym w sprawach bezpieczeństwa sieci i systemów informatycznych - bez warstw pośrednich.",
      },
    },
    {
      id: "3.6.2",
      question: {
        en: "Why does a CISO reporting through IT lack the authority to enforce security across the company?",
        de: "Warum fehlt einem CISO, der ueber die IT berichtet, die Befugnis, Sicherheit im gesamten Unternehmen durchzusetzen?",
        nl: "Waarom heeft een CISO die via IT rapporteert niet de autoriteit om beveiliging door het hele bedrijf af te dwingen?",
        fr: "Pourquoi un CISO qui rend compte via le service informatique n'a-t-il pas l'autorité pour faire appliquer la sécurité dans toute l'entreprise ?",
        it: "Perché un CISO che riferisce tramite l'IT non ha l'autorità per far rispettare la sicurezza in tutta l'azienda?",
        es: "¿Por qué un CISO que informa a través de TI carece de autoridad para hacer cumplir la seguridad en toda la empresa?",
        pl: "Dlaczego CISO raportujący przez dział IT nie ma uprawnień do egzekwowania bezpieczeństwa w całej firmie?",
      },
      options: [
        { en: "Because IT departments do not understand business risks", de: "Weil IT-Abteilungen Geschaeftsrisiken nicht verstehen", nl: "Omdat IT-afdelingen bedrijfsrisico's niet begrijpen", fr: "Parce que les services informatiques ne comprennent pas les risques métier", it: "Perché i reparti IT non comprendono i rischi aziendali", es: "Porque los departamentos de TI no comprenden los riesgos de negocio", pl: "Ponieważ działy IT nie rozumieją ryzyk biznesowych" },
        { en: "A CISO under IT has no authority over HR, finance, sales, and operations - their instructions are suggestions from a middle manager", de: "Ein CISO unter der IT hat keine Weisungsbefugnis gegenüber HR, Finanzen, Vertrieb und Betrieb - seine Anweisungen sind Vorschlaege eines mittleren Managers", nl: "Een CISO onder IT heeft geen gezag over HR, financiën, verkoop en operaties - zijn instructies zijn suggesties van een middenkaderlid", fr: "Un CISO sous le service informatique n'a aucune autorité sur les RH, la finance, les ventes et les opérations - ses instructions sont des suggestions d'un cadre intermédiaire", it: "Un CISO sotto l'IT non ha alcuna autorità su HR, finanza, vendite e operazioni - le sue istruzioni sono suggerimenti di un quadro intermedio", es: "Un CISO bajo TI no tiene autoridad sobre RR. HH., finanzas, ventas y operaciones; sus instrucciones son sugerencias de un mando intermedio", pl: "CISO podległy IT nie ma władzy nad HR, finansami, sprzedażą i operacjami - jego polecenia to sugestie menedżera średniego szczebla" },
        { en: "Because IT directors always overrule security recommendations", de: "Weil IT-Leiter Sicherheitsempfehlungen immer überstimmen", nl: "Omdat IT-directeuren altijd beveiligingsaanbevelingen overrulen", fr: "Parce que les directeurs informatiques annulent toujours les recommandations de sécurité", it: "Perché i direttori IT annullano sempre le raccomandazioni di sicurezza", es: "Porque los directores de TI siempre anulan las recomendaciones de seguridad", pl: "Ponieważ dyrektorzy IT zawsze uchylają zalecenia bezpieczeństwa" },
        { en: "Because the law explicitly prohibits CISOs from sitting in IT departments", de: "Weil das Gesetz ausdruecklich verbietet, dass CISOs in IT-Abteilungen angesiedelt sind", nl: "Omdat de wet expliciet verbiedt dat CISO's in IT-afdelingen zijn ondergebracht", fr: "Parce que la loi interdit explicitement aux CISO de siéger dans les services informatiques", it: "Perché la legge vieta esplicitamente ai CISO di far parte dei reparti IT", es: "Porque la ley prohíbe explícitamente que los CISO se ubiquen en los departamentos de TI", pl: "Ponieważ prawo wyraźnie zabrania umieszczania CISO w działach IT" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A CISO reporting to IT has no authority over the rest of the company. A CISO reporting directly to the CEO inherits the management body's authority, making security decisions executable across departments.",
        de: "Ein CISO, der an die IT berichtet, hat keine Weisungsbefugnis ueber den Rest des Unternehmens. Ein CISO, der direkt an den CEO berichtet, erbt die Autoritaet des Leitungsorgans und kann Sicherheitsentscheidungen abteilungsuebergreifend durchsetzen.",
        nl: "Een CISO die aan IT rapporteert heeft geen gezag over de rest van het bedrijf. Een CISO die rechtstreeks aan de CEO rapporteert erft de autoriteit van het leidinggevend orgaan, waardoor beveiligingsbeslissingen afdelingsoverschrijdend uitvoerbaar worden.",
        fr: "Un CISO qui rend compte au service informatique n'a aucune autorité sur le reste de l'entreprise. Un CISO qui rend compte directement au CEO hérite de l'autorité de l'organe de direction, rendant les décisions de sécurité exécutables dans tous les services.",
        it: "Un CISO che riferisce all'IT non ha alcuna autorità sul resto dell'azienda. Un CISO che riferisce direttamente al CEO eredita l'autorità dell'organo di gestione, rendendo le decisioni di sicurezza eseguibili in tutti i reparti.",
        es: "Un CISO que informa a TI no tiene autoridad sobre el resto de la empresa. Un CISO que informa directamente al CEO hereda la autoridad del órgano de dirección, lo que hace que las decisiones de seguridad sean ejecutables en todos los departamentos.",
        pl: "CISO raportujący do IT nie ma władzy nad resztą firmy. CISO raportujący bezpośrednio do CEO dziedziczy uprawnienia organu zarządzającego, dzięki czemu decyzje bezpieczeństwa są wykonalne we wszystkich działach.",
      },
    },
    {
      id: "3.6.3",
      question: {
        en: "If the CISO reports through IT or finance, what does the auditor conclude?",
        de: "Was stellt der Auditor fest, wenn der CISO ueber die IT oder Finanzabteilung berichtet?",
        nl: "Als de CISO via IT of financiën rapporteert, wat concludeert de auditor dan?",
        fr: "Si le CISO rend compte via le service informatique ou financier, que conclut l'auditeur ?",
        it: "Se il CISO riferisce tramite l'IT o la finanza, cosa conclude l'auditor?",
        es: "Si el CISO informa a través de TI o finanzas, ¿qué concluye el auditor?",
        pl: "Jeśli CISO raportuje przez IT lub finanse, co stwierdza audytor?",
      },
      options: [
        { en: "The requirement is met if the CISO informally briefs the CEO regularly", de: "Die Anforderung ist erfuellt, wenn der CISO den CEO regelmaessig informell informiert", nl: "De vereiste is vervuld als de CISO de CEO regelmatig informeel brieft", fr: "L'exigence est satisfaite si le CISO informe régulièrement le CEO de manière informelle", it: "Il requisito è soddisfatto se il CISO informa regolarmente il CEO in modo informale", es: "El requisito se cumple si el CISO informa al CEO de forma informal con regularidad", pl: "Wymóg jest spełniony, jeśli CISO regularnie nieformalnie informuje CEO" },
        { en: "The requirement is not met - regardless of the CISO's competence or how often they brief the CEO", de: "Die Anforderung ist nicht erfuellt - unabhaengig von der Kompetenz des CISO oder wie oft er den CEO informiert", nl: "De vereiste is niet vervuld - ongeacht de competentie van de CISO of hoe vaak hij de CEO brieft", fr: "L'exigence n'est pas satisfaite - quelles que soient la compétence du CISO ou la fréquence à laquelle il informe le CEO", it: "Il requisito non è soddisfatto - indipendentemente dalla competenza del CISO o dalla frequenza con cui informa il CEO", es: "El requisito no se cumple, independientemente de la competencia del CISO o de la frecuencia con que informe al CEO", pl: "Wymóg nie jest spełniony - niezależnie od kompetencji CISO ani częstotliwości informowania CEO" },
        { en: "The requirement is partially met and needs an observation note", de: "Die Anforderung ist teilweise erfuellt und erfordert eine Beobachtungsnotiz", nl: "De vereiste is gedeeltelijk vervuld en vereist een observatieopmerking", fr: "L'exigence est partiellement satisfaite et nécessite une note d'observation", it: "Il requisito è parzialmente soddisfatto e richiede una nota di osservazione", es: "El requisito se cumple parcialmente y necesita una nota de observación", pl: "Wymóg jest częściowo spełniony i wymaga notatki obserwacyjnej" },
        { en: "The requirement is waived for companies under 250 employees", de: "Die Anforderung entfällt für Unternehmen unter 250 Mitarbeitern", nl: "De vereiste vervalt voor bedrijven met minder dan 250 werknemers", fr: "L'exigence est levée pour les entreprises de moins de 250 employés", it: "Il requisito decade per le aziende con meno di 250 dipendenti", es: "El requisito se exime para las empresas de menos de 250 empleados", pl: "Wymóg nie obowiązuje firm zatrudniających poniżej 250 pracowników" },
      ],
      correctIndex: 1,
      explanation: {
        en: "If the CISO reports through IT or finance, the requirement is not met - regardless of how competent the CISO is or how often they informally brief you.",
        de: "Wenn der CISO ueber die IT oder Finanzabteilung berichtet, ist die Anforderung nicht erfuellt - unabhaengig davon, wie kompetent der CISO ist oder wie oft er Sie informell informiert.",
        nl: "Als de CISO via IT of financiën rapporteert, is de vereiste niet vervuld - ongeacht hoe competent de CISO is of hoe vaak hij u informeel brieft.",
        fr: "Si le CISO rend compte via le service informatique ou financier, l'exigence n'est pas satisfaite - quelles que soient la compétence du CISO ou la fréquence à laquelle il vous informe de manière informelle.",
        it: "Se il CISO riferisce tramite l'IT o la finanza, il requisito non è soddisfatto - indipendentemente da quanto sia competente il CISO o da quanto spesso vi informi in modo informale.",
        es: "Si el CISO informa a través de TI o finanzas, el requisito no se cumple, independientemente de lo competente que sea el CISO o de la frecuencia con que le informe de forma informal.",
        pl: "Jeśli CISO raportuje przez IT lub finanse, wymóg nie jest spełniony - niezależnie od tego, jak kompetentny jest CISO ani jak często nieformalnie Cię informuje.",
      },
    },
    {
      id: "3.6.4",
      question: {
        en: "What practical step does the lesson recommend to meet the reporting requirement?",
        de: "Welchen praktischen Schritt empfiehlt die Lektion, um die Berichtspflicht zu erfuellen?",
        nl: "Welke praktische stap beveelt de les aan om aan de rapportagevereiste te voldoen?",
        fr: "Quelle mesure pratique la leçon recommande-t-elle pour satisfaire à l'exigence de reporting ?",
        it: "Quale passo pratico raccomanda la lezione per soddisfare il requisito di reporting?",
        es: "¿Qué paso práctico recomienda la lección para cumplir el requisito de reporte?",
        pl: "Jaki praktyczny krok zaleca lekcja, aby spełnić wymóg raportowania?",
      },
      options: [
        { en: "Hire a second CISO who reports directly to the board", de: "Einen zweiten CISO einstellen, der direkt an den Vorstand berichtet", nl: "Een tweede CISO aannemen die rechtstreeks aan het bestuur rapporteert", fr: "Embaucher un second CISO qui rend compte directement au conseil", it: "Assumere un secondo CISO che riferisca direttamente al consiglio", es: "Contratar a un segundo CISO que informe directamente al consejo", pl: "Zatrudnić drugiego CISO raportującego bezpośrednio zarządowi" },
        { en: "Change the line on the org chart and schedule recurring monthly meetings with a standing written agenda", de: "Die Berichtslinie im Organigramm ändern und wiederkehrende monatliche Termine mit einer festen schriftlichen Tagesordnung einplanen", nl: "De lijn op het organogram wijzigen en terugkerende maandelijkse vergaderingen inplannen met een vaste schriftelijke agenda", fr: "Modifier la ligne sur l'organigramme et planifier des réunions mensuelles récurrentes avec un ordre du jour écrit permanent", it: "Modificare la linea nell'organigramma e programmare riunioni mensili ricorrenti con un ordine del giorno scritto permanente", es: "Cambiar la línea en el organigrama y programar reuniones mensuales recurrentes con un orden del día escrito permanente", pl: "Zmienić linię na schemacie organizacyjnym i zaplanować cykliczne comiesięczne spotkania ze stałym pisemnym porządkiem obrad" },
        { en: "Create a cybersecurity committee on the supervisory board", de: "Einen Cybersicherheitsausschuss im Aufsichtsrat einrichten", nl: "Een cyberbeveiligingscomité instellen bij de raad van commissarissen", fr: "Créer un comité de cybersécurité au sein du conseil de surveillance", it: "Creare un comitato per la cybersicurezza nel consiglio di sorveglianza", es: "Crear un comité de ciberseguridad en el consejo de supervisión", pl: "Utworzyć komitet ds. cyberbezpieczeństwa przy radzie nadzorczej" },
        { en: "Outsource cybersecurity reporting to an external consultant", de: "Die Cybersicherheitsberichterstattung an einen externen Berater auslagern", nl: "Cyberbeveiligingsrapportage uitbesteden aan een externe adviseur", fr: "Externaliser le reporting de cybersécurité à un consultant externe", it: "Esternalizzare il reporting sulla cybersicurezza a un consulente esterno", es: "Externalizar el reporte de ciberseguridad a un consultor externo", pl: "Zlecić raportowanie cyberbezpieczeństwa zewnętrznemu konsultantowi" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The budget and headcount do not have to change, only the line on the chart. Then schedule a recurring monthly meeting with a standing written agenda.",
        de: "Budget und Personalstaerke müssen sich nicht ändern, nur die Linie im Organigramm. Planen Sie dann ein wiederkehrendes monatliches Treffen mit einer festen schriftlichen Tagesordnung ein.",
        nl: "Het budget en de personeelssterkte hoeven niet te veranderen, alleen de lijn op het organogram. Plan vervolgens een terugkerende maandelijkse vergadering in met een vaste schriftelijke agenda.",
        fr: "Le budget et l'effectif n'ont pas à changer, seulement la ligne sur l'organigramme. Planifiez ensuite une réunion mensuelle récurrente avec un ordre du jour écrit permanent.",
        it: "Il budget e l'organico non devono cambiare, solo la linea nell'organigramma. Programmate poi una riunione mensile ricorrente con un ordine del giorno scritto permanente.",
        es: "El presupuesto y la plantilla no tienen que cambiar, solo la línea en el organigrama. Después, programe una reunión mensual recurrente con un orden del día escrito permanente.",
        pl: "Budżet i liczba pracowników nie muszą się zmieniać, tylko linia na schemacie organizacyjnym. Następnie zaplanuj cykliczne comiesięczne spotkanie ze stałym pisemnym porządkiem obrad.",
      },
    },
  ],
});

export default quiz;
