import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.7",
  passingScore: 75,
  questions: [
    {
      id: "3.7.1",
      question: {
        en: "What is the difference between how Essential and Important entities are audited under NIS2?",
        de: "Worin unterscheidet sich die Auditierung von wesentlichen und wichtigen Einrichtungen unter NIS2?",
        nl: "Wat is het verschil in de manier waarop essentiële en belangrijke entiteiten worden geauditeerd onder NIS2?",
        fr: "Quelle est la différence entre la manière dont les entités essentielles et importantes sont auditées au titre de NIS2 ?",
        it: "Qual è la differenza nel modo in cui i soggetti essenziali e importanti vengono sottoposti ad audit nell'ambito di NIS2?",
        es: "¿Cuál es la diferencia entre cómo se auditan las entidades esenciales e importantes en el marco de NIS2?",
        pl: "Jaka jest różnica w sposobie audytowania podmiotów kluczowych i ważnych w ramach NIS2?",
      },
      options: [
        { en: "Essential entities are never audited; Important entities are audited annually", de: "Wesentliche Einrichtungen werden nie geprüft; wichtige Einrichtungen werden jährlich geprüft", nl: "Essentiële entiteiten worden nooit geauditeerd; belangrijke entiteiten worden jaarlijks geauditeerd", fr: "Les entités essentielles ne sont jamais auditées ; les entités importantes sont auditées chaque année", it: "I soggetti essenziali non vengono mai sottoposti ad audit; i soggetti importanti vengono sottoposti ad audit annualmente", es: "Las entidades esenciales nunca se auditan; las entidades importantes se auditan anualmente", pl: "Podmioty kluczowe nigdy nie są audytowane; podmioty ważne są audytowane corocznie" },
        { en: "Essential entities can be audited proactively at any time; Important entities are audited reactively when triggered", de: "Wesentliche Einrichtungen können jederzeit proaktiv geprüft werden; wichtige Einrichtungen werden reaktiv bei Auslösern geprüft", nl: "Essentiële entiteiten kunnen proactief op elk moment worden geauditeerd; belangrijke entiteiten worden reactief geauditeerd wanneer daartoe aanleiding is", fr: "Les entités essentielles peuvent être auditées de manière proactive à tout moment ; les entités importantes sont auditées de manière réactive lorsqu'un élément déclencheur survient", it: "I soggetti essenziali possono essere sottoposti ad audit in modo proattivo in qualsiasi momento; i soggetti importanti vengono sottoposti ad audit in modo reattivo al verificarsi di un evento scatenante", es: "Las entidades esenciales pueden auditarse de forma proactiva en cualquier momento; las entidades importantes se auditan de forma reactiva cuando se produce un desencadenante", pl: "Podmioty kluczowe mogą być audytowane proaktywnie w dowolnym momencie; podmioty ważne są audytowane reaktywnie po wystąpieniu czynnika wyzwalającego" },
        { en: "Both are audited on the same annual schedule", de: "Beide werden nach dem gleichen jährlichen Zeitplan geprüft", nl: "Beide worden geauditeerd volgens hetzelfde jaarlijkse schema", fr: "Les deux sont audités selon le même calendrier annuel", it: "Entrambi vengono sottoposti ad audit secondo lo stesso calendario annuale", es: "Ambas se auditan según el mismo calendario anual", pl: "Oba są audytowane według tego samego rocznego harmonogramu" },
        { en: "Essential entities are audited by the BSI; Important entities are audited by private firms", de: "Wesentliche Einrichtungen werden vom BSI geprüft; wichtige Einrichtungen von privaten Firmen", nl: "Essentiële entiteiten worden geauditeerd door de BSI; belangrijke entiteiten door private bedrijven", fr: "Les entités essentielles sont auditées par le BSI ; les entités importantes sont auditées par des cabinets privés", it: "I soggetti essenziali vengono sottoposti ad audit dal BSI; i soggetti importanti da società private", es: "Las entidades esenciales son auditadas por el BSI; las entidades importantes por empresas privadas", pl: "Podmioty kluczowe są audytowane przez BSI; podmioty ważne przez firmy prywatne" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 32 governs Essential entities with proactive auditing at any time without cause. Article 33 governs Important entities with reactive auditing triggered by incidents, complaints, or other causes.",
        de: "Artikel 32 regelt wesentliche Einrichtungen mit proaktiver Prüfung jederzeit ohne Anlass. Artikel 33 regelt wichtige Einrichtungen mit reaktiver Prüfung, ausgelöst durch Vorfälle, Beschwerden oder andere Gründe.",
        nl: "Artikel 32 regelt essentiële entiteiten met proactieve audits op elk moment zonder aanleiding. Artikel 33 regelt belangrijke entiteiten met reactieve audits uitgelokt door incidenten, klachten of andere oorzaken.",
        fr: "L'article 32 régit les entités essentielles avec un audit proactif à tout moment sans motif. L'article 33 régit les entités importantes avec un audit réactif déclenché par des incidents, des plaintes ou d'autres motifs.",
        it: "L'articolo 32 disciplina i soggetti essenziali con audit proattivo in qualsiasi momento senza motivo. L'articolo 33 disciplina i soggetti importanti con audit reattivo attivato da incidenti, reclami o altre cause.",
        es: "El artículo 32 rige las entidades esenciales con auditoría proactiva en cualquier momento sin causa. El artículo 33 rige las entidades importantes con auditoría reactiva desencadenada por incidentes, denuncias u otras causas.",
        pl: "Artykuł 32 reguluje podmioty kluczowe z proaktywnym audytem w dowolnym momencie bez przyczyny. Artykuł 33 reguluje podmioty ważne z reaktywnym audytem wywołanym incydentami, skargami lub innymi przyczynami.",
      },
    },
    {
      id: "3.7.2",
      question: {
        en: "What is the difference between a finding and an observation in the auditor's report?",
        de: "Was ist der Unterschied zwischen einer Feststellung und einer Beobachtung im Auditbericht?",
        nl: "Wat is het verschil tussen een bevinding en een observatie in het auditrapport?",
        fr: "Quelle est la différence entre une constatation et une observation dans le rapport de l'auditeur ?",
        it: "Qual è la differenza tra un rilievo e un'osservazione nel rapporto dell'auditor?",
        es: "¿Cuál es la diferencia entre un hallazgo y una observación en el informe del auditor?",
        pl: "Jaka jest różnica między ustaleniem a obserwacją w raporcie audytora?",
      },
      options: [
        { en: "A finding is minor; an observation is serious", de: "Eine Feststellung ist geringfügig; eine Beobachtung ist schwerwiegend", nl: "Een bevinding is gering; een observatie is ernstig", fr: "Une constatation est mineure ; une observation est grave", it: "Un rilievo è minore; un'osservazione è grave", es: "Un hallazgo es menor; una observación es grave", pl: "Ustalenie jest drobne; obserwacja jest poważna" },
        { en: "A finding triggers a remediation order with a deadline; an observation does not trigger an order", de: "Eine Feststellung löst eine Abhilfeanordnung mit Frist aus; eine Beobachtung löst keine Anordnung aus", nl: "Een bevinding leidt tot een herstelorder met deadline; een observatie leidt niet tot een order", fr: "Une constatation déclenche une injonction de remédiation assortie d'un délai ; une observation ne déclenche pas d'injonction", it: "Un rilievo attiva un'ingiunzione di correzione con una scadenza; un'osservazione non attiva alcuna ingiunzione", es: "Un hallazgo desencadena una orden de remediación con un plazo; una observación no desencadena ninguna orden", pl: "Ustalenie uruchamia nakaz naprawczy z terminem; obserwacja nie uruchamia nakazu" },
        { en: "Both carry the same legal consequences", de: "Beide haben die gleichen rechtlichen Konsequenzen", nl: "Beide hebben dezelfde juridische gevolgen", fr: "Les deux entraînent les mêmes conséquences juridiques", it: "Entrambi comportano le stesse conseguenze giuridiche", es: "Ambos conllevan las mismas consecuencias jurídicas", pl: "Oba niosą te same skutki prawne" },
        { en: "A finding is for technical issues; an observation is for governance issues", de: "Eine Feststellung betrifft technische Themen; eine Beobachtung betrifft Governance-Themen", nl: "Een bevinding gaat over technische kwesties; een observatie over governancekwesties", fr: "Une constatation concerne les questions techniques ; une observation concerne les questions de gouvernance", it: "Un rilievo riguarda questioni tecniche; un'osservazione riguarda questioni di governance", es: "Un hallazgo es para cuestiones técnicas; una observación es para cuestiones de gobernanza", pl: "Ustalenie dotyczy kwestii technicznych; obserwacja dotyczy kwestii ładu korporacyjnego" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A finding is a non-conformance that triggers a remediation order with a deadline. An observation falls below good practice but does not violate the law and does not trigger an order.",
        de: "Eine Feststellung ist eine Abweichung, die eine Abhilfeanordnung mit Frist auslöst. Eine Beobachtung liegt unter guter Praxis, verstößt aber nicht gegen das Gesetz und löst keine Anordnung aus.",
        nl: "Een bevinding is een niet-conformiteit die leidt tot een herstelorder met deadline. Een observatie valt onder goede praktijk maar schendt de wet niet en leidt niet tot een order.",
        fr: "Une constatation est une non-conformité qui déclenche une injonction de remédiation assortie d'un délai. Une observation est en deçà des bonnes pratiques mais ne viole pas la loi et ne déclenche pas d'injonction.",
        it: "Un rilievo è una non conformità che attiva un'ingiunzione di correzione con una scadenza. Un'osservazione è al di sotto della buona prassi ma non viola la legge e non attiva alcuna ingiunzione.",
        es: "Un hallazgo es una no conformidad que desencadena una orden de remediación con un plazo. Una observación está por debajo de las buenas prácticas pero no infringe la ley y no desencadena ninguna orden.",
        pl: "Ustalenie to niezgodność, która uruchamia nakaz naprawczy z terminem. Obserwacja jest poniżej dobrej praktyki, ale nie narusza prawa i nie uruchamia nakazu.",
      },
    },
    {
      id: "3.7.3",
      question: {
        en: "How many documents form the backbone of the audit file according to the lesson?",
        de: "Wie viele Dokumente bilden laut der Lektion das Rückgrat der Auditakte?",
        nl: "Hoeveel documenten vormen de ruggengraat van het auditdossier volgens de les?",
        fr: "Combien de documents constituent l'épine dorsale du dossier d'audit selon la leçon ?",
        it: "Quanti documenti costituiscono la spina dorsale del fascicolo di audit secondo la lezione?",
        es: "¿Cuántos documentos forman la columna vertebral del expediente de auditoría según la lección?",
        pl: "Ile dokumentów stanowi trzon akt audytu według lekcji?",
      },
      options: [
        { en: "Three", de: "Drei", nl: "Drie", fr: "Trois", it: "Tre", es: "Tres", pl: "Trzy" },
        { en: "Five", de: "Fünf", nl: "Vijf", fr: "Cinq", it: "Cinque", es: "Cinco", pl: "Pięć" },
        { en: "Seven", de: "Sieben", nl: "Zeven", fr: "Sept", it: "Sette", es: "Siete", pl: "Siedem" },
        { en: "Ten", de: "Zehn", nl: "Tien", fr: "Dix", it: "Dieci", es: "Diez", pl: "Dziesięć" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Seven documents: Article 21 policy set, signed risk register with residual risk acceptance, incident reports and lessons learned, training records, CISO-to-board reporting minutes, asset inventory, and supplier contracts with critical clauses.",
        de: "Sieben Dokumente: Artikel-21-Richtlinienpaket, unterschriebenes Risikoregister mit Restrisikoakzeptanz, Vorfallberichte und Lessons Learned, Schulungsnachweise, Protokolle der CISO-Berichte an das Leitungsorgan, Asset-Inventar und Lieferantenverträge mit kritischen Klauseln.",
        nl: "Zeven documenten: beleidsset Artikel 21, ondertekend risicoregister met restrisico-acceptatie, incidentrapporten en geleerde lessen, trainingsregistraties, notulen CISO-tot-bestuur-rapportage, middelenregister en leverancierscontracten met kritieke clausules.",
        fr: "Sept documents : ensemble de politiques de l'article 21, registre des risques signé avec acceptation du risque résiduel, rapports d'incidents et enseignements tirés, registres de formation, comptes rendus du reporting du CISO au conseil, inventaire des actifs, et contrats fournisseurs avec clauses critiques.",
        it: "Sette documenti: insieme di politiche dell'articolo 21, registro dei rischi firmato con accettazione del rischio residuo, rapporti sugli incidenti e lezioni apprese, registri di formazione, verbali del reporting del CISO al consiglio, inventario degli asset e contratti con i fornitori con clausole critiche.",
        es: "Siete documentos: conjunto de políticas del artículo 21, registro de riesgos firmado con aceptación del riesgo residual, informes de incidentes y lecciones aprendidas, registros de formación, actas del reporte del CISO al consejo, inventario de activos y contratos de proveedores con cláusulas críticas.",
        pl: "Siedem dokumentów: zestaw polityk z artykułu 21, podpisany rejestr ryzyka z akceptacją ryzyka szczątkowego, raporty z incydentów i wnioski, rejestry szkoleń, protokoły raportowania CISO do zarządu, inwentaryzacja zasobów oraz umowy z dostawcami z kluczowymi klauzulami.",
      },
    },
    {
      id: "3.7.4",
      question: {
        en: "What happens if remediation is incomplete when the auditor returns?",
        de: "Was geschieht, wenn die Abhilfe bei der Rückkehr des Auditors unvollständig ist?",
        nl: "Wat gebeurt er als het herstel onvolledig is wanneer de auditor terugkeert?",
        fr: "Que se passe-t-il si la remédiation est incomplète lorsque l'auditeur revient ?",
        it: "Cosa succede se la correzione è incompleta quando l'auditor ritorna?",
        es: "¿Qué ocurre si la remediación es incompleta cuando el auditor regresa?",
        pl: "Co się stanie, jeśli naprawa jest niekompletna, gdy audytor powraca?",
      },
      options: [
        { en: "The auditor extends the deadline automatically", de: "Der Auditor verlängert die Frist automatisch", nl: "De auditor verlengt de deadline automatisch", fr: "L'auditeur prolonge automatiquement le délai", it: "L'auditor proroga automaticamente la scadenza", es: "El auditor prorroga el plazo automáticamente", pl: "Audytor automatycznie przedłuża termin" },
        { en: "The regulator escalates: binding instructions, public disclosure, or fines", de: "Die Aufsichtsbehörde eskaliert: verbindliche Anweisungen, öffentliche Bekanntmachung oder Bußgelder", nl: "De toezichthouder escaleert: bindende instructies, openbare bekendmaking of boetes", fr: "L'autorité de régulation escalade : instructions contraignantes, divulgation publique ou amendes", it: "L'autorità di regolamentazione intensifica: istruzioni vincolanti, divulgazione pubblica o sanzioni", es: "El regulador escala: instrucciones vinculantes, divulgación pública o multas", pl: "Organ nadzoru eskaluje: wiążące instrukcje, publiczne ujawnienie lub kary" },
        { en: "The finding is downgraded to an observation", de: "Die Feststellung wird zu einer Beobachtung herabgestuft", nl: "De bevinding wordt gedegradeerd tot een observatie", fr: "La constatation est rétrogradée en observation", it: "Il rilievo viene declassato a osservazione", es: "El hallazgo se rebaja a observación", pl: "Ustalenie zostaje zdegradowane do obserwacji" },
        { en: "The company is given a final warning with no further consequences", de: "Das Unternehmen erhält eine letzte Warnung ohne weitere Konsequenzen", nl: "Het bedrijf krijgt een laatste waarschuwing zonder verdere gevolgen", fr: "L'entreprise reçoit un dernier avertissement sans autre conséquence", it: "All'azienda viene dato un ultimo avvertimento senza ulteriori conseguenze", es: "Se da a la empresa una última advertencia sin más consecuencias", pl: "Firma otrzymuje ostatnie ostrzeżenie bez dalszych konsekwencji" },
      ],
      correctIndex: 1,
      explanation: {
        en: "If remediation is incomplete, the regulator escalates: binding instructions under Article 32(5), public disclosure, or fines.",
        de: "Wenn die Abhilfe unvollständig ist, eskaliert die Aufsichtsbehörde: verbindliche Anweisungen gemäß Artikel 32 Absatz 5, öffentliche Bekanntmachung oder Bußgelder.",
        nl: "Als het herstel onvolledig is, escaleert de toezichthouder: bindende instructies op grond van Artikel 32(5), openbare bekendmaking of boetes.",
        fr: "Si la remédiation est incomplète, l'autorité de régulation escalade : instructions contraignantes au titre de l'article 32(5), divulgation publique ou amendes.",
        it: "Se la correzione è incompleta, l'autorità di regolamentazione intensifica: istruzioni vincolanti ai sensi dell'articolo 32(5), divulgazione pubblica o sanzioni.",
        es: "Si la remediación es incompleta, el regulador escala: instrucciones vinculantes con arreglo al artículo 32(5), divulgación pública o multas.",
        pl: "Jeśli naprawa jest niekompletna, organ nadzoru eskaluje: wiążące instrukcje na mocy artykułu 32(5), publiczne ujawnienie lub kary.",
      },
    },
  ],
});

export default quiz;
