import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.8",
  passingScore: 75,
  questions: [
    {
      id: "3.8.1",
      question: {
        en: "What are the three reporting deadlines under Article 23 after discovering a significant incident?",
        de: "Welche drei Meldefristen gelten gemäß Artikel 23 nach der Entdeckung eines erheblichen Vorfalls?",
        nl: "Wat zijn de drie meldingstermijnen op grond van Artikel 23 na het ontdekken van een significant incident?",
        fr: "Quels sont les trois délais de notification au titre de l'article 23 après la découverte d'un incident important ?",
        it: "Quali sono i tre termini di notifica ai sensi dell'articolo 23 dopo aver scoperto un incidente significativo?",
        es: "¿Cuáles son los tres plazos de notificación con arreglo al artículo 23 tras descubrir un incidente significativo?",
        pl: "Jakie są trzy terminy zgłaszania na mocy artykułu 23 po wykryciu poważnego incydentu?",
      },
      options: [
        { en: "12 hours, 48 hours, two weeks", de: "12 Stunden, 48 Stunden, zwei Wochen", nl: "12 uur, 48 uur, twee weken", fr: "12 heures, 48 heures, deux semaines", it: "12 ore, 48 ore, due settimane", es: "12 horas, 48 horas, dos semanas", pl: "12 godzin, 48 godzin, dwa tygodnie" },
        { en: "24 hours for early warning, 72 hours for formal report, one month for final analysis", de: "24 Stunden für die Frühwarnung, 72 Stunden für den formellen Bericht, ein Monat für die Abschlussanalyse", nl: "24 uur voor vroegtijdige waarschuwing, 72 uur voor formeel rapport, één maand voor eindanalyse", fr: "24 heures pour l'alerte précoce, 72 heures pour le rapport formel, un mois pour l'analyse finale", it: "24 ore per l'allerta precoce, 72 ore per il rapporto formale, un mese per l'analisi finale", es: "24 horas para la alerta temprana, 72 horas para el informe formal, un mes para el análisis final", pl: "24 godziny na wczesne ostrzeżenie, 72 godziny na formalny raport, jeden miesiąc na analizę końcową" },
        { en: "48 hours, one week, three months", de: "48 Stunden, eine Woche, drei Monate", nl: "48 uur, één week, drie maanden", fr: "48 heures, une semaine, trois mois", it: "48 ore, una settimana, tre mesi", es: "48 horas, una semana, tres meses", pl: "48 godzin, jeden tydzień, trzy miesiące" },
        { en: "Immediately, 24 hours, one week", de: "Sofort, 24 Stunden, eine Woche", nl: "Onmiddellijk, 24 uur, één week", fr: "Immédiatement, 24 heures, une semaine", it: "Immediatamente, 24 ore, una settimana", es: "Inmediatamente, 24 horas, una semana", pl: "Natychmiast, 24 godziny, jeden tydzień" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 23(1): twenty-four hours for an early warning, seventy-two hours for a formal report, one month for the final analysis.",
        de: "Artikel 23 Absatz 1: vierundzwanzig Stunden für eine Frühwarnung, zweiundsiebzig Stunden für einen formellen Bericht, ein Monat für die Abschlussanalyse.",
        nl: "Artikel 23(1): vierentwintig uur voor een vroegtijdige waarschuwing, tweeënzeventig uur voor een formeel rapport, één maand voor de eindanalyse.",
        fr: "Article 23(1) : vingt-quatre heures pour une alerte précoce, soixante-douze heures pour un rapport formel, un mois pour l'analyse finale.",
        it: "Articolo 23(1): ventiquattro ore per un'allerta precoce, settantadue ore per un rapporto formale, un mese per l'analisi finale.",
        es: "Artículo 23(1): veinticuatro horas para una alerta temprana, setenta y dos horas para un informe formal, un mes para el análisis final.",
        pl: "Artykuł 23(1): dwadzieścia cztery godziny na wczesne ostrzeżenie, siedemdziesiąt dwie godziny na formalny raport, jeden miesiąc na analizę końcową.",
      },
    },
    {
      id: "3.8.2",
      question: {
        en: "Why should you preserve evidence before restoring from backups?",
        de: "Warum sollten Sie Beweise sichern, bevor Sie aus Backups wiederherstellen?",
        nl: "Waarom moet u bewijs bewaren vóór u vanuit back-ups herstelt?",
        fr: "Pourquoi devez-vous préserver les preuves avant de restaurer à partir de sauvegardes ?",
        it: "Perché dovreste preservare le prove prima di ripristinare dai backup?",
        es: "¿Por qué debe preservar las pruebas antes de restaurar desde las copias de seguridad?",
        pl: "Dlaczego należy zabezpieczyć dowody przed przywróceniem z kopii zapasowych?",
      },
      options: [
        { en: "Because backups may also be infected", de: "Weil auch die Backups infiziert sein koennten", nl: "Omdat back-ups mogelijk ook besmet zijn", fr: "Parce que les sauvegardes peuvent aussi être infectées", it: "Perché anche i backup potrebbero essere infetti", es: "Porque las copias de seguridad también pueden estar infectadas", pl: "Ponieważ kopie zapasowe również mogą być zainfekowane" },
        { en: "Because restoring before forensics destroys the evidence chain and leaves the entry vector open", de: "Weil eine Wiederherstellung vor der Forensik die Beweiskette zerstoert und den Angriffsvektor offen laesst", nl: "Omdat herstellen vóór forensisch onderzoek de bewijsketen vernietigt en de toegangsvector open laat", fr: "Parce que la restauration avant l'analyse forensique détruit la chaîne de preuves et laisse le vecteur d'entrée ouvert", it: "Perché ripristinare prima dell'analisi forense distrugge la catena delle prove e lascia aperto il vettore di accesso", es: "Porque restaurar antes del análisis forense destruye la cadena de pruebas y deja abierto el vector de entrada", pl: "Ponieważ przywrócenie przed analizą śledczą niszczy łańcuch dowodowy i pozostawia otwarty wektor wejścia" },
        { en: "Because the regulator requires you to wait 72 hours before restoring", de: "Weil die Aufsichtsbehörde verlangt, dass Sie 72 Stunden mit der Wiederherstellung warten", nl: "Omdat de toezichthouder vereist dat u 72 uur wacht met herstellen", fr: "Parce que l'autorité de régulation exige que vous attendiez 72 heures avant de restaurer", it: "Perché l'autorità di regolamentazione richiede di attendere 72 ore prima di ripristinare", es: "Porque el regulador exige que espere 72 horas antes de restaurar", pl: "Ponieważ organ nadzoru wymaga odczekania 72 godzin przed przywróceniem" },
        { en: "Because insurance companies will not pay if you restore too quickly", de: "Weil Versicherungen nicht zahlen, wenn Sie zu schnell wiederherstellen", nl: "Omdat verzekeraars niet betalen als u te snel herstelt", fr: "Parce que les compagnies d'assurance ne paieront pas si vous restaurez trop rapidement", it: "Perché le compagnie assicurative non pagheranno se ripristinate troppo rapidamente", es: "Porque las aseguradoras no pagarán si restaura demasiado rápido", pl: "Ponieważ ubezpieczyciele nie zapłacą, jeśli przywrócisz zbyt szybko" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Restoring before forensics examines compromised systems destroys the evidence chain and leaves the entry vector open. Norsk Hydro shifted to manual production to buy forensics time.",
        de: "Eine Wiederherstellung, bevor die Forensik kompromittierte Systeme untersucht hat, zerstoert die Beweiskette und laesst den Angriffsvektor offen. Norsk Hydro stellte auf manuelle Produktion um, um der Forensik Zeit zu verschaffen.",
        nl: "Herstellen vóórdat forensisch onderzoek gecompromitteerde systemen heeft onderzocht, vernietigt de bewijsketen en laat de toegangsvector open. Norsk Hydro schakelde over op handmatige productie om forensisch onderzoekers tijd te geven.",
        fr: "Restaurer avant que l'analyse forensique n'examine les systèmes compromis détruit la chaîne de preuves et laisse le vecteur d'entrée ouvert. Norsk Hydro est passé à la production manuelle pour gagner du temps pour l'analyse forensique.",
        it: "Ripristinare prima che l'analisi forense esamini i sistemi compromessi distrugge la catena delle prove e lascia aperto il vettore di accesso. Norsk Hydro è passata alla produzione manuale per guadagnare tempo per l'analisi forense.",
        es: "Restaurar antes de que el análisis forense examine los sistemas comprometidos destruye la cadena de pruebas y deja abierto el vector de entrada. Norsk Hydro pasó a la producción manual para ganar tiempo para el análisis forense.",
        pl: "Przywrócenie przed zbadaniem zainfekowanych systemów przez analityków śledczych niszczy łańcuch dowodowy i pozostawia otwarty wektor wejścia. Norsk Hydro przeszło na produkcję ręczną, aby zyskać czas na analizę śledczą.",
      },
    },
    {
      id: "3.8.3",
      question: {
        en: "What five decisions belong to the CEO alone in the first forty-eight hours of a ransomware attack?",
        de: "Welche fünf Entscheidungen liegen in den ersten achtundvierzig Stunden eines Ransomware-Angriffs allein beim CEO?",
        nl: "Welke vijf beslissingen zijn uitsluitend van de CEO in de eerste achtenveertig uur van een ransomwareaanval?",
        fr: "Quelles cinq décisions reviennent au seul CEO dans les quarante-huit premières heures d'une attaque par rançongiciel ?",
        it: "Quali cinque decisioni spettano esclusivamente al CEO nelle prime quarantotto ore di un attacco ransomware?",
        es: "¿Qué cinco decisiones corresponden únicamente al CEO en las primeras cuarenta y ocho horas de un ataque de ransomware?",
        pl: "Które pięć decyzji należy wyłącznie do CEO w pierwszych czterdziestu ośmiu godzinach ataku ransomware?",
      },
      options: [
        { en: "Call insurance, contact police, shut down servers, notify customers, pay the ransom", de: "Versicherung anrufen, Polizei kontaktieren, Server herunterfahren, Kunden benachrichtigen, Loesegeld zahlen", nl: "Verzekering bellen, politie contacteren, servers afsluiten, klanten informeren, losgeld betalen", fr: "Appeler l'assurance, contacter la police, arrêter les serveurs, notifier les clients, payer la rançon", it: "Chiamare l'assicurazione, contattare la polizia, spegnere i server, avvisare i clienti, pagare il riscatto", es: "Llamar al seguro, contactar a la policía, apagar los servidores, notificar a los clientes, pagar el rescate", pl: "Zadzwonić do ubezpieczyciela, skontaktować się z policją, wyłączyć serwery, powiadomić klientów, zapłacić okup" },
        { en: "Declare the crisis, authorise emergency spending, preserve evidence before restoring, file the report, hold the line on payment", de: "Die Krise erklaeren, Notfallausgaben genehmigen, Beweise vor der Wiederherstellung sichern, den Bericht einreichen, an der Zahlungsverweigerung festhalten", nl: "De crisis declareren, nooduitgaven autoriseren, bewijs bewaren vóór herstel, het rapport indienen, de lijn vasthouden over betaling", fr: "Déclarer la crise, autoriser les dépenses d'urgence, préserver les preuves avant la restauration, déposer le rapport, tenir la ligne sur le paiement", it: "Dichiarare la crisi, autorizzare le spese di emergenza, preservare le prove prima del ripristino, presentare il rapporto, mantenere la linea sul pagamento", es: "Declarar la crisis, autorizar el gasto de emergencia, preservar las pruebas antes de restaurar, presentar el informe, mantener la postura sobre el pago", pl: "Ogłosić kryzys, zatwierdzić wydatki nadzwyczajne, zabezpieczyć dowody przed przywróceniem, złożyć raport, utrzymać stanowisko w sprawie płatności" },
        { en: "Activate IT response, brief the board, contact the press, hire a consultant, file the report", de: "IT-Reaktion aktivieren, den Vorstand informieren, die Presse kontaktieren, einen Berater engagieren, den Bericht einreichen", nl: "IT-respons activeren, het bestuur briefen, de pers contacteren, een adviseur inhuren, het rapport indienen", fr: "Activer la réponse informatique, informer le conseil, contacter la presse, embaucher un consultant, déposer le rapport", it: "Attivare la risposta IT, informare il consiglio, contattare la stampa, assumere un consulente, presentare il rapporto", es: "Activar la respuesta de TI, informar al consejo, contactar a la prensa, contratar a un consultor, presentar el informe", pl: "Uruchomić reakcję IT, poinformować zarząd, skontaktować się z prasą, zatrudnić konsultanta, złożyć raport" },
        { en: "Shut down the network, call the BSI, notify employees, restore backups, review insurance", de: "Netzwerk abschalten, das BSI anrufen, Mitarbeiter benachrichtigen, Backups wiederherstellen, Versicherung prüfen", nl: "Het netwerk afsluiten, de BSI bellen, medewerkers informeren, back-ups herstellen, verzekering controleren", fr: "Arrêter le réseau, appeler le BSI, notifier les employés, restaurer les sauvegardes, examiner l'assurance", it: "Spegnere la rete, chiamare il BSI, avvisare i dipendenti, ripristinare i backup, esaminare l'assicurazione", es: "Apagar la red, llamar al BSI, notificar a los empleados, restaurar las copias de seguridad, revisar el seguro", pl: "Wyłączyć sieć, zadzwonić do BSI, powiadomić pracowników, przywrócić kopie zapasowe, przejrzeć ubezpieczenie" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Five CEO decisions: declare the crisis, authorise emergency spending, preserve evidence before restoring, file the regulatory report, hold the line on ransom payment.",
        de: "Fünf CEO-Entscheidungen: die Krise erklaeren, Notfallausgaben genehmigen, Beweise vor der Wiederherstellung sichern, den regulatorischen Bericht einreichen, an der Zahlungsverweigerung beim Loesegeld festhalten.",
        nl: "Vijf CEO-beslissingen: de crisis declareren, nooduitgaven autoriseren, bewijs bewaren vóór herstel, het regulatoire rapport indienen, de lijn vasthouden over losgeld.",
        fr: "Cinq décisions du CEO : déclarer la crise, autoriser les dépenses d'urgence, préserver les preuves avant la restauration, déposer le rapport réglementaire, tenir la ligne sur le paiement de la rançon.",
        it: "Cinque decisioni del CEO: dichiarare la crisi, autorizzare le spese di emergenza, preservare le prove prima del ripristino, presentare il rapporto normativo, mantenere la linea sul pagamento del riscatto.",
        es: "Cinco decisiones del CEO: declarar la crisis, autorizar el gasto de emergencia, preservar las pruebas antes de restaurar, presentar el informe regulatorio, mantener la postura sobre el pago del rescate.",
        pl: "Pięć decyzji CEO: ogłosić kryzys, zatwierdzić wydatki nadzwyczajne, zabezpieczyć dowody przed przywróceniem, złożyć raport regulacyjny, utrzymać stanowisko w sprawie zapłaty okupu.",
      },
    },
    {
      id: "3.8.4",
      question: {
        en: "Why did Norsk Hydro's CEO avoid personal liability despite the attack?",
        de: "Warum entging der CEO von Norsk Hydro trotz des Angriffs der persönlichen Haftung?",
        nl: "Waarom ontliep de CEO van Norsk Hydro persoonlijke aansprakelijkheid ondanks de aanval?",
        fr: "Pourquoi le CEO de Norsk Hydro a-t-il évité la responsabilité personnelle malgré l'attaque ?",
        it: "Perché il CEO di Norsk Hydro ha evitato la responsabilità personale nonostante l'attacco?",
        es: "¿Por qué el CEO de Norsk Hydro evitó la responsabilidad personal a pesar del ataque?",
        pl: "Dlaczego CEO Norsk Hydro uniknął osobistej odpowiedzialności pomimo ataku?",
      },
      options: [
        { en: "Because the company paid the ransom quickly", de: "Weil das Unternehmen das Loesegeld schnell bezahlt hat", nl: "Omdat het bedrijf snel het losgeld betaalde", fr: "Parce que l'entreprise a payé la rançon rapidement", it: "Perché l'azienda ha pagato rapidamente il riscatto", es: "Porque la empresa pagó el rescate rápidamente", pl: "Ponieważ firma szybko zapłaciła okup" },
        { en: "Because the incident response followed a board-approved plan that existed before the attack", de: "Weil die Vorfallreaktion einem vom Vorstand genehmigten Plan folgte, der vor dem Angriff existierte", nl: "Omdat de incidentrespons een door het bestuur goedgekeurd plan volgde dat vóór de aanval bestond", fr: "Parce que la réponse à l'incident a suivi un plan approuvé par le conseil qui existait avant l'attaque", it: "Perché la risposta all'incidente ha seguito un piano approvato dal consiglio che esisteva prima dell'attacco", es: "Porque la respuesta al incidente siguió un plan aprobado por el consejo que existía antes del ataque", pl: "Ponieważ reakcja na incydent przebiegała według zatwierdzonego przez zarząd planu, który istniał przed atakiem" },
        { en: "Because the attack was too sophisticated to prevent", de: "Weil der Angriff zu ausgekluegelt war, um ihn zu verhindern", nl: "Omdat de aanval te geavanceerd was om te voorkomen", fr: "Parce que l'attaque était trop sophistiquée pour être empêchée", it: "Perché l'attacco era troppo sofisticato per essere prevenuto", es: "Porque el ataque era demasiado sofisticado para prevenirlo", pl: "Ponieważ atak był zbyt wyrafinowany, by mu zapobiec" },
        { en: "Because the CEO had cybersecurity insurance", de: "Weil der CEO eine Cybersicherheitsversicherung hatte", nl: "Omdat de CEO een cyberverzekering had", fr: "Parce que le CEO disposait d'une assurance cybersécurité", it: "Perché il CEO aveva un'assicurazione di cybersicurezza", es: "Porque el CEO tenía un seguro de ciberseguridad", pl: "Ponieważ CEO miał ubezpieczenie cyberbezpieczeństwa" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The response worked because ransomware was on the risk register with a board-approved response plan. The CEO executed what the board had already signed.",
        de: "Die Reaktion funktionierte, weil Ransomware im Risikoregister mit einem vom Vorstand genehmigten Reaktionsplan stand. Der CEO fuehrte aus, was der Vorstand bereits unterschrieben hatte.",
        nl: "De respons werkte omdat ransomware op het risicoregister stond met een door het bestuur goedgekeurd responsplan. De CEO voerde uit wat het bestuur al had ondertekend.",
        fr: "La réponse a fonctionné parce que le rançongiciel figurait au registre des risques avec un plan de réponse approuvé par le conseil. Le CEO a exécuté ce que le conseil avait déjà signé.",
        it: "La risposta ha funzionato perché il ransomware era nel registro dei rischi con un piano di risposta approvato dal consiglio. Il CEO ha eseguito ciò che il consiglio aveva già firmato.",
        es: "La respuesta funcionó porque el ransomware estaba en el registro de riesgos con un plan de respuesta aprobado por el consejo. El CEO ejecutó lo que el consejo ya había firmado.",
        pl: "Reakcja zadziałała, ponieważ ransomware znajdował się w rejestrze ryzyka z zatwierdzonym przez zarząd planem reagowania. CEO wykonał to, co zarząd już podpisał.",
      },
    },
  ],
});

export default quiz;
