import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.9",
  passingScore: 75,
  questions: [
    {
      id: "3.9.1",
      question: {
        en: "When your supplier is breached and your customers' data is exposed, who is legally responsible for reporting?",
        de: "Wenn Ihr Lieferant kompromittiert wird und die Daten Ihrer Kunden offengelegt werden - wer ist rechtlich für die Meldung verantwortlich?",
        nl: "Wanneer uw leverancier wordt getroffen en de gegevens van uw klanten worden blootgesteld, wie is dan wettelijk verantwoordelijk voor de melding?",
        fr: "Lorsque votre fournisseur subit une violation et que les données de vos clients sont exposées, qui est juridiquement responsable de la notification ?",
        it: "Quando il vostro fornitore subisce una violazione e i dati dei vostri clienti vengono esposti, chi è giuridicamente responsabile della notifica?",
        es: "Cuando su proveedor sufre una brecha y los datos de sus clientes quedan expuestos, ¿quién es jurídicamente responsable de la notificación?",
        pl: "Gdy u Twojego dostawcy dojdzie do naruszenia i dane Twoich klientów zostaną ujawnione, kto jest prawnie odpowiedzialny za zgłoszenie?",
        cs: "Když je váš dodavatel napaden a data vašich zákazníků jsou vystavena, kdo je právně odpovědný za ohlášení?",
        pt: "Quando o seu fornecedor sofre uma violação e os dados dos seus clientes ficam expostos, quem é legalmente responsável pela notificação?",
        ro: "Când furnizorul dumneavoastră suferă o breșă, iar datele clienților dumneavoastră sunt expuse, cine este responsabil din punct de vedere juridic pentru raportare?",
      },
      options: [
        { en: "Only the supplier, since the breach occurred in their systems", de: "Nur der Lieferant, da der Vorfall in seinen Systemen aufgetreten ist", nl: "Alleen de leverancier, omdat het incident in hun systemen heeft plaatsgevonden", fr: "Uniquement le fournisseur, puisque la violation s'est produite dans ses systèmes", it: "Solo il fornitore, poiché la violazione si è verificata nei suoi sistemi", es: "Solo el proveedor, ya que la brecha se produjo en sus sistemas", pl: "Tylko dostawca, ponieważ naruszenie wystąpiło w jego systemach", cs: "Pouze dodavatel, protože k narušení došlo v jeho systémech", pt: "Apenas o fornecedor, uma vez que a violação ocorreu nos seus sistemas", ro: "Doar furnizorul, întrucât breșa a survenit în sistemele sale" },
        { en: "You must file your own Article 23 report - the supplier's report does not cover you", de: "Sie müssen Ihren eigenen Bericht gemäß Artikel 23 einreichen - der Bericht des Lieferanten deckt Sie nicht ab", nl: "U moet uw eigen Artikel 23-rapport indienen - het rapport van de leverancier dekt u niet", fr: "Vous devez déposer votre propre rapport au titre de l'article 23 - le rapport du fournisseur ne vous couvre pas", it: "Dovete presentare il vostro rapporto ai sensi dell'articolo 23 - il rapporto del fornitore non vi copre", es: "Debe presentar su propio informe con arreglo al artículo 23: el informe del proveedor no le cubre", pl: "Musisz złożyć własny raport z artykułu 23 - raport dostawcy Cię nie obejmuje", cs: "Musíte podat vlastní hlášení podle článku 23: hlášení dodavatele vás nekryje", pt: "Tem de apresentar o seu próprio relatório ao abrigo do artigo 23: o relatório do fornecedor não o cobre", ro: "Trebuie să depuneți propriul raport în temeiul articolului 23: raportul furnizorului nu vă acoperă" },
        { en: "The regulator decides who files based on the severity", de: "Die Aufsichtsbehörde entscheidet anhand der Schwere, wer meldet", nl: "De toezichthouder beslist wie meldt op basis van de ernst", fr: "L'autorité de régulation décide qui dépose en fonction de la gravité", it: "L'autorità di regolamentazione decide chi presenta in base alla gravità", es: "El regulador decide quién presenta en función de la gravedad", pl: "Organ nadzoru decyduje, kto zgłasza, na podstawie powagi", cs: "Regulační orgán rozhoduje, kdo podává hlášení, podle závažnosti", pt: "A autoridade reguladora decide quem apresenta o relatório com base na gravidade", ro: "Autoritatea de reglementare decide cine depune raportul în funcție de gravitate" },
        { en: "Neither party files until the full scope is determined", de: "Keine Partei meldet, bis der volle Umfang festgestellt ist", nl: "Geen van beide partijen meldt totdat de volledige omvang is vastgesteld", fr: "Aucune des parties ne dépose tant que la portée complète n'est pas déterminée", it: "Nessuna delle parti presenta finché non viene determinata l'intera portata", es: "Ninguna de las partes presenta hasta que se determina el alcance completo", pl: "Żadna ze stron nie zgłasza, dopóki nie zostanie ustalony pełny zakres", cs: "Žádná strana nepodává hlášení, dokud není určen plný rozsah", pt: "Nenhuma das partes apresenta o relatório enquanto não for determinado o âmbito completo", ro: "Niciuna dintre părți nu depune raportul până când nu este determinată amploarea completă" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A breach at your supplier is your incident under Article 23 whenever your customers are affected - the supplier's report to their regulator does not cover you.",
        de: "Ein Vorfall bei Ihrem Lieferanten ist Ihr Vorfall gemäß Artikel 23, sobald Ihre Kunden betroffen sind - der Bericht des Lieferanten an seine Aufsichtsbehörde deckt Sie nicht ab.",
        nl: "Een inbreuk bij uw leverancier is uw incident op grond van Artikel 23 wanneer uw klanten worden getroffen - het rapport van de leverancier aan hun toezichthouder dekt u niet.",
        fr: "Une violation chez votre fournisseur est votre incident au titre de l'article 23 dès lors que vos clients sont touchés - le rapport du fournisseur à son autorité de régulation ne vous couvre pas.",
        it: "Una violazione presso il vostro fornitore è il vostro incidente ai sensi dell'articolo 23 ogni volta che i vostri clienti sono coinvolti - il rapporto del fornitore alla sua autorità di regolamentazione non vi copre.",
        es: "Una brecha en su proveedor es su incidente con arreglo al artículo 23 siempre que sus clientes se vean afectados: el informe del proveedor a su regulador no le cubre.",
        pl: "Naruszenie u Twojego dostawcy jest Twoim incydentem na mocy artykułu 23, ilekroć dotyczy Twoich klientów - raport dostawcy do jego organu nadzoru Cię nie obejmuje.",
        cs: "Narušení u vašeho dodavatele je vaším incidentem podle článku 23, kdykoli jsou dotčeni vaši zákazníci. Hlášení dodavatele jeho regulačnímu orgánu vás nekryje.",
        pt: "Uma violação no seu fornecedor é o seu incidente ao abrigo do artigo 23 sempre que os seus clientes sejam afetados. O relatório do fornecedor à respetiva autoridade reguladora não o cobre.",
        ro: "O breșă la furnizorul dumneavoastră este incidentul dumneavoastră în temeiul articolului 23 ori de câte ori sunt afectați clienții dumneavoastră. Raportul furnizorului către autoritatea sa de reglementare nu vă acoperă.",
      },
    },
    {
      id: "3.9.2",
      question: {
        en: "What three supplier contract clauses does the lesson say you should check immediately during a supplier breach?",
        de: "Welche drei Lieferantenvertragsklauseln sollten Sie laut der Lektion bei einem Lieferantenvorfall sofort prüfen?",
        nl: "Welke drie clausules in leverancierscontracten moet u onmiddellijk controleren bij een leveranciersincident?",
        fr: "Quelles trois clauses du contrat fournisseur la leçon recommande-t-elle de vérifier immédiatement lors d'une violation chez un fournisseur ?",
        it: "Quali tre clausole del contratto con il fornitore la lezione consiglia di controllare immediatamente durante una violazione del fornitore?",
        es: "¿Qué tres cláusulas del contrato con el proveedor recomienda la lección comprobar de inmediato durante una brecha del proveedor?",
        pl: "Które trzy klauzule umowy z dostawcą lekcja zaleca natychmiast sprawdzić podczas naruszenia u dostawcy?",
        cs: "Která tři smluvní ujednání s dodavatelem byste podle lekce měli během narušení u dodavatele okamžitě zkontrolovat?",
        pt: "Que três cláusulas do contrato com o fornecedor diz a lição que deve verificar imediatamente durante uma violação no fornecedor?",
        ro: "Care trei clauze ale contractului cu furnizorul spune lecția că ar trebui să le verificați imediat în timpul unei breșe la furnizor?",
      },
      options: [
        { en: "Price, term, and jurisdiction", de: "Preis, Laufzeit und Gerichtsstand", nl: "Prijs, looptijd en rechtsgebied", fr: "Prix, durée et juridiction", it: "Prezzo, durata e giurisdizione", es: "Precio, plazo y jurisdicción", pl: "Cena, okres obowiązywania i jurysdykcja", cs: "Cenu, dobu trvání a soudní příslušnost", pt: "Preço, prazo e jurisdição", ro: "Preț, durată și jurisdicție" },
        { en: "Incident notification timelines, audit rights, and indemnification", de: "Vorfallbenachrichtigungsfristen, Prüfungsrechte und Schadloshaltung", nl: "Meldingstermijnen bij incidenten, auditrechten en schadevergoeding", fr: "Délais de notification des incidents, droits d'audit et indemnisation", it: "Tempistiche di notifica degli incidenti, diritti di audit e indennizzo", es: "Plazos de notificación de incidentes, derechos de auditoría e indemnización", pl: "Terminy powiadamiania o incydentach, prawa do audytu i odszkodowanie", cs: "Lhůty pro oznamování incidentů, práva na audit a odškodnění", pt: "Prazos de notificação de incidentes, direitos de auditoria e indemnização", ro: "Termenele de notificare a incidentelor, drepturile de audit și despăgubirea" },
        { en: "SLA, data processing agreement, and liability cap", de: "SLA, Auftragsverarbeitungsvertrag und Haftungsobergrenze", nl: "SLA, gegevensverwerkingsovereenkomst en aansprakelijkheidslimiet", fr: "SLA, accord de traitement des données et plafond de responsabilité", it: "SLA, accordo sul trattamento dei dati e limite di responsabilità", es: "ANS, acuerdo de tratamiento de datos y límite de responsabilidad", pl: "SLA, umowa powierzenia przetwarzania danych i limit odpowiedzialności", cs: "SLA, smlouvu o zpracování dat a strop odpovědnosti", pt: "SLA, acordo de tratamento de dados e limite de responsabilidade", ro: "SLA, acordul de prelucrare a datelor și plafonul de răspundere" },
        { en: "Termination clause, force majeure, and warranty", de: "Kuendigungsklausel, hoehere Gewalt und Gewaehrleistung", nl: "Opzeggingsclausule, overmacht en garantie", fr: "Clause de résiliation, force majeure et garantie", it: "Clausola di risoluzione, forza maggiore e garanzia", es: "Cláusula de rescisión, fuerza mayor y garantía", pl: "Klauzula wypowiedzenia, siła wyższa i gwarancja", cs: "Ustanovení o ukončení, vyšší moc a záruku", pt: "Cláusula de rescisão, força maior e garantia", ro: "Clauza de reziliere, forța majoră și garanția" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Incident notification timelines, audit rights, and indemnification - those three clauses decide your response timeline, your access rights, and cost recovery.",
        de: "Vorfallbenachrichtigungsfristen, Prüfungsrechte und Schadloshaltung - diese drei Klauseln bestimmen Ihren Reaktionszeitraum, Ihre Zugriffsrechte und die Kostenerstattung.",
        nl: "Meldingstermijnen bij incidenten, auditrechten en schadevergoeding - die drie clausules bepalen uw responstermijn, uw toegangsrechten en kostenherstel.",
        fr: "Délais de notification des incidents, droits d'audit et indemnisation - ces trois clauses déterminent votre délai de réponse, vos droits d'accès et le recouvrement des coûts.",
        it: "Tempistiche di notifica degli incidenti, diritti di audit e indennizzo - queste tre clausole determinano la vostra tempistica di risposta, i vostri diritti di accesso e il recupero dei costi.",
        es: "Plazos de notificación de incidentes, derechos de auditoría e indemnización: esas tres cláusulas determinan su plazo de respuesta, sus derechos de acceso y la recuperación de costes.",
        pl: "Terminy powiadamiania o incydentach, prawa do audytu i odszkodowanie - te trzy klauzule określają Twój czas reakcji, prawa dostępu i odzyskanie kosztów.",
        cs: "Lhůty pro oznamování incidentů, práva na audit a odškodnění: tato tři ujednání určují váš časový rámec reakce, vaše práva na přístup a náhradu nákladů.",
        pt: "Prazos de notificação de incidentes, direitos de auditoria e indemnização: estas três cláusulas determinam o seu calendário de resposta, os seus direitos de acesso e a recuperação de custos.",
        ro: "Termenele de notificare a incidentelor, drepturile de audit și despăgubirea: aceste trei clauze decid calendarul răspunsului dumneavoastră, drepturile de acces și recuperarea costurilor.",
      },
    },
    {
      id: "3.9.3",
      question: {
        en: "What two things did the MOVEit companies that responded best have in common?",
        de: "Was hatten die MOVEit-Unternehmen, die am besten reagiert haben, gemeinsam?",
        nl: "Wat hadden de MOVEit-bedrijven die het beste reageerden gemeen?",
        fr: "Quels deux points communs avaient les entreprises MOVEit qui ont le mieux réagi ?",
        it: "Quali due cose avevano in comune le aziende MOVEit che hanno risposto meglio?",
        es: "¿Qué dos cosas tenían en común las empresas de MOVEit que mejor respondieron?",
        pl: "Co miały wspólnego firmy MOVEit, które zareagowały najlepiej?",
        cs: "Co měly společné společnosti zasažené MOVEit, které reagovaly nejlépe?",
        pt: "Que duas coisas tinham em comum as empresas afetadas pelo MOVEit que melhor responderam?",
        ro: "Ce două lucruri aveau în comun companiile afectate de MOVEit care au răspuns cel mai bine?",
      },
      options: [
        { en: "Cyber insurance and external legal counsel on retainer", de: "Cyberversicherung und externe Rechtsberatung auf Retainer-Basis", nl: "Cyberverzekering en externe juridische adviseurs op retainer-basis", fr: "Une cyberassurance et un conseil juridique externe sous contrat permanent", it: "Cyberassicurazione e consulenza legale esterna a contratto continuativo", es: "Ciberseguro y asesoría jurídica externa con contrato de retención", pl: "Cyberubezpieczenie i zewnętrzni doradcy prawni na stałym zleceniu", cs: "Kybernetické pojištění a trvale zajištěného externího právního zástupce", pt: "Seguro cibernético e advogado externo em regime de avença", ro: "Asigurare cibernetică și consilier juridic extern permanent" },
        { en: "A pre-drafted customer notification template and a map of which suppliers touched which customer data", de: "Eine vorbereitete Kundenbenachrichtigungsvorlage und eine Zuordnung, welche Lieferanten auf welche Kundendaten zugegriffen haben", nl: "Een vooraf opgesteld klantmeldingssjabloon en een overzicht van welke leveranciers welke klantgegevens aanraakten", fr: "Un modèle de notification client préétabli et une cartographie indiquant quels fournisseurs ont accédé à quelles données clients", it: "Un modello di notifica al cliente predisposto e una mappa di quali fornitori hanno avuto accesso a quali dati dei clienti", es: "Una plantilla de notificación al cliente preelaborada y un mapa de qué proveedores tocaron qué datos de clientes", pl: "Wstępnie przygotowany szablon powiadomienia klienta oraz mapa, którzy dostawcy mieli dostęp do których danych klientów", cs: "Předem připravenou šablonu oznámení zákazníkům a mapu toho, kteří dodavatelé pracovali s kterými zákaznickými daty", pt: "Um modelo de notificação aos clientes previamente redigido e um mapa de que fornecedores tocaram em que dados de clientes", ro: "Un model de notificare a clienților redactat în prealabil și o hartă a furnizorilor care au avut acces la anumite date ale clienților" },
        { en: "A dedicated incident response team and 24/7 security monitoring", de: "Ein dediziertes Incident-Response-Team und 24/7-Sicherheitsueberwachung", nl: "Een toegewijd incidentresponsteam en 24/7 beveiligingsmonitoring", fr: "Une équipe dédiée de réponse aux incidents et une surveillance de sécurité 24/7", it: "Un team dedicato di risposta agli incidenti e un monitoraggio della sicurezza 24/7", es: "Un equipo dedicado de respuesta a incidentes y monitorización de seguridad 24/7", pl: "Dedykowany zespół reagowania na incydenty i monitorowanie bezpieczeństwa 24/7", cs: "Vyhrazený tým pro reakci na incidenty a nepřetržité bezpečnostní monitorování (24/7)", pt: "Uma equipa dedicada de resposta a incidentes e monitorização de segurança permanente", ro: "O echipă dedicată de răspuns la incidente și monitorizare a securității non-stop" },
        { en: "Direct communication with law enforcement and a PR agency", de: "Direkte Kommunikation mit Strafverfolgungsbehörden und einer PR-Agentur", nl: "Directe communicatie met rechtshandhaving en een PR-bureau", fr: "Une communication directe avec les forces de l'ordre et une agence de relations publiques", it: "Comunicazione diretta con le forze dell'ordine e un'agenzia di pubbliche relazioni", es: "Comunicación directa con las fuerzas del orden y una agencia de relaciones públicas", pl: "Bezpośrednia komunikacja z organami ścigania i agencją PR", cs: "Přímou komunikaci s orgány činnými v trestním řízení a agenturu pro vztahy s veřejností", pt: "Comunicação direta com as autoridades policiais e uma agência de relações públicas", ro: "Comunicare directă cu autoritățile de aplicare a legii și o agenție de relații publice" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The MOVEit companies that came out cleanest had a pre-drafted notification template and a map of which suppliers touched which customer data - cutting response time from days to hours.",
        de: "Die MOVEit-Unternehmen, die am besten davonkamen, hatten eine vorbereitete Benachrichtigungsvorlage und eine Zuordnung, welche Lieferanten auf welche Kundendaten zugegriffen haben - das reduzierte die Reaktionszeit von Tagen auf Stunden.",
        nl: "De MOVEit-bedrijven die er het best uitkwamen hadden een vooraf opgesteld meldingssjabloon en een overzicht van welke leveranciers welke klantgegevens aanraakten - wat de responstijd van dagen naar uren verkortte.",
        fr: "Les entreprises MOVEit qui s'en sont le mieux sorties disposaient d'un modèle de notification préétabli et d'une cartographie indiquant quels fournisseurs ont accédé à quelles données clients - réduisant le délai de réponse de jours à heures.",
        it: "Le aziende MOVEit che ne sono uscite meglio avevano un modello di notifica predisposto e una mappa di quali fornitori avevano avuto accesso a quali dati dei clienti - riducendo il tempo di risposta da giorni a ore.",
        es: "Las empresas de MOVEit que salieron mejor paradas tenían una plantilla de notificación preelaborada y un mapa de qué proveedores tocaron qué datos de clientes, reduciendo el tiempo de respuesta de días a horas.",
        pl: "Firmy MOVEit, które wyszły z tego najlepiej, miały wstępnie przygotowany szablon powiadomienia oraz mapę, którzy dostawcy mieli dostęp do których danych klientów - skracając czas reakcji z dni do godzin.",
        cs: "Společnosti zasažené MOVEit, které z toho vyšly nejlépe, měly předem připravenou šablonu oznámení a mapu toho, kteří dodavatelé pracovali s kterými zákaznickými daty, čímž zkrátily dobu reakce ze dnů na hodiny.",
        pt: "As empresas afetadas pelo MOVEit que saíram mais ilesas tinham um modelo de notificação previamente redigido e um mapa de que fornecedores tocaram em que dados de clientes, reduzindo o tempo de resposta de dias para horas.",
        ro: "Companiile afectate de MOVEit care au ieșit cel mai bine aveau un model de notificare redactat în prealabil și o hartă a furnizorilor care au avut acces la anumite date ale clienților, reducând timpul de răspuns de la zile la ore.",
      },
    },
    {
      id: "3.9.4",
      question: {
        en: "Which of the five CEO decisions should you take your time on during a supplier breach?",
        de: "Bei welcher der fünf CEO-Entscheidungen sollten Sie sich bei einem Lieferantenvorfall Zeit lassen?",
        nl: "Welke van de vijf CEO-beslissingen mag u rustig de tijd voor nemen bij een leveranciersincident?",
        fr: "Pour laquelle des cinq décisions du CEO devez-vous prendre votre temps lors d'une violation chez un fournisseur ?",
        it: "Per quale delle cinque decisioni del CEO dovreste prendervi il vostro tempo durante una violazione del fornitore?",
        es: "¿En cuál de las cinco decisiones del CEO debe tomarse su tiempo durante una brecha del proveedor?",
        pl: "Przy której z pięciu decyzji CEO możesz nie spieszyć się podczas naruszenia u dostawcy?",
        cs: "U kterého z pěti rozhodnutí generálního ředitele byste si během narušení u dodavatele měli dát načas?",
        pt: "Em qual das cinco decisões do diretor executivo deve levar o seu tempo durante uma violação no fornecedor?",
        ro: "La care dintre cele cinci decizii ale directorului general ar trebui să vă luați timp în cazul unei breșe la furnizor?",
      },
      options: [
        { en: "Filing your own regulatory report", de: "Die eigene regulatorische Meldung einreichen", nl: "Uw eigen regulatoire rapport indienen", fr: "Déposer votre propre rapport réglementaire", it: "Presentare il vostro rapporto normativo", es: "Presentar su propio informe regulatorio", pl: "Złożenie własnego raportu regulacyjnego", cs: "Podání vlastního hlášení regulačnímu orgánu", pt: "Apresentar o seu próprio relatório à autoridade reguladora", ro: "Depunerea propriului raport către autoritatea de reglementare" },
        { en: "Notifying affected customers", de: "Betroffene Kunden benachrichtigen", nl: "Getroffen klanten informeren", fr: "Notifier les clients touchés", it: "Avvisare i clienti coinvolti", es: "Notificar a los clientes afectados", pl: "Powiadomienie poszkodowanych klientów", cs: "Informování dotčených zákazníků", pt: "Notificar os clientes afetados", ro: "Notificarea clienților afectați" },
        { en: "Pursuing contractual remedies - only after the immediate incident is handled", de: "Vertragliche Rechtsbehelfe verfolgen - erst nachdem der unmittelbare Vorfall bewaeltigt ist", nl: "Contractuele middelen inzetten - pas nadat het onmiddellijke incident is afgehandeld", fr: "Engager des recours contractuels - uniquement après que l'incident immédiat est géré", it: "Perseguire i rimedi contrattuali - solo dopo che l'incidente immediato è stato gestito", es: "Ejercer los recursos contractuales, solo después de gestionar el incidente inmediato", pl: "Dochodzenie środków umownych - dopiero po opanowaniu bezpośredniego incydentu", cs: "Uplatnění smluvních nápravných prostředků: až poté, co je bezprostřední incident zvládnut", pt: "Procurar as soluções contratuais: apenas depois de o incidente imediato estar resolvido", ro: "Urmărirea remediilor contractuale: doar după ce incidentul imediat este gestionat" },
        { en: "Forcing the facts from the supplier", de: "Die Fakten vom Lieferanten einfordern", nl: "De feiten bij de leverancier forceren", fr: "Forcer le fournisseur à révéler les faits", it: "Ottenere con forza i fatti dal fornitore", es: "Obtener los hechos del proveedor", pl: "Wymuszenie faktów od dostawcy", cs: "Vynucení faktů od dodavatele", pt: "Forçar a obtenção dos factos junto do fornecedor", ro: "Obținerea forțată a faptelor de la furnizor" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Contractual remedies are the only decision you should take your time on. Once the immediate incident is handled, decide whether to trigger indemnification, switch providers, or renegotiate.",
        de: "Vertragliche Rechtsbehelfe sind die einzige Entscheidung, bei der Sie sich Zeit lassen sollten. Sobald der unmittelbare Vorfall bewaeltigt ist, entscheiden Sie, ob Sie die Schadloshaltung einfordern, den Anbieter wechseln oder nachverhandeln.",
        nl: "Contractuele middelen zijn de enige beslissing waarbij u de tijd mag nemen. Zodra het onmiddellijke incident is afgehandeld, beslist u of u schadevergoeding vordert, van leverancier wisselt of heronderhandelt.",
        fr: "Les recours contractuels sont la seule décision pour laquelle vous devriez prendre votre temps. Une fois l'incident immédiat géré, décidez s'il faut déclencher l'indemnisation, changer de prestataire ou renégocier.",
        it: "I rimedi contrattuali sono l'unica decisione per cui dovreste prendervi il vostro tempo. Una volta gestito l'incidente immediato, decidete se attivare l'indennizzo, cambiare fornitore o rinegoziare.",
        es: "Los recursos contractuales son la única decisión en la que debe tomarse su tiempo. Una vez gestionado el incidente inmediato, decida si activar la indemnización, cambiar de proveedor o renegociar.",
        pl: "Środki umowne to jedyna decyzja, przy której możesz nie spieszyć się. Po opanowaniu bezpośredniego incydentu zdecyduj, czy uruchomić odszkodowanie, zmienić dostawcę, czy renegocjować.",
        cs: "Smluvní nápravné prostředky jsou jediným rozhodnutím, u kterého si máte dát načas. Jakmile je bezprostřední incident zvládnut, rozhodněte, zda uplatnit odškodnění, změnit poskytovatele, nebo znovu vyjednávat.",
        pt: "As soluções contratuais são a única decisão em que deve levar o seu tempo. Uma vez resolvido o incidente imediato, decida se aciona a indemnização, muda de fornecedor ou renegoceia.",
        ro: "Remediile contractuale sunt singura decizie la care ar trebui să vă luați timp. Odată ce incidentul imediat este gestionat, decideți dacă declanșați despăgubirea, schimbați furnizorul sau renegociați.",
      },
    },
  ],
});

export default quiz;
