import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "4.1",
  passingScore: 75,
  questions: [
    {
      id: "4.1.1",
      question: {
        en: "Does Article 21 of the NIS2 Directive list insurance as one of the ten required measures?",
        de: "Listet Artikel 21 der NIS2-Richtlinie Versicherung als eine der zehn geforderten Maßnahmen auf?",
        nl: "Vermeldt artikel 21 van de NIS2-richtlijn verzekering als een van de tien vereiste maatregelen?",
        fr: "L'article 21 de la directive NIS2 mentionne-t-il l'assurance comme l'une des dix mesures requises ?",
        it: "L'articolo 21 della direttiva NIS2 elenca l'assicurazione tra le dieci misure richieste?",
        es: "¿Incluye el artículo 21 de la Directiva NIS2 el seguro como una de las diez medidas requeridas?",
        pl: "Czy artykuł 21 dyrektywy NIS2 wymienia ubezpieczenie jako jeden z dziesięciu wymaganych środków?",
        cs: "Uvádí článek 21 směrnice NIS2 pojištění jako jedno z deseti povinných opatření?",
        pt: "O artigo 21 da Diretiva NIS2 enumera o seguro como uma das dez medidas exigidas?",
        ro: "Articolul 21 din Directiva NIS2 enumeră asigurarea ca una dintre cele zece măsuri obligatorii?",
      },
      options: [
        { en: "Yes, insurance is listed as the tenth measure", de: "Ja, Versicherung ist als zehnte Maßnahme aufgeführt", nl: "Ja, verzekering staat vermeld als de tiende maatregel", fr: "Oui, l'assurance figure comme la dixième mesure", it: "Sì, l'assicurazione è elencata come decima misura", es: "Sí, el seguro figura como la décima medida", pl: "Tak, ubezpieczenie jest wymienione jako dziesiąty środek", cs: "Ano, pojištění je uvedeno jako desáté opatření", pt: "Sim, o seguro consta como a décima medida", ro: "Da, asigurarea figurează ca a zecea măsură" },
        { en: "No, the word insurance does not appear in the ten measures", de: "Nein, das Wort Versicherung kommt in den zehn Maßnahmen nicht vor", nl: "Nee, het woord verzekering komt niet voor in de tien maatregelen", fr: "Non, le mot assurance n'apparaît pas dans les dix mesures", it: "No, la parola assicurazione non compare nelle dieci misure", es: "No, la palabra seguro no aparece en las diez medidas", pl: "Nie, słowo ubezpieczenie nie pojawia się wśród dziesięciu środków", cs: "Ne, slovo pojištění se v deseti opatřeních neobjevuje", pt: "Não, a palavra seguro não aparece nas dez medidas", ro: "Nu, cuvântul asigurare nu apare în cele zece măsuri" },
        { en: "Insurance is listed as an optional additional measure", de: "Versicherung ist als optionale zusätzliche Maßnahme aufgeführt", nl: "Verzekering staat vermeld als een optionele aanvullende maatregel", fr: "L'assurance figure comme une mesure supplémentaire facultative", it: "L'assicurazione è elencata come misura aggiuntiva facoltativa", es: "El seguro figura como una medida adicional opcional", pl: "Ubezpieczenie jest wymienione jako opcjonalny środek dodatkowy", cs: "Pojištění je uvedeno jako nepovinné doplňkové opatření", pt: "O seguro consta como uma medida adicional facultativa", ro: "Asigurarea figurează ca o măsură suplimentară facultativă" },
        { en: "Yes, but only for Essential entities", de: "Ja, aber nur für wesentliche Einrichtungen", nl: "Ja, maar alleen voor essentiële entiteiten", fr: "Oui, mais uniquement pour les entités essentielles", it: "Sì, ma solo per i soggetti essenziali", es: "Sí, pero solo para las entidades esenciales", pl: "Tak, ale tylko dla podmiotów kluczowych", cs: "Ano, ale pouze u základních subjektů", pt: "Sim, mas apenas para entidades essenciais", ro: "Da, dar numai pentru entitățile esențiale" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 21 lists ten measures you must have in place. Nowhere in those ten measures does the word 'insurance' appear.",
        de: "Artikel 21 listet zehn Maßnahmen auf, die Sie umsetzen müssen. In keiner dieser zehn Maßnahmen kommt das Wort 'Versicherung' vor.",
        nl: "Artikel 21 bevat een lijst van tien maatregelen die u moet hebben geïmplementeerd. Nergens in die tien maatregelen komt het woord 'verzekering' voor.",
        fr: "L'article 21 énumère dix mesures que vous devez avoir mises en place. Nulle part dans ces dix mesures n'apparaît le mot « assurance ».",
        it: "L'articolo 21 elenca dieci misure che dovete avere in atto. In nessuna di queste dieci misure compare la parola 'assicurazione'.",
        es: "El artículo 21 enumera diez medidas que debe tener implementadas. En ninguna de esas diez medidas aparece la palabra «seguro».",
        pl: "Artykuł 21 wymienia dziesięć środków, które musisz wdrożyć. W żadnym z tych dziesięciu środków nie pojawia się słowo „ubezpieczenie”.",
        cs: "Článek 21 uvádí deset opatření, která musíte mít zavedena. V žádném z těchto deseti opatření se slovo 'pojištění' neobjevuje.",
        pt: "O artigo 21 enumera dez medidas que tem de ter implementadas. Em nenhuma dessas dez medidas aparece a palavra 'seguro'.",
        ro: "Articolul 21 enumeră zece măsuri pe care trebuie să le aveți implementate. În niciuna dintre aceste zece măsuri nu apare cuvântul 'asigurare'.",
      },
    },
    {
      id: "4.1.2",
      question: {
        en: "According to the BSI guidance referenced in the lesson, is risk transfer (including insurance) an acceptable treatment for serious risks at NIS2-covered entities?",
        de: "Ist laut der im Kurs referenzierten BSI-Empfehlung Risikotransfer (einschließlich Versicherung) eine akzeptable Behandlung für schwerwiegende Risiken bei NIS2-betroffenen Einrichtungen?",
        nl: "Is risicooverdracht (inclusief verzekering) volgens de BSI-richtlijnen waarnaar in de les wordt verwezen een aanvaardbare behandeling voor ernstige risico's bij NIS2-entiteiten?",
        fr: "Selon les orientations du BSI référencées dans la leçon, le transfert de risque (y compris l'assurance) est-il un traitement acceptable pour les risques graves dans les entités relevant de NIS2 ?",
        it: "Secondo le linee guida del BSI citate nella lezione, il trasferimento del rischio (compresa l'assicurazione) è un trattamento accettabile per i rischi gravi nei soggetti rientranti in NIS2?",
        es: "Según las orientaciones del BSI referenciadas en la lección, ¿es la transferencia del riesgo (incluido el seguro) un tratamiento aceptable para los riesgos graves en las entidades sujetas a NIS2?",
        pl: "Zgodnie z wytycznymi BSI przywołanymi w lekcji, czy transfer ryzyka (w tym ubezpieczenie) jest akceptowalnym sposobem postępowania z poważnymi ryzykami w podmiotach objętych NIS2?",
        cs: "Je podle pokynů BSI uvedených v lekci přenos rizika (včetně pojištění) přijatelným ošetřením závažných rizik u subjektů, na něž se vztahuje NIS2?",
        pt: "Segundo a orientação do BSI referida na lição, é a transferência de risco (incluindo o seguro) um tratamento aceitável para riscos graves nas entidades abrangidas pela NIS2?",
        ro: "Potrivit ghidului BSI menționat în lecție, este transferul riscului (inclusiv asigurarea) un tratament acceptabil pentru riscurile grave la entitățile vizate de NIS2?",
      },
      options: [
        { en: "Yes, risk transfer is always acceptable", de: "Ja, Risikotransfer ist immer akzeptabel", nl: "Ja, risicooverdracht is altijd aanvaardbaar", fr: "Oui, le transfert de risque est toujours acceptable", it: "Sì, il trasferimento del rischio è sempre accettabile", es: "Sí, la transferencia del riesgo siempre es aceptable", pl: "Tak, transfer ryzyka jest zawsze akceptowalny", cs: "Ano, přenos rizika je vždy přijatelný", pt: "Sim, a transferência de risco é sempre aceitável", ro: "Da, transferul riscului este întotdeauna acceptabil" },
        { en: "Yes, but only if combined with other controls", de: "Ja, aber nur in Kombination mit anderen Kontrollen", nl: "Ja, maar alleen in combinatie met andere beheersmaatregelen", fr: "Oui, mais uniquement s'il est combiné à d'autres contrôles", it: "Sì, ma solo se combinato con altri controlli", es: "Sí, pero solo si se combina con otros controles", pl: "Tak, ale tylko w połączeniu z innymi kontrolami", cs: "Ano, ale pouze v kombinaci s dalšími opatřeními", pt: "Sim, mas apenas se combinada com outros controlos", ro: "Da, dar numai dacă este combinat cu alte controale" },
        { en: "No, the BSI guidance explicitly says risk transfer is not acceptable for serious risks", de: "Nein, die BSI-Empfehlung sagt ausdrücklich, dass Risikotransfer für schwerwiegende Risiken nicht akzeptabel ist", nl: "Nee, de BSI-richtlijnen stellen uitdrukkelijk dat risicooverdracht niet aanvaardbaar is voor ernstige risico's", fr: "Non, les orientations du BSI indiquent explicitement que le transfert de risque n'est pas acceptable pour les risques graves", it: "No, le linee guida del BSI affermano esplicitamente che il trasferimento del rischio non è accettabile per i rischi gravi", es: "No, las orientaciones del BSI dicen explícitamente que la transferencia del riesgo no es aceptable para los riesgos graves", pl: "Nie, wytyczne BSI wyraźnie stwierdzają, że transfer ryzyka nie jest akceptowalny w przypadku poważnych ryzyk", cs: "Ne, pokyny BSI výslovně uvádějí, že přenos rizika není u závažných rizik přijatelný", pt: "Não, a orientação do BSI afirma expressamente que a transferência de risco não é aceitável para riscos graves", ro: "Nu, ghidul BSI afirmă în mod expres că transferul riscului nu este acceptabil pentru riscurile grave" },
        { en: "It depends on the size of the company", de: "Es hängt von der Größe des Unternehmens ab", nl: "Het hangt af van de omvang van het bedrijf", fr: "Cela dépend de la taille de l'entreprise", it: "Dipende dalle dimensioni dell'azienda", es: "Depende del tamaño de la empresa", pl: "To zależy od wielkości firmy", cs: "Záleží na velikosti společnosti", pt: "Depende da dimensão da empresa", ro: "Depinde de dimensiunea companiei" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The BSI guidance explicitly says risk transfer - including insurance - is not an acceptable treatment for serious risks at NIS2-covered entities.",
        de: "Die BSI-Empfehlung sagt ausdrücklich, dass Risikotransfer - einschließlich Versicherung - keine akzeptable Behandlung für schwerwiegende Risiken bei NIS2-betroffenen Einrichtungen ist.",
        nl: "De BSI-richtlijnen stellen uitdrukkelijk dat risicooverdracht - inclusief cyberverzekering - geen aanvaardbare behandeling is voor ernstige risico's bij NIS2-entiteiten.",
        fr: "Les orientations du BSI indiquent explicitement que le transfert de risque - y compris l'assurance - n'est pas un traitement acceptable pour les risques graves dans les entités relevant de NIS2.",
        it: "Le linee guida del BSI affermano esplicitamente che il trasferimento del rischio - compresa l'assicurazione - non è un trattamento accettabile per i rischi gravi nei soggetti rientranti in NIS2.",
        es: "Las orientaciones del BSI dicen explícitamente que la transferencia del riesgo - incluido el seguro - no es un tratamiento aceptable para los riesgos graves en las entidades sujetas a NIS2.",
        pl: "Wytyczne BSI wyraźnie stwierdzają, że transfer ryzyka - w tym ubezpieczenie - nie jest akceptowalnym sposobem postępowania z poważnymi ryzykami w podmiotach objętych NIS2.",
        cs: "Pokyny BSI výslovně uvádějí, že přenos rizika, včetně pojištění, není přijatelným ošetřením závažných rizik u subjektů, na něž se vztahuje NIS2.",
        pt: "A orientação do BSI afirma expressamente que a transferência de risco, incluindo o seguro, não é um tratamento aceitável para riscos graves nas entidades abrangidas pela NIS2.",
        ro: "Ghidul BSI afirmă în mod expres că transferul riscului, inclusiv asigurarea, nu este un tratament acceptabil pentru riscurile grave la entitățile vizate de NIS2.",
      },
    },
    {
      id: "4.1.3",
      question: {
        en: "Which three consequences does insurance NOT remove according to the lesson?",
        de: "Welche drei Konsequenzen beseitigt Versicherung laut der Lektion NICHT?",
        nl: "Welke drie gevolgen neemt verzekering NIET weg, volgens de les?",
        fr: "Quelles trois conséquences l'assurance ne supprime-t-elle PAS selon la leçon ?",
        it: "Quali tre conseguenze l'assicurazione NON elimina secondo la lezione?",
        es: "¿Qué tres consecuencias NO elimina el seguro según la lección?",
        pl: "Których trzech konsekwencji ubezpieczenie NIE usuwa według lekcji?",
        cs: "Které tři následky pojištění podle lekce NEodstraní?",
        pt: "Que três consequências o seguro NÃO elimina segundo a lição?",
        ro: "Care trei consecințe NU le elimină asigurarea potrivit lecției?",
      },
      options: [
        { en: "Business interruption, data loss, and reputational damage", de: "Betriebsunterbrechung, Datenverlust und Reputationsschaden", nl: "Bedrijfsonderbreking, gegevensverlies en reputatieschade", fr: "Interruption d'activité, perte de données et atteinte à la réputation", it: "Interruzione dell'attività, perdita di dati e danno reputazionale", es: "Interrupción del negocio, pérdida de datos y daño reputacional", pl: "Przerwa w działalności, utrata danych i szkoda wizerunkowa", cs: "Přerušení provozu, ztrátu dat a poškození pověsti", pt: "Interrupção da atividade, perda de dados e danos reputacionais", ro: "Întreruperea activității, pierderea de date și prejudiciul reputațional" },
        { en: "Regulatory fines, the manager ban, and the customer notification duty", de: "Regulatorische Bußgelder, das Geschäftsführungsverbot und die Kundenbenachrichtigungspflicht", nl: "Regulatoire boetes, het beheerdersverbod en de klantmeldingsplicht", fr: "Les amendes réglementaires, l'interdiction de gérer, et l'obligation de notification aux clients", it: "Le sanzioni normative, l'interdizione dalla carica di dirigente e l'obbligo di notifica ai clienti", es: "Las multas regulatorias, la prohibición de ejercer como directivo y el deber de notificación a los clientes", pl: "Kary regulacyjne, zakaz pełnienia funkcji kierowniczej oraz obowiązek powiadamiania klientów", cs: "Regulatorní pokuty, zákaz výkonu funkce manažera a oznamovací povinnost vůči zákazníkům", pt: "Coimas regulamentares, a proibição de exercício de funções de gestão e o dever de notificação aos clientes", ro: "Amenzile de reglementare, interdicția pentru manager și obligația de notificare a clienților" },
        { en: "Legal costs, forensic investigation, and incident response", de: "Rechtskosten, forensische Untersuchung und Vorfallreaktion", nl: "Juridische kosten, forensisch onderzoek en incidentrespons", fr: "Les frais juridiques, l'investigation forensique et la réponse à l'incident", it: "I costi legali, l'indagine forense e la risposta agli incidenti", es: "Los costes legales, la investigación forense y la respuesta a incidentes", pl: "Koszty prawne, dochodzenie śledcze i reagowanie na incydenty", cs: "Právní náklady, forenzní šetření a reakci na incidenty", pt: "Custos jurídicos, investigação forense e resposta a incidentes", ro: "Costurile juridice, investigația criminalistică și răspunsul la incidente" },
        { en: "Staff turnover, supply chain disruption, and media coverage", de: "Personalfluktuation, Lieferkettenunterbrechung und Medienberichterstattung", nl: "Personeelsverloop, verstoring van de toeleveringsketen en media-aandacht", fr: "La rotation du personnel, la perturbation de la chaîne d'approvisionnement et la couverture médiatique", it: "Il turnover del personale, l'interruzione della catena di fornitura e la copertura mediatica", es: "La rotación de personal, la interrupción de la cadena de suministro y la cobertura mediática", pl: "Rotacja personelu, zakłócenie łańcucha dostaw i rozgłos medialny", cs: "Fluktuaci zaměstnanců, narušení dodavatelského řetězce a mediální pozornost", pt: "Rotação de pessoal, perturbação da cadeia de abastecimento e cobertura mediática", ro: "Fluctuația de personal, perturbarea lanțului de aprovizionare și acoperirea mediatică" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Insurance does not remove regulatory fines under Article 32, the manager ban under Article 34, or the customer notification duty under Article 36.",
        de: "Versicherung beseitigt weder regulatorische Bußgelder gemäß Artikel 32, noch das Geschäftsführungsverbot gemäß Artikel 34, noch die Kundenbenachrichtigungspflicht gemäß Artikel 36.",
        nl: "Verzekering neemt regulatoire boetes op grond van artikel 32, het beheerdersverbod op grond van artikel 34 en de klantmeldingsplicht op grond van artikel 36 niet weg.",
        fr: "L'assurance ne supprime pas les amendes réglementaires au titre de l'article 32, l'interdiction de gérer au titre de l'article 34, ni l'obligation de notification aux clients au titre de l'article 36.",
        it: "L'assicurazione non elimina le sanzioni normative ai sensi dell'articolo 32, l'interdizione dalla carica di dirigente ai sensi dell'articolo 34, né l'obbligo di notifica ai clienti ai sensi dell'articolo 36.",
        es: "El seguro no elimina las multas regulatorias con arreglo al artículo 32, la prohibición de ejercer como directivo con arreglo al artículo 34, ni el deber de notificación a los clientes con arreglo al artículo 36.",
        pl: "Ubezpieczenie nie usuwa kar regulacyjnych na mocy artykułu 32, zakazu pełnienia funkcji kierowniczej na mocy artykułu 34 ani obowiązku powiadamiania klientów na mocy artykułu 36.",
        cs: "Pojištění neodstraní regulatorní pokuty podle článku 32, zákaz výkonu funkce manažera podle článku 34 ani oznamovací povinnost vůči zákazníkům podle článku 36.",
        pt: "O seguro não elimina as coimas regulamentares ao abrigo do artigo 32, a proibição de exercício de funções de gestão ao abrigo do artigo 34 nem o dever de notificação aos clientes ao abrigo do artigo 36.",
        ro: "Asigurarea nu elimină amenzile de reglementare prevăzute la articolul 32, interdicția pentru manager prevăzută la articolul 34 sau obligația de notificare a clienților prevăzută la articolul 36.",
      },
    },
    {
      id: "4.1.4",
      question: {
        en: "Why did Zurich Insurance refuse the Mondelez claim after the NotPetya attack?",
        de: "Warum hat Zurich Insurance den Anspruch von Mondelez nach dem NotPetya-Angriff abgelehnt?",
        nl: "Waarom weigerde Zurich Insurance de claim van Mondelez na de NotPetya-aanval?",
        fr: "Pourquoi Zurich Insurance a-t-il refusé la demande d'indemnisation de Mondelez après l'attaque NotPetya ?",
        it: "Perché Zurich Insurance ha rifiutato la richiesta di indennizzo di Mondelez dopo l'attacco NotPetya?",
        es: "¿Por qué rechazó Zurich Insurance la reclamación de Mondelez tras el ataque NotPetya?",
        pl: "Dlaczego Zurich Insurance odmówił roszczenia Mondelez po ataku NotPetya?",
        cs: "Proč Zurich Insurance odmítla nárok společnosti Mondelez po útoku NotPetya?",
        pt: "Por que razão a Zurich Insurance recusou a reclamação da Mondelez após o ataque NotPetya?",
        ro: "De ce a refuzat Zurich Insurance cererea Mondelez după atacul NotPetya?",
      },
      options: [
        { en: "Mondelez had not paid its premium", de: "Mondelez hatte seine Prämie nicht bezahlt", nl: "Mondelez had zijn premie niet betaald", fr: "Mondelez n'avait pas payé sa prime", it: "Mondelez non aveva pagato il premio", es: "Mondelez no había pagado su prima", pl: "Mondelez nie zapłacił składki", cs: "Mondelez nezaplatila pojistné", pt: "A Mondelez não tinha pago o prémio", ro: "Mondelez nu își plătise prima" },
        { en: "Zurich argued NotPetya was an act of war", de: "Zurich argumentierte, NotPetya sei ein Kriegsakt gewesen", nl: "Zurich betoogde dat NotPetya een oorlogsdaad was", fr: "Zurich a soutenu que NotPetya était un acte de guerre", it: "Zurich ha sostenuto che NotPetya fosse un atto di guerra", es: "Zurich argumentó que NotPetya fue un acto de guerra", pl: "Zurich argumentował, że NotPetya był aktem wojny", cs: "Zurich argumentovala, že NotPetya byl válečným aktem", pt: "A Zurich alegou que o NotPetya foi um ato de guerra", ro: "Zurich a argumentat că NotPetya a fost un act de război" },
        { en: "The policy had expired before the attack", de: "Die Police war vor dem Angriff abgelaufen", nl: "De polis was vóór de aanval verlopen", fr: "La police avait expiré avant l'attaque", it: "La polizza era scaduta prima dell'attacco", es: "La póliza había caducado antes del ataque", pl: "Polisa wygasła przed atakiem", cs: "Pojistka před útokem vypršela", pt: "A apólice tinha caducado antes do ataque", ro: "Polița expirase înainte de atac" },
        { en: "The damages exceeded the policy limit", de: "Die Schäden überstiegen die Deckungssumme", nl: "De schade overschreed het polislimiet", fr: "Les dommages dépassaient le plafond de la police", it: "I danni superavano il massimale della polizza", es: "Los daños superaban el límite de la póliza", pl: "Szkody przekroczyły limit polisy", cs: "Škody přesáhly limit pojistky", pt: "Os danos excederam o limite da apólice", ro: "Daunele au depășit plafonul poliței" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Zurich refused the claim, arguing NotPetya was an act of war - a single exclusion clause decided the outcome of a roughly one hundred million dollar claim.",
        de: "Zurich lehnte den Anspruch ab und argumentierte, NotPetya sei ein Kriegsakt gewesen - eine einzige Ausschlussklausel entschied über den Ausgang eines Anspruchs von rund hundert Millionen Dollar.",
        nl: "Zurich weigerde de claim en betoogde dat NotPetya een oorlogsdaad was - één enkele uitsluitingsclausule bepaalde de uitkomst van een claim van ongeveer honderd miljoen dollar.",
        fr: "Zurich a refusé la demande en soutenant que NotPetya était un acte de guerre - une seule clause d'exclusion a décidé de l'issue d'une demande d'environ cent millions de dollars.",
        it: "Zurich ha rifiutato la richiesta sostenendo che NotPetya fosse un atto di guerra - un'unica clausola di esclusione ha deciso l'esito di una richiesta di circa cento milioni di dollari.",
        es: "Zurich rechazó la reclamación argumentando que NotPetya fue un acto de guerra: una sola cláusula de exclusión decidió el desenlace de una reclamación de unos cien millones de dólares.",
        pl: "Zurich odmówił roszczenia, argumentując, że NotPetya był aktem wojny - pojedyncza klauzula wyłączająca zadecydowała o losie roszczenia o wartości około stu milionów dolarów.",
        cs: "Zurich nárok odmítla s argumentem, že NotPetya byl válečným aktem. O výsledku nároku ve výši zhruba sto milionů dolarů rozhodlo jediné ustanovení o výluce.",
        pt: "A Zurich recusou a reclamação, alegando que o NotPetya foi um ato de guerra. Uma única cláusula de exclusão decidiu o desfecho de uma reclamação de cerca de cem milhões de dólares.",
        ro: "Zurich a refuzat cererea, argumentând că NotPetya a fost un act de război. O singură clauză de excludere a decis soarta unei cereri de aproximativ o sută de milioane de dolari.",
      },
    },
  ],
});

export default quiz;
