import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "4.1",
  passingScore: 75,
  questions: [
    {
      id: "4.1.1",
      question: {
        en: "Does Article 21 of the NIS2 Directive list insurance as one of the ten required measures?",
        de: "Listet Artikel 21 der NIS2-Richtlinie Versicherung als eine der zehn geforderten Maßnahmen auf?",
        nl: "Vermeldt artikel 21 van de NIS2-richtlijn verzekering als een van de tien vereiste maatregelen?",
        fr: "L'article 21 de la directive NIS2 mentionne-t-il l'assurance comme l'une des dix mesures requises ?",
        it: "L'articolo 21 della direttiva NIS2 elenca l'assicurazione tra le dieci misure richieste?",
        es: "¿Incluye el artículo 21 de la Directiva NIS2 el seguro como una de las diez medidas requeridas?",
        pl: "Czy artykuł 21 dyrektywy NIS2 wymienia ubezpieczenie jako jeden z dziesięciu wymaganych środków?",
      },
      options: [
        { en: "Yes, insurance is listed as the tenth measure", de: "Ja, Versicherung ist als zehnte Maßnahme aufgeführt", nl: "Ja, verzekering staat vermeld als de tiende maatregel", fr: "Oui, l'assurance figure comme la dixième mesure", it: "Sì, l'assicurazione è elencata come decima misura", es: "Sí, el seguro figura como la décima medida", pl: "Tak, ubezpieczenie jest wymienione jako dziesiąty środek" },
        { en: "No, the word insurance does not appear in the ten measures", de: "Nein, das Wort Versicherung kommt in den zehn Maßnahmen nicht vor", nl: "Nee, het woord verzekering komt niet voor in de tien maatregelen", fr: "Non, le mot assurance n'apparaît pas dans les dix mesures", it: "No, la parola assicurazione non compare nelle dieci misure", es: "No, la palabra seguro no aparece en las diez medidas", pl: "Nie, słowo ubezpieczenie nie pojawia się wśród dziesięciu środków" },
        { en: "Insurance is listed as an optional additional measure", de: "Versicherung ist als optionale zusätzliche Maßnahme aufgeführt", nl: "Verzekering staat vermeld als een optionele aanvullende maatregel", fr: "L'assurance figure comme une mesure supplémentaire facultative", it: "L'assicurazione è elencata come misura aggiuntiva facoltativa", es: "El seguro figura como una medida adicional opcional", pl: "Ubezpieczenie jest wymienione jako opcjonalny środek dodatkowy" },
        { en: "Yes, but only for Essential entities", de: "Ja, aber nur für wesentliche Einrichtungen", nl: "Ja, maar alleen voor essentiële entiteiten", fr: "Oui, mais uniquement pour les entités essentielles", it: "Sì, ma solo per i soggetti essenziali", es: "Sí, pero solo para las entidades esenciales", pl: "Tak, ale tylko dla podmiotów kluczowych" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 21 lists ten measures you must have in place. Nowhere in those ten measures does the word 'insurance' appear.",
        de: "Artikel 21 listet zehn Maßnahmen auf, die Sie umsetzen müssen. In keiner dieser zehn Maßnahmen kommt das Wort 'Versicherung' vor.",
        nl: "Artikel 21 bevat een lijst van tien maatregelen die u moet hebben geïmplementeerd. Nergens in die tien maatregelen komt het woord 'verzekering' voor.",
        fr: "L'article 21 énumère dix mesures que vous devez avoir mises en place. Nulle part dans ces dix mesures n'apparaît le mot « assurance ».",
        it: "L'articolo 21 elenca dieci misure che dovete avere in atto. In nessuna di queste dieci misure compare la parola 'assicurazione'.",
        es: "El artículo 21 enumera diez medidas que debe tener implementadas. En ninguna de esas diez medidas aparece la palabra «seguro».",
        pl: "Artykuł 21 wymienia dziesięć środków, które musisz wdrożyć. W żadnym z tych dziesięciu środków nie pojawia się słowo „ubezpieczenie”.",
      },
    },
    {
      id: "4.1.2",
      question: {
        en: "According to the BSI guidance referenced in the lesson, is risk transfer (including insurance) an acceptable treatment for serious risks at NIS2-covered entities?",
        de: "Ist laut der im Kurs referenzierten BSI-Empfehlung Risikotransfer (einschließlich Versicherung) eine akzeptable Behandlung für schwerwiegende Risiken bei NIS2-betroffenen Einrichtungen?",
        nl: "Is risicooverdracht (inclusief verzekering) volgens de BSI-richtlijnen waarnaar in de les wordt verwezen een aanvaardbare behandeling voor ernstige risico's bij NIS2-entiteiten?",
        fr: "Selon les orientations du BSI référencées dans la leçon, le transfert de risque (y compris l'assurance) est-il un traitement acceptable pour les risques graves dans les entités relevant de NIS2 ?",
        it: "Secondo le linee guida del BSI citate nella lezione, il trasferimento del rischio (compresa l'assicurazione) è un trattamento accettabile per i rischi gravi nei soggetti rientranti in NIS2?",
        es: "Según las orientaciones del BSI referenciadas en la lección, ¿es la transferencia del riesgo (incluido el seguro) un tratamiento aceptable para los riesgos graves en las entidades sujetas a NIS2?",
        pl: "Zgodnie z wytycznymi BSI przywołanymi w lekcji, czy transfer ryzyka (w tym ubezpieczenie) jest akceptowalnym sposobem postępowania z poważnymi ryzykami w podmiotach objętych NIS2?",
      },
      options: [
        { en: "Yes, risk transfer is always acceptable", de: "Ja, Risikotransfer ist immer akzeptabel", nl: "Ja, risicooverdracht is altijd aanvaardbaar", fr: "Oui, le transfert de risque est toujours acceptable", it: "Sì, il trasferimento del rischio è sempre accettabile", es: "Sí, la transferencia del riesgo siempre es aceptable", pl: "Tak, transfer ryzyka jest zawsze akceptowalny" },
        { en: "Yes, but only if combined with other controls", de: "Ja, aber nur in Kombination mit anderen Kontrollen", nl: "Ja, maar alleen in combinatie met andere beheersmaatregelen", fr: "Oui, mais uniquement s'il est combiné à d'autres contrôles", it: "Sì, ma solo se combinato con altri controlli", es: "Sí, pero solo si se combina con otros controles", pl: "Tak, ale tylko w połączeniu z innymi kontrolami" },
        { en: "No, the BSI guidance explicitly says risk transfer is not acceptable for serious risks", de: "Nein, die BSI-Empfehlung sagt ausdrücklich, dass Risikotransfer für schwerwiegende Risiken nicht akzeptabel ist", nl: "Nee, de BSI-richtlijnen stellen uitdrukkelijk dat risicooverdracht niet aanvaardbaar is voor ernstige risico's", fr: "Non, les orientations du BSI indiquent explicitement que le transfert de risque n'est pas acceptable pour les risques graves", it: "No, le linee guida del BSI affermano esplicitamente che il trasferimento del rischio non è accettabile per i rischi gravi", es: "No, las orientaciones del BSI dicen explícitamente que la transferencia del riesgo no es aceptable para los riesgos graves", pl: "Nie, wytyczne BSI wyraźnie stwierdzają, że transfer ryzyka nie jest akceptowalny w przypadku poważnych ryzyk" },
        { en: "It depends on the size of the company", de: "Es hängt von der Größe des Unternehmens ab", nl: "Het hangt af van de omvang van het bedrijf", fr: "Cela dépend de la taille de l'entreprise", it: "Dipende dalle dimensioni dell'azienda", es: "Depende del tamaño de la empresa", pl: "To zależy od wielkości firmy" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The BSI guidance explicitly says risk transfer - including insurance - is not an acceptable treatment for serious risks at NIS2-covered entities.",
        de: "Die BSI-Empfehlung sagt ausdrücklich, dass Risikotransfer - einschließlich Versicherung - keine akzeptable Behandlung für schwerwiegende Risiken bei NIS2-betroffenen Einrichtungen ist.",
        nl: "De BSI-richtlijnen stellen uitdrukkelijk dat risicooverdracht - inclusief cyberverzekering - geen aanvaardbare behandeling is voor ernstige risico's bij NIS2-entiteiten.",
        fr: "Les orientations du BSI indiquent explicitement que le transfert de risque - y compris l'assurance - n'est pas un traitement acceptable pour les risques graves dans les entités relevant de NIS2.",
        it: "Le linee guida del BSI affermano esplicitamente che il trasferimento del rischio - compresa l'assicurazione - non è un trattamento accettabile per i rischi gravi nei soggetti rientranti in NIS2.",
        es: "Las orientaciones del BSI dicen explícitamente que la transferencia del riesgo - incluido el seguro - no es un tratamiento aceptable para los riesgos graves en las entidades sujetas a NIS2.",
        pl: "Wytyczne BSI wyraźnie stwierdzają, że transfer ryzyka - w tym ubezpieczenie - nie jest akceptowalnym sposobem postępowania z poważnymi ryzykami w podmiotach objętych NIS2.",
      },
    },
    {
      id: "4.1.3",
      question: {
        en: "Which three consequences does insurance NOT remove according to the lesson?",
        de: "Welche drei Konsequenzen beseitigt Versicherung laut der Lektion NICHT?",
        nl: "Welke drie gevolgen neemt verzekering NIET weg, volgens de les?",
        fr: "Quelles trois conséquences l'assurance ne supprime-t-elle PAS selon la leçon ?",
        it: "Quali tre conseguenze l'assicurazione NON elimina secondo la lezione?",
        es: "¿Qué tres consecuencias NO elimina el seguro según la lección?",
        pl: "Których trzech konsekwencji ubezpieczenie NIE usuwa według lekcji?",
      },
      options: [
        { en: "Business interruption, data loss, and reputational damage", de: "Betriebsunterbrechung, Datenverlust und Reputationsschaden", nl: "Bedrijfsonderbreking, gegevensverlies en reputatieschade", fr: "Interruption d'activité, perte de données et atteinte à la réputation", it: "Interruzione dell'attività, perdita di dati e danno reputazionale", es: "Interrupción del negocio, pérdida de datos y daño reputacional", pl: "Przerwa w działalności, utrata danych i szkoda wizerunkowa" },
        { en: "Regulatory fines, the manager ban, and the customer notification duty", de: "Regulatorische Bußgelder, das Geschäftsführungsverbot und die Kundenbenachrichtigungspflicht", nl: "Regulatoire boetes, het beheerdersverbod en de klantmeldingsplicht", fr: "Les amendes réglementaires, l'interdiction de gérer, et l'obligation de notification aux clients", it: "Le sanzioni normative, l'interdizione dalla carica di dirigente e l'obbligo di notifica ai clienti", es: "Las multas regulatorias, la prohibición de ejercer como directivo y el deber de notificación a los clientes", pl: "Kary regulacyjne, zakaz pełnienia funkcji kierowniczej oraz obowiązek powiadamiania klientów" },
        { en: "Legal costs, forensic investigation, and incident response", de: "Rechtskosten, forensische Untersuchung und Vorfallreaktion", nl: "Juridische kosten, forensisch onderzoek en incidentrespons", fr: "Les frais juridiques, l'investigation forensique et la réponse à l'incident", it: "I costi legali, l'indagine forense e la risposta agli incidenti", es: "Los costes legales, la investigación forense y la respuesta a incidentes", pl: "Koszty prawne, dochodzenie śledcze i reagowanie na incydenty" },
        { en: "Staff turnover, supply chain disruption, and media coverage", de: "Personalfluktuation, Lieferkettenunterbrechung und Medienberichterstattung", nl: "Personeelsverloop, verstoring van de toeleveringsketen en media-aandacht", fr: "La rotation du personnel, la perturbation de la chaîne d'approvisionnement et la couverture médiatique", it: "Il turnover del personale, l'interruzione della catena di fornitura e la copertura mediatica", es: "La rotación de personal, la interrupción de la cadena de suministro y la cobertura mediática", pl: "Rotacja personelu, zakłócenie łańcucha dostaw i rozgłos medialny" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Insurance does not remove regulatory fines under Article 32, the manager ban under Article 34, or the customer notification duty under Article 36.",
        de: "Versicherung beseitigt weder regulatorische Bußgelder gemäß Artikel 32, noch das Geschäftsführungsverbot gemäß Artikel 34, noch die Kundenbenachrichtigungspflicht gemäß Artikel 36.",
        nl: "Verzekering neemt regulatoire boetes op grond van artikel 32, het beheerdersverbod op grond van artikel 34 en de klantmeldingsplicht op grond van artikel 36 niet weg.",
        fr: "L'assurance ne supprime pas les amendes réglementaires au titre de l'article 32, l'interdiction de gérer au titre de l'article 34, ni l'obligation de notification aux clients au titre de l'article 36.",
        it: "L'assicurazione non elimina le sanzioni normative ai sensi dell'articolo 32, l'interdizione dalla carica di dirigente ai sensi dell'articolo 34, né l'obbligo di notifica ai clienti ai sensi dell'articolo 36.",
        es: "El seguro no elimina las multas regulatorias con arreglo al artículo 32, la prohibición de ejercer como directivo con arreglo al artículo 34, ni el deber de notificación a los clientes con arreglo al artículo 36.",
        pl: "Ubezpieczenie nie usuwa kar regulacyjnych na mocy artykułu 32, zakazu pełnienia funkcji kierowniczej na mocy artykułu 34 ani obowiązku powiadamiania klientów na mocy artykułu 36.",
      },
    },
    {
      id: "4.1.4",
      question: {
        en: "Why did Zurich Insurance refuse the Mondelez claim after the NotPetya attack?",
        de: "Warum hat Zurich Insurance den Anspruch von Mondelez nach dem NotPetya-Angriff abgelehnt?",
        nl: "Waarom weigerde Zurich Insurance de claim van Mondelez na de NotPetya-aanval?",
        fr: "Pourquoi Zurich Insurance a-t-il refusé la demande d'indemnisation de Mondelez après l'attaque NotPetya ?",
        it: "Perché Zurich Insurance ha rifiutato la richiesta di indennizzo di Mondelez dopo l'attacco NotPetya?",
        es: "¿Por qué rechazó Zurich Insurance la reclamación de Mondelez tras el ataque NotPetya?",
        pl: "Dlaczego Zurich Insurance odmówił roszczenia Mondelez po ataku NotPetya?",
      },
      options: [
        { en: "Mondelez had not paid its premium", de: "Mondelez hatte seine Prämie nicht bezahlt", nl: "Mondelez had zijn premie niet betaald", fr: "Mondelez n'avait pas payé sa prime", it: "Mondelez non aveva pagato il premio", es: "Mondelez no había pagado su prima", pl: "Mondelez nie zapłacił składki" },
        { en: "Zurich argued NotPetya was an act of war", de: "Zurich argumentierte, NotPetya sei ein Kriegsakt gewesen", nl: "Zurich betoogde dat NotPetya een oorlogsdaad was", fr: "Zurich a soutenu que NotPetya était un acte de guerre", it: "Zurich ha sostenuto che NotPetya fosse un atto di guerra", es: "Zurich argumentó que NotPetya fue un acto de guerra", pl: "Zurich argumentował, że NotPetya był aktem wojny" },
        { en: "The policy had expired before the attack", de: "Die Police war vor dem Angriff abgelaufen", nl: "De polis was vóór de aanval verlopen", fr: "La police avait expiré avant l'attaque", it: "La polizza era scaduta prima dell'attacco", es: "La póliza había caducado antes del ataque", pl: "Polisa wygasła przed atakiem" },
        { en: "The damages exceeded the policy limit", de: "Die Schäden überstiegen die Deckungssumme", nl: "De schade overschreed het polislimiet", fr: "Les dommages dépassaient le plafond de la police", it: "I danni superavano il massimale della polizza", es: "Los daños superaban el límite de la póliza", pl: "Szkody przekroczyły limit polisy" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Zurich refused the claim, arguing NotPetya was an act of war - a single exclusion clause decided the outcome of a roughly one hundred million dollar claim.",
        de: "Zurich lehnte den Anspruch ab und argumentierte, NotPetya sei ein Kriegsakt gewesen - eine einzige Ausschlussklausel entschied über den Ausgang eines Anspruchs von rund hundert Millionen Dollar.",
        nl: "Zurich weigerde de claim en betoogde dat NotPetya een oorlogsdaad was - één enkele uitsluitingsclausule bepaalde de uitkomst van een claim van ongeveer honderd miljoen dollar.",
        fr: "Zurich a refusé la demande en soutenant que NotPetya était un acte de guerre - une seule clause d'exclusion a décidé de l'issue d'une demande d'environ cent millions de dollars.",
        it: "Zurich ha rifiutato la richiesta sostenendo che NotPetya fosse un atto di guerra - un'unica clausola di esclusione ha deciso l'esito di una richiesta di circa cento milioni di dollari.",
        es: "Zurich rechazó la reclamación argumentando que NotPetya fue un acto de guerra: una sola cláusula de exclusión decidió el desenlace de una reclamación de unos cien millones de dólares.",
        pl: "Zurich odmówił roszczenia, argumentując, że NotPetya był aktem wojny - pojedyncza klauzula wyłączająca zadecydowała o losie roszczenia o wartości około stu milionów dolarów.",
      },
    },
  ],
});

export default quiz;
