import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "4.5",
  passingScore: 75,
  questions: [
    {
      id: "4.5.1",
      question: {
        en: "What is the correct order for communicating during a crisis according to the lesson?",
        de: "Welche Reihenfolge der Kommunikation während einer Krise ist laut der Lektion korrekt?",
        nl: "Wat is de juiste volgorde van communicatie tijdens een crisis volgens de les?",
        fr: "Quel est l'ordre correct de communication pendant une crise selon la leçon ?",
        it: "Qual è l'ordine corretto di comunicazione durante una crisi secondo la lezione?",
        es: "¿Cuál es el orden correcto de comunicación durante una crisis según la lección?",
        pl: "Jaka jest prawidłowa kolejność komunikacji podczas kryzysu według lekcji?",
        cs: "Jaké je podle lekce správné pořadí komunikace během krize?",
        pt: "Qual é a ordem correta de comunicação durante uma crise segundo a lição?",
        ro: "Care este ordinea corectă de comunicare în timpul unei crize potrivit lecției?",
      },
      options: [
        { en: "Public first, then regulator, then customers, then internal", de: "Öffentlichkeit zuerst, dann Aufsichtsbehörde, dann Kunden, dann intern", nl: "Publiek eerst, dan toezichthouder, dan klanten, dan intern", fr: "Le public d'abord, puis l'autorité de régulation, puis les clients, puis l'interne", it: "Prima il pubblico, poi l'autorità di regolamentazione, poi i clienti, poi l'interno", es: "Primero el público, luego el regulador, luego los clientes, luego lo interno", pl: "Najpierw opinia publiczna, potem organ nadzoru, potem klienci, potem wewnętrznie", cs: "Nejprve veřejnost, pak regulační orgán, pak zákazníci, pak interně", pt: "Primeiro o público, depois a autoridade reguladora, depois os clientes, depois o interno", ro: "Mai întâi publicul, apoi autoritatea de reglementare, apoi clienții, apoi intern" },
        { en: "Internal first, regulator second, customers third, public fourth", de: "Intern zuerst, Aufsichtsbehörde zweitens, Kunden drittens, Öffentlichkeit viertens", nl: "Intern eerst, toezichthouder tweede, klanten derde, publiek vierde", fr: "L'interne d'abord, l'autorité de régulation en deuxième, les clients en troisième, le public en quatrième", it: "Prima l'interno, l'autorità di regolamentazione per seconda, i clienti per terzi, il pubblico per quarto", es: "Primero lo interno, el regulador segundo, los clientes tercero, el público cuarto", pl: "Najpierw wewnętrznie, organ nadzoru jako drugi, klienci jako trzeci, opinia publiczna jako czwarta", cs: "Nejprve interně, jako druhý regulační orgán, jako třetí zákazníci, jako čtvrtá veřejnost", pt: "Primeiro o interno, em segundo a autoridade reguladora, em terceiro os clientes, em quarto o público", ro: "Mai întâi intern, al doilea autoritatea de reglementare, al treilea clienții, al patrulea publicul" },
        { en: "Regulator first, then public, then internal, then customers", de: "Aufsichtsbehörde zuerst, dann Öffentlichkeit, dann intern, dann Kunden", nl: "Toezichthouder eerst, dan publiek, dan intern, dan klanten", fr: "L'autorité de régulation d'abord, puis le public, puis l'interne, puis les clients", it: "Prima l'autorità di regolamentazione, poi il pubblico, poi l'interno, poi i clienti", es: "Primero el regulador, luego el público, luego lo interno, luego los clientes", pl: "Najpierw organ nadzoru, potem opinia publiczna, potem wewnętrznie, potem klienci", cs: "Nejprve regulační orgán, pak veřejnost, pak interně, pak zákazníci", pt: "Primeiro a autoridade reguladora, depois o público, depois o interno, depois os clientes", ro: "Mai întâi autoritatea de reglementare, apoi publicul, apoi intern, apoi clienții" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Internal first, regulator second, customers third, public fourth. Mixing the sequence creates legal exposure and a narrative you do not control.",
        de: "Intern zuerst, Aufsichtsbehörde zweitens, Kunden drittens, Öffentlichkeit viertens. Eine vertauschte Reihenfolge schafft rechtliche Angriffspunkte und ein Narrativ, das Sie nicht kontrollieren.",
        nl: "Intern eerst, toezichthouder tweede, klanten derde, publiek vierde. De volgorde omwisselen creëert juridische blootstelling en een verhaal dat u niet beheerst.",
        fr: "L'interne d'abord, l'autorité de régulation en deuxième, les clients en troisième, le public en quatrième. Inverser la séquence crée une exposition juridique et un récit que vous ne contrôlez pas.",
        it: "Prima l'interno, l'autorità di regolamentazione per seconda, i clienti per terzi, il pubblico per quarto. Invertire la sequenza crea esposizione giuridica e una narrazione che non controllate.",
        es: "Primero lo interno, el regulador segundo, los clientes tercero, el público cuarto. Alterar la secuencia crea exposición jurídica y un relato que usted no controla.",
        pl: "Najpierw wewnętrznie, organ nadzoru jako drugi, klienci jako trzeci, opinia publiczna jako czwarta. Zmiana kolejności tworzy ekspozycję prawną i narrację, której nie kontrolujesz.",
        cs: "Nejprve interně, jako druhý regulační orgán, jako třetí zákazníci, jako čtvrtá veřejnost. Zaměnění pořadí vytváří právní expozici a narativ, který nemáte pod kontrolou.",
        pt: "Primeiro o interno, em segundo a autoridade reguladora, em terceiro os clientes, em quarto o público. Trocar a sequência cria exposição jurídica e uma narrativa que não controla.",
        ro: "Mai întâi intern, al doilea autoritatea de reglementare, al treilea clienții, al patrulea publicul. Amestecarea secvenței creează expunere juridică și o narațiune pe care nu o controlați.",
      },
    },
    {
      id: "4.5.2",
      question: {
        en: "What is the purpose of a holding statement issued within two hours?",
        de: "Was ist der Zweck einer Übergangserklärung, die innerhalb von zwei Stunden veröffentlicht wird?",
        nl: "Wat is het doel van een overbruggingsverklaring die binnen twee uur wordt uitgebracht?",
        fr: "Quel est l'objectif d'une déclaration d'attente publiée dans les deux heures ?",
        it: "Qual è lo scopo di una dichiarazione interlocutoria emessa entro due ore?",
        es: "¿Cuál es el propósito de una declaración provisional emitida en dos horas?",
        pl: "Jaki jest cel oświadczenia tymczasowego wydanego w ciągu dwóch godzin?",
        cs: "Jaký je účel předběžného prohlášení vydaného do dvou hodin?",
        pt: "Qual é o objetivo de uma declaração provisória emitida no prazo de duas horas?",
        ro: "Care este scopul unei declarații preliminare emise în termen de două ore?",
      },
      options: [
        { en: "To provide a full technical analysis of the incident", de: "Eine vollständige technische Analyse des Vorfalls bereitzustellen", nl: "Een volledige technische analyse van het incident te geven", fr: "Fournir une analyse technique complète de l'incident", it: "Fornire un'analisi tecnica completa dell'incidente", es: "Proporcionar un análisis técnico completo del incidente", pl: "Dostarczenie pełnej analizy technicznej incydentu", cs: "Poskytnout úplnou technickou analýzu incidentu", pt: "Fornecer uma análise técnica completa do incidente", ro: "Furnizarea unei analize tehnice complete a incidentului" },
        { en: "To acknowledge disruption without speculating on cause or scope, and commit to a specific update time", de: "Die Störung zu bestätigen, ohne über Ursache oder Umfang zu spekulieren, und einen konkreten Aktualisierungszeitpunkt zuzusagen", nl: "De verstoring te bevestigen zonder te speculeren over oorzaak of omvang, en een specifiek updatemoment toe te zeggen", fr: "Reconnaître la perturbation sans spéculer sur la cause ou l'ampleur, et s'engager sur une heure de mise à jour précise", it: "Riconoscere l'interruzione senza speculare su causa o portata, e impegnarsi su un orario di aggiornamento specifico", es: "Reconocer la interrupción sin especular sobre la causa o el alcance, y comprometerse a una hora de actualización específica", pl: "Potwierdzenie zakłócenia bez spekulowania na temat przyczyny lub zakresu oraz zobowiązanie się do konkretnego terminu aktualizacji", cs: "Potvrdit narušení bez spekulací o příčině nebo rozsahu a zavázat se ke konkrétnímu času aktualizace", pt: "Reconhecer a perturbação sem especular sobre a causa ou o âmbito, e comprometer-se com uma hora específica de atualização", ro: "Recunoașterea perturbării fără a specula asupra cauzei sau a amplorii și angajarea la o oră specifică de actualizare" },
        { en: "To assign blame and identify the attacker", de: "Schuld zuzuweisen und den Angreifer zu identifizieren", nl: "Schuld toe te wijzen en de aanvaller te identificeren", fr: "Attribuer la responsabilité et identifier l'attaquant", it: "Attribuire la colpa e identificare l'attaccante", es: "Asignar la culpa e identificar al atacante", pl: "Przypisanie winy i zidentyfikowanie atakującego", cs: "Určit viníka a identifikovat útočníka", pt: "Atribuir culpas e identificar o atacante", ro: "Atribuirea vinovăției și identificarea atacatorului" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A holding statement acknowledges disruption without speculating on cause or scope, and commits to a specific update time. Silence in the first two hours is when journalists write the story for you.",
        de: "Eine Übergangserklärung bestätigt die Störung, ohne über Ursache oder Umfang zu spekulieren, und sagt einen konkreten Aktualisierungszeitpunkt zu. Schweigen in den ersten zwei Stunden ist der Moment, in dem Journalisten die Geschichte für Sie schreiben.",
        nl: "Een overbruggingsverklaring bevestigt de verstoring zonder te speculeren over oorzaak of omvang, en zegt een specifiek updatemoment toe. Stilte in de eerste twee uur is het moment waarop journalisten het verhaal voor u schrijven.",
        fr: "Une déclaration d'attente reconnaît la perturbation sans spéculer sur la cause ou l'ampleur, et s'engage sur une heure de mise à jour précise. Le silence dans les deux premières heures est le moment où les journalistes écrivent l'histoire à votre place.",
        it: "Una dichiarazione interlocutoria riconosce l'interruzione senza speculare su causa o portata, e si impegna su un orario di aggiornamento specifico. Il silenzio nelle prime due ore è il momento in cui i giornalisti scrivono la storia al posto vostro.",
        es: "Una declaración provisional reconoce la interrupción sin especular sobre la causa o el alcance, y se compromete a una hora de actualización específica. El silencio en las primeras dos horas es cuando los periodistas escriben la historia por usted.",
        pl: "Oświadczenie tymczasowe potwierdza zakłócenie bez spekulowania na temat przyczyny lub zakresu i zobowiązuje się do konkretnego terminu aktualizacji. Milczenie w pierwszych dwóch godzinach to moment, gdy dziennikarze piszą historię za Ciebie.",
        cs: "Předběžné prohlášení potvrzuje narušení bez spekulací o příčině nebo rozsahu a zavazuje se ke konkrétnímu času aktualizace. Mlčení v prvních dvou hodinách je doba, kdy příběh za vás napíší novináři.",
        pt: "Uma declaração provisória reconhece a perturbação sem especular sobre a causa ou o âmbito, e compromete-se com uma hora específica de atualização. O silêncio nas primeiras duas horas é quando os jornalistas escrevem a história por si.",
        ro: "O declarație preliminară recunoaște perturbarea fără a specula asupra cauzei sau a amplorii și se angajează la o oră specifică de actualizare. Tăcerea în primele două ore este momentul în care jurnaliștii scriu povestea în locul dumneavoastră.",
      },
    },
    {
      id: "4.5.3",
      question: {
        en: "Within what timeframe must the regulator be notified of a significant incident under the NIS2 Directive?",
        de: "Innerhalb welches Zeitraums muss die Aufsichtsbehörde über einen erheblichen Vorfall gemäß der NIS2-Richtlinie benachrichtigt werden?",
        nl: "Binnen welke termijn moet de toezichthouder worden geïnformeerd over een significant incident op grond van de NIS2-richtlijn?",
        fr: "Dans quel délai l'autorité de régulation doit-elle être notifiée d'un incident important au titre de la directive NIS2 ?",
        it: "Entro quale termine deve essere notificato all'autorità di regolamentazione un incidente significativo ai sensi della direttiva NIS2?",
        es: "¿En qué plazo debe notificarse al regulador un incidente significativo con arreglo a la Directiva NIS2?",
        pl: "W jakim terminie należy powiadomić organ nadzoru o poważnym incydencie na mocy dyrektywy NIS2?",
        cs: "V jaké lhůtě musí být regulační orgán informován o významném incidentu podle směrnice NIS2?",
        pt: "Em que prazo tem a autoridade reguladora de ser notificada de um incidente significativo ao abrigo da Diretiva NIS2?",
        ro: "În ce termen trebuie notificată autoritatea de reglementare cu privire la un incident semnificativ în temeiul Directivei NIS2?",
      },
      options: [
        { en: "Within forty-eight hours", de: "Innerhalb von achtundvierzig Stunden", nl: "Binnen achtenveertig uur", fr: "Dans les quarante-huit heures", it: "Entro quarantotto ore", es: "En cuarenta y ocho horas", pl: "W ciągu czterdziestu ośmiu godzin", cs: "Do čtyřiceti osmi hodin", pt: "No prazo de quarenta e oito horas", ro: "În termen de patruzeci și opt de ore" },
        { en: "Within twenty-four hours", de: "Innerhalb von vierundzwanzig Stunden", nl: "Binnen vierentwintig uur", fr: "Dans les vingt-quatre heures", it: "Entro ventiquattro ore", es: "En veinticuatro horas", pl: "W ciągu dwudziestu czterech godzin", cs: "Do dvaceti čtyř hodin", pt: "No prazo de vinte e quatro horas", ro: "În termen de douăzeci și patru de ore" },
        { en: "Within seventy-two hours", de: "Innerhalb von zweiundsiebzig Stunden", nl: "Binnen tweeënzeventig uur", fr: "Dans les soixante-douze heures", it: "Entro settantadue ore", es: "En setenta y dos horas", pl: "W ciągu siedemdziesięciu dwóch godzin", cs: "Do sedmdesáti dvou hodin", pt: "No prazo de setenta e duas horas", ro: "În termen de șaptezeci și două de ore" },
        { en: "Within one week", de: "Innerhalb einer Woche", nl: "Binnen één week", fr: "Dans un délai d'une semaine", it: "Entro una settimana", es: "En una semana", pl: "W ciągu jednego tygodnia", cs: "Do jednoho týdne", pt: "No prazo de uma semana", ro: "În termen de o săptămână" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The regulator must be notified within twenty-four hours. You must then commit to updating within seventy-two hours.",
        de: "Die Aufsichtsbehörde muss innerhalb von vierundzwanzig Stunden benachrichtigt werden. Danach müssen Sie sich verpflichten, innerhalb von zweiundsiebzig Stunden ein Update zu liefern.",
        nl: "De toezichthouder moet binnen vierentwintig uur worden geïnformeerd. U moet vervolgens toezeggen binnen tweeënzeventig uur een update te geven.",
        fr: "L'autorité de régulation doit être notifiée dans les vingt-quatre heures. Vous devez ensuite vous engager à fournir une mise à jour dans les soixante-douze heures.",
        it: "L'autorità di regolamentazione deve essere notificata entro ventiquattro ore. Dovete poi impegnarvi a fornire un aggiornamento entro settantadue ore.",
        es: "El regulador debe ser notificado en veinticuatro horas. Después debe comprometerse a actualizar en setenta y dos horas.",
        pl: "Organ nadzoru musi zostać powiadomiony w ciągu dwudziestu czterech godzin. Następnie musisz zobowiązać się do przekazania aktualizacji w ciągu siedemdziesięciu dwóch godzin.",
        cs: "Regulační orgán musí být informován do dvaceti čtyř hodin. Poté se musíte zavázat k aktualizaci do sedmdesáti dvou hodin.",
        pt: "A autoridade reguladora tem de ser notificada no prazo de vinte e quatro horas. Deve depois comprometer-se a atualizar no prazo de setenta e duas horas.",
        ro: "Autoritatea de reglementare trebuie notificată în termen de douăzeci și patru de ore. Apoi trebuie să vă angajați la o actualizare în termen de șaptezeci și două de ore.",
      },
    },
    {
      id: "4.5.4",
      question: {
        en: "What is the CEO's typical role in crisis communication according to the Maersk case study?",
        de: "Welche Rolle hat der CEO laut der Maersk-Fallstudie typischerweise in der Krisenkommunikation?",
        nl: "Wat is de typische rol van de CEO in crisiscommunicatie volgens de casus Maersk?",
        fr: "Quel est le rôle typique du CEO dans la communication de crise selon l'étude de cas Maersk ?",
        it: "Qual è il ruolo tipico del CEO nella comunicazione di crisi secondo il caso di studio Maersk?",
        es: "¿Cuál es el papel típico del CEO en la comunicación de crisis según el caso práctico de Maersk?",
        pl: "Jaka jest typowa rola CEO w komunikacji kryzysowej według studium przypadku Maersk?",
        cs: "Jaká je podle případové studie Maersk obvyklá role generálního ředitele v krizové komunikaci?",
        pt: "Qual é o papel típico do diretor executivo na comunicação de crise segundo o estudo de caso da Maersk?",
        ro: "Care este rolul tipic al directorului general în comunicarea de criză potrivit studiului de caz Maersk?",
      },
      options: [
        { en: "The CEO is always the primary spokesperson on television", de: "Der CEO ist immer der primäre Sprecher im Fernsehen", nl: "De CEO is altijd de primaire woordvoerder op televisie", fr: "Le CEO est toujours le principal porte-parole à la télévision", it: "Il CEO è sempre il portavoce principale in televisione", es: "El CEO es siempre el portavoz principal en televisión", pl: "CEO zawsze jest głównym rzecznikiem w telewizji", cs: "Generální ředitel je vždy hlavním mluvčím v televizi", pt: "O diretor executivo é sempre o porta-voz principal na televisão", ro: "Directorul general este întotdeauna principalul purtător de cuvânt la televiziune" },
        { en: "The CEO rarely speaks publicly but is always the final approver of every external statement", de: "Der CEO tritt selten öffentlich auf, ist aber immer der endgültige Freigeber jeder externen Stellungnahme", nl: "De CEO treedt zelden publiekelijk op maar is altijd de uiteindelijke goedkeurder van elke externe verklaring", fr: "Le CEO s'exprime rarement publiquement mais est toujours l'approbateur final de chaque déclaration externe", it: "Il CEO parla raramente in pubblico ma è sempre l'approvatore finale di ogni dichiarazione esterna", es: "El CEO rara vez habla en público pero siempre es el aprobador final de cada declaración externa", pl: "CEO rzadko zabiera głos publicznie, ale zawsze jest ostatecznym zatwierdzającym każde zewnętrzne oświadczenie", cs: "Generální ředitel zřídka vystupuje veřejně, ale je vždy konečným schvalovatelem každého externího prohlášení", pt: "O diretor executivo raramente fala publicamente, mas é sempre o aprovador final de cada declaração externa", ro: "Directorul general vorbește rareori în public, dar este întotdeauna aprobatorul final al fiecărei declarații externe" },
        { en: "The CEO delegates all communication to the legal department", de: "Der CEO delegiert die gesamte Kommunikation an die Rechtsabteilung", nl: "De CEO delegeert alle communicatie aan de juridische afdeling", fr: "Le CEO délègue toute la communication au service juridique", it: "Il CEO delega tutta la comunicazione al reparto legale", es: "El CEO delega toda la comunicación en el departamento jurídico", pl: "CEO deleguje całą komunikację na dział prawny", cs: "Generální ředitel deleguje veškerou komunikaci na právní oddělení", pt: "O diretor executivo delega toda a comunicação no departamento jurídico", ro: "Directorul general deleagă toată comunicarea departamentului juridic" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The CEO is typically not the spokesperson on television but is always the final approver of every external statement. Every statement passes legal review before release.",
        de: "Der CEO ist typischerweise nicht der Sprecher im Fernsehen, ist aber immer der endgültige Freigeber jeder externen Stellungnahme. Jede Stellungnahme durchläuft eine rechtliche Prüfung vor der Veröffentlichung.",
        nl: "De CEO is doorgaans niet de woordvoerder op televisie maar is altijd de uiteindelijke goedkeurder van elke externe verklaring. Elke verklaring doorloopt een juridische beoordeling vóór publicatie.",
        fr: "Le CEO n'est généralement pas le porte-parole à la télévision mais est toujours l'approbateur final de chaque déclaration externe. Chaque déclaration passe une revue juridique avant publication.",
        it: "Il CEO tipicamente non è il portavoce in televisione ma è sempre l'approvatore finale di ogni dichiarazione esterna. Ogni dichiarazione passa una revisione legale prima della diffusione.",
        es: "El CEO normalmente no es el portavoz en televisión pero siempre es el aprobador final de cada declaración externa. Cada declaración pasa una revisión jurídica antes de su publicación.",
        pl: "CEO zazwyczaj nie jest rzecznikiem w telewizji, ale zawsze jest ostatecznym zatwierdzającym każde zewnętrzne oświadczenie. Każde oświadczenie przechodzi przegląd prawny przed publikacją.",
        cs: "Generální ředitel obvykle není mluvčím v televizi, ale je vždy konečným schvalovatelem každého externího prohlášení. Každé prohlášení projde před zveřejněním právním přezkumem.",
        pt: "O diretor executivo não é normalmente o porta-voz na televisão, mas é sempre o aprovador final de cada declaração externa. Cada declaração passa por revisão jurídica antes da divulgação.",
        ro: "Directorul general nu este de regulă purtătorul de cuvânt la televiziune, dar este întotdeauna aprobatorul final al fiecărei declarații externe. Fiecare declarație trece printr-o revizuire juridică înainte de publicare.",
      },
    },
  ],
});

export default quiz;
