import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "5.1",
  passingScore: 75,
  questions: [
    {
      id: "5.1.1",
      question: {
        en: "What are the three priorities for the first two weeks according to the 90-day plan?",
        de: "Welche drei Prioritaeten gelten laut dem 90-Tage-Plan für die ersten zwei Wochen?",
        nl: "Wat zijn de drie prioriteiten voor de eerste twee weken volgens het 90-dagenplan?",
        fr: "Quelles sont les trois priorités des deux premières semaines selon le plan de 90 jours ?",
        it: "Quali sono le tre priorità per le prime due settimane secondo il piano di 90 giorni?",
        es: "¿Cuáles son las tres prioridades de las primeras dos semanas según el plan de 90 días?",
        pl: "Jakie są trzy priorytety na pierwsze dwa tygodnie według planu 90-dniowego?",
      },
      options: [
        { en: "Hire a CISO, purchase insurance, and file for an extension", de: "Einen CISO einstellen, Versicherung abschließen und eine Verlaengerung beantragen", nl: "Een CISO aannemen, verzekering afsluiten en een verlenging aanvragen", fr: "Embaucher un CISO, souscrire une assurance et demander une prolongation", it: "Assumere un CISO, stipulare un'assicurazione e richiedere una proroga", es: "Contratar a un CISO, contratar un seguro y solicitar una prórroga", pl: "Zatrudnić CISO, wykupić ubezpieczenie i złożyć wniosek o przedłużenie" },
        { en: "Confirm scoping assessment, register with the BSI, and confirm the CISO reporting line", de: "Betroffenheitsbewertung bestätigten, beim BSI registrieren und die Berichtslinie des CISO bestätigten", nl: "Scope-beoordeling bevestigen, registreren bij de BSI en de rapportagelijn van de CISO bevestigen", fr: "Confirmer l'évaluation du périmètre, s'enregistrer auprès du BSI et confirmer la ligne de reporting du CISO", it: "Confermare la valutazione dell'ambito di applicazione, registrarsi presso il BSI e confermare la linea di reporting del CISO", es: "Confirmar la evaluación del ámbito de aplicación, registrarse ante el BSI y confirmar la línea de reporte del CISO", pl: "Potwierdzić ocenę zakresu, zarejestrować się w BSI i potwierdzić linię raportowania CISO" },
        { en: "Write all eleven policies, run a tabletop exercise, and schedule the management review", de: "Alle elf Richtlinien schreiben, eine Tabletop-Uebung durchführen und die Management-Bewertung planen", nl: "Alle elf beleidslijnen schrijven, een tabletop-oefening uitvoeren en de managementbeoordeling plannen", fr: "Rédiger les onze politiques, mener un exercice sur table et planifier la revue de direction", it: "Redigere tutte e undici le politiche, condurre un'esercitazione teorica e programmare il riesame della direzione", es: "Redactar las once políticas, realizar un ejercicio de simulación y programar la revisión por la dirección", pl: "Napisać wszystkie jedenaście polityk, przeprowadzić ćwiczenie sztabowe i zaplanować przegląd zarządzania" },
        { en: "Purchase cyber insurance, engage an external auditor, and notify customers", de: "Cyberversicherung abschließen, einen externen Auditor beauftragen und Kunden benachrichtigen", nl: "Cyberverzekering afsluiten, een externe auditor inschakelen en klanten informeren", fr: "Souscrire une cyberassurance, engager un auditeur externe et notifier les clients", it: "Stipulare una cyberassicurazione, incaricare un auditor esterno e avvisare i clienti", es: "Contratar un ciberseguro, contratar a un auditor externo y notificar a los clientes", pl: "Wykupić cyberubezpieczenie, zaangażować zewnętrznego audytora i powiadomić klientów" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The first two weeks are about scope, registration, and the CISO reporting line - these are the prerequisites everything else depends on.",
        de: "Die ersten zwei Wochen drehen sich um Betroffenheit, Registrierung und die Berichtslinie des CISO - das sind die Voraussetzungen, von denen alles andere abhaengt.",
        nl: "De eerste twee weken gaan over scope, registratie en de rapportagelijn van de CISO - dat zijn de voorwaarden waarvan alles else afhankelijk is.",
        fr: "Les deux premières semaines portent sur le périmètre, l'enregistrement et la ligne de reporting du CISO - ce sont les conditions préalables dont tout le reste dépend.",
        it: "Le prime due settimane riguardano l'ambito di applicazione, la registrazione e la linea di reporting del CISO - sono i prerequisiti da cui dipende tutto il resto.",
        es: "Las primeras dos semanas tratan del ámbito de aplicación, el registro y la línea de reporte del CISO: son los requisitos previos de los que depende todo lo demás.",
        pl: "Pierwsze dwa tygodnie dotyczą zakresu, rejestracji i linii raportowania CISO - to warunki wstępne, od których zależy wszystko inne.",
      },
    },
    {
      id: "5.1.2",
      question: {
        en: "What is the residual risk acceptance and why does it matter?",
        de: "Was ist die Restrisikoakzeptanz und warum ist sie wichtig?",
        nl: "Wat is de restrisico-acceptatie en waarom is die belangrijk?",
        fr: "Qu'est-ce que l'acceptation du risque résiduel et pourquoi est-elle importante ?",
        it: "Cos'è l'accettazione del rischio residuo e perché è importante?",
        es: "¿Qué es la aceptación del riesgo residual y por qué importa?",
        pl: "Czym jest akceptacja ryzyka szczątkowego i dlaczego ma znaczenie?",
      },
      options: [
        { en: "An insurance document that transfers remaining risk to the insurer", de: "Ein Versicherungsdokument, das das verbleibende Risiko auf den Versicherer uebertraegt", nl: "Een verzekeringsdocument dat het resterende risico overdraagt aan de verzekeraar", fr: "Un document d'assurance qui transfère le risque restant à l'assureur", it: "Un documento assicurativo che trasferisce il rischio residuo all'assicuratore", es: "Un documento de seguro que transfiere el riesgo restante al asegurador", pl: "Dokument ubezpieczeniowy przenoszący pozostałe ryzyko na ubezpieczyciela" },
        { en: "The CEO's signature proving they personally reviewed what the company decided to live with - the artefact most auditors look for first", de: "Die Unterschrift des CEO, die belegt, dass er persönlich geprüft hat, womit das Unternehmen zu leben beschlossen hat - das Artefakt, nach dem Auditoren zuerst suchen", nl: "De handtekening van de CEO die bewijst dat zij persoonlijk hebben beoordeeld waarmee het bedrijf heeft besloten te leven - het artefact waarnaar de meeste auditors als eerste zoeken", fr: "La signature du CEO prouvant qu'il a personnellement examiné ce que l'entreprise a décidé d'accepter - l'artefact que la plupart des auditeurs recherchent en premier", it: "La firma del CEO che dimostra di aver esaminato personalmente ciò con cui l'azienda ha deciso di convivere - l'artefatto che la maggior parte degli auditor cerca per primo", es: "La firma del CEO que demuestra que revisó personalmente aquello con lo que la empresa decidió convivir: el artefacto que la mayoría de los auditores busca primero", pl: "Podpis CEO potwierdzający, że osobiście przejrzał to, z czym firma zdecydowała się funkcjonować - artefakt, którego większość audytorów szuka w pierwszej kolejności" },
        { en: "A report from the CISO listing all risks that have been eliminated", de: "Ein Bericht des CISO, der alle beseitigten Risiken auflistet", nl: "Een rapport van de CISO met alle geëlimineerde risico's", fr: "Un rapport du CISO énumérant tous les risques qui ont été éliminés", it: "Un rapporto del CISO che elenca tutti i rischi eliminati", es: "Un informe del CISO que enumera todos los riesgos que se han eliminado", pl: "Raport CISO wymieniający wszystkie wyeliminowane ryzyka" },
        { en: "A legal waiver releasing the CEO from personal liability for known risks", de: "Ein rechtlicher Verzicht, der den CEO von der persönlichen Haftung für bekannte Risiken befreit", nl: "Een juridische vrijwaring die de CEO vrijstelt van persoonlijke aansprakelijkheid voor bekende risico's", fr: "Une renonciation juridique libérant le CEO de toute responsabilité personnelle pour les risques connus", it: "Una rinuncia legale che libera il CEO dalla responsabilità personale per i rischi noti", es: "Una renuncia jurídica que exime al CEO de responsabilidad personal por los riesgos conocidos", pl: "Prawne zrzeczenie zwalniające CEO z osobistej odpowiedzialności za znane ryzyka" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The residual risk acceptance is the artefact most CEOs miss and most auditors look for first. Your signature proves you personally reviewed what the company decided to live with.",
        de: "Die Restrisikoakzeptanz ist das Artefakt, das die meisten CEOs versaeumen und nach dem die meisten Auditoren zuerst suchen. Ihre Unterschrift belegt, dass Sie persönlich geprüft haben, womit das Unternehmen zu leben beschlossen hat.",
        nl: "De restrisico-acceptatie is het artefact dat de meeste CEO's missen en waarnaar de meeste auditors als eerste zoeken. Uw handtekening bewijst dat u persoonlijk heeft beoordeeld waarmee het bedrijf heeft besloten te leven.",
        fr: "L'acceptation du risque résiduel est l'artefact que la plupart des CEO oublient et que la plupart des auditeurs recherchent en premier. Votre signature prouve que vous avez personnellement examiné ce que l'entreprise a décidé d'accepter.",
        it: "L'accettazione del rischio residuo è l'artefatto che la maggior parte dei CEO trascura e che la maggior parte degli auditor cerca per primo. La vostra firma dimostra che avete esaminato personalmente ciò con cui l'azienda ha deciso di convivere.",
        es: "La aceptación del riesgo residual es el artefacto que la mayoría de los CEO pasa por alto y que la mayoría de los auditores busca primero. Su firma demuestra que revisó personalmente aquello con lo que la empresa decidió convivir.",
        pl: "Akceptacja ryzyka szczątkowego to artefakt, który większość CEO pomija, a którego większość audytorów szuka w pierwszej kolejności. Twój podpis dowodzi, że osobiście przejrzałeś to, z czym firma zdecydowała się funkcjonować.",
      },
    },
    {
      id: "5.1.3",
      question: {
        en: "What is the recommended ongoing cadence after the 90-day baseline is established?",
        de: "Welcher laufende Rhythmus wird empfohlen, nachdem die 90-Tage-Baseline etabliert ist?",
        nl: "Welk doorlopend ritme wordt aanbevolen nadat de 90-dagenbasislijn is vastgesteld?",
        fr: "Quelle est la cadence continue recommandée une fois la base de référence de 90 jours établie ?",
        it: "Qual è la cadenza continuativa raccomandata dopo che è stata stabilita la baseline di 90 giorni?",
        es: "¿Cuál es la cadencia continua recomendada una vez establecida la base de referencia de 90 días?",
        pl: "Jaki jest zalecany stały rytm po ustanowieniu poziomu bazowego z 90 dni?",
      },
      options: [
        { en: "Weekly CISO briefings, quarterly policy reviews, annual training", de: "Woechentliche CISO-Briefings, vierteljährliche Richtlinienprüfungen, jährliche Schulung", nl: "Wekelijkse CISO-briefings, kwartaallijkse beleidsbeoordelingen, jaarlijkse training", fr: "Briefings hebdomadaires du CISO, revues trimestrielles des politiques, formation annuelle", it: "Briefing settimanali del CISO, revisioni trimestrali delle politiche, formazione annuale", es: "Briefings semanales del CISO, revisiones trimestrales de políticas, formación anual", pl: "Cotygodniowe briefingi CISO, kwartalne przeglądy polityk, coroczne szkolenie" },
        { en: "Monthly CISO briefings, annual policy re-sign-off and risk register review, training refresher every three years", de: "Monatliche CISO-Briefings, jährliche Richtlinien-Neufreigabe und Risikoregister-Prüfung, Schulungsauffrischung alle drei Jahre", nl: "Maandelijkse CISO-briefings, jaarlijkse herondertekening beleid en beoordeling risicoregister, trainingsopfrissing elke drie jaar", fr: "Briefings mensuels du CISO, nouvelle validation annuelle des politiques et revue du registre des risques, recyclage de la formation tous les trois ans", it: "Briefing mensili del CISO, nuova approvazione annuale delle politiche e revisione del registro dei rischi, aggiornamento della formazione ogni tre anni", es: "Briefings mensuales del CISO, nueva aprobación anual de las políticas y revisión del registro de riesgos, reciclaje de la formación cada tres años", pl: "Comiesięczne briefingi CISO, coroczne ponowne zatwierdzenie polityk i przegląd rejestru ryzyka, odświeżenie szkolenia co trzy lata" },
        { en: "Daily status updates, monthly audits, annual board review", de: "Taegliche Statusberichte, monatliche Audits, jährliche Vorstandsprüfung", nl: "Dagelijkse statusupdates, maandelijkse audits, jaarlijkse bestuursreview", fr: "Mises à jour quotidiennes du statut, audits mensuels, revue annuelle du conseil", it: "Aggiornamenti giornalieri sullo stato, audit mensili, revisione annuale del consiglio", es: "Actualizaciones diarias del estado, auditorías mensuales, revisión anual del consejo", pl: "Codzienne aktualizacje statusu, miesięczne audyty, coroczny przegląd zarządu" },
        { en: "No ongoing cadence is needed once the baseline is established", de: "Nach Etablierung der Baseline ist kein laufender Rhythmus erforderlich", nl: "Na de basislijn is geen doorlopend ritme nodig", fr: "Aucune cadence continue n'est nécessaire une fois la base de référence établie", it: "Una volta stabilita la baseline non è necessaria alcuna cadenza continuativa", es: "No se necesita ninguna cadencia continua una vez establecida la base de referencia", pl: "Po ustanowieniu poziomu bazowego nie jest potrzebny żaden stały rytm" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Monthly CISO briefing; annually: policy re-sign-off, risk register review with updated residual risk acceptance, management review; every three years: management body training refresher.",
        de: "Monatliches CISO-Briefing; jährlich: Richtlinien-Neufreigabe, Risikoregister-Prüfung mit aktualisierter Restrisikoakzeptanz, Management-Bewertung; alle drei Jahre: Schulungsauffrischung für das Leitungsorgan.",
        nl: "Maandelijkse CISO-briefing; jaarlijks: herondertekening beleid, beoordeling risicoregister met bijgewerkte restrisico-acceptatie, managementbeoordeling; elke drie jaar: trainingsopfrissing voor het leidinggevend orgaan.",
        fr: "Briefing mensuel du CISO ; chaque année : nouvelle validation des politiques, revue du registre des risques avec acceptation actualisée du risque résiduel, revue de direction ; tous les trois ans : recyclage de la formation de l'organe de direction.",
        it: "Briefing mensile del CISO; annualmente: nuova approvazione delle politiche, revisione del registro dei rischi con accettazione aggiornata del rischio residuo, riesame della direzione; ogni tre anni: aggiornamento della formazione dell'organo di gestione.",
        es: "Briefing mensual del CISO; anualmente: nueva aprobación de las políticas, revisión del registro de riesgos con aceptación actualizada del riesgo residual, revisión por la dirección; cada tres años: reciclaje de la formación del órgano de dirección.",
        pl: "Comiesięczny briefing CISO; corocznie: ponowne zatwierdzenie polityk, przegląd rejestru ryzyka z zaktualizowaną akceptacją ryzyka szczątkowego, przegląd zarządzania; co trzy lata: odświeżenie szkolenia organu zarządzającego.",
      },
    },
    {
      id: "5.1.4",
      question: {
        en: "Which three artefacts carry the most audit weight by day ninety?",
        de: "Welche drei Artefakte haben bis zum neunzigsten Tag das groesste Auditgewicht?",
        nl: "Welke drie artefacten hebben het meeste auditgewicht op dag negentig?",
        fr: "Quels trois artefacts ont le plus de poids d'audit au quatre-vingt-dixième jour ?",
        it: "Quali tre artefatti hanno il maggior peso ai fini dell'audit entro il novantesimo giorno?",
        es: "¿Qué tres artefactos tienen mayor peso de auditoría hacia el día noventa?",
        pl: "Które trzy artefakty mają największe znaczenie dla audytu do dziewięćdziesiątego dnia?",
      },
      options: [
        { en: "Insurance certificates, vendor contracts, and employee handbooks", de: "Versicherungszertifikate, Lieferantenvertraege und Mitarbeiterhandbuecher", nl: "Verzekeringscertificaten, leverancierscontracten en personeelshandboeken", fr: "Certificats d'assurance, contrats fournisseurs et manuels des employés", it: "Certificati assicurativi, contratti con i fornitori e manuali per i dipendenti", es: "Certificados de seguro, contratos de proveedores y manuales del empleado", pl: "Certyfikaty ubezpieczeniowe, umowy z dostawcami i podręczniki pracownicze" },
        { en: "The signed top-level policy, the risk register with residual risk acceptance, and the evidence walk of the ten measures", de: "Die unterschriebene übergeordnete Richtlinie, das Risikoregister mit Restrisikoakzeptanz und der Evidenznachweis der zehn Maßnahmen", nl: "Het ondertekende overkoepelende beleid, het risicoregister met restrisico-acceptatie en het bewijs van de tien maatregelen", fr: "La politique de haut niveau signée, le registre des risques avec acceptation du risque résiduel, et la revue des preuves des dix mesures", it: "La politica di alto livello firmata, il registro dei rischi con accettazione del rischio residuo e la rassegna delle prove delle dieci misure", es: "La política de alto nivel firmada, el registro de riesgos con aceptación del riesgo residual y el recorrido de evidencias de las diez medidas", pl: "Podpisana nadrzędna polityka, rejestr ryzyka z akceptacją ryzyka szczątkowego oraz przegląd dowodów dziesięciu środków" },
        { en: "The CISO's CV, the IT budget, and the incident log", de: "Der Lebenslauf des CISO, das IT-Budget und das Vorfallprotokoll", nl: "Het CV van de CISO, het IT-budget en het incidentlogboek", fr: "Le CV du CISO, le budget informatique et le journal des incidents", it: "Il CV del CISO, il budget IT e il registro degli incidenti", es: "El CV del CISO, el presupuesto de TI y el registro de incidentes", pl: "CV CISO, budżet IT i dziennik incydentów" },
        { en: "The cyber insurance certificate, the D&O policy, and the registration confirmation", de: "Das Cyberversicherungszertifikat, die D&O-Police und die Registrierungsbestätigtung", nl: "Het cyberverzekeringscertificaat, de D&O-polis en de registratiebevestiging", fr: "Le certificat de cyberassurance, la police D&O et la confirmation d'enregistrement", it: "Il certificato di cyberassicurazione, la polizza D&O e la conferma di registrazione", es: "El certificado de ciberseguro, la póliza D&O y la confirmación de registro", pl: "Certyfikat cyberubezpieczenia, polisa D&O i potwierdzenie rejestracji" },
      ],
      correctIndex: 1,
      explanation: {
        en: "By day ninety, you should have signed the top-level policy, the risk register with residual risk acceptance, and walked the ten measures with evidence.",
        de: "Bis zum neunzigsten Tag sollten Sie die übergeordnete Richtlinie unterschrieben, das Risikoregister mit Restrisikoakzeptanz unterzeichnet und die zehn Maßnahmen mit Evidenz durchlaufen haben.",
        nl: "Op dag negentig moet u het overkoepelende beleid hebben ondertekend, het risicoregister met restrisico-acceptatie, en de tien maatregelen met bewijs hebben doorlopen.",
        fr: "Au quatre-vingt-dixième jour, vous devriez avoir signé la politique de haut niveau, le registre des risques avec acceptation du risque résiduel, et parcouru les dix mesures avec des preuves.",
        it: "Entro il novantesimo giorno, dovreste aver firmato la politica di alto livello, il registro dei rischi con accettazione del rischio residuo, e aver esaminato le dieci misure con le prove.",
        es: "Hacia el día noventa, debería haber firmado la política de alto nivel, el registro de riesgos con aceptación del riesgo residual, y haber recorrido las diez medidas con evidencias.",
        pl: "Do dziewięćdziesiątego dnia powinieneś podpisać nadrzędną politykę, rejestr ryzyka z akceptacją ryzyka szczątkowego oraz przejść przez dziesięć środków wraz z dowodami.",
      },
    },
  ],
});

export default quiz;
