import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "5.1",
  passingScore: 75,
  questions: [
    {
      id: "5.1.1",
      question: {
        en: "What are the three priorities for the first two weeks according to the 90-day plan?",
        de: "Welche drei Prioritaeten gelten laut dem 90-Tage-Plan für die ersten zwei Wochen?",
        nl: "Wat zijn de drie prioriteiten voor de eerste twee weken volgens het 90-dagenplan?",
        fr: "Quelles sont les trois priorités des deux premières semaines selon le plan de 90 jours ?",
        it: "Quali sono le tre priorità per le prime due settimane secondo il piano di 90 giorni?",
        es: "¿Cuáles son las tres prioridades de las primeras dos semanas según el plan de 90 días?",
        pl: "Jakie są trzy priorytety na pierwsze dwa tygodnie według planu 90-dniowego?",
        cs: "Jaké jsou tři priority pro první dva týdny podle 90denního plánu?",
        pt: "Quais são as três prioridades para as primeiras duas semanas segundo o plano de 90 dias?",
        ro: "Care sunt cele trei priorități pentru primele două săptămâni potrivit planului de 90 de zile?",
      },
      options: [
        { en: "Hire a CISO, purchase insurance, and file for an extension", de: "Einen CISO einstellen, Versicherung abschließen und eine Verlaengerung beantragen", nl: "Een CISO aannemen, verzekering afsluiten en een verlenging aanvragen", fr: "Embaucher un CISO, souscrire une assurance et demander une prolongation", it: "Assumere un CISO, stipulare un'assicurazione e richiedere una proroga", es: "Contratar a un CISO, contratar un seguro y solicitar una prórroga", pl: "Zatrudnić CISO, wykupić ubezpieczenie i złożyć wniosek o przedłużenie", cs: "Najmout CISO, zakoupit pojištění a požádat o prodloužení", pt: "Contratar um CISO, adquirir um seguro e requerer uma prorrogação", ro: "Angajarea unui CISO, achiziționarea unei asigurări și solicitarea unei prelungiri" },
        { en: "Confirm scoping assessment, register with the BSI, and confirm the CISO reporting line", de: "Betroffenheitsbewertung bestätigten, beim BSI registrieren und die Berichtslinie des CISO bestätigten", nl: "Scope-beoordeling bevestigen, registreren bij de BSI en de rapportagelijn van de CISO bevestigen", fr: "Confirmer l'évaluation du périmètre, s'enregistrer auprès du BSI et confirmer la ligne de reporting du CISO", it: "Confermare la valutazione dell'ambito di applicazione, registrarsi presso il BSI e confermare la linea di reporting del CISO", es: "Confirmar la evaluación del ámbito de aplicación, registrarse ante el BSI y confirmar la línea de reporte del CISO", pl: "Potwierdzić ocenę zakresu, zarejestrować się w BSI i potwierdzić linię raportowania CISO", cs: "Potvrdit posouzení působnosti, zaregistrovat se u BSI a potvrdit linii podávání zpráv CISO", pt: "Confirmar a avaliação de âmbito, registar-se junto do BSI e confirmar a linha de reporte do CISO", ro: "Confirmarea evaluării domeniului de aplicare, înregistrarea la BSI și confirmarea liniei de raportare a CISO" },
        { en: "Write all eleven policies, run a tabletop exercise, and schedule the management review", de: "Alle elf Richtlinien schreiben, eine Tabletop-Uebung durchführen und die Management-Bewertung planen", nl: "Alle elf beleidslijnen schrijven, een tabletop-oefening uitvoeren en de managementbeoordeling plannen", fr: "Rédiger les onze politiques, mener un exercice sur table et planifier la revue de direction", it: "Redigere tutte e undici le politiche, condurre un'esercitazione teorica e programmare il riesame della direzione", es: "Redactar las once políticas, realizar un ejercicio de simulación y programar la revisión por la dirección", pl: "Napisać wszystkie jedenaście polityk, przeprowadzić ćwiczenie sztabowe i zaplanować przegląd zarządzania", cs: "Napsat všech jedenáct politik, provést cvičení u stolu a naplánovat přezkum vedením", pt: "Redigir as onze políticas, realizar um exercício de simulação teórica e agendar a revisão pela gestão", ro: "Redactarea tuturor celor unsprezece politici, desfășurarea unui exercițiu teoretic de tip tabletop și programarea revizuirii efectuate de conducere" },
        { en: "Purchase cyber insurance, engage an external auditor, and notify customers", de: "Cyberversicherung abschließen, einen externen Auditor beauftragen und Kunden benachrichtigen", nl: "Cyberverzekering afsluiten, een externe auditor inschakelen en klanten informeren", fr: "Souscrire une cyberassurance, engager un auditeur externe et notifier les clients", it: "Stipulare una cyberassicurazione, incaricare un auditor esterno e avvisare i clienti", es: "Contratar un ciberseguro, contratar a un auditor externo y notificar a los clientes", pl: "Wykupić cyberubezpieczenie, zaangażować zewnętrznego audytora i powiadomić klientów", cs: "Zakoupit kybernetické pojištění, najmout externího auditora a informovat zákazníky", pt: "Adquirir um seguro cibernético, contratar um auditor externo e notificar os clientes", ro: "Achiziționarea unei asigurări cibernetice, angajarea unui auditor extern și notificarea clienților" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The first two weeks are about scope, registration, and the CISO reporting line - these are the prerequisites everything else depends on.",
        de: "Die ersten zwei Wochen drehen sich um Betroffenheit, Registrierung und die Berichtslinie des CISO - das sind die Voraussetzungen, von denen alles andere abhaengt.",
        nl: "De eerste twee weken gaan over scope, registratie en de rapportagelijn van de CISO - dat zijn de voorwaarden waarvan alles else afhankelijk is.",
        fr: "Les deux premières semaines portent sur le périmètre, l'enregistrement et la ligne de reporting du CISO - ce sont les conditions préalables dont tout le reste dépend.",
        it: "Le prime due settimane riguardano l'ambito di applicazione, la registrazione e la linea di reporting del CISO - sono i prerequisiti da cui dipende tutto il resto.",
        es: "Las primeras dos semanas tratan del ámbito de aplicación, el registro y la línea de reporte del CISO: son los requisitos previos de los que depende todo lo demás.",
        pl: "Pierwsze dwa tygodnie dotyczą zakresu, rejestracji i linii raportowania CISO - to warunki wstępne, od których zależy wszystko inne.",
        cs: "První dva týdny jsou o působnosti, registraci a linii podávání zpráv CISO. To jsou předpoklady, na kterých závisí vše ostatní.",
        pt: "As primeiras duas semanas são sobre o âmbito, o registo e a linha de reporte do CISO. São os pré-requisitos de que tudo o resto depende.",
        ro: "Primele două săptămâni vizează domeniul de aplicare, înregistrarea și linia de raportare a CISO. Acestea sunt condițiile prealabile de care depinde tot restul.",
      },
    },
    {
      id: "5.1.2",
      question: {
        en: "What is the residual risk acceptance and why does it matter?",
        de: "Was ist die Restrisikoakzeptanz und warum ist sie wichtig?",
        nl: "Wat is de restrisico-acceptatie en waarom is die belangrijk?",
        fr: "Qu'est-ce que l'acceptation du risque résiduel et pourquoi est-elle importante ?",
        it: "Cos'è l'accettazione del rischio residuo e perché è importante?",
        es: "¿Qué es la aceptación del riesgo residual y por qué importa?",
        pl: "Czym jest akceptacja ryzyka szczątkowego i dlaczego ma znaczenie?",
        cs: "Co je přijetí zbytkového rizika a proč na něm záleží?",
        pt: "O que é a aceitação do risco residual e por que é importante?",
        ro: "Ce este acceptarea riscului rezidual și de ce contează?",
      },
      options: [
        { en: "An insurance document that transfers remaining risk to the insurer", de: "Ein Versicherungsdokument, das das verbleibende Risiko auf den Versicherer uebertraegt", nl: "Een verzekeringsdocument dat het resterende risico overdraagt aan de verzekeraar", fr: "Un document d'assurance qui transfère le risque restant à l'assureur", it: "Un documento assicurativo che trasferisce il rischio residuo all'assicuratore", es: "Un documento de seguro que transfiere el riesgo restante al asegurador", pl: "Dokument ubezpieczeniowy przenoszący pozostałe ryzyko na ubezpieczyciela", cs: "Pojistný dokument, který přenáší zbývající riziko na pojistitele", pt: "Um documento de seguro que transfere o risco remanescente para a seguradora", ro: "Un document de asigurare care transferă riscul rămas către asigurător" },
        { en: "The CEO's signature proving they personally reviewed what the company decided to live with - the artefact most auditors look for first", de: "Die Unterschrift des CEO, die belegt, dass er persönlich geprüft hat, womit das Unternehmen zu leben beschlossen hat - das Artefakt, nach dem Auditoren zuerst suchen", nl: "De handtekening van de CEO die bewijst dat zij persoonlijk hebben beoordeeld waarmee het bedrijf heeft besloten te leven - het artefact waarnaar de meeste auditors als eerste zoeken", fr: "La signature du CEO prouvant qu'il a personnellement examiné ce que l'entreprise a décidé d'accepter - l'artefact que la plupart des auditeurs recherchent en premier", it: "La firma del CEO che dimostra di aver esaminato personalmente ciò con cui l'azienda ha deciso di convivere - l'artefatto che la maggior parte degli auditor cerca per primo", es: "La firma del CEO que demuestra que revisó personalmente aquello con lo que la empresa decidió convivir: el artefacto que la mayoría de los auditores busca primero", pl: "Podpis CEO potwierdzający, że osobiście przejrzał to, z czym firma zdecydowała się funkcjonować - artefakt, którego większość audytorów szuka w pierwszej kolejności", cs: "Podpis generálního ředitele dokládající, že osobně přezkoumal to, s čím se společnost rozhodla žít: artefakt, který většina auditorů hledá jako první", pt: "A assinatura do diretor executivo a comprovar que reviu pessoalmente aquilo com que a empresa decidiu conviver: o artefacto que a maioria dos auditores procura primeiro", ro: "Semnătura directorului general care dovedește că a revizuit personal ceea ce compania a decis să accepte: artefactul pe care majoritatea auditorilor îl caută mai întâi" },
        { en: "A report from the CISO listing all risks that have been eliminated", de: "Ein Bericht des CISO, der alle beseitigten Risiken auflistet", nl: "Een rapport van de CISO met alle geëlimineerde risico's", fr: "Un rapport du CISO énumérant tous les risques qui ont été éliminés", it: "Un rapporto del CISO che elenca tutti i rischi eliminati", es: "Un informe del CISO que enumera todos los riesgos que se han eliminado", pl: "Raport CISO wymieniający wszystkie wyeliminowane ryzyka", cs: "Zprávu od CISO se seznamem všech rizik, která byla odstraněna", pt: "Um relatório do CISO que enumera todos os riscos que foram eliminados", ro: "Un raport al CISO care enumeră toate riscurile care au fost eliminate" },
        { en: "A legal waiver releasing the CEO from personal liability for known risks", de: "Ein rechtlicher Verzicht, der den CEO von der persönlichen Haftung für bekannte Risiken befreit", nl: "Een juridische vrijwaring die de CEO vrijstelt van persoonlijke aansprakelijkheid voor bekende risico's", fr: "Une renonciation juridique libérant le CEO de toute responsabilité personnelle pour les risques connus", it: "Una rinuncia legale che libera il CEO dalla responsabilità personale per i rischi noti", es: "Una renuncia jurídica que exime al CEO de responsabilidad personal por los riesgos conocidos", pl: "Prawne zrzeczenie zwalniające CEO z osobistej odpowiedzialności za znane ryzyka", cs: "Právní vzdání se nároku, které zprošťuje generálního ředitele osobní odpovědnosti za známá rizika", pt: "Uma renúncia jurídica que liberta o diretor executivo da responsabilidade pessoal por riscos conhecidos", ro: "O renunțare juridică ce îl eliberează pe directorul general de răspunderea personală pentru riscurile cunoscute" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The residual risk acceptance is the artefact most CEOs miss and most auditors look for first. Your signature proves you personally reviewed what the company decided to live with.",
        de: "Die Restrisikoakzeptanz ist das Artefakt, das die meisten CEOs versaeumen und nach dem die meisten Auditoren zuerst suchen. Ihre Unterschrift belegt, dass Sie persönlich geprüft haben, womit das Unternehmen zu leben beschlossen hat.",
        nl: "De restrisico-acceptatie is het artefact dat de meeste CEO's missen en waarnaar de meeste auditors als eerste zoeken. Uw handtekening bewijst dat u persoonlijk heeft beoordeeld waarmee het bedrijf heeft besloten te leven.",
        fr: "L'acceptation du risque résiduel est l'artefact que la plupart des CEO oublient et que la plupart des auditeurs recherchent en premier. Votre signature prouve que vous avez personnellement examiné ce que l'entreprise a décidé d'accepter.",
        it: "L'accettazione del rischio residuo è l'artefatto che la maggior parte dei CEO trascura e che la maggior parte degli auditor cerca per primo. La vostra firma dimostra che avete esaminato personalmente ciò con cui l'azienda ha deciso di convivere.",
        es: "La aceptación del riesgo residual es el artefacto que la mayoría de los CEO pasa por alto y que la mayoría de los auditores busca primero. Su firma demuestra que revisó personalmente aquello con lo que la empresa decidió convivir.",
        pl: "Akceptacja ryzyka szczątkowego to artefakt, który większość CEO pomija, a którego większość audytorów szuka w pierwszej kolejności. Twój podpis dowodzi, że osobiście przejrzałeś to, z czym firma zdecydowała się funkcjonować.",
        cs: "Přijetí zbytkového rizika je artefakt, který většině generálních ředitelů chybí a který většina auditorů hledá jako první. Váš podpis dokládá, že jste osobně přezkoumali to, s čím se společnost rozhodla žít.",
        pt: "A aceitação do risco residual é o artefacto que a maioria dos diretores executivos não tem e que a maioria dos auditores procura primeiro. A sua assinatura comprova que reviu pessoalmente aquilo com que a empresa decidiu conviver.",
        ro: "Acceptarea riscului rezidual este artefactul pe care majoritatea directorilor generali îl ratează și pe care majoritatea auditorilor îl caută mai întâi. Semnătura dumneavoastră dovedește că ați revizuit personal ceea ce compania a decis să accepte.",
      },
    },
    {
      id: "5.1.3",
      question: {
        en: "What is the recommended ongoing cadence after the 90-day baseline is established?",
        de: "Welcher laufende Rhythmus wird empfohlen, nachdem die 90-Tage-Baseline etabliert ist?",
        nl: "Welk doorlopend ritme wordt aanbevolen nadat de 90-dagenbasislijn is vastgesteld?",
        fr: "Quelle est la cadence continue recommandée une fois la base de référence de 90 jours établie ?",
        it: "Qual è la cadenza continuativa raccomandata dopo che è stata stabilita la baseline di 90 giorni?",
        es: "¿Cuál es la cadencia continua recomendada una vez establecida la base de referencia de 90 días?",
        pl: "Jaki jest zalecany stały rytm po ustanowieniu poziomu bazowego z 90 dni?",
        cs: "Jaká je doporučená průběžná četnost poté, co je zaveden 90denní základ?",
        pt: "Qual é a periodicidade contínua recomendada após estabelecida a base de 90 dias?",
        ro: "Care este ritmul continuu recomandat după stabilirea bazei de 90 de zile?",
      },
      options: [
        { en: "Weekly CISO briefings, quarterly policy reviews, annual training", de: "Woechentliche CISO-Briefings, vierteljährliche Richtlinienprüfungen, jährliche Schulung", nl: "Wekelijkse CISO-briefings, kwartaallijkse beleidsbeoordelingen, jaarlijkse training", fr: "Briefings hebdomadaires du CISO, revues trimestrielles des politiques, formation annuelle", it: "Briefing settimanali del CISO, revisioni trimestrali delle politiche, formazione annuale", es: "Briefings semanales del CISO, revisiones trimestrales de políticas, formación anual", pl: "Cotygodniowe briefingi CISO, kwartalne przeglądy polityk, coroczne szkolenie", cs: "Týdenní briefingy CISO, čtvrtletní přezkumy politik, roční školení", pt: "Sessões de informação semanais do CISO, revisões trimestrais de políticas, formação anual", ro: "Sesiuni săptămânale de informare ale CISO, revizuiri trimestriale ale politicilor, formare anuală" },
        { en: "Monthly CISO briefings, annual policy re-sign-off and risk register review, training refresher every three years", de: "Monatliche CISO-Briefings, jährliche Richtlinien-Neufreigabe und Risikoregister-Prüfung, Schulungsauffrischung alle drei Jahre", nl: "Maandelijkse CISO-briefings, jaarlijkse herondertekening beleid en beoordeling risicoregister, trainingsopfrissing elke drie jaar", fr: "Briefings mensuels du CISO, nouvelle validation annuelle des politiques et revue du registre des risques, recyclage de la formation tous les trois ans", it: "Briefing mensili del CISO, nuova approvazione annuale delle politiche e revisione del registro dei rischi, aggiornamento della formazione ogni tre anni", es: "Briefings mensuales del CISO, nueva aprobación anual de las políticas y revisión del registro de riesgos, reciclaje de la formación cada tres años", pl: "Comiesięczne briefingi CISO, coroczne ponowne zatwierdzenie polityk i przegląd rejestru ryzyka, odświeżenie szkolenia co trzy lata", cs: "Měsíční briefingy CISO, roční opětovné podepsání politik a přezkum registru rizik, opakovací školení každé tři roky", pt: "Sessões de informação mensais do CISO, nova assinatura anual das políticas e revisão do registo de riscos, atualização de formação de três em três anos", ro: "Sesiuni lunare de informare ale CISO, resemnarea anuală a politicilor și revizuirea registrului de riscuri, reîmprospătarea formării o dată la trei ani" },
        { en: "Daily status updates, monthly audits, annual board review", de: "Taegliche Statusberichte, monatliche Audits, jährliche Vorstandsprüfung", nl: "Dagelijkse statusupdates, maandelijkse audits, jaarlijkse bestuursreview", fr: "Mises à jour quotidiennes du statut, audits mensuels, revue annuelle du conseil", it: "Aggiornamenti giornalieri sullo stato, audit mensili, revisione annuale del consiglio", es: "Actualizaciones diarias del estado, auditorías mensuales, revisión anual del consejo", pl: "Codzienne aktualizacje statusu, miesięczne audyty, coroczny przegląd zarządu", cs: "Denní aktualizace stavu, měsíční audity, roční přezkum orgánem", pt: "Atualizações diárias de estado, auditorias mensais, revisão anual pelo órgão de administração", ro: "Actualizări zilnice de stare, audituri lunare, revizuire anuală de către organul de conducere" },
        { en: "No ongoing cadence is needed once the baseline is established", de: "Nach Etablierung der Baseline ist kein laufender Rhythmus erforderlich", nl: "Na de basislijn is geen doorlopend ritme nodig", fr: "Aucune cadence continue n'est nécessaire une fois la base de référence établie", it: "Una volta stabilita la baseline non è necessaria alcuna cadenza continuativa", es: "No se necesita ninguna cadencia continua una vez establecida la base de referencia", pl: "Po ustanowieniu poziomu bazowego nie jest potrzebny żaden stały rytm", cs: "Po zavedení základu není žádná průběžná četnost potřeba", pt: "Não é necessária qualquer periodicidade contínua depois de estabelecida a base", ro: "Nu este necesar niciun ritm continuu odată ce baza este stabilită" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Monthly CISO briefing; annually: policy re-sign-off, risk register review with updated residual risk acceptance, management review; every three years: management body training refresher.",
        de: "Monatliches CISO-Briefing; jährlich: Richtlinien-Neufreigabe, Risikoregister-Prüfung mit aktualisierter Restrisikoakzeptanz, Management-Bewertung; alle drei Jahre: Schulungsauffrischung für das Leitungsorgan.",
        nl: "Maandelijkse CISO-briefing; jaarlijks: herondertekening beleid, beoordeling risicoregister met bijgewerkte restrisico-acceptatie, managementbeoordeling; elke drie jaar: trainingsopfrissing voor het leidinggevend orgaan.",
        fr: "Briefing mensuel du CISO ; chaque année : nouvelle validation des politiques, revue du registre des risques avec acceptation actualisée du risque résiduel, revue de direction ; tous les trois ans : recyclage de la formation de l'organe de direction.",
        it: "Briefing mensile del CISO; annualmente: nuova approvazione delle politiche, revisione del registro dei rischi con accettazione aggiornata del rischio residuo, riesame della direzione; ogni tre anni: aggiornamento della formazione dell'organo di gestione.",
        es: "Briefing mensual del CISO; anualmente: nueva aprobación de las políticas, revisión del registro de riesgos con aceptación actualizada del riesgo residual, revisión por la dirección; cada tres años: reciclaje de la formación del órgano de dirección.",
        pl: "Comiesięczny briefing CISO; corocznie: ponowne zatwierdzenie polityk, przegląd rejestru ryzyka z zaktualizowaną akceptacją ryzyka szczątkowego, przegląd zarządzania; co trzy lata: odświeżenie szkolenia organu zarządzającego.",
        cs: "Měsíční briefing CISO, ročně: opětovné podepsání politik, přezkum registru rizik s aktualizovaným přijetím zbytkového rizika, přezkum vedením, každé tři roky: opakovací školení řídicího orgánu.",
        pt: "Sessão de informação mensal do CISO, anualmente: nova assinatura das políticas, revisão do registo de riscos com aceitação do risco residual atualizada, revisão pela gestão, de três em três anos: atualização da formação do órgão de administração.",
        ro: "Sesiune lunară de informare a CISO, anual: resemnarea politicilor, revizuirea registrului de riscuri cu acceptarea actualizată a riscului rezidual, revizuirea efectuată de conducere, o dată la trei ani: reîmprospătarea formării organului de conducere.",
      },
    },
    {
      id: "5.1.4",
      question: {
        en: "Which three artefacts carry the most audit weight by day ninety?",
        de: "Welche drei Artefakte haben bis zum neunzigsten Tag das groesste Auditgewicht?",
        nl: "Welke drie artefacten hebben het meeste auditgewicht op dag negentig?",
        fr: "Quels trois artefacts ont le plus de poids d'audit au quatre-vingt-dixième jour ?",
        it: "Quali tre artefatti hanno il maggior peso ai fini dell'audit entro il novantesimo giorno?",
        es: "¿Qué tres artefactos tienen mayor peso de auditoría hacia el día noventa?",
        pl: "Które trzy artefakty mają największe znaczenie dla audytu do dziewięćdziesiątego dnia?",
        cs: "Které tři artefakty mají do devadesátého dne největší auditní váhu?",
        pt: "Que três artefactos têm o maior peso de auditoria ao chegar ao dia noventa?",
        ro: "Care trei artefacte au cea mai mare greutate la audit până în ziua a nouăzecea?",
      },
      options: [
        { en: "Insurance certificates, vendor contracts, and employee handbooks", de: "Versicherungszertifikate, Lieferantenvertraege und Mitarbeiterhandbuecher", nl: "Verzekeringscertificaten, leverancierscontracten en personeelshandboeken", fr: "Certificats d'assurance, contrats fournisseurs et manuels des employés", it: "Certificati assicurativi, contratti con i fornitori e manuali per i dipendenti", es: "Certificados de seguro, contratos de proveedores y manuales del empleado", pl: "Certyfikaty ubezpieczeniowe, umowy z dostawcami i podręczniki pracownicze", cs: "Pojistná osvědčení, smlouvy s dodavateli a příručky pro zaměstnance", pt: "Certificados de seguro, contratos de fornecedores e manuais do trabalhador", ro: "Certificate de asigurare, contracte cu furnizorii și manuale ale angajaților" },
        { en: "The signed top-level policy, the risk register with residual risk acceptance, and the evidence walk of the ten measures", de: "Die unterschriebene übergeordnete Richtlinie, das Risikoregister mit Restrisikoakzeptanz und der Evidenznachweis der zehn Maßnahmen", nl: "Het ondertekende overkoepelende beleid, het risicoregister met restrisico-acceptatie en het bewijs van de tien maatregelen", fr: "La politique de haut niveau signée, le registre des risques avec acceptation du risque résiduel, et la revue des preuves des dix mesures", it: "La politica di alto livello firmata, il registro dei rischi con accettazione del rischio residuo e la rassegna delle prove delle dieci misure", es: "La política de alto nivel firmada, el registro de riesgos con aceptación del riesgo residual y el recorrido de evidencias de las diez medidas", pl: "Podpisana nadrzędna polityka, rejestr ryzyka z akceptacją ryzyka szczątkowego oraz przegląd dowodów dziesięciu środków", cs: "Podepsanou nadřazenou politiku, registr rizik s přijetím zbytkového rizika a doložení deseti opatření důkazy", pt: "A política de nível superior assinada, o registo de riscos com aceitação do risco residual e a demonstração com provas das dez medidas", ro: "Politica de nivel superior semnată, registrul de riscuri cu acceptarea riscului rezidual și parcurgerea pe bază de dovezi a celor zece măsuri" },
        { en: "The CISO's CV, the IT budget, and the incident log", de: "Der Lebenslauf des CISO, das IT-Budget und das Vorfallprotokoll", nl: "Het CV van de CISO, het IT-budget en het incidentlogboek", fr: "Le CV du CISO, le budget informatique et le journal des incidents", it: "Il CV del CISO, il budget IT e il registro degli incidenti", es: "El CV del CISO, el presupuesto de TI y el registro de incidentes", pl: "CV CISO, budżet IT i dziennik incydentów", cs: "Životopis CISO, rozpočet na IT a protokol incidentů", pt: "O currículo do CISO, o orçamento de TI e o registo de incidentes", ro: "CV-ul CISO, bugetul IT și jurnalul de incidente" },
        { en: "The cyber insurance certificate, the D&O policy, and the registration confirmation", de: "Das Cyberversicherungszertifikat, die D&O-Police und die Registrierungsbestätigtung", nl: "Het cyberverzekeringscertificaat, de D&O-polis en de registratiebevestiging", fr: "Le certificat de cyberassurance, la police D&O et la confirmation d'enregistrement", it: "Il certificato di cyberassicurazione, la polizza D&O e la conferma di registrazione", es: "El certificado de ciberseguro, la póliza D&O y la confirmación de registro", pl: "Certyfikat cyberubezpieczenia, polisa D&O i potwierdzenie rejestracji", cs: "Osvědčení o kybernetickém pojištění, pojistku D&O a potvrzení registrace", pt: "O certificado de seguro cibernético, a apólice D&O e a confirmação de registo", ro: "Certificatul de asigurare cibernetică, polița D&O și confirmarea înregistrării" },
      ],
      correctIndex: 1,
      explanation: {
        en: "By day ninety, you should have signed the top-level policy, the risk register with residual risk acceptance, and walked the ten measures with evidence.",
        de: "Bis zum neunzigsten Tag sollten Sie die übergeordnete Richtlinie unterschrieben, das Risikoregister mit Restrisikoakzeptanz unterzeichnet und die zehn Maßnahmen mit Evidenz durchlaufen haben.",
        nl: "Op dag negentig moet u het overkoepelende beleid hebben ondertekend, het risicoregister met restrisico-acceptatie, en de tien maatregelen met bewijs hebben doorlopen.",
        fr: "Au quatre-vingt-dixième jour, vous devriez avoir signé la politique de haut niveau, le registre des risques avec acceptation du risque résiduel, et parcouru les dix mesures avec des preuves.",
        it: "Entro il novantesimo giorno, dovreste aver firmato la politica di alto livello, il registro dei rischi con accettazione del rischio residuo, e aver esaminato le dieci misure con le prove.",
        es: "Hacia el día noventa, debería haber firmado la política de alto nivel, el registro de riesgos con aceptación del riesgo residual, y haber recorrido las diez medidas con evidencias.",
        pl: "Do dziewięćdziesiątego dnia powinieneś podpisać nadrzędną politykę, rejestr ryzyka z akceptacją ryzyka szczątkowego oraz przejść przez dziesięć środków wraz z dowodami.",
        cs: "Do devadesátého dne byste měli mít podepsanou nadřazenou politiku, registr rizik s přijetím zbytkového rizika a deset opatření doložených důkazy.",
        pt: "Até ao dia noventa, deve ter assinado a política de nível superior, o registo de riscos com aceitação do risco residual e ter demonstrado as dez medidas com provas.",
        ro: "Până în ziua a nouăzecea, ar trebui să fi semnat politica de nivel superior, registrul de riscuri cu acceptarea riscului rezidual și să fi parcurs cele zece măsuri cu dovezi.",
      },
    },
  ],
});

export default quiz;
