ALTER TABLE "asset" ADD COLUMN "catalog_id" varchar(80);--> statement-breakpoint
-- Which catalogue item each listed asset is, read off the name the platform gave it in either
-- language or, once 2.2 renamed it, the catalogue name it moved into the description. The name
-- wins where both match. The labels are this release's catalogue (each names exactly one item),
-- compared exactly as the platform wrote them; the code still recognises a hand-typed variant.
-- Safe to rerun: only assets without a catalogue item are touched.
UPDATE "asset" SET "catalog_id" = "match"."id"
FROM (
  SELECT DISTINCT ON ("a"."id") "a"."id" AS "asset_id", "known"."id"
  FROM "asset" "a"
  JOIN (VALUES
  ('Vertrieb und Kundenservice', 'bp-sales-cs'),
  ('Sales and customer service', 'bp-sales-cs'),
  ('Produktion oder Dienstleistungserbringung', 'bp-production-service'),
  ('Production or service delivery', 'bp-production-service'),
  ('Beschaffung', 'bp-procurement'),
  ('Procurement', 'bp-procurement'),
  ('Personal- und Lohnverwaltung', 'bp-hr-payroll'),
  ('HR and payroll administration', 'bp-hr-payroll'),
  ('Finanzen und Buchhaltung', 'bp-finance-accounting'),
  ('Finance and accounting', 'bp-finance-accounting'),
  ('Marketing und externe Kommunikation', 'bp-marketing'),
  ('Marketing and external communications', 'bp-marketing'),
  ('Logistik, Transport und Versand', 'bp-logistics'),
  ('Logistics, transport and shipping', 'bp-logistics'),
  ('Lagerhaltung und Bestandsführung', 'bp-warehousing'),
  ('Warehousing and stock management', 'bp-warehousing'),
  ('Instandhaltung und Wartung', 'bp-maintenance'),
  ('Maintenance and repair', 'bp-maintenance'),
  ('Qualitätsmanagement', 'bp-quality'),
  ('Quality management', 'bp-quality'),
  ('Forschung und Entwicklung', 'bp-rnd'),
  ('Research and development', 'bp-rnd'),
  ('IT-Betrieb', 'bp-it-operations'),
  ('IT operations', 'bp-it-operations'),
  ('Gebäudemanagement und Haustechnik', 'bp-facility-management'),
  ('Facility management and building services', 'bp-facility-management'),
  ('Recht und Compliance', 'bp-legal-compliance'),
  ('Legal and compliance', 'bp-legal-compliance'),
  ('Unternehmenswebsite', 'cf-website'),
  ('Company website', 'cf-website'),
  ('Webshop oder Online-Bestellung', 'cf-webshop'),
  ('Webshop or online ordering', 'cf-webshop'),
  ('Kundenportal (Login)', 'cf-customer-portal'),
  ('Customer portal (login)', 'cf-customer-portal'),
  ('Mobile App', 'cf-mobile-app'),
  ('Mobile app', 'cf-mobile-app'),
  ('Kontaktformular auf der Website', 'cf-contact-form'),
  ('Contact form on the website', 'cf-contact-form'),
  ('Newsletterversand (Mailchimp, Brevo)', 'cf-newsletter'),
  ('Newsletter system (Mailchimp, Brevo)', 'cf-newsletter'),
  ('Firmenkonten in sozialen Netzwerken (LinkedIn, Instagram)', 'cf-social-media'),
  ('Company social media accounts (LinkedIn, Instagram)', 'cf-social-media'),
  ('CRM (Salesforce, HubSpot, Pipedrive)', 'sales-crm'),
  ('E-Signatur (DocuSign, Adobe Sign)', 'sales-e-signature'),
  ('E-signature (DocuSign, Adobe Sign)', 'sales-e-signature'),
  ('Video-Meeting- / Demo-Tool (Teams, Zoom, Meet)', 'sales-demo-meeting'),
  ('Video meeting / demo tool (Teams, Zoom, Meet)', 'sales-demo-meeting'),
  ('Angebotserstellung und Kalkulation', 'sales-quote-proposal'),
  ('Quoting and price calculation', 'sales-quote-proposal'),
  ('Vertragsverwaltung', 'sales-contract-mgmt'),
  ('Contract management', 'sales-contract-mgmt'),
  ('Onlinemarktplätze (Amazon, eBay)', 'sales-marketplace'),
  ('Online marketplaces (Amazon, eBay)', 'sales-marketplace'),
  ('Kontaktdatenbanken für die Akquise (Apollo, ZoomInfo)', 'sales-lead-gen'),
  ('Lead-gen / prospecting tool (Apollo, ZoomInfo)', 'sales-lead-gen'),
  ('Vertriebsanalytik oder BI-Dashboard', 'sales-analytics'),
  ('Sales analytics or BI dashboard', 'sales-analytics'),
  ('Helpdesk / Ticketing (Zendesk, Intercom)', 'cs-helpdesk'),
  ('Helpdesk / ticketing (Zendesk, Intercom)', 'cs-helpdesk'),
  ('Telefon- / VoIP-System', 'cs-voip'),
  ('Phone / VoIP system', 'cs-voip'),
  ('Wissensdatenbank oder FAQ-System', 'cs-knowledge-base'),
  ('Knowledge base or FAQ system', 'cs-knowledge-base'),
  ('Gemeinsames Servicepostfach (info@, service@)', 'cs-shared-mailbox'),
  ('Shared service mailbox (info@, service@)', 'cs-shared-mailbox'),
  ('Live-Chat auf der Website', 'cs-live-chat'),
  ('Live chat on the website', 'cs-live-chat'),
  ('Messenger für den Kundenkontakt (WhatsApp Business)', 'cs-messenger'),
  ('Messenger for customer contact (WhatsApp Business)', 'cs-messenger'),
  ('Terminbuchung für Kunden (online)', 'cs-appointment-booking'),
  ('Online appointment booking', 'cs-appointment-booking'),
  ('Außendienstsoftware (Servicetechniker)', 'cs-field-service'),
  ('Field service software (service technicians)', 'cs-field-service'),
  ('Umfragen und Kundenfeedback', 'cs-feedback'),
  ('Survey or feedback tool', 'cs-feedback'),
  ('HRIS (Personio, BambooHR, Workday)', 'hr-hris'),
  ('Lohnsoftware (DATEV Lohn, Lexware, sage)', 'hr-payroll'),
  ('Payroll (DATEV Lohn, Lexware, sage)', 'hr-payroll'),
  ('Zeiterfassung', 'hr-time-tracking'),
  ('Time tracking', 'hr-time-tracking'),
  ('Digitale Personalakten', 'hr-personnel-files'),
  ('Digital personnel files', 'hr-personnel-files'),
  ('Recruiting / Bewerbermanagement', 'hr-recruiting'),
  ('Recruiting / applicant tracking', 'hr-recruiting'),
  ('Schicht- und Dienstplanung', 'hr-scheduling'),
  ('Shift and staff scheduling', 'hr-scheduling'),
  ('Lernplattform (LMS)', 'hr-lms'),
  ('Learning management system (LMS)', 'hr-lms'),
  ('Mitarbeitergespräche und Leistungsbeurteilung', 'hr-performance'),
  ('Performance review tool', 'hr-performance'),
  ('Arbeitsschutz (Unterweisungen, Gefährdungsbeurteilungen)', 'hr-safety'),
  ('Occupational safety (instructions, risk assessments)', 'hr-safety'),
  ('Buchhaltung (DATEV, Lexware, sevDesk, lexoffice)', 'fin-accounting'),
  ('Accounting software (DATEV, Lexware, sevDesk, lexoffice)', 'fin-accounting'),
  ('ERP (SAP, Microsoft Dynamics, ProAlpha)', 'fin-erp'),
  ('Online-Banking-Portale', 'fin-online-banking'),
  ('Online banking portals', 'fin-online-banking'),
  ('Spesenmanagement (Pleo, Spendesk, Moss)', 'fin-expense'),
  ('Expense management (Pleo, Spendesk, Moss)', 'fin-expense'),
  ('Rechnungsstellungssystem', 'fin-invoicing'),
  ('Invoicing system', 'fin-invoicing'),
  ('Zahlungsverarbeitung (Stripe, PayPal, Klarna)', 'fin-payment-processing'),
  ('Payment processing (Stripe, PayPal, Klarna)', 'fin-payment-processing'),
  ('Beschaffungs- oder Bestellsystem', 'fin-procurement-system'),
  ('Procurement / purchase order system', 'fin-procurement-system'),
  ('Datenaustausch mit der Steuerberatung (DATEV Unternehmen online)', 'fin-tax-advisor'),
  ('Data exchange with the tax adviser', 'fin-tax-advisor'),
  ('Steuerportal (ELSTER)', 'fin-tax-portal'),
  ('Tax authority portal', 'fin-tax-portal'),
  ('Revisionssicheres Belegarchiv (GoBD)', 'fin-receipt-archive'),
  ('Audit-proof receipt archive', 'fin-receipt-archive'),
  ('Budgetplanung und Controlling', 'fin-budgeting'),
  ('Budgeting and controlling', 'fin-budgeting'),
  ('E-Mail (Microsoft 365, Google Workspace, Exchange)', 'it-email'),
  ('Email (Microsoft 365, Google Workspace, Exchange)', 'it-email'),
  ('Gemeinsame Dateiablage (SharePoint, Google Drive, NAS)', 'it-file-storage'),
  ('Shared file storage (SharePoint, Google Drive, NAS)', 'it-file-storage'),
  ('Videokonferenz (Teams, Zoom, Meet)', 'it-video-conferencing'),
  ('Video conferencing (Teams, Zoom, Meet)', 'it-video-conferencing'),
  ('Interner Chat (Slack, Teams)', 'it-internal-chat'),
  ('Internal chat (Slack, Teams)', 'it-internal-chat'),
  ('Identity Provider (Azure AD/Entra, Google Workspace, Okta)', 'it-identity-provider'),
  ('Identity provider (Azure AD/Entra, Google Workspace, Okta)', 'it-identity-provider'),
  ('Endpoint-Schutz (Defender, CrowdStrike, SentinelOne)', 'it-endpoint-protection'),
  ('Endpoint protection (Defender, CrowdStrike, SentinelOne)', 'it-endpoint-protection'),
  ('Passwortmanager (1Password, LastPass, Bitwarden)', 'it-password-manager'),
  ('Password manager (1Password, LastPass, Bitwarden)', 'it-password-manager'),
  ('Code-Repositories (GitHub, GitLab, Bitbucket)', 'it-code-repos'),
  ('Code repositories (GitHub, GitLab, Bitbucket)', 'it-code-repos'),
  ('Bürosoftware (Word, Excel, LibreOffice)', 'it-office-suite'),
  ('Office suite (Word, Excel, LibreOffice)', 'it-office-suite'),
  ('Dokumentenmanagement (DMS)', 'it-document-mgmt'),
  ('Document management (DMS)', 'it-document-mgmt'),
  ('Intranet oder Wiki (Confluence, Notion)', 'it-wiki-kb'),
  ('Intranet or wiki (Confluence, Notion)', 'it-wiki-kb'),
  ('Projektmanagement (Jira, Asana, Linear)', 'it-project-management'),
  ('Project management (Jira, Asana, Linear)', 'it-project-management'),
  ('KI-Assistenten (ChatGPT, Microsoft Copilot)', 'it-ai-assistants'),
  ('AI assistants (ChatGPT, Microsoft Copilot)', 'it-ai-assistants'),
  ('Spamfilter und Virenschutz für E-Mails', 'it-email-security'),
  ('Spam and malware filter for email', 'it-email-security'),
  ('Fernwartungssoftware (TeamViewer, AnyDesk)', 'it-remote-support'),
  ('Remote support (TeamViewer, AnyDesk)', 'it-remote-support'),
  ('Mobilgeräteverwaltung (Intune, Jamf)', 'it-mdm'),
  ('Mobile device management (Intune, Jamf)', 'it-mdm'),
  ('Patchmanagement / RMM', 'it-patch-rmm'),
  ('Patch management / RMM', 'it-patch-rmm'),
  ('Monitoring (Datadog, Grafana)', 'it-monitoring'),
  ('IT-Ticketsystem für interne Anfragen', 'it-ticketing'),
  ('IT ticket system for internal requests', 'it-ticketing'),
  ('On-Premise-Server', 'infra-onprem-servers'),
  ('On-premise servers', 'infra-onprem-servers'),
  ('Cloud-Plattform (AWS, Azure, GCP, Hetzner)', 'infra-cloud-platform'),
  ('Cloud platform (AWS, Azure, GCP, Hetzner)', 'infra-cloud-platform'),
  ('Netzwerkequipment (Firewall, Switches, WLAN)', 'infra-network-equipment'),
  ('Network equipment (firewall, switches, WiFi)', 'infra-network-equipment'),
  ('Backup-System (Veeam, NAS, Cloud-Backup)', 'infra-backup-system'),
  ('Backup system (Veeam, NAS, cloud backup)', 'infra-backup-system'),
  ('Sicherungsmedien (Festplatten, Bänder, auch außer Haus)', 'infra-backup-media'),
  ('Backup media (drives, tapes, including off-site)', 'infra-backup-media'),
  ('Virtualisierung (VMware, Hyper-V, Proxmox)', 'infra-virtualisation'),
  ('Virtualisation (VMware, Hyper-V, Proxmox)', 'infra-virtualisation'),
  ('Terminalserver (Remote Desktop, Citrix)', 'infra-terminal-server'),
  ('Terminal servers (Remote Desktop, Citrix)', 'infra-terminal-server'),
  ('Verzeichnisdienst und Domänencontroller (Active Directory)', 'infra-directory'),
  ('Directory service and domain controllers (Active Directory)', 'infra-directory'),
  ('Datenbankserver (SQL Server, PostgreSQL)', 'infra-database'),
  ('Database servers (SQL Server, PostgreSQL)', 'infra-database'),
  ('Netzwerkspeicher (NAS, SAN)', 'infra-storage'),
  ('Network storage (NAS, SAN)', 'infra-storage'),
  ('Domains und DNS (Registrar)', 'infra-dns-domains'),
  ('Domains and DNS (registrar)', 'infra-dns-domains'),
  ('Bürodrucker / Scanner', 'infra-printer-fleet'),
  ('Office printers / scanners', 'infra-printer-fleet'),
  ('USV und Notstrom', 'infra-ups'),
  ('UPS and emergency power', 'infra-ups'),
  ('Notebooks und Desktops', 'ep-laptops'),
  ('Laptops and desktops', 'ep-laptops'),
  ('Firmenmobilgeräte (Handys, Tablets)', 'ep-mobile'),
  ('Company mobile devices (phones, tablets)', 'ep-mobile'),
  ('USB-Sticks und externe Festplatten', 'ep-removable-media'),
  ('USB sticks and external drives', 'ep-removable-media'),
  ('BYOD (private Geräte mit Firmenzugriff)', 'ep-byod'),
  ('BYOD (employee personal devices accessing company data)', 'ep-byod'),
  ('Gemeinsam genutzte Rechner (Produktion, Empfang)', 'ep-shared-pcs'),
  ('Shared workstations (shop floor, reception)', 'ep-shared-pcs'),
  ('Thin Clients', 'ep-thin-clients'),
  ('Thin clients', 'ep-thin-clients'),
  ('Handscanner und mobile Datenerfassung (MDE)', 'ep-handheld-scanners'),
  ('Handheld scanners and mobile data terminals', 'ep-handheld-scanners'),
  ('Besprechungsraumtechnik (Bildschirme, Konferenzsysteme)', 'ep-meeting-rooms'),
  ('Meeting room equipment (displays, conference systems)', 'ep-meeting-rooms'),
  ('Videoüberwachung (Kameras)', 'ep-cameras'),
  ('Video surveillance cameras', 'ep-cameras'),
  ('Zutrittskontrolle (Ausweise, Kartenleser)', 'ep-access-control'),
  ('Access control (badges, card readers)', 'ep-access-control'),
  ('Gebäudetechnik (Heizung, Lüftung, Alarmanlage)', 'ep-building-tech'),
  ('Building technology (heating, ventilation, alarm system)', 'ep-building-tech'),
  ('Hauptbüro', 'loc-main-office'),
  ('Main office', 'loc-main-office'),
  ('Serverraum (On-Premise)', 'loc-server-room'),
  ('Server room (on-premise)', 'loc-server-room'),
  ('Homeoffices der Mitarbeitenden', 'loc-employee-homes'),
  ('Employee home offices', 'loc-employee-homes'),
  ('Weitere Büros / Filialen', 'loc-branch-offices'),
  ('Additional offices / branches', 'loc-branch-offices'),
  ('Produktionshalle oder Werkstatt', 'loc-production'),
  ('Production hall or workshop', 'loc-production'),
  ('Lager- oder Logistikstandort', 'loc-warehouse'),
  ('Warehouse or storage facility', 'loc-warehouse'),
  ('Technikräume und Netzwerkschränke', 'loc-technical-rooms'),
  ('Technical rooms and network cabinets', 'loc-technical-rooms'),
  ('Rechenzentrum (eigen oder gemietetes Rack)', 'loc-datacenter'),
  ('Datacenter (own or rented rack)', 'loc-datacenter'),
  ('Archivraum (Papierakten)', 'loc-archive'),
  ('Archive room (paper records)', 'loc-archive'),
  ('Internet-Anbindung (ISP)', 'net-internet'),
  ('Internet connection (ISP)', 'net-internet'),
  ('VPN oder Zero-Trust-Fernzugriff', 'net-vpn'),
  ('VPN or Zero Trust remote access', 'net-vpn'),
  ('Internes Netzwerk (LAN, Netzsegmente)', 'net-lan'),
  ('Internal network (LAN, network segments)', 'net-lan'),
  ('WLAN (Firmennetz und Gästenetz)', 'net-wifi'),
  ('Wi-Fi (company and guest networks)', 'net-wifi'),
  ('Mobilfunk und mobile Router (LTE, 5G)', 'net-mobile'),
  ('Mobile data and mobile routers (LTE, 5G)', 'net-mobile'),
  ('Standortkopplungen (Filialen, Partner)', 'net-site-to-site'),
  ('Site-to-site links (branches, partners)', 'net-site-to-site'),
  ('Fernwartungszugänge für Dienstleister', 'net-remote-maintenance'),
  ('Remote maintenance access for service providers', 'net-remote-maintenance'),
  ('Schnittstellen zu Drittanbietern (APIs)', 'net-third-party-api'),
  ('Third-party API integrations', 'net-third-party-api'),
  ('Telefonanschluss (SIP-Trunk)', 'net-phone-line'),
  ('Telephone line (SIP trunk)', 'net-phone-line'),
  ('SPS / SCADA-Steuerungen', 'sec-plc-scada'),
  ('PLC / SCADA controllers', 'sec-plc-scada'),
  ('MES (Manufacturing Execution System)', 'sec-mes'),
  ('CAD / PLM (Engineering-Daten)', 'sec-cad-plm'),
  ('CAD / PLM (engineering data)', 'sec-cad-plm'),
  ('Lagerverwaltungssystem (WMS)', 'sec-warehouse-mgmt'),
  ('Warehouse Management System (WMS)', 'sec-warehouse-mgmt'),
  ('Fahrzeuge mit Telematik / GPS', 'sec-fleet-vehicles'),
  ('Vehicles with telematics / GPS', 'sec-fleet-vehicles'),
  ('Vernetzte Medizingeräte', 'sec-medical-devices'),
  ('Networked medical devices', 'sec-medical-devices'),
  ('Krankenhausinformationssystem (KIS / HIS / EHR)', 'sec-ehr-his'),
  ('Hospital information system (KIS / HIS / EHR)', 'sec-ehr-his'),
  ('Vernetzte Laborgeräte / LIMS', 'sec-lab-instruments'),
  ('Networked lab instruments / LIMS', 'sec-lab-instruments'),
  ('Energie-SCADA / Leitsystem', 'sec-energy-scada'),
  ('Energy SCADA / control system', 'sec-energy-scada'),
  ('Wasser- / Abwasser-SCADA', 'sec-water-scada'),
  ('Water / wastewater SCADA', 'sec-water-scada'),
  ('Trading-Plattform-Anbindung (SWIFT, SEPA, Börse)', 'sec-trading-platform'),
  ('Trading platform connection (SWIFT, SEPA, exchange)', 'sec-trading-platform'),
  ('Geldautomaten / SB-Terminals', 'sec-atm-fleet'),
  ('ATM / self-service terminal fleet', 'sec-atm-fleet'),
  ('DNS / TLD-Infrastruktur', 'sec-dns-tld'),
  ('DNS / TLD infrastructure', 'sec-dns-tld')
  ) AS "known"("label", "id")
    ON "known"."label" IN (trim("a"."name"), trim("a"."description"))
  WHERE "a"."catalog_id" IS NULL
  ORDER BY "a"."id", ("known"."label" = trim("a"."name")) DESC
) AS "match"
WHERE "asset"."id" = "match"."asset_id";
