export { sendMail, sendWelcomeEmail, type SendMailOptions } from "./send";
export {
  inviteEmail,
  memberRemovedEmail,
  categoryAssignedEmail,
  categoryUnassignedEmail,
  contactEmailChangedEmail,
  reviewDecisionEmail,
  deadlineReminderEmail,
  deadlineUrgentEmail,
  deadlineOverdueEmail,
  dailyDigestEmail,
  weeklyManagementDigestEmail,
  escalationEmail,
  supplierIncidentBroadcastEmail,
  supplierAddedYouEmail,
  entityInvitesSupplierEmail,
  newUserSignupEmail,
  dataDeletionRequestEmail,
  courseFollowupEmail,
  newsletterEmail,
  emailVerificationCodeEmail,
  passwordResetCodeEmail,
  type DigestItem,
} from "./templates";
