export { sendAuthCode } from "./auth-code";
export { type SendMailOptions, sendMail, sendWelcomeEmail } from "./send";
export {
  accountSetupEmail,
  billingAlertEmail,
  categoryAssignedEmail,
  categoryUnassignedEmail,
  contactEmailChangedEmail,
  courseFollowupEmail,
  type DigestItem,
  type DigestNextStep,
  type DocumentEmail,
  type DocumentFact,
  dailyDigestEmail,
  documentEmail,
  emailVerificationCodeEmail,
  entityInvitesSupplierEmail,
  gdprAlertEmail,
  inviteEmail,
  memberRemovedEmail,
  newSaleEmail,
  newsletterEmail,
  newUserSignupEmail,
  passwordResetCodeEmail,
  registrationAttemptEmail,
  reviewDecisionEmail,
  supplierAddedYouEmail,
  supplierIncidentBroadcastEmail,
  weeklyManagementDigestEmail,
} from "./templates";
