ALTER TABLE "company" ADD COLUMN "service_description" text;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "data_processing_locations" varchar(1000);--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "incident_sla_hours" integer;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "is_saas" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "is_on_prem" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "is_professional_services" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "is_managed_service" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "uses_ai_systems" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "accept_right_to_audit" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "has_subprocessors" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "subprocessor_list" text;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "data_return_on_termination" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "dpa_available" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "incident_assistance_commitment" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "notify_material_changes" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "notify_on_location_change" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "has_exit_plan" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "provides_sbom_for_ai" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "ai_sbom_url" varchar(500);--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "saas_hosting_region" varchar(255);--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "saas_encryption_at_rest" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "saas_encryption_in_transit" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "saas_mfa_enforced" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "saas_rto_hours" integer;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "on_prem_sbom_provided" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "on_prem_signed_releases" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "on_prem_vulnerability_disclosure_policy" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "on_prem_patch_sla_critical_hours" integer;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "pro_services_background_check_scope" varchar(500);--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "pro_services_nda_in_place" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "pro_services_customer_premises_policy" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "managed_privileged_access_mgmt" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "managed_session_recording" boolean;--> statement-breakpoint
ALTER TABLE "company" ADD COLUMN "managed_on_call_24x7" boolean;