import { dictionaryTermSchema, type DictionaryTerm } from "@/lib/training/schemas";
import { z } from "zod";

// Locale values are filled from the `en` source by scripts/i18n/translate-course.ts.
const dictionary: DictionaryTerm[] = z.array(dictionaryTermSchema).parse([
  {
    "term": "SBOM",
    "type": "defined",
    "definition": {
      "en": "Software Bill of Materials. A machine-readable inventory of every software component in a product: names, versions, suppliers, and identifiers. Required for products with digital elements under Annex I, Part II, point (1) CRA.",
      "de": "Software Bill of Materials. Eine maschinenlesbare Bestandsliste aller Softwarekomponenten in einem Produkt: Namen, Versionen, Lieferanten und Identifikatoren. Erforderlich für Produkte mit digitalen Elementen gemäß Anhang I Teil II Nummer 1 CRA.",
      "nl": "Software Bill of Materials. Een machineleesbare inventaris van elk softwarecomponent in een product: namen, versies, leveranciers en identificatoren. Vereist voor producten met digitale elementen onder Bijlage I Deel II punt (1) CRA.",
      "fr": "Nomenclature des composants logiciels. Inventaire lisible par machine de chaque composant logiciel dans un produit : noms, versions, fournisseurs et identifiants. Obligatoire pour les produits comportant des éléments numériques conformément à l'annexe I, partie II, point (1) du CRA.",
      "it": "Software Bill of Materials. Un inventario leggibile da macchina di ogni componente software in un prodotto: nomi, versioni, fornitori e identificatori. Richiesto per i prodotti con elementi digitali ai sensi dell'Allegato I, Parte II, punto (1) CRA.",
      "es": "Lista de materiales de software. Un inventario legible por máquina de cada componente de software en un producto: nombres, versiones, proveedores e identificadores. Obligatorio para productos con elementos digitales según el Anexo I, Parte II, punto (1) del CRA.",
      "pl": "Software Bill of Materials. Maszynowo czytelny wykaz wszystkich komponentów oprogramowania w produkcie: nazwy, wersje, dostawcy oraz identyfikatory. Wymagany dla produktów z elementami cyfrowymi na podstawie Załącznik I Część II punkt (1) CRA.",
      "cs": "Software Bill of Materials. Strojově čitelný soupis všech softwarových komponent v produktu: názvy, verze, dodavatelé a identifikátory. Vyžadováno pro produkty s digitálními prvky podle Přílohy I část II bod (1) CRA.",
      "pt": "Software Bill of Materials. Um inventário legível por máquina de todos os componentes de software num produto: nomes, versões, fornecedores e identificadores. Obrigatório para produtos com elementos digitais ao abrigo do Anexo I, Parte II, ponto (1) do CRA.",
      "ro": "Software Bill of Materials. Un inventar lizibil automat al fiecărei componente software dintr-un produs: nume, versiuni, furnizori și identificatori. Obligatoriu pentru produsele cu elemente digitale conform Anexei I, Partea II, punctul (1) CRA."
    }
  },
  {
    "term": "Product with digital elements",
    "type": "defined",
    "definition": {
      "en": "Any hardware or software product that can connect, directly or indirectly, to another device or network. The core scope concept in Article 3(1) CRA. Covers physical devices with firmware, standalone software, apps, and operating systems.",
      "de": "Jedes Hardware- oder Softwareprodukt, das direkt oder indirekt mit einem anderen Gerät oder Netzwerk verbunden werden kann. Das zentrale Geltungsbereichskonzept in Artikel 3(1) CRA. Umfasst physische Geräte mit Firmware, eigenständige Software, Apps und Betriebssysteme.",
      "nl": "Elk hardware- of softwareproduct dat direct of indirect verbinding kan maken met een ander apparaat of netwerk. Het kernbegrip in Artikel 3(1) CRA. Omvat fysieke apparaten met firmware, standalone software, apps en besturingssystemen.",
      "fr": "Tout produit matériel ou logiciel pouvant se connecter, directement ou indirectement, à un autre appareil ou réseau. Concept central de portée défini à l'article 3(1) du CRA. Couvre les appareils physiques avec micrologiciel, les logiciels autonomes, les applications et les systèmes d'exploitation.",
      "it": "Qualsiasi prodotto hardware o software che può connettersi, direttamente o indirettamente, a un altro dispositivo o a una rete. Il concetto centrale di ambito di cui all'Articolo 3(1) CRA. Copre dispositivi fisici con firmware, software autonomo, app e sistemi operativi.",
      "es": "Cualquier producto de hardware o software que pueda conectarse, directa o indirectamente, a otro dispositivo o red. El concepto central de ámbito en el Artículo 3(1) del CRA. Abarca dispositivos físicos con firmware, software independiente, aplicaciones y sistemas operativos.",
      "pl": "Każdy produkt sprzętowy lub programowy, który może łączyć się bezpośrednio lub pośrednio z innym urządzeniem lub siecią. Podstawowe pojęcie zakresu w Artykuł 3(1) CRA. Obejmuje urządzenia fizyczne z oprogramowaniem układowym, oprogramowanie samodzielne, aplikacje oraz systemy operacyjne.",
      "cs": "Jakýkoli hardwarový nebo softwarový produkt, který se může přímo nebo nepřímo připojit k jinému zařízení nebo síti. Základní koncept rozsahu v Článku 3(1) CRA. Zahrnuje fyzická zařízení s firmwarem, samostatný software, aplikace a operační systémy.",
      "pt": "Qualquer produto de hardware ou software que possa ligar-se, direta ou indiretamente, a outro dispositivo ou rede. O conceito central de âmbito no Artigo 3(1) do CRA. Abrange dispositivos físicos com firmware, software independente, aplicações e sistemas operativos.",
      "ro": "Orice produs hardware sau software care se poate conecta, direct sau indirect, la un alt dispozitiv sau rețea. Conceptul central de domeniu de aplicare din Articolul 3(1) CRA. Acoperă dispozitive fizice cu firmware, software independent, aplicații și sisteme de operare."
    }
  },
  {
    "term": "Top-level dependency",
    "type": "defined",
    "definition": {
      "en": "A component that your product directly imports or links against. The CRA minimum in Annex I, Part II, point (1) requires the SBOM to cover at least these. If your code has `import requests` or `<dependency>spring-boot</dependency>`, those are top-level dependencies.",
      "de": "Eine Komponente, die Ihr Produkt direkt importiert oder gegen die es verlinkt. Die CRA-Mindestanforderung in Anhang I Teil II Nummer 1 verlangt, dass die SBOM mindestens diese abdeckt. Wenn Ihr Code `import requests` oder `<dependency>spring-boot</dependency>` enthält, handelt es sich dabei um Top-Level-Dependencies.",
      "nl": "Een component die uw product direct importeert of waartegen het linkt. De CRA-minimumvereiste in Bijlage I Deel II punt (1) vereist dat de SBOM ten minste deze dekt. Als uw code `import requests` of `<dependency>spring-boot</dependency>` bevat, zijn dat top-level dependencies.",
      "fr": "Composant que votre produit importe ou lie directement. L'exigence minimale du CRA à l'annexe I, partie II, point (1) impose que la SBOM couvre au moins ces éléments. Si votre code contient `import requests` ou `<dependency>spring-boot</dependency>`, il s'agit de dépendances de premier niveau.",
      "it": "Un componente che il prodotto importa o collega direttamente. Il minimo CRA di cui all'Allegato I, Parte II, punto (1) richiede che l'SBOM copra almeno questi. Se il codice contiene `import requests` o `<dependency>spring-boot</dependency>`, si tratta di dipendenze di primo livello.",
      "es": "Un componente que su producto importa o enlaza directamente. El mínimo del CRA en el Anexo I, Parte II, punto (1) exige que el SBOM cubra al menos estos. Si su código tiene `import requests` o `<dependency>spring-boot</dependency>`, esos son dependencias de nivel superior.",
      "pl": "Komponent, który produkt importuje lub linkuje bezpośrednio. Minimum CRA w Załącznik I Część II punkt (1) wymaga, aby SBOM obejmował co najmniej te komponenty. Jeśli kod zawiera `import requests` lub `<dependency>spring-boot</dependency>`, są to zależności najwyższego poziomu.",
      "cs": "Komponenta, kterou váš produkt přímo importuje nebo proti níž se linkuje. Minimum CRA v Příloze I část II bod (1) vyžaduje, aby SBOM pokrýval alespoň tyto. Pokud váš kód obsahuje `import requests` nebo `<dependency>spring-boot</dependency>`, jedná se o závislosti nejvyšší úrovně.",
      "pt": "Um componente que o seu produto importa ou liga diretamente. O mínimo exigido pelo CRA no Anexo I, Parte II, ponto (1) requer que o SBOM cubra pelo menos estes. Se o seu código tiver `import requests` ou `<dependency>spring-boot</dependency>`, esses são dependências de nível superior.",
      "ro": "O componentă pe care produsul dvs. o importă sau o leagă direct. Cerința minimă CRA din Anexa I, Partea II, punctul (1) impune ca SBOM-ul să acopere cel puțin aceste componente. Dacă codul dvs. conține `import requests` sau `<dependency>spring-boot</dependency>`, acestea sunt dependențe de nivel superior."
    }
  },
  {
    "term": "Transitive dependency",
    "type": "defined",
    "definition": {
      "en": "A component pulled in by one of your top-level dependencies, not by your code directly. Log4Shell (CVE-2021-44228) was a transitive dependency in thousands of applications whose teams had no idea it was there. The CRA minimum does not require listing these, but best practice does.",
      "de": "Eine Komponente, die durch eine Ihrer Top-Level-Dependencies eingebunden wird, nicht direkt durch Ihren Code. Log4Shell (CVE-2021-44228) war eine Transitive Dependency in Tausenden von Anwendungen, deren Teams keine Ahnung davon hatten. Die CRA-Mindestanforderung verlangt nicht die Auflistung dieser, bewährte Praxis jedoch schon.",
      "nl": "Een component die door een van uw top-level dependencies wordt meegehaald, niet direct door uw code. Log4Shell (CVE-2021-44228) was een transitive dependency in duizenden applicaties waarvan de teams geen idee hadden dat deze aanwezig was. De CRA-minimumvereiste vereist niet dat deze worden vermeld, maar best practice wel.",
      "fr": "Composant intégré par l'une de vos dépendances de premier niveau, et non directement par votre code. Log4Shell (CVE-2021-44228) était une dépendance transitive dans des milliers d'applications dont les équipes ignoraient la présence. L'exigence minimale du CRA n'impose pas de les lister, mais les bonnes pratiques le recommandent.",
      "it": "Un componente incluso da una delle dipendenze di primo livello, non direttamente dal codice. Log4Shell (CVE-2021-44228) era una dipendenza transitiva in migliaia di applicazioni i cui team non sapevano della sua presenza. Il minimo CRA non richiede di elencarle, ma la prassi ottimale sì.",
      "es": "Un componente incorporado por una de sus dependencias de nivel superior, no por su código directamente. Log4Shell (CVE-2021-44228) fue una dependencia transitiva en miles de aplicaciones cuyos equipos desconocían su presencia. El mínimo del CRA no exige listarlas, pero las mejores prácticas sí lo hacen.",
      "pl": "Komponent pobierany przez jedną z zależności najwyższego poziomu, a nie bezpośrednio przez kod. Log4Shell (CVE-2021-44228) był zależnością pośrednią w tysiącach aplikacji, o których zespoły nie wiedziały. Minimum CRA nie wymaga ich wymieniania, lecz dobre praktyki tak.",
      "cs": "Komponenta stažená jednou z vašich závislostí nejvyšší úrovně, nikoli přímo vaším kódem. Log4Shell (CVE-2021-44228) byla tranzitivní závislost v tisících aplikací, o jejichž týmech neměly tušení, že tam je. Minimum CRA nevyžaduje tyto položky uvádět, ale osvědčené postupy ano.",
      "pt": "Um componente obtido por uma das suas dependências de nível superior, não diretamente pelo seu código. O Log4Shell (CVE-2021-44228) era uma dependência transitiva em milhares de aplicações cujas equipas desconheciam a sua presença. O mínimo exigido pelo CRA não requer a listagem destas, mas as boas práticas recomendam-no.",
      "ro": "O componentă adusă de una dintre dependențele de nivel superior, nu direct de codul dvs. Log4Shell (CVE-2021-44228) a fost o dependență tranzitivă în mii de aplicații ale căror echipe nu știau de existența acesteia. Cerința minimă CRA nu impune listarea acestora, dar bunele practici o recomandă."
    }
  },
  {
    "term": "CycloneDX",
    "type": "defined",
    "definition": {
      "en": "An OWASP SBOM standard in JSON or XML format. Security-focused: built around vulnerability tracking, VEX statements, and CVE integration. Version 1.6 is current. The preferred format for CRA Article 14 compliance because it maps directly to vulnerability management workflows.",
      "de": "Ein OWASP-SBOM-Standard im JSON- oder XML-Format. Sicherheitsfokussiert: aufgebaut um Vulnerability-Tracking, VEX-Statements und CVE-Integration. Version 1.6 ist aktuell. Das bevorzugte Format für die CRA-Artikel-14-Konformität, da es direkt auf Vulnerability-Management-Workflows abbildet.",
      "nl": "Een OWASP-SBOM-standaard in JSON- of XML-formaat. Beveiligingsgericht: gebouwd rond kwetsbaarheidsregistratie, VEX-statements en CVE-integratie. Versie 1.6 is actueel. Het voorkeursformaat voor CRA Artikel 14-naleving omdat het direct aansluit op kwetsbaarheidsbeheerprocessen.",
      "fr": "Norme SBOM de l'OWASP au format JSON ou XML. Orientée sécurité : centrée sur le suivi des vulnérabilités, les déclarations VEX et l'intégration des CVE. La version 1.6 est la version actuelle. Format préféré pour la conformité à l'article 14 du CRA, car il correspond directement aux flux de gestion des vulnérabilités.",
      "it": "Uno standard OWASP per SBOM in formato JSON o XML. Orientato alla sicurezza: costruito intorno al tracciamento delle vulnerabilità, alle dichiarazioni VEX e all'integrazione CVE. La versione 1.6 è quella attuale. Il formato preferito per la conformità all'Articolo 14 CRA perché si collega direttamente ai flussi di gestione delle vulnerabilità.",
      "es": "Un estándar de SBOM de OWASP en formato JSON o XML. Orientado a la seguridad: construido en torno al seguimiento de vulnerabilidades, declaraciones VEX e integración de CVE. La versión 1.6 es la actual. El formato preferido para el cumplimiento del Artículo 14 del CRA porque se asigna directamente a los flujos de trabajo de gestión de vulnerabilidades.",
      "pl": "Standard SBOM OWASP w formacie JSON lub XML. Skupiony na bezpieczeństwie: zbudowany wokół śledzenia podatności, instrukcji VEX oraz integracji CVE. Aktualna jest wersja 1.6. Preferowany format do zgodności z Artykuł 14 CRA, ponieważ mapuje się bezpośrednio na procesy zarządzania podatnościami.",
      "cs": "Standard SBOM od OWASP ve formátu JSON nebo XML. Zaměřený na zabezpečení: postavený kolem sledování zranitelností, prohlášení VEX a integrace CVE. Aktuální je verze 1.6. Preferovaný formát pro soulad s Článkem 14 CRA, protože přímo mapuje na pracovní postupy správy zranitelností.",
      "pt": "Um padrão de SBOM da OWASP em formato JSON ou XML. Focado em segurança: construído em torno do rastreio de vulnerabilidades, declarações VEX e integração de CVE. A versão 1.6 é a atual. O formato preferido para conformidade com o Artigo 14 do CRA porque mapeia diretamente para fluxos de gestão de vulnerabilidades.",
      "ro": "Un standard OWASP SBOM în format JSON sau XML. Orientat spre securitate: construit în jurul urmăririi vulnerabilităților, a declarațiilor VEX și a integrării CVE. Versiunea 1.6 este actuală. Formatul preferat pentru conformitatea cu Articolul 14 CRA deoarece se mapează direct la fluxurile de lucru de gestionare a vulnerabilităților."
    }
  },
  {
    "term": "SPDX",
    "type": "defined",
    "definition": {
      "en": "Software Package Data Exchange. ISO/IEC 5962:2021 standard for SBOMs, originated at the Linux Foundation. License-focused: built around open-source license compliance and attribution. Available in JSON, YAML, RDF, and tag-value formats. Both CycloneDX and SPDX qualify as 'commonly used and machine-readable' formats under CRA Annex I, Part II, point (1).",
      "de": "Software Package Data Exchange. ISO/IEC-5962:2021-Standard für SBOMs, entstanden bei der Linux Foundation. Lizenzfokussiert: aufgebaut um Open-Source-Lizenzkonformität und Attribution. Verfügbar in JSON-, YAML-, RDF- und Tag-Value-Formaten. Sowohl CycloneDX als auch SPDX gelten als 'üblich verwendete und maschinenlesbare' Formate gemäß Anhang I Teil II Nummer 1 CRA.",
      "nl": "Software Package Data Exchange. ISO/IEC 5962:2021-standaard voor SBOMs, ontstaan bij de Linux Foundation. Licentiegericht: gebouwd rond naleving van open-source licenties en attributie. Beschikbaar in JSON-, YAML-, RDF- en tag-value-formaten. Zowel CycloneDX als SPDX kwalificeren als 'veelgebruikte en machineleesbare' formaten onder Bijlage I Deel II punt (1) CRA.",
      "fr": "Software Package Data Exchange. Norme ISO/IEC 5962:2021 pour les SBOM, issue de la Linux Foundation. Orientée licences : centrée sur la conformité aux licences open source et les attributions. Disponible aux formats JSON, YAML, RDF et tag-value. CycloneDX et SPDX sont tous deux considérés comme des formats « couramment utilisés et lisibles par machine » au titre de l'annexe I, partie II, point (1) du CRA.",
      "it": "Software Package Data Exchange. Standard ISO/IEC 5962:2021 per gli SBOM, originato dalla Linux Foundation. Orientato alle licenze: costruito intorno alla conformità e all'attribuzione delle licenze open source. Disponibile in formati JSON, YAML, RDF e tag-value. Sia CycloneDX sia SPDX si qualificano come formati «comunemente usati e leggibili da macchina» ai sensi dell'Allegato I, Parte II, punto (1) CRA.",
      "es": "Intercambio de datos de paquetes de software. Norma ISO/IEC 5962:2021 para SBOM, originada en la Linux Foundation. Orientado a licencias: construido en torno al cumplimiento de licencias de código abierto y la atribución. Disponible en formatos JSON, YAML, RDF y de valor de etiqueta. Tanto CycloneDX como SPDX cumplen como formatos «de uso común y legibles por máquina» según el Anexo I, Parte II, punto (1) del CRA.",
      "pl": "Software Package Data Exchange. Standard ISO/IEC 5962:2021 dla SBOM-ów, powstały w Linux Foundation. Skupiony na licencjach: zbudowany wokół zgodności licencji open source i atrybucji. Dostępny w formatach JSON, YAML, RDF oraz tag-value. Zarówno CycloneDX, jak i SPDX kwalifikują się jako formaty powszechnie używane i maszynowo czytelne zgodnie z Załącznik I Część II punkt (1) CRA.",
      "cs": "Software Package Data Exchange. Standard ISO/IEC 5962:2021 pro SBOM, vzniklý v Linux Foundation. Zaměřený na licence: postavený kolem souladu s licencemi open source a atribuci. Dostupný ve formátech JSON, YAML, RDF a tag-value. CycloneDX i SPDX splňují požadavek na „běžně používané a strojově čitelné“ formáty podle Přílohy I část II bod (1) CRA.",
      "pt": "Software Package Data Exchange. Norma ISO/IEC 5962:2021 para SBOMs, originada na Linux Foundation. Focada em licenças: construída em torno da conformidade e atribuição de licenças de código aberto. Disponível em formatos JSON, YAML, RDF e tag-value. Tanto o CycloneDX como o SPDX qualificam-se como formatos \"comumente usados e legíveis por máquina\" ao abrigo do Anexo I, Parte II, ponto (1) do CRA.",
      "ro": "Software Package Data Exchange. Standardul ISO/IEC 5962:2021 pentru SBOM-uri, originar de la Linux Foundation. Orientat spre licențe: construit în jurul conformității cu licențele open-source și a atribuirii. Disponibil în formate JSON, YAML, RDF și tag-value. Atât CycloneDX cât și SPDX se califică drept formate „utilizate în mod obișnuit și lizibile automat” conform Anexei I, Partea II, punctul (1) CRA."
    }
  },
  {
    "term": "PURL",
    "type": "defined",
    "definition": {
      "en": "Package URL. A standard identifier for software components: `pkg:type/namespace/name@version`. For example, `pkg:npm/%40angular/core@17.0.0`. PURLs are the recommended unique identifier in both CycloneDX and SPDX, and the practical anchor for linking an SBOM component to a CVE database entry.",
      "de": "Package URL. Ein Standardidentifikator für Softwarekomponenten: `pkg:type/namespace/name@version`. Zum Beispiel `pkg:npm/%40angular/core@17.0.0`. PURLs sind der empfohlene eindeutige Identifikator sowohl in CycloneDX als auch in SPDX und der praktische Anker zum Verknüpfen einer SBOM-Komponente mit einem CVE-Datenbankeintrag.",
      "nl": "Package URL. Een standaardidentificator voor softwarecomponenten: `pkg:type/namespace/name@version`. Bijvoorbeeld `pkg:npm/%40angular/core@17.0.0`. PURLs zijn de aanbevolen unieke identificator in zowel CycloneDX als SPDX en het praktische anker voor het koppelen van een SBOM-component aan een CVE-databasevermelding.",
      "fr": "Package URL. Identifiant normalisé pour les composants logiciels : `pkg:type/namespace/name@version`. Par exemple, `pkg:npm/%40angular/core@17.0.0`. Les PURL constituent l'identifiant unique recommandé dans CycloneDX et SPDX, et le point d'ancrage pratique pour lier un composant de SBOM à une entrée de base de données CVE.",
      "it": "Package URL. Un identificatore standard per i componenti software: `pkg:type/namespace/name@version`. Ad esempio `pkg:npm/%40angular/core@17.0.0`. I PURL sono l'identificatore univoco raccomandato sia in CycloneDX sia in SPDX e l'ancora pratica per collegare un componente dell'SBOM a una voce del database CVE.",
      "es": "URL de paquete. Un identificador estándar para componentes de software: `pkg:type/namespace/name@version`. Por ejemplo, `pkg:npm/%40angular/core@17.0.0`. Los PURL son el identificador único recomendado tanto en CycloneDX como en SPDX, y el ancla práctica para vincular un componente de SBOM a una entrada de base de datos de CVE.",
      "pl": "Package URL. Standardowy identyfikator komponentów oprogramowania: `pkg:type/namespace/name@version`. Na przykład `pkg:npm/%40angular/core@17.0.0`. PURL są zalecanym unikalnym identyfikatorem zarówno w CycloneDX, jak i SPDX oraz praktycznym łącznikiem między komponentem SBOM a wpisem w bazie CVE.",
      "cs": "Package URL. Standardní identifikátor softwarových komponent: `pkg:type/namespace/name@version`. Například `pkg:npm/%40angular/core@17.0.0`. PURL jsou doporučeným jedinečným identifikátorem v CycloneDX i SPDX a praktickou kotvou pro propojení komponenty SBOM se záznamem v databázi CVE.",
      "pt": "Package URL. Um identificador normalizado para componentes de software: `pkg:type/namespace/name@version`. Por exemplo, `pkg:npm/%40angular/core@17.0.0`. Os PURLs são o identificador único recomendado tanto no CycloneDX como no SPDX, e a âncora prática para ligar um componente do SBOM a uma entrada na base de dados de CVE.",
      "ro": "Package URL. Un identificator standard pentru componentele software: `pkg:type/namespace/name@version`. De exemplu, `pkg:npm/%40angular/core@17.0.0`. PURL-urile sunt identificatorul unic recomandat atât în CycloneDX cât și în SPDX și ancora practică pentru legarea unei componente SBOM la o intrare din baza de date CVE."
    }
  },
  {
    "term": "CVE",
    "type": "vocabulary",
    "definition": {
      "en": "Common Vulnerabilities and Exposures. The standardised identifier for publicly known cybersecurity vulnerabilities. Format: CVE-YEAR-NUMBER (e.g. CVE-2021-44228 for Log4Shell). An SBOM linked to a CVE database tells you which known vulnerabilities affect your product.",
      "de": "Common Vulnerabilities and Exposures. Der standardisierte Identifikator für öffentlich bekannte Cybersicherheitslücken. Format: CVE-YEAR-NUMBER (z. B. CVE-2021-44228 für Log4Shell). Eine mit einer CVE-Datenbank verknüpfte SBOM zeigt Ihnen, welche bekannten Schwachstellen Ihr Produkt betreffen.",
      "nl": "Common Vulnerabilities and Exposures. De gestandaardiseerde identificator voor publiek bekende cybersecurity-kwetsbaarheden. Formaat: CVE-JAAR-NUMMER (bijv. CVE-2021-44228 voor Log4Shell). Een SBOM die aan een CVE-database is gekoppeld, toont welke bekende kwetsbaarheden uw product treffen.",
      "fr": "Common Vulnerabilities and Exposures. Identifiant normalisé des vulnérabilités de cybersécurité publiquement connues. Format : CVE-ANNÉE-NUMÉRO (par exemple CVE-2021-44228 pour Log4Shell). Une SBOM liée à une base de données CVE indique quelles vulnérabilités connues affectent votre produit.",
      "it": "Common Vulnerabilities and Exposures. L'identificatore standardizzato per le vulnerabilità di cybersecurity note pubblicamente. Formato: CVE-YEAR-NUMBER (ad esempio CVE-2021-44228 per Log4Shell). Un SBOM collegato a un database CVE indica quali vulnerabilità note interessano il prodotto.",
      "es": "Vulnerabilidades y exposiciones comunes. El identificador normalizado para vulnerabilidades de ciberseguridad de conocimiento público. Formato: CVE-YEAR-NUMBER (por ejemplo, CVE-2021-44228 para Log4Shell). Un SBOM vinculado a una base de datos de CVE indica qué vulnerabilidades conocidas afectan a su producto.",
      "pl": "Common Vulnerabilities and Exposures. Standaryzowany identyfikator publicznie znanych podatności cyberbezpieczeństwa. Format: CVE-ROK-NUMER (np. CVE-2021-44228 dla Log4Shell). SBOM powiązany z bazą CVE informuje, które znane podatności dotyczą produktu.",
      "cs": "Common Vulnerabilities and Exposures. Standardizovaný identifikátor veřejně známých kybernetických zranitelností. Formát: CVE-YEAR-NUMBER (např. CVE-2021-44228 pro Log4Shell). SBOM propojený s databází CVE ukazuje, které známé zranitelnosti ovlivňují váš produkt.",
      "pt": "Common Vulnerabilities and Exposures. O identificador normalizado para vulnerabilidades de cibersegurança conhecidas publicamente. Formato: CVE-YEAR-NUMBER (por exemplo, CVE-2021-44228 para o Log4Shell). Um SBOM ligado a uma base de dados de CVE indica quais vulnerabilidades conhecidas afetam o seu produto.",
      "ro": "Common Vulnerabilities and Exposures. Identificatorul standardizat pentru vulnerabilitățile de securitate cibernetică cunoscute public. Format: CVE-YEAR-NUMBER (de exemplu CVE-2021-44228 pentru Log4Shell). Un SBOM legat de o bază de date CVE vă indică ce vulnerabilități cunoscute afectează produsul dvs."
    }
  },
  {
    "term": "VEX",
    "type": "defined",
    "definition": {
      "en": "Vulnerability Exploitability eXchange. A statement attached to an SBOM that documents whether a known CVE actually affects your product and why. Supported natively in CycloneDX. A VEX statement of 'not affected' with a justification is strong evidence in an Article 14 audit.",
      "de": "Vulnerability Exploitability eXchange. Eine einer SBOM beigefügte Erklärung, die dokumentiert, ob eine bekannte CVE Ihr Produkt tatsächlich betrifft und warum. Nativ in CycloneDX unterstützt. Ein VEX-Statement 'not affected' mit Begründung ist starkes Beweismaterial in einer Artikel-14-Prüfung.",
      "nl": "Vulnerability Exploitability eXchange. Een statement dat aan een SBOM is gekoppeld en documenteert of een bekende CVE uw product daadwerkelijk treft en waarom. Native ondersteund in CycloneDX. Een VEX-statement 'not affected' met een motivering vormt sterk bewijs in een Artikel 14-audit.",
      "fr": "Vulnerability Exploitability eXchange. Déclaration jointe à une SBOM qui indique si un CVE connu affecte réellement votre produit et pourquoi. Prise en charge native dans CycloneDX. Une déclaration VEX de type « non affecté » accompagnée d'une justification constitue une preuve solide lors d'un audit au titre de l'article 14.",
      "it": "Vulnerability Exploitability eXchange. Una dichiarazione allegata a un SBOM che documenta se un CVE noto influisce effettivamente sul prodotto e perché. Supportato nativamente in CycloneDX. Una dichiarazione VEX «not affected» con giustificazione costituisce una prova solida in un audit ai sensi dell'Articolo 14.",
      "es": "Intercambio de explotabilidad de vulnerabilidades. Una declaración adjunta a un SBOM que documenta si un CVE conocido afecta realmente a su producto y por qué. Compatible de forma nativa en CycloneDX. Una declaración VEX de «no afectado» con justificación constituye una prueba sólida en una auditoría del Artículo 14.",
      "pl": "Vulnerability Exploitability eXchange. Oświadczenie dołączone do SBOM, które dokumentuje, czy znane CVE faktycznie dotyczy produktu i dlaczego. Obsługiwane natywnie w CycloneDX. Oświadczenie VEX o braku wpływu z uzasadnieniem stanowi mocny dowód podczas audytu Artykuł 14.",
      "cs": "Vulnerability Exploitability eXchange. Prohlášení připojené k SBOM, které dokumentuje, zda známé CVE skutečně ovlivňuje váš produkt a proč. Nativně podporováno v CycloneDX. Prohlášení VEX typu „not affected“ s odůvodněním je silným důkazem při auditu podle Článku 14.",
      "pt": "Vulnerability Exploitability eXchange. Uma declaração anexada a um SBOM que documenta se um CVE conhecido afeta realmente o seu produto e porquê. Suportado nativamente no CycloneDX. Uma declaração VEX de \"não afetado\" com justificação constitui prova robusta numa auditoria ao Artigo 14.",
      "ro": "Vulnerability Exploitability eXchange. O declarație atașată unui SBOM care documentează dacă un CVE cunoscut afectează efectiv produsul dvs. și de ce. Acceptat nativ în CycloneDX. O declarație VEX de tip „not affected” cu justificare reprezintă o probă solidă într-un audit conform Articolului 14."
    }
  },
  {
    "term": "Actively exploited vulnerability",
    "type": "defined",
    "definition": {
      "en": "A vulnerability in your product that a malicious actor is currently using against real systems, without the permission of the system owner. The trigger for the Article 14(1) CRA 24-hour reporting obligation. Distinguished from a publicly disclosed but not yet exploited vulnerability.",
      "de": "Eine Schwachstelle in Ihrem Produkt, die ein böswilliger Akteur derzeit gegen reale Systeme einsetzt, ohne Erlaubnis des Systemeigentümers. Der Auslöser für die 24-Stunden-Meldepflicht nach Artikel 14(1) CRA. Abzugrenzen von einer öffentlich bekannt gemachten, aber noch nicht ausgenutzten Schwachstelle.",
      "nl": "Een kwetsbaarheid in uw product die een kwaadwillende momenteel gebruikt tegen echte systemen, zonder toestemming van de systeembeheerder. De trigger voor de rapportageverplichting van 24 uur in Artikel 14(1) CRA. Onderscheiden van een publiek bekendgemaakte maar nog niet geëxploiteerde kwetsbaarheid.",
      "fr": "Vulnérabilité de votre produit qu'un acteur malveillant utilise actuellement contre des systèmes réels, sans autorisation du propriétaire du système. Déclencheur de l'obligation de notification dans les 24 heures prévue à l'article 14(1) du CRA. À distinguer d'une vulnérabilité publiquement divulguée mais pas encore exploitée.",
      "it": "Una vulnerabilità nel prodotto che un attore malevolo sta attualmente sfruttando contro sistemi reali, senza il permesso del titolare del sistema. Il fattore scatenante dell'obbligo di segnalazione entro 24 ore di cui all'Articolo 14(1) CRA. Si distingue da una vulnerabilità divulgata pubblicamente ma non ancora sfruttata.",
      "es": "Una vulnerabilidad en su producto que un actor malicioso está utilizando actualmente contra sistemas reales, sin el permiso del propietario del sistema. El desencadenante de la obligación de notificación en 24 horas del Artículo 14(1) del CRA. Se distingue de una vulnerabilidad divulgada públicamente pero aún no explotada.",
      "pl": "Podatność w produkcie, z której aktualnie korzysta złośliwy podmiot przeciwko rzeczywistym systemom bez zgody właściciela systemu. Wyzwalacz 24-godzinnego obowiązku zgłaszania zgodnie z Artykuł 14(1) CRA. Odróżnia się od podatności ujawnionej publicznie, lecz jeszcze niewykorzystywanej.",
      "cs": "Zranitelnost ve vašem produktu, kterou škodlivý aktér aktuálně využívá proti reálným systémům bez souhlasu vlastníka systému. Spouštěč 24hodinové oznamovací povinnosti podle Článku 14(1) CRA. Liší se od veřejně zveřejněné, ale dosud nevyužívané zranitelnosti.",
      "pt": "Uma vulnerabilidade no seu produto que um agente malicioso está atualmente a utilizar contra sistemas reais, sem autorização do proprietário do sistema. O gatilho para a obrigação de comunicação no prazo de 24 horas prevista no Artigo 14(1) do CRA. Distingue-se de uma vulnerabilidade divulgada publicamente mas ainda não explorada.",
      "ro": "O vulnerabilitate din produsul dvs. pe care un actor rău intenționat o exploatează în prezent împotriva unor sisteme reale, fără permisiunea proprietarului sistemului. Declanșatorul obligației de raportare în 24 de ore conform Articolului 14(1) CRA. Se distinge de o vulnerabilitate divulgată public dar încă neexploatată."
    }
  },
  {
    "term": "Market surveillance authority",
    "type": "vocabulary",
    "definition": {
      "en": "The national authority that checks CRA compliance in each EU member state. In Germany this function sits with the BSI. Market surveillance authorities can request your technical documentation, including the SBOM, at any time. You must provide it within a reasonable timeframe, not make it publicly available.",
      "de": "Die nationale Behörde, die die CRA-Konformität in jedem EU-Mitgliedstaat prüft. In Deutschland liegt diese Funktion beim BSI. Marktüberwachungsbehörden können Ihre technischen Unterlagen, einschließlich der SBOM, jederzeit anfordern. Sie müssen sie innerhalb eines angemessenen Zeitraums bereitstellen, nicht öffentlich zugänglich machen.",
      "nl": "De nationale autoriteit die CRA-naleving controleert in elke EU-lidstaat. In Duitsland ligt deze functie bij de BSI. Markttoezichtautoriteiten kunnen uw technische documentatie, inclusief de SBOM, op elk moment opvragen. U moet deze binnen een redelijke termijn verstrekken en deze niet openbaar maken.",
      "fr": "Autorité nationale chargée de vérifier la conformité au CRA dans chaque État membre de l'UE. En Allemagne, cette fonction est assurée par le BSI. Les autorités de surveillance du marché peuvent demander votre documentation technique, y compris la SBOM, à tout moment. Vous devez la fournir dans un délai raisonnable, sans la rendre publique.",
      "it": "L'autorità nazionale che verifica la conformità al CRA in ciascuno Stato membro dell'UE. In Germania questa funzione è affidata al BSI. Le autorità di vigilanza del mercato possono richiedere la documentazione tecnica, incluso l'SBOM, in qualsiasi momento. Occorre fornirla entro un termine ragionevole e non renderla pubblica.",
      "es": "La autoridad nacional que verifica el cumplimiento del CRA en cada Estado miembro de la UE. En Alemania esta función corresponde al BSI. Las autoridades de vigilancia del mercado pueden solicitar su documentación técnica, incluido el SBOM, en cualquier momento. Debe facilitarla en un plazo razonable y no hacerla pública.",
      "pl": "Krajowy organ sprawdzający zgodność z CRA w każdym państwie członkowskim UE. W Niemczech funkcję tę pełni BSI. Organy nadzoru rynku mogą w dowolnym momencie zażądać dokumentacji technicznej, w tym SBOM. Należy ją dostarczyć w rozsądnym terminie, nie udostępniając publicznie.",
      "cs": "Národní orgán, který v každém členském státě EU kontroluje soulad s CRA. V Německu tuto funkci vykonává BSI. Orgány dohledu nad trhem mohou kdykoli požadovat vaši technickou dokumentaci, včetně SBOM. Musíte ji poskytnout v přiměřené lhůtě, nesmíte ji zveřejňovat.",
      "pt": "A autoridade nacional que verifica a conformidade com o CRA em cada Estado-Membro da UE. Na Alemanha esta função cabe ao BSI. As autoridades de vigilância do mercado podem solicitar a sua documentação técnica, incluindo o SBOM, em qualquer momento. Deve fornecê-la num prazo razoável e não torná-la publicamente disponível.",
      "ro": "Autoritatea națională care verifică conformitatea cu CRA în fiecare stat membru UE. În Germania această funcție revine BSI. Autoritățile de supraveghere a pieței pot solicita oricând documentația tehnică, inclusiv SBOM-ul. Trebuie să o furnizați într-un termen rezonabil, fără a o face publică."
    }
  },
  {
    "term": "Technical documentation",
    "type": "defined",
    "definition": {
      "en": "The set of documents a manufacturer must compile and keep under CRA Article 31 and Annex VII. Includes the SBOM, risk assessment, secure design decisions, test results, and the EU declaration of conformity. Must be retained for 10 years after the product is placed on the market, or for the support period, whichever is longer.",
      "de": "Die Dokumentensammlung, die ein Hersteller gemäß Artikel 31 CRA und Anhang VII zusammenstellen und aufbewahren muss. Umfasst die SBOM, Risikobewertung, sichere Designentscheidungen, Testergebnisse und die EU-Konformitätserklärung. Muss 10 Jahre nach dem Inverkehrbringen des Produkts oder für den Supportzeitraum, je nachdem, welcher länger ist, aufbewahrt werden.",
      "nl": "Het geheel documenten dat een fabrikant moet samenstellen en bewaren onder Artikel 31 en Bijlage VII CRA. Omvat de SBOM, risicobeoordeling, beslissingen over secure design, testresultaten en de EU-conformiteitsverklaring. Moet 10 jaar na het op de markt brengen van het product worden bewaard, of gedurende de supportperiode, afhankelijk van welke langer is.",
      "fr": "Ensemble de documents qu'un fabricant doit compiler et conserver conformément à l'article 31 et à l'annexe VII du CRA. Comprend la SBOM, l'évaluation des risques, les décisions de conception sécurisée, les résultats des tests et la déclaration UE de conformité. Doit être conservé pendant 10 ans après la mise sur le marché du produit, ou pendant la période de support, la durée la plus longue étant retenue.",
      "it": "L'insieme dei documenti che un fabbricante deve compilare e conservare ai sensi dell'Articolo 31 CRA e dell'Allegato VII. Include l'SBOM, la valutazione dei rischi, le decisioni di progettazione sicura, i risultati dei test e la dichiarazione UE di conformità. Devono essere conservati per 10 anni dopo l'immissione del prodotto sul mercato o per il periodo di supporto, a seconda di quale sia più lungo.",
      "es": "El conjunto de documentos que un fabricante debe compilar y conservar según el Artículo 31 del CRA y el Anexo VII. Incluye el SBOM, la evaluación de riesgos, las decisiones de diseño seguro, los resultados de las pruebas y la declaración UE de conformidad. Deben conservarse durante 10 años después de que el producto se comercialice, o durante el período de soporte, lo que sea más largo.",
      "pl": "Zbiór dokumentów, które producent musi sporządzić i przechowywać zgodnie z Artykuł 31 CRA oraz Załącznik VII. Obejmuje SBOM, ocenę ryzyka, decyzje dotyczące bezpiecznego projektowania, wyniki testów oraz deklarację zgodności UE. Dokumenty należy przechowywać przez 10 lat po wprowadzeniu produktu do obrotu lub przez okres wsparcia, w zależności od tego, co jest dłuższe.",
      "cs": "Soubor dokumentů, které musí výrobce sestavit a uchovávat podle Článku 31 CRA a Přílohy VII. Zahrnuje SBOM, posouzení rizik, rozhodnutí o zabezpečeném návrhu, výsledky testů a prohlášení EU o shodě. Musí být uchováváno 10 let po uvedení produktu na trh nebo po dobu podpory, podle toho, co je delší.",
      "pt": "O conjunto de documentos que um fabricante deve compilar e conservar ao abrigo do Artigo 31 e do Anexo VII do CRA. Inclui o SBOM, a avaliação de riscos, as decisões de conceção segura, os resultados dos testes e a declaração de conformidade da UE. Deve ser conservado durante 10 anos após a colocação do produto no mercado, ou durante o período de suporte, consoante o que for mais longo.",
      "ro": "Setul de documente pe care un producător trebuie să le compileze și să le păstreze conform Articolului 31 CRA și Anexei VII. Include SBOM-ul, evaluarea riscurilor, deciziile de proiectare securizată, rezultatele testelor și declarația de conformitate UE. Trebuie păstrate timp de 10 ani după introducerea pe piață a produsului sau pe durata perioadei de suport, oricare este mai lungă."
    }
  },
  {
    "term": "Support period",
    "type": "defined",
    "definition": {
      "en": "The time during which a manufacturer provides security updates for a product. CRA Article 13(8) requires the support period to be at least five years, or the expected use time if the product is expected to be in use for less than five years. The SBOM retention period runs for 10 years or until the end of this support period, whichever is longer.",
      "de": "Der Zeitraum, in dem ein Hersteller Sicherheitsupdates für ein Produkt bereitstellt. Artikel 13(8) CRA verlangt, dass der Supportzeitraum mindestens fünf Jahre beträgt oder der erwarteten Nutzungsdauer, wenn das Produkt voraussichtlich weniger als fünf Jahre genutzt wird. Der SBOM-Aufbewahrungszeitraum läuft 10 Jahre oder bis zum Ende dieses Supportzeitraums, je nachdem, welcher länger ist.",
      "nl": "De periode waarin een fabrikant beveiligingsupdates voor een product levert. Artikel 13(8) CRA vereist dat de supportperiode ten minste vijf jaar bedraagt, of de verwachte gebruiksduur als het product naar verwachting korter dan vijf jaar in gebruik is. De bewaartermijn van de SBOM loopt 10 jaar of tot het einde van deze supportperiode, afhankelijk van welke langer is.",
      "fr": "Période pendant laquelle un fabricant fournit des mises à jour de sécurité pour un produit. L'article 13(8) du CRA exige que la période de support soit d'au moins cinq ans, ou égale à la durée d'utilisation prévue si celle-ci est inférieure à cinq ans. La période de conservation de la SBOM court sur 10 ans ou jusqu'à la fin de cette période de support, la durée la plus longue étant retenue.",
      "it": "Il periodo durante il quale un fabbricante fornisce aggiornamenti di sicurezza per un prodotto. L'Articolo 13(8) CRA richiede che il periodo di supporto sia di almeno cinque anni, o il tempo di utilizzo previsto se il prodotto è destinato a essere utilizzato per meno di cinque anni. Il periodo di conservazione dell'SBOM è di 10 anni o fino alla fine di questo periodo di supporto, a seconda di quale sia più lungo.",
      "es": "El tiempo durante el cual un fabricante proporciona actualizaciones de seguridad para un producto. El Artículo 13(8) del CRA exige que el período de soporte sea de al menos cinco años, o el tiempo de uso previsto si se espera que el producto se utilice menos de cinco años. El período de conservación del SBOM se extiende durante 10 años o hasta el final de este período de soporte, lo que sea más largo.",
      "pl": "Okres, w którym producent dostarcza aktualizacje zabezpieczeń dla produktu. Artykuł 13(8) CRA wymaga, aby okres wsparcia wynosił co najmniej pięć lat lub oczekiwany czas użytkowania, jeśli produkt ma być używany krócej niż pięć lat. Okres przechowywania SBOM wynosi 10 lat lub do końca tego okresu wsparcia, w zależności od tego, co jest dłuższe.",
      "cs": "Doba, po kterou výrobce poskytuje bezpečnostní aktualizace pro produkt. Článek 13(8) CRA vyžaduje, aby doba podpory činila alespoň pět let, nebo očekávanou dobu používání, je-li produkt očekáván v používání po dobu kratší než pět let. Doba uchovávání SBOM běží 10 let nebo do konce této doby podpory, podle toho, co je delší.",
      "pt": "O período durante o qual um fabricante fornece atualizações de segurança para um produto. O Artigo 13(8) do CRA exige que o período de suporte seja de pelo menos cinco anos, ou o tempo de utilização previsto se este for inferior a cinco anos. O período de conservação do SBOM decorre durante 10 anos ou até ao fim deste período de suporte, consoante o que for mais longo.",
      "ro": "Perioada în care un producător furnizează actualizări de securitate pentru un produs. Articolul 13(8) CRA impune ca perioada de suport să fie de cel puțin cinci ani sau timpul de utilizare estimat dacă produsul este prevăzut a fi utilizat mai puțin de cinci ani. Perioada de păstrare a SBOM-ului rulează timp de 10 ani sau până la sfârșitul acestei perioade de suport, oricare este mai lungă."
    }
  },
  {
    "term": "ENISA",
    "type": "vocabulary",
    "definition": {
      "en": "European Union Agency for Cybersecurity. Receives Article 14 CRA vulnerability and incident reports via the Single Reporting Platform (operational September 11, 2026). Also receives NIS 2 Article 23 early warnings for certain entity types.",
      "de": "Agentur der Europäischen Union für Cybersicherheit. Empfängt Meldungen zu Schwachstellen und Vorfällen nach Artikel 14 CRA über die Single Reporting Platform (betriebsbereit ab 11. September 2026). Empfängt auch Frühwarnungen nach Artikel 23 NIS 2 für bestimmte Entitätstypen.",
      "nl": "European Union Agency for Cybersecurity. Ontvangt Artikel 14 CRA-kwetsbaarheids- en incidentmeldingen via het Single Reporting Platform (operationeel vanaf 11 september 2026). Ontvangt ook NIS 2 Artikel 23 vroegtijdige waarschuwingen voor bepaalde entiteitstypen.",
      "fr": "Agence de l'Union européenne pour la cybersécurité. Reçoit les notifications de vulnérabilités et d'incidents au titre de l'article 14 du CRA via la plateforme de notification unique (opérationnelle le 11 septembre 2026). Reçoit également les alertes précoces au titre de l'article 23 de NIS 2 pour certains types d'entités.",
      "it": "Agenzia dell'Unione europea per la cibersicurezza. Riceve le segnalazioni di vulnerabilità e incidenti ai sensi dell'Articolo 14 CRA tramite la Piattaforma unica di segnalazione (operativa dall'11 settembre 2026). Riceve inoltre gli avvisi precoci ai sensi dell'Articolo 23 NIS 2 per determinati tipi di entità.",
      "es": "Agencia de la Unión Europea para la Ciberseguridad. Recibe los informes de vulnerabilidades e incidentes del Artículo 14 del CRA a través de la Plataforma Única de Notificación (operativa a partir del 11 de septiembre de 2026). También recibe las advertencias tempranas del Artículo 23 de NIS 2 para determinados tipos de entidades.",
      "pl": "Agencja Unii Europejskiej ds. Cyberbezpieczeństwa. Otrzymuje zgłoszenia podatności i incydentów zgodnie z Artykuł 14 CRA za pośrednictwem Jednolitej Platformy Zgłaszania (uruchomionej 11 września 2026). Otrzymuje także wczesne ostrzeżenia zgodnie z Artykuł 23 NIS 2 dla określonych typów podmiotów.",
      "cs": "Agentura Evropské unie pro kybernetickou bezpečnost. Přijímá hlášení o zranitelnostech a incidentech podle Článku 14 CRA prostřednictvím jednotné oznamovací platformy (provozní od 11. září 2026). Přijímá také včasná varování podle Článku 23 NIS 2 pro určité typy subjektů.",
      "pt": "Agência da União Europeia para a Cibersegurança. Recebe comunicações de vulnerabilidades e incidentes do Artigo 14 do CRA através da Plataforma Única de Comunicação (operacional a 11 de setembro de 2026). Recebe igualmente os alertas antecipados do Artigo 23 da NIS 2 para determinados tipos de entidades.",
      "ro": "European Union Agency for Cybersecurity. Primește rapoartele de vulnerabilități și incidente conform Articolului 14 CRA prin Single Reporting Platform (operațional la 11 septembrie 2026). Primește de asemenea avertismentele timpurii conform Articolului 23 NIS 2 pentru anumite tipuri de entități."
    }
  },
  {
    "term": "Coordinated vulnerability disclosure",
    "type": "defined",
    "definition": {
      "en": "A process where a security researcher privately reports a vulnerability to the manufacturer before publishing details publicly. CRA Article 13(6) requires manufacturers to have a policy for accepting and processing such disclosures. Typically implemented via a security.txt file and a dedicated security contact.",
      "de": "Ein Verfahren, bei dem ein Sicherheitsforscher eine Schwachstelle dem Hersteller privat meldet, bevor Details öffentlich veröffentlicht werden. Artikel 13(6) CRA verlangt von Herstellern eine Richtlinie zur Annahme und Bearbeitung solcher Offenlegungen. Typischerweise umgesetzt über eine security.txt-Datei und einen dedizierten Sicherheitskontakt.",
      "nl": "Een proces waarbij een security researcher een kwetsbaarheid privé meldt bij de fabrikant voordat details openbaar worden gemaakt. Artikel 13(6) CRA vereist dat fabrikanten een beleid hebben voor het accepteren en verwerken van dergelijke meldingen. Doorgaans geïmplementeerd via een security.txt-bestand en een specifiek beveiligingscontact.",
      "fr": "Processus par lequel un chercheur en sécurité signale une vulnérabilité au fabricant de manière privée avant de publier les détails publiquement. L'article 13(6) du CRA impose aux fabricants d'avoir une politique d'acceptation et de traitement de ces signalements. Généralement mis en œuvre via un fichier security.txt et un contact sécurité dédié.",
      "it": "Un processo in cui un ricercatore di sicurezza segnala privatamente una vulnerabilità al fabbricante prima di pubblicarne i dettagli. L'Articolo 13(6) CRA richiede che i fabbricanti dispongano di una politica per accettare ed elaborare tali segnalazioni. Di norma attuata tramite un file security.txt e un contatto dedicato per la sicurezza.",
      "es": "Un proceso en el que un investigador de seguridad informa de forma privada de una vulnerabilidad al fabricante antes de publicar los detalles públicamente. El Artículo 13(6) del CRA exige que los fabricantes tengan una política para aceptar y tramitar tales divulgaciones. Habitualmente se implementa mediante un archivo security.txt y un contacto de seguridad dedicado.",
      "pl": "Proces, w którym badacz bezpieczeństwa prywatnie zgłasza podatność producentowi przed publicznym ujawnieniem szczegółów. Artykuł 13(6) CRA wymaga, aby producenci posiadali politykę przyjmowania i przetwarzania takich zgłoszeń. Zazwyczaj realizowany za pomocą pliku security.txt oraz dedykowanego kontaktu ds. bezpieczeństwa.",
      "cs": "Proces, při kterém bezpečnostní výzkumník soukromě nahlásí zranitelnost výrobci před zveřejněním podrobností. Článek 13(6) CRA vyžaduje, aby výrobci měli zásady pro přijímání a zpracování takových oznámení. Obvykle se implementuje prostřednictvím souboru security.txt a vyhrazeného bezpečnostního kontaktu.",
      "pt": "Um processo em que um investigador de segurança comunica uma vulnerabilidade ao fabricante de forma privada antes de publicar os detalhes publicamente. O Artigo 13(6) do CRA exige que os fabricantes disponham de uma política para aceitar e processar tais divulgações. Normalmente implementado através de um ficheiro security.txt e de um contacto de segurança dedicado.",
      "ro": "Un proces prin care un cercetător de securitate raportează privat o vulnerabilitate producătorului înainte de a publica detalii public. Articolul 13(6) CRA impune producătorilor să aibă o politică de acceptare și procesare a unor astfel de divulgări. De obicei implementată printr-un fișier security.txt și un contact dedicat de securitate."
    }
  },
  {
    "term": "Supply chain attack",
    "type": "vocabulary",
    "definition": {
      "en": "An attack that targets a manufacturer through a compromised dependency or supplier, rather than attacking the manufacturer's own systems directly. SolarWinds and XZ Utils are examples. The SBOM is your map for identifying which supply chain components are present and therefore which supply chain attacks can reach your product.",
      "de": "Ein Angriff, der einen Hersteller über eine kompromittierte Dependency oder einen Lieferanten angreift, statt direkt die eigenen Systeme des Herstellers anzugreifen. SolarWinds und XZ Utils sind Beispiele. Die SBOM ist Ihre Karte zur Identifikation, welche Supply-Chain-Komponenten vorhanden sind und welche Supply-Chain-Angriffe daher Ihr Produkt erreichen können.",
      "nl": "Een aanval die een fabrikant treft via een gecompromitteerde dependency of leverancier, in plaats van de eigen systemen van de fabrikant direct aan te vallen. SolarWinds en XZ Utils zijn voorbeelden. De SBOM is uw kaart om te bepalen welke supply chain-componenten aanwezig zijn en dus welke supply chain-aanvallen uw product kunnen bereiken.",
      "fr": "Attaque ciblant un fabricant par l'intermédiaire d'une dépendance ou d'un fournisseur compromis, plutôt que par une attaque directe contre les systèmes du fabricant. SolarWinds et XZ Utils en sont des exemples. La SBOM constitue votre carte pour identifier les composants de la chaîne d'approvisionnement présents et donc les attaques par la chaîne d'approvisionnement susceptibles d'atteindre votre produit.",
      "it": "Un attacco che prende di mira un fabbricante attraverso una dipendenza o un fornitore compromesso, anziché attaccare direttamente i sistemi del fabbricante. SolarWinds e XZ Utils sono esempi. L'SBOM è la mappa per identificare quali componenti della catena di fornitura sono presenti e quindi quali attacchi alla catena di fornitura possono raggiungere il prodotto.",
      "es": "Un ataque dirigido a un fabricante a través de una dependencia o proveedor comprometido, en lugar de atacar directamente los sistemas propios del fabricante. SolarWinds y XZ Utils son ejemplos. El SBOM es su mapa para identificar qué componentes de la cadena de suministro están presentes y, por tanto, qué ataques a la cadena de suministro pueden alcanzar su producto.",
      "pl": "Atak wymierzony w producenta poprzez skompromitowaną zależność lub dostawcę, a nie bezpośrednio w systemy producenta. Przykładami są SolarWinds i XZ Utils. SBOM jest mapą pozwalającą zidentyfikować, które komponenty łańcucha dostaw są obecne i w związku z tym które ataki na łańcuch dostaw mogą dotrzeć do produktu.",
      "cs": "Útok, který cílí na výrobce prostřednictvím kompromitované závislosti nebo dodavatele, nikoli přímým útokem na systémy výrobce. Příklady jsou SolarWinds a XZ Utils. SBOM je vaše mapa pro identifikaci, které komponenty dodavatelského řetězce jsou přítomny, a tedy které útoky na dodavatelský řetězec mohou dosáhnout vašeho produktu.",
      "pt": "Um ataque que visa um fabricante através de uma dependência ou fornecedor comprometido, em vez de atacar diretamente os sistemas do próprio fabricante. O SolarWinds e o XZ Utils são exemplos. O SBOM é o seu mapa para identificar quais componentes da cadeia de abastecimento estão presentes e, por conseguinte, quais ataques à cadeia de abastecimento podem atingir o seu produto.",
      "ro": "Un atac care vizează un producător printr-o dependență sau un furnizor compromis, în loc să atace direct sistemele proprii ale producătorului. SolarWinds și XZ Utils sunt exemple. SBOM-ul este harta dvs. pentru identificarea componentelor din lanțul de aprovizionare prezente și, prin urmare, a atacurilor din lanțul de aprovizionare care pot atinge produsul dvs."
    }
  },
  {
    "term": "Hash",
    "type": "defined",
    "definition": {
      "en": "A fixed-length fingerprint of a file computed by an algorithm such as SHA-256. Including a hash for each SBOM component lets you verify that the component has not been tampered with since the SBOM was generated. CycloneDX and SPDX both support hashes per component.",
      "de": "Ein Fingerabdruck fester Länge einer Datei, berechnet durch einen Algorithmus wie SHA-256. Die Aufnahme eines Hashs für jede SBOM-Komponente ermöglicht die Überprüfung, dass die Komponente seit der Generierung der SBOM nicht manipuliert wurde. Sowohl CycloneDX als auch SPDX unterstützen Hashes pro Komponente.",
      "nl": "Een vingerafdruk van vaste lengte van een bestand, berekend met een algoritme zoals SHA-256. Het opnemen van een hash voor elke SBOM-component stelt u in staat te verifiëren dat de component niet is gemanipuleerd sinds de SBOM werd gegenereerd. Zowel CycloneDX als SPDX ondersteunen hashes per component.",
      "fr": "Empreinte de longueur fixe d'un fichier calculée par un algorithme tel que SHA-256. L'inclusion d'un hachage pour chaque composant de la SBOM permet de vérifier que le composant n'a pas été altéré depuis la génération de la SBOM. CycloneDX et SPDX prennent tous deux en charge les hachages par composant.",
      "it": "Un'impronta digitale a lunghezza fissa di un file calcolata da un algoritmo come SHA-256. Includere un hash per ogni componente dell'SBOM consente di verificare che il componente non sia stato alterato dopo la generazione dell'SBOM. Sia CycloneDX sia SPDX supportano gli hash per componente.",
      "es": "Una huella digital de longitud fija de un archivo calculada mediante un algoritmo como SHA-256. Incluir un hash para cada componente del SBOM permite verificar que el componente no ha sido alterado desde que se generó el SBOM. Tanto CycloneDX como SPDX admiten hashes por componente.",
      "pl": "Odcisk palca o stałej długości pliku obliczony algorytmem takim jak SHA-256. Dołączenie skrótu dla każdego komponentu SBOM pozwala zweryfikować, że komponent nie został zmodyfikowany od momentu wygenerowania SBOM. Zarówno CycloneDX, jak i SPDX obsługują skróty dla każdego komponentu.",
      "cs": "Otisk souboru pevné délky vypočítaný algoritmem, například SHA-256. Zahrnutí hashe pro každou komponentu SBOM umožňuje ověřit, že komponenta nebyla od vygenerování SBOM pozměněna. CycloneDX i SPDX podporují hashe na komponentu.",
      "pt": "Uma impressão digital de comprimento fixo de um ficheiro calculada por um algoritmo como o SHA-256. Incluir um hash para cada componente do SBOM permite verificar que o componente não foi adulterado desde a geração do SBOM. Tanto o CycloneDX como o SPDX suportam hashes por componente.",
      "ro": "O amprentă de lungime fixă a unui fișier calculată de un algoritm precum SHA-256. Includerea unui hash pentru fiecare componentă SBOM permite verificarea faptului că componenta nu a fost modificată de la generarea SBOM-ului. Atât CycloneDX cât și SPDX acceptă hash-uri per componentă."
    }
  },
  {
    "term": "Conformity assessment",
    "type": "vocabulary",
    "definition": {
      "en": "The process a manufacturer uses to demonstrate that its product meets CRA requirements. Default-class products can self-assess. Important Class I products can self-assess using harmonised standards. Important Class II products require a third-party conformity assessment body (CAB). The SBOM is part of the technical documentation reviewed during conformity assessment.",
      "de": "Der Prozess, den ein Hersteller nutzt, um nachzuweisen, dass sein Produkt die CRA-Anforderungen erfüllt. Produkte der Standardklasse können selbst bewerten. Wichtige Produkte der Klasse I können anhand harmonisierter Normen selbst bewerten. Wichtige Produkte der Klasse II erfordern eine Konformitätsbewertungsstelle (CAB) als Dritte. Die SBOM ist Teil der technischen Dokumentation, die während der Konformitätsbewertung geprüft wird.",
      "nl": "Het proces dat een fabrikant gebruikt om aan te tonen dat zijn product voldoet aan de CRA-vereisten. Producten van de standaardklasse kunnen zelf beoordelen. Belangrijke Klasse I-producten kunnen zelf beoordelen met geharmoniseerde normen. Belangrijke Klasse II-producten vereisen een conformiteitsbeoordelingsinstantie (CAB) van een derde partij. De SBOM maakt deel uit van de technische documentatie die tijdens de conformiteitsbeoordeling wordt beoordeeld.",
      "fr": "Processus utilisé par un fabricant pour démontrer que son produit respecte les exigences du CRA. Les produits de classe par défaut peuvent faire l'objet d'une auto-évaluation. Les produits importants de classe I peuvent faire l'objet d'une auto-évaluation sur la base de normes harmonisées. Les produits importants de classe II exigent l'intervention d'un organisme d'évaluation de la conformité tiers (CAB). La SBOM fait partie de la documentation technique examinée lors de l'évaluation de la conformité.",
      "it": "Il processo con cui un fabbricante dimostra che il proprio prodotto soddisfa i requisiti del CRA. I prodotti della classe predefinita possono effettuare l'autovalutazione. I prodotti importanti di classe I possono effettuare l'autovalutazione utilizzando norme armonizzate. I prodotti importanti di classe II richiedono un organismo di valutazione della conformità terzo (CAB). L'SBOM fa parte della documentazione tecnica esaminata durante la valutazione della conformità.",
      "es": "El proceso que utiliza un fabricante para demostrar que su producto cumple los requisitos del CRA. Los productos de clase por defecto pueden autoevaluarse. Los productos importantes de clase I pueden autoevaluarse mediante normas armonizadas. Los productos importantes de clase II requieren un organismo de evaluación de la conformidad de terceros (CAB). El SBOM forma parte de la documentación técnica revisada durante la evaluación de la conformidad.",
      "pl": "Proces, za pomocą którego producent wykazuje, że jego produkt spełnia wymagania CRA. Produkty klasy domyślnej mogą podlegać samoocenie. Ważne produkty klasy I mogą podlegać samoocenie z wykorzystaniem norm zharmonizowanych. Ważne produkty klasy II wymagają oceny zgodności przez jednostkę notyfikowaną (CAB). SBOM stanowi część dokumentacji technicznej ocenianej podczas oceny zgodności.",
      "cs": "Proces, kterým výrobce prokazuje, že jeho produkt splňuje požadavky CRA. Produkty výchozí třídy mohou provádět vlastní posouzení. Důležité produkty třídy I mohou provádět vlastní posouzení pomocí harmonizovaných norem. Důležité produkty třídy II vyžadují posouzení shody třetí stranou (CAB). SBOM je součástí technické dokumentace přezkoumávané při posuzování shody.",
      "pt": "O processo que um fabricante utiliza para demonstrar que o seu produto cumpre os requisitos do CRA. Os produtos da classe predefinida podem efetuar uma autoavaliação. Os produtos Importantes de Classe I podem efetuar uma autoavaliação utilizando normas harmonizadas. Os produtos Importantes de Classe II exigem um organismo de avaliação da conformidade de terceiros (CAB). O SBOM faz parte da documentação técnica analisada durante a avaliação da conformidade.",
      "ro": "Procesul prin care un producător demonstrează că produsul său îndeplinește cerințele CRA. Produsele din clasa implicită pot fi autoevaluate. Produsele importante din clasa I pot fi autoevaluate utilizând standarde armonizate. Produsele importante din clasa II necesită un organism de evaluare a conformității terț (CAB). SBOM-ul face parte din documentația tehnică revizuită în timpul evaluării conformității."
    }
  },
  {
    "term": "Syft",
    "type": "defined",
    "definition": {
      "en": "An open-source SBOM generator by Anchore. Scans container images, filesystems, and language-specific package manifests. Outputs CycloneDX or SPDX. The fastest way to generate an initial SBOM for an existing product.",
      "de": "Ein Open-Source-SBOM-Generator von Anchore. Scannt Container-Images, Dateisysteme und sprachspezifische Paketmanifeste. Gibt CycloneDX oder SPDX aus. Der schnellste Weg zur Erzeugung einer initialen SBOM für ein bestehendes Produkt.",
      "nl": "Een open-source SBOM-generator van Anchore. Scant container images, bestandssystemen en taalspecifieke package manifests. Produceert CycloneDX of SPDX. De snelste manier om een initiële SBOM voor een bestaand product te genereren.",
      "fr": "Générateur de SBOM open source d'Anchore. Analyse les images de conteneurs, les systèmes de fichiers et les manifestes de paquets spécifiques aux langages. Produit des fichiers CycloneDX ou SPDX. Moyen le plus rapide de générer une première SBOM pour un produit existant.",
      "it": "Un generatore SBOM open source di Anchore. Analizza immagini container, filesystem e manifest dei pacchetti specifici del linguaggio. Produce output in CycloneDX o SPDX. Il modo più rapido per generare un SBOM iniziale per un prodotto esistente.",
      "es": "Un generador de SBOM de código abierto de Anchore. Examina imágenes de contenedores, sistemas de archivos y manifiestos de paquetes específicos de lenguajes. Genera salidas en CycloneDX o SPDX. La forma más rápida de generar un SBOM inicial para un producto existente.",
      "pl": "Generator SBOM typu open source od Anchore. Skanuje obrazy kontenerów, systemy plików oraz manifesty pakietów dla konkretnych języków. Wyprowadza CycloneDX lub SPDX. Najszybszy sposób wygenerowania początkowego SBOM dla istniejącego produktu.",
      "cs": "Open-source generátor SBOM od Anchore. Skenuje kontejnerové obrazy, souborové systémy a manifesty balíčků specifické pro jazyk. Vystupuje ve formátech CycloneDX nebo SPDX. Nejrychlejší způsob, jak vygenerovat počáteční SBOM pro existující produkt.",
      "pt": "Um gerador de SBOM de código aberto da Anchore. Analisa imagens de contentores, sistemas de ficheiros e manifestos de pacotes específicos de linguagens. Produz CycloneDX ou SPDX. A forma mais rápida de gerar um SBOM inicial para um produto existente.",
      "ro": "Un generator SBOM open-source de la Anchore. Scanează imagini de containere, sisteme de fișiere și manifesturi de pachete specifice limbajelor. Generează ieșiri CycloneDX sau SPDX. Cea mai rapidă metodă de generare a unui SBOM inițial pentru un produs existent."
    }
  },
  {
    "term": "Grype",
    "type": "defined",
    "definition": {
      "en": "An open-source vulnerability scanner by Anchore. Takes an SBOM as input and matches components against the NVD, GitHub Advisory Database, and other vulnerability feeds. The tool that converts an SBOM into an Article 14 monitoring capability.",
      "de": "Ein Open-Source-Vulnerability-Scanner von Anchore. Nimmt eine SBOM als Eingabe und gleicht Komponenten mit der NVD, der GitHub Advisory Database und weiteren Vulnerability-Feeds ab. Das Tool, das eine SBOM in eine Artikel-14-Überwachungsfähigkeit umwandelt.",
      "nl": "Een open-source kwetsbaarheidsscanner van Anchore. Neemt een SBOM als input en vergelijkt componenten met de NVD, GitHub Advisory Database en andere kwetsbaarheidsfeeds. Het hulpmiddel dat een SBOM omzet in een monitoringmogelijkheid voor Artikel 14.",
      "fr": "Scanner de vulnérabilités open source d'Anchore. Prend une SBOM en entrée et met en correspondance les composants avec la NVD, la base de données des avis GitHub et d'autres flux de vulnérabilités. Outil qui transforme une SBOM en capacité de surveillance au titre de l'article 14.",
      "it": "Uno scanner di vulnerabilità open source di Anchore. Prende in input un SBOM e confronta i componenti con l'NVD, il GitHub Advisory Database e altri feed di vulnerabilità. Lo strumento che trasforma un SBOM in una capacità di monitoraggio ai sensi dell'Articolo 14.",
      "es": "Un escáner de vulnerabilidades de código abierto de Anchore. Toma un SBOM como entrada y coteja componentes con la NVD, la base de datos de avisos de GitHub y otras fuentes de vulnerabilidades. La herramienta que convierte un SBOM en una capacidad de supervisión del Artículo 14.",
      "pl": "Skaner podatności typu open source od Anchore. Przyjmuje SBOM jako dane wejściowe i porównuje komponenty z NVD, GitHub Advisory Database oraz innymi źródłami informacji o podatnościach. Narzędzie przekształcające SBOM w zdolność monitorowania zgodnie z Artykuł 14.",
      "cs": "Open-source skener zranitelností od Anchore. Přijímá SBOM jako vstup a porovnává komponenty s NVD, GitHub Advisory Database a dalšími zdroji zranitelností. Nástroj, který převádí SBOM na schopnost monitorování podle Článku 14.",
      "pt": "Um scanner de vulnerabilidades de código aberto da Anchore. Aceita um SBOM como entrada e compara componentes com a NVD, a Base de Dados de Avisos do GitHub e outras fontes de vulnerabilidades. A ferramenta que converte um SBOM numa capacidade de monitorização ao abrigo do Artigo 14.",
      "ro": "Un scanner de vulnerabilități open-source de la Anchore. Primește un SBOM ca intrare și potrivește componentele cu NVD, GitHub Advisory Database și alte fluxuri de vulnerabilități. Instrumentul care transformă un SBOM într-o capacitate de monitorizare conform Articolului 14."
    }
  }
]);

export default dictionary;
