import { courseSchema } from "@/lib/training/schemas";

const course = courseSchema.parse({
  id: "cra-sbom",
  title: {
    en: "CRA SBOM Fundamentals",
    de: "CRA SBOM-Grundlagen",
    fr: "Fondamentaux du SBOM selon le CRA",
    it: "Fondamenti dello SBOM secondo il CRA",
    es: "Fundamentos del SBOM según el CRA",
    pl: "Podstawy SBOM według CRA",
    cs: "Základy SBOM podle CRA",
    pt: "Fundamentos do SBOM segundo o CRA",
    ro: "Fundamentele SBOM conform CRA",
  },
  description: {
    en: "Build, maintain, and retain the Software Bill of Materials the Cyber Resilience Act demands. Built for product managers, engineers, and security leads at companies selling products with digital elements into the EU. Covers Article 13(5) obligations, CycloneDX and SPDX formats, tooling, and the link to Article 14 vulnerability reporting.",
    de: "Erstellen, pflegen und archivieren Sie die Software-Stückliste, die der Cyber Resilience Act fordert. Für Produktmanager, Entwickler und Security-Leads in Unternehmen, die Produkte mit digitalen Elementen in der EU vertreiben. Deckt die Pflichten aus Artikel 13(5) ab, CycloneDX- und SPDX-Formate, Werkzeuge und den Bezug zur Schwachstellenmeldepflicht nach Artikel 14.",
    fr: "Créez, maintenez et conservez la nomenclature logicielle (Software Bill of Materials) qu'exige le Cyber Resilience Act. Conçu pour les chefs de produit, les ingénieurs et les responsables de la sécurité dans les entreprises qui vendent des produits comportant des éléments numériques dans l'UE. Couvre les obligations de l'article 13(5), les formats CycloneDX et SPDX, l'outillage et le lien avec la notification des vulnérabilités au titre de l'article 14.",
    it: "Crea, mantieni e conserva la distinta base del software (Software Bill of Materials) richiesta dal Cyber Resilience Act. Pensato per product manager, ingegneri e responsabili della sicurezza nelle aziende che vendono prodotti con elementi digitali nell'UE. Copre gli obblighi dell'articolo 13(5), i formati CycloneDX e SPDX, gli strumenti e il collegamento con la segnalazione delle vulnerabilità ai sensi dell'articolo 14.",
    es: "Cree, mantenga y conserve la lista de materiales de software (Software Bill of Materials) que exige el Cyber Resilience Act. Pensado para responsables de producto, ingenieros y responsables de seguridad en empresas que venden productos con elementos digitales en la UE. Cubre las obligaciones del artículo 13(5), los formatos CycloneDX y SPDX, las herramientas y el vínculo con la notificación de vulnerabilidades del artículo 14.",
    pl: "Twórz, utrzymuj i przechowuj wykaz komponentów oprogramowania (Software Bill of Materials) wymagany przez Cyber Resilience Act. Przeznaczone dla menedżerów produktu, inżynierów i osób odpowiedzialnych za bezpieczeństwo w firmach sprzedających w UE produkty zawierające elementy cyfrowe. Obejmuje obowiązki z artykułu 13(5), formaty CycloneDX i SPDX, narzędzia oraz powiązanie ze zgłaszaniem podatności na podstawie artykułu 14.",
    cs: "Sestavte, udržujte a uchovávejte soupis softwarových komponent (Software Bill of Materials), který vyžaduje Cyber Resilience Act. Určeno pro produktové manažery, vývojáře a vedoucí bezpečnosti ve firmách prodávajících produkty s digitálními prvky do EU. Pokrývá povinnosti podle článku 13(5), formáty CycloneDX a SPDX, nástroje a vazbu na hlášení zranitelností podle článku 14.",
    pt: "Crie, mantenha e conserve a lista de materiais de software (Software Bill of Materials) que o Cyber Resilience Act exige. Concebido para gestores de produto, engenheiros e responsáveis de segurança em empresas que vendem produtos com elementos digitais na UE. Abrange as obrigações do artigo 13(5), os formatos CycloneDX e SPDX, as ferramentas e a ligação à notificação de vulnerabilidades ao abrigo do artigo 14.",
    ro: "Creați, mențineți și păstrați lista de materiale software (Software Bill of Materials) pe care o impune Cyber Resilience Act. Conceput pentru managerii de produs, ingineri și responsabilii de securitate din companiile care vând în UE produse cu elemente digitale. Acoperă obligațiile de la articolul 13(5), formatele CycloneDX și SPDX, instrumentele și legătura cu notificarea vulnerabilităților în temeiul articolului 14.",
  },
  version: "1.0",
  modules: [
    {
      id: "foundation",
      title: {
        en: "Foundation",
        de: "Grundlagen",
        fr: "Fondations",
        it: "Fondamenti",
        es: "Fundamentos",
        pl: "Podstawy",
        cs: "Základy",
        pt: "Fundamentos",
        ro: "Fundamente",
      },
      order: 0,
      lessonIds: ["0.1"],
    },
    {
      id: "module-1",
      title: {
        en: "What Goes Into an SBOM",
        de: "Was in eine SBOM gehört",
        fr: "Ce que contient un SBOM",
        it: "Cosa contiene uno SBOM",
        es: "Qué incluye un SBOM",
        pl: "Co wchodzi w skład SBOM",
        cs: "Co patří do SBOM",
        pt: "O que entra num SBOM",
        ro: "Ce conține un SBOM",
      },
      order: 1,
      lessonIds: ["1.1", "1.2", "1.3"],
    },
    {
      id: "module-2",
      title: {
        en: "Formats",
        de: "Formate",
        fr: "Formats",
        it: "Formati",
        es: "Formatos",
        pl: "Formaty",
        cs: "Formáty",
        pt: "Formatos",
        ro: "Formate",
      },
      order: 2,
      lessonIds: ["2.1", "2.2"],
    },
    {
      id: "module-3",
      title: {
        en: "Building and Maintaining Your SBOM",
        de: "SBOM erstellen und pflegen",
        fr: "Créer et maintenir votre SBOM",
        it: "Creare e mantenere il tuo SBOM",
        es: "Crear y mantener su SBOM",
        pl: "Tworzenie i utrzymywanie SBOM",
        cs: "Tvorba a údržba vašeho SBOM",
        pt: "Criar e manter o seu SBOM",
        ro: "Crearea și menținerea SBOM",
      },
      order: 3,
      lessonIds: ["3.1", "3.2"],
    },
    {
      id: "final",
      title: {
        en: "Final",
        de: "Abschluss",
        fr: "Conclusion",
        it: "Conclusione",
        es: "Cierre",
        pl: "Podsumowanie",
        cs: "Závěr",
        pt: "Conclusão",
        ro: "Final",
      },
      order: 4,
      lessonIds: ["4.1"],
    },
  ],
});

export default course;
