// Source of truth for the supplier questionnaire fields in this section.
// Edit this file (not data/supply-chain-questionnaire.json) and run
// `bun run build:json` to regenerate the published JSON artefact.
//
// Descriptions are Mittelstand-readable plain language: what to type, with
// a short example where the question is ambiguous. Legal citations live in
// the `legalBasis` field so audit teams still see the source. Labels are
// the public schema contract and are not edited here.

import type { SupplierField } from "../schema";

export const profileFields: SupplierField[] = [
  {
    id: "legalName",
    section: "profile",
    type: "string",
    label: {
      en: "Legal name",
      de: "Firmierung (Rechtsname)",
      fr: "Raison sociale",
      it: "Denominazione legale",
      es: "Razón social",
      pl: "Nazwa prawna",
    },
    description: {
      en: "Your company's registered name, as it appears in the commercial register. Example: Müller GmbH or Acme Software Ltd.",
      de: "Der eingetragene Name Ihres Unternehmens, so wie er im Handelsregister steht. Beispiel: Müller GmbH oder Schmidt AG.",
      fr: "Le nom enregistré de votre entreprise, tel qu'il figure au registre du commerce. Exemple : Müller GmbH ou Acme Software Ltd.",
      it: "Il nome registrato della vostra azienda, così come appare nel registro delle imprese. Esempio: Müller GmbH o Acme Software Ltd.",
      es: "El nombre registrado de su empresa, tal como aparece en el registro mercantil. Ejemplo: Müller GmbH o Acme Software Ltd.",
      pl: "Zarejestrowana nazwa Twojej firmy, taka jak widnieje w rejestrze handlowym. Przykład: Müller GmbH lub Acme Software Ltd.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "registeredAddress",
    section: "profile",
    type: "string",
    label: {
      en: "Registered address",
      de: "Geschäftsanschrift",
      fr: "Adresse du siège social",
      it: "Indirizzo della sede legale",
      es: "Domicilio social",
      pl: "Adres siedziby",
    },
    description: {
      en: "Your company's registered business address. One address is enough, even if you have several locations.",
      de: "Die Geschäftsanschrift Ihres Unternehmens. Eine Adresse genügt, auch wenn Sie mehrere Standorte haben.",
      fr: "L'adresse commerciale enregistrée de votre entreprise. Une seule adresse suffit, même si vous avez plusieurs sites.",
      it: "L'indirizzo commerciale registrato della vostra azienda. È sufficiente un solo indirizzo, anche se avete più sedi.",
      es: "El domicilio comercial registrado de su empresa. Basta con una dirección, aunque tenga varias ubicaciones.",
      pl: "Zarejestrowany adres prowadzenia działalności Twojej firmy. Wystarczy jeden adres, nawet jeśli masz kilka lokalizacji.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "country",
    section: "profile",
    type: "country",
    label: {
      en: "Country",
      de: "Land",
      fr: "Pays",
      it: "Paese",
      es: "País",
      pl: "Kraj",
    },
    description: {
      en: "The country where your company is legally established. Two letters, e.g. DE for Germany.",
      de: "Das Land, in dem Ihr Unternehmen rechtlich sitzt. Zwei Buchstaben, zum Beispiel DE für Deutschland.",
      fr: "Le pays où votre entreprise est légalement établie. Deux lettres, par exemple DE pour l'Allemagne.",
      it: "Il paese in cui la vostra azienda è legalmente stabilita. Due lettere, ad esempio DE per la Germania.",
      es: "El país donde su empresa está legalmente establecida. Dos letras, por ejemplo DE para Alemania.",
      pl: "Kraj, w którym Twoja firma ma siedzibę prawną. Dwie litery, np. DE dla Niemiec.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "primaryDomain",
    section: "profile",
    type: "url",
    label: {
      en: "Primary domain",
      de: "Primäre Domain",
      fr: "Domaine principal",
      it: "Dominio principale",
      es: "Dominio principal",
      pl: "Domena główna",
    },
    description: {
      en: "Your main domain, usually the URL of your website. Example: acmesoftware.com.",
      de: "Ihre Hauptdomain, üblicherweise die Adresse Ihrer Webseite. Beispiel: muellergmbh.de.",
      fr: "Votre domaine principal, généralement l'URL de votre site web. Exemple : acmesoftware.com.",
      it: "Il vostro dominio principale, di solito l'URL del vostro sito web. Esempio: acmesoftware.com.",
      es: "Su dominio principal, normalmente la URL de su sitio web. Ejemplo: acmesoftware.com.",
      pl: "Twoja domena główna, zwykle adres URL Twojej witryny. Przykład: acmesoftware.com.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "tagline",
    section: "profile",
    type: "string",
    label: {
      en: "Tagline (one line, customer-facing)",
      de: "Slogan (eine Zeile, kundenseitig sichtbar)",
      fr: "Slogan (une ligne, visible par les clients)",
      it: "Slogan (una riga, visibile ai clienti)",
      es: "Eslogan (una línea, visible para el cliente)",
      pl: "Slogan (jedna linia, widoczny dla klientów)",
    },
    description: {
      en: "One line summarising what you offer. Customers see this on your supplier profile. Example: ERP for SME manufacturing.",
      de: "Eine Zeile, die Ihre Leistung zusammenfasst. Kunden sehen diese im Lieferantenprofil. Beispiel: ERP für mittelständische Produktion.",
      fr: "Une ligne résumant ce que vous proposez. Les clients la voient sur votre profil fournisseur. Exemple : ERP pour l'industrie manufacturière des PME.",
      it: "Una riga che riassume ciò che offrite. I clienti la vedono nel vostro profilo fornitore. Esempio: ERP per la produzione delle PMI.",
      es: "Una línea que resume lo que ofrece. Los clientes la ven en su perfil de proveedor. Ejemplo: ERP para la fabricación de pymes.",
      pl: "Jedna linia podsumowująca Twoją ofertę. Klienci widzą ją w Twoim profilu dostawcy. Przykład: ERP dla produkcji w sektorze MŚP.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "description",
    section: "profile",
    type: "text",
    label: {
      en: "Public description (longer)",
      de: "Öffentliche Beschreibung (länger)",
      fr: "Description publique (plus longue)",
      it: "Descrizione pubblica (più estesa)",
      es: "Descripción pública (más extensa)",
      pl: "Opis publiczny (dłuższy)",
    },
    description: {
      en: "Two to three sentences about your company and what you do. This appears on your supplier profile. Sales pitch, security posture, or both.",
      de: "Zwei bis drei Sätze über Ihr Unternehmen und Ihre Leistung. Diese Beschreibung erscheint auf Ihrem Lieferantenprofil. Verkaufsversprechen, Sicherheitspositionierung oder beides.",
      fr: "Deux à trois phrases sur votre entreprise et votre activité. Ce texte apparaît sur votre profil fournisseur. Argumentaire commercial, posture de sécurité, ou les deux.",
      it: "Due o tre frasi sulla vostra azienda e su ciò che fate. Questo testo appare nel vostro profilo fornitore. Argomentazione commerciale, posizionamento di sicurezza o entrambi.",
      es: "Dos o tres frases sobre su empresa y lo que hace. Esto aparece en su perfil de proveedor. Argumento de venta, postura de seguridad o ambos.",
      pl: "Dwa do trzech zdań o Twojej firmie i tym, czym się zajmuje. Pojawia się to w Twoim profilu dostawcy. Argumentacja sprzedażowa, postawa w zakresie bezpieczeństwa lub oba elementy.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "serviceDescription",
    section: "profile",
    type: "text",
    label: {
      en: "Description of services provided",
      de: "Beschreibung der erbrachten Leistungen",
      fr: "Description des services fournis",
      it: "Descrizione dei servizi forniti",
      es: "Descripción de los servicios prestados",
      pl: "Opis świadczonych usług",
    },
    description: {
      en: "One paragraph on what your company technically delivers to customers. Concrete products, modules, or services. Avoid pure marketing language.",
      de: "Ein Absatz darüber, was Ihr Unternehmen Kunden technisch liefert. Konkrete Produkte, Module oder Dienstleistungen. Vermeiden Sie reine Marketing-Sprache.",
      fr: "Un paragraphe sur ce que votre entreprise livre techniquement aux clients. Produits, modules ou services concrets. Évitez le langage purement marketing.",
      it: "Un paragrafo su ciò che la vostra azienda fornisce tecnicamente ai clienti. Prodotti, moduli o servizi concreti. Evitate il linguaggio puramente di marketing.",
      es: "Un párrafo sobre lo que su empresa entrega técnicamente a los clientes. Productos, módulos o servicios concretos. Evite el lenguaje puramente comercial.",
      pl: "Jeden akapit o tym, co Twoja firma technicznie dostarcza klientom. Konkretne produkty, moduły lub usługi. Unikaj czysto marketingowego języka.",
    },
    legalBasis: "ENISA TIG §5.2(b) + §5.1.4 TIPS",
    required: true,
  },
  {
    id: "dataProcessingLocations",
    section: "profile",
    type: "string",
    label: {
      en: "Countries / regions where customer data is processed",
      de: "Länder / Regionen, in denen Kundendaten verarbeitet werden",
      fr: "Pays / régions où les données des clients sont traitées",
      it: "Paesi / regioni in cui vengono trattati i dati dei clienti",
      es: "Países / regiones donde se tratan los datos de los clientes",
      pl: "Kraje / regiony, w których przetwarzane są dane klientów",
    },
    description: {
      en: "Every country where your customers' data is stored or processed. Comma-separated, ISO country codes. Example: DE, NL, US. If you process entirely within the EU, listing the EU countries is enough.",
      de: "Alle Länder, in denen Kundendaten Ihrer Kunden gespeichert oder verarbeitet werden. Komma-getrennt, ISO-Ländercodes. Beispiel: DE, NL, US. Wenn Sie ausschließlich in der EU verarbeiten, reicht eine Liste der EU-Länder.",
      fr: "Tous les pays où les données de vos clients sont stockées ou traitées. Séparés par des virgules, codes pays ISO. Exemple : DE, NL, US. Si vous traitez entièrement au sein de l'UE, lister les pays de l'UE suffit.",
      it: "Tutti i paesi in cui i dati dei vostri clienti vengono archiviati o trattati. Separati da virgole, codici paese ISO. Esempio: DE, NL, US. Se trattate interamente all'interno dell'UE, è sufficiente elencare i paesi dell'UE.",
      es: "Todos los países donde se almacenan o tratan los datos de sus clientes. Separados por comas, códigos de país ISO. Ejemplo: DE, NL, US. Si trata los datos enteramente dentro de la UE, basta con enumerar los países de la UE.",
      pl: "Wszystkie kraje, w których przechowywane lub przetwarzane są dane Twoich klientów. Oddzielone przecinkami, kody krajów ISO. Przykład: DE, NL, US. Jeśli przetwarzasz dane wyłącznie w UE, wystarczy wymienić kraje UE.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "securityContactName",
    section: "profile",
    type: "string",
    label: {
      en: "Security contact name",
      de: "Name des Sicherheitskontakts",
      fr: "Nom du contact sécurité",
      it: "Nome del referente per la sicurezza",
      es: "Nombre del contacto de seguridad",
      pl: "Imię i nazwisko kontaktu ds. bezpieczeństwa",
    },
    description: {
      en: "Who customers contact when a security incident hits. In smaller companies often the managing director or IT lead. One person is enough.",
      de: "Wer bei einem Sicherheitsvorfall direkt angesprochen wird. Bei kleineren Unternehmen oft die Geschäftsführung oder die IT-Leitung. Eine Person genügt.",
      fr: "La personne que les clients contactent lors d'un incident de sécurité. Dans les petites entreprises, souvent le directeur général ou le responsable informatique. Une seule personne suffit.",
      it: "La persona che i clienti contattano in caso di incidente di sicurezza. Nelle aziende più piccole spesso l'amministratore delegato o il responsabile IT. È sufficiente una sola persona.",
      es: "La persona a la que los clientes contactan cuando se produce un incidente de seguridad. En las empresas más pequeñas suele ser el director general o el responsable de TI. Basta con una persona.",
      pl: "Osoba, z którą klienci kontaktują się w przypadku incydentu bezpieczeństwa. W mniejszych firmach często dyrektor zarządzający lub kierownik IT. Wystarczy jedna osoba.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: true,
  },
  {
    id: "incidentContactEmail",
    section: "profile",
    type: "email",
    label: {
      en: "Incident contact email",
      de: "E-Mail für Vorfälle",
      fr: "E-mail de contact pour les incidents",
      it: "E-mail di contatto per gli incidenti",
      es: "Correo electrónico de contacto para incidentes",
      pl: "E-mail kontaktowy do zgłaszania incydentów",
    },
    description: {
      en: "Email address customers use to report a security incident. Ideally a distribution list like security@example.com that reaches multiple people.",
      de: "E-Mail-Adresse, die Kunden bei einem Sicherheitsvorfall verwenden. Idealerweise ein Verteiler wie security@firma.de, der mehrere Personen erreicht.",
      fr: "Adresse e-mail que les clients utilisent pour signaler un incident de sécurité. Idéalement une liste de diffusion comme security@example.com qui atteint plusieurs personnes.",
      it: "Indirizzo e-mail che i clienti utilizzano per segnalare un incidente di sicurezza. Idealmente una lista di distribuzione come security@example.com che raggiunge più persone.",
      es: "Dirección de correo electrónico que los clientes utilizan para notificar un incidente de seguridad. Idealmente una lista de distribución como security@example.com que llegue a varias personas.",
      pl: "Adres e-mail, którego klienci używają do zgłaszania incydentu bezpieczeństwa. Najlepiej lista dystrybucyjna, taka jak security@example.com, która dociera do wielu osób.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: true,
  },
  {
    id: "incidentContactPhone",
    section: "profile",
    type: "phone",
    label: {
      en: "Incident contact phone (24/7)",
      de: "Telefonnummer für Vorfälle (24/7)",
      fr: "Téléphone de contact pour les incidents (24/7)",
      it: "Telefono di contatto per gli incidenti (24/7)",
      es: "Teléfono de contacto para incidentes (24/7)",
      pl: "Telefon kontaktowy do zgłaszania incydentów (24/7)",
    },
    description: {
      en: "Phone number for urgent incident reports. If you do not run 24/7 on-call, mention your business hours in brackets.",
      de: "Telefonnummer für dringende Vorfallsmeldungen. Wenn Sie keinen 24/7-Bereitschaftsdienst haben, geben Sie die Geschäftszeiten in Klammern an.",
      fr: "Numéro de téléphone pour les signalements urgents d'incidents. Si vous n'assurez pas d'astreinte 24/7, indiquez vos heures ouvrées entre parenthèses.",
      it: "Numero di telefono per le segnalazioni urgenti di incidenti. Se non disponete di reperibilità 24/7, indicate il vostro orario lavorativo tra parentesi.",
      es: "Número de teléfono para las notificaciones urgentes de incidentes. Si no dispone de guardia 24/7, indique su horario laboral entre paréntesis.",
      pl: "Numer telefonu do pilnych zgłoszeń incydentów. Jeśli nie prowadzisz dyżuru 24/7, podaj godziny pracy w nawiasie.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: false,
  },
  {
    id: "incidentSlaHours",
    section: "profile",
    type: "integer",
    label: {
      en: "Incident notification SLA (hours)",
      de: "Meldefrist für Vorfälle (Stunden)",
      fr: "SLA de notification d'incident (heures)",
      it: "SLA di notifica degli incidenti (ore)",
      es: "SLA de notificación de incidentes (horas)",
      pl: "SLA powiadamiania o incydentach (godziny)",
    },
    description: {
      en: "Hours from incident detection to customer notification, at the latest. Realistic self-assessment, not aspirational. Common values: 24, 48, or 72 hours.",
      de: "Wie viele Stunden Sie maximal brauchen, um einen Kunden nach Erkennung eines Vorfalls zu informieren. Realistische Selbsteinschätzung, nicht Wunschwert. Übliche Werte: 24, 48 oder 72 Stunden.",
      fr: "Heures entre la détection d'un incident et la notification au client, au plus tard. Auto-évaluation réaliste, pas un objectif théorique. Valeurs courantes : 24, 48 ou 72 heures.",
      it: "Ore tra il rilevamento di un incidente e la notifica al cliente, al più tardi. Autovalutazione realistica, non un valore ideale. Valori comuni: 24, 48 o 72 ore.",
      es: "Horas desde la detección de un incidente hasta la notificación al cliente, como máximo. Autoevaluación realista, no aspiracional. Valores habituales: 24, 48 o 72 horas.",
      pl: "Liczba godzin od wykrycia incydentu do powiadomienia klienta, najpóźniej. Realistyczna samoocena, a nie wartość docelowa. Typowe wartości: 24, 48 lub 72 godziny.",
    },
    legalBasis: "NIS2 Art. 23",
    required: false,
  },
  {
    id: "bsiRegistrationId",
    section: "profile",
    type: "string",
    label: {
      en: "BSI registration ID (only if your company is itself NIS2-regulated)",
      de: "BSI-Registrierungs-ID (nur falls Ihr Unternehmen selbst NIS2-reguliert ist)",
      fr: "Identifiant d'enregistrement BSI (uniquement si votre entreprise est elle-même réglementée par NIS2)",
      it: "ID di registrazione BSI (solo se la vostra azienda è essa stessa regolamentata da NIS2)",
      es: "ID de registro BSI (solo si su empresa está regulada por NIS2)",
      pl: "Identyfikator rejestracji BSI (tylko jeśli Twoja firma sama podlega NIS2)",
    },
    description: {
      en: "If your company is itself NIS 2 regulated and registered with the BSI, enter the registration ID here. Optional. Lets customers see at a glance that you meet the same obligation as a regulated entity.",
      de: "Wenn Ihr Unternehmen selbst der NIS 2 unterliegt und beim BSI registriert ist, tragen Sie die Registrierungs-ID hier ein. Optional. Kunden sehen damit auf einen Blick, dass Sie als regulierte Einrichtung dieselbe Pflicht erfüllen.",
      fr: "Si votre entreprise est elle-même soumise à NIS 2 et enregistrée auprès du BSI, saisissez ici l'identifiant d'enregistrement. Facultatif. Permet aux clients de voir d'un coup d'œil que vous remplissez la même obligation qu'une entité réglementée.",
      it: "Se la vostra azienda è essa stessa soggetta a NIS 2 e registrata presso il BSI, inserite qui l'ID di registrazione. Facoltativo. Consente ai clienti di vedere a colpo d'occhio che soddisfate lo stesso obbligo di un'entità regolamentata.",
      es: "Si su empresa está sujeta a NIS 2 y registrada ante el BSI, introduzca aquí el ID de registro. Opcional. Permite a los clientes ver de un vistazo que cumple la misma obligación que una entidad regulada.",
      pl: "Jeśli Twoja firma sama podlega NIS 2 i jest zarejestrowana w BSI, wpisz tutaj identyfikator rejestracji. Opcjonalne. Pozwala klientom od razu zobaczyć, że spełniasz ten sam obowiązek co podmiot regulowany.",
    },
    legalBasis: "ENISA TIG §5.1.2",
    required: false,
  },
  {
    id: "isSaas",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide SaaS / hosted services",
      de: "Wir bieten SaaS / gehostete Dienste",
      fr: "Nous fournissons des services SaaS / hébergés",
      it: "Forniamo servizi SaaS / in hosting",
      es: "Ofrecemos servicios SaaS / alojados",
      pl: "Świadczymy usługi SaaS / hostowane",
    },
    description: {
      en: "You run software for customers on your own infrastructure and deliver it over the internet. Tick more than one box if you offer several models.",
      de: "Sie betreiben Software für Kunden auf eigener Infrastruktur und liefern sie über das Internet. Mehrfachauswahl möglich, wenn Sie mehrere Modelle anbieten.",
      fr: "Vous exécutez des logiciels pour les clients sur votre propre infrastructure et les livrez via internet. Cochez plusieurs cases si vous proposez plusieurs modèles.",
      it: "Eseguite software per i clienti sulla vostra infrastruttura e lo erogate tramite internet. Selezionate più caselle se offrite più modelli.",
      es: "Ejecuta software para los clientes en su propia infraestructura y lo entrega a través de internet. Marque más de una casilla si ofrece varios modelos.",
      pl: "Uruchamiasz oprogramowanie dla klientów na własnej infrastrukturze i dostarczasz je przez internet. Zaznacz więcej niż jedno pole, jeśli oferujesz kilka modeli.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isOnPrem",
    section: "profile",
    type: "boolean",
    label: {
      en: "We deliver on-prem software",
      de: "Wir liefern On-Prem-Software",
      fr: "Nous livrons des logiciels on-premise",
      it: "Forniamo software on-premise",
      es: "Entregamos software on-premise",
      pl: "Dostarczamy oprogramowanie on-premise",
    },
    description: {
      en: "You deliver software that customers install and run on their own infrastructure.",
      de: "Sie liefern Software, die Ihre Kunden auf ihrer eigenen Infrastruktur installieren und betreiben.",
      fr: "Vous livrez des logiciels que les clients installent et exécutent sur leur propre infrastructure.",
      it: "Fornite software che i clienti installano ed eseguono sulla propria infrastruttura.",
      es: "Entrega software que los clientes instalan y ejecutan en su propia infraestructura.",
      pl: "Dostarczasz oprogramowanie, które klienci instalują i uruchamiają na własnej infrastrukturze.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isProfessionalServices",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide professional services / consulting",
      de: "Wir bieten Dienstleistungen / Beratung",
      fr: "Nous fournissons des services professionnels / conseil",
      it: "Forniamo servizi professionali / consulenza",
      es: "Ofrecemos servicios profesionales / consultoría",
      pl: "Świadczymy usługi profesjonalne / doradztwo",
    },
    description: {
      en: "Your main deliverable is human work: consulting, implementation, training, audit, or customisation.",
      de: "Sie liefern menschliche Arbeit als Hauptleistung: Beratung, Implementierung, Schulung, Audit oder Customizing.",
      fr: "Votre prestation principale est un travail humain : conseil, mise en œuvre, formation, audit ou personnalisation.",
      it: "La vostra prestazione principale è il lavoro umano: consulenza, implementazione, formazione, audit o personalizzazione.",
      es: "Su entregable principal es trabajo humano: consultoría, implementación, formación, auditoría o personalización.",
      pl: "Twoim głównym produktem jest praca ludzka: doradztwo, wdrożenie, szkolenia, audyt lub dostosowanie.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isManagedService",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide managed services / MSP",
      de: "Wir bieten Managed Services / MSP",
      fr: "Nous fournissons des services gérés / MSP",
      it: "Forniamo servizi gestiti / MSP",
      es: "Ofrecemos servicios gestionados / MSP",
      pl: "Świadczymy usługi zarządzane / MSP",
    },
    description: {
      en: "You operate parts of your customer's IT for them, with your own staff. Typical for MSP and MSSP models.",
      de: "Sie betreiben Teile der IT-Landschaft des Kunden für ihn, mit eigenem Personal. Typisch für MSP- und MSSP-Modelle.",
      fr: "Vous exploitez pour le client une partie de son informatique, avec votre propre personnel. Typique des modèles MSP et MSSP.",
      it: "Gestite per il cliente parti della sua infrastruttura IT, con personale proprio. Tipico dei modelli MSP e MSSP.",
      es: "Opera para el cliente partes de su TI, con personal propio. Típico de los modelos MSP y MSSP.",
      pl: "Obsługujesz dla klienta części jego infrastruktury IT, własnym personelem. Typowe dla modeli MSP i MSSP.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "usesAiSystems",
    section: "profile",
    type: "boolean",
    label: {
      en: "We use, integrate or provide AI systems",
      de: "Wir nutzen, integrieren oder bieten KI-Systeme",
      fr: "Nous utilisons, intégrons ou fournissons des systèmes d'IA",
      it: "Utilizziamo, integriamo o forniamo sistemi di IA",
      es: "Utilizamos, integramos o proporcionamos sistemas de IA",
      pl: "Używamy, integrujemy lub dostarczamy systemy SI",
    },
    description: {
      en: "Do your products or services process customer data through an AI or ML model? Includes external models you call through an API, for example OpenAI or Anthropic.",
      de: "Verarbeiten Ihre Produkte oder Dienste Kundendaten durch ein KI- oder ML-Modell? Inklusive externer Modelle, die Sie über eine API anbinden, zum Beispiel OpenAI oder Anthropic.",
      fr: "Vos produits ou services traitent-ils les données des clients via un modèle d'IA ou de ML ? Cela inclut les modèles externes que vous appelez via une API, par exemple OpenAI ou Anthropic.",
      it: "I vostri prodotti o servizi trattano i dati dei clienti tramite un modello di IA o ML? Sono inclusi i modelli esterni richiamati tramite API, ad esempio OpenAI o Anthropic.",
      es: "¿Sus productos o servicios tratan datos de los clientes mediante un modelo de IA o ML? Incluye modelos externos a los que llama a través de una API, por ejemplo OpenAI o Anthropic.",
      pl: "Czy Twoje produkty lub usługi przetwarzają dane klientów za pomocą modelu SI lub ML? Obejmuje to modele zewnętrzne wywoływane przez API, na przykład OpenAI lub Anthropic.",
    },
    legalBasis: "NIS2 Art. 21(2)(d)",
    required: true,
  },
];
