// Source of truth for the supplier questionnaire fields in this section.
// Edit this file (not data/supply-chain-questionnaire.json) and run
// `bun run build:json` to regenerate the published JSON artefact.
//
// Descriptions are Mittelstand-readable plain language: what to type, with
// a short example where the question is ambiguous. Legal citations live in
// the `legalBasis` field so audit teams still see the source. Labels are
// the public schema contract and are not edited here.

import type { SupplierField } from "../schema";

export const profileFields: SupplierField[] = [
  {
    id: "legalName",
    section: "profile",
    type: "string",
    label: {
      en: "Legal name",
      de: "Firmierung (Rechtsname)",
      fr: "Raison sociale",
      it: "Denominazione legale",
      es: "Razón social",
      pl: "Nazwa prawna",
      cs: "Obchodní firma (právní název)",
      pt: "Denominação social",
      ro: "Denumirea legală",
    },
    description: {
      en: "Your company's registered name, as it appears in the commercial register. Example: Müller GmbH or Acme Software Ltd.",
      de: "Der eingetragene Name Ihres Unternehmens, so wie er im Handelsregister steht. Beispiel: Müller GmbH oder Schmidt AG.",
      fr: "Le nom enregistré de votre entreprise, tel qu'il figure au registre du commerce. Exemple : Müller GmbH ou Acme Software Ltd.",
      it: "Il nome registrato della vostra azienda, così come appare nel registro delle imprese. Esempio: Müller GmbH o Acme Software Ltd.",
      es: "El nombre registrado de su empresa, tal como aparece en el registro mercantil. Ejemplo: Müller GmbH o Acme Software Ltd.",
      pl: "Zarejestrowana nazwa Twojej firmy, taka jak widnieje w rejestrze handlowym. Przykład: Müller GmbH lub Acme Software Ltd.",
      cs: "Zapsaný název vaší společnosti tak, jak je uveden v obchodním rejstříku. Příklad: Müller GmbH nebo Acme Software Ltd.",
      pt: "O nome registado da sua empresa, tal como consta do registo comercial. Exemplo: Müller GmbH ou Acme Software Ltd.",
      ro: "Denumirea înregistrată a companiei dumneavoastră, astfel cum apare în registrul comerțului. Exemplu: Müller GmbH sau Acme Software Ltd.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "registeredAddress",
    section: "profile",
    type: "string",
    label: {
      en: "Registered address",
      de: "Geschäftsanschrift",
      fr: "Adresse du siège social",
      it: "Indirizzo della sede legale",
      es: "Domicilio social",
      pl: "Adres siedziby",
      cs: "Sídlo společnosti",
      pt: "Sede social",
      ro: "Adresa sediului social",
    },
    description: {
      en: "Your company's registered business address. One address is enough, even if you have several locations.",
      de: "Die Geschäftsanschrift Ihres Unternehmens. Eine Adresse genügt, auch wenn Sie mehrere Standorte haben.",
      fr: "L'adresse commerciale enregistrée de votre entreprise. Une seule adresse suffit, même si vous avez plusieurs sites.",
      it: "L'indirizzo commerciale registrato della vostra azienda. È sufficiente un solo indirizzo, anche se avete più sedi.",
      es: "El domicilio comercial registrado de su empresa. Basta con una dirección, aunque tenga varias ubicaciones.",
      pl: "Zarejestrowany adres prowadzenia działalności Twojej firmy. Wystarczy jeden adres, nawet jeśli masz kilka lokalizacji.",
      cs: "Zapsaná obchodní adresa vaší společnosti. Jedna adresa stačí, i když máte více provozoven.",
      pt: "O endereço comercial registado da sua empresa. Basta um endereço, mesmo que tenha várias localizações.",
      ro: "Adresa comercială înregistrată a companiei dumneavoastră. Este suficientă o singură adresă, chiar dacă aveți mai multe locații.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "country",
    section: "profile",
    type: "country",
    label: {
      en: "Country",
      de: "Land",
      fr: "Pays",
      it: "Paese",
      es: "País",
      pl: "Kraj",
      cs: "Země",
      pt: "País",
      ro: "Țară",
    },
    description: {
      en: "The country where your company is legally established. Two letters, e.g. DE for Germany.",
      de: "Das Land, in dem Ihr Unternehmen rechtlich sitzt. Zwei Buchstaben, zum Beispiel DE für Deutschland.",
      fr: "Le pays où votre entreprise est légalement établie. Deux lettres, par exemple DE pour l'Allemagne.",
      it: "Il paese in cui la vostra azienda è legalmente stabilita. Due lettere, ad esempio DE per la Germania.",
      es: "El país donde su empresa está legalmente establecida. Dos letras, por ejemplo DE para Alemania.",
      pl: "Kraj, w którym Twoja firma ma siedzibę prawną. Dwie litery, np. DE dla Niemiec.",
      cs: "Země, ve které je vaše společnost právně usazena. Dvě písmena, například DE pro Německo.",
      pt: "O país onde a sua empresa está legalmente estabelecida. Duas letras, por exemplo DE para a Alemanha.",
      ro: "Țara în care compania dumneavoastră este stabilită legal. Două litere, de exemplu DE pentru Germania.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "primaryDomain",
    section: "profile",
    type: "url",
    label: {
      en: "Primary domain",
      de: "Primäre Domain",
      fr: "Domaine principal",
      it: "Dominio principale",
      es: "Dominio principal",
      pl: "Domena główna",
      cs: "Hlavní doména",
      pt: "Domínio principal",
      ro: "Domeniu principal",
    },
    description: {
      en: "Your main domain, usually the URL of your website. Example: acmesoftware.com.",
      de: "Ihre Hauptdomain, üblicherweise die Adresse Ihrer Webseite. Beispiel: muellergmbh.de.",
      fr: "Votre domaine principal, généralement l'URL de votre site web. Exemple : acmesoftware.com.",
      it: "Il vostro dominio principale, di solito l'URL del vostro sito web. Esempio: acmesoftware.com.",
      es: "Su dominio principal, normalmente la URL de su sitio web. Ejemplo: acmesoftware.com.",
      pl: "Twoja domena główna, zwykle adres URL Twojej witryny. Przykład: acmesoftware.com.",
      cs: "Vaše hlavní doména, obvykle adresa URL vašich webových stránek. Příklad: acmesoftware.com.",
      pt: "O seu domínio principal, normalmente o URL do seu sítio web. Exemplo: acmesoftware.com.",
      ro: "Domeniul dumneavoastră principal, de obicei adresa URL a site-ului web. Exemplu: acmesoftware.com.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "serviceDescription",
    section: "profile",
    type: "text",
    label: {
      en: "Description of services provided",
      de: "Beschreibung der erbrachten Leistungen",
      fr: "Description des services fournis",
      it: "Descrizione dei servizi forniti",
      es: "Descripción de los servicios prestados",
      pl: "Opis świadczonych usług",
      cs: "Popis poskytovaných služeb",
      pt: "Descrição dos serviços prestados",
      ro: "Descrierea serviciilor furnizate",
    },
    description: {
      en: "One paragraph on what your company technically delivers to customers. Concrete products, modules, or services. Avoid pure marketing language.",
      de: "Ein Absatz darüber, was Ihr Unternehmen Kunden technisch liefert. Konkrete Produkte, Module oder Dienstleistungen. Vermeiden Sie reine Marketing-Sprache.",
      fr: "Un paragraphe sur ce que votre entreprise livre techniquement aux clients. Produits, modules ou services concrets. Évitez le langage purement marketing.",
      it: "Un paragrafo su ciò che la vostra azienda fornisce tecnicamente ai clienti. Prodotti, moduli o servizi concreti. Evitate il linguaggio puramente di marketing.",
      es: "Un párrafo sobre lo que su empresa entrega técnicamente a los clientes. Productos, módulos o servicios concretos. Evite el lenguaje puramente comercial.",
      pl: "Jeden akapit o tym, co Twoja firma technicznie dostarcza klientom. Konkretne produkty, moduły lub usługi. Unikaj czysto marketingowego języka.",
      cs: "Jeden odstavec o tom, co vaše společnost zákazníkům technicky dodává. Konkrétní produkty, moduly nebo služby. Vyhněte se čistě marketingovému jazyku.",
      pt: "Um parágrafo sobre o que a sua empresa entrega tecnicamente aos clientes. Produtos, módulos ou serviços concretos. Evite linguagem puramente de marketing.",
      ro: "Un paragraf despre ceea ce compania dumneavoastră livrează din punct de vedere tehnic clienților. Produse, module sau servicii concrete. Evitați limbajul pur de marketing.",
    },
    legalBasis: "ENISA TIG §5.2(b) + §5.1.4 TIPS",
    required: true,
  },
  {
    id: "dataProcessingLocations",
    section: "profile",
    type: "string",
    label: {
      en: "Countries / regions where customer data is processed",
      de: "Länder / Regionen, in denen Kundendaten verarbeitet werden",
      fr: "Pays / régions où les données des clients sont traitées",
      it: "Paesi / regioni in cui vengono trattati i dati dei clienti",
      es: "Países / regiones donde se tratan los datos de los clientes",
      pl: "Kraje / regiony, w których przetwarzane są dane klientów",
      cs: "Země / regiony, kde se zpracovávají data zákazníků",
      pt: "Países / regiões onde são tratados os dados dos clientes",
      ro: "Țări / regiuni în care sunt prelucrate datele clienților",
    },
    description: {
      en: "Every country where your customers' data is stored or processed. Comma-separated, ISO country codes. Example: DE, NL, US. If you process entirely within the EU, listing the EU countries is enough.",
      de: "Alle Länder, in denen Kundendaten Ihrer Kunden gespeichert oder verarbeitet werden. Komma-getrennt, ISO-Ländercodes. Beispiel: DE, NL, US. Wenn Sie ausschließlich in der EU verarbeiten, reicht eine Liste der EU-Länder.",
      fr: "Tous les pays où les données de vos clients sont stockées ou traitées. Séparés par des virgules, codes pays ISO. Exemple : DE, NL, US. Si vous traitez entièrement au sein de l'UE, lister les pays de l'UE suffit.",
      it: "Tutti i paesi in cui i dati dei vostri clienti vengono archiviati o trattati. Separati da virgole, codici paese ISO. Esempio: DE, NL, US. Se trattate interamente all'interno dell'UE, è sufficiente elencare i paesi dell'UE.",
      es: "Todos los países donde se almacenan o tratan los datos de sus clientes. Separados por comas, códigos de país ISO. Ejemplo: DE, NL, US. Si trata los datos enteramente dentro de la UE, basta con enumerar los países de la UE.",
      pl: "Wszystkie kraje, w których przechowywane lub przetwarzane są dane Twoich klientów. Oddzielone przecinkami, kody krajów ISO. Przykład: DE, NL, US. Jeśli przetwarzasz dane wyłącznie w UE, wystarczy wymienić kraje UE.",
      cs: "Všechny země, kde se ukládají nebo zpracovávají data vašich zákazníků. Oddělené čárkami, kódy zemí ISO. Příklad: DE, NL, US. Pokud zpracováváte výhradně v rámci EU, stačí uvést země EU.",
      pt: "Todos os países onde os dados dos seus clientes são armazenados ou tratados. Separados por vírgulas, códigos de país ISO. Exemplo: DE, NL, US. Se tratar os dados inteiramente dentro da UE, basta enumerar os países da UE.",
      ro: "Toate țările în care datele clienților dumneavoastră sunt stocate sau prelucrate. Separate prin virgule, coduri de țară ISO. Exemplu: DE, NL, US. Dacă prelucrați integral în interiorul UE, este suficient să enumerați țările UE.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "securityContactName",
    section: "profile",
    type: "string",
    label: {
      en: "Security contact name",
      de: "Name des Sicherheitskontakts",
      fr: "Nom du contact sécurité",
      it: "Nome del referente per la sicurezza",
      es: "Nombre del contacto de seguridad",
      pl: "Imię i nazwisko kontaktu ds. bezpieczeństwa",
      cs: "Jméno bezpečnostního kontaktu",
      pt: "Nome do contacto de segurança",
      ro: "Numele persoanei de contact pentru securitate",
    },
    description: {
      en: "Who customers contact when a security incident hits. In smaller companies often the managing director or IT lead. One person is enough.",
      de: "Wer bei einem Sicherheitsvorfall direkt angesprochen wird. Bei kleineren Unternehmen oft die Geschäftsführung oder die IT-Leitung. Eine Person genügt.",
      fr: "La personne que les clients contactent lors d'un incident de sécurité. Dans les petites entreprises, souvent le directeur général ou le responsable informatique. Une seule personne suffit.",
      it: "La persona che i clienti contattano in caso di incidente di sicurezza. Nelle aziende più piccole spesso l'amministratore delegato o il responsabile IT. È sufficiente una sola persona.",
      es: "La persona a la que los clientes contactan cuando se produce un incidente de seguridad. En las empresas más pequeñas suele ser el director general o el responsable de TI. Basta con una persona.",
      pl: "Osoba, z którą klienci kontaktują się w przypadku incydentu bezpieczeństwa. W mniejszych firmach często dyrektor zarządzający lub kierownik IT. Wystarczy jedna osoba.",
      cs: "Na koho se zákazníci obrátí, když dojde k bezpečnostnímu incidentu. V menších společnostech často jednatel nebo vedoucí IT. Jedna osoba stačí.",
      pt: "A quem os clientes recorrem quando ocorre um incidente de segurança. Nas empresas mais pequenas, muitas vezes o diretor-geral ou o responsável de TI. Basta uma pessoa.",
      ro: "Persoana pe care clienții o contactează atunci când are loc un incident de securitate. În companiile mai mici, adesea directorul general sau responsabilul IT. Este suficientă o singură persoană.",
    },
    legalBasis: "CIR 2024/2690 §5.2(a)",
    required: true,
  },
  {
    id: "incidentContactEmail",
    section: "profile",
    type: "email",
    label: {
      en: "Incident contact email",
      de: "E-Mail für Vorfälle",
      fr: "E-mail de contact pour les incidents",
      it: "E-mail di contatto per gli incidenti",
      es: "Correo electrónico de contacto para incidentes",
      pl: "E-mail kontaktowy do zgłaszania incydentów",
      cs: "E-mail pro kontakt při incidentech",
      pt: "E-mail de contacto para incidentes",
      ro: "E-mail de contact pentru incidente",
    },
    description: {
      en: "Email address customers use to report a security incident. Ideally a distribution list like security@example.com that reaches multiple people.",
      de: "E-Mail-Adresse, die Kunden bei einem Sicherheitsvorfall verwenden. Idealerweise ein Verteiler wie security@firma.de, der mehrere Personen erreicht.",
      fr: "Adresse e-mail que les clients utilisent pour signaler un incident de sécurité. Idéalement une liste de diffusion comme security@example.com qui atteint plusieurs personnes.",
      it: "Indirizzo e-mail che i clienti utilizzano per segnalare un incidente di sicurezza. Idealmente una lista di distribuzione come security@example.com che raggiunge più persone.",
      es: "Dirección de correo electrónico que los clientes utilizan para notificar un incidente de seguridad. Idealmente una lista de distribución como security@example.com que llegue a varias personas.",
      pl: "Adres e-mail, którego klienci używają do zgłaszania incydentu bezpieczeństwa. Najlepiej lista dystrybucyjna, taka jak security@example.com, która dociera do wielu osób.",
      cs: "E-mailová adresa, kterou zákazníci používají k nahlášení bezpečnostního incidentu. Ideálně distribuční seznam jako security@example.com, který zastihne více osob.",
      pt: "Endereço de e-mail que os clientes utilizam para comunicar um incidente de segurança. Idealmente uma lista de distribuição como security@example.com que chegue a várias pessoas.",
      ro: "Adresa de e-mail pe care clienții o folosesc pentru a raporta un incident de securitate. În mod ideal, o listă de distribuție precum security@example.com care ajunge la mai multe persoane.",
    },
    legalBasis: "CIR 2024/2690 §5.2(a)",
    required: true,
  },
  {
    id: "incidentContactPhone",
    section: "profile",
    type: "phone",
    label: {
      en: "Incident contact phone",
      de: "Telefonnummer für Vorfälle",
    },
    description: {
      en: "Phone number for urgent incident reports. Add the hours it is answered in brackets; round-the-clock cover is not expected.",
      de: "Telefonnummer für dringende Vorfallsmeldungen. Nennen Sie in Klammern, wann sie besetzt ist; eine Erreichbarkeit rund um die Uhr wird nicht erwartet.",
    },
    legalBasis: "CIR 2024/2690 §5.2(a)",
    required: false,
  },
  {
    id: "incidentSlaHours",
    section: "profile",
    type: "integer",
    label: {
      en: "How fast you inform customers of an incident (hours)",
      de: "Wie schnell Sie Kunden über einen Vorfall informieren (Stunden)",
    },
    description: {
      en: "At most this many hours after you notice a security incident that affects your customers. Your customers must give their own authority an early warning within 24 hours (Art. 23(4)(a) NIS2), so a promise of 24 hours or less helps them most. Give a value you keep, not a wish.",
      de: "Höchstens so viele Stunden, nachdem Sie einen Sicherheitsvorfall bemerkt haben, der Ihre Kunden betrifft. Ihre Kunden müssen ihrer Behörde selbst innerhalb von 24 Stunden eine Frühwarnung geben (Art. 23 Abs. 4 Buchst. a NIS2), deshalb hilft ihnen eine Zusage von 24 Stunden oder weniger am meisten. Nennen Sie einen Wert, den Sie halten, keinen Wunsch.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: false,
  },
  {
    id: "isSaas",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide SaaS / hosted services",
      de: "Wir bieten SaaS / gehostete Dienste",
      fr: "Nous fournissons des services SaaS / hébergés",
      it: "Forniamo servizi SaaS / in hosting",
      es: "Ofrecemos servicios SaaS / alojados",
      pl: "Świadczymy usługi SaaS / hostowane",
      cs: "Poskytujeme SaaS / hostované služby",
      pt: "Fornecemos serviços SaaS / alojados",
      ro: "Furnizăm servicii SaaS / găzduite",
    },
    description: {
      en: "You run software for customers on your own infrastructure and deliver it over the internet. Tick more than one box if you offer several models.",
      de: "Sie betreiben Software für Kunden auf eigener Infrastruktur und liefern sie über das Internet. Mehrfachauswahl möglich, wenn Sie mehrere Modelle anbieten.",
      fr: "Vous exécutez des logiciels pour les clients sur votre propre infrastructure et les livrez via internet. Cochez plusieurs cases si vous proposez plusieurs modèles.",
      it: "Eseguite software per i clienti sulla vostra infrastruttura e lo erogate tramite internet. Selezionate più caselle se offrite più modelli.",
      es: "Ejecuta software para los clientes en su propia infraestructura y lo entrega a través de internet. Marque más de una casilla si ofrece varios modelos.",
      pl: "Uruchamiasz oprogramowanie dla klientów na własnej infrastrukturze i dostarczasz je przez internet. Zaznacz więcej niż jedno pole, jeśli oferujesz kilka modeli.",
      cs: "Provozujete software pro zákazníky na vlastní infrastruktuře a dodáváte jej přes internet. Pokud nabízíte více modelů, zaškrtněte více políček.",
      pt: "Executa software para os clientes na sua própria infraestrutura e entrega-o através da internet. Assinale mais do que uma caixa se oferecer vários modelos.",
      ro: "Rulați software pentru clienți pe propria infrastructură și îl livrați prin internet. Bifați mai multe casete dacă oferiți mai multe modele.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isOnPrem",
    section: "profile",
    type: "boolean",
    label: {
      en: "We deliver on-prem software",
      de: "Wir liefern On-Prem-Software",
      fr: "Nous livrons des logiciels on-premise",
      it: "Forniamo software on-premise",
      es: "Entregamos software on-premise",
      pl: "Dostarczamy oprogramowanie on-premise",
      cs: "Dodáváme on-premise software",
      pt: "Fornecemos software on-premise",
      ro: "Livrăm software on-premise",
    },
    description: {
      en: "You deliver software that customers install and run on their own infrastructure.",
      de: "Sie liefern Software, die Ihre Kunden auf ihrer eigenen Infrastruktur installieren und betreiben.",
      fr: "Vous livrez des logiciels que les clients installent et exécutent sur leur propre infrastructure.",
      it: "Fornite software che i clienti installano ed eseguono sulla propria infrastruttura.",
      es: "Entrega software que los clientes instalan y ejecutan en su propia infraestructura.",
      pl: "Dostarczasz oprogramowanie, które klienci instalują i uruchamiają na własnej infrastrukturze.",
      cs: "Dodáváte software, který si zákazníci instalují a provozují na vlastní infrastruktuře.",
      pt: "Fornece software que os clientes instalam e executam na sua própria infraestrutura.",
      ro: "Livrați software pe care clienții îl instalează și îl rulează pe propria infrastructură.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isProfessionalServices",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide professional services / consulting",
      de: "Wir bieten Dienstleistungen / Beratung",
      fr: "Nous fournissons des services professionnels / conseil",
      it: "Forniamo servizi professionali / consulenza",
      es: "Ofrecemos servicios profesionales / consultoría",
      pl: "Świadczymy usługi profesjonalne / doradztwo",
      cs: "Poskytujeme profesionální služby / poradenství",
      pt: "Fornecemos serviços profissionais / consultoria",
      ro: "Furnizăm servicii profesionale / consultanță",
    },
    description: {
      en: "Your main deliverable is human work: consulting, implementation, training, audit, or customisation.",
      de: "Sie liefern menschliche Arbeit als Hauptleistung: Beratung, Implementierung, Schulung, Audit oder Customizing.",
      fr: "Votre prestation principale est un travail humain : conseil, mise en œuvre, formation, audit ou personnalisation.",
      it: "La vostra prestazione principale è il lavoro umano: consulenza, implementazione, formazione, audit o personalizzazione.",
      es: "Su entregable principal es trabajo humano: consultoría, implementación, formación, auditoría o personalización.",
      pl: "Twoim głównym produktem jest praca ludzka: doradztwo, wdrożenie, szkolenia, audyt lub dostosowanie.",
      cs: "Vaším hlavním výstupem je lidská práce: poradenství, implementace, školení, audit nebo přizpůsobení.",
      pt: "O seu principal resultado é trabalho humano: consultoria, implementação, formação, auditoria ou personalização.",
      ro: "Principalul dumneavoastră livrabil este munca umană: consultanță, implementare, instruire, audit sau personalizare.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isManagedService",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide managed services / MSP",
      de: "Wir bieten Managed Services / MSP",
      fr: "Nous fournissons des services gérés / MSP",
      it: "Forniamo servizi gestiti / MSP",
      es: "Ofrecemos servicios gestionados / MSP",
      pl: "Świadczymy usługi zarządzane / MSP",
      cs: "Poskytujeme spravované služby / MSP",
      pt: "Fornecemos serviços geridos / MSP",
      ro: "Furnizăm servicii gestionate / MSP",
    },
    description: {
      en: "You operate parts of your customer's IT for them, with your own staff. Typical for MSP and MSSP models.",
      de: "Sie betreiben Teile der IT-Landschaft des Kunden für ihn, mit eigenem Personal. Typisch für MSP- und MSSP-Modelle.",
      fr: "Vous exploitez pour le client une partie de son informatique, avec votre propre personnel. Typique des modèles MSP et MSSP.",
      it: "Gestite per il cliente parti della sua infrastruttura IT, con personale proprio. Tipico dei modelli MSP e MSSP.",
      es: "Opera para el cliente partes de su TI, con personal propio. Típico de los modelos MSP y MSSP.",
      pl: "Obsługujesz dla klienta części jego infrastruktury IT, własnym personelem. Typowe dla modeli MSP i MSSP.",
      cs: "Provozujete pro zákazníka části jeho IT vlastním personálem. Typické pro modely MSP a MSSP.",
      pt: "Opera para o cliente partes da sua TI, com pessoal próprio. Típico dos modelos MSP e MSSP.",
      ro: "Operați pentru client părți din infrastructura sa IT, cu personal propriu. Tipic pentru modelele MSP și MSSP.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "processesCustomerData",
    section: "profile",
    type: "boolean",
    label: {
      en: "We process or store our customers' data",
      de: "Wir verarbeiten oder speichern Daten unserer Kunden",
    },
    description: {
      en: "Tick yes if your customers' data sits on or passes through your systems, for example in your software, your data centre or your ticket system. With the next answer, this tells a customer how much the rest of your answers matter to them.",
      de: "Ja, wenn Daten Ihrer Kunden auf Ihren Systemen liegen oder durch sie laufen, zum Beispiel in Ihrer Software, Ihrem Rechenzentrum oder Ihrem Ticketsystem. Zusammen mit der nächsten Antwort sieht ein Kunde daran, wie schwer Ihre übrigen Antworten für ihn wiegen.",
    },
    legalBasis: "ENISA TIG §5.1.2",
    required: true,
  },
  {
    id: "accessesCustomerSystems",
    section: "profile",
    type: "boolean",
    label: {
      en: "We access our customers' systems",
      de: "Wir greifen auf Systeme unserer Kunden zu",
    },
    description: {
      en: "Tick yes if you can sign in to your customers' systems, remotely, as an administrator or on site, for example for maintenance, support or operations.",
      de: "Ja, wenn Sie sich bei Ihren Kunden anmelden können, aus der Ferne, als Administrator oder vor Ort, zum Beispiel für Wartung, Support oder Betrieb.",
    },
    legalBasis: "ENISA TIG §5.1.2",
    required: true,
  },
];
