// Source of truth for the supplier questionnaire fields in this section.
// Edit this file (not data/supply-chain-questionnaire.json) and run
// `bun run build:json` to regenerate the published JSON artefact.
//
// Descriptions are Mittelstand-readable plain language: what to type, with
// a short example where the question is ambiguous. Legal citations live in
// the `legalBasis` field so audit teams still see the source. Labels are
// the public schema contract and are not edited here.

import type { SupplierField } from "../schema";

export const profileFields: SupplierField[] = [
  {
    id: "legalName",
    section: "profile",
    type: "string",
    label: {
      en: "Legal name",
      de: "Firmierung (Rechtsname)",
      fr: "Raison sociale",
      it: "Denominazione legale",
      es: "Razón social",
      pl: "Nazwa prawna",
      cs: "Obchodní firma (právní název)",
      pt: "Denominação social",
      ro: "Denumirea legală",
    },
    description: {
      en: "Your company's registered name, as it appears in the commercial register. Example: Müller GmbH or Acme Software Ltd.",
      de: "Der eingetragene Name Ihres Unternehmens, so wie er im Handelsregister steht. Beispiel: Müller GmbH oder Schmidt AG.",
      fr: "Le nom enregistré de votre entreprise, tel qu'il figure au registre du commerce. Exemple : Müller GmbH ou Acme Software Ltd.",
      it: "Il nome registrato della vostra azienda, così come appare nel registro delle imprese. Esempio: Müller GmbH o Acme Software Ltd.",
      es: "El nombre registrado de su empresa, tal como aparece en el registro mercantil. Ejemplo: Müller GmbH o Acme Software Ltd.",
      pl: "Zarejestrowana nazwa Twojej firmy, taka jak widnieje w rejestrze handlowym. Przykład: Müller GmbH lub Acme Software Ltd.",
      cs: "Zapsaný název vaší společnosti tak, jak je uveden v obchodním rejstříku. Příklad: Müller GmbH nebo Acme Software Ltd.",
      pt: "O nome registado da sua empresa, tal como consta do registo comercial. Exemplo: Müller GmbH ou Acme Software Ltd.",
      ro: "Denumirea înregistrată a companiei dumneavoastră, astfel cum apare în registrul comerțului. Exemplu: Müller GmbH sau Acme Software Ltd.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "registeredAddress",
    section: "profile",
    type: "string",
    label: {
      en: "Registered address",
      de: "Geschäftsanschrift",
      fr: "Adresse du siège social",
      it: "Indirizzo della sede legale",
      es: "Domicilio social",
      pl: "Adres siedziby",
      cs: "Sídlo společnosti",
      pt: "Sede social",
      ro: "Adresa sediului social",
    },
    description: {
      en: "Your company's registered business address. One address is enough, even if you have several locations.",
      de: "Die Geschäftsanschrift Ihres Unternehmens. Eine Adresse genügt, auch wenn Sie mehrere Standorte haben.",
      fr: "L'adresse commerciale enregistrée de votre entreprise. Une seule adresse suffit, même si vous avez plusieurs sites.",
      it: "L'indirizzo commerciale registrato della vostra azienda. È sufficiente un solo indirizzo, anche se avete più sedi.",
      es: "El domicilio comercial registrado de su empresa. Basta con una dirección, aunque tenga varias ubicaciones.",
      pl: "Zarejestrowany adres prowadzenia działalności Twojej firmy. Wystarczy jeden adres, nawet jeśli masz kilka lokalizacji.",
      cs: "Zapsaná obchodní adresa vaší společnosti. Jedna adresa stačí, i když máte více provozoven.",
      pt: "O endereço comercial registado da sua empresa. Basta um endereço, mesmo que tenha várias localizações.",
      ro: "Adresa comercială înregistrată a companiei dumneavoastră. Este suficientă o singură adresă, chiar dacă aveți mai multe locații.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "country",
    section: "profile",
    type: "country",
    label: {
      en: "Country",
      de: "Land",
      fr: "Pays",
      it: "Paese",
      es: "País",
      pl: "Kraj",
      cs: "Země",
      pt: "País",
      ro: "Țară",
    },
    description: {
      en: "The country where your company is legally established. Two letters, e.g. DE for Germany.",
      de: "Das Land, in dem Ihr Unternehmen rechtlich sitzt. Zwei Buchstaben, zum Beispiel DE für Deutschland.",
      fr: "Le pays où votre entreprise est légalement établie. Deux lettres, par exemple DE pour l'Allemagne.",
      it: "Il paese in cui la vostra azienda è legalmente stabilita. Due lettere, ad esempio DE per la Germania.",
      es: "El país donde su empresa está legalmente establecida. Dos letras, por ejemplo DE para Alemania.",
      pl: "Kraj, w którym Twoja firma ma siedzibę prawną. Dwie litery, np. DE dla Niemiec.",
      cs: "Země, ve které je vaše společnost právně usazena. Dvě písmena, například DE pro Německo.",
      pt: "O país onde a sua empresa está legalmente estabelecida. Duas letras, por exemplo DE para a Alemanha.",
      ro: "Țara în care compania dumneavoastră este stabilită legal. Două litere, de exemplu DE pentru Germania.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "primaryDomain",
    section: "profile",
    type: "url",
    label: {
      en: "Primary domain",
      de: "Primäre Domain",
      fr: "Domaine principal",
      it: "Dominio principale",
      es: "Dominio principal",
      pl: "Domena główna",
      cs: "Hlavní doména",
      pt: "Domínio principal",
      ro: "Domeniu principal",
    },
    description: {
      en: "Your main domain, usually the URL of your website. Example: acmesoftware.com.",
      de: "Ihre Hauptdomain, üblicherweise die Adresse Ihrer Webseite. Beispiel: muellergmbh.de.",
      fr: "Votre domaine principal, généralement l'URL de votre site web. Exemple : acmesoftware.com.",
      it: "Il vostro dominio principale, di solito l'URL del vostro sito web. Esempio: acmesoftware.com.",
      es: "Su dominio principal, normalmente la URL de su sitio web. Ejemplo: acmesoftware.com.",
      pl: "Twoja domena główna, zwykle adres URL Twojej witryny. Przykład: acmesoftware.com.",
      cs: "Vaše hlavní doména, obvykle adresa URL vašich webových stránek. Příklad: acmesoftware.com.",
      pt: "O seu domínio principal, normalmente o URL do seu sítio web. Exemplo: acmesoftware.com.",
      ro: "Domeniul dumneavoastră principal, de obicei adresa URL a site-ului web. Exemplu: acmesoftware.com.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "tagline",
    section: "profile",
    type: "string",
    label: {
      en: "Tagline (one line, customer-facing)",
      de: "Slogan (eine Zeile, kundenseitig sichtbar)",
      fr: "Slogan (une ligne, visible par les clients)",
      it: "Slogan (una riga, visibile ai clienti)",
      es: "Eslogan (una línea, visible para el cliente)",
      pl: "Slogan (jedna linia, widoczny dla klientów)",
      cs: "Slogan (jeden řádek, viditelný pro zákazníky)",
      pt: "Slogan (uma linha, visível para os clientes)",
      ro: "Slogan (un rând, vizibil pentru clienți)",
    },
    description: {
      en: "One line summarising what you offer. Customers see this on your supplier profile. Example: ERP for SME manufacturing.",
      de: "Eine Zeile, die Ihre Leistung zusammenfasst. Kunden sehen diese im Lieferantenprofil. Beispiel: ERP für mittelständische Produktion.",
      fr: "Une ligne résumant ce que vous proposez. Les clients la voient sur votre profil fournisseur. Exemple : ERP pour l'industrie manufacturière des PME.",
      it: "Una riga che riassume ciò che offrite. I clienti la vedono nel vostro profilo fornitore. Esempio: ERP per la produzione delle PMI.",
      es: "Una línea que resume lo que ofrece. Los clientes la ven en su perfil de proveedor. Ejemplo: ERP para la fabricación de pymes.",
      pl: "Jedna linia podsumowująca Twoją ofertę. Klienci widzą ją w Twoim profilu dostawcy. Przykład: ERP dla produkcji w sektorze MŚP.",
      cs: "Jeden řádek shrnující, co nabízíte. Zákazníci jej vidí ve vašem profilu dodavatele. Příklad: ERP pro výrobu v malých a středních podnicích.",
      pt: "Uma linha a resumir o que oferece. Os clientes veem-na no seu perfil de fornecedor. Exemplo: ERP para a indústria transformadora das PME.",
      ro: "Un rând care rezumă ceea ce oferiți. Clienții îl văd în profilul dumneavoastră de furnizor. Exemplu: ERP pentru producția din IMM-uri.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "description",
    section: "profile",
    type: "text",
    label: {
      en: "Public description (longer)",
      de: "Öffentliche Beschreibung (länger)",
      fr: "Description publique (plus longue)",
      it: "Descrizione pubblica (più estesa)",
      es: "Descripción pública (más extensa)",
      pl: "Opis publiczny (dłuższy)",
      cs: "Veřejný popis (delší)",
      pt: "Descrição pública (mais longa)",
      ro: "Descriere publică (mai lungă)",
    },
    description: {
      en: "Two to three sentences about your company and what you do. This appears on your supplier profile. Sales pitch, security posture, or both.",
      de: "Zwei bis drei Sätze über Ihr Unternehmen und Ihre Leistung. Diese Beschreibung erscheint auf Ihrem Lieferantenprofil. Verkaufsversprechen, Sicherheitspositionierung oder beides.",
      fr: "Deux à trois phrases sur votre entreprise et votre activité. Ce texte apparaît sur votre profil fournisseur. Argumentaire commercial, posture de sécurité, ou les deux.",
      it: "Due o tre frasi sulla vostra azienda e su ciò che fate. Questo testo appare nel vostro profilo fornitore. Argomentazione commerciale, posizionamento di sicurezza o entrambi.",
      es: "Dos o tres frases sobre su empresa y lo que hace. Esto aparece en su perfil de proveedor. Argumento de venta, postura de seguridad o ambos.",
      pl: "Dwa do trzech zdań o Twojej firmie i tym, czym się zajmuje. Pojawia się to w Twoim profilu dostawcy. Argumentacja sprzedażowa, postawa w zakresie bezpieczeństwa lub oba elementy.",
      cs: "Dvě až tři věty o vaší společnosti a tom, co děláte. Zobrazí se ve vašem profilu dodavatele. Prodejní sdělení, bezpečnostní postoj nebo obojí.",
      pt: "Duas a três frases sobre a sua empresa e o que faz. Aparece no seu perfil de fornecedor. Argumento de venda, postura de segurança ou ambos.",
      ro: "Două sau trei propoziții despre compania dumneavoastră și ceea ce faceți. Apare în profilul dumneavoastră de furnizor. Argument de vânzare, postură de securitate sau ambele.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "serviceDescription",
    section: "profile",
    type: "text",
    label: {
      en: "Description of services provided",
      de: "Beschreibung der erbrachten Leistungen",
      fr: "Description des services fournis",
      it: "Descrizione dei servizi forniti",
      es: "Descripción de los servicios prestados",
      pl: "Opis świadczonych usług",
      cs: "Popis poskytovaných služeb",
      pt: "Descrição dos serviços prestados",
      ro: "Descrierea serviciilor furnizate",
    },
    description: {
      en: "One paragraph on what your company technically delivers to customers. Concrete products, modules, or services. Avoid pure marketing language.",
      de: "Ein Absatz darüber, was Ihr Unternehmen Kunden technisch liefert. Konkrete Produkte, Module oder Dienstleistungen. Vermeiden Sie reine Marketing-Sprache.",
      fr: "Un paragraphe sur ce que votre entreprise livre techniquement aux clients. Produits, modules ou services concrets. Évitez le langage purement marketing.",
      it: "Un paragrafo su ciò che la vostra azienda fornisce tecnicamente ai clienti. Prodotti, moduli o servizi concreti. Evitate il linguaggio puramente di marketing.",
      es: "Un párrafo sobre lo que su empresa entrega técnicamente a los clientes. Productos, módulos o servicios concretos. Evite el lenguaje puramente comercial.",
      pl: "Jeden akapit o tym, co Twoja firma technicznie dostarcza klientom. Konkretne produkty, moduły lub usługi. Unikaj czysto marketingowego języka.",
      cs: "Jeden odstavec o tom, co vaše společnost zákazníkům technicky dodává. Konkrétní produkty, moduly nebo služby. Vyhněte se čistě marketingovému jazyku.",
      pt: "Um parágrafo sobre o que a sua empresa entrega tecnicamente aos clientes. Produtos, módulos ou serviços concretos. Evite linguagem puramente de marketing.",
      ro: "Un paragraf despre ceea ce compania dumneavoastră livrează din punct de vedere tehnic clienților. Produse, module sau servicii concrete. Evitați limbajul pur de marketing.",
    },
    legalBasis: "ENISA TIG §5.2(b) + §5.1.4 TIPS",
    required: true,
  },
  {
    id: "dataProcessingLocations",
    section: "profile",
    type: "string",
    label: {
      en: "Countries / regions where customer data is processed",
      de: "Länder / Regionen, in denen Kundendaten verarbeitet werden",
      fr: "Pays / régions où les données des clients sont traitées",
      it: "Paesi / regioni in cui vengono trattati i dati dei clienti",
      es: "Países / regiones donde se tratan los datos de los clientes",
      pl: "Kraje / regiony, w których przetwarzane są dane klientów",
      cs: "Země / regiony, kde se zpracovávají data zákazníků",
      pt: "Países / regiões onde são tratados os dados dos clientes",
      ro: "Țări / regiuni în care sunt prelucrate datele clienților",
    },
    description: {
      en: "Every country where your customers' data is stored or processed. Comma-separated, ISO country codes. Example: DE, NL, US. If you process entirely within the EU, listing the EU countries is enough.",
      de: "Alle Länder, in denen Kundendaten Ihrer Kunden gespeichert oder verarbeitet werden. Komma-getrennt, ISO-Ländercodes. Beispiel: DE, NL, US. Wenn Sie ausschließlich in der EU verarbeiten, reicht eine Liste der EU-Länder.",
      fr: "Tous les pays où les données de vos clients sont stockées ou traitées. Séparés par des virgules, codes pays ISO. Exemple : DE, NL, US. Si vous traitez entièrement au sein de l'UE, lister les pays de l'UE suffit.",
      it: "Tutti i paesi in cui i dati dei vostri clienti vengono archiviati o trattati. Separati da virgole, codici paese ISO. Esempio: DE, NL, US. Se trattate interamente all'interno dell'UE, è sufficiente elencare i paesi dell'UE.",
      es: "Todos los países donde se almacenan o tratan los datos de sus clientes. Separados por comas, códigos de país ISO. Ejemplo: DE, NL, US. Si trata los datos enteramente dentro de la UE, basta con enumerar los países de la UE.",
      pl: "Wszystkie kraje, w których przechowywane lub przetwarzane są dane Twoich klientów. Oddzielone przecinkami, kody krajów ISO. Przykład: DE, NL, US. Jeśli przetwarzasz dane wyłącznie w UE, wystarczy wymienić kraje UE.",
      cs: "Všechny země, kde se ukládají nebo zpracovávají data vašich zákazníků. Oddělené čárkami, kódy zemí ISO. Příklad: DE, NL, US. Pokud zpracováváte výhradně v rámci EU, stačí uvést země EU.",
      pt: "Todos os países onde os dados dos seus clientes são armazenados ou tratados. Separados por vírgulas, códigos de país ISO. Exemplo: DE, NL, US. Se tratar os dados inteiramente dentro da UE, basta enumerar os países da UE.",
      ro: "Toate țările în care datele clienților dumneavoastră sunt stocate sau prelucrate. Separate prin virgule, coduri de țară ISO. Exemplu: DE, NL, US. Dacă prelucrați integral în interiorul UE, este suficient să enumerați țările UE.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "securityContactName",
    section: "profile",
    type: "string",
    label: {
      en: "Security contact name",
      de: "Name des Sicherheitskontakts",
      fr: "Nom du contact sécurité",
      it: "Nome del referente per la sicurezza",
      es: "Nombre del contacto de seguridad",
      pl: "Imię i nazwisko kontaktu ds. bezpieczeństwa",
      cs: "Jméno bezpečnostního kontaktu",
      pt: "Nome do contacto de segurança",
      ro: "Numele persoanei de contact pentru securitate",
    },
    description: {
      en: "Who customers contact when a security incident hits. In smaller companies often the managing director or IT lead. One person is enough.",
      de: "Wer bei einem Sicherheitsvorfall direkt angesprochen wird. Bei kleineren Unternehmen oft die Geschäftsführung oder die IT-Leitung. Eine Person genügt.",
      fr: "La personne que les clients contactent lors d'un incident de sécurité. Dans les petites entreprises, souvent le directeur général ou le responsable informatique. Une seule personne suffit.",
      it: "La persona che i clienti contattano in caso di incidente di sicurezza. Nelle aziende più piccole spesso l'amministratore delegato o il responsabile IT. È sufficiente una sola persona.",
      es: "La persona a la que los clientes contactan cuando se produce un incidente de seguridad. En las empresas más pequeñas suele ser el director general o el responsable de TI. Basta con una persona.",
      pl: "Osoba, z którą klienci kontaktują się w przypadku incydentu bezpieczeństwa. W mniejszych firmach często dyrektor zarządzający lub kierownik IT. Wystarczy jedna osoba.",
      cs: "Na koho se zákazníci obrátí, když dojde k bezpečnostnímu incidentu. V menších společnostech často jednatel nebo vedoucí IT. Jedna osoba stačí.",
      pt: "A quem os clientes recorrem quando ocorre um incidente de segurança. Nas empresas mais pequenas, muitas vezes o diretor-geral ou o responsável de TI. Basta uma pessoa.",
      ro: "Persoana pe care clienții o contactează atunci când are loc un incident de securitate. În companiile mai mici, adesea directorul general sau responsabilul IT. Este suficientă o singură persoană.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: true,
  },
  {
    id: "incidentContactEmail",
    section: "profile",
    type: "email",
    label: {
      en: "Incident contact email",
      de: "E-Mail für Vorfälle",
      fr: "E-mail de contact pour les incidents",
      it: "E-mail di contatto per gli incidenti",
      es: "Correo electrónico de contacto para incidentes",
      pl: "E-mail kontaktowy do zgłaszania incydentów",
      cs: "E-mail pro kontakt při incidentech",
      pt: "E-mail de contacto para incidentes",
      ro: "E-mail de contact pentru incidente",
    },
    description: {
      en: "Email address customers use to report a security incident. Ideally a distribution list like security@example.com that reaches multiple people.",
      de: "E-Mail-Adresse, die Kunden bei einem Sicherheitsvorfall verwenden. Idealerweise ein Verteiler wie security@firma.de, der mehrere Personen erreicht.",
      fr: "Adresse e-mail que les clients utilisent pour signaler un incident de sécurité. Idéalement une liste de diffusion comme security@example.com qui atteint plusieurs personnes.",
      it: "Indirizzo e-mail che i clienti utilizzano per segnalare un incidente di sicurezza. Idealmente una lista di distribuzione come security@example.com che raggiunge più persone.",
      es: "Dirección de correo electrónico que los clientes utilizan para notificar un incidente de seguridad. Idealmente una lista de distribución como security@example.com que llegue a varias personas.",
      pl: "Adres e-mail, którego klienci używają do zgłaszania incydentu bezpieczeństwa. Najlepiej lista dystrybucyjna, taka jak security@example.com, która dociera do wielu osób.",
      cs: "E-mailová adresa, kterou zákazníci používají k nahlášení bezpečnostního incidentu. Ideálně distribuční seznam jako security@example.com, který zastihne více osob.",
      pt: "Endereço de e-mail que os clientes utilizam para comunicar um incidente de segurança. Idealmente uma lista de distribuição como security@example.com que chegue a várias pessoas.",
      ro: "Adresa de e-mail pe care clienții o folosesc pentru a raporta un incident de securitate. În mod ideal, o listă de distribuție precum security@example.com care ajunge la mai multe persoane.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: true,
  },
  {
    id: "incidentContactPhone",
    section: "profile",
    type: "phone",
    label: {
      en: "Incident contact phone (24/7)",
      de: "Telefonnummer für Vorfälle (24/7)",
      fr: "Téléphone de contact pour les incidents (24/7)",
      it: "Telefono di contatto per gli incidenti (24/7)",
      es: "Teléfono de contacto para incidentes (24/7)",
      pl: "Telefon kontaktowy do zgłaszania incydentów (24/7)",
      cs: "Telefon pro kontakt při incidentech (24/7)",
      pt: "Telefone de contacto para incidentes (24/7)",
      ro: "Telefon de contact pentru incidente (24/7)",
    },
    description: {
      en: "Phone number for urgent incident reports. If you do not run 24/7 on-call, mention your business hours in brackets.",
      de: "Telefonnummer für dringende Vorfallsmeldungen. Wenn Sie keinen 24/7-Bereitschaftsdienst haben, geben Sie die Geschäftszeiten in Klammern an.",
      fr: "Numéro de téléphone pour les signalements urgents d'incidents. Si vous n'assurez pas d'astreinte 24/7, indiquez vos heures ouvrées entre parenthèses.",
      it: "Numero di telefono per le segnalazioni urgenti di incidenti. Se non disponete di reperibilità 24/7, indicate il vostro orario lavorativo tra parentesi.",
      es: "Número de teléfono para las notificaciones urgentes de incidentes. Si no dispone de guardia 24/7, indique su horario laboral entre paréntesis.",
      pl: "Numer telefonu do pilnych zgłoszeń incydentów. Jeśli nie prowadzisz dyżuru 24/7, podaj godziny pracy w nawiasie.",
      cs: "Telefonní číslo pro naléhavá hlášení incidentů. Pokud neprovozujete pohotovost 24/7, uveďte v závorce svou pracovní dobu.",
      pt: "Número de telefone para comunicações urgentes de incidentes. Se não dispuser de piquete 24/7, indique o seu horário de funcionamento entre parênteses.",
      ro: "Număr de telefon pentru raportările urgente de incidente. Dacă nu aveți serviciu de permanență 24/7, indicați programul de lucru între paranteze.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: false,
  },
  {
    id: "incidentSlaHours",
    section: "profile",
    type: "integer",
    label: {
      en: "Incident notification SLA (hours)",
      de: "Meldefrist für Vorfälle (Stunden)",
      fr: "SLA de notification d'incident (heures)",
      it: "SLA di notifica degli incidenti (ore)",
      es: "SLA de notificación de incidentes (horas)",
      pl: "SLA powiadamiania o incydentach (godziny)",
      cs: "SLA pro oznamování incidentů (hodiny)",
      pt: "SLA de notificação de incidentes (horas)",
      ro: "SLA de notificare a incidentelor (ore)",
    },
    description: {
      en: "Hours from incident detection to customer notification, at the latest. Realistic self-assessment, not aspirational. Common values: 24, 48, or 72 hours.",
      de: "Wie viele Stunden Sie maximal brauchen, um einen Kunden nach Erkennung eines Vorfalls zu informieren. Realistische Selbsteinschätzung, nicht Wunschwert. Übliche Werte: 24, 48 oder 72 Stunden.",
      fr: "Heures entre la détection d'un incident et la notification au client, au plus tard. Auto-évaluation réaliste, pas un objectif théorique. Valeurs courantes : 24, 48 ou 72 heures.",
      it: "Ore tra il rilevamento di un incidente e la notifica al cliente, al più tardi. Autovalutazione realistica, non un valore ideale. Valori comuni: 24, 48 o 72 ore.",
      es: "Horas desde la detección de un incidente hasta la notificación al cliente, como máximo. Autoevaluación realista, no aspiracional. Valores habituales: 24, 48 o 72 horas.",
      pl: "Liczba godzin od wykrycia incydentu do powiadomienia klienta, najpóźniej. Realistyczna samoocena, a nie wartość docelowa. Typowe wartości: 24, 48 lub 72 godziny.",
      cs: "Počet hodin od zjištění incidentu do oznámení zákazníkovi, nejpozději. Realistické sebehodnocení, nikoli cílová hodnota. Obvyklé hodnoty: 24, 48 nebo 72 hodin.",
      pt: "Horas desde a deteção de um incidente até à notificação do cliente, o mais tardar. Autoavaliação realista, não aspiracional. Valores comuns: 24, 48 ou 72 horas.",
      ro: "Numărul de ore de la detectarea unui incident până la notificarea clientului, cel târziu. Autoevaluare realistă, nu o valoare aspirațională. Valori uzuale: 24, 48 sau 72 de ore.",
    },
    legalBasis: "NIS2 Art. 23",
    required: false,
  },
  {
    id: "bsiRegistrationId",
    section: "profile",
    type: "string",
    label: {
      en: "BSI registration ID (only if your company is itself NIS2-regulated)",
      de: "BSI-Registrierungs-ID (nur falls Ihr Unternehmen selbst NIS2-reguliert ist)",
      fr: "Identifiant d'enregistrement BSI (uniquement si votre entreprise est elle-même réglementée par NIS2)",
      it: "ID di registrazione BSI (solo se la vostra azienda è essa stessa regolamentata da NIS2)",
      es: "ID de registro BSI (solo si su empresa está regulada por NIS2)",
      pl: "Identyfikator rejestracji BSI (tylko jeśli Twoja firma sama podlega NIS2)",
      cs: "Registrační ID BSI (pouze pokud vaše společnost sama podléhá NIS2)",
      pt: "ID de registo BSI (apenas se a sua empresa estiver ela própria sujeita a NIS2)",
      ro: "ID de înregistrare BSI (numai dacă firma dumneavoastră este ea însăși reglementată de NIS2)",
    },
    description: {
      en: "If your company is itself NIS 2 regulated and registered with the BSI, enter the registration ID here. Optional. Lets customers see at a glance that you meet the same obligation as a regulated entity.",
      de: "Wenn Ihr Unternehmen selbst der NIS 2 unterliegt und beim BSI registriert ist, tragen Sie die Registrierungs-ID hier ein. Optional. Kunden sehen damit auf einen Blick, dass Sie als regulierte Einrichtung dieselbe Pflicht erfüllen.",
      fr: "Si votre entreprise est elle-même soumise à NIS 2 et enregistrée auprès du BSI, saisissez ici l'identifiant d'enregistrement. Facultatif. Permet aux clients de voir d'un coup d'œil que vous remplissez la même obligation qu'une entité réglementée.",
      it: "Se la vostra azienda è essa stessa soggetta a NIS 2 e registrata presso il BSI, inserite qui l'ID di registrazione. Facoltativo. Consente ai clienti di vedere a colpo d'occhio che soddisfate lo stesso obbligo di un'entità regolamentata.",
      es: "Si su empresa está sujeta a NIS 2 y registrada ante el BSI, introduzca aquí el ID de registro. Opcional. Permite a los clientes ver de un vistazo que cumple la misma obligación que una entidad regulada.",
      pl: "Jeśli Twoja firma sama podlega NIS 2 i jest zarejestrowana w BSI, wpisz tutaj identyfikator rejestracji. Opcjonalne. Pozwala klientom od razu zobaczyć, że spełniasz ten sam obowiązek co podmiot regulowany.",
      cs: "Pokud vaše společnost sama podléhá NIS 2 a je registrována u BSI, zadejte zde registrační ID. Volitelné. Zákazníci tak na první pohled vidí, že plníte stejnou povinnost jako regulovaný subjekt.",
      pt: "Se a sua empresa estiver ela própria sujeita à NIS 2 e registada junto do BSI, introduza aqui o ID de registo. Opcional. Permite aos clientes ver de imediato que cumpre a mesma obrigação que uma entidade regulada.",
      ro: "Dacă firma dumneavoastră este ea însăși supusă NIS 2 și înregistrată la BSI, introduceți aici ID-ul de înregistrare. Opțional. Le permite clienților să vadă dintr-o privire că îndepliniți aceeași obligație ca o entitate reglementată.",
    },
    legalBasis: "ENISA TIG §5.1.2",
    required: false,
  },
  {
    id: "isSaas",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide SaaS / hosted services",
      de: "Wir bieten SaaS / gehostete Dienste",
      fr: "Nous fournissons des services SaaS / hébergés",
      it: "Forniamo servizi SaaS / in hosting",
      es: "Ofrecemos servicios SaaS / alojados",
      pl: "Świadczymy usługi SaaS / hostowane",
      cs: "Poskytujeme SaaS / hostované služby",
      pt: "Fornecemos serviços SaaS / alojados",
      ro: "Furnizăm servicii SaaS / găzduite",
    },
    description: {
      en: "You run software for customers on your own infrastructure and deliver it over the internet. Tick more than one box if you offer several models.",
      de: "Sie betreiben Software für Kunden auf eigener Infrastruktur und liefern sie über das Internet. Mehrfachauswahl möglich, wenn Sie mehrere Modelle anbieten.",
      fr: "Vous exécutez des logiciels pour les clients sur votre propre infrastructure et les livrez via internet. Cochez plusieurs cases si vous proposez plusieurs modèles.",
      it: "Eseguite software per i clienti sulla vostra infrastruttura e lo erogate tramite internet. Selezionate più caselle se offrite più modelli.",
      es: "Ejecuta software para los clientes en su propia infraestructura y lo entrega a través de internet. Marque más de una casilla si ofrece varios modelos.",
      pl: "Uruchamiasz oprogramowanie dla klientów na własnej infrastrukturze i dostarczasz je przez internet. Zaznacz więcej niż jedno pole, jeśli oferujesz kilka modeli.",
      cs: "Provozujete software pro zákazníky na vlastní infrastruktuře a dodáváte jej přes internet. Pokud nabízíte více modelů, zaškrtněte více políček.",
      pt: "Executa software para os clientes na sua própria infraestrutura e entrega-o através da internet. Assinale mais do que uma caixa se oferecer vários modelos.",
      ro: "Rulați software pentru clienți pe propria infrastructură și îl livrați prin internet. Bifați mai multe casete dacă oferiți mai multe modele.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isOnPrem",
    section: "profile",
    type: "boolean",
    label: {
      en: "We deliver on-prem software",
      de: "Wir liefern On-Prem-Software",
      fr: "Nous livrons des logiciels on-premise",
      it: "Forniamo software on-premise",
      es: "Entregamos software on-premise",
      pl: "Dostarczamy oprogramowanie on-premise",
      cs: "Dodáváme on-premise software",
      pt: "Fornecemos software on-premise",
      ro: "Livrăm software on-premise",
    },
    description: {
      en: "You deliver software that customers install and run on their own infrastructure.",
      de: "Sie liefern Software, die Ihre Kunden auf ihrer eigenen Infrastruktur installieren und betreiben.",
      fr: "Vous livrez des logiciels que les clients installent et exécutent sur leur propre infrastructure.",
      it: "Fornite software che i clienti installano ed eseguono sulla propria infrastruttura.",
      es: "Entrega software que los clientes instalan y ejecutan en su propia infraestructura.",
      pl: "Dostarczasz oprogramowanie, które klienci instalują i uruchamiają na własnej infrastrukturze.",
      cs: "Dodáváte software, který si zákazníci instalují a provozují na vlastní infrastruktuře.",
      pt: "Fornece software que os clientes instalam e executam na sua própria infraestrutura.",
      ro: "Livrați software pe care clienții îl instalează și îl rulează pe propria infrastructură.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isProfessionalServices",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide professional services / consulting",
      de: "Wir bieten Dienstleistungen / Beratung",
      fr: "Nous fournissons des services professionnels / conseil",
      it: "Forniamo servizi professionali / consulenza",
      es: "Ofrecemos servicios profesionales / consultoría",
      pl: "Świadczymy usługi profesjonalne / doradztwo",
      cs: "Poskytujeme profesionální služby / poradenství",
      pt: "Fornecemos serviços profissionais / consultoria",
      ro: "Furnizăm servicii profesionale / consultanță",
    },
    description: {
      en: "Your main deliverable is human work: consulting, implementation, training, audit, or customisation.",
      de: "Sie liefern menschliche Arbeit als Hauptleistung: Beratung, Implementierung, Schulung, Audit oder Customizing.",
      fr: "Votre prestation principale est un travail humain : conseil, mise en œuvre, formation, audit ou personnalisation.",
      it: "La vostra prestazione principale è il lavoro umano: consulenza, implementazione, formazione, audit o personalizzazione.",
      es: "Su entregable principal es trabajo humano: consultoría, implementación, formación, auditoría o personalización.",
      pl: "Twoim głównym produktem jest praca ludzka: doradztwo, wdrożenie, szkolenia, audyt lub dostosowanie.",
      cs: "Vaším hlavním výstupem je lidská práce: poradenství, implementace, školení, audit nebo přizpůsobení.",
      pt: "O seu principal resultado é trabalho humano: consultoria, implementação, formação, auditoria ou personalização.",
      ro: "Principalul dumneavoastră livrabil este munca umană: consultanță, implementare, instruire, audit sau personalizare.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isManagedService",
    section: "profile",
    type: "boolean",
    label: {
      en: "We provide managed services / MSP",
      de: "Wir bieten Managed Services / MSP",
      fr: "Nous fournissons des services gérés / MSP",
      it: "Forniamo servizi gestiti / MSP",
      es: "Ofrecemos servicios gestionados / MSP",
      pl: "Świadczymy usługi zarządzane / MSP",
      cs: "Poskytujeme spravované služby / MSP",
      pt: "Fornecemos serviços geridos / MSP",
      ro: "Furnizăm servicii gestionate / MSP",
    },
    description: {
      en: "You operate parts of your customer's IT for them, with your own staff. Typical for MSP and MSSP models.",
      de: "Sie betreiben Teile der IT-Landschaft des Kunden für ihn, mit eigenem Personal. Typisch für MSP- und MSSP-Modelle.",
      fr: "Vous exploitez pour le client une partie de son informatique, avec votre propre personnel. Typique des modèles MSP et MSSP.",
      it: "Gestite per il cliente parti della sua infrastruttura IT, con personale proprio. Tipico dei modelli MSP e MSSP.",
      es: "Opera para el cliente partes de su TI, con personal propio. Típico de los modelos MSP y MSSP.",
      pl: "Obsługujesz dla klienta części jego infrastruktury IT, własnym personelem. Typowe dla modeli MSP i MSSP.",
      cs: "Provozujete pro zákazníka části jeho IT vlastním personálem. Typické pro modely MSP a MSSP.",
      pt: "Opera para o cliente partes da sua TI, com pessoal próprio. Típico dos modelos MSP e MSSP.",
      ro: "Operați pentru client părți din infrastructura sa IT, cu personal propriu. Tipic pentru modelele MSP și MSSP.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "usesAiSystems",
    section: "profile",
    type: "boolean",
    label: {
      en: "We use, integrate or provide AI systems",
      de: "Wir nutzen, integrieren oder bieten KI-Systeme",
      fr: "Nous utilisons, intégrons ou fournissons des systèmes d'IA",
      it: "Utilizziamo, integriamo o forniamo sistemi di IA",
      es: "Utilizamos, integramos o proporcionamos sistemas de IA",
      pl: "Używamy, integrujemy lub dostarczamy systemy SI",
      cs: "Používáme, integrujeme nebo poskytujeme systémy AI",
      pt: "Utilizamos, integramos ou fornecemos sistemas de IA",
      ro: "Utilizăm, integrăm sau furnizăm sisteme de IA",
    },
    description: {
      en: "Do your products or services process customer data through an AI or ML model? Includes external models you call through an API, for example OpenAI or Anthropic.",
      de: "Verarbeiten Ihre Produkte oder Dienste Kundendaten durch ein KI- oder ML-Modell? Inklusive externer Modelle, die Sie über eine API anbinden, zum Beispiel OpenAI oder Anthropic.",
      fr: "Vos produits ou services traitent-ils les données des clients via un modèle d'IA ou de ML ? Cela inclut les modèles externes que vous appelez via une API, par exemple OpenAI ou Anthropic.",
      it: "I vostri prodotti o servizi trattano i dati dei clienti tramite un modello di IA o ML? Sono inclusi i modelli esterni richiamati tramite API, ad esempio OpenAI o Anthropic.",
      es: "¿Sus productos o servicios tratan datos de los clientes mediante un modelo de IA o ML? Incluye modelos externos a los que llama a través de una API, por ejemplo OpenAI o Anthropic.",
      pl: "Czy Twoje produkty lub usługi przetwarzają dane klientów za pomocą modelu SI lub ML? Obejmuje to modele zewnętrzne wywoływane przez API, na przykład OpenAI lub Anthropic.",
      cs: "Zpracovávají vaše produkty nebo služby data zákazníků prostřednictvím modelu AI nebo ML? Včetně externích modelů, které voláte přes API, například OpenAI nebo Anthropic.",
      pt: "Os seus produtos ou serviços tratam dados dos clientes através de um modelo de IA ou ML? Inclui modelos externos que invoca através de uma API, por exemplo OpenAI ou Anthropic.",
      ro: "Produsele sau serviciile dumneavoastră prelucrează datele clienților printr-un model de IA sau ML? Include modele externe pe care le apelați printr-un API, de exemplu OpenAI sau Anthropic.",
    },
    legalBasis: "NIS2 Art. 21(2)(d)",
    required: true,
  },
];
