// Source of truth for the supplier questionnaire fields in this section.
// Edit this file (not data/supply-chain-questionnaire.json) and run
// `bun run build:json` to regenerate the published JSON artefact.

import type { SupplierField } from "../schema";

export const saasTechnicalFields: SupplierField[] = [
  {
    id: "saasHostingRegion",
    section: "saas_technical",
    type: "string",
    label: {
      en: "Hosting region",
      de: "Hosting-Region",
      fr: "Région d'hébergement",
      it: "Regione di hosting",
      es: "Región de alojamiento",
      pl: "Region hostingu",
      cs: "Region hostingu",
      pt: "Região de alojamento",
      ro: "Regiunea de găzduire",
    },
    description: {
      en: "The cloud region where customer data is hosted. Example: AWS eu-central-1, Azure West Europe. Name the primary region; secondary or backup regions can be added comma-separated.",
      de: "Die Cloud-Region, in der Kundendaten gehostet werden. Beispiel: AWS eu-central-1, Azure West Europe. Geben Sie die Hauptregion an, Sekundär- oder Backup-Regionen kommen als kommagetrennte Liste dazu.",
      fr: "La région cloud où les données des clients sont hébergées. Exemple : AWS eu-central-1, Azure West Europe. Indiquez la région principale ; les régions secondaires ou de sauvegarde peuvent être ajoutées séparées par des virgules.",
      it: "La regione cloud in cui sono ospitati i dati dei clienti. Esempio: AWS eu-central-1, Azure West Europe. Indicare la regione principale; le regioni secondarie o di backup possono essere aggiunte separate da virgole.",
      es: "La región de la nube donde se alojan los datos de los clientes. Ejemplo: AWS eu-central-1, Azure West Europe. Indique la región principal; las regiones secundarias o de respaldo pueden añadirse separadas por comas.",
      pl: "Region chmury, w którym hostowane są dane klientów. Przykład: AWS eu-central-1, Azure West Europe. Podaj region główny; regiony zapasowe lub do tworzenia kopii zapasowych można dodać po przecinku.",
      cs: "Region cloudu, ve kterém jsou hostována zákaznická data. Příklad: AWS eu-central-1, Azure West Europe. Uveďte hlavní region; sekundární nebo záložní regiony lze doplnit oddělené čárkami.",
      pt: "A região da nuvem onde os dados dos clientes são alojados. Exemplo: AWS eu-central-1, Azure West Europe. Indique a região principal; as regiões secundárias ou de cópia de segurança podem ser acrescentadas separadas por vírgulas.",
      ro: "Regiunea cloud în care sunt găzduite datele clienților. Exemplu: AWS eu-central-1, Azure West Europe. Indicați regiunea principală; regiunile secundare sau de rezervă pot fi adăugate separate prin virgule.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
    visibleWhen: { field: "isSaas", equals: true },
  },
  {
    id: "saasEncryptionAtRest",
    section: "saas_technical",
    type: "boolean",
    label: {
      en: "Encryption at rest",
      de: "Verschlüsselung im Ruhezustand",
      fr: "Chiffrement au repos",
      it: "Cifratura dei dati a riposo",
      es: "Cifrado en reposo",
      pl: "Szyfrowanie danych w spoczynku",
      cs: "Šifrování dat v klidu",
      pt: "Cifragem dos dados em repouso",
      ro: "Criptarea datelor în repaus",
    },
    description: {
      en: "Tick yes if customer data on disk is encrypted at rest with AES-256 or equivalent. Cloud-managed disk encryption (AWS EBS, Azure Disk Encryption) counts.",
      de: "Ja, wenn Kundendaten auf der Festplatte mit AES-256 oder gleichwertig verschlüsselt sind. Cloud-verwaltete Festplattenverschlüsselung (AWS EBS, Azure Disk Encryption) zählt.",
      fr: "Cochez oui si les données des clients sur disque sont chiffrées au repos avec AES-256 ou équivalent. Le chiffrement de disque géré par le cloud (AWS EBS, Azure Disk Encryption) compte.",
      it: "Selezionare sì se i dati dei clienti su disco sono cifrati a riposo con AES-256 o equivalente. È valida la cifratura del disco gestita dal cloud (AWS EBS, Azure Disk Encryption).",
      es: "Marque sí si los datos de los clientes en disco están cifrados en reposo con AES-256 o equivalente. El cifrado de disco gestionado por la nube (AWS EBS, Azure Disk Encryption) cuenta.",
      pl: "Zaznacz tak, jeśli dane klientów na dysku są szyfrowane w spoczynku za pomocą AES-256 lub równoważnego standardu. Liczy się szyfrowanie dysków zarządzane przez chmurę (AWS EBS, Azure Disk Encryption).",
      cs: "Zaškrtněte ano, pokud jsou zákaznická data na disku šifrována v klidu pomocí AES-256 nebo rovnocenného standardu. Platí i šifrování disků spravované cloudem (AWS EBS, Azure Disk Encryption).",
      pt: "Assinale sim se os dados dos clientes em disco estiverem cifrados em repouso com AES-256 ou equivalente. A cifragem de disco gerida pela nuvem (AWS EBS, Azure Disk Encryption) conta.",
      ro: "Bifați da dacă datele clienților de pe disc sunt criptate în repaus cu AES-256 sau echivalent. Criptarea discului gestionată de cloud (AWS EBS, Azure Disk Encryption) este luată în calcul.",
    },
    legalBasis: "NIS2 Art. 21(2)(h) / ENISA TIG §9",
    required: true,
    visibleWhen: { field: "isSaas", equals: true },
  },
  {
    id: "saasEncryptionInTransit",
    section: "saas_technical",
    type: "boolean",
    label: {
      en: "Encryption in transit (TLS ≥ 1.2)",
      de: "Verschlüsselung bei Übertragung (TLS ≥ 1.2)",
      fr: "Chiffrement en transit (TLS ≥ 1.2)",
      it: "Cifratura in transito (TLS ≥ 1.2)",
      es: "Cifrado en tránsito (TLS ≥ 1.2)",
      pl: "Szyfrowanie podczas przesyłania (TLS ≥ 1.2)",
      cs: "Šifrování při přenosu (TLS ≥ 1.2)",
      pt: "Cifragem em trânsito (TLS ≥ 1.2)",
      ro: "Criptarea în tranzit (TLS ≥ 1.2)",
    },
    description: {
      en: "Tick yes if all customer-facing endpoints enforce TLS 1.2 or higher. TLS 1.3 is preferred. Plain HTTP must redirect to HTTPS.",
      de: "Ja, wenn alle kundenseitigen Endpunkte mindestens TLS 1.2 erzwingen. TLS 1.3 ist vorzuziehen. Reines HTTP muss auf HTTPS weiterleiten.",
      fr: "Cochez oui si tous les points d'accès exposés aux clients imposent TLS 1.2 ou supérieur. TLS 1.3 est préférable. Le HTTP simple doit rediriger vers HTTPS.",
      it: "Selezionare sì se tutti gli endpoint rivolti ai clienti impongono TLS 1.2 o superiore. TLS 1.3 è da preferire. Il semplice HTTP deve reindirizzare a HTTPS.",
      es: "Marque sí si todos los puntos de acceso orientados al cliente exigen TLS 1.2 o superior. Se prefiere TLS 1.3. El HTTP simple debe redirigir a HTTPS.",
      pl: "Zaznacz tak, jeśli wszystkie punkty końcowe dostępne dla klientów wymuszają TLS 1.2 lub wyższy. Preferowany jest TLS 1.3. Zwykły HTTP musi przekierowywać na HTTPS.",
      cs: "Zaškrtněte ano, pokud všechny koncové body dostupné zákazníkům vynucují TLS 1.2 nebo vyšší. Preferován je TLS 1.3. Prostý HTTP musí přesměrovávat na HTTPS.",
      pt: "Assinale sim se todos os pontos de extremidade orientados ao cliente impuserem TLS 1.2 ou superior. É preferível o TLS 1.3. O HTTP simples deve redirecionar para HTTPS.",
      ro: "Bifați da dacă toate punctele finale orientate către clienți impun TLS 1.2 sau o versiune superioară. Este de preferat TLS 1.3. HTTP simplu trebuie să redirecționeze către HTTPS.",
    },
    legalBasis: "NIS2 Art. 21(2)(h) / ENISA TIG §9",
    required: true,
    visibleWhen: { field: "isSaas", equals: true },
  },
  {
    id: "saasMfaEnforced",
    section: "saas_technical",
    type: "boolean",
    label: {
      en: "MFA enforced for all admin accounts",
      de: "MFA für alle Admin-Konten erzwungen",
      fr: "MFA imposé pour tous les comptes d'administration",
      it: "MFA imposto per tutti gli account amministrativi",
      es: "MFA obligatorio para todas las cuentas de administración",
      pl: "MFA wymuszone dla wszystkich kont administracyjnych",
      cs: "MFA vynuceno pro všechny administrátorské účty",
      pt: "MFA imposta para todas as contas de administração",
      ro: "MFA impusă pentru toate conturile de administrare",
    },
    description: {
      en: "Tick yes if every internal admin account on the SaaS platform must use MFA. Same standard as your internal admin policy.",
      de: "Ja, wenn jedes interne Admin-Konto auf der SaaS-Plattform MFA verwenden muss. Gleicher Standard wie für Ihre internen Admin-Vorgaben.",
      fr: "Cochez oui si chaque compte d'administration interne sur la plateforme SaaS doit utiliser le MFA. Même standard que votre politique d'administration interne.",
      it: "Selezionare sì se ogni account amministrativo interno sulla piattaforma SaaS deve utilizzare l'MFA. Stesso standard della vostra policy amministrativa interna.",
      es: "Marque sí si cada cuenta de administración interna en la plataforma SaaS debe usar MFA. El mismo estándar que su política de administración interna.",
      pl: "Zaznacz tak, jeśli każde wewnętrzne konto administracyjne na platformie SaaS musi używać MFA. Ten sam standard co Twoja wewnętrzna polityka administracyjna.",
      cs: "Zaškrtněte ano, pokud každý interní administrátorský účet na platformě SaaS musí používat MFA. Stejný standard jako vaše interní administrátorská pravidla.",
      pt: "Assinale sim se todas as contas de administração internas na plataforma SaaS tiverem de utilizar MFA. O mesmo padrão da sua política de administração interna.",
      ro: "Bifați da dacă fiecare cont de administrare intern de pe platforma SaaS trebuie să utilizeze MFA. Același standard ca politica dumneavoastră internă de administrare.",
    },
    legalBasis: "NIS2 Art. 21(2)(j) / ENISA TIG §11.3",
    required: true,
    visibleWhen: { field: "isSaas", equals: true },
  },
  {
    id: "saasRtoHours",
    section: "saas_technical",
    type: "integer",
    label: {
      en: "Recovery time objective (RTO) in hours",
      de: "Recovery Time Objective (RTO) in Stunden",
      fr: "Objectif de temps de reprise (RTO) en heures",
      it: "Obiettivo del tempo di ripristino (RTO) in ore",
      es: "Objetivo de tiempo de recuperación (RTO) en horas",
      pl: "Docelowy czas przywrócenia (RTO) w godzinach",
      cs: "Cílová doba obnovení (RTO) v hodinách",
      pt: "Objetivo de tempo de recuperação (RTO) em horas",
      ro: "Obiectivul de timp de recuperare (RTO) în ore",
    },
    description: {
      en: "Maximum number of hours your service can be unavailable before recovery. Realistic SLA value, not aspirational. Common SaaS values: 4, 8, or 24 hours.",
      de: "Maximale Anzahl Stunden, die Ihr Dienst ausfallen darf, bevor die Wiederherstellung greift. Realistischer SLA-Wert, kein Wunschwert. Übliche SaaS-Werte: 4, 8 oder 24 Stunden.",
      fr: "Nombre maximal d'heures pendant lesquelles votre service peut être indisponible avant reprise. Valeur SLA réaliste, pas un objectif théorique. Valeurs SaaS courantes : 4, 8 ou 24 heures.",
      it: "Numero massimo di ore in cui il servizio può essere non disponibile prima del ripristino. Valore SLA realistico, non un valore ideale. Valori SaaS comuni: 4, 8 o 24 ore.",
      es: "Número máximo de horas que su servicio puede estar no disponible antes de la recuperación. Valor de SLA realista, no aspiracional. Valores habituales de SaaS: 4, 8 o 24 horas.",
      pl: "Maksymalna liczba godzin, przez które Twoja usługa może być niedostępna przed przywróceniem. Realistyczna wartość SLA, a nie wartość docelowa. Typowe wartości SaaS: 4, 8 lub 24 godziny.",
      cs: "Maximální počet hodin, po které může být vaše služba nedostupná před obnovením. Realistická hodnota SLA, nikoli aspirační. Obvyklé hodnoty SaaS: 4, 8 nebo 24 hodin.",
      pt: "Número máximo de horas em que o seu serviço pode estar indisponível antes da recuperação. Valor de SLA realista, não aspiracional. Valores comuns de SaaS: 4, 8 ou 24 horas.",
      ro: "Numărul maxim de ore în care serviciul dumneavoastră poate fi indisponibil înainte de recuperare. Valoare SLA realistă, nu aspirațională. Valori SaaS frecvente: 4, 8 sau 24 de ore.",
    },
    legalBasis: "NIS2 Art. 21(2)(c) / ENISA TIG §4",
    required: true,
    visibleWhen: { field: "isSaas", equals: true },
  },
];
