// Source of truth for the supplier questionnaire fields in this section.
// Edit this file (not data/supply-chain-questionnaire.json) and run
// `bun run build:json` to regenerate the published JSON artefact.
//
// Descriptions are Mittelstand-readable plain language with a "tick yes if"
// threshold and concrete examples. Legal citations live in `legalBasis` so
// audit teams still see the source. Labels are the public schema contract
// and are not edited here.

import type { SupplierField } from "../schema";

export const securityPracticesFields: SupplierField[] = [
  {
    id: "hasIsms",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented Information Security Management System (ISMS)",
      de: "Dokumentiertes Informationssicherheits-Managementsystem (ISMS)",
      fr: "Système de management de la sécurité de l'information documenté (ISMS)",
      it: "Sistema di gestione della sicurezza delle informazioni documentato (ISMS)",
      es: "Sistema de gestión de la seguridad de la información documentado (ISMS)",
      pl: "Udokumentowany system zarządzania bezpieczeństwem informacji (ISMS)",
      cs: "Dokumentovaný systém řízení bezpečnosti informací (ISMS)",
      pt: "Sistema de gestão da segurança da informação documentado (ISMS)",
      ro: "Sistem documentat de management al securității informației (ISMS)",
    },
    description: {
      en: "Tick yes if you have a written information security policy with assigned roles, regular reviews, and documented incident handling. ISO 27001 or BSI Grundschutz certification implies yes.",
      de: "Ja, wenn Sie eine schriftliche Informationssicherheits-Richtlinie haben, klar zugewiesene Rollen, regelmäßige Überprüfungen und einen dokumentierten Umgang mit Vorfällen. ISO 27001 oder BSI Grundschutz Zertifizierung bedeutet automatisch Ja.",
      fr: "Cochez oui si vous disposez d'une politique de sécurité de l'information écrite avec des rôles attribués, des revues régulières et une gestion documentée des incidents. Une certification ISO 27001 ou BSI Grundschutz implique oui.",
      it: "Selezionare sì se si dispone di una politica scritta di sicurezza delle informazioni con ruoli assegnati, revisioni periodiche e gestione documentata degli incidenti. Una certificazione ISO 27001 o BSI Grundschutz implica sì.",
      es: "Marque sí si dispone de una política escrita de seguridad de la información con roles asignados, revisiones periódicas y gestión documentada de incidentes. Una certificación ISO 27001 o BSI Grundschutz implica sí.",
      pl: "Zaznacz tak, jeśli masz pisemną politykę bezpieczeństwa informacji z przypisanymi rolami, regularnymi przeglądami i udokumentowaną obsługą incydentów. Certyfikacja ISO 27001 lub BSI Grundschutz oznacza tak.",
      cs: "Zaškrtněte ano, pokud máte písemnou politiku bezpečnosti informací s přidělenými rolemi, pravidelnými přezkumy a dokumentovaným řešením incidentů. Certifikace ISO 27001 nebo BSI Grundschutz znamená ano.",
      pt: "Assinale sim se tiver uma política escrita de segurança da informação com funções atribuídas, revisões periódicas e tratamento documentado de incidentes. Uma certificação ISO 27001 ou BSI Grundschutz implica sim.",
      ro: "Bifați da dacă aveți o politică scrisă de securitate a informației cu roluri atribuite, revizuiri periodice și gestionarea documentată a incidentelor. O certificare ISO 27001 sau BSI Grundschutz implică da.",
    },
    legalBasis: "CIR 2024/2690 §5.1.2(a)",
    required: true,
  },
  {
    id: "hasIso27001OrEquivalent",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Hold ISO 27001, BSI Grundschutz, or equivalent certification",
      de: "ISO 27001, BSI Grundschutz oder gleichwertige Zertifizierung",
      fr: "Détenir une certification ISO 27001, BSI Grundschutz ou équivalente",
      it: "Possesso di una certificazione ISO 27001, BSI Grundschutz o equivalente",
      es: "Disponer de certificación ISO 27001, BSI Grundschutz o equivalente",
      pl: "Posiadanie certyfikatu ISO 27001, BSI Grundschutz lub równoważnego",
      cs: "Držení certifikace ISO 27001, BSI Grundschutz nebo rovnocenné",
      pt: "Deter certificação ISO 27001, BSI Grundschutz ou equivalente",
      ro: "Deținerea certificării ISO 27001, BSI Grundschutz sau echivalente",
    },
    description: {
      en: "Tick yes if your company currently holds an ISO 27001, BSI Grundschutz, SOC 2 Type II, or equivalent certification. Upload the certificate in the Certifications tab.",
      de: "Ja, wenn Ihr Unternehmen aktuell nach ISO 27001, BSI Grundschutz, SOC 2 Type II oder einem gleichwertigen Standard zertifiziert ist. Das Zertifikat laden Sie im Reiter Zertifizierungen hoch.",
      fr: "Cochez oui si votre entreprise détient actuellement une certification ISO 27001, BSI Grundschutz, SOC 2 Type II ou équivalente. Téléchargez le certificat dans l'onglet Certifications.",
      it: "Selezionare sì se la vostra azienda possiede attualmente una certificazione ISO 27001, BSI Grundschutz, SOC 2 Type II o equivalente. Caricate il certificato nella scheda Certificazioni.",
      es: "Marque sí si su empresa dispone actualmente de una certificación ISO 27001, BSI Grundschutz, SOC 2 Type II o equivalente. Suba el certificado en la pestaña Certificaciones.",
      pl: "Zaznacz tak, jeśli Twoja firma posiada aktualnie certyfikat ISO 27001, BSI Grundschutz, SOC 2 Type II lub równoważny. Prześlij certyfikat w zakładce Certyfikaty.",
      cs: "Zaškrtněte ano, pokud vaše společnost aktuálně drží certifikaci ISO 27001, BSI Grundschutz, SOC 2 Type II nebo rovnocennou. Certifikát nahrajte na kartě Certifikace.",
      pt: "Assinale sim se a sua empresa detiver atualmente uma certificação ISO 27001, BSI Grundschutz, SOC 2 Type II ou equivalente. Carregue o certificado no separador Certificações.",
      ro: "Bifați da dacă societatea dumneavoastră deține în prezent o certificare ISO 27001, BSI Grundschutz, SOC 2 Type II sau echivalentă. Încărcați certificatul în fila Certificări.",
    },
    legalBasis: "CIR 2024/2690 §5.1.2(b)",
    required: true,
  },
  {
    id: "staffSecurityTraining",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Annual security awareness training for all staff",
      de: "Jährliche Security-Awareness-Schulung für alle Mitarbeitenden",
      fr: "Formation annuelle de sensibilisation à la sécurité pour tout le personnel",
      it: "Formazione annuale di sensibilizzazione alla sicurezza per tutto il personale",
      es: "Formación anual de concienciación en seguridad para todo el personal",
      pl: "Coroczne szkolenie z zakresu świadomości bezpieczeństwa dla całego personelu",
      cs: "Každoroční školení o povědomí o bezpečnosti pro všechny zaměstnance",
      pt: "Formação anual de sensibilização para a segurança para todo o pessoal",
      ro: "Instruire anuală de conștientizare a securității pentru tot personalul",
    },
    description: {
      en: "Tick yes if every staff member receives at least one annual information-security awareness training. E-learning counts; phishing simulations add to it.",
      de: "Ja, wenn alle Mitarbeitenden mindestens einmal pro Jahr eine Awareness-Schulung zur Informationssicherheit erhalten. E-Learning genügt, Phishing-Simulationen kommen oben drauf.",
      fr: "Cochez oui si chaque membre du personnel reçoit au moins une formation annuelle de sensibilisation à la sécurité de l'information. Le e-learning compte ; les simulations de phishing s'y ajoutent.",
      it: "Selezionare sì se ogni dipendente riceve almeno una formazione annuale di sensibilizzazione alla sicurezza delle informazioni. L'e-learning è valido; le simulazioni di phishing si aggiungono.",
      es: "Marque sí si cada miembro del personal recibe al menos una formación anual de concienciación en seguridad de la información. El e-learning cuenta; las simulaciones de phishing se suman.",
      pl: "Zaznacz tak, jeśli każdy pracownik otrzymuje co najmniej jedno coroczne szkolenie z zakresu świadomości bezpieczeństwa informacji. E-learning się liczy; symulacje phishingu są uzupełnieniem.",
      cs: "Zaškrtněte ano, pokud každý zaměstnanec absolvuje alespoň jedno každoroční školení o povědomí o bezpečnosti informací. E-learning se počítá, simulace phishingu jsou doplňkem.",
      pt: "Assinale sim se cada colaborador receber pelo menos uma formação anual de sensibilização para a segurança da informação. O e-learning conta, as simulações de phishing acrescentam-se.",
      ro: "Bifați da dacă fiecare angajat beneficiază de cel puțin o instruire anuală de conștientizare a securității informației. E-learningul contează, simulările de phishing se adaugă.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(b)",
    required: true,
  },
  {
    id: "backgroundChecks",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Background checks on staff with customer data access",
      de: "Zuverlässigkeitsprüfung für Mitarbeitende mit Kundendaten-Zugriff",
      fr: "Vérifications d'antécédents pour le personnel ayant accès aux données des clients",
      it: "Verifiche dei precedenti per il personale con accesso ai dati dei clienti",
      es: "Verificación de antecedentes del personal con acceso a datos de clientes",
      pl: "Weryfikacja przeszłości personelu z dostępem do danych klientów",
      cs: "Prověřování zaměstnanců s přístupem k zákaznickým datům",
      pt: "Verificação de antecedentes do pessoal com acesso a dados de clientes",
      ro: "Verificarea antecedentelor personalului cu acces la datele clienților",
    },
    description: {
      en: "Tick yes if you run a background check for staff with access to customer data. Common bar: a criminal record extract or equivalent document on hire.",
      de: "Ja, wenn Sie für Mitarbeitende mit Zugang zu Kundendaten eine Zuverlässigkeitsprüfung durchführen. Übliche Stufe: polizeiliches Führungszeugnis oder vergleichbares Dokument bei der Einstellung.",
      fr: "Cochez oui si vous effectuez une vérification d'antécédents pour le personnel ayant accès aux données des clients. Niveau courant : extrait de casier judiciaire ou document équivalent à l'embauche.",
      it: "Selezionare sì se si effettua una verifica dei precedenti per il personale con accesso ai dati dei clienti. Livello comune: estratto del casellario giudiziale o documento equivalente al momento dell'assunzione.",
      es: "Marque sí si realiza una verificación de antecedentes al personal con acceso a los datos de los clientes. Nivel habitual: certificado de antecedentes penales o documento equivalente en la contratación.",
      pl: "Zaznacz tak, jeśli przeprowadzasz weryfikację przeszłości personelu z dostępem do danych klientów. Typowy poziom: wyciąg z rejestru karnego lub równoważny dokument przy zatrudnieniu.",
      cs: "Zaškrtněte ano, pokud provádíte prověření zaměstnanců s přístupem k zákaznickým datům. Obvyklá úroveň: výpis z rejstříku trestů nebo rovnocenný dokument při nástupu.",
      pt: "Assinale sim se efetuar uma verificação de antecedentes do pessoal com acesso a dados de clientes. Nível comum: certificado de registo criminal ou documento equivalente na contratação.",
      ro: "Bifați da dacă efectuați o verificare a antecedentelor personalului cu acces la datele clienților. Nivel comun: cazier judiciar sau document echivalent la angajare.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(c)",
    required: true,
  },
  {
    id: "vulnerabilityHandling",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented vulnerability handling and patching process",
      de: "Dokumentierter Schwachstellen- und Patch-Management-Prozess",
      fr: "Processus documenté de gestion des vulnérabilités et de correctifs",
      it: "Processo documentato di gestione delle vulnerabilità e di patching",
      es: "Proceso documentado de gestión de vulnerabilidades y aplicación de parches",
      pl: "Udokumentowany proces obsługi podatności i instalowania poprawek",
      cs: "Dokumentovaný proces řešení zranitelností a instalace záplat",
      pt: "Processo documentado de tratamento de vulnerabilidades e aplicação de correções",
      ro: "Proces documentat de gestionare a vulnerabilităților și de aplicare a corecțiilor",
    },
    description: {
      en: "Tick yes if you have a written process for handling security vulnerabilities: detect, assess, prioritise, patch or mitigate. CVE monitoring and SLA-driven patching are the standard.",
      de: "Ja, wenn Sie einen schriftlichen Prozess für die Behandlung von Sicherheitslücken haben: erkennen, bewerten, priorisieren, patchen oder mitigieren. CVE-Monitoring und SLA-basiertes Patching gelten als Standard.",
      fr: "Cochez oui si vous disposez d'un processus écrit pour traiter les vulnérabilités de sécurité : détecter, évaluer, prioriser, corriger ou atténuer. La surveillance des CVE et l'application de correctifs pilotée par SLA sont la norme.",
      it: "Selezionare sì se si dispone di un processo scritto per la gestione delle vulnerabilità di sicurezza: rilevare, valutare, dare priorità, applicare patch o mitigare. Il monitoraggio delle CVE e il patching guidato da SLA sono lo standard.",
      es: "Marque sí si dispone de un proceso escrito para gestionar las vulnerabilidades de seguridad: detectar, evaluar, priorizar, parchear o mitigar. La supervisión de CVE y la aplicación de parches basada en SLA son el estándar.",
      pl: "Zaznacz tak, jeśli masz pisemny proces obsługi podatności bezpieczeństwa: wykrywanie, ocena, priorytetyzacja, instalowanie poprawek lub łagodzenie. Monitorowanie CVE i instalowanie poprawek w oparciu o SLA są standardem.",
      cs: "Zaškrtněte ano, pokud máte písemný proces pro řešení bezpečnostních zranitelností: detekce, vyhodnocení, stanovení priorit, záplatování nebo zmírnění. Monitorování CVE a záplatování řízené SLA jsou standardem.",
      pt: "Assinale sim se tiver um processo escrito para o tratamento de vulnerabilidades de segurança: detetar, avaliar, priorizar, corrigir ou mitigar. A monitorização de CVE e a aplicação de correções orientada por SLA são a norma.",
      ro: "Bifați da dacă aveți un proces scris pentru gestionarea vulnerabilităților de securitate: detectare, evaluare, prioritizare, aplicarea corecțiilor sau atenuare. Monitorizarea CVE și aplicarea corecțiilor pe baza SLA sunt standardul.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(f)",
    required: true,
  },
  {
    id: "acceptRightToAudit",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Accept customer right to audit (or provide audit reports)",
      de: "Akzeptanz des Auditrechts (oder Bereitstellung von Auditberichten)",
      fr: "Accepter le droit d'audit du client (ou fournir des rapports d'audit)",
      it: "Accettare il diritto di audit del cliente (o fornire relazioni di audit)",
      es: "Aceptar el derecho de auditoría del cliente (o proporcionar informes de auditoría)",
      pl: "Akceptacja prawa klienta do audytu (lub udostępnianie raportów z audytu)",
      cs: "Akceptace práva zákazníka na audit (nebo poskytnutí auditních zpráv)",
      pt: "Aceitar o direito de auditoria do cliente (ou fornecer relatórios de auditoria)",
      ro: "Acceptarea dreptului de audit al clientului (sau furnizarea de rapoarte de audit)",
    },
    description: {
      en: "Tick yes if you either grant customers an on-site audit right or provide substitute audit reports (for example SOC 2, ISAE 3402).",
      de: "Ja, wenn Sie Kunden entweder ein Auditrecht vor Ort einräumen oder ihnen stellvertretend Auditberichte (zum Beispiel SOC 2, ISAE 3402) zur Verfügung stellen.",
      fr: "Cochez oui si vous accordez aux clients soit un droit d'audit sur site, soit des rapports d'audit de substitution (par exemple SOC 2, ISAE 3402).",
      it: "Selezionare sì se si concede ai clienti un diritto di audit in loco oppure si forniscono relazioni di audit sostitutive (ad esempio SOC 2, ISAE 3402).",
      es: "Marque sí si concede a los clientes un derecho de auditoría in situ o les proporciona informes de auditoría sustitutivos (por ejemplo SOC 2, ISAE 3402).",
      pl: "Zaznacz tak, jeśli przyznajesz klientom prawo do audytu na miejscu albo udostępniasz zastępcze raporty z audytu (na przykład SOC 2, ISAE 3402).",
      cs: "Zaškrtněte ano, pokud zákazníkům buď udělujete právo na audit na místě, nebo poskytujete náhradní auditní zprávy (například SOC 2, ISAE 3402).",
      pt: "Assinale sim se conceder aos clientes um direito de auditoria no local ou fornecer relatórios de auditoria substitutos (por exemplo SOC 2, ISAE 3402).",
      ro: "Bifați da dacă fie acordați clienților un drept de audit la fața locului, fie furnizați rapoarte de audit substitutive (de exemplu SOC 2, ISAE 3402).",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(e)",
    required: true,
  },
  {
    id: "hasSubprocessors",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Use subprocessors / sub-suppliers",
      de: "Einsatz von Sub-Unternehmern / Sub-Lieferanten",
      fr: "Recours à des sous-traitants ultérieurs / sous-fournisseurs",
      it: "Ricorso a subincaricati / subfornitori",
      es: "Uso de subencargados / subproveedores",
      pl: "Korzystanie z podwykonawców przetwarzania / poddostawców",
      cs: "Využití dalších zpracovatelů / subdodavatelů",
      pt: "Utilização de subcontratantes / subfornecedores",
      ro: "Utilizarea de subîmputerniciți / subfurnizori",
    },
    description: {
      en: "Tick yes if you use other companies to deliver your service that have access to customer data or infrastructure. Typical examples: AWS, Azure, Cloudflare, Stripe.",
      de: "Ja, wenn Sie für die Leistungserbringung andere Unternehmen einsetzen, die Zugang zu Kundendaten oder Kunden-Infrastruktur haben. Typische Beispiele: AWS, Azure, Cloudflare, Stripe.",
      fr: "Cochez oui si vous recourez à d'autres entreprises pour fournir votre service et qu'elles ont accès aux données ou à l'infrastructure des clients. Exemples typiques : AWS, Azure, Cloudflare, Stripe.",
      it: "Selezionare sì se per erogare il servizio si ricorre ad altre aziende che hanno accesso ai dati o all'infrastruttura dei clienti. Esempi tipici: AWS, Azure, Cloudflare, Stripe.",
      es: "Marque sí si recurre a otras empresas para prestar su servicio que tienen acceso a los datos o la infraestructura de los clientes. Ejemplos típicos: AWS, Azure, Cloudflare, Stripe.",
      pl: "Zaznacz tak, jeśli do świadczenia usługi korzystasz z innych firm, które mają dostęp do danych lub infrastruktury klientów. Typowe przykłady: AWS, Azure, Cloudflare, Stripe.",
      cs: "Zaškrtněte ano, pokud k poskytování své služby využíváte jiné společnosti, které mají přístup k zákaznickým datům nebo infrastruktuře. Typické příklady: AWS, Azure, Cloudflare, Stripe.",
      pt: "Assinale sim se utilizar outras empresas para prestar o seu serviço que tenham acesso aos dados ou à infraestrutura dos clientes. Exemplos típicos: AWS, Azure, Cloudflare, Stripe.",
      ro: "Bifați da dacă, pentru a vă presta serviciul, utilizați alte societăți care au acces la datele sau la infrastructura clienților. Exemple tipice: AWS, Azure, Cloudflare, Stripe.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(g)",
    required: true,
  },
  {
    id: "subprocessorList",
    section: "security_practices",
    type: "text",
    label: {
      en: "List of subprocessors",
      de: "Liste der Sub-Unternehmer",
      fr: "Liste des sous-traitants ultérieurs",
      it: "Elenco dei subincaricati",
      es: "Lista de subencargados",
      pl: "Lista podwykonawców przetwarzania",
      cs: "Seznam dalších zpracovatelů",
      pt: "Lista de subcontratantes",
      ro: "Lista subîmputerniciților",
    },
    description: {
      en: "List every subprocessor with name, processing location, and what they do for you. A table or bullet list is enough. Update whenever you add or remove one.",
      de: "Liste aller Sub-Unternehmer mit Name, Verarbeitungsstandort und Aufgabe. Eine Tabelle oder Stichpunktliste genügt. Aktualisieren Sie diese, wenn Sie einen Sub-Unternehmer hinzufügen oder entfernen.",
      fr: "Listez chaque sous-traitant ultérieur avec son nom, son lieu de traitement et ce qu'il fait pour vous. Un tableau ou une liste à puces suffit. Mettez-la à jour à chaque ajout ou retrait.",
      it: "Elencare ogni subincaricato con nome, luogo di trattamento e attività svolta per voi. È sufficiente una tabella o un elenco puntato. Aggiornatela ogni volta che ne aggiungete o rimuovete uno.",
      es: "Enumere cada subencargado con su nombre, lugar de tratamiento y lo que hace por usted. Basta con una tabla o una lista de viñetas. Actualícela cada vez que añada o elimine uno.",
      pl: "Wymień każdego podwykonawcę przetwarzania z nazwą, miejscem przetwarzania i tym, co dla Ciebie robi. Wystarczy tabela lub lista punktowana. Aktualizuj ją za każdym razem, gdy dodajesz lub usuwasz podwykonawcę.",
      cs: "Uveďte každého dalšího zpracovatele s názvem, místem zpracování a tím, co pro vás dělá. Postačí tabulka nebo odrážkový seznam. Aktualizujte ji vždy, když nějakého přidáte nebo odeberete.",
      pt: "Enumere cada subcontratante com o nome, o local de tratamento e o que faz para si. Basta uma tabela ou uma lista de pontos. Atualize-a sempre que adicionar ou remover um.",
      ro: "Enumerați fiecare subîmputernicit cu numele, locul prelucrării și activitatea pe care o desfășoară pentru dumneavoastră. Este suficient un tabel sau o listă cu marcatori. Actualizați-o ori de câte ori adăugați sau eliminați unul.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(g)",
    required: false,
    visibleWhen: { field: "hasSubprocessors", equals: true },
  },
  {
    id: "dataReturnOnTermination",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Commit to return / destroy customer data on termination",
      de: "Verpflichtung zur Rückgabe / Vernichtung von Kundendaten bei Vertragsende",
      fr: "S'engager à restituer / détruire les données des clients à la résiliation",
      it: "Impegno a restituire / distruggere i dati dei clienti alla cessazione",
      es: "Comprometerse a devolver / destruir los datos del cliente al finalizar el contrato",
      pl: "Zobowiązanie do zwrotu / zniszczenia danych klientów po zakończeniu umowy",
      cs: "Závazek vrátit / zničit zákaznická data při ukončení smlouvy",
      pt: "Comprometer-se a devolver / destruir os dados do cliente na cessação",
      ro: "Angajamentul de a returna / distruge datele clientului la încetare",
    },
    description: {
      en: "Tick yes if you contractually commit to returning or destroying customer data at the end of the contract. Common practice: export and return, then delete within 30 days.",
      de: "Ja, wenn Sie sich vertraglich verpflichten, Kundendaten am Ende des Vertrags zurückzugeben oder zu vernichten. Üblich: Rückgabe als Export, dann Löschung innerhalb von 30 Tagen.",
      fr: "Cochez oui si vous vous engagez contractuellement à restituer ou détruire les données des clients à la fin du contrat. Pratique courante : export et restitution, puis suppression sous 30 jours.",
      it: "Selezionare sì se ci si impegna contrattualmente a restituire o distruggere i dati dei clienti al termine del contratto. Prassi comune: export e restituzione, quindi cancellazione entro 30 giorni.",
      es: "Marque sí si se compromete contractualmente a devolver o destruir los datos del cliente al finalizar el contrato. Práctica habitual: exportar y devolver, y luego eliminar en un plazo de 30 días.",
      pl: "Zaznacz tak, jeśli zobowiązujesz się umownie do zwrotu lub zniszczenia danych klientów po zakończeniu umowy. Powszechna praktyka: eksport i zwrot, a następnie usunięcie w ciągu 30 dni.",
      cs: "Zaškrtněte ano, pokud se smluvně zavazujete vrátit nebo zničit zákaznická data na konci smlouvy. Obvyklá praxe: export a vrácení, poté smazání do 30 dnů.",
      pt: "Assinale sim se se comprometer contratualmente a devolver ou destruir os dados do cliente no final do contrato. Prática comum: exportar e devolver e, depois, eliminar no prazo de 30 dias.",
      ro: "Bifați da dacă vă angajați contractual să returnați sau să distrugeți datele clientului la sfârșitul contractului. Practică comună: export și returnare, apoi ștergere în termen de 30 de zile.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(h)",
    required: true,
  },
  {
    id: "dpaAvailable",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Standard data processing agreement (DPA) available",
      de: "Standard-Auftragsverarbeitungsvertrag (AVV) verfügbar",
      fr: "Contrat type de traitement des données (DPA) disponible",
      it: "Accordo standard sul trattamento dei dati (DPA) disponibile",
      es: "Contrato estándar de tratamiento de datos (DPA) disponible",
      pl: "Dostępna standardowa umowa o przetwarzaniu danych (DPA)",
      cs: "Dostupná standardní smlouva o zpracování dat (DPA)",
      pt: "Contrato padrão de tratamento de dados (DPA) disponível",
      ro: "Acord standard de prelucrare a datelor (DPA) disponibil",
    },
    description: {
      en: "Tick yes if you have a standard data processing agreement under GDPR Article 28 that customers can sign. Required as soon as you process personal data.",
      de: "Ja, wenn Sie einen standardisierten Auftragsverarbeitungsvertrag nach Artikel 28 DSGVO haben, den Kunden unterschreiben können. Notwendig, sobald Sie personenbezogene Daten verarbeiten.",
      fr: "Cochez oui si vous disposez d'un contrat type de traitement des données au titre de l'article 28 du GDPR que les clients peuvent signer. Requis dès que vous traitez des données à caractère personnel.",
      it: "Selezionare sì se si dispone di un accordo standard sul trattamento dei dati ai sensi dell'articolo 28 del GDPR che i clienti possono firmare. Richiesto non appena si trattano dati personali.",
      es: "Marque sí si dispone de un contrato estándar de tratamiento de datos conforme al artículo 28 del GDPR que los clientes puedan firmar. Obligatorio en cuanto trate datos personales.",
      pl: "Zaznacz tak, jeśli masz standardową umowę o przetwarzaniu danych zgodnie z artykułem 28 GDPR, którą klienci mogą podpisać. Wymagane, gdy tylko przetwarzasz dane osobowe.",
      cs: "Zaškrtněte ano, pokud máte standardní smlouvu o zpracování dat podle článku 28 GDPR, kterou mohou zákazníci podepsat. Vyžadováno, jakmile zpracováváte osobní údaje.",
      pt: "Assinale sim se tiver um contrato padrão de tratamento de dados ao abrigo do artigo 28.º do GDPR que os clientes possam assinar. Obrigatório a partir do momento em que trata dados pessoais.",
      ro: "Bifați da dacă aveți un acord standard de prelucrare a datelor în temeiul articolului 28 din GDPR pe care clienții îl pot semna. Necesar de îndată ce prelucrați date cu caracter personal.",
    },
    legalBasis: "GDPR Art. 28",
    required: true,
  },
  {
    id: "securityPolicyReviewedAnnually",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Security policies reviewed at least annually",
      de: "Sicherheitsrichtlinien werden mindestens jährlich überprüft",
      fr: "Politiques de sécurité revues au moins une fois par an",
      it: "Politiche di sicurezza riviste almeno annualmente",
      es: "Las políticas de seguridad se revisan al menos una vez al año",
      pl: "Polityki bezpieczeństwa są przeglądane co najmniej raz w roku",
      cs: "Bezpečnostní politiky se přezkoumávají alespoň jednou ročně",
      pt: "As políticas de segurança são revistas pelo menos uma vez por ano",
      ro: "Politicile de securitate sunt revizuite cel puțin o dată pe an",
    },
    description: {
      en: "Tick yes if your security policies are reviewed at least once a year and updated as needed. A written note in the document is enough evidence.",
      de: "Ja, wenn Ihre Sicherheitsrichtlinien mindestens jährlich überprüft und bei Bedarf aktualisiert werden. Eine schriftliche Notiz im Dokument genügt als Nachweis.",
      fr: "Cochez oui si vos politiques de sécurité sont revues au moins une fois par an et mises à jour si nécessaire. Une note écrite dans le document suffit comme preuve.",
      it: "Selezionare sì se le vostre politiche di sicurezza vengono riviste almeno una volta all'anno e aggiornate secondo necessità. Una nota scritta nel documento è una prova sufficiente.",
      es: "Marque sí si sus políticas de seguridad se revisan al menos una vez al año y se actualizan según sea necesario. Una nota escrita en el documento basta como prueba.",
      pl: "Zaznacz tak, jeśli Twoje polityki bezpieczeństwa są przeglądane co najmniej raz w roku i aktualizowane w razie potrzeby. Pisemna notatka w dokumencie jest wystarczającym dowodem.",
      cs: "Zaškrtněte ano, pokud se vaše bezpečnostní politiky přezkoumávají alespoň jednou ročně a podle potřeby aktualizují. Písemná poznámka v dokumentu je dostatečným důkazem.",
      pt: "Assinale sim se as suas políticas de segurança forem revistas pelo menos uma vez por ano e atualizadas conforme necessário. Uma nota escrita no documento é prova suficiente.",
      ro: "Bifați da dacă politicile dumneavoastră de securitate sunt revizuite cel puțin o dată pe an și actualizate după caz. O notă scrisă în document este o dovadă suficientă.",
    },
    legalBasis: "NIS2 Art. 21(2)(a) / ENISA TIG §1.1",
    required: true,
  },
  {
    id: "hasIncidentResponsePlan",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented incident response plan",
      de: "Dokumentierter Notfall-/Incident-Response-Plan",
      fr: "Plan de réponse aux incidents documenté",
      it: "Piano di risposta agli incidenti documentato",
      es: "Plan de respuesta a incidentes documentado",
      pl: "Udokumentowany plan reagowania na incydenty",
      cs: "Dokumentovaný plán reakce na incidenty",
      pt: "Plano de resposta a incidentes documentado",
      ro: "Plan documentat de răspuns la incidente",
    },
    description: {
      en: "Tick yes if you have a written plan for handling security incidents: who decides, who communicates, who documents. At least one tabletop exercise per year is good practice.",
      de: "Ja, wenn Sie einen schriftlichen Plan für den Umgang mit Sicherheitsvorfällen haben: wer entscheidet, wer kommuniziert, wer dokumentiert. Mindestens eine Tabletop-Übung pro Jahr ist gute Praxis.",
      fr: "Cochez oui si vous disposez d'un plan écrit pour gérer les incidents de sécurité : qui décide, qui communique, qui documente. Au moins un exercice sur table par an est une bonne pratique.",
      it: "Selezionare sì se si dispone di un piano scritto per la gestione degli incidenti di sicurezza: chi decide, chi comunica, chi documenta. Almeno un'esercitazione tabletop all'anno è una buona prassi.",
      es: "Marque sí si dispone de un plan escrito para gestionar los incidentes de seguridad: quién decide, quién comunica, quién documenta. Al menos un ejercicio de simulación al año es una buena práctica.",
      pl: "Zaznacz tak, jeśli masz pisemny plan obsługi incydentów bezpieczeństwa: kto decyduje, kto komunikuje, kto dokumentuje. Co najmniej jedno ćwiczenie sztabowe rocznie to dobra praktyka.",
      cs: "Zaškrtněte ano, pokud máte písemný plán pro řešení bezpečnostních incidentů: kdo rozhoduje, kdo komunikuje, kdo dokumentuje. Alespoň jedno stolní cvičení ročně je dobrou praxí.",
      pt: "Assinale sim se tiver um plano escrito para o tratamento de incidentes de segurança: quem decide, quem comunica, quem documenta. Pelo menos um exercício de simulação por ano é boa prática.",
      ro: "Bifați da dacă aveți un plan scris pentru gestionarea incidentelor de securitate: cine decide, cine comunică, cine documentează. Cel puțin un exercițiu de simulare pe an este o bună practică.",
    },
    legalBasis: "NIS2 Art. 21(2)(b) / ENISA TIG §3",
    required: true,
  },
  {
    id: "hasBusinessContinuityPlan",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented business continuity / disaster recovery plan",
      de: "Dokumentierter Business-Continuity- / Disaster-Recovery-Plan",
      fr: "Plan de continuité d'activité / reprise après sinistre documenté",
      it: "Piano di continuità operativa / ripristino di emergenza documentato",
      es: "Plan de continuidad de negocio / recuperación ante desastres documentado",
      pl: "Udokumentowany plan ciągłości działania / odtwarzania po awarii",
      cs: "Dokumentovaný plán kontinuity činnosti / obnovy po havárii",
      pt: "Plano de continuidade de negócio / recuperação de desastres documentado",
      ro: "Plan documentat de continuitate a activității / recuperare în caz de dezastru",
    },
    description: {
      en: "Tick yes if you have a plan that explains how you keep running or recover quickly during an outage: critical systems, fallbacks, RTO and RPO targets.",
      de: "Ja, wenn Sie einen Plan haben, der erklärt, wie Sie den Betrieb bei einem Ausfall aufrechterhalten oder schnell wiederherstellen: kritische Systeme, Ersatzwege, RTO und RPO Ziele.",
      fr: "Cochez oui si vous disposez d'un plan expliquant comment vous maintenez l'activité ou récupérez rapidement lors d'une panne : systèmes critiques, solutions de repli, objectifs RTO et RPO.",
      it: "Selezionare sì se si dispone di un piano che spiega come mantenere l'operatività o ripristinare rapidamente durante un'interruzione: sistemi critici, soluzioni di ripiego, obiettivi RTO e RPO.",
      es: "Marque sí si dispone de un plan que explique cómo mantiene el funcionamiento o se recupera con rapidez durante una interrupción: sistemas críticos, alternativas, objetivos RTO y RPO.",
      pl: "Zaznacz tak, jeśli masz plan wyjaśniający, jak utrzymujesz działanie lub szybko przywracasz je podczas awarii: systemy krytyczne, rozwiązania awaryjne, cele RTO i RPO.",
      cs: "Zaškrtněte ano, pokud máte plán, který vysvětluje, jak udržíte provoz nebo se rychle zotavíte při výpadku: kritické systémy, záložní řešení, cíle RTO a RPO.",
      pt: "Assinale sim se tiver um plano que explique como mantém o funcionamento ou recupera rapidamente durante uma interrupção: sistemas críticos, soluções de recurso, objetivos RTO e RPO.",
      ro: "Bifați da dacă aveți un plan care explică modul în care vă mențineți funcționarea sau vă recuperați rapid în timpul unei întreruperi: sisteme critice, soluții de rezervă, obiective RTO și RPO.",
    },
    legalBasis: "NIS2 Art. 21(2)(c) / ENISA TIG §4",
    required: true,
  },
  {
    id: "hasCryptographyPolicy",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented cryptography policy",
      de: "Dokumentierte Kryptografie-Richtlinie",
      fr: "Politique de cryptographie documentée",
      it: "Politica di crittografia documentata",
      es: "Política de criptografía documentada",
      pl: "Udokumentowana polityka kryptografii",
      cs: "Dokumentovaná politika kryptografie",
      pt: "Política de criptografia documentada",
      ro: "Politică de criptografie documentată",
    },
    description: {
      en: "Tick yes if you have written down which cryptography you use where: data in transit (TLS 1.2+), data at rest (AES-256), key management, hashing algorithms.",
      de: "Ja, wenn Sie schriftlich festgelegt haben, welche Verschlüsselungsverfahren Sie wofür einsetzen: Daten im Transit (TLS 1.2+), Daten im Ruhezustand (AES-256), Schlüsselverwaltung, ausgewählte Hashing-Verfahren.",
      fr: "Cochez oui si vous avez consigné par écrit quelle cryptographie vous utilisez et où : données en transit (TLS 1.2+), données au repos (AES-256), gestion des clés, algorithmes de hachage.",
      it: "Selezionare sì se avete messo per iscritto quale crittografia utilizzate e dove: dati in transito (TLS 1.2+), dati a riposo (AES-256), gestione delle chiavi, algoritmi di hashing.",
      es: "Marque sí si ha documentado por escrito qué criptografía usa y dónde: datos en tránsito (TLS 1.2+), datos en reposo (AES-256), gestión de claves, algoritmos de hash.",
      pl: "Zaznacz tak, jeśli masz pisemnie określone, jaką kryptografię stosujesz i gdzie: dane w tranzycie (TLS 1.2+), dane w spoczynku (AES-256), zarządzanie kluczami, algorytmy haszujące.",
      cs: "Zaškrtněte ano, pokud máte písemně stanoveno, jakou kryptografii používáte a kde: data při přenosu (TLS 1.2+), data v klidu (AES-256), správa klíčů, hashovací algoritmy.",
      pt: "Assinale sim se tiver registado por escrito que criptografia utiliza e onde: dados em trânsito (TLS 1.2+), dados em repouso (AES-256), gestão de chaves, algoritmos de hash.",
      ro: "Bifați da dacă ați consemnat în scris ce criptografie utilizați și unde: date în tranzit (TLS 1.2+), date în repaus (AES-256), gestionarea cheilor, algoritmi de hash.",
    },
    legalBasis: "NIS2 Art. 21(2)(h) / ENISA TIG §9",
    required: true,
  },
  {
    id: "hasPrivilegedAccessMgmt",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Privileged access management (PAM) for internal staff",
      de: "Privileged Access Management (PAM) für interne Mitarbeitende",
      fr: "Gestion des accès à privilèges (PAM) pour le personnel interne",
      it: "Gestione degli accessi privilegiati (PAM) per il personale interno",
      es: "Gestión de accesos privilegiados (PAM) para el personal interno",
      pl: "Zarządzanie dostępem uprzywilejowanym (PAM) dla personelu wewnętrznego",
      cs: "Správa privilegovaného přístupu (PAM) pro interní zaměstnance",
      pt: "Gestão de acessos privilegiados (PAM) para o pessoal interno",
      ro: "Gestionarea accesului privilegiat (PAM) pentru personalul intern",
    },
    description: {
      en: "Tick yes if administrators and privileged accounts get extra controls: separate sign-in, MFA, session logging, or just-in-time access.",
      de: "Ja, wenn Administratoren und privilegierte Konten besondere Kontrollen haben: separater Login, MFA, Sitzungsprotokollierung oder zeitlich befristete Berechtigung.",
      fr: "Cochez oui si les administrateurs et les comptes à privilèges bénéficient de contrôles supplémentaires : connexion distincte, MFA, journalisation des sessions ou accès juste-à-temps.",
      it: "Selezionare sì se gli amministratori e gli account privilegiati dispongono di controlli aggiuntivi: accesso separato, MFA, registrazione delle sessioni o accesso just-in-time.",
      es: "Marque sí si los administradores y las cuentas privilegiadas cuentan con controles adicionales: inicio de sesión separado, MFA, registro de sesiones o acceso just-in-time.",
      pl: "Zaznacz tak, jeśli administratorzy i konta uprzywilejowane mają dodatkowe mechanizmy kontroli: osobne logowanie, MFA, rejestrowanie sesji lub dostęp just-in-time.",
      cs: "Zaškrtněte ano, pokud administrátoři a privilegované účty mají dodatečné kontroly: oddělené přihlášení, MFA, protokolování relací nebo přístup just-in-time.",
      pt: "Assinale sim se os administradores e as contas privilegiadas dispuserem de controlos adicionais: início de sessão separado, MFA, registo de sessões ou acesso just-in-time.",
      ro: "Bifați da dacă administratorii și conturile privilegiate beneficiază de controale suplimentare: autentificare separată, MFA, jurnalizarea sesiunilor sau acces just-in-time.",
    },
    legalBasis: "NIS2 Art. 21(2)(i) / ENISA TIG §11.3",
    required: true,
  },
  {
    id: "mfaEnforcedInternal",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "MFA enforced for all internal admin / privileged accounts",
      de: "MFA für alle internen Admin- / privilegierten Konten erzwungen",
      fr: "MFA imposé pour tous les comptes d'administration / à privilèges internes",
      it: "MFA imposto per tutti gli account amministrativi / privilegiati interni",
      es: "MFA obligatorio para todas las cuentas internas de administración / privilegiadas",
      pl: "MFA wymuszone dla wszystkich wewnętrznych kont administracyjnych / uprzywilejowanych",
      cs: "MFA vynuceno pro všechny interní administrátorské / privilegované účty",
      pt: "MFA imposto para todas as contas internas de administração / privilegiadas",
      ro: "MFA impus pentru toate conturile interne de administrare / privilegiate",
    },
    description: {
      en: "Tick yes if every internal admin or privileged account must use MFA. Hardware tokens or authenticator apps count; SMS does not.",
      de: "Ja, wenn alle internen Administrator-Konten oder Konten mit erhöhten Rechten MFA erzwingen müssen. Hardware-Tokens oder Authenticator-Apps zählen, SMS ist nicht ausreichend.",
      fr: "Cochez oui si chaque compte d'administration ou à privilèges interne doit utiliser le MFA. Les jetons matériels ou les applications d'authentification comptent ; le SMS ne compte pas.",
      it: "Selezionare sì se ogni account amministrativo o privilegiato interno deve utilizzare l'MFA. I token hardware o le app di autenticazione sono validi; gli SMS no.",
      es: "Marque sí si cada cuenta interna de administración o privilegiada debe usar MFA. Los tokens de hardware o las aplicaciones de autenticación cuentan; los SMS no.",
      pl: "Zaznacz tak, jeśli każde wewnętrzne konto administracyjne lub uprzywilejowane musi używać MFA. Tokeny sprzętowe lub aplikacje uwierzytelniające się liczą; SMS nie.",
      cs: "Zaškrtněte ano, pokud každý interní administrátorský nebo privilegovaný účet musí používat MFA. Hardwarové tokeny nebo autentizační aplikace se počítají, SMS nikoli.",
      pt: "Assinale sim se cada conta interna de administração ou privilegiada tiver de usar MFA. Os tokens de hardware ou as aplicações de autenticação contam, o SMS não.",
      ro: "Bifați da dacă fiecare cont intern de administrare sau privilegiat trebuie să utilizeze MFA. Tokenurile hardware sau aplicațiile de autentificare contează, SMS-ul nu.",
    },
    legalBasis: "NIS2 Art. 21(2)(j)",
    required: true,
  },
  {
    id: "hasAssetInventory",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Maintain an inventory of information assets",
      de: "Asset-Inventar wird gepflegt",
      fr: "Tenir un inventaire des actifs d'information",
      it: "Mantenere un inventario degli asset informativi",
      es: "Mantener un inventario de activos de información",
      pl: "Prowadzenie inwentaryzacji zasobów informacyjnych",
      cs: "Vedení inventáře informačních aktiv",
      pt: "Manter um inventário de ativos de informação",
      ro: "Menținerea unui inventar al activelor informaționale",
    },
    description: {
      en: "Tick yes if you keep a current list of every information system you use to deliver your service: servers, databases, SaaS tools, endpoints. A spreadsheet is enough.",
      de: "Ja, wenn Sie eine aktuelle Liste aller Informationssysteme führen, die Sie für die Leistungserbringung einsetzen: Server, Datenbanken, SaaS-Werkzeuge, Endgeräte. Eine Tabelle genügt.",
      fr: "Cochez oui si vous tenez une liste à jour de chaque système d'information que vous utilisez pour fournir votre service : serveurs, bases de données, outils SaaS, terminaux. Un tableur suffit.",
      it: "Selezionare sì se si mantiene un elenco aggiornato di ogni sistema informativo utilizzato per erogare il servizio: server, database, strumenti SaaS, endpoint. È sufficiente un foglio di calcolo.",
      es: "Marque sí si mantiene una lista actualizada de cada sistema de información que utiliza para prestar su servicio: servidores, bases de datos, herramientas SaaS, endpoints. Basta con una hoja de cálculo.",
      pl: "Zaznacz tak, jeśli prowadzisz aktualną listę każdego systemu informacyjnego używanego do świadczenia usługi: serwery, bazy danych, narzędzia SaaS, punkty końcowe. Wystarczy arkusz kalkulacyjny.",
      cs: "Zaškrtněte ano, pokud vedete aktuální seznam každého informačního systému, který používáte k poskytování své služby: servery, databáze, nástroje SaaS, koncové body. Postačí tabulka.",
      pt: "Assinale sim se mantiver uma lista atual de cada sistema de informação que utiliza para prestar o seu serviço: servidores, bases de dados, ferramentas SaaS, terminais. Basta uma folha de cálculo.",
      ro: "Bifați da dacă mențineți o listă actualizată a fiecărui sistem informatic pe care îl utilizați pentru a vă presta serviciul: servere, baze de date, instrumente SaaS, puncte finale. Este suficient un tabel de calcul.",
    },
    legalBasis: "NIS2 Art. 21(2)(i) / ENISA TIG §12.4",
    required: true,
  },
  {
    id: "hasPenetrationTestingProgram",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Annual or biennial penetration testing program",
      de: "Jährliches oder zweijährliches Penetrationstest-Programm",
      fr: "Programme de tests d'intrusion annuel ou biennal",
      it: "Programma di penetration test annuale o biennale",
      es: "Programa de pruebas de penetración anual o bienal",
      pl: "Program testów penetracyjnych co rok lub co dwa lata",
      cs: "Program penetračního testování každý rok nebo každé dva roky",
      pt: "Programa de testes de penetração anual ou bienal",
      ro: "Program de testare a penetrării anual sau bienal",
    },
    description: {
      en: "Tick yes if you commission an external penetration test at least every one to two years. For smaller companies, an external vulnerability scan as a minimum step is acceptable.",
      de: "Ja, wenn Sie mindestens alle ein bis zwei Jahre einen externen Penetrationstest beauftragen. Bei kleineren Unternehmen ist eine externe Schwachstellenanalyse als Mindestschritt akzeptabel.",
      fr: "Cochez oui si vous commandez un test d'intrusion externe au moins tous les un à deux ans. Pour les petites entreprises, un scan de vulnérabilités externe comme étape minimale est acceptable.",
      it: "Selezionare sì se si commissiona un penetration test esterno almeno ogni uno o due anni. Per le aziende più piccole, una scansione esterna delle vulnerabilità come passo minimo è accettabile.",
      es: "Marque sí si encarga una prueba de penetración externa al menos cada uno o dos años. Para las empresas más pequeñas, un escaneo de vulnerabilidades externo como paso mínimo es aceptable.",
      pl: "Zaznacz tak, jeśli zlecasz zewnętrzny test penetracyjny co najmniej raz na jeden do dwóch lat. W przypadku mniejszych firm akceptowalnym minimalnym krokiem jest zewnętrzne skanowanie podatności.",
      cs: "Zaškrtněte ano, pokud si necháváte provést externí penetrační test alespoň jednou za jeden až dva roky. U menších společností je jako minimální krok přijatelné externí skenování zranitelností.",
      pt: "Assinale sim se encomendar um teste de penetração externo pelo menos uma vez de um a dois anos. Para empresas mais pequenas, uma análise externa de vulnerabilidades como passo mínimo é aceitável.",
      ro: "Bifați da dacă comandați un test de penetrare extern cel puțin o dată la unu sau doi ani. Pentru societățile mai mici, o scanare externă a vulnerabilităților ca pas minim este acceptabilă.",
    },
    legalBasis: "NIS2 Art. 21(2)(e) / ENISA TIG §6.5",
    required: true,
  },
  {
    id: "pastBreachesDisclosed",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "We disclose past notifiable cybersecurity events when asked by customers",
      de: "Wir legen frühere meldepflichtige Sicherheitsvorfälle auf Anfrage offen",
      fr: "Nous divulguons les événements de cybersécurité notifiables passés à la demande des clients",
      it: "Divulghiamo gli eventi di cibersicurezza notificabili passati su richiesta dei clienti",
      es: "Divulgamos los eventos de ciberseguridad notificables pasados cuando los clientes lo solicitan",
      pl: "Ujawniamy przeszłe podlegające zgłoszeniu zdarzenia cyberbezpieczeństwa na prośbę klientów",
      cs: "Na žádost zákazníků zveřejňujeme minulé ohlašovací povinnosti podléhající události kybernetické bezpečnosti",
      pt: "Divulgamos eventos de cibersegurança notificáveis ocorridos no passado quando solicitado pelos clientes",
      ro: "Divulgăm evenimentele de securitate cibernetică notificabile din trecut la cererea clienților",
    },
    description: {
      en: "Tick yes if, on customer request, you openly disclose whether and which reportable security incidents your company had in the past. Common window: the last three to five years.",
      de: "Ja, wenn Sie auf Kundenanfrage offen kommunizieren, ob und welche meldepflichtigen Sicherheitsvorfälle Ihr Unternehmen in der Vergangenheit hatte. Übliche Schwelle: die letzten drei bis fünf Jahre.",
      fr: "Cochez oui si, à la demande du client, vous divulguez ouvertement si et quels incidents de sécurité à signaler votre entreprise a connus par le passé. Fenêtre courante : les trois à cinq dernières années.",
      it: "Selezionare sì se, su richiesta del cliente, divulgate apertamente se e quali incidenti di sicurezza notificabili la vostra azienda ha avuto in passato. Finestra comune: gli ultimi tre-cinque anni.",
      es: "Marque sí si, a petición del cliente, divulga abiertamente si su empresa tuvo en el pasado incidentes de seguridad notificables y cuáles. Ventana habitual: los últimos tres a cinco años.",
      pl: "Zaznacz tak, jeśli na prośbę klienta otwarcie ujawniasz, czy i jakie podlegające zgłoszeniu incydenty bezpieczeństwa Twoja firma miała w przeszłości. Typowy okres: ostatnie od trzech do pięciu lat.",
      cs: "Zaškrtněte ano, pokud na žádost zákazníka otevřeně sdělíte, zda a jaké ohlašovací povinnosti podléhající bezpečnostní incidenty vaše společnost v minulosti měla. Obvyklé okno: poslední tři až pět let.",
      pt: "Assinale sim se, a pedido do cliente, divulgar abertamente se e que incidentes de segurança notificáveis a sua empresa teve no passado. Janela comum: os últimos três a cinco anos.",
      ro: "Bifați da dacă, la cererea clientului, divulgați deschis dacă și ce incidente de securitate notificabile a avut societatea dumneavoastră în trecut. Interval comun: ultimii trei până la cinci ani.",
    },
    legalBasis: "ENISA TIG §5.1.2",
    required: true,
  },
  {
    id: "incidentAssistanceCommitment",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Provide incident assistance to customers at no / ex-ante cost",
      de: "Wir unterstützen Kunden im Vorfall ohne / zu vorab definierten Kosten",
      fr: "Fournir une assistance aux clients en cas d'incident sans frais / à coût défini à l'avance",
      it: "Fornire assistenza ai clienti in caso di incidente senza costi / a costo predefinito",
      es: "Prestar asistencia a los clientes en caso de incidente sin coste / a coste predefinido",
      pl: "Zapewniamy klientom pomoc w razie incydentu bez kosztów / po kosztach ustalonych z góry",
      cs: "Poskytujeme zákazníkům pomoc při incidentu bez nákladů / za předem stanovené náklady",
      pt: "Prestar assistência aos clientes em caso de incidente sem custos / a custo definido à partida",
      ro: "Furnizăm clienților asistență în caz de incident fără costuri / la cost stabilit în prealabil",
    },
    description: {
      en: "Tick yes if you commit to helping customers at no extra cost when an incident is caused by your product or service. If you agree a pre-defined day rate up front instead, also tick yes.",
      de: "Ja, wenn Sie sich verpflichten, Kunden bei einem durch Ihr Produkt oder Ihre Dienstleistung verursachten Vorfall ohne zusätzliche Kosten zu unterstützen. Wenn Sie stattdessen einen vorab definierten Tagessatz vereinbaren, wählen Sie auch Ja.",
      fr: "Cochez oui si vous vous engagez à aider les clients sans frais supplémentaires lorsqu'un incident est causé par votre produit ou service. Si vous convenez plutôt d'un tarif journalier défini à l'avance, cochez également oui.",
      it: "Selezionare sì se ci si impegna ad assistere i clienti senza costi aggiuntivi quando un incidente è causato dal proprio prodotto o servizio. Se invece si concorda in anticipo una tariffa giornaliera predefinita, selezionare comunque sì.",
      es: "Marque sí si se compromete a ayudar a los clientes sin coste adicional cuando un incidente es causado por su producto o servicio. Si en su lugar acuerda de antemano una tarifa diaria predefinida, marque también sí.",
      pl: "Zaznacz tak, jeśli zobowiązujesz się pomagać klientom bez dodatkowych kosztów, gdy incydent jest spowodowany przez Twój produkt lub usługę. Jeśli zamiast tego z góry uzgadniasz wcześniej zdefiniowaną stawkę dzienną, również zaznacz tak.",
      cs: "Zaškrtněte ano, pokud se zavazujete pomáhat zákazníkům bez dodatečných nákladů, když je incident způsoben vaším produktem nebo službou. Pokud místo toho předem sjednáte stanovenou denní sazbu, zaškrtněte rovněž ano.",
      pt: "Assinale sim se se comprometer a ajudar os clientes sem custos adicionais quando um incidente for causado pelo seu produto ou serviço. Se, em alternativa, acordar à partida uma tarifa diária predefinida, assinale também sim.",
      ro: "Bifați da dacă vă angajați să ajutați clienții fără costuri suplimentare atunci când un incident este cauzat de produsul sau serviciul dumneavoastră. Dacă în schimb conveniți în prealabil o tarifă zilnică predefinită, bifați de asemenea da.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "cooperateWithAuthorities",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Fully cooperate with competent authorities (BSI, ENISA, national CSIRTs)",
      de: "Vollständige Kooperation mit zuständigen Behörden (BSI, ENISA, nationale CSIRTs)",
      fr: "Coopérer pleinement avec les autorités compétentes (BSI, ENISA, CSIRT nationaux)",
      it: "Cooperare pienamente con le autorità competenti (BSI, ENISA, CSIRT nazionali)",
      es: "Cooperar plenamente con las autoridades competentes (BSI, ENISA, CSIRT nacionales)",
      pl: "Pełna współpraca z właściwymi organami (BSI, ENISA, krajowe CSIRT)",
      cs: "Plná spolupráce s příslušnými orgány (BSI, ENISA, národní CSIRT)",
      pt: "Cooperar plenamente com as autoridades competentes (BSI, ENISA, CSIRT nacionais)",
      ro: "Cooperarea deplină cu autoritățile competente (BSI, ENISA, CSIRT naționale)",
    },
    description: {
      en: "Tick yes if you commit to fully cooperating with competent authorities like BSI, ENISA, or national CSIRTs during inspections, audits, and incident handling. Standard for serious suppliers.",
      de: "Ja, wenn Sie sich verpflichten, mit zuständigen Behörden wie BSI, ENISA oder nationalen CSIRTs bei Inspektionen, Audits und Vorfallbearbeitung vollständig zu kooperieren. Standard für seriöse Lieferanten.",
      fr: "Cochez oui si vous vous engagez à coopérer pleinement avec les autorités compétentes telles que le BSI, l'ENISA ou les CSIRT nationaux lors des inspections, des audits et du traitement des incidents. Standard pour les fournisseurs sérieux.",
      it: "Selezionare sì se ci si impegna a cooperare pienamente con le autorità competenti come BSI, ENISA o i CSIRT nazionali durante le ispezioni, gli audit e la gestione degli incidenti. Standard per i fornitori seri.",
      es: "Marque sí si se compromete a cooperar plenamente con las autoridades competentes como el BSI, la ENISA o los CSIRT nacionales durante las inspecciones, las auditorías y la gestión de incidentes. Estándar para los proveedores serios.",
      pl: "Zaznacz tak, jeśli zobowiązujesz się do pełnej współpracy z właściwymi organami, takimi jak BSI, ENISA lub krajowe CSIRT, podczas inspekcji, audytów i obsługi incydentów. Standard dla poważnych dostawców.",
      cs: "Zaškrtněte ano, pokud se zavazujete plně spolupracovat s příslušnými orgány, jako jsou BSI, ENISA nebo národní CSIRT, při inspekcích, auditech a řešení incidentů. Standard pro seriózní dodavatele.",
      pt: "Assinale sim se se comprometer a cooperar plenamente com as autoridades competentes, como o BSI, a ENISA ou os CSIRT nacionais, durante inspeções, auditorias e tratamento de incidentes. Padrão para fornecedores sérios.",
      ro: "Bifați da dacă vă angajați să cooperați pe deplin cu autoritățile competente, precum BSI, ENISA sau CSIRT-urile naționale, în timpul inspecțiilor, auditurilor și gestionării incidentelor. Standard pentru furnizorii serioși.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "notifyMaterialChanges",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Notify customers of any material change affecting service delivery",
      de: "Wir benachrichtigen Kunden über jede wesentliche Änderung der Leistungserbringung",
      fr: "Informer les clients de tout changement important affectant la prestation du service",
      it: "Notificare ai clienti qualsiasi modifica sostanziale che incida sull'erogazione del servizio",
      es: "Notificar a los clientes cualquier cambio sustancial que afecte a la prestación del servicio",
      pl: "Powiadamiamy klientów o każdej istotnej zmianie wpływającej na świadczenie usługi",
      cs: "Informujeme zákazníky o každé podstatné změně ovlivňující poskytování služby",
      pt: "Notificar os clientes de qualquer alteração substancial que afete a prestação do serviço",
      ro: "Notificarea clienților cu privire la orice modificare substanțială care afectează prestarea serviciului",
    },
    description: {
      en: "Tick yes if you commit to notifying customers of any material change affecting your ability to deliver: acquisitions, subprocessor changes, major technical shifts.",
      de: "Ja, wenn Sie sich verpflichten, Kunden über jede wesentliche Veränderung zu informieren, die Ihre Fähigkeit zur Leistungserbringung beeinflusst: Übernahmen, Wechsel des Sub-Unternehmers, größere technische Umstellungen.",
      fr: "Cochez oui si vous vous engagez à informer les clients de tout changement important affectant votre capacité à fournir le service : acquisitions, changements de sous-traitant ultérieur, évolutions techniques majeures.",
      it: "Selezionare sì se ci si impegna a notificare ai clienti qualsiasi modifica sostanziale che incida sulla capacità di erogare il servizio: acquisizioni, cambi di subincaricato, importanti cambiamenti tecnici.",
      es: "Marque sí si se compromete a notificar a los clientes cualquier cambio sustancial que afecte a su capacidad de prestar el servicio: adquisiciones, cambios de subencargado, cambios técnicos importantes.",
      pl: "Zaznacz tak, jeśli zobowiązujesz się powiadamiać klientów o każdej istotnej zmianie wpływającej na Twoją zdolność do świadczenia usługi: przejęcia, zmiany podwykonawcy przetwarzania, poważne zmiany techniczne.",
      cs: "Zaškrtněte ano, pokud se zavazujete informovat zákazníky o každé podstatné změně ovlivňující vaši schopnost poskytovat službu: akvizice, změny dalšího zpracovatele, zásadní technické změny.",
      pt: "Assinale sim se se comprometer a notificar os clientes de qualquer alteração substancial que afete a sua capacidade de prestar o serviço: aquisições, mudanças de subcontratante, alterações técnicas importantes.",
      ro: "Bifați da dacă vă angajați să notificați clienții cu privire la orice modificare substanțială care afectează capacitatea dumneavoastră de a presta serviciul: achiziții, schimbări de subîmputernicit, modificări tehnice majore.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "notifyOnLocationChange",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Notify customers in advance if data-processing locations change",
      de: "Wir benachrichtigen Kunden im Voraus, wenn sich Verarbeitungsstandorte ändern",
      fr: "Informer les clients à l'avance en cas de changement des lieux de traitement des données",
      it: "Notificare ai clienti in anticipo in caso di cambiamento dei luoghi di trattamento dei dati",
      es: "Notificar a los clientes con antelación si cambian los lugares de tratamiento de datos",
      pl: "Powiadamiamy klientów z wyprzedzeniem, jeśli zmieniają się miejsca przetwarzania danych",
      cs: "Informujeme zákazníky předem, pokud se mění místa zpracování dat",
      pt: "Notificar os clientes com antecedência se os locais de tratamento de dados mudarem",
      ro: "Notificarea clienților în avans dacă se schimbă locurile de prelucrare a datelor",
    },
    description: {
      en: "Tick yes if you notify customers in advance before the processing location of their data changes. Important for data protection and for GDPR-compliant supply chain oversight.",
      de: "Ja, wenn Sie Kunden im Voraus informieren, bevor sich der Verarbeitungsstandort ihrer Daten ändert. Wichtig für Datenschutz und für DSGVO-konforme Lieferkettenkontrolle.",
      fr: "Cochez oui si vous informez les clients à l'avance avant que le lieu de traitement de leurs données ne change. Important pour la protection des données et pour une supervision de la chaîne d'approvisionnement conforme au GDPR.",
      it: "Selezionare sì se si informano i clienti in anticipo prima che cambi il luogo di trattamento dei loro dati. Importante per la protezione dei dati e per una supervisione della catena di approvvigionamento conforme al GDPR.",
      es: "Marque sí si informa a los clientes con antelación antes de que cambie el lugar de tratamiento de sus datos. Importante para la protección de datos y para una supervisión de la cadena de suministro conforme al GDPR.",
      pl: "Zaznacz tak, jeśli informujesz klientów z wyprzedzeniem, zanim zmieni się miejsce przetwarzania ich danych. Ważne dla ochrony danych i dla zgodnego z GDPR nadzoru nad łańcuchem dostaw.",
      cs: "Zaškrtněte ano, pokud zákazníky informujete předem, než se změní místo zpracování jejich dat. Důležité pro ochranu dat a pro dohled nad dodavatelským řetězcem v souladu s GDPR.",
      pt: "Assinale sim se notificar os clientes com antecedência antes de o local de tratamento dos seus dados mudar. Importante para a proteção de dados e para uma supervisão da cadeia de fornecimento em conformidade com o GDPR.",
      ro: "Bifați da dacă notificați clienții în avans înainte ca locul de prelucrare a datelor lor să se schimbe. Important pentru protecția datelor și pentru o supraveghere a lanțului de aprovizionare conformă cu GDPR.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "hasExitPlan",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented exit strategy with mandatory transition period",
      de: "Dokumentierte Exit-Strategie mit verpflichtender Übergangszeit",
      fr: "Stratégie de sortie documentée avec période de transition obligatoire",
      it: "Strategia di uscita documentata con periodo di transizione obbligatorio",
      es: "Estrategia de salida documentada con periodo de transición obligatorio",
      pl: "Udokumentowana strategia wyjścia z obowiązkowym okresem przejściowym",
      cs: "Dokumentovaná strategie ukončení s povinným přechodným obdobím",
      pt: "Estratégia de saída documentada com período de transição obrigatório",
      ro: "Strategie de ieșire documentată cu perioadă de tranziție obligatorie",
    },
    description: {
      en: "Tick yes if you have a written exit strategy: how long an orderly handover takes, what data and knowledge gets transferred, what you commit to during the transition.",
      de: "Ja, wenn Sie eine schriftliche Exit-Strategie haben: Wie lange dauert der geordnete Übergang, welche Daten und welches Wissen werden übergeben, welche Mitwirkungspflichten gelten in dieser Phase.",
      fr: "Cochez oui si vous disposez d'une stratégie de sortie écrite : combien de temps dure une passation ordonnée, quelles données et connaissances sont transférées, à quoi vous vous engagez pendant la transition.",
      it: "Selezionare sì se si dispone di una strategia di uscita scritta: quanto dura un passaggio di consegne ordinato, quali dati e conoscenze vengono trasferiti, a cosa ci si impegna durante la transizione.",
      es: "Marque sí si dispone de una estrategia de salida escrita: cuánto dura un traspaso ordenado, qué datos y conocimientos se transfieren, a qué se compromete durante la transición.",
      pl: "Zaznacz tak, jeśli masz pisemną strategię wyjścia: jak długo trwa uporządkowane przekazanie, jakie dane i wiedza są przekazywane, do czego się zobowiązujesz w okresie przejściowym.",
      cs: "Zaškrtněte ano, pokud máte písemnou strategii ukončení: jak dlouho trvá řádné předání, jaká data a znalosti se předávají, k čemu se v průběhu přechodu zavazujete.",
      pt: "Assinale sim se tiver uma estratégia de saída escrita: quanto tempo demora uma transferência ordenada, que dados e conhecimentos são transferidos, a que se compromete durante a transição.",
      ro: "Bifați da dacă aveți o strategie de ieșire scrisă: cât durează o predare ordonată, ce date și cunoștințe se transferă, la ce vă angajați în timpul tranziției.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "providesSbomForAi",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Provide an SBOM-for-AI per G7 minimum elements",
      de: "Wir stellen ein SBOM-for-AI nach G7-Mindestelementen bereit",
      fr: "Fournir un SBOM-for-AI selon les éléments minimaux du G7",
      it: "Fornire un SBOM-for-AI secondo gli elementi minimi del G7",
      es: "Proporcionar un SBOM-for-AI según los elementos mínimos del G7",
      pl: "Dostarczamy SBOM-for-AI zgodnie z minimalnymi elementami G7",
      cs: "Poskytujeme SBOM-for-AI podle minimálních prvků G7",
      pt: "Fornecer um SBOM-for-AI segundo os elementos mínimos do G7",
      ro: "Furnizarea unui SBOM-for-AI conform elementelor minime G7",
    },
    description: {
      en: "Optional. Tick yes if you can provide an SBOM-for-AI per the G7 minimum elements (May 2026). Documents metadata, models, training data, infrastructure, security properties, KPIs, and system behaviour. Voluntary standard.",
      de: "Optional. Ja, wenn Sie eine SBOM-for-AI nach den G7-Mindestelementen (Mai 2026) bereitstellen können. Dokumentiert Metadaten, Modelle, Trainingsdaten, Infrastruktur, Sicherheitsmerkmale, KPIs und Systemverhalten. Freiwilliger Standard.",
      fr: "Facultatif. Cochez oui si vous pouvez fournir un SBOM-for-AI selon les éléments minimaux du G7 (mai 2026). Documente les métadonnées, les modèles, les données d'entraînement, l'infrastructure, les propriétés de sécurité, les KPI et le comportement du système. Standard volontaire.",
      it: "Facoltativo. Selezionare sì se è possibile fornire un SBOM-for-AI secondo gli elementi minimi del G7 (maggio 2026). Documenta metadati, modelli, dati di addestramento, infrastruttura, proprietà di sicurezza, KPI e comportamento del sistema. Standard volontario.",
      es: "Opcional. Marque sí si puede proporcionar un SBOM-for-AI según los elementos mínimos del G7 (mayo de 2026). Documenta metadatos, modelos, datos de entrenamiento, infraestructura, propiedades de seguridad, KPI y comportamiento del sistema. Estándar voluntario.",
      pl: "Opcjonalne. Zaznacz tak, jeśli możesz dostarczyć SBOM-for-AI zgodnie z minimalnymi elementami G7 (maj 2026). Dokumentuje metadane, modele, dane treningowe, infrastrukturę, właściwości bezpieczeństwa, KPI i zachowanie systemu. Standard dobrowolny.",
      cs: "Volitelné. Zaškrtněte ano, pokud dokážete poskytnout SBOM-for-AI podle minimálních prvků G7 (květen 2026). Dokumentuje metadata, modely, trénovací data, infrastrukturu, bezpečnostní vlastnosti, KPI a chování systému. Dobrovolný standard.",
      pt: "Opcional. Assinale sim se conseguir fornecer um SBOM-for-AI segundo os elementos mínimos do G7 (maio de 2026). Documenta metadados, modelos, dados de treino, infraestrutura, propriedades de segurança, KPI e comportamento do sistema. Norma voluntária.",
      ro: "Opțional. Bifați da dacă puteți furniza un SBOM-for-AI conform elementelor minime G7 (mai 2026). Documentează metadate, modele, date de antrenament, infrastructură, proprietăți de securitate, KPI și comportamentul sistemului. Standard voluntar.",
    },
    legalBasis: "NIS2 Art. 21(2)(d) / ENISA TIG §5.1.2",
    required: false,
    visibleWhen: { field: "usesAiSystems", equals: true },
  },
  {
    id: "aiSbomUrl",
    section: "security_practices",
    type: "url",
    label: {
      en: "SBOM-for-AI document URL",
      de: "URL des SBOM-for-AI-Dokuments",
      fr: "URL du document SBOM-for-AI",
      it: "URL del documento SBOM-for-AI",
      es: "URL del documento SBOM-for-AI",
      pl: "URL dokumentu SBOM-for-AI",
      cs: "URL dokumentu SBOM-for-AI",
      pt: "URL do documento SBOM-for-AI",
      ro: "URL-ul documentului SBOM-for-AI",
    },
    description: {
      en: "Public or shared URL to your SBOM-for-AI document. Can be a PDF, a JSON file, or a project page.",
      de: "Öffentliche oder geteilte URL zu Ihrem SBOM-for-AI-Dokument. Kann ein PDF, eine JSON-Datei oder eine Projektseite sein.",
      fr: "URL publique ou partagée vers votre document SBOM-for-AI. Peut être un PDF, un fichier JSON ou une page de projet.",
      it: "URL pubblico o condiviso del vostro documento SBOM-for-AI. Può essere un PDF, un file JSON o una pagina di progetto.",
      es: "URL pública o compartida de su documento SBOM-for-AI. Puede ser un PDF, un archivo JSON o una página de proyecto.",
      pl: "Publiczny lub udostępniony URL do Twojego dokumentu SBOM-for-AI. Może to być plik PDF, plik JSON lub strona projektu.",
      cs: "Veřejná nebo sdílená URL k vašemu dokumentu SBOM-for-AI. Může to být PDF, soubor JSON nebo stránka projektu.",
      pt: "URL público ou partilhado do seu documento SBOM-for-AI. Pode ser um PDF, um ficheiro JSON ou uma página de projeto.",
      ro: "URL public sau partajat către documentul dumneavoastră SBOM-for-AI. Poate fi un PDF, un fișier JSON sau o pagină de proiect.",
    },
    legalBasis: "NIS2 Art. 21(2)(d) / ENISA TIG §5.1.2",
    required: false,
    visibleWhen: { field: "providesSbomForAi", equals: true },
  },
];
