// Source of truth for the supplier questionnaire fields in this section.
// Edit this file (not data/supply-chain-questionnaire.json) and run
// `bun run build:json` to regenerate the published JSON artefact.
//
// Descriptions are Mittelstand-readable plain language with a "tick yes if"
// threshold and concrete examples. Legal citations live in `legalBasis` so
// audit teams still see the source. Labels are the public schema contract
// and are not edited here.

import type { SupplierField } from "../schema";

export const securityPracticesFields: SupplierField[] = [
  {
    id: "hasIsms",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented Information Security Management System (ISMS)",
      de: "Dokumentiertes Informationssicherheits-Managementsystem (ISMS)",
      fr: "Système de management de la sécurité de l'information documenté (ISMS)",
      it: "Sistema di gestione della sicurezza delle informazioni documentato (ISMS)",
      es: "Sistema de gestión de la seguridad de la información documentado (ISMS)",
      pl: "Udokumentowany system zarządzania bezpieczeństwem informacji (ISMS)",
      cs: "Dokumentovaný systém řízení bezpečnosti informací (ISMS)",
      pt: "Sistema de gestão da segurança da informação documentado (ISMS)",
      ro: "Sistem documentat de management al securității informației (ISMS)",
    },
    description: {
      en: "Tick yes if you have a written information security policy with assigned roles, regular reviews, and documented incident handling. ISO 27001 or BSI Grundschutz certification implies yes.",
      de: "Ja, wenn Sie eine schriftliche Informationssicherheits-Richtlinie haben, klar zugewiesene Rollen, regelmäßige Überprüfungen und einen dokumentierten Umgang mit Vorfällen. ISO 27001 oder BSI Grundschutz Zertifizierung bedeutet automatisch Ja.",
      fr: "Cochez oui si vous disposez d'une politique de sécurité de l'information écrite avec des rôles attribués, des revues régulières et une gestion documentée des incidents. Une certification ISO 27001 ou BSI Grundschutz implique oui.",
      it: "Selezionare sì se si dispone di una politica scritta di sicurezza delle informazioni con ruoli assegnati, revisioni periodiche e gestione documentata degli incidenti. Una certificazione ISO 27001 o BSI Grundschutz implica sì.",
      es: "Marque sí si dispone de una política escrita de seguridad de la información con roles asignados, revisiones periódicas y gestión documentada de incidentes. Una certificación ISO 27001 o BSI Grundschutz implica sí.",
      pl: "Zaznacz tak, jeśli masz pisemną politykę bezpieczeństwa informacji z przypisanymi rolami, regularnymi przeglądami i udokumentowaną obsługą incydentów. Certyfikacja ISO 27001 lub BSI Grundschutz oznacza tak.",
      cs: "Zaškrtněte ano, pokud máte písemnou politiku bezpečnosti informací s přidělenými rolemi, pravidelnými přezkumy a dokumentovaným řešením incidentů. Certifikace ISO 27001 nebo BSI Grundschutz znamená ano.",
      pt: "Assinale sim se tiver uma política escrita de segurança da informação com funções atribuídas, revisões periódicas e tratamento documentado de incidentes. Uma certificação ISO 27001 ou BSI Grundschutz implica sim.",
      ro: "Bifați da dacă aveți o politică scrisă de securitate a informației cu roluri atribuite, revizuiri periodice și gestionarea documentată a incidentelor. O certificare ISO 27001 sau BSI Grundschutz implică da.",
    },
    legalBasis: "CIR 2024/2690 §5.1.2(a)",
    required: true,
  },
  {
    id: "hasIso27001OrEquivalent",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Hold ISO 27001, BSI Grundschutz, or equivalent certification",
      de: "ISO 27001, BSI Grundschutz oder gleichwertige Zertifizierung",
      fr: "Détenir une certification ISO 27001, BSI Grundschutz ou équivalente",
      it: "Possesso di una certificazione ISO 27001, BSI Grundschutz o equivalente",
      es: "Disponer de certificación ISO 27001, BSI Grundschutz o equivalente",
      pl: "Posiadanie certyfikatu ISO 27001, BSI Grundschutz lub równoważnego",
      cs: "Držení certifikace ISO 27001, BSI Grundschutz nebo rovnocenné",
      pt: "Deter certificação ISO 27001, BSI Grundschutz ou equivalente",
      ro: "Deținerea certificării ISO 27001, BSI Grundschutz sau echivalente",
    },
    description: {
      en: "Tick yes if your company currently holds an ISO 27001, BSI Grundschutz, SOC 2 Type II, or equivalent certification. Upload the certificate in the Certifications tab.",
      de: "Ja, wenn Ihr Unternehmen aktuell nach ISO 27001, BSI Grundschutz, SOC 2 Type II oder einem gleichwertigen Standard zertifiziert ist. Das Zertifikat laden Sie im Reiter Zertifizierungen hoch.",
      fr: "Cochez oui si votre entreprise détient actuellement une certification ISO 27001, BSI Grundschutz, SOC 2 Type II ou équivalente. Téléchargez le certificat dans l'onglet Certifications.",
      it: "Selezionare sì se la vostra azienda possiede attualmente una certificazione ISO 27001, BSI Grundschutz, SOC 2 Type II o equivalente. Caricate il certificato nella scheda Certificazioni.",
      es: "Marque sí si su empresa dispone actualmente de una certificación ISO 27001, BSI Grundschutz, SOC 2 Type II o equivalente. Suba el certificado en la pestaña Certificaciones.",
      pl: "Zaznacz tak, jeśli Twoja firma posiada aktualnie certyfikat ISO 27001, BSI Grundschutz, SOC 2 Type II lub równoważny. Prześlij certyfikat w zakładce Certyfikaty.",
      cs: "Zaškrtněte ano, pokud vaše společnost aktuálně drží certifikaci ISO 27001, BSI Grundschutz, SOC 2 Type II nebo rovnocennou. Certifikát nahrajte na kartě Certifikace.",
      pt: "Assinale sim se a sua empresa detiver atualmente uma certificação ISO 27001, BSI Grundschutz, SOC 2 Type II ou equivalente. Carregue o certificado no separador Certificações.",
      ro: "Bifați da dacă societatea dumneavoastră deține în prezent o certificare ISO 27001, BSI Grundschutz, SOC 2 Type II sau echivalentă. Încărcați certificatul în fila Certificări.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(b)",
    required: true,
  },
  {
    id: "staffSecurityTraining",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Annual security awareness training for all staff",
      de: "Jährliche Security-Awareness-Schulung für alle Mitarbeitenden",
      fr: "Formation annuelle de sensibilisation à la sécurité pour tout le personnel",
      it: "Formazione annuale di sensibilizzazione alla sicurezza per tutto il personale",
      es: "Formación anual de concienciación en seguridad para todo el personal",
      pl: "Coroczne szkolenie z zakresu świadomości bezpieczeństwa dla całego personelu",
      cs: "Každoroční školení o povědomí o bezpečnosti pro všechny zaměstnance",
      pt: "Formação anual de sensibilização para a segurança para todo o pessoal",
      ro: "Instruire anuală de conștientizare a securității pentru tot personalul",
    },
    description: {
      en: "Tick yes if every staff member receives at least one annual information-security awareness training. E-learning counts; phishing simulations add to it.",
      de: "Ja, wenn alle Mitarbeitenden mindestens einmal pro Jahr eine Awareness-Schulung zur Informationssicherheit erhalten. E-Learning genügt, Phishing-Simulationen kommen oben drauf.",
      fr: "Cochez oui si chaque membre du personnel reçoit au moins une formation annuelle de sensibilisation à la sécurité de l'information. Le e-learning compte ; les simulations de phishing s'y ajoutent.",
      it: "Selezionare sì se ogni dipendente riceve almeno una formazione annuale di sensibilizzazione alla sicurezza delle informazioni. L'e-learning è valido; le simulazioni di phishing si aggiungono.",
      es: "Marque sí si cada miembro del personal recibe al menos una formación anual de concienciación en seguridad de la información. El e-learning cuenta; las simulaciones de phishing se suman.",
      pl: "Zaznacz tak, jeśli każdy pracownik otrzymuje co najmniej jedno coroczne szkolenie z zakresu świadomości bezpieczeństwa informacji. E-learning się liczy; symulacje phishingu są uzupełnieniem.",
      cs: "Zaškrtněte ano, pokud každý zaměstnanec absolvuje alespoň jedno každoroční školení o povědomí o bezpečnosti informací. E-learning se počítá, simulace phishingu jsou doplňkem.",
      pt: "Assinale sim se cada colaborador receber pelo menos uma formação anual de sensibilização para a segurança da informação. O e-learning conta, as simulações de phishing acrescentam-se.",
      ro: "Bifați da dacă fiecare angajat beneficiază de cel puțin o instruire anuală de conștientizare a securității informației. E-learningul contează, simulările de phishing se adaugă.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(b)",
    required: true,
  },
  {
    id: "backgroundChecks",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Suitability checks for staff with privileged access",
      de: "Zuverlässigkeitsprüfung für Mitarbeitende mit privilegiertem Zugang",
    },
    description: {
      en: "Tick yes if, before they start, you check that people who will have administrator or data access at customers are suitable for that role, as far as employment and data protection law allow (references, for example, or a criminal record certificate where lawful and needed for the role). Checking every member of staff is not expected.",
      de: "Ja, wenn Sie vor dem Einsatz prüfen, ob Mitarbeitende mit Administrator oder Datenzugang bei Kunden für diese Rolle geeignet sind, soweit Arbeitsrecht und Datenschutz es erlauben (etwa Referenzen oder, wo zulässig und für die Rolle nötig, ein Führungszeugnis). Eine Prüfung aller Mitarbeitenden wird nicht erwartet.",
    },
    legalBasis: "CIR 2024/2690 §10.2.1",
    required: true,
  },
  {
    id: "vulnerabilityHandling",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented vulnerability handling and patching process",
      de: "Dokumentierter Schwachstellen- und Patch-Management-Prozess",
      fr: "Processus documenté de gestion des vulnérabilités et de correctifs",
      it: "Processo documentato di gestione delle vulnerabilità e di patching",
      es: "Proceso documentado de gestión de vulnerabilidades y aplicación de parches",
      pl: "Udokumentowany proces obsługi podatności i instalowania poprawek",
      cs: "Dokumentovaný proces řešení zranitelností a instalace záplat",
      pt: "Processo documentado de tratamento de vulnerabilidades e aplicação de correções",
      ro: "Proces documentat de gestionare a vulnerabilităților și de aplicare a corecțiilor",
    },
    description: {
      en: "Tick yes if you have a written process for handling security vulnerabilities: detect, assess, prioritise, patch or mitigate. CVE monitoring and SLA-driven patching are the standard.",
      de: "Ja, wenn Sie einen schriftlichen Prozess für die Behandlung von Sicherheitslücken haben: erkennen, bewerten, priorisieren, patchen oder mitigieren. CVE-Monitoring und SLA-basiertes Patching gelten als Standard.",
      fr: "Cochez oui si vous disposez d'un processus écrit pour traiter les vulnérabilités de sécurité : détecter, évaluer, prioriser, corriger ou atténuer. La surveillance des CVE et l'application de correctifs pilotée par SLA sont la norme.",
      it: "Selezionare sì se si dispone di un processo scritto per la gestione delle vulnerabilità di sicurezza: rilevare, valutare, dare priorità, applicare patch o mitigare. Il monitoraggio delle CVE e il patching guidato da SLA sono lo standard.",
      es: "Marque sí si dispone de un proceso escrito para gestionar las vulnerabilidades de seguridad: detectar, evaluar, priorizar, parchear o mitigar. La supervisión de CVE y la aplicación de parches basada en SLA son el estándar.",
      pl: "Zaznacz tak, jeśli masz pisemny proces obsługi podatności bezpieczeństwa: wykrywanie, ocena, priorytetyzacja, instalowanie poprawek lub łagodzenie. Monitorowanie CVE i instalowanie poprawek w oparciu o SLA są standardem.",
      cs: "Zaškrtněte ano, pokud máte písemný proces pro řešení bezpečnostních zranitelností: detekce, vyhodnocení, stanovení priorit, záplatování nebo zmírnění. Monitorování CVE a záplatování řízené SLA jsou standardem.",
      pt: "Assinale sim se tiver um processo escrito para o tratamento de vulnerabilidades de segurança: detetar, avaliar, priorizar, corrigir ou mitigar. A monitorização de CVE e a aplicação de correções orientada por SLA são a norma.",
      ro: "Bifați da dacă aveți un proces scris pentru gestionarea vulnerabilităților de securitate: detectare, evaluare, prioritizare, aplicarea corecțiilor sau atenuare. Monitorizarea CVE și aplicarea corecțiilor pe baza SLA sunt standardul.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(f)",
    required: true,
  },
  {
    id: "acceptRightToAudit",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Accept customer right to audit (or provide audit reports)",
      de: "Akzeptanz des Auditrechts (oder Bereitstellung von Auditberichten)",
      fr: "Accepter le droit d'audit du client (ou fournir des rapports d'audit)",
      it: "Accettare il diritto di audit del cliente (o fornire relazioni di audit)",
      es: "Aceptar el derecho de auditoría del cliente (o proporcionar informes de auditoría)",
      pl: "Akceptacja prawa klienta do audytu (lub udostępnianie raportów z audytu)",
      cs: "Akceptace práva zákazníka na audit (nebo poskytnutí auditních zpráv)",
      pt: "Aceitar o direito de auditoria do cliente (ou fornecer relatórios de auditoria)",
      ro: "Acceptarea dreptului de audit al clientului (sau furnizarea de rapoarte de audit)",
    },
    description: {
      en: "Tick yes if you either grant customers an on-site audit right or provide substitute audit reports (for example SOC 2, ISAE 3402).",
      de: "Ja, wenn Sie Kunden entweder ein Auditrecht vor Ort einräumen oder ihnen stellvertretend Auditberichte (zum Beispiel SOC 2, ISAE 3402) zur Verfügung stellen.",
      fr: "Cochez oui si vous accordez aux clients soit un droit d'audit sur site, soit des rapports d'audit de substitution (par exemple SOC 2, ISAE 3402).",
      it: "Selezionare sì se si concede ai clienti un diritto di audit in loco oppure si forniscono relazioni di audit sostitutive (ad esempio SOC 2, ISAE 3402).",
      es: "Marque sí si concede a los clientes un derecho de auditoría in situ o les proporciona informes de auditoría sustitutivos (por ejemplo SOC 2, ISAE 3402).",
      pl: "Zaznacz tak, jeśli przyznajesz klientom prawo do audytu na miejscu albo udostępniasz zastępcze raporty z audytu (na przykład SOC 2, ISAE 3402).",
      cs: "Zaškrtněte ano, pokud zákazníkům buď udělujete právo na audit na místě, nebo poskytujete náhradní auditní zprávy (například SOC 2, ISAE 3402).",
      pt: "Assinale sim se conceder aos clientes um direito de auditoria no local ou fornecer relatórios de auditoria substitutos (por exemplo SOC 2, ISAE 3402).",
      ro: "Bifați da dacă fie acordați clienților un drept de audit la fața locului, fie furnizați rapoarte de audit substitutive (de exemplu SOC 2, ISAE 3402).",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(e)",
    required: true,
  },
  {
    id: "hasSubprocessors",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Use subprocessors / sub-suppliers",
      de: "Einsatz von Unterauftragnehmern",
      fr: "Recours à des sous-traitants ultérieurs / sous-fournisseurs",
      it: "Ricorso a subincaricati / subfornitori",
      es: "Uso de subencargados / subproveedores",
      pl: "Korzystanie z podwykonawców przetwarzania / poddostawców",
      cs: "Využití dalších zpracovatelů / subdodavatelů",
      pt: "Utilização de subcontratantes / subfornecedores",
      ro: "Utilizarea de subîmputerniciți / subfurnizori",
    },
    description: {
      en: "Tick yes if you use other companies to deliver your service that have access to customer data or infrastructure. Typical examples: AWS, Azure, Cloudflare, Stripe.",
      de: "Ja, wenn Sie für die Leistungserbringung andere Unternehmen einsetzen, die Zugang zu Kundendaten oder Kunden-Infrastruktur haben. Typische Beispiele: AWS, Azure, Cloudflare, Stripe.",
      fr: "Cochez oui si vous recourez à d'autres entreprises pour fournir votre service et qu'elles ont accès aux données ou à l'infrastructure des clients. Exemples typiques : AWS, Azure, Cloudflare, Stripe.",
      it: "Selezionare sì se per erogare il servizio si ricorre ad altre aziende che hanno accesso ai dati o all'infrastruttura dei clienti. Esempi tipici: AWS, Azure, Cloudflare, Stripe.",
      es: "Marque sí si recurre a otras empresas para prestar su servicio que tienen acceso a los datos o la infraestructura de los clientes. Ejemplos típicos: AWS, Azure, Cloudflare, Stripe.",
      pl: "Zaznacz tak, jeśli do świadczenia usługi korzystasz z innych firm, które mają dostęp do danych lub infrastruktury klientów. Typowe przykłady: AWS, Azure, Cloudflare, Stripe.",
      cs: "Zaškrtněte ano, pokud k poskytování své služby využíváte jiné společnosti, které mají přístup k zákaznickým datům nebo infrastruktuře. Typické příklady: AWS, Azure, Cloudflare, Stripe.",
      pt: "Assinale sim se utilizar outras empresas para prestar o seu serviço que tenham acesso aos dados ou à infraestrutura dos clientes. Exemplos típicos: AWS, Azure, Cloudflare, Stripe.",
      ro: "Bifați da dacă, pentru a vă presta serviciul, utilizați alte societăți care au acces la datele sau la infrastructura clienților. Exemple tipice: AWS, Azure, Cloudflare, Stripe.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(g)",
    required: true,
  },
  {
    id: "subprocessorList",
    section: "security_practices",
    type: "text",
    label: {
      en: "List of subprocessors",
      de: "Liste der Unterauftragnehmer",
      fr: "Liste des sous-traitants ultérieurs",
      it: "Elenco dei subincaricati",
      es: "Lista de subencargados",
      pl: "Lista podwykonawców przetwarzania",
      cs: "Seznam dalších zpracovatelů",
      pt: "Lista de subcontratantes",
      ro: "Lista subîmputerniciților",
    },
    description: {
      en: "List every subprocessor with name, processing location, and what they do for you. A table or bullet list is enough. Update whenever you add or remove one.",
      de: "Liste aller Unterauftragnehmer mit Name, Verarbeitungsort und Aufgabe. Eine Tabelle oder Stichpunktliste genügt. Aktualisieren Sie sie, wenn Sie einen Unterauftragnehmer hinzufügen oder entfernen.",
      fr: "Listez chaque sous-traitant ultérieur avec son nom, son lieu de traitement et ce qu'il fait pour vous. Un tableau ou une liste à puces suffit. Mettez-la à jour à chaque ajout ou retrait.",
      it: "Elencare ogni subincaricato con nome, luogo di trattamento e attività svolta per voi. È sufficiente una tabella o un elenco puntato. Aggiornatela ogni volta che ne aggiungete o rimuovete uno.",
      es: "Enumere cada subencargado con su nombre, lugar de tratamiento y lo que hace por usted. Basta con una tabla o una lista de viñetas. Actualícela cada vez que añada o elimine uno.",
      pl: "Wymień każdego podwykonawcę przetwarzania z nazwą, miejscem przetwarzania i tym, co dla Ciebie robi. Wystarczy tabela lub lista punktowana. Aktualizuj ją za każdym razem, gdy dodajesz lub usuwasz podwykonawcę.",
      cs: "Uveďte každého dalšího zpracovatele s názvem, místem zpracování a tím, co pro vás dělá. Postačí tabulka nebo odrážkový seznam. Aktualizujte ji vždy, když nějakého přidáte nebo odeberete.",
      pt: "Enumere cada subcontratante com o nome, o local de tratamento e o que faz para si. Basta uma tabela ou uma lista de pontos. Atualize-a sempre que adicionar ou remover um.",
      ro: "Enumerați fiecare subîmputernicit cu numele, locul prelucrării și activitatea pe care o desfășoară pentru dumneavoastră. Este suficient un tabel sau o listă cu marcatori. Actualizați-o ori de câte ori adăugați sau eliminați unul.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(g)",
    required: false,
    visibleWhen: { field: "hasSubprocessors", equals: true },
  },
  {
    id: "subprocessorRequirementsPassedOn",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "We bind subcontractors to comparable security requirements",
      de: "Wir verpflichten Unterauftragnehmer auf vergleichbare Sicherheitsanforderungen",
    },
    description: {
      en: "Tick yes if your contracts with subcontractors contain security requirements that match what your customers ask of you, for example on incidents, access and data handling.",
      de: "Ja, wenn Ihre Verträge mit Unterauftragnehmern Sicherheitsanforderungen enthalten, die dem entsprechen, was Ihre Kunden von Ihnen verlangen, etwa zu Vorfällen, Zugängen und dem Umgang mit Daten.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(g)",
    required: true,
    visibleWhen: { field: "hasSubprocessors", equals: true },
  },
  {
    id: "dataReturnOnTermination",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Commit to return / destroy customer data on termination",
      de: "Verpflichtung zur Rückgabe / Vernichtung von Kundendaten bei Vertragsende",
      fr: "S'engager à restituer / détruire les données des clients à la résiliation",
      it: "Impegno a restituire / distruggere i dati dei clienti alla cessazione",
      es: "Comprometerse a devolver / destruir los datos del cliente al finalizar el contrato",
      pl: "Zobowiązanie do zwrotu / zniszczenia danych klientów po zakończeniu umowy",
      cs: "Závazek vrátit / zničit zákaznická data při ukončení smlouvy",
      pt: "Comprometer-se a devolver / destruir os dados do cliente na cessação",
      ro: "Angajamentul de a returna / distruge datele clientului la încetare",
    },
    description: {
      en: "Tick yes if you contractually commit to returning or destroying customer data at the end of the contract. Common practice: export and return, then delete within 30 days.",
      de: "Ja, wenn Sie sich vertraglich verpflichten, Kundendaten am Ende des Vertrags zurückzugeben oder zu vernichten. Üblich: Rückgabe als Export, dann Löschung innerhalb von 30 Tagen.",
      fr: "Cochez oui si vous vous engagez contractuellement à restituer ou détruire les données des clients à la fin du contrat. Pratique courante : export et restitution, puis suppression sous 30 jours.",
      it: "Selezionare sì se ci si impegna contrattualmente a restituire o distruggere i dati dei clienti al termine del contratto. Prassi comune: export e restituzione, quindi cancellazione entro 30 giorni.",
      es: "Marque sí si se compromete contractualmente a devolver o destruir los datos del cliente al finalizar el contrato. Práctica habitual: exportar y devolver, y luego eliminar en un plazo de 30 días.",
      pl: "Zaznacz tak, jeśli zobowiązujesz się umownie do zwrotu lub zniszczenia danych klientów po zakończeniu umowy. Powszechna praktyka: eksport i zwrot, a następnie usunięcie w ciągu 30 dni.",
      cs: "Zaškrtněte ano, pokud se smluvně zavazujete vrátit nebo zničit zákaznická data na konci smlouvy. Obvyklá praxe: export a vrácení, poté smazání do 30 dnů.",
      pt: "Assinale sim se se comprometer contratualmente a devolver ou destruir os dados do cliente no final do contrato. Prática comum: exportar e devolver e, depois, eliminar no prazo de 30 dias.",
      ro: "Bifați da dacă vă angajați contractual să returnați sau să distrugeți datele clientului la sfârșitul contractului. Practică comună: export și returnare, apoi ștergere în termen de 30 de zile.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(h)",
    required: true,
  },
  {
    id: "dpaAvailable",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Standard data processing agreement (DPA) available",
      de: "Standard-Auftragsverarbeitungsvertrag (AVV) verfügbar",
      fr: "Contrat type de traitement des données (DPA) disponible",
      it: "Accordo standard sul trattamento dei dati (DPA) disponibile",
      es: "Contrato estándar de tratamiento de datos (DPA) disponible",
      pl: "Dostępna standardowa umowa o przetwarzaniu danych (DPA)",
      cs: "Dostupná standardní smlouva o zpracování dat (DPA)",
      pt: "Contrato padrão de tratamento de dados (DPA) disponível",
      ro: "Acord standard de prelucrare a datelor (DPA) disponibil",
    },
    description: {
      en: "Tick yes if you have a standard data processing agreement that customers can sign. It is required once you process personal data on a customer's behalf (Art. 28(3) GDPR).",
      de: "Ja, wenn Sie einen standardisierten Auftragsverarbeitungsvertrag haben, den Kunden unterschreiben können. Nötig ist er, sobald Sie personenbezogene Daten im Auftrag eines Kunden verarbeiten (Art. 28 Abs. 3 DSGVO).",
    },
    legalBasis: "GDPR Art. 28(3)",
    required: true,
    visibleWhen: { field: "processesCustomerData", equals: true },
  },
  {
    id: "hasIncidentResponsePlan",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented incident response plan",
      de: "Dokumentierter Notfall-/Incident-Response-Plan",
      fr: "Plan de réponse aux incidents documenté",
      it: "Piano di risposta agli incidenti documentato",
      es: "Plan de respuesta a incidentes documentado",
      pl: "Udokumentowany plan reagowania na incydenty",
      cs: "Dokumentovaný plán reakce na incidenty",
      pt: "Plano de resposta a incidentes documentado",
      ro: "Plan documentat de răspuns la incidente",
    },
    description: {
      en: "Tick yes if you have a written plan for handling security incidents: who decides, who communicates, who documents. At least one tabletop exercise per year is good practice.",
      de: "Ja, wenn Sie einen schriftlichen Plan für den Umgang mit Sicherheitsvorfällen haben: wer entscheidet, wer kommuniziert, wer dokumentiert. Mindestens eine Tabletop-Übung pro Jahr ist gute Praxis.",
      fr: "Cochez oui si vous disposez d'un plan écrit pour gérer les incidents de sécurité : qui décide, qui communique, qui documente. Au moins un exercice sur table par an est une bonne pratique.",
      it: "Selezionare sì se si dispone di un piano scritto per la gestione degli incidenti di sicurezza: chi decide, chi comunica, chi documenta. Almeno un'esercitazione tabletop all'anno è una buona prassi.",
      es: "Marque sí si dispone de un plan escrito para gestionar los incidentes de seguridad: quién decide, quién comunica, quién documenta. Al menos un ejercicio de simulación al año es una buena práctica.",
      pl: "Zaznacz tak, jeśli masz pisemny plan obsługi incydentów bezpieczeństwa: kto decyduje, kto komunikuje, kto dokumentuje. Co najmniej jedno ćwiczenie sztabowe rocznie to dobra praktyka.",
      cs: "Zaškrtněte ano, pokud máte písemný plán pro řešení bezpečnostních incidentů: kdo rozhoduje, kdo komunikuje, kdo dokumentuje. Alespoň jedno stolní cvičení ročně je dobrou praxí.",
      pt: "Assinale sim se tiver um plano escrito para o tratamento de incidentes de segurança: quem decide, quem comunica, quem documenta. Pelo menos um exercício de simulação por ano é boa prática.",
      ro: "Bifați da dacă aveți un plan scris pentru gestionarea incidentelor de securitate: cine decide, cine comunică, cine documentează. Cel puțin un exercițiu de simulare pe an este o bună practică.",
    },
    legalBasis: "NIS2 Art. 21(2)(b) / ENISA TIG §3",
    required: true,
  },
  {
    id: "hasBusinessContinuityPlan",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Documented business continuity / disaster recovery plan",
      de: "Dokumentierter Business-Continuity- / Disaster-Recovery-Plan",
      fr: "Plan de continuité d'activité / reprise après sinistre documenté",
      it: "Piano di continuità operativa / ripristino di emergenza documentato",
      es: "Plan de continuidad de negocio / recuperación ante desastres documentado",
      pl: "Udokumentowany plan ciągłości działania / odtwarzania po awarii",
      cs: "Dokumentovaný plán kontinuity činnosti / obnovy po havárii",
      pt: "Plano de continuidade de negócio / recuperação de desastres documentado",
      ro: "Plan documentat de continuitate a activității / recuperare în caz de dezastru",
    },
    description: {
      en: "Tick yes if you have a plan that explains how you keep running or recover quickly during an outage: critical systems, fallbacks, RTO and RPO targets.",
      de: "Ja, wenn Sie einen Plan haben, der erklärt, wie Sie den Betrieb bei einem Ausfall aufrechterhalten oder schnell wiederherstellen: kritische Systeme, Ersatzwege, RTO und RPO Ziele.",
      fr: "Cochez oui si vous disposez d'un plan expliquant comment vous maintenez l'activité ou récupérez rapidement lors d'une panne : systèmes critiques, solutions de repli, objectifs RTO et RPO.",
      it: "Selezionare sì se si dispone di un piano che spiega come mantenere l'operatività o ripristinare rapidamente durante un'interruzione: sistemi critici, soluzioni di ripiego, obiettivi RTO e RPO.",
      es: "Marque sí si dispone de un plan que explique cómo mantiene el funcionamiento o se recupera con rapidez durante una interrupción: sistemas críticos, alternativas, objetivos RTO y RPO.",
      pl: "Zaznacz tak, jeśli masz plan wyjaśniający, jak utrzymujesz działanie lub szybko przywracasz je podczas awarii: systemy krytyczne, rozwiązania awaryjne, cele RTO i RPO.",
      cs: "Zaškrtněte ano, pokud máte plán, který vysvětluje, jak udržíte provoz nebo se rychle zotavíte při výpadku: kritické systémy, záložní řešení, cíle RTO a RPO.",
      pt: "Assinale sim se tiver um plano que explique como mantém o funcionamento ou recupera rapidamente durante uma interrupção: sistemas críticos, soluções de recurso, objetivos RTO e RPO.",
      ro: "Bifați da dacă aveți un plan care explică modul în care vă mențineți funcționarea sau vă recuperați rapid în timpul unei întreruperi: sisteme critice, soluții de rezervă, obiective RTO și RPO.",
    },
    legalBasis: "NIS2 Art. 21(2)(c) / ENISA TIG §4",
    required: true,
  },
  {
    id: "mfaEnforcedInternal",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "MFA enforced for all internal admin / privileged accounts",
      de: "MFA für alle internen Admin- / privilegierten Konten erzwungen",
      fr: "MFA imposé pour tous les comptes d'administration / à privilèges internes",
      it: "MFA imposto per tutti gli account amministrativi / privilegiati interni",
      es: "MFA obligatorio para todas las cuentas internas de administración / privilegiadas",
      pl: "MFA wymuszone dla wszystkich wewnętrznych kont administracyjnych / uprzywilejowanych",
      cs: "MFA vynuceno pro všechny interní administrátorské / privilegované účty",
      pt: "MFA imposto para todas as contas internas de administração / privilegiadas",
      ro: "MFA impus pentru toate conturile interne de administrare / privilegiate",
    },
    description: {
      en: "Tick yes if every internal admin or privileged account must use MFA. Hardware tokens or authenticator apps count; SMS does not.",
      de: "Ja, wenn alle internen Administrator-Konten oder Konten mit erhöhten Rechten MFA erzwingen müssen. Hardware-Tokens oder Authenticator-Apps zählen, SMS ist nicht ausreichend.",
      fr: "Cochez oui si chaque compte d'administration ou à privilèges interne doit utiliser le MFA. Les jetons matériels ou les applications d'authentification comptent ; le SMS ne compte pas.",
      it: "Selezionare sì se ogni account amministrativo o privilegiato interno deve utilizzare l'MFA. I token hardware o le app di autenticazione sono validi; gli SMS no.",
      es: "Marque sí si cada cuenta interna de administración o privilegiada debe usar MFA. Los tokens de hardware o las aplicaciones de autenticación cuentan; los SMS no.",
      pl: "Zaznacz tak, jeśli każde wewnętrzne konto administracyjne lub uprzywilejowane musi używać MFA. Tokeny sprzętowe lub aplikacje uwierzytelniające się liczą; SMS nie.",
      cs: "Zaškrtněte ano, pokud každý interní administrátorský nebo privilegovaný účet musí používat MFA. Hardwarové tokeny nebo autentizační aplikace se počítají, SMS nikoli.",
      pt: "Assinale sim se cada conta interna de administração ou privilegiada tiver de usar MFA. Os tokens de hardware ou as aplicações de autenticação contam, o SMS não.",
      ro: "Bifați da dacă fiecare cont intern de administrare sau privilegiat trebuie să utilizeze MFA. Tokenurile hardware sau aplicațiile de autentificare contează, SMS-ul nu.",
    },
    legalBasis: "NIS2 Art. 21(2)(j)",
    required: true,
  },
  {
    id: "hasPenetrationTestingProgram",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "Annual or biennial penetration testing program",
      de: "Jährliches oder zweijährliches Penetrationstest-Programm",
      fr: "Programme de tests d'intrusion annuel ou biennal",
      it: "Programma di penetration test annuale o biennale",
      es: "Programa de pruebas de penetración anual o bienal",
      pl: "Program testów penetracyjnych co rok lub co dwa lata",
      cs: "Program penetračního testování každý rok nebo každé dva roky",
      pt: "Programa de testes de penetração anual ou bienal",
      ro: "Program de testare a penetrării anual sau bienal",
    },
    description: {
      en: "Tick yes if you commission an external penetration test at least every one to two years. For smaller companies, an external vulnerability scan as a minimum step is acceptable.",
      de: "Ja, wenn Sie mindestens alle ein bis zwei Jahre einen externen Penetrationstest beauftragen. Bei kleineren Unternehmen ist eine externe Schwachstellenanalyse als Mindestschritt akzeptabel.",
      fr: "Cochez oui si vous commandez un test d'intrusion externe au moins tous les un à deux ans. Pour les petites entreprises, un scan de vulnérabilités externe comme étape minimale est acceptable.",
      it: "Selezionare sì se si commissiona un penetration test esterno almeno ogni uno o due anni. Per le aziende più piccole, una scansione esterna delle vulnerabilità come passo minimo è accettabile.",
      es: "Marque sí si encarga una prueba de penetración externa al menos cada uno o dos años. Para las empresas más pequeñas, un escaneo de vulnerabilidades externo como paso mínimo es aceptable.",
      pl: "Zaznacz tak, jeśli zlecasz zewnętrzny test penetracyjny co najmniej raz na jeden do dwóch lat. W przypadku mniejszych firm akceptowalnym minimalnym krokiem jest zewnętrzne skanowanie podatności.",
      cs: "Zaškrtněte ano, pokud si necháváte provést externí penetrační test alespoň jednou za jeden až dva roky. U menších společností je jako minimální krok přijatelné externí skenování zranitelností.",
      pt: "Assinale sim se encomendar um teste de penetração externo pelo menos uma vez de um a dois anos. Para empresas mais pequenas, uma análise externa de vulnerabilidades como passo mínimo é aceitável.",
      ro: "Bifați da dacă comandați un test de penetrare extern cel puțin o dată la unu sau doi ani. Pentru societățile mai mici, o scanare externă a vulnerabilităților ca pas minim este acceptabilă.",
    },
    legalBasis: "NIS2 Art. 21(2)(e) / ENISA TIG §6.5",
    required: true,
  },
  {
    id: "secureDevelopment",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "We develop to defined secure development rules",
      de: "Wir entwickeln nach festgelegten Regeln für sichere Entwicklung",
    },
    description: {
      en: "Tick yes if your development follows set rules, for example a review before every change goes live, dependencies kept up to date, tests, and a check for known vulnerabilities. Asked only of suppliers who run software as a service or ship software.",
      de: "Ja, wenn Ihre Entwicklung festen Regeln folgt, zum Beispiel einer Prüfung vor jeder Änderung, die live geht, aktuellen Abhängigkeiten, Tests und einer Prüfung auf bekannte Schwachstellen. Gefragt nur bei Lieferanten, die Software als Dienst betreiben oder ausliefern.",
    },
    legalBasis: "CIR 2024/2690 §5.1.2(a)",
    required: true,
    visibleWhen: {
      anyOf: [
        { field: "isSaas", equals: true },
        { field: "isOnPrem", equals: true },
      ],
    },
  },
  {
    id: "pastBreachesDisclosed",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "We disclose past notifiable cybersecurity events when asked by customers",
      de: "Wir legen frühere meldepflichtige Sicherheitsvorfälle auf Anfrage offen",
      fr: "Nous divulguons les événements de cybersécurité notifiables passés à la demande des clients",
      it: "Divulghiamo gli eventi di cibersicurezza notificabili passati su richiesta dei clienti",
      es: "Divulgamos los eventos de ciberseguridad notificables pasados cuando los clientes lo solicitan",
      pl: "Ujawniamy przeszłe podlegające zgłoszeniu zdarzenia cyberbezpieczeństwa na prośbę klientów",
      cs: "Na žádost zákazníků zveřejňujeme minulé ohlašovací povinnosti podléhající události kybernetické bezpečnosti",
      pt: "Divulgamos eventos de cibersegurança notificáveis ocorridos no passado quando solicitado pelos clientes",
      ro: "Divulgăm evenimentele de securitate cibernetică notificabile din trecut la cererea clienților",
    },
    description: {
      en: "Tick yes if, on customer request, you openly disclose whether and which reportable security incidents your company had in the past. Common window: the last three to five years.",
      de: "Ja, wenn Sie auf Kundenanfrage offen kommunizieren, ob und welche meldepflichtigen Sicherheitsvorfälle Ihr Unternehmen in der Vergangenheit hatte. Übliche Schwelle: die letzten drei bis fünf Jahre.",
      fr: "Cochez oui si, à la demande du client, vous divulguez ouvertement si et quels incidents de sécurité à signaler votre entreprise a connus par le passé. Fenêtre courante : les trois à cinq dernières années.",
      it: "Selezionare sì se, su richiesta del cliente, divulgate apertamente se e quali incidenti di sicurezza notificabili la vostra azienda ha avuto in passato. Finestra comune: gli ultimi tre-cinque anni.",
      es: "Marque sí si, a petición del cliente, divulga abiertamente si su empresa tuvo en el pasado incidentes de seguridad notificables y cuáles. Ventana habitual: los últimos tres a cinco años.",
      pl: "Zaznacz tak, jeśli na prośbę klienta otwarcie ujawniasz, czy i jakie podlegające zgłoszeniu incydenty bezpieczeństwa Twoja firma miała w przeszłości. Typowy okres: ostatnie od trzech do pięciu lat.",
      cs: "Zaškrtněte ano, pokud na žádost zákazníka otevřeně sdělíte, zda a jaké ohlašovací povinnosti podléhající bezpečnostní incidenty vaše společnost v minulosti měla. Obvyklé okno: poslední tři až pět let.",
      pt: "Assinale sim se, a pedido do cliente, divulgar abertamente se e que incidentes de segurança notificáveis a sua empresa teve no passado. Janela comum: os últimos três a cinco anos.",
      ro: "Bifați da dacă, la cererea clientului, divulgați deschis dacă și ce incidente de securitate notificabile a avut societatea dumneavoastră în trecut. Interval comun: ultimii trei până la cinci ani.",
    },
    legalBasis: "ENISA TIG §5.1.2",
    required: true,
  },
  {
    id: "cooperateWithAuthorities",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "We give customers the information their authority asks for",
      de: "Wir liefern Kunden die Angaben, die ihre Behörde verlangt",
    },
    description: {
      en: "Tick yes if you give your customers the information their supervisory authority asks for after an incident or during an audit. As a supplier you owe that authority nothing directly; the duty is your customer's, and you help them meet it.",
      de: "Ja, wenn Sie Ihren Kunden die Angaben liefern, die deren Aufsichtsbehörde nach einem Vorfall oder bei einer Prüfung verlangt. Als Lieferant sind Sie dieser Behörde nicht selbst verpflichtet; die Pflicht hat Ihr Kunde, und Sie helfen ihm, sie zu erfüllen.",
    },
    legalBasis: "ENISA TIG §5.1.4",
    required: true,
  },
  {
    id: "notifyMaterialChanges",
    section: "security_practices",
    type: "boolean",
    label: {
      en: "We inform customers of material changes, including where their data is processed",
      de: "Wir informieren Kunden über wesentliche Änderungen, auch der Verarbeitungsorte",
    },
    description: {
      en: "Tick yes if you tell customers before anything material changes in how you deliver: a takeover, a new subcontractor, another hosting provider, or a new country where their data is processed.",
      de: "Ja, wenn Sie Kunden vorab informieren, bevor sich an Ihrer Leistung etwas Wesentliches ändert: eine Übernahme, ein neuer Unterauftragnehmer, ein anderer Hoster oder ein neues Land, in dem ihre Daten verarbeitet werden.",
    },
    legalBasis: "ENISA TIG §5.1.4",
    required: true,
  },
];
