import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.1",
  passingScore: 75,
  questions: [
    {
      id: "1.1.1",
      question: {
        en: "Which field allows a vulnerability scanner to look up a component in a CVE database?",
        de: "Welches Feld ermöglicht einem Schwachstellenscanner die Suche nach einer Komponente in einer CVE-Datenbank?",
        fr: "Quel champ permet à un scanner de vulnérabilités de rechercher un composant dans une base de données CVE ?",
        it: "Quale campo consente a uno scanner di vulnerabilità di cercare un componente in una banca dati CVE?",
        es: "¿Qué campo permite a un escáner de vulnerabilidades buscar un componente en una base de datos CVE?",
        pl: "Które pole umożliwia skanerowi podatności wyszukanie komponentu w bazie danych CVE?",
      },
      options: [
        { en: "The component name field", de: "Das Namensfeld der Komponente", fr: "Le champ du nom du composant", it: "Il campo del nome del componente", es: "El campo del nombre del componente", pl: "Pole nazwy komponentu" },
        { en: "The PURL (Package URL)", de: "Die PURL (Package URL)", fr: "La PURL (Package URL)", it: "La PURL (Package URL)", es: "La PURL (Package URL)", pl: "PURL (Package URL)" },
        { en: "The supplier field", de: "Das Lieferantenfeld", fr: "Le champ du fournisseur", it: "Il campo del fornitore", es: "El campo del proveedor", pl: "Pole dostawcy" },
        { en: "The license identifier", de: "Der Lizenzbezeichner", fr: "L'identifiant de licence", it: "L'identificatore di licenza", es: "El identificador de licencia", pl: "Identyfikator licencji" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The PURL (Package URL) is the standard unique identifier for SBOM components. Vulnerability databases use PURLs to link CVE records to specific packages and versions, making them the anchor for automated vulnerability scanning.",
        de: "Die PURL (Package URL) ist der standardisierte eindeutige Bezeichner für SBOM-Komponenten. Schwachstellendatenbanken verwenden PURLs, um CVE-Einträge mit bestimmten Paketen und Versionen zu verknüpfen — sie sind der Anker für automatisierte Schwachstellensuche.",
        fr: "La PURL (Package URL) est l'identifiant unique standard des composants SBOM. Les bases de données de vulnérabilités utilisent les PURL pour relier les enregistrements CVE à des paquets et versions précis, ce qui en fait le point d'ancrage de l'analyse automatisée des vulnérabilités.",
        it: "La PURL (Package URL) è l'identificatore univoco standard dei componenti SBOM. Le banche dati delle vulnerabilità usano le PURL per collegare i record CVE a pacchetti e versioni specifici, rendendole il punto di ancoraggio per la scansione automatizzata delle vulnerabilità.",
        es: "La PURL (Package URL) es el identificador único estándar de los componentes SBOM. Las bases de datos de vulnerabilidades usan las PURL para vincular registros CVE con paquetes y versiones concretos, lo que las convierte en el ancla del análisis automatizado de vulnerabilidades.",
        pl: "PURL (Package URL) to standardowy unikatowy identyfikator komponentów SBOM. Bazy danych podatności używają PURL, aby powiązać wpisy CVE z konkretnymi pakietami i wersjami, co czyni je punktem zaczepienia dla zautomatyzowanego skanowania podatności.",
      },
    },
    {
      id: "1.1.2",
      question: {
        en: "Why must the SBOM record an exact version string rather than a version range?",
        de: "Warum muss die SBOM eine genaue Versionszeichenkette statt eines Versionsbereichs enthalten?",
        fr: "Pourquoi la SBOM doit-elle enregistrer une chaîne de version exacte plutôt qu'une plage de versions ?",
        it: "Perché la SBOM deve registrare una stringa di versione esatta anziché un intervallo di versioni?",
        es: "¿Por qué debe la SBOM registrar una cadena de versión exacta en lugar de un intervalo de versiones?",
        pl: "Dlaczego SBOM musi zapisywać dokładny ciąg wersji, a nie zakres wersji?",
      },
      options: [
        { en: "Because Annex VII CRA requires a specific version format", de: "Weil Anhang VII CRA ein bestimmtes Versionsformat vorschreibt", fr: "Parce que l'annexe VII CRA exige un format de version précis", it: "Perché l'allegato VII CRA richiede un formato di versione specifico", es: "Porque el anexo VII CRA exige un formato de versión específico", pl: "Ponieważ załącznik VII CRA wymaga określonego formatu wersji" },
        { en: "Because a CVE typically affects a version range and is fixed in a specific version — without the exact version, you cannot determine exposure", de: "Weil eine CVE typischerweise einen Versionsbereich betrifft und in einer bestimmten Version behoben ist — ohne die genaue Version lässt sich die Betroffenheit nicht feststellen", fr: "Parce qu'une CVE affecte généralement une plage de versions et est corrigée dans une version précise. Sans la version exacte, vous ne pouvez pas déterminer l'exposition", it: "Perché una CVE riguarda tipicamente un intervallo di versioni ed è corretta in una versione specifica. Senza la versione esatta, non è possibile determinare l'esposizione", es: "Porque una CVE suele afectar a un intervalo de versiones y se corrige en una versión concreta. Sin la versión exacta, no se puede determinar la exposición", pl: "Ponieważ CVE zazwyczaj dotyczy zakresu wersji i jest naprawiana w konkretnej wersji. Bez dokładnej wersji nie można ustalić narażenia" },
        { en: "Because PURL syntax does not support ranges", de: "Weil die PURL-Syntax keine Bereiche unterstützt", fr: "Parce que la syntaxe PURL ne prend pas en charge les plages", it: "Perché la sintassi PURL non supporta gli intervalli", es: "Porque la sintaxis PURL no admite intervalos", pl: "Ponieważ składnia PURL nie obsługuje zakresów" },
        { en: "Because the supplier field requires a matching version", de: "Weil das Lieferantenfeld eine übereinstimmende Version erfordert", fr: "Parce que le champ du fournisseur exige une version correspondante", it: "Perché il campo del fornitore richiede una versione corrispondente", es: "Porque el campo del proveedor exige una versión coincidente", pl: "Ponieważ pole dostawcy wymaga zgodnej wersji" },
      ],
      correctIndex: 1,
      explanation: {
        en: "CVEs are fixed in specific versions. A version range like '>=2.0' does not tell a scanner which binary is actually deployed, so it cannot determine whether that binary is affected by a given CVE.",
        de: "CVEs werden in bestimmten Versionen behoben. Ein Versionsbereich wie '>=2.0' sagt dem Scanner nicht, welches Binary tatsächlich eingesetzt wird — er kann daher nicht feststellen, ob es von einer CVE betroffen ist.",
        fr: "Les CVE sont corrigées dans des versions précises. Une plage de versions telle que '>=2.0' n'indique pas au scanner quel binaire est réellement déployé, il ne peut donc pas déterminer si ce binaire est affecté par une CVE donnée.",
        it: "Le CVE vengono corrette in versioni specifiche. Un intervallo di versioni come '>=2.0' non indica allo scanner quale binario sia effettivamente distribuito, quindi non può determinare se quel binario sia interessato da una determinata CVE.",
        es: "Las CVE se corrigen en versiones concretas. Un intervalo de versiones como '>=2.0' no indica al escáner qué binario está realmente desplegado, por lo que no puede determinar si ese binario se ve afectado por una CVE determinada.",
        pl: "CVE są naprawiane w konkretnych wersjach. Zakres wersji taki jak '>=2.0' nie informuje skanera, który plik binarny jest faktycznie wdrożony, więc nie może on ustalić, czy ten plik binarny jest podatny na daną CVE.",
      },
    },
    {
      id: "1.1.3",
      question: {
        en: "What does a hash field in an SBOM component entry verify?",
        de: "Was verifiziert ein Hash-Feld in einem SBOM-Komponenteneintrag?",
        fr: "Que vérifie un champ de hachage dans une entrée de composant SBOM ?",
        it: "Che cosa verifica un campo hash in una voce di componente SBOM?",
        es: "¿Qué verifica un campo de hash en una entrada de componente SBOM?",
        pl: "Co weryfikuje pole skrótu (hash) we wpisie komponentu SBOM?",
      },
      options: [
        { en: "That the component was downloaded from an approved registry", de: "Dass die Komponente aus einem genehmigten Registry heruntergeladen wurde", fr: "Que le composant a été téléchargé depuis un registre approuvé", it: "Che il componente sia stato scaricato da un registry approvato", es: "Que el componente se descargó de un registro aprobado", pl: "Że komponent został pobrany z zatwierdzonego rejestru" },
        { en: "That the component has no known vulnerabilities", de: "Dass die Komponente keine bekannten Schwachstellen hat", fr: "Que le composant ne présente aucune vulnérabilité connue", it: "Che il componente non presenti vulnerabilità note", es: "Que el componente no tiene vulnerabilidades conocidas", pl: "Że komponent nie ma znanych podatności" },
        { en: "That the component file has not been tampered with since the SBOM was generated", de: "Dass die Komponentendatei seit der SBOM-Erstellung nicht verändert wurde", fr: "Que le fichier du composant n'a pas été altéré depuis la génération de la SBOM", it: "Che il file del componente non sia stato manomesso dopo la generazione della SBOM", es: "Que el archivo del componente no ha sido manipulado desde que se generó la SBOM", pl: "Że plik komponentu nie został zmodyfikowany od czasu wygenerowania SBOM" },
        { en: "That the PURL matches the version field", de: "Dass die PURL mit dem Versionsfeld übereinstimmt", fr: "Que la PURL correspond au champ de version", it: "Che la PURL corrisponda al campo della versione", es: "Que la PURL coincide con el campo de versión", pl: "Że PURL jest zgodna z polem wersji" },
      ],
      correctIndex: 2,
      explanation: {
        en: "A hash is a fingerprint of the component file. It lets you verify integrity — that the component deployed is exactly the one the SBOM documents. It does not indicate vulnerability status or registry origin.",
        de: "Ein Hash ist ein Fingerabdruck der Komponentendatei. Er ermöglicht die Integritätsprüfung — dass die eingesetzte Komponente genau die ist, die die SBOM dokumentiert. Er gibt keine Auskunft über den Schwachstellenstatus oder die Registry-Herkunft.",
        fr: "Un hachage est une empreinte du fichier du composant. Il permet de vérifier l'intégrité, à savoir que le composant déployé est exactement celui que la SBOM documente. Il n'indique ni le statut de vulnérabilité ni l'origine du registre.",
        it: "Un hash è un'impronta del file del componente. Consente di verificare l'integrità, ovvero che il componente distribuito sia esattamente quello documentato dalla SBOM. Non indica lo stato di vulnerabilità né l'origine del registry.",
        es: "Un hash es una huella del archivo del componente. Permite verificar la integridad, es decir, que el componente desplegado es exactamente el que documenta la SBOM. No indica el estado de vulnerabilidad ni el origen del registro.",
        pl: "Skrót (hash) to odcisk pliku komponentu. Pozwala zweryfikować integralność, czyli że wdrożony komponent jest dokładnie tym, który dokumentuje SBOM. Nie wskazuje statusu podatności ani pochodzenia z rejestru.",
      },
    },
    {
      id: "1.1.4",
      question: {
        en: "What does the SBOM metadata section document?",
        de: "Was dokumentiert der Metadaten-Abschnitt der SBOM?",
        fr: "Que documente la section de métadonnées de la SBOM ?",
        it: "Che cosa documenta la sezione dei metadati della SBOM?",
        es: "¿Qué documenta la sección de metadatos de la SBOM?",
        pl: "Co dokumentuje sekcja metadanych SBOM?",
      },
      options: [
        { en: "The vulnerability status of each component", de: "Den Schwachstellenstatus jeder Komponente", fr: "Le statut de vulnérabilité de chaque composant", it: "Lo stato di vulnerabilità di ciascun componente", es: "El estado de vulnerabilidad de cada componente", pl: "Status podatności każdego komponentu" },
        { en: "When the SBOM was generated, which tool generated it, and what product it describes", de: "Wann die SBOM erstellt wurde, welches Werkzeug sie erstellt hat und welches Produkt sie beschreibt", fr: "Quand la SBOM a été générée, quel outil l'a générée et quel produit elle décrit", it: "Quando è stata generata la SBOM, quale strumento l'ha generata e quale prodotto descrive", es: "Cuándo se generó la SBOM, qué herramienta la generó y qué producto describe", pl: "Kiedy wygenerowano SBOM, jakie narzędzie ją wygenerowało i jaki produkt opisuje" },
        { en: "The license obligations for all components", de: "Die Lizenzverpflichtungen für alle Komponenten", fr: "Les obligations de licence pour tous les composants", it: "Gli obblighi di licenza per tutti i componenti", es: "Las obligaciones de licencia de todos los componentes", pl: "Zobowiązania licencyjne dla wszystkich komponentów" },
        { en: "The supplier contact information for each component", de: "Die Lieferantenkontaktdaten für jede Komponente", fr: "Les coordonnées du fournisseur pour chaque composant", it: "I dati di contatto del fornitore per ciascun componente", es: "Los datos de contacto del proveedor de cada componente", pl: "Dane kontaktowe dostawcy każdego komponentu" },
      ],
      correctIndex: 1,
      explanation: {
        en: "SBOM metadata covers the document itself: the generation timestamp, the tool that created it, and the top-level product it describes. Auditors check metadata first to verify the SBOM is current and properly attributed.",
        de: "SBOM-Metadaten betreffen das Dokument selbst: den Erstellungszeitpunkt, das erstellende Werkzeug und das beschriebene Produkt. Prüfer überprüfen die Metadaten zuerst, um sicherzustellen, dass die SBOM aktuell und korrekt zugeordnet ist.",
        fr: "Les métadonnées de la SBOM portent sur le document lui-même : l'horodatage de génération, l'outil qui l'a créée et le produit de premier niveau qu'elle décrit. Les auditeurs vérifient d'abord les métadonnées pour s'assurer que la SBOM est à jour et correctement attribuée.",
        it: "I metadati della SBOM riguardano il documento stesso: la marca temporale di generazione, lo strumento che l'ha creata e il prodotto di primo livello che descrive. Gli auditor controllano per primi i metadati per verificare che la SBOM sia aggiornata e correttamente attribuita.",
        es: "Los metadatos de la SBOM se refieren al documento en sí: la marca temporal de generación, la herramienta que la creó y el producto de nivel superior que describe. Los auditores revisan primero los metadatos para verificar que la SBOM está actualizada y correctamente atribuida.",
        pl: "Metadane SBOM dotyczą samego dokumentu: znacznika czasu wygenerowania, narzędzia, które go utworzyło, oraz opisywanego produktu najwyższego poziomu. Audytorzy najpierw sprawdzają metadane, aby zweryfikować, że SBOM jest aktualny i prawidłowo przypisany.",
      },
    },
    {
      id: "1.1.5",
      question: {
        en: "Which format satisfies the CRA Article 13(5) requirement for a 'machine-readable' SBOM?",
        de: "Welches Format erfüllt die CRA-Artikel-13(5)-Anforderung einer 'maschinenlesbaren' SBOM?",
        fr: "Quel format satisfait à l'exigence de l'article 13(5) CRA relative à une SBOM « lisible par machine » ?",
        it: "Quale formato soddisfa il requisito dell'articolo 13(5) CRA di una SBOM « leggibile da una macchina »?",
        es: "¿Qué formato satisface el requisito del artículo 13(5) CRA de una SBOM « legible por máquina »?",
        pl: "Który format spełnia wymóg artykułu 13(5) CRA dotyczący SBOM « odczytywalnego maszynowo »?",
      },
      options: [
        { en: "A PDF listing all component names and versions", de: "Ein PDF mit allen Komponentennamen und Versionen", fr: "Un PDF répertoriant tous les noms et versions des composants", it: "Un PDF che elenca tutti i nomi e le versioni dei componenti", es: "Un PDF que enumera todos los nombres y versiones de los componentes", pl: "Plik PDF z listą wszystkich nazw i wersji komponentów" },
        { en: "A spreadsheet with component name, version, and supplier columns", de: "Eine Tabelle mit Spalten für Komponentenname, Version und Anbieter", fr: "Un tableur avec des colonnes pour le nom du composant, la version et le fournisseur", it: "Un foglio di calcolo con colonne per nome del componente, versione e fornitore", es: "Una hoja de cálculo con columnas de nombre del componente, versión y proveedor", pl: "Arkusz kalkulacyjny z kolumnami nazwy komponentu, wersji i dostawcy" },
        { en: "CycloneDX JSON or SPDX JSON — formats a vulnerability scanner can parse without human intervention", de: "CycloneDX JSON oder SPDX JSON — Formate, die ein Schwachstellenscanner ohne menschliches Zutun verarbeiten kann", fr: "CycloneDX JSON ou SPDX JSON, des formats qu'un scanner de vulnérabilités peut analyser sans intervention humaine", it: "CycloneDX JSON o SPDX JSON, formati che uno scanner di vulnerabilità può analizzare senza intervento umano", es: "CycloneDX JSON o SPDX JSON, formatos que un escáner de vulnerabilidades puede analizar sin intervención humana", pl: "CycloneDX JSON lub SPDX JSON, formaty, które skaner podatności może przetworzyć bez udziału człowieka" },
        { en: "Any file that lists component names alphabetically", de: "Jede Datei, die Komponentennamen alphabetisch auflistet", fr: "Tout fichier qui répertorie les noms des composants par ordre alphabétique", it: "Qualsiasi file che elenca i nomi dei componenti in ordine alfabetico", es: "Cualquier archivo que enumere los nombres de los componentes alfabéticamente", pl: "Dowolny plik zawierający alfabetyczną listę nazw komponentów" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Machine-readable means a tool can parse it programmatically. CycloneDX JSON and SPDX JSON both satisfy this. A PDF or spreadsheet cannot be processed by a vulnerability scanner without manual extraction.",
        de: "Maschinenlesbar bedeutet, dass ein Werkzeug es programmatisch verarbeiten kann. CycloneDX JSON und SPDX JSON erfüllen beide diese Anforderung. Ein PDF oder eine Tabelle kann von einem Schwachstellenscanner nicht ohne manuelle Extraktion verarbeitet werden.",
        fr: "Lisible par machine signifie qu'un outil peut l'analyser de manière programmatique. CycloneDX JSON et SPDX JSON satisfont tous deux à cette exigence. Un PDF ou un tableur ne peut pas être traité par un scanner de vulnérabilités sans extraction manuelle.",
        it: "Leggibile da una macchina significa che uno strumento può analizzarlo in modo programmatico. CycloneDX JSON e SPDX JSON soddisfano entrambi questo requisito. Un PDF o un foglio di calcolo non può essere elaborato da uno scanner di vulnerabilità senza estrazione manuale.",
        es: "Legible por máquina significa que una herramienta puede analizarlo de forma programática. CycloneDX JSON y SPDX JSON cumplen ambos este requisito. Un PDF o una hoja de cálculo no puede ser procesado por un escáner de vulnerabilidades sin extracción manual.",
        pl: "Odczytywalny maszynowo oznacza, że narzędzie może go przetworzyć programowo. CycloneDX JSON i SPDX JSON spełniają ten wymóg. Plik PDF ani arkusz kalkulacyjny nie mogą być przetworzone przez skaner podatności bez ręcznej ekstrakcji.",
      },
    },
  ],
});

export default quiz;
