import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.2",
  passingScore: 75,
  questions: [
    {
      id: "1.2.1",
      question: {
        en: "What is a top-level dependency?",
        de: "Was ist eine direkte Abhängigkeit (Top-Level Dependency)?",
        fr: "Qu'est-ce qu'une dépendance de premier niveau ?",
        it: "Che cos'è una dipendenza di primo livello?",
        es: "¿Qué es una dependencia de primer nivel?",
        pl: "Czym jest zależność najwyższego poziomu?",
      },
      options: [
        { en: "The most critical dependency in terms of security risk", de: "Die sicherheitskritischste Abhängigkeit", fr: "La dépendance la plus critique en termes de risque de sécurité", it: "La dipendenza più critica in termini di rischio per la sicurezza", es: "La dependencia más crítica en términos de riesgo de seguridad", pl: "Najbardziej krytyczna zależność pod względem ryzyka bezpieczeństwa" },
        { en: "A component that your code directly imports or links against", de: "Eine Komponente, die Ihr Code direkt importiert oder gegen die er verlinkt", fr: "Un composant que votre code importe ou auquel il se lie directement", it: "Un componente che il vostro codice importa o a cui si collega direttamente", es: "Un componente que su código importa o con el que enlaza directamente", pl: "Komponent, który Twój kod bezpośrednio importuje lub z którym się łączy" },
        { en: "A dependency that is shared by more than three of your top-level libraries", de: "Eine Abhängigkeit, die von mehr als drei Ihrer direkten Bibliotheken geteilt wird", fr: "Une dépendance partagée par plus de trois de vos bibliothèques de premier niveau", it: "Una dipendenza condivisa da più di tre delle vostre librerie di primo livello", es: "Una dependencia compartida por más de tres de sus bibliotecas de primer nivel", pl: "Zależność współdzielona przez więcej niż trzy Twoje biblioteki najwyższego poziomu" },
        { en: "Any component with a CVSS score above 7.0", de: "Jede Komponente mit einem CVSS-Score über 7,0", fr: "Tout composant dont le score CVSS est supérieur à 7,0", it: "Qualsiasi componente con un punteggio CVSS superiore a 7,0", es: "Cualquier componente con una puntuación CVSS superior a 7,0", pl: "Dowolny komponent z wynikiem CVSS powyżej 7,0" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A top-level dependency is one your code directly imports — listed in your own package manifest (package.json, pom.xml, requirements.txt, etc.). You chose it explicitly. CRA Article 13(5) requires the SBOM to cover at least these.",
        de: "Eine direkte Abhängigkeit ist eine, die Ihr Code direkt importiert — aufgeführt in Ihrem eigenen Paketmanifest (package.json, pom.xml, requirements.txt usw.). Sie haben sie explizit gewählt. CRA Artikel 13(5) verlangt, dass die SBOM mindestens diese abdeckt.",
        fr: "Une dépendance de premier niveau est celle que votre code importe directement, répertoriée dans votre propre manifeste de paquet (package.json, pom.xml, requirements.txt, etc.). Vous l'avez choisie explicitement. L'article 13(5) CRA exige que la SBOM couvre au moins celles-ci.",
        it: "Una dipendenza di primo livello è quella che il vostro codice importa direttamente, elencata nel vostro manifesto di pacchetto (package.json, pom.xml, requirements.txt, ecc.). L'avete scelta esplicitamente. L'articolo 13(5) CRA richiede che la SBOM copra almeno queste.",
        es: "Una dependencia de primer nivel es la que su código importa directamente, enumerada en su propio manifiesto de paquete (package.json, pom.xml, requirements.txt, etc.). La eligió explícitamente. El artículo 13(5) CRA exige que la SBOM cubra al menos estas.",
        pl: "Zależność najwyższego poziomu to taka, którą Twój kod bezpośrednio importuje, wymieniona we własnym manifeście pakietu (package.json, pom.xml, requirements.txt itd.). Wybrałeś ją w sposób wyraźny. Artykuł 13(5) CRA wymaga, aby SBOM obejmował co najmniej te zależności.",
      },
    },
    {
      id: "1.2.2",
      question: {
        en: "Log4Shell (CVE-2021-44228) affected thousands of applications whose developers had never directly imported log4j-core. What does this illustrate?",
        de: "Log4Shell (CVE-2021-44228) betraf Tausende von Anwendungen, deren Entwickler log4j-core nie direkt importiert hatten. Was verdeutlicht dies?",
        fr: "Log4Shell (CVE-2021-44228) a affecté des milliers d'applications dont les développeurs n'avaient jamais importé directement log4j-core. Qu'est-ce que cela illustre ?",
        it: "Log4Shell (CVE-2021-44228) ha colpito migliaia di applicazioni i cui sviluppatori non avevano mai importato direttamente log4j-core. Che cosa illustra questo?",
        es: "Log4Shell (CVE-2021-44228) afectó a miles de aplicaciones cuyos desarrolladores nunca habían importado directamente log4j-core. ¿Qué ilustra esto?",
        pl: "Log4Shell (CVE-2021-44228) dotknął tysiące aplikacji, których deweloperzy nigdy bezpośrednio nie importowali log4j-core. Co to ilustruje?",
      },
      options: [
        { en: "That CVE scores overestimate real-world risk", de: "Dass CVE-Scores das Risiko in der Praxis überschätzen", fr: "Que les scores CVE surestiment le risque réel", it: "Che i punteggi CVE sovrastimano il rischio reale", es: "Que las puntuaciones CVE sobrestiman el riesgo real", pl: "Że wyniki CVE zawyżają rzeczywiste ryzyko" },
        { en: "That top-level-only SBOMs fail to reveal transitive vulnerability exposure", de: "Dass rein auf direkten Abhängigkeiten basierende SBOMs die transitive Schwachstellenexposition nicht aufdecken", fr: "Que les SBOM limitées au premier niveau ne révèlent pas l'exposition transitive aux vulnérabilités", it: "Che le SBOM limitate al primo livello non rivelano l'esposizione transitiva alle vulnerabilità", es: "Que las SBOM limitadas al primer nivel no revelan la exposición transitiva a vulnerabilidades", pl: "Że SBOM obejmujące tylko najwyższy poziom nie ujawniają tranzytywnego narażenia na podatności" },
        { en: "That Java applications are inherently less secure", de: "Dass Java-Anwendungen von Natur aus unsicherer sind", fr: "Que les applications Java sont intrinsèquement moins sûres", it: "Che le applicazioni Java sono intrinsecamente meno sicure", es: "Que las aplicaciones Java son intrínsecamente menos seguras", pl: "Że aplikacje Java są z natury mniej bezpieczne" },
        { en: "That dependency scanning tools were not available before 2021", de: "Dass Abhängigkeitsscanner vor 2021 nicht verfügbar waren", fr: "Que les outils d'analyse des dépendances n'étaient pas disponibles avant 2021", it: "Che gli strumenti di scansione delle dipendenze non erano disponibili prima del 2021", es: "Que las herramientas de análisis de dependencias no estaban disponibles antes de 2021", pl: "Że narzędzia do skanowania zależności nie były dostępne przed 2021 rokiem" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Log4Shell was a transitive dependency — pulled in by a library that was itself a dependency. Teams with top-level-only SBOMs had no record of log4j-core and could not quickly determine whether they were affected. Full transitive SBOMs answered the question in a single scanner run.",
        de: "Log4Shell war eine transitive Abhängigkeit — eingebunden durch eine Bibliothek, die selbst eine Abhängigkeit war. Teams mit reinen Top-Level-SBOMs hatten keinen Eintrag für log4j-core und konnten nicht schnell feststellen, ob sie betroffen waren. Vollständige transitive SBOMs beantworteten die Frage in einem einzigen Scanner-Durchlauf.",
        fr: "Log4Shell était une dépendance transitive, introduite par une bibliothèque qui était elle-même une dépendance. Les équipes disposant de SBOM limitées au premier niveau n'avaient aucune trace de log4j-core et ne pouvaient pas déterminer rapidement si elles étaient affectées. Des SBOM transitives complètes ont répondu à la question en une seule exécution du scanner.",
        it: "Log4Shell era una dipendenza transitiva, introdotta da una libreria che era essa stessa una dipendenza. I team con SBOM limitate al primo livello non avevano alcuna registrazione di log4j-core e non potevano determinare rapidamente se fossero interessati. Le SBOM transitive complete hanno risposto alla domanda in una sola esecuzione dello scanner.",
        es: "Log4Shell era una dependencia transitiva, incorporada por una biblioteca que era a su vez una dependencia. Los equipos con SBOM limitadas al primer nivel no tenían registro de log4j-core y no podían determinar rápidamente si estaban afectados. Las SBOM transitivas completas respondieron a la pregunta en una sola ejecución del escáner.",
        pl: "Log4Shell był zależnością tranzytywną, wciągniętą przez bibliotekę, która sama była zależnością. Zespoły z SBOM obejmującymi tylko najwyższy poziom nie miały wpisu dla log4j-core i nie mogły szybko ustalić, czy są narażone. Pełne tranzytywne SBOM odpowiedziały na to pytanie w jednym przebiegu skanera.",
      },
    },
    {
      id: "1.2.3",
      question: {
        en: "What does the CRA Article 13(5) require as the minimum scope for SBOM coverage?",
        de: "Was verlangt CRA Artikel 13(5) als Mindestumfang der SBOM-Abdeckung?",
        fr: "Quelle est l'étendue minimale de couverture de la SBOM exigée par l'article 13(5) CRA ?",
        it: "Quale ambito minimo di copertura della SBOM richiede l'articolo 13(5) CRA?",
        es: "¿Qué alcance mínimo de cobertura de la SBOM exige el artículo 13(5) CRA?",
        pl: "Jaki minimalny zakres pokrycia SBOM wymaga artykuł 13(5) CRA?",
      },
      options: [
        { en: "All components including OS packages and transitive dependencies at every level", de: "Alle Komponenten einschließlich OS-Paketen und transitiver Abhängigkeiten auf jeder Ebene", fr: "Tous les composants, y compris les paquets du système d'exploitation et les dépendances transitives à tous les niveaux", it: "Tutti i componenti, compresi i pacchetti del sistema operativo e le dipendenze transitive a ogni livello", es: "Todos los componentes, incluidos los paquetes del sistema operativo y las dependencias transitivas en todos los niveles", pl: "Wszystkie komponenty, w tym pakiety systemu operacyjnego i zależności tranzytywne na każdym poziomie" },
        { en: "Only components with a CVSS severity of High or Critical", de: "Nur Komponenten mit einem CVSS-Schweregrad von Hoch oder Kritisch", fr: "Uniquement les composants dont la gravité CVSS est élevée ou critique", it: "Solo i componenti con gravità CVSS alta o critica", es: "Solo los componentes con una gravedad CVSS alta o crítica", pl: "Tylko komponenty o wadze CVSS wysokiej lub krytycznej" },
        { en: "At least the top-level dependencies", de: "Mindestens die direkten Abhängigkeiten", fr: "Au moins les dépendances de premier niveau", it: "Almeno le dipendenze di primo livello", es: "Al menos las dependencias de primer nivel", pl: "Co najmniej zależności najwyższego poziomu" },
        { en: "Only components that have had a CVE published in the last 12 months", de: "Nur Komponenten, für die in den letzten 12 Monaten eine CVE veröffentlicht wurde", fr: "Uniquement les composants pour lesquels une CVE a été publiée au cours des 12 derniers mois", it: "Solo i componenti per i quali è stata pubblicata una CVE negli ultimi 12 mesi", es: "Solo los componentes para los que se ha publicado una CVE en los últimos 12 meses", pl: "Tylko komponenty, dla których w ciągu ostatnich 12 miesięcy opublikowano CVE" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Article 13(5) CRA requires the SBOM to cover 'at least the top-level dependencies.' This is the legal minimum. Best practice and most SBOM tooling goes further and covers the full transitive tree.",
        de: "Artikel 13(5) CRA verlangt, dass die SBOM 'mindestens die direkten Abhängigkeiten' abdeckt. Dies ist das gesetzliche Minimum. Best Practice und die meisten SBOM-Werkzeuge gehen weiter und decken den vollständigen transitiven Baum ab.",
        fr: "L'article 13(5) CRA exige que la SBOM couvre « au moins les dépendances de premier niveau ». Il s'agit du minimum légal. Les bonnes pratiques et la plupart des outils SBOM vont plus loin et couvrent l'arbre transitif complet.",
        it: "L'articolo 13(5) CRA richiede che la SBOM copra « almeno le dipendenze di primo livello ». Questo è il minimo legale. Le buone pratiche e la maggior parte degli strumenti SBOM vanno oltre e coprono l'intero albero transitivo.",
        es: "El artículo 13(5) CRA exige que la SBOM cubra « al menos las dependencias de primer nivel ». Este es el mínimo legal. Las buenas prácticas y la mayoría de las herramientas SBOM van más allá y cubren el árbol transitivo completo.",
        pl: "Artykuł 13(5) CRA wymaga, aby SBOM obejmował « co najmniej zależności najwyższego poziomu ». Jest to minimum prawne. Dobre praktyki i większość narzędzi SBOM idą dalej i obejmują pełne drzewo tranzytywne.",
      },
    },
    {
      id: "1.2.4",
      question: {
        en: "Why do most SBOM tools (Syft, cdxgen) produce full transitive output by default?",
        de: "Warum liefern die meisten SBOM-Werkzeuge (Syft, cdxgen) standardmäßig vollständige transitive Ausgaben?",
        fr: "Pourquoi la plupart des outils SBOM (Syft, cdxgen) produisent-ils une sortie transitive complète par défaut ?",
        it: "Perché la maggior parte degli strumenti SBOM (Syft, cdxgen) produce per impostazione predefinita un output transitivo completo?",
        es: "¿Por qué la mayoría de las herramientas SBOM (Syft, cdxgen) producen una salida transitiva completa de forma predeterminada?",
        pl: "Dlaczego większość narzędzi SBOM (Syft, cdxgen) domyślnie generuje pełny wynik tranzytywny?",
      },
      options: [
        { en: "Because EU regulations require it for all product categories", de: "Weil EU-Vorschriften dies für alle Produktkategorien verlangen", fr: "Parce que la réglementation de l'UE l'exige pour toutes les catégories de produits", it: "Perché la normativa dell'UE lo richiede per tutte le categorie di prodotti", es: "Porque la normativa de la UE lo exige para todas las categorías de productos", pl: "Ponieważ przepisy UE wymagają tego dla wszystkich kategorii produktów" },
        { en: "Because full transitive coverage is best practice for vulnerability monitoring, and there is no technical cost argument for stopping at top-level when the tools do not", de: "Weil vollständige transitive Abdeckung Best Practice für die Schwachstellenüberwachung ist und es kein technisches Kostenargument gibt, bei direkten Abhängigkeiten zu stoppen, wenn die Werkzeuge es nicht tun", fr: "Parce que la couverture transitive complète est une bonne pratique pour la surveillance des vulnérabilités, et qu'il n'y a aucun argument de coût technique pour s'arrêter au premier niveau alors que les outils ne le font pas", it: "Perché la copertura transitiva completa è una buona pratica per il monitoraggio delle vulnerabilità e non esiste alcun argomento di costo tecnico per fermarsi al primo livello quando gli strumenti non lo fanno", es: "Porque la cobertura transitiva completa es una buena práctica para la supervisión de vulnerabilidades, y no existe ningún argumento de coste técnico para detenerse en el primer nivel cuando las herramientas no lo hacen", pl: "Ponieważ pełne pokrycie tranzytywne to dobra praktyka monitorowania podatności, a nie ma technicznego argumentu kosztowego, by zatrzymywać się na najwyższym poziomie, skoro narzędzia tego nie robią" },
        { en: "Because transitive dependencies change more frequently than top-level ones", de: "Weil transitive Abhängigkeiten häufiger wechseln als direkte", fr: "Parce que les dépendances transitives changent plus fréquemment que celles de premier niveau", it: "Perché le dipendenze transitive cambiano più frequentemente di quelle di primo livello", es: "Porque las dependencias transitivas cambian con más frecuencia que las de primer nivel", pl: "Ponieważ zależności tranzytywne zmieniają się częściej niż te najwyższego poziomu" },
        { en: "Because VEX statements are only valid for transitive dependencies", de: "Weil VEX-Aussagen nur für transitive Abhängigkeiten gültig sind", fr: "Parce que les déclarations VEX ne sont valables que pour les dépendances transitives", it: "Perché le dichiarazioni VEX sono valide solo per le dipendenze transitive", es: "Porque las declaraciones VEX solo son válidas para las dependencias transitivas", pl: "Ponieważ oświadczenia VEX są ważne tylko dla zależności tranzytywnych" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Tools like Syft read the full dependency tree from package lock files and container image layer metadata. Stopping at top-level would require extra configuration to strip information. Full transitive output is best practice and the default — do not override it.",
        de: "Werkzeuge wie Syft lesen den vollständigen Abhängigkeitsbaum aus Package-Lock-Dateien und Container-Image-Layer-Metadaten. Das Stoppen bei direkten Abhängigkeiten würde eine zusätzliche Konfiguration erfordern, um Informationen zu entfernen. Vollständige transitive Ausgabe ist Best Practice und die Voreinstellung — überschreiben Sie sie nicht.",
        fr: "Des outils comme Syft lisent l'arbre de dépendances complet à partir des fichiers de verrouillage de paquets et des métadonnées des couches d'image de conteneur. S'arrêter au premier niveau nécessiterait une configuration supplémentaire pour retirer des informations. La sortie transitive complète est une bonne pratique et le réglage par défaut : ne la remplacez pas.",
        it: "Strumenti come Syft leggono l'intero albero delle dipendenze dai file di lock dei pacchetti e dai metadati dei layer dell'immagine del container. Fermarsi al primo livello richiederebbe una configurazione aggiuntiva per rimuovere informazioni. L'output transitivo completo è una buona pratica ed è l'impostazione predefinita: non sovrascrivetela.",
        es: "Herramientas como Syft leen el árbol de dependencias completo a partir de los archivos de bloqueo de paquetes y los metadatos de las capas de la imagen del contenedor. Detenerse en el primer nivel requeriría configuración adicional para eliminar información. La salida transitiva completa es una buena práctica y la opción predeterminada: no la anule.",
        pl: "Narzędzia takie jak Syft odczytują pełne drzewo zależności z plików blokad pakietów oraz metadanych warstw obrazu kontenera. Zatrzymanie się na najwyższym poziomie wymagałoby dodatkowej konfiguracji w celu usunięcia informacji. Pełny wynik tranzytywny to dobra praktyka i ustawienie domyślne: nie nadpisuj go.",
      },
    },
    {
      id: "1.2.5",
      question: {
        en: "What is required to attach a VEX 'not_affected' statement for a CVE in a transitive dependency?",
        de: "Was ist erforderlich, um eine VEX-'not_affected'-Aussage für eine CVE in einer transitiven Abhängigkeit anzuhängen?",
        fr: "Que faut-il pour attacher une déclaration VEX « not_affected » à une CVE dans une dépendance transitive ?",
        it: "Che cosa è necessario per allegare una dichiarazione VEX « not_affected » a una CVE in una dipendenza transitiva?",
        es: "¿Qué se requiere para adjuntar una declaración VEX « not_affected » a una CVE en una dependencia transitiva?",
        pl: "Co jest wymagane, aby dołączyć oświadczenie VEX « not_affected » dla CVE w zależności tranzytywnej?",
      },
      options: [
        { en: "The CVE must have a CVSS score below 7.0", de: "Die CVE muss einen CVSS-Score unter 7,0 haben", fr: "La CVE doit avoir un score CVSS inférieur à 7,0", it: "La CVE deve avere un punteggio CVSS inferiore a 7,0", es: "La CVE debe tener una puntuación CVSS inferior a 7,0", pl: "CVE musi mieć wynik CVSS poniżej 7,0" },
        { en: "The transitive component must be present in the SBOM", de: "Die transitive Komponente muss in der SBOM vorhanden sein", fr: "Le composant transitif doit être présent dans la SBOM", it: "Il componente transitivo deve essere presente nella SBOM", es: "El componente transitivo debe estar presente en la SBOM", pl: "Komponent tranzytywny musi być obecny w SBOM" },
        { en: "The component must be a top-level dependency", de: "Die Komponente muss eine direkte Abhängigkeit sein", fr: "Le composant doit être une dépendance de premier niveau", it: "Il componente deve essere una dipendenza di primo livello", es: "El componente debe ser una dependencia de primer nivel", pl: "Komponent musi być zależnością najwyższego poziomu" },
        { en: "The CVE must not yet appear in the NVD", de: "Die CVE darf noch nicht in der NVD erscheinen", fr: "La CVE ne doit pas encore figurer dans la NVD", it: "La CVE non deve ancora comparire nella NVD", es: "La CVE no debe figurar todavía en la NVD", pl: "CVE nie może jeszcze figurować w NVD" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A VEX statement is attached to a specific component entry in the SBOM. If the transitive component is not listed in the SBOM, there is no entry to attach the VEX statement to. This means you cannot formally document 'not affected' decisions for CVEs in dependencies your SBOM does not cover.",
        de: "Eine VEX-Aussage wird an einen bestimmten Komponenteneintrag in der SBOM angehängt. Wenn die transitive Komponente nicht in der SBOM aufgeführt ist, gibt es keinen Eintrag, an den die VEX-Aussage angehängt werden kann. Das bedeutet, dass Sie 'not affected'-Entscheidungen für CVEs in Abhängigkeiten, die Ihre SBOM nicht abdeckt, nicht formal dokumentieren können.",
        fr: "Une déclaration VEX est attachée à une entrée de composant précise dans la SBOM. Si le composant transitif n'est pas répertorié dans la SBOM, il n'y a aucune entrée à laquelle attacher la déclaration VEX. Cela signifie que vous ne pouvez pas documenter formellement des décisions « not affected » pour des CVE dans des dépendances que votre SBOM ne couvre pas.",
        it: "Una dichiarazione VEX è allegata a una voce di componente specifica nella SBOM. Se il componente transitivo non è elencato nella SBOM, non esiste alcuna voce a cui allegare la dichiarazione VEX. Ciò significa che non è possibile documentare formalmente decisioni « not affected » per CVE in dipendenze che la vostra SBOM non copre.",
        es: "Una declaración VEX se adjunta a una entrada de componente concreta en la SBOM. Si el componente transitivo no figura en la SBOM, no hay ninguna entrada a la que adjuntar la declaración VEX. Esto significa que no puede documentar formalmente decisiones « not affected » para CVE en dependencias que su SBOM no cubre.",
        pl: "Oświadczenie VEX jest dołączane do konkretnego wpisu komponentu w SBOM. Jeśli komponent tranzytywny nie figuruje w SBOM, nie ma wpisu, do którego można by dołączyć oświadczenie VEX. Oznacza to, że nie możesz formalnie udokumentować decyzji « not affected » dla CVE w zależnościach, których Twój SBOM nie obejmuje.",
      },
    },
  ],
});

export default quiz;
