import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.3",
  passingScore: 75,
  questions: [
    {
      id: "1.3.1",
      question: {
        en: "What is the minimum retention period for the SBOM under CRA Article 31?",
        de: "Wie lang ist die Mindestaufbewahrungspflicht für die SBOM gemäß CRA Artikel 31?",
        fr: "Quelle est la durée minimale de conservation de la SBOM au titre de l'article 31 CRA ?",
        it: "Qual è il periodo minimo di conservazione della SBOM ai sensi dell'articolo 31 CRA?",
        es: "¿Cuál es el período mínimo de conservación de la SBOM conforme al artículo 31 CRA?",
        pl: "Jaki jest minimalny okres przechowywania SBOM zgodnie z artykułem 31 CRA?",
        cs: "Jaká je minimální doba uchovávání SBOM podle článku 31 CRA?",
        pt: "Qual é o período mínimo de conservação do SBOM ao abrigo do artigo 31 CRA?",
        ro: "Care este perioada minimă de păstrare a SBOM în temeiul articolului 31 CRA?",
      },
      options: [
        { en: "5 years after first placement on the market", de: "5 Jahre nach erstmaligem Inverkehrbringen", fr: "5 ans après la première mise sur le marché", it: "5 anni dopo la prima immissione sul mercato", es: "5 años después de la primera introducción en el mercado", pl: "5 lat po pierwszym wprowadzeniu do obrotu", cs: "5 let po prvním uvedení na trh", pt: "5 anos após a primeira colocação no mercado", ro: "5 ani de la prima introducere pe piață" },
        { en: "10 years after first placement on the market, or for the support period, whichever is longer", de: "10 Jahre nach erstmaligem Inverkehrbringen oder für die Unterstützungsdauer, je nachdem, was länger ist", fr: "10 ans après la première mise sur le marché, ou pendant la période de support, selon la durée la plus longue", it: "10 anni dopo la prima immissione sul mercato, oppure per il periodo di supporto, se più lungo", es: "10 años después de la primera introducción en el mercado, o durante el período de soporte, lo que sea más largo", pl: "10 lat po pierwszym wprowadzeniu do obrotu lub przez okres wsparcia, w zależności od tego, który okres jest dłuższy", cs: "10 let po prvním uvedení na trh, nebo po dobu podpory, podle toho, co je delší", pt: "10 anos após a primeira colocação no mercado, ou durante o período de suporte, consoante o que for mais longo", ro: "10 ani de la prima introducere pe piață sau pe durata perioadei de suport, oricare dintre acestea este mai lungă" },
        { en: "3 years, or until a new product version is released", de: "3 Jahre oder bis eine neue Produktversion veröffentlicht wird", fr: "3 ans, ou jusqu'à la publication d'une nouvelle version du produit", it: "3 anni, oppure fino al rilascio di una nuova versione del prodotto", es: "3 años, o hasta que se publique una nueva versión del producto", pl: "3 lata lub do wydania nowej wersji produktu", cs: "3 roky, nebo dokud není vydána nová verze produktu", pt: "3 anos, ou até ao lançamento de uma nova versão do produto", ro: "3 ani sau până la lansarea unei noi versiuni a produsului" },
        { en: "7 years after the product is withdrawn from the market", de: "7 Jahre nach dem Rückzug des Produkts vom Markt", fr: "7 ans après le retrait du produit du marché", it: "7 anni dopo il ritiro del prodotto dal mercato", es: "7 años después de la retirada del producto del mercado", pl: "7 lat po wycofaniu produktu z rynku", cs: "7 let po stažení produktu z trhu", pt: "7 anos após a retirada do produto do mercado", ro: "7 ani de la retragerea produsului de pe piață" },
      ],
      correctIndex: 1,
      explanation: {
        en: "CRA Article 31(3) requires technical documentation to be kept for 10 years after the product is placed on the market, or for the support period, whichever is longer. For long-lived industrial products, the support period may exceed 10 years.",
        de: "CRA Artikel 31(3) verlangt, dass technische Dokumentation 10 Jahre nach Inverkehrbringen oder für die Unterstützungsdauer aufbewahrt wird, je nachdem, was länger ist. Bei langlebigen Industrieprodukten kann die Unterstützungsdauer 10 Jahre überschreiten.",
        fr: "L'article 31(3) CRA exige que la documentation technique soit conservée pendant 10 ans après la mise sur le marché du produit, ou pendant la période de support, selon la durée la plus longue. Pour les produits industriels à longue durée de vie, la période de support peut dépasser 10 ans.",
        it: "L'articolo 31(3) CRA richiede che la documentazione tecnica sia conservata per 10 anni dopo l'immissione del prodotto sul mercato, oppure per il periodo di supporto, se più lungo. Per i prodotti industriali a lunga durata, il periodo di supporto può superare i 10 anni.",
        es: "El artículo 31(3) CRA exige que la documentación técnica se conserve durante 10 años después de la introducción del producto en el mercado, o durante el período de soporte, lo que sea más largo. Para los productos industriales de larga duración, el período de soporte puede superar los 10 años.",
        pl: "Artykuł 31(3) CRA wymaga przechowywania dokumentacji technicznej przez 10 lat po wprowadzeniu produktu do obrotu lub przez okres wsparcia, w zależności od tego, który okres jest dłuższy. W przypadku długowiecznych produktów przemysłowych okres wsparcia może przekroczyć 10 lat.",
        cs: "Článek 31(3) CRA vyžaduje, aby technická dokumentace byla uchovávána 10 let po uvedení produktu na trh, nebo po dobu podpory, podle toho, co je delší. U dlouhověkých průmyslových produktů může doba podpory přesáhnout 10 let.",
        pt: "O artigo 31(3) CRA exige que a documentação técnica seja conservada durante 10 anos após a colocação do produto no mercado, ou durante o período de suporte, consoante o que for mais longo. Para produtos industriais de longa duração, o período de suporte pode exceder 10 anos.",
        ro: "Articolul 31(3) CRA impune ca documentația tehnică să fie păstrată timp de 10 ani de la introducerea produsului pe piață sau pe durata perioadei de suport, oricare dintre acestea este mai lungă. Pentru produsele industriale de lungă durată, perioada de suport poate depăși 10 ani.",
      },
    },
    {
      id: "1.3.2",
      question: {
        en: "Who can request the technical documentation, including the SBOM, under CRA Article 31?",
        de: "Wer kann die technische Dokumentation, einschließlich der SBOM, gemäß CRA Artikel 31 anfordern?",
        fr: "Qui peut demander la documentation technique, y compris la SBOM, au titre de l'article 31 CRA ?",
        it: "Chi può richiedere la documentazione tecnica, compresa la SBOM, ai sensi dell'articolo 31 CRA?",
        es: "¿Quién puede solicitar la documentación técnica, incluida la SBOM, conforme al artículo 31 CRA?",
        pl: "Kto może zażądać dokumentacji technicznej, w tym SBOM, zgodnie z artykułem 31 CRA?",
        cs: "Kdo si může vyžádat technickou dokumentaci, včetně SBOM, podle článku 31 CRA?",
        pt: "Quem pode solicitar a documentação técnica, incluindo o SBOM, ao abrigo do artigo 31 CRA?",
        ro: "Cine poate solicita documentația tehnică, inclusiv SBOM, în temeiul articolului 31 CRA?",
      },
      options: [
        { en: "Any member of the public who can demonstrate a security interest", de: "Jede Person der Öffentlichkeit, die ein Sicherheitsinteresse nachweisen kann", fr: "Tout membre du public pouvant démontrer un intérêt en matière de sécurité", it: "Qualsiasi membro del pubblico che possa dimostrare un interesse in materia di sicurezza", es: "Cualquier miembro del público que pueda demostrar un interés en materia de seguridad", pl: "Każdy członek społeczeństwa, który może wykazać interes w zakresie bezpieczeństwa", cs: "Kterýkoli člen veřejnosti, který může prokázat bezpečnostní zájem", pt: "Qualquer membro do público que possa demonstrar um interesse em matéria de segurança", ro: "Orice membru al publicului care poate demonstra un interes în materie de securitate" },
        { en: "Only the manufacturer's customers under GDPR data access rights", de: "Nur die Kunden des Herstellers gemäß DSGVO-Datenzugriffsrechten", fr: "Uniquement les clients du fabricant au titre des droits d'accès aux données du GDPR", it: "Solo i clienti del fabbricante in virtù dei diritti di accesso ai dati del GDPR", es: "Solo los clientes del fabricante en virtud de los derechos de acceso a los datos del GDPR", pl: "Tylko klienci producenta na podstawie praw dostępu do danych GDPR", cs: "Pouze zákazníci výrobce na základě práv na přístup k údajům podle GDPR", pt: "Apenas os clientes do fabricante ao abrigo dos direitos de acesso aos dados do GDPR", ro: "Doar clienții fabricantului în temeiul drepturilor de acces la date prevăzute de GDPR" },
        { en: "National market surveillance authorities", de: "Nationale Marktüberwachungsbehörden", fr: "Les autorités nationales de surveillance du marché", it: "Le autorità nazionali di vigilanza del mercato", es: "Las autoridades nacionales de vigilancia del mercado", pl: "Krajowe organy nadzoru rynku", cs: "Vnitrostátní orgány dozoru nad trhem", pt: "As autoridades nacionais de fiscalização do mercado", ro: "Autoritățile naționale de supraveghere a pieței" },
        { en: "ENISA and the European Commission only", de: "Nur ENISA und die Europäische Kommission", fr: "Uniquement l'ENISA et la Commission européenne", it: "Solo l'ENISA e la Commissione europea", es: "Solo la ENISA y la Comisión Europea", pl: "Tylko ENISA i Komisja Europejska", cs: "Pouze ENISA a Evropská komise", pt: "Apenas a ENISA e a Comissão Europeia", ro: "Doar ENISA și Comisia Europeană" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Market surveillance authorities (national bodies such as the BSI in Germany) can request technical documentation at any time. The SBOM is not a public document and does not have to be made available to customers or the general public.",
        de: "Marktüberwachungsbehörden (nationale Stellen wie das BSI in Deutschland) können die technische Dokumentation jederzeit anfordern. Die SBOM ist kein öffentliches Dokument und muss weder Kunden noch der allgemeinen Öffentlichkeit zugänglich gemacht werden.",
        fr: "Les autorités de surveillance du marché, organismes nationaux tels que le BSI en Allemagne, peuvent demander la documentation technique à tout moment. La SBOM n'est pas un document public et n'a pas à être mise à la disposition des clients ni du grand public.",
        it: "Le autorità di vigilanza del mercato, organismi nazionali come il BSI in Germania, possono richiedere la documentazione tecnica in qualsiasi momento. La SBOM non è un documento pubblico e non deve essere messa a disposizione dei clienti né del pubblico in generale.",
        es: "Las autoridades de vigilancia del mercado, organismos nacionales como el BSI en Alemania, pueden solicitar la documentación técnica en cualquier momento. La SBOM no es un documento público y no tiene que ponerse a disposición de los clientes ni del público en general.",
        pl: "Organy nadzoru rynku, krajowe instytucje takie jak BSI w Niemczech, mogą w każdej chwili zażądać dokumentacji technicznej. SBOM nie jest dokumentem publicznym i nie musi być udostępniany klientom ani ogółowi społeczeństwa.",
        cs: "Orgány dozoru nad trhem, vnitrostátní subjekty jako BSI v Německu, si mohou technickou dokumentaci vyžádat kdykoli. SBOM není veřejný dokument a nemusí být zpřístupněn zákazníkům ani široké veřejnosti.",
        pt: "As autoridades de fiscalização do mercado, organismos nacionais como o BSI na Alemanha, podem solicitar a documentação técnica a qualquer momento. O SBOM não é um documento público e não tem de ser disponibilizado aos clientes nem ao público em geral.",
        ro: "Autoritățile de supraveghere a pieței, organisme naționale precum BSI din Germania, pot solicita documentația tehnică în orice moment. SBOM nu este un document public și nu trebuie pus la dispoziția clienților sau a publicului larg.",
      },
    },
    {
      id: "1.3.3",
      question: {
        en: "A manufacturer releases 20 security patches for a product over three years. How many SBOMs must be retained?",
        de: "Ein Hersteller veröffentlicht über drei Jahre hinweg 20 Sicherheits-Patches für ein Produkt. Wie viele SBOMs müssen aufbewahrt werden?",
        fr: "Un fabricant publie 20 correctifs de sécurité pour un produit sur trois ans. Combien de SBOM doivent être conservées ?",
        it: "Un fabbricante rilascia 20 patch di sicurezza per un prodotto nell'arco di tre anni. Quante SBOM devono essere conservate?",
        es: "Un fabricante publica 20 parches de seguridad para un producto a lo largo de tres años. ¿Cuántas SBOM deben conservarse?",
        pl: "Producent wydaje 20 poprawek bezpieczeństwa dla produktu w ciągu trzech lat. Ile SBOM musi zostać zachowanych?",
        cs: "Výrobce vydá za tři roky 20 bezpečnostních záplat pro produkt. Kolik SBOM musí být uchováno?",
        pt: "Um fabricante lança 20 correções de segurança para um produto ao longo de três anos. Quantos SBOM têm de ser conservados?",
        ro: "Un fabricant lansează 20 de corecții de securitate pentru un produs pe parcursul a trei ani. Câte SBOM trebuie păstrate?",
      },
      options: [
        { en: "Only the latest SBOM needs to be retained", de: "Nur die aktuelle SBOM muss aufbewahrt werden", fr: "Seule la dernière SBOM doit être conservée", it: "Deve essere conservata solo la SBOM più recente", es: "Solo debe conservarse la SBOM más reciente", pl: "Należy zachować tylko najnowszy SBOM", cs: "Stačí uchovat pouze nejnovější SBOM", pt: "Só é necessário conservar o SBOM mais recente", ro: "Trebuie păstrat doar cel mai recent SBOM" },
        { en: "One SBOM per year is sufficient", de: "Eine SBOM pro Jahr ist ausreichend", fr: "Une SBOM par an suffit", it: "Una SBOM all'anno è sufficiente", es: "Una SBOM al año es suficiente", pl: "Jeden SBOM rocznie wystarczy", cs: "Jeden SBOM ročně postačuje", pt: "Um SBOM por ano é suficiente", ro: "Un SBOM pe an este suficient" },
        { en: "An SBOM for each release version, 20 SBOMs in this case", de: "Eine SBOM für jede Release-Version, in diesem Fall 20 SBOMs", fr: "Une SBOM pour chaque version publiée, soit 20 SBOM dans ce cas", it: "Una SBOM per ogni versione rilasciata, ovvero 20 SBOM in questo caso", es: "Una SBOM por cada versión publicada, es decir, 20 SBOM en este caso", pl: "Jeden SBOM dla każdej wydanej wersji, czyli 20 SBOM w tym przypadku", cs: "Jeden SBOM pro každou vydanou verzi, v tomto případě 20 SBOM", pt: "Um SBOM por cada versão lançada, ou seja, 20 SBOM neste caso", ro: "Câte un SBOM pentru fiecare versiune lansată, adică 20 de SBOM în acest caz" },
        { en: "SBOMs only need to be retained for the final version of the product", de: "SBOMs müssen nur für die letzte Version des Produkts aufbewahrt werden", fr: "Les SBOM ne doivent être conservées que pour la version finale du produit", it: "Le SBOM devono essere conservate solo per la versione finale del prodotto", es: "Las SBOM solo deben conservarse para la versión final del producto", pl: "SBOM należy zachować tylko dla ostatniej wersji produktu", cs: "SBOM je třeba uchovat pouze pro konečnou verzi produktu", pt: "Os SBOM só têm de ser conservados para a versão final do produto", ro: "SBOM trebuie păstrate doar pentru versiunea finală a produsului" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Each released version has its own component inventory. A market surveillance authority investigating a vulnerability from three years ago wants the SBOM from the version that was in the market at that time. Retain one SBOM per release, linked to that release's version and build.",
        de: "Jede veröffentlichte Version hat ihr eigenes Komponenteninventar. Eine Marktüberwachungsbehörde, die eine Schwachstelle von vor drei Jahren untersucht, möchte die SBOM der Version, die zu diesem Zeitpunkt auf dem Markt war. Bewahren Sie eine SBOM pro Release auf, verknüpft mit der Version und dem Build dieses Releases.",
        fr: "Chaque version publiée a son propre inventaire de composants. Une autorité de surveillance du marché enquêtant sur une vulnérabilité datant de trois ans veut la SBOM de la version qui était sur le marché à ce moment-là. Conservez une SBOM par version, liée à la version et à la build de cette publication.",
        it: "Ogni versione rilasciata ha il proprio inventario dei componenti. Un'autorità di vigilanza del mercato che indaga su una vulnerabilità di tre anni fa vuole la SBOM della versione che era sul mercato in quel momento. Conservate una SBOM per ogni rilascio, collegata alla versione e alla build di quel rilascio.",
        es: "Cada versión publicada tiene su propio inventario de componentes. Una autoridad de vigilancia del mercado que investiga una vulnerabilidad de hace tres años quiere la SBOM de la versión que estaba en el mercado en ese momento. Conserve una SBOM por cada versión, vinculada a la versión y a la compilación de esa publicación.",
        pl: "Każda wydana wersja ma własny inwentarz komponentów. Organ nadzoru rynku badający podatność sprzed trzech lat chce uzyskać SBOM wersji, która była wówczas na rynku. Zachowuj jeden SBOM na każde wydanie, powiązany z wersją i kompilacją tego wydania.",
        cs: "Každá vydaná verze má svůj vlastní inventář komponent. Orgán dozoru nad trhem, který vyšetřuje zranitelnost spred tří let, chce SBOM verze, jež byla v té době na trhu. Uchovávejte jeden SBOM na vydání, propojený s verzí a sestavením daného vydání.",
        pt: "Cada versão lançada tem o seu próprio inventário de componentes. Uma autoridade de fiscalização do mercado que investiga uma vulnerabilidade de há três anos quer o SBOM da versão que estava no mercado nessa altura. Conserve um SBOM por cada lançamento, associado à versão e à compilação desse lançamento.",
        ro: "Fiecare versiune lansată are propriul inventar de componente. O autoritate de supraveghere a pieței care investighează o vulnerabilitate de acum trei ani dorește SBOM al versiunii care se afla pe piață în acel moment. Păstrați câte un SBOM pentru fiecare lansare, asociat cu versiunea și compilarea acelei lansări.",
      },
    },
    {
      id: "1.3.4",
      question: {
        en: "The SBOM is part of which CRA document set?",
        de: "Die SBOM ist Teil welcher CRA-Dokumentensammlung?",
        fr: "La SBOM fait partie de quel ensemble de documents CRA ?",
        it: "La SBOM fa parte di quale insieme di documenti CRA?",
        es: "¿De qué conjunto de documentos CRA forma parte la SBOM?",
        pl: "Częścią którego zestawu dokumentów CRA jest SBOM?",
        cs: "Součástí které sady dokumentů CRA je SBOM?",
        pt: "De que conjunto de documentos CRA faz parte o SBOM?",
        ro: "Din ce set de documente CRA face parte SBOM?",
      },
      options: [
        { en: "The EU declaration of conformity", de: "Die EU-Konformitätserklärung", fr: "La déclaration UE de conformité", it: "La dichiarazione di conformità UE", es: "La declaración UE de conformidad", pl: "Deklaracja zgodności UE", cs: "EU prohlášení o shodě", pt: "A declaração UE de conformidade", ro: "Declarația UE de conformitate" },
        { en: "The technical documentation under Article 31 and Annex VII", de: "Die technische Dokumentation gemäß Artikel 31 und Anhang VII", fr: "La documentation technique au titre de l'article 31 et de l'annexe VII", it: "La documentazione tecnica ai sensi dell'articolo 31 e dell'allegato VII", es: "La documentación técnica conforme al artículo 31 y al anexo VII", pl: "Dokumentacja techniczna zgodnie z artykułem 31 i załącznikiem VII", cs: "Technická dokumentace podle článku 31 a přílohy VII", pt: "A documentação técnica ao abrigo do artigo 31 e do anexo VII", ro: "Documentația tehnică în temeiul articolului 31 și al anexei VII" },
        { en: "The vulnerability disclosure policy under Article 13(6)", de: "Die Richtlinie zur Schwachstellenmeldung gemäß Artikel 13(6)", fr: "La politique de divulgation des vulnérabilités au titre de l'article 13(6)", it: "La politica di divulgazione delle vulnerabilità ai sensi dell'articolo 13(6)", es: "La política de divulgación de vulnerabilidades conforme al artículo 13(6)", pl: "Polityka ujawniania podatności zgodnie z artykułem 13(6)", cs: "Zásady zveřejňování zranitelností podle článku 13(6)", pt: "A política de divulgação de vulnerabilidades ao abrigo do artigo 13(6)", ro: "Politica de divulgare a vulnerabilităților în temeiul articolului 13(6)" },
        { en: "The product safety data sheet", de: "Das Produktsicherheitsdatenblatt", fr: "La fiche de données de sécurité du produit", it: "La scheda di dati di sicurezza del prodotto", es: "La ficha de datos de seguridad del producto", pl: "Karta charakterystyki bezpieczeństwa produktu", cs: "Bezpečnostní list produktu", pt: "A ficha de dados de segurança do produto", ro: "Fișa cu date de securitate a produsului" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The SBOM is one item in the technical documentation package required by Article 31 and detailed in Annex VII. The full package also includes the risk assessment, secure design documentation, test results, and the EU declaration of conformity.",
        de: "Die SBOM ist ein Bestandteil der technischen Dokumentation, die Artikel 31 verlangt und Anhang VII detailliert. Das vollständige Paket umfasst auch die Risikobeurteilung, die Dokumentation des sicheren Designs, Testergebnisse und die EU-Konformitätserklärung.",
        fr: "La SBOM est l'un des éléments du dossier de documentation technique exigé par l'article 31 et détaillé à l'annexe VII. Le dossier complet comprend également l'évaluation des risques, la documentation de conception sécurisée, les résultats des tests et la déclaration UE de conformité.",
        it: "La SBOM è uno degli elementi del pacchetto di documentazione tecnica richiesto dall'articolo 31 e dettagliato nell'allegato VII. Il pacchetto completo comprende anche la valutazione dei rischi, la documentazione di progettazione sicura, i risultati dei test e la dichiarazione di conformità UE.",
        es: "La SBOM es uno de los elementos del conjunto de documentación técnica exigido por el artículo 31 y detallado en el anexo VII. El conjunto completo incluye también la evaluación de riesgos, la documentación de diseño seguro, los resultados de las pruebas y la declaración UE de conformidad.",
        pl: "SBOM jest jednym z elementów pakietu dokumentacji technicznej wymaganego przez artykuł 31 i szczegółowo opisanego w załączniku VII. Pełny pakiet obejmuje również ocenę ryzyka, dokumentację bezpiecznego projektowania, wyniki testów oraz deklarację zgodności UE.",
        cs: "SBOM je jednou z položek balíčku technické dokumentace vyžadovaného článkem 31 a podrobně popsaného v příloze VII. Úplný balíček zahrnuje také posouzení rizik, dokumentaci bezpečného návrhu, výsledky testů a EU prohlášení o shodě.",
        pt: "O SBOM é um dos elementos do conjunto de documentação técnica exigido pelo artigo 31 e detalhado no anexo VII. O conjunto completo inclui também a avaliação de riscos, a documentação de conceção segura, os resultados dos testes e a declaração UE de conformidade.",
        ro: "SBOM este unul dintre elementele pachetului de documentație tehnică impus de articolul 31 și detaliat în anexa VII. Pachetul complet include și evaluarea riscurilor, documentația privind proiectarea sigură, rezultatele testelor și declarația UE de conformitate.",
      },
    },
    {
      id: "1.3.5",
      question: {
        en: "Which storage approach best supports the 10-year retention requirement?",
        de: "Welcher Speicheransatz unterstützt die 10-jährige Aufbewahrungspflicht am besten?",
        fr: "Quelle approche de stockage répond le mieux à l'exigence de conservation de 10 ans ?",
        it: "Quale approccio di archiviazione supporta meglio l'obbligo di conservazione di 10 anni?",
        es: "¿Qué enfoque de almacenamiento responde mejor al requisito de conservación de 10 años?",
        pl: "Które podejście do przechowywania najlepiej spełnia wymóg przechowywania przez 10 lat?",
        cs: "Který přístup k ukládání nejlépe podporuje desetiletou povinnost uchovávání?",
        pt: "Que abordagem de armazenamento responde melhor ao requisito de conservação de 10 anos?",
        ro: "Ce abordare de stocare răspunde cel mai bine cerinței de păstrare timp de 10 ani?",
      },
      options: [
        { en: "Store only the current SBOM in your CI/CD system's artifact cache", de: "Speichern Sie nur die aktuelle SBOM im Artifact-Cache Ihres CI/CD-Systems", fr: "Ne stocker que la SBOM actuelle dans le cache d'artefacts de votre système CI/CD", it: "Archiviare solo la SBOM attuale nella cache degli artefatti del sistema CI/CD", es: "Almacenar solo la SBOM actual en la caché de artefactos de su sistema CI/CD", pl: "Przechowywać tylko bieżący SBOM w pamięci podręcznej artefaktów systemu CI/CD", cs: "Ukládejte pouze aktuální SBOM do mezipaměti artefaktů vašeho systému CI/CD", pt: "Armazenar apenas o SBOM atual na cache de artefactos do seu sistema CI/CD", ro: "Stocați doar SBOM curent în cache-ul de artefacte al sistemului dumneavoastră CI/CD" },
        { en: "Store SBOMs in version control tagged with product version and build timestamp, using a format (JSON) that will remain readable", de: "Speichern Sie SBOMs in der Versionsverwaltung, getaggt mit Produktversion und Build-Zeitstempel, in einem Format (JSON), das lesbar bleibt", fr: "Stocker les SBOM dans le contrôle de version, étiquetées avec la version du produit et l'horodatage de build, dans un format (JSON) qui restera lisible", it: "Archiviare le SBOM nel controllo di versione, etichettate con la versione del prodotto e la marca temporale di build, in un formato (JSON) che resterà leggibile", es: "Almacenar las SBOM en el control de versiones, etiquetadas con la versión del producto y la marca temporal de compilación, en un formato (JSON) que seguirá siendo legible", pl: "Przechowywać SBOM w systemie kontroli wersji, oznaczone wersją produktu i znacznikiem czasu kompilacji, w formacie (JSON), który pozostanie odczytywalny", cs: "Ukládejte SBOM do správy verzí, označené verzí produktu a časovým razítkem sestavení, ve formátu (JSON), který zůstane čitelný", pt: "Armazenar os SBOM no controlo de versões, etiquetados com a versão do produto e a marca temporal de compilação, num formato (JSON) que se mantenha legível", ro: "Stocați SBOM-urile în controlul versiunilor, etichetate cu versiunea produsului și marcajul temporal al compilării, într-un format (JSON) care va rămâne lizibil" },
        { en: "Store SBOMs as PDFs attached to the product user manual", de: "Speichern Sie SBOMs als PDFs, die dem Produktbenutzerhandbuch beigefügt sind", fr: "Stocker les SBOM sous forme de PDF joints au manuel d'utilisation du produit", it: "Archiviare le SBOM come PDF allegati al manuale d'uso del prodotto", es: "Almacenar las SBOM como PDF adjuntos al manual de usuario del producto", pl: "Przechowywać SBOM jako pliki PDF dołączone do instrukcji obsługi produktu", cs: "Ukládejte SBOM jako PDF přiložené k uživatelské příručce produktu", pt: "Armazenar os SBOM como PDF anexados ao manual do utilizador do produto", ro: "Stocați SBOM-urile ca PDF-uri atașate la manualul de utilizare al produsului" },
        { en: "Regenerate SBOMs on demand using the current codebase whenever an authority requests one", de: "Erstellen Sie SBOMs bei Bedarf aus dem aktuellen Codestand neu, wenn eine Behörde eine anfordert", fr: "Régénérer les SBOM à la demande à partir du code source actuel chaque fois qu'une autorité en réclame une", it: "Rigenerare le SBOM su richiesta a partire dal codice attuale ogni volta che un'autorità ne richiede una", es: "Regenerar las SBOM bajo demanda a partir del código actual cada vez que una autoridad solicite una", pl: "Generować SBOM na żądanie na podstawie bieżącego kodu za każdym razem, gdy organ o nią poprosi", cs: "Generujte SBOM na vyžádání z aktuálního kódu pokaždé, když o něj orgán požádá", pt: "Regenerar os SBOM a pedido a partir do código atual sempre que uma autoridade solicitar um", ro: "Regenerați SBOM-urile la cerere pe baza codului actual ori de câte ori o autoritate solicită unul" },
      ],
      correctIndex: 1,
      explanation: {
        en: "SBOMs must be retained for each specific release version. Storing them in version control with version and timestamp tags creates the audit trail. Using standard JSON formats (CycloneDX, SPDX) ensures readability in 10 years. Regenerating from current code does not reproduce the state at release time.",
        de: "SBOMs müssen für jede spezifische Release-Version aufbewahrt werden. Die Speicherung in der Versionsverwaltung mit Versions- und Zeitstempel-Tags erstellt den Prüfpfad. Die Verwendung von Standard-JSON-Formaten (CycloneDX, SPDX) gewährleistet die Lesbarkeit in 10 Jahren. Die Neuerstellung aus dem aktuellen Code reproduziert nicht den Zustand zum Zeitpunkt des Releases.",
        fr: "Les SBOM doivent être conservées pour chaque version publiée. Les stocker dans le contrôle de version avec des étiquettes de version et d'horodatage constitue la piste d'audit. L'utilisation de formats JSON standard (CycloneDX, SPDX) garantit la lisibilité dans 10 ans. La régénération à partir du code actuel ne reproduit pas l'état au moment de la publication.",
        it: "Le SBOM devono essere conservate per ogni specifica versione rilasciata. Archiviarle nel controllo di versione con etichette di versione e marca temporale crea la pista di controllo. L'uso di formati JSON standard (CycloneDX, SPDX) garantisce la leggibilità tra 10 anni. La rigenerazione dal codice attuale non riproduce lo stato al momento del rilascio.",
        es: "Las SBOM deben conservarse para cada versión publicada concreta. Almacenarlas en el control de versiones con etiquetas de versión y marca temporal crea la pista de auditoría. El uso de formatos JSON estándar (CycloneDX, SPDX) garantiza la legibilidad dentro de 10 años. La regeneración a partir del código actual no reproduce el estado en el momento de la publicación.",
        pl: "SBOM muszą być przechowywane dla każdej konkretnej wydanej wersji. Przechowywanie ich w systemie kontroli wersji z etykietami wersji i znacznika czasu tworzy ścieżkę audytu. Użycie standardowych formatów JSON (CycloneDX, SPDX) zapewnia odczytywalność za 10 lat. Ponowne wygenerowanie z bieżącego kodu nie odtwarza stanu z momentu wydania.",
        cs: "SBOM musí být uchovávány pro každou konkrétní vydanou verzi. Jejich uložení do správy verzí s označením verze a časovým razítkem vytváří auditní stopu. Použití standardních formátů JSON (CycloneDX, SPDX) zajišťuje čitelnost za 10 let. Opětovné vygenerování z aktuálního kódu nereprodukuje stav v době vydání.",
        pt: "Os SBOM têm de ser conservados para cada versão lançada específica. Armazená-los no controlo de versões com etiquetas de versão e marca temporal cria o registo de auditoria. A utilização de formatos JSON padrão (CycloneDX, SPDX) garante a legibilidade dentro de 10 anos. Regenerar a partir do código atual não reproduz o estado no momento do lançamento.",
        ro: "SBOM-urile trebuie păstrate pentru fiecare versiune lansată în parte. Stocarea lor în controlul versiunilor cu etichete de versiune și marcaj temporal creează pista de audit. Folosirea formatelor JSON standard (CycloneDX, SPDX) asigură lizibilitatea peste 10 ani. Regenerarea din codul actual nu reproduce starea de la momentul lansării.",
      },
    },
  ],
});

export default quiz;
