import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "1.3",
  passingScore: 75,
  questions: [
    {
      id: "1.3.1",
      question: {
        en: "What is the minimum retention period for the SBOM under CRA Article 31?",
        de: "Wie lang ist die Mindestaufbewahrungspflicht für die SBOM gemäß CRA Artikel 31?",
        fr: "Quelle est la durée minimale de conservation de la SBOM au titre de l'article 31 CRA ?",
        it: "Qual è il periodo minimo di conservazione della SBOM ai sensi dell'articolo 31 CRA?",
        es: "¿Cuál es el período mínimo de conservación de la SBOM conforme al artículo 31 CRA?",
        pl: "Jaki jest minimalny okres przechowywania SBOM zgodnie z artykułem 31 CRA?",
      },
      options: [
        { en: "5 years after first placement on the market", de: "5 Jahre nach erstmaligem Inverkehrbringen", fr: "5 ans après la première mise sur le marché", it: "5 anni dopo la prima immissione sul mercato", es: "5 años después de la primera introducción en el mercado", pl: "5 lat po pierwszym wprowadzeniu do obrotu" },
        { en: "10 years after first placement on the market, or for the support period, whichever is longer", de: "10 Jahre nach erstmaligem Inverkehrbringen oder für die Unterstützungsdauer, je nachdem, was länger ist", fr: "10 ans après la première mise sur le marché, ou pendant la période de support, selon la durée la plus longue", it: "10 anni dopo la prima immissione sul mercato, oppure per il periodo di supporto, se più lungo", es: "10 años después de la primera introducción en el mercado, o durante el período de soporte, lo que sea más largo", pl: "10 lat po pierwszym wprowadzeniu do obrotu lub przez okres wsparcia, w zależności od tego, który okres jest dłuższy" },
        { en: "3 years, or until a new product version is released", de: "3 Jahre oder bis eine neue Produktversion veröffentlicht wird", fr: "3 ans, ou jusqu'à la publication d'une nouvelle version du produit", it: "3 anni, oppure fino al rilascio di una nuova versione del prodotto", es: "3 años, o hasta que se publique una nueva versión del producto", pl: "3 lata lub do wydania nowej wersji produktu" },
        { en: "7 years after the product is withdrawn from the market", de: "7 Jahre nach dem Rückzug des Produkts vom Markt", fr: "7 ans après le retrait du produit du marché", it: "7 anni dopo il ritiro del prodotto dal mercato", es: "7 años después de la retirada del producto del mercado", pl: "7 lat po wycofaniu produktu z rynku" },
      ],
      correctIndex: 1,
      explanation: {
        en: "CRA Article 31(3) requires technical documentation to be kept for 10 years after the product is placed on the market, or for the support period, whichever is longer. For long-lived industrial products, the support period may exceed 10 years.",
        de: "CRA Artikel 31(3) verlangt, dass technische Dokumentation 10 Jahre nach Inverkehrbringen oder für die Unterstützungsdauer aufbewahrt wird, je nachdem, was länger ist. Bei langlebigen Industrieprodukten kann die Unterstützungsdauer 10 Jahre überschreiten.",
        fr: "L'article 31(3) CRA exige que la documentation technique soit conservée pendant 10 ans après la mise sur le marché du produit, ou pendant la période de support, selon la durée la plus longue. Pour les produits industriels à longue durée de vie, la période de support peut dépasser 10 ans.",
        it: "L'articolo 31(3) CRA richiede che la documentazione tecnica sia conservata per 10 anni dopo l'immissione del prodotto sul mercato, oppure per il periodo di supporto, se più lungo. Per i prodotti industriali a lunga durata, il periodo di supporto può superare i 10 anni.",
        es: "El artículo 31(3) CRA exige que la documentación técnica se conserve durante 10 años después de la introducción del producto en el mercado, o durante el período de soporte, lo que sea más largo. Para los productos industriales de larga duración, el período de soporte puede superar los 10 años.",
        pl: "Artykuł 31(3) CRA wymaga przechowywania dokumentacji technicznej przez 10 lat po wprowadzeniu produktu do obrotu lub przez okres wsparcia, w zależności od tego, który okres jest dłuższy. W przypadku długowiecznych produktów przemysłowych okres wsparcia może przekroczyć 10 lat.",
      },
    },
    {
      id: "1.3.2",
      question: {
        en: "Who can request the technical documentation, including the SBOM, under CRA Article 31?",
        de: "Wer kann die technische Dokumentation, einschließlich der SBOM, gemäß CRA Artikel 31 anfordern?",
        fr: "Qui peut demander la documentation technique, y compris la SBOM, au titre de l'article 31 CRA ?",
        it: "Chi può richiedere la documentazione tecnica, compresa la SBOM, ai sensi dell'articolo 31 CRA?",
        es: "¿Quién puede solicitar la documentación técnica, incluida la SBOM, conforme al artículo 31 CRA?",
        pl: "Kto może zażądać dokumentacji technicznej, w tym SBOM, zgodnie z artykułem 31 CRA?",
      },
      options: [
        { en: "Any member of the public who can demonstrate a security interest", de: "Jede Person der Öffentlichkeit, die ein Sicherheitsinteresse nachweisen kann", fr: "Tout membre du public pouvant démontrer un intérêt en matière de sécurité", it: "Qualsiasi membro del pubblico che possa dimostrare un interesse in materia di sicurezza", es: "Cualquier miembro del público que pueda demostrar un interés en materia de seguridad", pl: "Każdy członek społeczeństwa, który może wykazać interes w zakresie bezpieczeństwa" },
        { en: "Only the manufacturer's customers under GDPR data access rights", de: "Nur die Kunden des Herstellers gemäß DSGVO-Datenzugriffsrechten", fr: "Uniquement les clients du fabricant au titre des droits d'accès aux données du GDPR", it: "Solo i clienti del fabbricante in virtù dei diritti di accesso ai dati del GDPR", es: "Solo los clientes del fabricante en virtud de los derechos de acceso a los datos del GDPR", pl: "Tylko klienci producenta na podstawie praw dostępu do danych GDPR" },
        { en: "National market surveillance authorities", de: "Nationale Marktüberwachungsbehörden", fr: "Les autorités nationales de surveillance du marché", it: "Le autorità nazionali di vigilanza del mercato", es: "Las autoridades nacionales de vigilancia del mercado", pl: "Krajowe organy nadzoru rynku" },
        { en: "ENISA and the European Commission only", de: "Nur ENISA und die Europäische Kommission", fr: "Uniquement l'ENISA et la Commission européenne", it: "Solo l'ENISA e la Commissione europea", es: "Solo la ENISA y la Comisión Europea", pl: "Tylko ENISA i Komisja Europejska" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Market surveillance authorities — national bodies such as the BSI in Germany — can request technical documentation at any time. The SBOM is not a public document and does not have to be made available to customers or the general public.",
        de: "Marktüberwachungsbehörden — nationale Stellen wie das BSI in Deutschland — können die technische Dokumentation jederzeit anfordern. Die SBOM ist kein öffentliches Dokument und muss weder Kunden noch der allgemeinen Öffentlichkeit zugänglich gemacht werden.",
        fr: "Les autorités de surveillance du marché, organismes nationaux tels que le BSI en Allemagne, peuvent demander la documentation technique à tout moment. La SBOM n'est pas un document public et n'a pas à être mise à la disposition des clients ni du grand public.",
        it: "Le autorità di vigilanza del mercato, organismi nazionali come il BSI in Germania, possono richiedere la documentazione tecnica in qualsiasi momento. La SBOM non è un documento pubblico e non deve essere messa a disposizione dei clienti né del pubblico in generale.",
        es: "Las autoridades de vigilancia del mercado, organismos nacionales como el BSI en Alemania, pueden solicitar la documentación técnica en cualquier momento. La SBOM no es un documento público y no tiene que ponerse a disposición de los clientes ni del público en general.",
        pl: "Organy nadzoru rynku, krajowe instytucje takie jak BSI w Niemczech, mogą w każdej chwili zażądać dokumentacji technicznej. SBOM nie jest dokumentem publicznym i nie musi być udostępniany klientom ani ogółowi społeczeństwa.",
      },
    },
    {
      id: "1.3.3",
      question: {
        en: "A manufacturer releases 20 security patches for a product over three years. How many SBOMs must be retained?",
        de: "Ein Hersteller veröffentlicht über drei Jahre hinweg 20 Sicherheits-Patches für ein Produkt. Wie viele SBOMs müssen aufbewahrt werden?",
        fr: "Un fabricant publie 20 correctifs de sécurité pour un produit sur trois ans. Combien de SBOM doivent être conservées ?",
        it: "Un fabbricante rilascia 20 patch di sicurezza per un prodotto nell'arco di tre anni. Quante SBOM devono essere conservate?",
        es: "Un fabricante publica 20 parches de seguridad para un producto a lo largo de tres años. ¿Cuántas SBOM deben conservarse?",
        pl: "Producent wydaje 20 poprawek bezpieczeństwa dla produktu w ciągu trzech lat. Ile SBOM musi zostać zachowanych?",
      },
      options: [
        { en: "Only the latest SBOM needs to be retained", de: "Nur die aktuelle SBOM muss aufbewahrt werden", fr: "Seule la dernière SBOM doit être conservée", it: "Deve essere conservata solo la SBOM più recente", es: "Solo debe conservarse la SBOM más reciente", pl: "Należy zachować tylko najnowszy SBOM" },
        { en: "One SBOM per year is sufficient", de: "Eine SBOM pro Jahr ist ausreichend", fr: "Une SBOM par an suffit", it: "Una SBOM all'anno è sufficiente", es: "Una SBOM al año es suficiente", pl: "Jeden SBOM rocznie wystarczy" },
        { en: "An SBOM for each release version — 20 SBOMs in this case", de: "Eine SBOM für jede Release-Version — in diesem Fall 20 SBOMs", fr: "Une SBOM pour chaque version publiée, soit 20 SBOM dans ce cas", it: "Una SBOM per ogni versione rilasciata, ovvero 20 SBOM in questo caso", es: "Una SBOM por cada versión publicada, es decir, 20 SBOM en este caso", pl: "Jeden SBOM dla każdej wydanej wersji, czyli 20 SBOM w tym przypadku" },
        { en: "SBOMs only need to be retained for the final version of the product", de: "SBOMs müssen nur für die letzte Version des Produkts aufbewahrt werden", fr: "Les SBOM ne doivent être conservées que pour la version finale du produit", it: "Le SBOM devono essere conservate solo per la versione finale del prodotto", es: "Las SBOM solo deben conservarse para la versión final del producto", pl: "SBOM należy zachować tylko dla ostatniej wersji produktu" },
      ],
      correctIndex: 2,
      explanation: {
        en: "Each released version has its own component inventory. A market surveillance authority investigating a vulnerability from three years ago wants the SBOM from the version that was in the market at that time. Retain one SBOM per release, linked to that release's version and build.",
        de: "Jede veröffentlichte Version hat ihr eigenes Komponenteninventar. Eine Marktüberwachungsbehörde, die eine Schwachstelle von vor drei Jahren untersucht, möchte die SBOM der Version, die zu diesem Zeitpunkt auf dem Markt war. Bewahren Sie eine SBOM pro Release auf, verknüpft mit der Version und dem Build dieses Releases.",
        fr: "Chaque version publiée a son propre inventaire de composants. Une autorité de surveillance du marché enquêtant sur une vulnérabilité datant de trois ans veut la SBOM de la version qui était sur le marché à ce moment-là. Conservez une SBOM par version, liée à la version et à la build de cette publication.",
        it: "Ogni versione rilasciata ha il proprio inventario dei componenti. Un'autorità di vigilanza del mercato che indaga su una vulnerabilità di tre anni fa vuole la SBOM della versione che era sul mercato in quel momento. Conservate una SBOM per ogni rilascio, collegata alla versione e alla build di quel rilascio.",
        es: "Cada versión publicada tiene su propio inventario de componentes. Una autoridad de vigilancia del mercado que investiga una vulnerabilidad de hace tres años quiere la SBOM de la versión que estaba en el mercado en ese momento. Conserve una SBOM por cada versión, vinculada a la versión y a la compilación de esa publicación.",
        pl: "Każda wydana wersja ma własny inwentarz komponentów. Organ nadzoru rynku badający podatność sprzed trzech lat chce uzyskać SBOM wersji, która była wówczas na rynku. Zachowuj jeden SBOM na każde wydanie, powiązany z wersją i kompilacją tego wydania.",
      },
    },
    {
      id: "1.3.4",
      question: {
        en: "The SBOM is part of which CRA document set?",
        de: "Die SBOM ist Teil welcher CRA-Dokumentensammlung?",
        fr: "La SBOM fait partie de quel ensemble de documents CRA ?",
        it: "La SBOM fa parte di quale insieme di documenti CRA?",
        es: "¿De qué conjunto de documentos CRA forma parte la SBOM?",
        pl: "Częścią którego zestawu dokumentów CRA jest SBOM?",
      },
      options: [
        { en: "The EU declaration of conformity", de: "Die EU-Konformitätserklärung", fr: "La déclaration UE de conformité", it: "La dichiarazione di conformità UE", es: "La declaración UE de conformidad", pl: "Deklaracja zgodności UE" },
        { en: "The technical documentation under Article 31 and Annex VII", de: "Die technische Dokumentation gemäß Artikel 31 und Anhang VII", fr: "La documentation technique au titre de l'article 31 et de l'annexe VII", it: "La documentazione tecnica ai sensi dell'articolo 31 e dell'allegato VII", es: "La documentación técnica conforme al artículo 31 y al anexo VII", pl: "Dokumentacja techniczna zgodnie z artykułem 31 i załącznikiem VII" },
        { en: "The vulnerability disclosure policy under Article 13(6)", de: "Die Richtlinie zur Schwachstellenmeldung gemäß Artikel 13(6)", fr: "La politique de divulgation des vulnérabilités au titre de l'article 13(6)", it: "La politica di divulgazione delle vulnerabilità ai sensi dell'articolo 13(6)", es: "La política de divulgación de vulnerabilidades conforme al artículo 13(6)", pl: "Polityka ujawniania podatności zgodnie z artykułem 13(6)" },
        { en: "The product safety data sheet", de: "Das Produktsicherheitsdatenblatt", fr: "La fiche de données de sécurité du produit", it: "La scheda di dati di sicurezza del prodotto", es: "La ficha de datos de seguridad del producto", pl: "Karta charakterystyki bezpieczeństwa produktu" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The SBOM is one item in the technical documentation package required by Article 31 and detailed in Annex VII. The full package also includes the risk assessment, secure design documentation, test results, and the EU declaration of conformity.",
        de: "Die SBOM ist ein Bestandteil der technischen Dokumentation, die Artikel 31 verlangt und Anhang VII detailliert. Das vollständige Paket umfasst auch die Risikobeurteilung, die Dokumentation des sicheren Designs, Testergebnisse und die EU-Konformitätserklärung.",
        fr: "La SBOM est l'un des éléments du dossier de documentation technique exigé par l'article 31 et détaillé à l'annexe VII. Le dossier complet comprend également l'évaluation des risques, la documentation de conception sécurisée, les résultats des tests et la déclaration UE de conformité.",
        it: "La SBOM è uno degli elementi del pacchetto di documentazione tecnica richiesto dall'articolo 31 e dettagliato nell'allegato VII. Il pacchetto completo comprende anche la valutazione dei rischi, la documentazione di progettazione sicura, i risultati dei test e la dichiarazione di conformità UE.",
        es: "La SBOM es uno de los elementos del conjunto de documentación técnica exigido por el artículo 31 y detallado en el anexo VII. El conjunto completo incluye también la evaluación de riesgos, la documentación de diseño seguro, los resultados de las pruebas y la declaración UE de conformidad.",
        pl: "SBOM jest jednym z elementów pakietu dokumentacji technicznej wymaganego przez artykuł 31 i szczegółowo opisanego w załączniku VII. Pełny pakiet obejmuje również ocenę ryzyka, dokumentację bezpiecznego projektowania, wyniki testów oraz deklarację zgodności UE.",
      },
    },
    {
      id: "1.3.5",
      question: {
        en: "Which storage approach best supports the 10-year retention requirement?",
        de: "Welcher Speicheransatz unterstützt die 10-jährige Aufbewahrungspflicht am besten?",
        fr: "Quelle approche de stockage répond le mieux à l'exigence de conservation de 10 ans ?",
        it: "Quale approccio di archiviazione supporta meglio l'obbligo di conservazione di 10 anni?",
        es: "¿Qué enfoque de almacenamiento responde mejor al requisito de conservación de 10 años?",
        pl: "Które podejście do przechowywania najlepiej spełnia wymóg przechowywania przez 10 lat?",
      },
      options: [
        { en: "Store only the current SBOM in your CI/CD system's artifact cache", de: "Speichern Sie nur die aktuelle SBOM im Artifact-Cache Ihres CI/CD-Systems", fr: "Ne stocker que la SBOM actuelle dans le cache d'artefacts de votre système CI/CD", it: "Archiviare solo la SBOM attuale nella cache degli artefatti del sistema CI/CD", es: "Almacenar solo la SBOM actual en la caché de artefactos de su sistema CI/CD", pl: "Przechowywać tylko bieżący SBOM w pamięci podręcznej artefaktów systemu CI/CD" },
        { en: "Store SBOMs in version control tagged with product version and build timestamp, using a format (JSON) that will remain readable", de: "Speichern Sie SBOMs in der Versionsverwaltung, getaggt mit Produktversion und Build-Zeitstempel, in einem Format (JSON), das lesbar bleibt", fr: "Stocker les SBOM dans le contrôle de version, étiquetées avec la version du produit et l'horodatage de build, dans un format (JSON) qui restera lisible", it: "Archiviare le SBOM nel controllo di versione, etichettate con la versione del prodotto e la marca temporale di build, in un formato (JSON) che resterà leggibile", es: "Almacenar las SBOM en el control de versiones, etiquetadas con la versión del producto y la marca temporal de compilación, en un formato (JSON) que seguirá siendo legible", pl: "Przechowywać SBOM w systemie kontroli wersji, oznaczone wersją produktu i znacznikiem czasu kompilacji, w formacie (JSON), który pozostanie odczytywalny" },
        { en: "Store SBOMs as PDFs attached to the product user manual", de: "Speichern Sie SBOMs als PDFs, die dem Produktbenutzerhandbuch beigefügt sind", fr: "Stocker les SBOM sous forme de PDF joints au manuel d'utilisation du produit", it: "Archiviare le SBOM come PDF allegati al manuale d'uso del prodotto", es: "Almacenar las SBOM como PDF adjuntos al manual de usuario del producto", pl: "Przechowywać SBOM jako pliki PDF dołączone do instrukcji obsługi produktu" },
        { en: "Regenerate SBOMs on demand using the current codebase whenever an authority requests one", de: "Erstellen Sie SBOMs bei Bedarf aus dem aktuellen Codestand neu, wenn eine Behörde eine anfordert", fr: "Régénérer les SBOM à la demande à partir du code source actuel chaque fois qu'une autorité en réclame une", it: "Rigenerare le SBOM su richiesta a partire dal codice attuale ogni volta che un'autorità ne richiede una", es: "Regenerar las SBOM bajo demanda a partir del código actual cada vez que una autoridad solicite una", pl: "Generować SBOM na żądanie na podstawie bieżącego kodu za każdym razem, gdy organ o nią poprosi" },
      ],
      correctIndex: 1,
      explanation: {
        en: "SBOMs must be retained for each specific release version. Storing them in version control with version and timestamp tags creates the audit trail. Using standard JSON formats (CycloneDX, SPDX) ensures readability in 10 years. Regenerating from current code does not reproduce the state at release time.",
        de: "SBOMs müssen für jede spezifische Release-Version aufbewahrt werden. Die Speicherung in der Versionsverwaltung mit Versions- und Zeitstempel-Tags erstellt den Prüfpfad. Die Verwendung von Standard-JSON-Formaten (CycloneDX, SPDX) gewährleistet die Lesbarkeit in 10 Jahren. Die Neuerstellung aus dem aktuellen Code reproduziert nicht den Zustand zum Zeitpunkt des Releases.",
        fr: "Les SBOM doivent être conservées pour chaque version publiée. Les stocker dans le contrôle de version avec des étiquettes de version et d'horodatage constitue la piste d'audit. L'utilisation de formats JSON standard (CycloneDX, SPDX) garantit la lisibilité dans 10 ans. La régénération à partir du code actuel ne reproduit pas l'état au moment de la publication.",
        it: "Le SBOM devono essere conservate per ogni specifica versione rilasciata. Archiviarle nel controllo di versione con etichette di versione e marca temporale crea la pista di controllo. L'uso di formati JSON standard (CycloneDX, SPDX) garantisce la leggibilità tra 10 anni. La rigenerazione dal codice attuale non riproduce lo stato al momento del rilascio.",
        es: "Las SBOM deben conservarse para cada versión publicada concreta. Almacenarlas en el control de versiones con etiquetas de versión y marca temporal crea la pista de auditoría. El uso de formatos JSON estándar (CycloneDX, SPDX) garantiza la legibilidad dentro de 10 años. La regeneración a partir del código actual no reproduce el estado en el momento de la publicación.",
        pl: "SBOM muszą być przechowywane dla każdej konkretnej wydanej wersji. Przechowywanie ich w systemie kontroli wersji z etykietami wersji i znacznika czasu tworzy ścieżkę audytu. Użycie standardowych formatów JSON (CycloneDX, SPDX) zapewnia odczytywalność za 10 lat. Ponowne wygenerowanie z bieżącego kodu nie odtwarza stanu z momentu wydania.",
      },
    },
  ],
});

export default quiz;
