import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.1",
  passingScore: 75,
  questions: [
    {
      id: "2.1.1",
      question: {
        en: "Which organisation maintains the CycloneDX standard?",
        de: "Welche Organisation pflegt den CycloneDX-Standard?",
        fr: "Quelle organisation maintient le standard CycloneDX ?",
        it: "Quale organizzazione mantiene lo standard CycloneDX?",
        es: "¿Qué organización mantiene el estándar CycloneDX?",
        pl: "Która organizacja utrzymuje standard CycloneDX?",
      },
      options: [
        { en: "ISO", de: "ISO", fr: "ISO", it: "ISO", es: "ISO", pl: "ISO" },
        { en: "Linux Foundation", de: "Linux Foundation", fr: "Linux Foundation", it: "Linux Foundation", es: "Linux Foundation", pl: "Linux Foundation" },
        { en: "OWASP", de: "OWASP", fr: "OWASP", it: "OWASP", es: "OWASP", pl: "OWASP" },
        { en: "NIST", de: "NIST", fr: "NIST", it: "NIST", es: "NIST", pl: "NIST" },
      ],
      correctIndex: 2,
      explanation: {
        en: "CycloneDX is an OWASP project — the Open Web Application Security Project. SPDX is the Linux Foundation project. ISO/IEC 5962:2021 is the ISO standard for SBOM, which covers SPDX.",
        de: "CycloneDX ist ein OWASP-Projekt — das Open Web Application Security Project. SPDX ist das Linux-Foundation-Projekt. ISO/IEC 5962:2021 ist der ISO-Standard für SBOM, der SPDX abdeckt.",
        fr: "CycloneDX est un projet OWASP, l'Open Web Application Security Project. SPDX est le projet de la Linux Foundation. ISO/IEC 5962:2021 est le standard ISO pour la SBOM, qui couvre SPDX.",
        it: "CycloneDX è un progetto OWASP, l'Open Web Application Security Project. SPDX è il progetto della Linux Foundation. ISO/IEC 5962:2021 è lo standard ISO per la SBOM, che copre SPDX.",
        es: "CycloneDX es un proyecto de OWASP, el Open Web Application Security Project. SPDX es el proyecto de la Linux Foundation. ISO/IEC 5962:2021 es el estándar ISO para la SBOM, que cubre SPDX.",
        pl: "CycloneDX to projekt OWASP, czyli Open Web Application Security Project. SPDX to projekt Linux Foundation. ISO/IEC 5962:2021 to standard ISO dla SBOM, który obejmuje SPDX.",
      },
    },
    {
      id: "2.1.2",
      question: {
        en: "What does a VEX 'not_affected' statement with a 'code_not_reachable' justification document?",
        de: "Was dokumentiert eine VEX-'not_affected'-Aussage mit der Begründung 'code_not_reachable'?",
        fr: "Que documente une déclaration VEX « not_affected » assortie d'une justification « code_not_reachable » ?",
        it: "Che cosa documenta una dichiarazione VEX « not_affected » con la giustificazione « code_not_reachable »?",
        es: "¿Qué documenta una declaración VEX « not_affected » con una justificación « code_not_reachable »?",
        pl: "Co dokumentuje oświadczenie VEX « not_affected » z uzasadnieniem « code_not_reachable »?",
      },
      options: [
        { en: "That the CVE has been patched in the next planned release", de: "Dass die CVE im nächsten geplanten Release gepatcht wird", fr: "Que la CVE sera corrigée dans la prochaine version planifiée", it: "Che la CVE sarà corretta nel prossimo rilascio pianificato", es: "Que la CVE se corregirá en la próxima versión planificada", pl: "Że CVE zostanie naprawiona w następnym zaplanowanym wydaniu" },
        { en: "That the vulnerable code exists in the component but cannot be reached in this product's execution context", de: "Dass der anfällige Code in der Komponente vorhanden ist, aber im Ausführungskontext dieses Produkts nicht erreichbar ist", fr: "Que le code vulnérable existe dans le composant mais ne peut être atteint dans le contexte d'exécution de ce produit", it: "Che il codice vulnerabile esiste nel componente ma non è raggiungibile nel contesto di esecuzione di questo prodotto", es: "Que el código vulnerable existe en el componente pero no puede alcanzarse en el contexto de ejecución de este producto", pl: "Że podatny kod istnieje w komponencie, ale nie można go osiągnąć w kontekście wykonawczym tego produktu" },
        { en: "That the component version is not affected by the CVE according to the NVD", de: "Dass die Komponentenversion laut NVD nicht von der CVE betroffen ist", fr: "Que la version du composant n'est pas affectée par la CVE selon la NVD", it: "Che la versione del componente non è interessata dalla CVE secondo la NVD", es: "Que la versión del componente no se ve afectada por la CVE según la NVD", pl: "Że wersja komponentu nie jest podatna na CVE według NVD" },
        { en: "That the CVE has been disputed by the component vendor", de: "Dass die CVE vom Komponentenanbieter angefochten wird", fr: "Que la CVE est contestée par le fournisseur du composant", it: "Che la CVE è contestata dal fornitore del componente", es: "Que la CVE ha sido impugnada por el proveedor del componente", pl: "Że CVE została zakwestionowana przez dostawcę komponentu" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A VEX 'not_affected' statement with 'code_not_reachable' means: the vulnerable code path exists in the component version you are using, but your product's architecture or configuration means that code path is never executed. This is a formal, machine-readable audit record of the investigation decision.",
        de: "Eine VEX-'not_affected'-Aussage mit 'code_not_reachable' bedeutet: Der anfällige Codepfad ist in der verwendeten Komponentenversion vorhanden, aber durch die Architektur oder Konfiguration Ihres Produkts wird dieser Codepfad nie ausgeführt. Dies ist ein formales, maschinenlesbares Auditprotokoll der Untersuchungsentscheidung.",
        fr: "Une déclaration VEX « not_affected » avec « code_not_reachable » signifie : le chemin de code vulnérable existe dans la version du composant que vous utilisez, mais l'architecture ou la configuration de votre produit fait que ce chemin de code n'est jamais exécuté. Il s'agit d'un enregistrement d'audit formel et lisible par machine de la décision d'investigation.",
        it: "Una dichiarazione VEX « not_affected » con « code_not_reachable » significa: il percorso di codice vulnerabile esiste nella versione del componente in uso, ma l'architettura o la configurazione del prodotto fa sì che quel percorso di codice non venga mai eseguito. Si tratta di una registrazione di audit formale e leggibile da una macchina della decisione di indagine.",
        es: "Una declaración VEX « not_affected » con « code_not_reachable » significa: la ruta de código vulnerable existe en la versión del componente que utiliza, pero la arquitectura o configuración de su producto hace que esa ruta de código nunca se ejecute. Es un registro de auditoría formal y legible por máquina de la decisión de investigación.",
        pl: "Oświadczenie VEX « not_affected » z « code_not_reachable » oznacza: podatna ścieżka kodu istnieje w używanej wersji komponentu, ale architektura lub konfiguracja produktu sprawia, że ta ścieżka kodu nigdy nie jest wykonywana. Jest to formalny, odczytywalny maszynowo zapis audytowy decyzji wynikającej z analizy.",
      },
    },
    {
      id: "2.1.3",
      question: {
        en: "What are the four main sections of a CycloneDX SBOM document?",
        de: "Was sind die vier Hauptabschnitte eines CycloneDX-SBOM-Dokuments?",
        fr: "Quelles sont les quatre sections principales d'un document SBOM CycloneDX ?",
        it: "Quali sono le quattro sezioni principali di un documento SBOM CycloneDX?",
        es: "¿Cuáles son las cuatro secciones principales de un documento SBOM CycloneDX?",
        pl: "Jakie są cztery główne sekcje dokumentu SBOM CycloneDX?",
      },
      options: [
        { en: "Header, body, signatures, appendix", de: "Kopfzeile, Hauptteil, Signaturen, Anhang", fr: "En-tête, corps, signatures, annexe", it: "Intestazione, corpo, firme, appendice", es: "Encabezado, cuerpo, firmas, apéndice", pl: "Nagłówek, treść, podpisy, załącznik" },
        { en: "Metadata, components, dependencies, vulnerabilities", de: "Metadaten, Komponenten, Abhängigkeiten, Schwachstellen", fr: "Métadonnées, composants, dépendances, vulnérabilités", it: "Metadati, componenti, dipendenze, vulnerabilità", es: "Metadatos, componentes, dependencias, vulnerabilidades", pl: "Metadane, komponenty, zależności, podatności" },
        { en: "Document info, packages, relationships, files", de: "Dokumentinformationen, Pakete, Beziehungen, Dateien", fr: "Informations du document, paquets, relations, fichiers", it: "Informazioni del documento, pacchetti, relazioni, file", es: "Información del documento, paquetes, relaciones, archivos", pl: "Informacje o dokumencie, pakiety, relacje, pliki" },
        { en: "Manifest, inventory, licenses, hashes", de: "Manifest, Inventar, Lizenzen, Hash-Werte", fr: "Manifeste, inventaire, licences, hachages", it: "Manifesto, inventario, licenze, hash", es: "Manifiesto, inventario, licencias, hashes", pl: "Manifest, inwentarz, licencje, skróty" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A CycloneDX document has: metadata (about the SBOM and the product), components (the component inventory), dependencies (the dependency graph), and optionally vulnerabilities (embedded CVE data). SPDX uses different section names: document creation information, packages, relationships.",
        de: "Ein CycloneDX-Dokument hat: Metadaten (über die SBOM und das Produkt), Komponenten (das Komponenteninventar), Abhängigkeiten (der Abhängigkeitsgraph) und optional Schwachstellen (eingebettete CVE-Daten). SPDX verwendet andere Abschnittsnamen: Dokumenterstellungsinformationen, Pakete, Beziehungen.",
        fr: "Un document CycloneDX comporte : des métadonnées (sur la SBOM et le produit), des composants (l'inventaire des composants), des dépendances (le graphe de dépendances) et, en option, des vulnérabilités (données CVE intégrées). SPDX utilise des noms de sections différents : informations de création du document, paquets, relations.",
        it: "Un documento CycloneDX comprende: metadati (sulla SBOM e sul prodotto), componenti (l'inventario dei componenti), dipendenze (il grafo delle dipendenze) e, facoltativamente, vulnerabilità (dati CVE incorporati). SPDX utilizza nomi di sezione diversi: informazioni di creazione del documento, pacchetti, relazioni.",
        es: "Un documento CycloneDX tiene: metadatos (sobre la SBOM y el producto), componentes (el inventario de componentes), dependencias (el grafo de dependencias) y, opcionalmente, vulnerabilidades (datos CVE incorporados). SPDX utiliza nombres de sección diferentes: información de creación del documento, paquetes, relaciones.",
        pl: "Dokument CycloneDX zawiera: metadane (o SBOM i produkcie), komponenty (inwentarz komponentów), zależności (graf zależności) oraz opcjonalnie podatności (osadzone dane CVE). SPDX używa innych nazw sekcji: informacje o utworzeniu dokumentu, pakiety, relacje.",
      },
    },
    {
      id: "2.1.4",
      question: {
        en: "Why is CycloneDX described as the preferred format for CRA Article 14 compliance workflows?",
        de: "Warum wird CycloneDX als bevorzugtes Format für CRA-Artikel-14-Compliance-Workflows beschrieben?",
        fr: "Pourquoi CycloneDX est-il décrit comme le format privilégié pour les processus de conformité à l'article 14 CRA ?",
        it: "Perché CycloneDX è descritto come il formato preferito per i flussi di lavoro di conformità all'articolo 14 CRA?",
        es: "¿Por qué se describe CycloneDX como el formato preferido para los flujos de trabajo de conformidad con el artículo 14 CRA?",
        pl: "Dlaczego CycloneDX jest opisywany jako preferowany format w procesach zgodności z artykułem 14 CRA?",
      },
      options: [
        { en: "Because the European Commission has officially designated CycloneDX as the required format", de: "Weil die Europäische Kommission CycloneDX offiziell als vorgeschriebenes Format festgelegt hat", fr: "Parce que la Commission européenne a officiellement désigné CycloneDX comme le format requis", it: "Perché la Commissione europea ha designato ufficialmente CycloneDX come formato richiesto", es: "Porque la Comisión Europea ha designado oficialmente CycloneDX como el formato requerido", pl: "Ponieważ Komisja Europejska oficjalnie wyznaczyła CycloneDX jako wymagany format" },
        { en: "Because it was designed for vulnerability management workflows and has native VEX support, and tools like Grype and Dependency-Track are built around it", de: "Weil es für Schwachstellenmanagement-Workflows konzipiert wurde und native VEX-Unterstützung hat, und Werkzeuge wie Grype und Dependency-Track darauf aufgebaut sind", fr: "Parce qu'il a été conçu pour les processus de gestion des vulnérabilités, qu'il prend en charge VEX nativement et que des outils comme Grype et Dependency-Track sont construits autour de lui", it: "Perché è stato progettato per i flussi di lavoro di gestione delle vulnerabilità, supporta VEX in modo nativo e strumenti come Grype e Dependency-Track sono costruiti attorno a esso", es: "Porque se diseñó para los flujos de trabajo de gestión de vulnerabilidades, tiene soporte nativo de VEX y herramientas como Grype y Dependency-Track están construidas en torno a él", pl: "Ponieważ został zaprojektowany do procesów zarządzania podatnościami, natywnie obsługuje VEX, a narzędzia takie jak Grype i Dependency-Track są wokół niego zbudowane" },
        { en: "Because it is the only format that supports PURL identifiers", de: "Weil es das einzige Format ist, das PURL-Bezeichner unterstützt", fr: "Parce que c'est le seul format qui prend en charge les identifiants PURL", it: "Perché è l'unico formato che supporta gli identificatori PURL", es: "Porque es el único formato que admite los identificadores PURL", pl: "Ponieważ jest to jedyny format obsługujący identyfikatory PURL" },
        { en: "Because SPDX does not support component hashes", de: "Weil SPDX keine Komponenten-Hash-Werte unterstützt", fr: "Parce que SPDX ne prend pas en charge les hachages de composants", it: "Perché SPDX non supporta gli hash dei componenti", es: "Porque SPDX no admite los hashes de componentes", pl: "Ponieważ SPDX nie obsługuje skrótów komponentów" },
      ],
      correctIndex: 1,
      explanation: {
        en: "CycloneDX was designed for security use cases from the start. Its native VEX support, Dependency-Track integration, and tooling ecosystem (Grype, Syft, cdxgen) make it the natural choice for the Article 14 monitoring and reporting loop. SPDX also qualifies for CRA compliance but was designed primarily for license management.",
        de: "CycloneDX wurde von Anfang an für Sicherheits-Anwendungsfälle konzipiert. Seine native VEX-Unterstützung, die Dependency-Track-Integration und das Werkzeug-Ökosystem (Grype, Syft, cdxgen) machen es zur natürlichen Wahl für den Artikel-14-Überwachungs- und Meldungskreislauf. SPDX qualifiziert sich ebenfalls für die CRA-Compliance, wurde jedoch primär für die Lizenzverwaltung konzipiert.",
        fr: "CycloneDX a été conçu dès le départ pour des cas d'usage de sécurité. Sa prise en charge native de VEX, son intégration avec Dependency-Track et son écosystème d'outils (Grype, Syft, cdxgen) en font le choix naturel pour la boucle de surveillance et de signalement de l'article 14. SPDX est également admissible pour la conformité CRA, mais a été conçu principalement pour la gestion des licences.",
        it: "CycloneDX è stato progettato fin dall'inizio per casi d'uso di sicurezza. Il suo supporto nativo a VEX, l'integrazione con Dependency-Track e l'ecosistema di strumenti (Grype, Syft, cdxgen) ne fanno la scelta naturale per il ciclo di monitoraggio e segnalazione dell'articolo 14. Anche SPDX è idoneo per la conformità CRA, ma è stato progettato principalmente per la gestione delle licenze.",
        es: "CycloneDX se diseñó desde el principio para casos de uso de seguridad. Su soporte nativo de VEX, su integración con Dependency-Track y su ecosistema de herramientas (Grype, Syft, cdxgen) lo convierten en la elección natural para el bucle de supervisión y notificación del artículo 14. SPDX también es válido para la conformidad CRA, pero se diseñó principalmente para la gestión de licencias.",
        pl: "CycloneDX został od początku zaprojektowany z myślą o zastosowaniach bezpieczeństwa. Jego natywna obsługa VEX, integracja z Dependency-Track oraz ekosystem narzędzi (Grype, Syft, cdxgen) czynią go naturalnym wyborem dla pętli monitorowania i zgłaszania z artykułu 14. SPDX również kwalifikuje się do zgodności z CRA, ale został zaprojektowany głównie do zarządzania licencjami.",
      },
    },
    {
      id: "2.1.5",
      question: {
        en: "Which command generates a CycloneDX 1.6 JSON SBOM from a container image using Syft?",
        de: "Welcher Befehl erstellt eine CycloneDX-1.6-JSON-SBOM aus einem Container-Image mit Syft?",
        fr: "Quelle commande génère une SBOM CycloneDX 1.6 JSON à partir d'une image de conteneur avec Syft ?",
        it: "Quale comando genera una SBOM CycloneDX 1.6 JSON da un'immagine di container con Syft?",
        es: "¿Qué comando genera una SBOM CycloneDX 1.6 JSON a partir de una imagen de contenedor con Syft?",
        pl: "Które polecenie generuje SBOM CycloneDX 1.6 JSON z obrazu kontenera za pomocą Syft?",
      },
      options: [
        { en: "syft my-image:latest --format cdx", de: "syft my-image:latest --format cdx", fr: "syft my-image:latest --format cdx", it: "syft my-image:latest --format cdx", es: "syft my-image:latest --format cdx", pl: "syft my-image:latest --format cdx" },
        { en: "syft scan my-image:latest > sbom.json", de: "syft scan my-image:latest > sbom.json", fr: "syft scan my-image:latest > sbom.json", it: "syft scan my-image:latest > sbom.json", es: "syft scan my-image:latest > sbom.json", pl: "syft scan my-image:latest > sbom.json" },
        { en: "syft my-image:latest -o cyclonedx-json > sbom.cdx.json", de: "syft my-image:latest -o cyclonedx-json > sbom.cdx.json", fr: "syft my-image:latest -o cyclonedx-json > sbom.cdx.json", it: "syft my-image:latest -o cyclonedx-json > sbom.cdx.json", es: "syft my-image:latest -o cyclonedx-json > sbom.cdx.json", pl: "syft my-image:latest -o cyclonedx-json > sbom.cdx.json" },
        { en: "syft generate --type cyclonedx my-image:latest", de: "syft generate --type cyclonedx my-image:latest", fr: "syft generate --type cyclonedx my-image:latest", it: "syft generate --type cyclonedx my-image:latest", es: "syft generate --type cyclonedx my-image:latest", pl: "syft generate --type cyclonedx my-image:latest" },
      ],
      correctIndex: 2,
      explanation: {
        en: "The correct Syft command is: syft <target> -o cyclonedx-json > output-file.cdx.json. The -o flag sets the output format. cyclonedx-json produces CycloneDX 1.6 JSON by default.",
        de: "Der korrekte Syft-Befehl ist: syft <Ziel> -o cyclonedx-json > Ausgabedatei.cdx.json. Das -o-Flag legt das Ausgabeformat fest. cyclonedx-json erzeugt standardmäßig CycloneDX 1.6 JSON.",
        fr: "La commande Syft correcte est : syft <cible> -o cyclonedx-json > fichier-de-sortie.cdx.json. L'option -o définit le format de sortie. cyclonedx-json produit par défaut du CycloneDX 1.6 JSON.",
        it: "Il comando Syft corretto è: syft <destinazione> -o cyclonedx-json > file-di-output.cdx.json. L'opzione -o imposta il formato di output. cyclonedx-json produce per impostazione predefinita CycloneDX 1.6 JSON.",
        es: "El comando Syft correcto es: syft <destino> -o cyclonedx-json > archivo-de-salida.cdx.json. La opción -o establece el formato de salida. cyclonedx-json produce CycloneDX 1.6 JSON de forma predeterminada.",
        pl: "Poprawne polecenie Syft to: syft <cel> -o cyclonedx-json > plik-wyjsciowy.cdx.json. Flaga -o ustawia format wyjściowy. cyclonedx-json domyślnie generuje CycloneDX 1.6 JSON.",
      },
    },
  ],
});

export default quiz;
