import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "2.2",
  passingScore: 75,
  questions: [
    {
      id: "2.2.1",
      question: {
        en: "What is the ISO standard designation for SPDX?",
        de: "Wie lautet die ISO-Standardbezeichnung für SPDX?",
        fr: "Quelle est la désignation de standard ISO pour SPDX ?",
        it: "Qual è la designazione dello standard ISO per SPDX?",
        es: "¿Cuál es la designación del estándar ISO para SPDX?",
        pl: "Jakie jest oznaczenie standardu ISO dla SPDX?",
        cs: "Jaké je označení standardu ISO pro SPDX?",
        pt: "Qual é a designação do padrão ISO para o SPDX?",
        ro: "Care este denumirea standardului ISO pentru SPDX?",
      },
      options: [
        { en: "ISO/IEC 27001:2022", de: "ISO/IEC 27001:2022", fr: "ISO/IEC 27001:2022", it: "ISO/IEC 27001:2022", es: "ISO/IEC 27001:2022", pl: "ISO/IEC 27001:2022", cs: "ISO/IEC 27001:2022", pt: "ISO/IEC 27001:2022", ro: "ISO/IEC 27001:2022" },
        { en: "ISO/IEC 5962:2021", de: "ISO/IEC 5962:2021", fr: "ISO/IEC 5962:2021", it: "ISO/IEC 5962:2021", es: "ISO/IEC 5962:2021", pl: "ISO/IEC 5962:2021", cs: "ISO/IEC 5962:2021", pt: "ISO/IEC 5962:2021", ro: "ISO/IEC 5962:2021" },
        { en: "ISO 22301:2019", de: "ISO 22301:2019", fr: "ISO 22301:2019", it: "ISO 22301:2019", es: "ISO 22301:2019", pl: "ISO 22301:2019", cs: "ISO 22301:2019", pt: "ISO 22301:2019", ro: "ISO 22301:2019" },
        { en: "ISO/IEC 29147:2018", de: "ISO/IEC 29147:2018", fr: "ISO/IEC 29147:2018", it: "ISO/IEC 29147:2018", es: "ISO/IEC 29147:2018", pl: "ISO/IEC 29147:2018", cs: "ISO/IEC 29147:2018", pt: "ISO/IEC 29147:2018", ro: "ISO/IEC 29147:2018" },
      ],
      correctIndex: 1,
      explanation: {
        en: "SPDX is ISO/IEC 5962:2021 — the international standard for Software Package Data Exchange, published by ISO in 2021. It is the only SBOM format that is also an ISO standard.",
        de: "SPDX ist ISO/IEC 5962:2021 — der internationale Standard für Software Package Data Exchange, 2021 von der ISO veröffentlicht. Es ist das einzige SBOM-Format, das auch ein ISO-Standard ist.",
        fr: "SPDX correspond à ISO/IEC 5962:2021, le standard international pour Software Package Data Exchange, publié par l'ISO en 2021. C'est le seul format SBOM qui soit également un standard ISO.",
        it: "SPDX è ISO/IEC 5962:2021, lo standard internazionale per Software Package Data Exchange, pubblicato dall'ISO nel 2021. È l'unico formato SBOM che è anche uno standard ISO.",
        es: "SPDX es ISO/IEC 5962:2021, el estándar internacional para Software Package Data Exchange, publicado por la ISO en 2021. Es el único formato SBOM que también es un estándar ISO.",
        pl: "SPDX to ISO/IEC 5962:2021, międzynarodowy standard Software Package Data Exchange, opublikowany przez ISO w 2021 roku. Jest to jedyny format SBOM, który jest również standardem ISO.",
        cs: "SPDX je ISO/IEC 5962:2021, mezinárodní standard pro Software Package Data Exchange, který ISO vydala v roce 2021. Je to jediný formát SBOM, který je zároveň standardem ISO.",
        pt: "O SPDX é a ISO/IEC 5962:2021, a norma internacional para Software Package Data Exchange, publicada pela ISO em 2021. É o único formato SBOM que é também uma norma ISO.",
        ro: "SPDX este ISO/IEC 5962:2021, standardul internațional pentru Software Package Data Exchange, publicat de ISO în 2021. Este singurul format SBOM care este și un standard ISO.",
      },
    },
    {
      id: "2.2.2",
      question: {
        en: "What is SPDX's original design purpose, which distinguishes it from CycloneDX?",
        de: "Was ist der ursprüngliche Entwurfszweck von SPDX, der es von CycloneDX unterscheidet?",
        fr: "Quel est l'objectif de conception initial de SPDX, qui le distingue de CycloneDX ?",
        it: "Qual è lo scopo di progettazione originario di SPDX, che lo distingue da CycloneDX?",
        es: "¿Cuál es el propósito de diseño original de SPDX, que lo distingue de CycloneDX?",
        pl: "Jaki jest pierwotny cel projektowy SPDX, który odróżnia go od CycloneDX?",
        cs: "Jaký je původní účel návrhu SPDX, který jej odlišuje od CycloneDX?",
        pt: "Qual é o propósito de conceção original do SPDX, que o distingue do CycloneDX?",
        ro: "Care este scopul inițial de proiectare al SPDX, care îl deosebește de CycloneDX?",
      },
      options: [
        { en: "Vulnerability tracking and active exploitation monitoring", de: "Schwachstellenverfolgung und Überwachung aktiver Ausnutzungen", fr: "Suivi des vulnérabilités et surveillance de l'exploitation active", it: "Tracciamento delle vulnerabilità e monitoraggio dello sfruttamento attivo", es: "Seguimiento de vulnerabilidades y supervisión de la explotación activa", pl: "Śledzenie podatności i monitorowanie aktywnego wykorzystywania", cs: "Sledování zranitelností a monitorování aktivního zneužívání", pt: "Rastreio de vulnerabilidades e monitorização da exploração ativa", ro: "Urmărirea vulnerabilităților și monitorizarea exploatării active" },
        { en: "Open-source license compliance and attribution tracking", de: "Open-Source-Lizenz-Compliance und Nachverfolgung von Namensnennung", fr: "Conformité des licences open source et suivi de l'attribution", it: "Conformità delle licenze open source e tracciamento dell'attribuzione", es: "Conformidad de licencias de código abierto y seguimiento de la atribución", pl: "Zgodność licencji open source i śledzenie atrybucji", cs: "Soulad s licencemi open source a sledování uvádění autorství", pt: "Conformidade de licenças de código aberto e rastreio da atribuição", ro: "Conformitatea licențelor open source și urmărirea atribuirii" },
        { en: "Container image scanning and OS package detection", de: "Container-Image-Scanning und OS-Paketerkennung", fr: "Analyse des images de conteneur et détection des paquets du système d'exploitation", it: "Scansione delle immagini di container e rilevamento dei pacchetti del sistema operativo", es: "Análisis de imágenes de contenedor y detección de paquetes del sistema operativo", pl: "Skanowanie obrazów kontenerów i wykrywanie pakietów systemu operacyjnego", cs: "Skenování kontejnerových obrazů a detekce OS balíčků", pt: "Análise de imagens de contentor e deteção de pacotes do sistema operativo", ro: "Scanarea imaginilor de container și detectarea pachetelor sistemului de operare" },
        { en: "Supply chain provenance and code signing", de: "Lieferketten-Herkunftsnachweis und Code-Signierung", fr: "Provenance de la chaîne d'approvisionnement et signature du code", it: "Provenienza della catena di fornitura e firma del codice", es: "Procedencia de la cadena de suministro y firma del código", pl: "Pochodzenie łańcucha dostaw i podpisywanie kodu", cs: "Prokazování původu v dodavatelském řetězci a podepisování kódu", pt: "Proveniência da cadeia de abastecimento e assinatura de código", ro: "Proveniența lanțului de aprovizionare și semnarea codului" },
      ],
      correctIndex: 1,
      explanation: {
        en: "SPDX was created at the Linux Foundation in 2010 to solve the open-source license compliance problem: tracking which licenses apply to which components and what obligations they create. It has grown to cover vulnerability management fields, but its original design is license-focused.",
        de: "SPDX wurde 2010 bei der Linux Foundation entwickelt, um das Open-Source-Lizenz-Compliance-Problem zu lösen: Welche Lizenzen gelten für welche Komponenten und welche Verpflichtungen entstehen daraus. Es wurde um Felder für das Schwachstellenmanagement erweitert, aber sein ursprünglicher Entwurf ist lizenzorientiert.",
        fr: "SPDX a été créé à la Linux Foundation en 2010 pour résoudre le problème de conformité des licences open source : savoir quelles licences s'appliquent à quels composants et quelles obligations elles créent. Il a évolué pour couvrir des champs de gestion des vulnérabilités, mais sa conception initiale est axée sur les licences.",
        it: "SPDX è stato creato presso la Linux Foundation nel 2010 per risolvere il problema della conformità delle licenze open source: tenere traccia di quali licenze si applicano a quali componenti e quali obblighi ne derivano. Si è ampliato per coprire campi di gestione delle vulnerabilità, ma la sua progettazione originaria è incentrata sulle licenze.",
        es: "SPDX se creó en la Linux Foundation en 2010 para resolver el problema de la conformidad de licencias de código abierto: rastrear qué licencias se aplican a qué componentes y qué obligaciones generan. Ha crecido hasta cubrir campos de gestión de vulnerabilidades, pero su diseño original se centra en las licencias.",
        pl: "SPDX powstał w Linux Foundation w 2010 roku, aby rozwiązać problem zgodności licencji open source: śledzenie, które licencje mają zastosowanie do których komponentów i jakie obowiązki z nich wynikają. Rozszerzono go o pola zarządzania podatnościami, ale jego pierwotny projekt jest skoncentrowany na licencjach.",
        cs: "SPDX vznikl v Linux Foundation v roce 2010, aby vyřešil problém souladu s licencemi open source: sledování, které licence se vztahují na které komponenty a jaké povinnosti z nich plynou. Rozrostl se o pole pro správu zranitelností, jeho původní návrh je však zaměřen na licence.",
        pt: "O SPDX foi criado na Linux Foundation em 2010 para resolver o problema da conformidade de licenças de código aberto: rastrear que licenças se aplicam a que componentes e que obrigações geram. Cresceu de modo a abranger campos de gestão de vulnerabilidades, mas a sua conceção original é centrada nas licenças.",
        ro: "SPDX a fost creat la Linux Foundation în 2010 pentru a rezolva problema conformității licențelor open source: urmărirea licențelor care se aplică fiecărei componente și a obligațiilor care decurg din ele. S-a extins pentru a acoperi câmpuri de gestionare a vulnerabilităților, dar proiectarea sa inițială este centrată pe licențe.",
      },
    },
    {
      id: "2.2.3",
      question: {
        en: "Which platform natively exports SPDX 2.3 JSON without requiring local tooling installation?",
        de: "Welche Plattform exportiert nativ SPDX 2.3 JSON ohne lokale Werkzeuginstallation?",
        fr: "Quelle plateforme exporte nativement du SPDX 2.3 JSON sans nécessiter l'installation d'outils locaux ?",
        it: "Quale piattaforma esporta nativamente SPDX 2.3 JSON senza richiedere l'installazione di strumenti locali?",
        es: "¿Qué plataforma exporta de forma nativa SPDX 2.3 JSON sin requerir la instalación de herramientas locales?",
        pl: "Która platforma natywnie eksportuje SPDX 2.3 JSON bez konieczności instalowania lokalnych narzędzi?",
        cs: "Která platforma nativně exportuje SPDX 2.3 JSON, aniž by vyžadovala instalaci lokálních nástrojů?",
        pt: "Que plataforma exporta nativamente SPDX 2.3 JSON sem exigir a instalação de ferramentas locais?",
        ro: "Ce platformă exportă nativ SPDX 2.3 JSON fără a necesita instalarea de instrumente locale?",
      },
      options: [
        { en: "Docker Hub", de: "Docker Hub", fr: "Docker Hub", it: "Docker Hub", es: "Docker Hub", pl: "Docker Hub", cs: "Docker Hub", pt: "Docker Hub", ro: "Docker Hub" },
        { en: "OWASP Dependency-Track", de: "OWASP Dependency-Track", fr: "OWASP Dependency-Track", it: "OWASP Dependency-Track", es: "OWASP Dependency-Track", pl: "OWASP Dependency-Track", cs: "OWASP Dependency-Track", pt: "OWASP Dependency-Track", ro: "OWASP Dependency-Track" },
        { en: "GitHub's dependency graph", de: "GitHubs Abhängigkeitsgraph", fr: "Le graphe de dépendances de GitHub", it: "Il grafo delle dipendenze di GitHub", es: "El grafo de dependencias de GitHub", pl: "Graf zależności GitHub", cs: "Graf závislostí GitHubu", pt: "O grafo de dependências do GitHub", ro: "Graful de dependențe al GitHub" },
        { en: "The NVD (National Vulnerability Database)", de: "Die NVD (National Vulnerability Database)", fr: "La NVD (National Vulnerability Database)", it: "La NVD (National Vulnerability Database)", es: "La NVD (National Vulnerability Database)", pl: "NVD (National Vulnerability Database)", cs: "NVD (National Vulnerability Database)", pt: "A NVD (National Vulnerability Database)", ro: "NVD (National Vulnerability Database)" },
      ],
      correctIndex: 2,
      explanation: {
        en: "GitHub's dependency graph exports SPDX 2.3 JSON from the repository API endpoint. This provides an SBOM without running any local tools, making it the fastest way to get started for teams with code on GitHub.",
        de: "GitHubs Abhängigkeitsgraph exportiert SPDX 2.3 JSON über den Repository-API-Endpunkt. Dies liefert eine SBOM ohne die Ausführung lokaler Werkzeuge und ist für Teams mit Code auf GitHub der schnellste Einstieg.",
        fr: "Le graphe de dépendances de GitHub exporte du SPDX 2.3 JSON depuis le point de terminaison de l'API du dépôt. Cela fournit une SBOM sans exécuter d'outils locaux, ce qui en fait le moyen le plus rapide de démarrer pour les équipes dont le code est sur GitHub.",
        it: "Il grafo delle dipendenze di GitHub esporta SPDX 2.3 JSON dall'endpoint API del repository. Questo fornisce una SBOM senza eseguire alcuno strumento locale, rendendolo il modo più rapido per iniziare per i team che hanno il codice su GitHub.",
        es: "El grafo de dependencias de GitHub exporta SPDX 2.3 JSON desde el punto de conexión de la API del repositorio. Esto proporciona una SBOM sin ejecutar ninguna herramienta local, lo que lo convierte en la forma más rápida de empezar para los equipos con código en GitHub.",
        pl: "Graf zależności GitHub eksportuje SPDX 2.3 JSON z punktu końcowego API repozytorium. Zapewnia to SBOM bez uruchamiania jakichkolwiek lokalnych narzędzi, co czyni go najszybszym sposobem na rozpoczęcie pracy dla zespołów z kodem na GitHub.",
        cs: "Graf závislostí GitHubu exportuje SPDX 2.3 JSON z koncového bodu API repozitáře. Tím poskytuje SBOM bez spuštění jakýchkoli lokálních nástrojů, což z něj činí nejrychlejší způsob, jak začít, pro týmy s kódem na GitHubu.",
        pt: "O grafo de dependências do GitHub exporta SPDX 2.3 JSON a partir do ponto de extremidade da API do repositório. Isto fornece um SBOM sem executar quaisquer ferramentas locais, o que o torna a forma mais rápida de começar para equipas com código no GitHub.",
        ro: "Graful de dependențe al GitHub exportă SPDX 2.3 JSON din punctul final al API-ului depozitului. Acesta oferă un SBOM fără a rula niciun instrument local, ceea ce îl face cea mai rapidă modalitate de a începe pentru echipele cu cod pe GitHub.",
      },
    },
    {
      id: "2.2.4",
      question: {
        en: "Both CycloneDX and SPDX satisfy the CRA Article 13(5) format requirement. What is the basis for this?",
        de: "Sowohl CycloneDX als auch SPDX erfüllen die Formatanforderung von CRA Artikel 13(5). Was ist die Grundlage dafür?",
        fr: "CycloneDX et SPDX satisfont tous deux à l'exigence de format de l'article 13(5) CRA. Sur quoi cela repose-t-il ?",
        it: "Sia CycloneDX che SPDX soddisfano il requisito di formato dell'articolo 13(5) CRA. Su che cosa si basa questo?",
        es: "Tanto CycloneDX como SPDX satisfacen el requisito de formato del artículo 13(5) CRA. ¿En qué se basa esto?",
        pl: "Zarówno CycloneDX, jak i SPDX spełniają wymóg formatu z artykułu 13(5) CRA. Na czym to się opiera?",
        cs: "CycloneDX i SPDX splňují požadavek na formát podle článku 13(5) CRA. Na čem se to zakládá?",
        pt: "Tanto o CycloneDX como o SPDX cumprem o requisito de formato do artigo 13(5) CRA. Em que se baseia isto?",
        ro: "Atât CycloneDX, cât și SPDX îndeplinesc cerința de format a articolului 13(5) CRA. Pe ce se bazează acest lucru?",
      },
      options: [
        { en: "Both are mandated by ENISA's SBOM technical guidelines", de: "Beide sind durch ENISAs technische SBOM-Leitlinien vorgeschrieben", fr: "Les deux sont imposés par les lignes directrices techniques SBOM de l'ENISA", it: "Entrambi sono imposti dalle linee guida tecniche SBOM dell'ENISA", es: "Ambos son exigidos por las directrices técnicas SBOM de la ENISA", pl: "Oba są wymagane przez wytyczne techniczne SBOM ENISA", cs: "Oba jsou nařízeny technickými pokyny ENISA pro SBOM", pt: "Ambos são impostos pelas orientações técnicas da ENISA sobre SBOM", ro: "Ambele sunt impuse de orientările tehnice ale ENISA privind SBOM" },
        { en: "Both are 'commonly used, machine-readable' formats — the exact words of Article 13(5)", de: "Beide sind 'allgemein verwendete, maschinenlesbare' Formate — die genauen Worte von Artikel 13(5)", fr: "Les deux sont des formats « couramment utilisés, lisibles par machine », les termes exacts de l'article 13(5)", it: "Entrambi sono formati « comunemente utilizzati, leggibili da una macchina », le parole esatte dell'articolo 13(5)", es: "Ambos son formatos « comúnmente utilizados, legibles por máquina », las palabras exactas del artículo 13(5)", pl: "Oba są formatami « powszechnie używanymi, odczytywalnymi maszynowo », czyli dokładnymi słowami artykułu 13(5)", cs: "Oba jsou formáty 'běžně používané, strojově čitelné', což jsou přesná slova článku 13(5)", pt: "Ambos são formatos 'comummente utilizados e legíveis por máquina', as palavras exatas do artigo 13(5)", ro: "Ambele sunt formate 'utilizate în mod curent, lizibile automat', exact cuvintele articolului 13(5)" },
        { en: "Both have been reviewed and certified by a notified conformity assessment body", de: "Beide wurden von einer notifizierten Konformitätsbewertungsstelle geprüft und zertifiziert", fr: "Les deux ont été examinés et certifiés par un organisme notifié d'évaluation de la conformité", it: "Entrambi sono stati esaminati e certificati da un organismo notificato di valutazione della conformità", es: "Ambos han sido revisados y certificados por un organismo notificado de evaluación de la conformidad", pl: "Oba zostały zweryfikowane i certyfikowane przez notyfikowaną jednostkę oceniającą zgodność", cs: "Oba byly přezkoumány a certifikovány oznámeným subjektem posuzování shody", pt: "Ambos foram analisados e certificados por um organismo notificado de avaliação da conformidade", ro: "Ambele au fost analizate și certificate de un organism notificat de evaluare a conformității" },
        { en: "Both are referenced by name in CRA Recital 41", de: "Beide werden namentlich in CRA Erwägungsgrund 41 genannt", fr: "Les deux sont mentionnés nommément dans le considérant 41 du CRA", it: "Entrambi sono menzionati per nome nel considerando 41 del CRA", es: "Ambos se mencionan por su nombre en el considerando 41 del CRA", pl: "Oba są wymienione z nazwy w motywie 41 CRA", cs: "Oba jsou jmenovitě uvedeny v bodě odůvodnění 41 CRA", pt: "Ambos são mencionados pelo nome no considerando 41 do CRA", ro: "Ambele sunt menționate cu numele în considerentul 41 al CRA" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Article 13(5) CRA requires the SBOM to be in a 'commonly used, machine-readable format.' Neither CycloneDX nor SPDX is named in the regulation. Both satisfy the requirement because both are widely used across hundreds of organisations and both are machine-parseable.",
        de: "Artikel 13(5) CRA verlangt, dass die SBOM in einem 'allgemein verwendeten, maschinenlesbaren Format' vorliegt. Weder CycloneDX noch SPDX wird in der Verordnung namentlich genannt. Beide erfüllen die Anforderung, weil beide von Hunderten von Organisationen genutzt werden und beide maschinell verarbeitbar sind.",
        fr: "L'article 13(5) CRA exige que la SBOM soit dans un « format couramment utilisé et lisible par machine ». Ni CycloneDX ni SPDX n'est nommé dans le règlement. Les deux satisfont à l'exigence parce qu'ils sont largement utilisés par des centaines d'organisations et que tous deux sont analysables par machine.",
        it: "L'articolo 13(5) CRA richiede che la SBOM sia in un « formato comunemente utilizzato e leggibile da una macchina ». Né CycloneDX né SPDX è nominato nel regolamento. Entrambi soddisfano il requisito perché sono ampiamente utilizzati da centinaia di organizzazioni ed entrambi sono analizzabili da una macchina.",
        es: "El artículo 13(5) CRA exige que la SBOM esté en un « formato comúnmente utilizado y legible por máquina ». Ni CycloneDX ni SPDX se nombra en el reglamento. Ambos satisfacen el requisito porque ambos se utilizan ampliamente en cientos de organizaciones y ambos son analizables por máquina.",
        pl: "Artykuł 13(5) CRA wymaga, aby SBOM był w « powszechnie używanym, odczytywalnym maszynowo formacie ». Ani CycloneDX, ani SPDX nie jest wymieniony w rozporządzeniu z nazwy. Oba spełniają ten wymóg, ponieważ oba są szeroko stosowane w setkach organizacji i oba są przetwarzalne maszynowo.",
        cs: "Článek 13(5) CRA vyžaduje, aby byl SBOM v 'běžně používaném, strojově čitelném formátu'. Ani CycloneDX, ani SPDX nejsou v nařízení jmenovitě uvedeny. Oba požadavek splňují, protože oba jsou široce používány ve stovkách organizací a oba jsou strojově zpracovatelné.",
        pt: "O artigo 13(5) CRA exige que o SBOM esteja num 'formato comummente utilizado e legível por máquina'. Nem o CycloneDX nem o SPDX são nomeados no regulamento. Ambos cumprem o requisito porque ambos são amplamente utilizados em centenas de organizações e ambos são processáveis por máquina.",
        ro: "Articolul 13(5) CRA impune ca SBOM să fie într-un 'format utilizat în mod curent, lizibil automat'. Nici CycloneDX, nici SPDX nu sunt numite în regulament. Ambele îndeplinesc cerința, deoarece ambele sunt utilizate pe scară largă în sute de organizații și ambele pot fi prelucrate automat.",
      },
    },
    {
      id: "2.2.5",
      question: {
        en: "If your primary driver is CRA Article 14 vulnerability reporting compliance, which format is the more natural fit and why?",
        de: "Wenn Ihr primäres Ziel die CRA-Artikel-14-Konformität beim Schwachstellenmeldewesen ist, welches Format passt besser und warum?",
        fr: "Si votre objectif principal est la conformité au signalement des vulnérabilités de l'article 14 CRA, quel format convient le mieux et pourquoi ?",
        it: "Se il vostro obiettivo principale è la conformità alla segnalazione delle vulnerabilità dell'articolo 14 CRA, quale formato è più adatto e perché?",
        es: "Si su objetivo principal es la conformidad con la notificación de vulnerabilidades del artículo 14 CRA, ¿qué formato es el más adecuado y por qué?",
        pl: "Jeśli Twoim głównym celem jest zgodność ze zgłaszaniem podatności z artykułu 14 CRA, który format jest bardziej odpowiedni i dlaczego?",
        cs: "Pokud je vaším hlavním cílem soulad s hlášením zranitelností podle článku 14 CRA, který formát se hodí lépe a proč?",
        pt: "Se o seu objetivo principal é a conformidade com a comunicação de vulnerabilidades do artigo 14 CRA, que formato é o mais adequado e porquê?",
        ro: "Dacă obiectivul dumneavoastră principal este conformitatea cu raportarea vulnerabilităților prevăzută la articolul 14 CRA, ce format este mai potrivit și de ce?",
      },
      options: [
        { en: "SPDX, because it is an ISO standard and ISO standards are preferred by market surveillance authorities", de: "SPDX, weil es ein ISO-Standard ist und ISO-Standards von Marktüberwachungsbehörden bevorzugt werden", fr: "SPDX, parce que c'est un standard ISO et que les standards ISO sont privilégiés par les autorités de surveillance du marché", it: "SPDX, perché è uno standard ISO e gli standard ISO sono preferiti dalle autorità di vigilanza del mercato", es: "SPDX, porque es un estándar ISO y los estándares ISO son preferidos por las autoridades de vigilancia del mercado", pl: "SPDX, ponieważ jest standardem ISO, a standardy ISO są preferowane przez organy nadzoru rynku", cs: "SPDX, protože je standardem ISO a standardy ISO orgány dozoru nad trhem preferují", pt: "O SPDX, porque é uma norma ISO e as normas ISO são preferidas pelas autoridades de fiscalização do mercado", ro: "SPDX, pentru că este un standard ISO, iar standardele ISO sunt preferate de autoritățile de supraveghere a pieței" },
        { en: "CycloneDX, because it was designed for vulnerability management, has native VEX support, and has more mature tooling (Grype, Dependency-Track) for the Article 14 monitoring loop", de: "CycloneDX, weil es für das Schwachstellenmanagement konzipiert wurde, native VEX-Unterstützung hat und reifere Werkzeuge (Grype, Dependency-Track) für den Artikel-14-Überwachungskreislauf bietet", fr: "CycloneDX, parce qu'il a été conçu pour la gestion des vulnérabilités, qu'il prend en charge VEX nativement et qu'il dispose d'un outillage plus mature (Grype, Dependency-Track) pour la boucle de surveillance de l'article 14", it: "CycloneDX, perché è stato progettato per la gestione delle vulnerabilità, supporta VEX in modo nativo e dispone di strumenti più maturi (Grype, Dependency-Track) per il ciclo di monitoraggio dell'articolo 14", es: "CycloneDX, porque se diseñó para la gestión de vulnerabilidades, tiene soporte nativo de VEX y cuenta con herramientas más maduras (Grype, Dependency-Track) para el bucle de supervisión del artículo 14", pl: "CycloneDX, ponieważ został zaprojektowany do zarządzania podatnościami, natywnie obsługuje VEX i dysponuje bardziej dojrzałymi narzędziami (Grype, Dependency-Track) do pętli monitorowania z artykułu 14", cs: "CycloneDX, protože byl navržen pro správu zranitelností, má nativní podporu VEX a má vyzrálejší nástroje (Grype, Dependency-Track) pro monitorovací smyčku podle článku 14", pt: "O CycloneDX, porque foi concebido para a gestão de vulnerabilidades, tem suporte nativo de VEX e dispõe de ferramentas mais maduras (Grype, Dependency-Track) para o ciclo de monitorização do artigo 14", ro: "CycloneDX, pentru că a fost conceput pentru gestionarea vulnerabilităților, are suport nativ pentru VEX și dispune de instrumente mai mature (Grype, Dependency-Track) pentru bucla de monitorizare prevăzută la articolul 14" },
        { en: "Neither — you must produce both formats to satisfy Article 14", de: "Keines — Sie müssen beide Formate produzieren, um Artikel 14 zu erfüllen", fr: "Aucun des deux : vous devez produire les deux formats pour satisfaire à l'article 14", it: "Nessuno dei due: dovete produrre entrambi i formati per soddisfare l'articolo 14", es: "Ninguno de los dos: debe producir ambos formatos para satisfacer el artículo 14", pl: "Żaden z nich: aby spełnić artykuł 14, musisz wytworzyć oba formaty", cs: "Žádný, k naplnění článku 14 musíte vyprodukovat oba formáty", pt: "Nenhum: tem de produzir ambos os formatos para cumprir o artigo 14", ro: "Niciunul: trebuie să produceți ambele formate pentru a îndeplini articolul 14" },
        { en: "SPDX, because its multi-format output (JSON, YAML, RDF) is required for ENISA's reporting platform", de: "SPDX, weil seine Multi-Format-Ausgabe (JSON, YAML, RDF) für ENISAs Meldeplattform erforderlich ist", fr: "SPDX, parce que sa sortie multi-format (JSON, YAML, RDF) est requise pour la plateforme de signalement de l'ENISA", it: "SPDX, perché il suo output multiformato (JSON, YAML, RDF) è richiesto per la piattaforma di segnalazione dell'ENISA", es: "SPDX, porque su salida multiformato (JSON, YAML, RDF) es necesaria para la plataforma de notificación de la ENISA", pl: "SPDX, ponieważ jego wieloformatowy wynik (JSON, YAML, RDF) jest wymagany dla platformy zgłoszeniowej ENISA", cs: "SPDX, protože jeho víceformátový výstup (JSON, YAML, RDF) je vyžadován pro hlásicí platformu ENISA", pt: "O SPDX, porque a sua saída multiformato (JSON, YAML, RDF) é exigida para a plataforma de comunicação da ENISA", ro: "SPDX, pentru că ieșirea sa în mai multe formate (JSON, YAML, RDF) este necesară pentru platforma de raportare a ENISA" },
      ],
      correctIndex: 1,
      explanation: {
        en: "CycloneDX was designed for security operations from the start. Its native VEX support lets you formally document 'not affected' decisions. Grype natively consumes CycloneDX and outputs CycloneDX vulnerability results. Dependency-Track is built around CycloneDX. For Article 14 compliance, this toolchain is more mature than the SPDX equivalent.",
        de: "CycloneDX wurde von Anfang an für Sicherheitsoperationen konzipiert. Die native VEX-Unterstützung ermöglicht die formale Dokumentation von 'not affected'-Entscheidungen. Grype verarbeitet nativ CycloneDX und gibt CycloneDX-Schwachstellenergebnisse aus. Dependency-Track ist auf CycloneDX aufgebaut. Für die Artikel-14-Compliance ist diese Werkzeugkette ausgereifter als das SPDX-Äquivalent.",
        fr: "CycloneDX a été conçu dès le départ pour les opérations de sécurité. Sa prise en charge native de VEX permet de documenter formellement les décisions « not affected ». Grype consomme nativement CycloneDX et produit des résultats de vulnérabilités au format CycloneDX. Dependency-Track est construit autour de CycloneDX. Pour la conformité à l'article 14, cette chaîne d'outils est plus mature que l'équivalent SPDX.",
        it: "CycloneDX è stato progettato fin dall'inizio per le operazioni di sicurezza. Il suo supporto nativo a VEX consente di documentare formalmente le decisioni « not affected ». Grype consuma nativamente CycloneDX e produce risultati di vulnerabilità in formato CycloneDX. Dependency-Track è costruito attorno a CycloneDX. Per la conformità all'articolo 14, questa catena di strumenti è più matura dell'equivalente SPDX.",
        es: "CycloneDX se diseñó desde el principio para las operaciones de seguridad. Su soporte nativo de VEX permite documentar formalmente las decisiones « not affected ». Grype consume de forma nativa CycloneDX y produce resultados de vulnerabilidades en formato CycloneDX. Dependency-Track está construido en torno a CycloneDX. Para la conformidad con el artículo 14, esta cadena de herramientas es más madura que el equivalente de SPDX.",
        pl: "CycloneDX został od początku zaprojektowany z myślą o operacjach bezpieczeństwa. Jego natywna obsługa VEX pozwala formalnie udokumentować decyzje « not affected ». Grype natywnie przetwarza CycloneDX i generuje wyniki podatności w formacie CycloneDX. Dependency-Track jest zbudowany wokół CycloneDX. Dla zgodności z artykułem 14 ten łańcuch narzędzi jest bardziej dojrzały niż odpowiednik SPDX.",
        cs: "CycloneDX byl od počátku navržen pro bezpečnostní provoz. Jeho nativní podpora VEX umožňuje formálně dokumentovat rozhodnutí 'not affected'. Grype nativně zpracovává CycloneDX a vydává výsledky zranitelností ve formátu CycloneDX. Dependency-Track je postaven kolem CycloneDX. Pro soulad s článkem 14 je tento řetězec nástrojů vyzrálejší než ekvivalent SPDX.",
        pt: "O CycloneDX foi concebido desde o início para as operações de segurança. O seu suporte nativo de VEX permite documentar formalmente decisões 'not affected'. O Grype consome nativamente CycloneDX e produz resultados de vulnerabilidades em formato CycloneDX. O Dependency-Track é construído em torno do CycloneDX. Para a conformidade com o artigo 14, esta cadeia de ferramentas é mais madura do que o equivalente SPDX.",
        ro: "CycloneDX a fost conceput de la început pentru operațiunile de securitate. Suportul său nativ pentru VEX permite documentarea formală a deciziilor 'not affected'. Grype consumă nativ CycloneDX și produce rezultate de vulnerabilități în format CycloneDX. Dependency-Track este construit în jurul CycloneDX. Pentru conformitatea cu articolul 14, acest lanț de instrumente este mai matur decât echivalentul SPDX.",
      },
    },
  ],
});

export default quiz;
