import { quizSchema } from "@/lib/training/schemas";

const quiz = quizSchema.parse({
  lessonId: "3.1",
  passingScore: 75,
  questions: [
    {
      id: "3.1.1",
      question: {
        en: "What is the key difference between source-time SBOM tools (like cdxgen) and image-scanning tools (like Syft)?",
        de: "Was ist der wesentliche Unterschied zwischen quellenbasierten SBOM-Werkzeugen (wie cdxgen) und Image-Scanning-Werkzeugen (wie Syft)?",
        fr: "Quelle est la différence essentielle entre les outils SBOM au niveau des sources (comme cdxgen) et les outils d'analyse d'images (comme Syft) ?",
        it: "Qual è la differenza fondamentale tra gli strumenti SBOM a livello di sorgente (come cdxgen) e gli strumenti di scansione delle immagini (come Syft)?",
        es: "¿Cuál es la diferencia clave entre las herramientas SBOM en el nivel de las fuentes (como cdxgen) y las herramientas de análisis de imágenes (como Syft)?",
        pl: "Jaka jest kluczowa różnica między narzędziami SBOM działającymi na poziomie źródła (jak cdxgen) a narzędziami skanującymi obrazy (jak Syft)?",
      },
      options: [
        { en: "Source-time tools only support CycloneDX, image-scanning tools only support SPDX", de: "Quellenbasierte Werkzeuge unterstützen nur CycloneDX, Image-Scanning-Werkzeuge nur SPDX", fr: "Les outils au niveau des sources ne prennent en charge que CycloneDX, les outils d'analyse d'images ne prennent en charge que SPDX", it: "Gli strumenti a livello di sorgente supportano solo CycloneDX, gli strumenti di scansione delle immagini supportano solo SPDX", es: "Las herramientas en el nivel de las fuentes solo admiten CycloneDX, las herramientas de análisis de imágenes solo admiten SPDX", pl: "Narzędzia na poziomie źródła obsługują tylko CycloneDX, narzędzia skanujące obrazy obsługują tylko SPDX" },
        { en: "Source-time tools read package manifests and produce full transitive application dependency graphs; image scanners examine built artifacts and find OS and runtime packages", de: "Quellenbasierte Werkzeuge lesen Paketmanifeste und erstellen vollständige transitive Anwendungsabhängigkeitsgraphen; Image-Scanner untersuchen erstellte Artefakte und finden OS- und Laufzeitpakete", fr: "Les outils au niveau des sources lisent les manifestes de paquets et produisent des graphes de dépendances applicatives transitifs complets ; les analyseurs d'images examinent les artefacts construits et trouvent les paquets du système d'exploitation et d'exécution", it: "Gli strumenti a livello di sorgente leggono i manifesti dei pacchetti e producono grafi completi delle dipendenze transitive dell'applicazione; gli scanner di immagini esaminano gli artefatti compilati e individuano i pacchetti del sistema operativo e di runtime", es: "Las herramientas en el nivel de las fuentes leen los manifiestos de paquetes y producen grafos completos de dependencias transitivas de la aplicación; los analizadores de imágenes examinan los artefactos compilados y encuentran los paquetes del sistema operativo y de tiempo de ejecución", pl: "Narzędzia na poziomie źródła odczytują manifesty pakietów i tworzą pełne tranzytywne grafy zależności aplikacji; skanery obrazów badają skompilowane artefakty i znajdują pakiety systemu operacyjnego oraz pakiety wykonawcze" },
        { en: "Image-scanning tools are more accurate for application dependencies because they see the actual binary", de: "Image-Scanning-Werkzeuge sind für Anwendungsabhängigkeiten genauer, weil sie das tatsächliche Binary sehen", fr: "Les outils d'analyse d'images sont plus précis pour les dépendances applicatives parce qu'ils voient le binaire réel", it: "Gli strumenti di scansione delle immagini sono più accurati per le dipendenze applicative perché vedono il binario effettivo", es: "Las herramientas de análisis de imágenes son más precisas para las dependencias de la aplicación porque ven el binario real", pl: "Narzędzia skanujące obrazy są dokładniejsze dla zależności aplikacji, ponieważ widzą rzeczywisty plik binarny" },
        { en: "Source-time tools require internet access; image-scanning tools work offline", de: "Quellenbasierte Werkzeuge benötigen Internetzugang; Image-Scanning-Werkzeuge arbeiten offline", fr: "Les outils au niveau des sources nécessitent un accès Internet ; les outils d'analyse d'images fonctionnent hors ligne", it: "Gli strumenti a livello di sorgente richiedono l'accesso a Internet; gli strumenti di scansione delle immagini funzionano offline", es: "Las herramientas en el nivel de las fuentes requieren acceso a Internet; las herramientas de análisis de imágenes funcionan sin conexión", pl: "Narzędzia na poziomie źródła wymagają dostępu do Internetu; narzędzia skanujące obrazy działają offline" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Source-time tools (cdxgen) read lock files like package-lock.json or pom.xml and produce the full transitive dependency graph. Image scanners (Syft) examine a built artifact — container image or directory — and identify packages from OS package databases and embedded language manifests. Neither is complete alone: combine both for full coverage.",
        de: "Quellenbasierte Werkzeuge (cdxgen) lesen Lock-Dateien wie package-lock.json oder pom.xml und erstellen den vollständigen transitiven Abhängigkeitsgraphen. Image-Scanner (Syft) untersuchen ein erstelltes Artefakt — Container-Image oder Verzeichnis — und identifizieren Pakete aus OS-Paketdatenbanken und eingebetteten Sprachmanifesten. Keines ist allein vollständig: Kombinieren Sie beide für vollständige Abdeckung.",
        fr: "Les outils au niveau des sources (cdxgen) lisent les fichiers de verrouillage comme package-lock.json ou pom.xml et produisent le graphe de dépendances transitif complet. Les analyseurs d'images (Syft) examinent un artefact construit, image de conteneur ou répertoire, et identifient les paquets à partir des bases de données de paquets du système d'exploitation et des manifestes de langage intégrés. Aucun n'est complet à lui seul : combinez les deux pour une couverture totale.",
        it: "Gli strumenti a livello di sorgente (cdxgen) leggono i file di lock come package-lock.json o pom.xml e producono il grafo completo delle dipendenze transitive. Gli scanner di immagini (Syft) esaminano un artefatto compilato, immagine di container o directory, e individuano i pacchetti dalle banche dati dei pacchetti del sistema operativo e dai manifesti di linguaggio incorporati. Nessuno dei due è completo da solo: combinateli entrambi per una copertura totale.",
        es: "Las herramientas en el nivel de las fuentes (cdxgen) leen archivos de bloqueo como package-lock.json o pom.xml y producen el grafo de dependencias transitivas completo. Los analizadores de imágenes (Syft) examinan un artefacto compilado, imagen de contenedor o directorio, e identifican los paquetes a partir de las bases de datos de paquetes del sistema operativo y los manifiestos de lenguaje incorporados. Ninguno es completo por sí solo: combine ambos para una cobertura total.",
        pl: "Narzędzia na poziomie źródła (cdxgen) odczytują pliki blokad, takie jak package-lock.json lub pom.xml, i tworzą pełny tranzytywny graf zależności. Skanery obrazów (Syft) badają skompilowany artefakt, obraz kontenera lub katalog, i identyfikują pakiety z baz danych pakietów systemu operacyjnego oraz osadzonych manifestów językowych. Żadne z nich nie jest kompletne samo w sobie: połącz oba, aby uzyskać pełne pokrycie.",
      },
    },
    {
      id: "3.1.2",
      question: {
        en: "When should SBOM generation be triggered in the build pipeline?",
        de: "Wann sollte die SBOM-Erstellung in der Build-Pipeline ausgelöst werden?",
        fr: "Quand la génération de la SBOM doit-elle être déclenchée dans le pipeline de build ?",
        it: "Quando dovrebbe essere attivata la generazione della SBOM nella pipeline di build?",
        es: "¿Cuándo debe activarse la generación de la SBOM en la canalización de compilación?",
        pl: "Kiedy należy uruchomić generowanie SBOM w potoku kompilacji?",
      },
      options: [
        { en: "Once per quarter, during a scheduled compliance review", de: "Einmal pro Quartal, während einer geplanten Compliance-Überprüfung", fr: "Une fois par trimestre, lors d'une revue de conformité planifiée", it: "Una volta al trimestre, durante una revisione di conformità pianificata", es: "Una vez por trimestre, durante una revisión de conformidad planificada", pl: "Raz na kwartał, podczas zaplanowanego przeglądu zgodności" },
        { en: "As part of every build that produces a release artifact — one SBOM per release, generated at build time", de: "Als Teil jedes Builds, der ein Release-Artefakt erzeugt — eine SBOM pro Release, zum Build-Zeitpunkt erstellt", fr: "Dans le cadre de chaque build qui produit un artefact de publication : une SBOM par version, générée au moment du build", it: "Come parte di ogni build che produce un artefatto di rilascio: una SBOM per ogni rilascio, generata al momento del build", es: "Como parte de cada compilación que produce un artefacto de publicación: una SBOM por cada versión, generada en el momento de la compilación", pl: "W ramach każdej kompilacji wytwarzającej artefakt wydania: jeden SBOM na wydanie, generowany w czasie kompilacji" },
        { en: "Only before a conformity assessment or audit", de: "Nur vor einer Konformitätsbewertung oder einem Audit", fr: "Uniquement avant une évaluation de la conformité ou un audit", it: "Solo prima di una valutazione della conformità o di un audit", es: "Solo antes de una evaluación de la conformidad o una auditoría", pl: "Tylko przed oceną zgodności lub audytem" },
        { en: "When the product's dependency tree changes by more than 10 percent", de: "Wenn der Abhängigkeitsbaum des Produkts um mehr als 10 Prozent wechselt", fr: "Lorsque l'arbre de dépendances du produit change de plus de 10 pour cent", it: "Quando l'albero delle dipendenze del prodotto cambia di oltre il 10 percento", es: "Cuando el árbol de dependencias del producto cambia en más del 10 por ciento", pl: "Gdy drzewo zależności produktu zmienia się o więcej niż 10 procent" },
      ],
      correctIndex: 1,
      explanation: {
        en: "The SBOM must reflect the exact component inventory of the released product. Manual or scheduled generation creates a gap between the SBOM and the actual artifact. Generating it as part of the build, from the same artifact, ensures accuracy and creates the audit trail the 10-year retention rule requires.",
        de: "Die SBOM muss das genaue Komponenteninventar des veröffentlichten Produkts widerspiegeln. Manuelle oder geplante Erstellung schafft eine Lücke zwischen der SBOM und dem tatsächlichen Artefakt. Die Erstellung als Teil des Builds aus demselben Artefakt gewährleistet Genauigkeit und schafft den Prüfpfad, den die 10-jährige Aufbewahrungspflicht erfordert.",
        fr: "La SBOM doit refléter l'inventaire exact des composants du produit publié. Une génération manuelle ou planifiée crée un écart entre la SBOM et l'artefact réel. La générer dans le cadre du build, à partir du même artefact, garantit l'exactitude et constitue la piste d'audit qu'exige la règle de conservation de 10 ans.",
        it: "La SBOM deve riflettere l'esatto inventario dei componenti del prodotto rilasciato. Una generazione manuale o pianificata crea una discrepanza tra la SBOM e l'artefatto effettivo. Generarla come parte del build, dallo stesso artefatto, garantisce l'accuratezza e costituisce la pista di controllo richiesta dalla regola di conservazione di 10 anni.",
        es: "La SBOM debe reflejar el inventario exacto de componentes del producto publicado. Una generación manual o planificada crea una brecha entre la SBOM y el artefacto real. Generarla como parte de la compilación, a partir del mismo artefacto, garantiza la exactitud y crea la pista de auditoría que exige la regla de conservación de 10 años.",
        pl: "SBOM musi odzwierciedlać dokładny inwentarz komponentów wydanego produktu. Ręczne lub zaplanowane generowanie tworzy rozbieżność między SBOM a rzeczywistym artefaktem. Generowanie go w ramach kompilacji, z tego samego artefaktu, zapewnia dokładność i tworzy ścieżkę audytu wymaganą przez zasadę przechowywania przez 10 lat.",
      },
    },
    {
      id: "3.1.3",
      question: {
        en: "How should the SBOM be linked to the release artifact it documents?",
        de: "Wie sollte die SBOM mit dem Release-Artefakt verknüpft werden, das sie dokumentiert?",
        fr: "Comment la SBOM doit-elle être liée à l'artefact de publication qu'elle documente ?",
        it: "Come dovrebbe essere collegata la SBOM all'artefatto di rilascio che documenta?",
        es: "¿Cómo debe vincularse la SBOM al artefacto de publicación que documenta?",
        pl: "Jak SBOM powinien być powiązany z artefaktem wydania, który dokumentuje?",
      },
      options: [
        { en: "By embedding the SBOM inside the binary", de: "Durch Einbettung der SBOM in die Binary", fr: "En intégrant la SBOM dans le binaire", it: "Incorporando la SBOM nel binario", es: "Incorporando la SBOM dentro del binario", pl: "Przez osadzenie SBOM w pliku binarnym" },
        { en: "By tagging the SBOM filename or metadata with the product version and build SHA, and attaching it as a release asset", de: "Durch Versehen des SBOM-Dateinamens oder der Metadaten mit der Produktversion und dem Build-SHA und Anhängen als Release-Asset", fr: "En étiquetant le nom de fichier ou les métadonnées de la SBOM avec la version du produit et le SHA de build, et en l'attachant comme ressource de publication", it: "Etichettando il nome del file o i metadati della SBOM con la versione del prodotto e lo SHA di build e allegandola come asset di rilascio", es: "Etiquetando el nombre de archivo o los metadatos de la SBOM con la versión del producto y el SHA de compilación, y adjuntándola como activo de la publicación", pl: "Przez oznaczenie nazwy pliku lub metadanych SBOM wersją produktu i SHA kompilacji oraz dołączenie go jako zasób wydania" },
        { en: "By storing the SBOM in a separate system that is accessed via the product serial number", de: "Durch Speicherung der SBOM in einem separaten System, auf das über die Produktseriennummer zugegriffen wird", fr: "En stockant la SBOM dans un système distinct accessible via le numéro de série du produit", it: "Archiviando la SBOM in un sistema separato a cui si accede tramite il numero di serie del prodotto", es: "Almacenando la SBOM en un sistema separado al que se accede mediante el número de serie del producto", pl: "Przez przechowywanie SBOM w osobnym systemie, do którego dostęp uzyskuje się za pomocą numeru seryjnego produktu" },
        { en: "By emailing the SBOM to the market surveillance authority at each release", de: "Durch Versenden der SBOM per E-Mail an die Marktüberwachungsbehörde bei jedem Release", fr: "En envoyant la SBOM par courriel à l'autorité de surveillance du marché à chaque publication", it: "Inviando la SBOM via e-mail all'autorità di vigilanza del mercato a ogni rilascio", es: "Enviando la SBOM por correo electrónico a la autoridad de vigilancia del mercado en cada publicación", pl: "Przez wysyłanie SBOM pocztą elektroniczną do organu nadzoru rynku przy każdym wydaniu" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Tagging the SBOM with the product version and build SHA creates the traceable link between the documentation and the artifact. Attaching it as a release asset (GitHub Release, GitLab artifact) keeps it co-located with the release. This is the foundation of the 10-year audit trail.",
        de: "Das Versehen der SBOM mit der Produktversion und dem Build-SHA schafft den nachvollziehbaren Link zwischen der Dokumentation und dem Artefakt. Das Anhängen als Release-Asset (GitHub Release, GitLab Artifact) hält es am selben Ort wie das Release. Dies ist die Grundlage des 10-jährigen Prüfpfads.",
        fr: "Étiqueter la SBOM avec la version du produit et le SHA de build crée le lien traçable entre la documentation et l'artefact. L'attacher comme ressource de publication (GitHub Release, artefact GitLab) la maintient au même emplacement que la publication. C'est le fondement de la piste d'audit de 10 ans.",
        it: "Etichettare la SBOM con la versione del prodotto e lo SHA di build crea il collegamento tracciabile tra la documentazione e l'artefatto. Allegarla come asset di rilascio (GitHub Release, artefatto GitLab) la mantiene nella stessa posizione del rilascio. È il fondamento della pista di controllo di 10 anni.",
        es: "Etiquetar la SBOM con la versión del producto y el SHA de compilación crea el vínculo rastreable entre la documentación y el artefacto. Adjuntarla como activo de la publicación (GitHub Release, artefacto de GitLab) la mantiene en la misma ubicación que la publicación. Es el fundamento de la pista de auditoría de 10 años.",
        pl: "Oznaczenie SBOM wersją produktu i SHA kompilacji tworzy możliwe do prześledzenia powiązanie między dokumentacją a artefaktem. Dołączenie go jako zasobu wydania (GitHub Release, artefakt GitLab) utrzymuje go w tym samym miejscu co wydanie. Jest to fundament dziesięcioletniej ścieżki audytu.",
      },
    },
    {
      id: "3.1.4",
      question: {
        en: "What does SBOM schema validation catch before the SBOM is stored?",
        de: "Was erkennt die SBOM-Schema-Validierung, bevor die SBOM gespeichert wird?",
        fr: "Que détecte la validation du schéma de la SBOM avant que celle-ci ne soit stockée ?",
        it: "Che cosa rileva la validazione dello schema della SBOM prima che la SBOM venga archiviata?",
        es: "¿Qué detecta la validación del esquema de la SBOM antes de que se almacene la SBOM?",
        pl: "Co wykrywa walidacja schematu SBOM, zanim SBOM zostanie zapisany?",
      },
      options: [
        { en: "Vulnerabilities in the listed components", de: "Schwachstellen in den aufgeführten Komponenten", fr: "Les vulnérabilités dans les composants répertoriés", it: "Le vulnerabilità nei componenti elencati", es: "Las vulnerabilidades en los componentes enumerados", pl: "Podatności w wymienionych komponentach" },
        { en: "Missing required fields, incorrect data types, and malformed PURLs", de: "Fehlende Pflichtfelder, falsche Datentypen und fehlerhafte PURLs", fr: "Les champs obligatoires manquants, les types de données incorrects et les PURL mal formées", it: "I campi obbligatori mancanti, i tipi di dati errati e le PURL malformate", es: "Los campos obligatorios ausentes, los tipos de datos incorrectos y las PURL malformadas", pl: "Brakujące pola wymagane, nieprawidłowe typy danych i źle sformułowane PURL" },
        { en: "Whether the SBOM complies with Article 13(5) CRA", de: "Ob die SBOM Artikel 13(5) CRA entspricht", fr: "Si la SBOM est conforme à l'article 13(5) CRA", it: "Se la SBOM è conforme all'articolo 13(5) CRA", es: "Si la SBOM cumple el artículo 13(5) CRA", pl: "Czy SBOM jest zgodny z artykułem 13(5) CRA" },
        { en: "Whether all components have valid open-source licenses", de: "Ob alle Komponenten gültige Open-Source-Lizenzen haben", fr: "Si tous les composants ont des licences open source valides", it: "Se tutti i componenti hanno licenze open source valide", es: "Si todos los componentes tienen licencias de código abierto válidas", pl: "Czy wszystkie komponenty mają ważne licencje open source" },
      ],
      correctIndex: 1,
      explanation: {
        en: "Schema validation using the CycloneDX CLI (or equivalent SPDX validator) checks that the SBOM document conforms to the format specification: required fields are present, data types are correct, PURLs are well-formed. It does not check vulnerability status or legal compliance.",
        de: "Die Schema-Validierung mit der CycloneDX CLI (oder einem gleichwertigen SPDX-Validator) prüft, ob das SBOM-Dokument der Formatspezifikation entspricht: Pflichtfelder sind vorhanden, Datentypen sind korrekt, PURLs sind wohlgeformt. Sie prüft weder den Schwachstellenstatus noch die rechtliche Compliance.",
        fr: "La validation du schéma à l'aide de la CycloneDX CLI (ou d'un validateur SPDX équivalent) vérifie que le document SBOM est conforme à la spécification du format : les champs obligatoires sont présents, les types de données sont corrects, les PURL sont bien formées. Elle ne vérifie ni le statut de vulnérabilité ni la conformité juridique.",
        it: "La validazione dello schema tramite la CycloneDX CLI (o un validatore SPDX equivalente) verifica che il documento SBOM sia conforme alla specifica del formato: i campi obbligatori sono presenti, i tipi di dati sono corretti, le PURL sono ben formate. Non verifica né lo stato di vulnerabilità né la conformità giuridica.",
        es: "La validación del esquema mediante la CycloneDX CLI (o un validador SPDX equivalente) comprueba que el documento SBOM se ajusta a la especificación del formato: los campos obligatorios están presentes, los tipos de datos son correctos, las PURL están bien formadas. No comprueba el estado de vulnerabilidad ni la conformidad jurídica.",
        pl: "Walidacja schematu za pomocą CycloneDX CLI (lub równoważnego walidatora SPDX) sprawdza, czy dokument SBOM jest zgodny ze specyfikacją formatu: pola wymagane są obecne, typy danych są poprawne, PURL są dobrze sformułowane. Nie sprawdza statusu podatności ani zgodności prawnej.",
      },
    },
    {
      id: "3.1.5",
      question: {
        en: "What is the benefit of signing an SBOM with a tool like Cosign?",
        de: "Was ist der Vorteil der Signierung einer SBOM mit einem Werkzeug wie Cosign?",
        fr: "Quel est l'avantage de signer une SBOM avec un outil comme Cosign ?",
        it: "Qual è il vantaggio di firmare una SBOM con uno strumento come Cosign?",
        es: "¿Cuál es la ventaja de firmar una SBOM con una herramienta como Cosign?",
        pl: "Jaka jest korzyść z podpisywania SBOM narzędziem takim jak Cosign?",
      },
      options: [
        { en: "It encrypts the SBOM so only the market surveillance authority can read it", de: "Es verschlüsselt die SBOM, sodass nur die Marktüberwachungsbehörde sie lesen kann", fr: "Elle chiffre la SBOM de sorte que seule l'autorité de surveillance du marché puisse la lire", it: "Cifra la SBOM in modo che solo l'autorità di vigilanza del mercato possa leggerla", es: "Cifra la SBOM de modo que solo la autoridad de vigilancia del mercado pueda leerla", pl: "Szyfruje SBOM tak, aby tylko organ nadzoru rynku mógł go odczytać" },
        { en: "It creates a chain of custody: cryptographic proof that the SBOM was produced at a specific point in time by your build system and has not been altered since", de: "Es schafft einen Prüfpfad: kryptografischen Nachweis, dass die SBOM zu einem bestimmten Zeitpunkt von Ihrem Build-System erstellt und seitdem nicht verändert wurde", fr: "Elle crée une chaîne de traçabilité : une preuve cryptographique que la SBOM a été produite à un moment précis par votre système de build et n'a pas été modifiée depuis", it: "Crea una catena di custodia: una prova crittografica che la SBOM è stata prodotta in un momento preciso dal vostro sistema di build e non è stata alterata da allora", es: "Crea una cadena de custodia: una prueba criptográfica de que la SBOM fue producida en un momento concreto por su sistema de compilación y no se ha alterado desde entonces", pl: "Tworzy łańcuch dowodowy: kryptograficzny dowód, że SBOM został wytworzony w określonym momencie przez Twój system kompilacji i nie został od tego czasu zmieniony" },
        { en: "It automatically submits the SBOM to ENISA for compliance registration", de: "Es übermittelt die SBOM automatisch an ENISA zur Compliance-Registrierung", fr: "Elle soumet automatiquement la SBOM à l'ENISA pour l'enregistrement de conformité", it: "Invia automaticamente la SBOM all'ENISA per la registrazione di conformità", es: "Envía automáticamente la SBOM a la ENISA para el registro de conformidad", pl: "Automatycznie przesyła SBOM do ENISA w celu rejestracji zgodności" },
        { en: "It validates the SBOM against the CycloneDX schema", de: "Es validiert die SBOM gegen das CycloneDX-Schema", fr: "Elle valide la SBOM par rapport au schéma CycloneDX", it: "Valida la SBOM rispetto allo schema CycloneDX", es: "Valida la SBOM con respecto al esquema CycloneDX", pl: "Waliduje SBOM względem schematu CycloneDX" },
      ],
      correctIndex: 1,
      explanation: {
        en: "A Cosign signature proves that the SBOM was generated by your build system (not modified after the fact) at a specific time. This chain of custody strengthens the evidentiary value of the SBOM in an Article 14 audit or a market surveillance authority review.",
        de: "Eine Cosign-Signatur beweist, dass die SBOM von Ihrem Build-System (nicht nachträglich modifiziert) zu einem bestimmten Zeitpunkt erstellt wurde. Dieser Prüfpfad stärkt den Beweiswert der SBOM in einem Artikel-14-Audit oder einer Überprüfung durch eine Marktüberwachungsbehörde.",
        fr: "Une signature Cosign prouve que la SBOM a été générée par votre système de build (sans modification ultérieure) à un moment précis. Cette chaîne de traçabilité renforce la valeur probante de la SBOM lors d'un audit au titre de l'article 14 ou d'un examen par une autorité de surveillance du marché.",
        it: "Una firma Cosign dimostra che la SBOM è stata generata dal vostro sistema di build (non modificata successivamente) in un momento preciso. Questa catena di custodia rafforza il valore probatorio della SBOM in un audit ai sensi dell'articolo 14 o in un esame da parte di un'autorità di vigilanza del mercato.",
        es: "Una firma de Cosign demuestra que la SBOM fue generada por su sistema de compilación (sin modificación posterior) en un momento concreto. Esta cadena de custodia refuerza el valor probatorio de la SBOM en una auditoría conforme al artículo 14 o en una revisión por parte de una autoridad de vigilancia del mercado.",
        pl: "Podpis Cosign dowodzi, że SBOM został wygenerowany przez Twój system kompilacji (bez późniejszej modyfikacji) w określonym momencie. Ten łańcuch dowodowy wzmacnia wartość dowodową SBOM podczas audytu na podstawie artykułu 14 lub przeglądu przez organ nadzoru rynku.",
      },
    },
  ],
});

export default quiz;
